### ISSUE TITLE
Custom notification sound discrepancy in parameters

### ISSUE THREAD

**Issue by cycl0psg** [home-assistant/iOS#1010]
**iOS device model, version and app version**
Model Name: iPhone 6s
Software Version: 13.6.1
App version: 2020.6 (14)

Model Name: MacBook Air (Retina, 13-inch, 2020)
Software Version: macOS Catalina 10.15.6 (19G2021)
App version: 2020.6 (14)

**Home Assistant Core Version**
0.114.4

On iPhone and iPad the notification service call requires the filename to be called including the file extension while on macOS the extension must be omitted otherwise the device will use the default notification sound

**Comment by zacwest** [comment]
Yes, this is annoying - but I wasn't able to find any way for us to work around it.

The sound playback is done by the system and it seems like macOS behaves differently than iOS here.

**Comment by zacwest** [comment]
Filed with Apple as FB8684715.

**Comment by zacwest** [comment]
I'm unable to get sounds from `~/Library/Sounds` to play at all under Big Sur. Might need to rethink if it's worth calling it out if it's not going to work there.

**Comment by zacwest** [comment]
Apple followed up on my radar - this is resolved in Big Sur Beta 9+; sounds both play, and support playing with or without extension. I think we can do a targeted workaround for Catalina that strips the .wav from the end for just that OS.

**Comment by zacwest** [comment]
The change above is deployed now, so it should behave the same for both iOS and macOS now.
