### ISSUE TITLE
Cannot edit files (set focus) in Visual Studio Code add-on

### ISSUE THREAD

**Issue by fi-sch** [home-assistant/iOS#1015]
**Device model, version and app version**
Model Name: MBP 13" 2020, iPhone 8
Software Version: macOS 10.15.6 Catalina, iOS 13.6.1
App version: 2020.6 (14), 2020.5.2 (1)

**Home Assistant Core Version**
0.114.4

**Describe the bug**
I'm not sure wether it is strictly bug in the macOS/iOS app or it's something with add-on itself.
Anyways, I'm not able to edit files using Visual Studio Code add-on. I just can't set focus / cursor position in VS Code.

**Expected behavior**
Ability to set cursor position and type.

**Comment by bgoncal** [comment]
Can't reproduce, please let me know if this is still an issue for you.
