### ISSUE TITLE
Location updates are really slow

### ISSUE THREAD

**Issue by niccolobusato** [home-assistant/iOS#1016]
**iOS device model, version and app version**

Model Name: iPhone X
Software Version: 13.7
App version: 2020.5.2(1)

**Home Assistant Core Version**

0.114.4
**Describe the bug**
Location updates are slow. I recieve the "welcome home" notification when i'm already inside my home from 20 minutes

sometimes does not even happen until i open the app and pull to refresh
**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by zacwest** [comment]
Can you provide any kind of event or detailed logs? It is likely this will be resolved by some of the region entering changes in 2020.6. You can give [the TestFlight](https://home-assistant.io/ios/beta) a try for that.

**Comment by danielbahl** [comment]
@zacwest I just want to dedicate a thank you for all the work you have put into the iOS version of Home Assistant, it has become a really awesome app that providers a truly complete experience all the way. **Great work**!

On topic: I am experiencing the same problem. It has occurred within the last few months, where our alarm no longer disables when we pass into the home zone - typically 1-3 minutes after we have returned home it registers and update the location.

Our zone is reasonably large, approx. 200m around the house, so it usually logs our entry way before we hit the driveway. The problems exist for both my wife and me. Both iPhone Xs running the latest iOS 13 and latest iOS 14 beta (now GM)

I will start testing the latest beta build and will report back if this has resolved the issue.

Thank you,
-db

**Comment by ntompson** [comment]
I've noticed a similar thing, although not 20 minutes slow. It's been happening the last few months. It used to be that my automation to turn the lights on when I get home triggered before I could even see the house. These days, it's quite common that I can get out of the car and walk to the door before it finally triggers. It's kind of a first world problem - it's not that bad of a delay for me, but I can certainly say that it is not as quick as it used to be. I'm using latest iOS 13.whatever on an iPhone Max XS.

**Comment by niccolobusato** [comment]
the app update does not have resolved the issue

**Comment by zacwest** [comment]
To diagnose your issue, we'll need to have some more information. Specifically useful will be logs from the device, which will happen for location events, in App Configuration > Event Log. What is logged when you expect to have your location updated, and what is logged later that causes your expectation to happen late?

**Comment by niccolobusato** [comment]
starting from the bottom w/ Relevant position change:

![image](https://user-images.githubusercontent.com/44100360/93807438-ea7c1000-fc4a-11ea-8344-e54114fc86a8.png)

then

![image](https://user-images.githubusercontent.com/44100360/93807521-0b446580-fc4b-11ea-94a2-a50d6b4580f1.png)


{"Entrato" means "Entered"}

**Comment by niccolobusato** [comment]
still having the same issues

**Comment by zacwest** [comment]
@niccolobusato I can help put this together if you [drop the full logs](https://www.dropbox.com/request/CtVWqILBXZ41tmFSGK2y) via the 'export log files' button underneath Event Log. To debug this issue, I mostly need:

- What timestamp is this occurring at?
- What was the GPS location sent at the time you expected to be in a certain zone?
- What is the center point and radius of that zone?

You can get the above via the Event Log (tap into each location item). Glancing at your screenshots above, I don't see anything obviously incorrect, so it's going to be in the details and not in the general overview.

**Comment by zacwest** [comment]
With recent app updates, location changes are generally more accurate than since this ticket was created. The latest app also features a Location History screen which allows exporting some debug information about the location update. If you run into location errors, please open a new ticket.
