### ISSUE TITLE
Microphone sensor - AirPods manufacturer attribute wrong

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/iOS#1018]
**Device model, version and app version**

Model Name: 
Software Version: macOS app / Big Sur beta
App version: 2020.6(14)

**Home Assistant Core Version**

0.115.0b9

**Describe the bug**
Not a big deal, but just noticed this and found it a bit weird. My AirPods show up as part of the microphone sensor. Yet the manufacturer says 4c instead of Apple Inc.

If you look at the unique ID at the very top you can see 4c in the mac address/bluetooth identifier or whatever, so maybe it's grabbing from that? I dunno. These are the first gen AirPods btw. 

![image](https://i.imgur.com/apM9vif.png)

**Expected behavior**
Say Apple Inc

**Comment by zacwest** [comment]
Can you connect them and go to System Information and tell me what the Audio section says is the manufacturer?

**Comment by SeanPM5** [comment]
Under Bluetooth -> Airpods screen on iOS:
Model A1523
Version 6.8.8

And here's the info from System Profiler on macOS. It shows up twice (I guess once for each side) and also says 4c... Weird. I guess this is a bug on Apple's side then, so it could be closed unless you wanna do some kind of workaround.

```
Sean’s AirPods:

  Default Input Device:	Yes
  Input Channels:	1
  Manufacturer:	4c
  Current SampleRate:	16000
  Transport:	Bluetooth
  Input Source:	Default
```

```
Sean’s AirPods:

  Default Output Device:	Yes
  Default System Output Device:	Yes
  Manufacturer:	4c
  Output Channels:	2
  Current SampleRate:	48000
  Transport:	Bluetooth
  Output Source:	Default


```

**Comment by zacwest** [comment]
I think I'd like to avoid a workaround if the system's reporting weird info. Not great, but I don't think '4c' means much to us enough to special case it.
