### ISSUE TITLE
'On the Fly' scenes visible in iOS actions

### ISSUE THREAD

**Issue by bluesheep** [home-assistant/iOS#1029]
I use a node-red flow to capture an 'on the fly' scene as per [these instructions](https://www.home-assistant.io/integrations/scene/#creating-scenes-on-the-fly)

The scene I create is visible within the iOS actions list as per the screenshot attached. It is not visible as a scene in HA.

![IMG_1180](https://user-images.githubusercontent.com/1271446/93450268-ad6ff080-f8cd-11ea-955d-444fbf93b6a7.PNG)

**Comment by zacwest** [comment]
There is a bug in 2020.5.x where scenes aren't cleaning up their actions when removed which will be resolved with 2020.6. That will make the symptoms of this a bit better.

We should be able to filter out transient scenes, or at least default their action creation to off, if it's part of their metadata.

**Comment by zacwest** [comment]
We can't tell the difference between `scene.create`-made scenes and yaml/config-made scenes. I think the fix I mentioned above that prevents the old ones from sticking around will be the best we can accomplish.
