### ISSUE TITLE
Crash when launching on older Catalina (10.15) versions

### ISSUE THREAD

**Issue by johnny5th** [home-assistant/iOS#1035]
**Device model, version and app version**
Model Name: MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)
Software Version: Version 10.15.3 (19D76)
App version: 2020.7 (1) Mac

**Home Assistant Core Version**
0.115.0

**Describe the bug**
Immediate crash

Process:               Home Assistant [22530]
Path:                  /Applications/Home Assistant.app/Contents/MacOS/Home Assistant
Identifier:            io.robbie.HomeAssistant
Version:               2020.7 (1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Home Assistant [22530]
User ID:               501

Date/Time:             2020-09-18 11:28:34.763 -0500
OS Version:            Mac OS X 10.15.3 (19D76)
Report Version:        12
Bridge OS Version:     4.2 (17P3050)
Anonymous UUID:        F2233EF1-4744-C0DC-4B08-82E4F18BCA62

Sleep/Wake UUID:       1D824955-8E60-4A49-97B6-FB0FDDB22A54

Time Awake Since Boot: 600000 seconds
Time Since Wake:       9100 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x4] Symbol missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Symbol not found: _OBJC_CLASS_$_SFAuthenticationSession
  Referenced from: /Applications/Home Assistant.app/Contents/MacOS/Home Assistant (which was built for Mac OS X 13.1)
  Expected in: /System/iOSSupport/System/Library/Frameworks/SafariServices.framework/Versions/A/SafariServices
 in /Applications/Home Assistant.app/Contents/MacOS/Home Assistant

**To Reproduce**
Open the app

**Expected behavior**
App Opens

**Additional context**
Downloaded from github, unzipped, moved tin Applications, and opened.

**Comment by zacwest** [comment]
There seems to be something with the earlier Catalina builds which is resolved in a later one. I may be able to work around it, but updating your macOS version definitely fixes it, too.

**Comment by johnny5th** [comment]
Would you like me to update to check or keep it where it is to test for you?

**Comment by zacwest** [comment]
I can spin up a VM with an older version to test, so feel free to upgrade!

**Comment by mann7774** [comment]
I have the same - Immediate crash.

Model Name: MacBook Air (13-inch, Mid 2012)
Software Version: Version 10.15.3 (19D76)

First piece of log:

Process:               Home Assistant [45039]
Path:                  /Applications/Home Assistant.app/Contents/MacOS/Home Assistant
Identifier:            io.robbie.HomeAssistant
Version:               2020.7 (1)
OS Version:            Mac OS X 10.15.3 (19D76)
...
Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x4] Symbol missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Symbol not found: _OBJC_CLASS_$_SFAuthenticationSession
  Referenced from: /Applications/Home Assistant.app/Contents/MacOS/Home Assistant (which was built for Mac OS X 13.1)
  Expected in: /System/iOSSupport/System/Library/Frameworks/SafariServices.framework/Versions/A/SafariServices
 in /Applications/Home Assistant.app/Contents/MacOS/Home Assistant
