### ISSUE TITLE
Make the macOS app available via `brew` package manager

### ISSUE THREAD

**Issue by kquinsland** [home-assistant/iOS#1039]
**Is your feature request related to a problem? Please describe.**
This is not related to performance or bugs. This is purely a 'quality of life' request.

**Describe the solution you'd like**

I would like to see the macOS app distributed through the [homebrew package manager](https://brew.sh/). It's a wonderful package manager that makes is easy to install and - if the app allows it - update applications in a manor that's identical to the package managers from the *nix world.

I would like to be able to run:

```
me@some-host$ brew install home-assistant
```

and have the `home-assistant.app` fetched and put on my system. Ideally, any updates would also be installed with a `brew update`.

**Additional context**

the `brew` tool works by cloning git repos. Each repo has metadata about the application, where to fetch it from, how to validate it and anything else needed for automated install/remove/update.  For example, there is a CLI tool for working w/ the akamai APIs. The file that tells `brew` how to install / manage the `akamai` tool is [here](https://github.com/Homebrew/homebrew-core/blob/master/Formula/akamai.rb)

To [implement this request](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap), a few components need to be set up:

0. A repo that has the metadata set up for the applications in question. a *dedicated* repo is nice, but not required. This existing repo would work.

1. When a new macOS app is built, the repo containing release info needs to be updated. This process is relatively trivial to automate with github actions. There are _several_ implementations that can automate this process.

- https://github.com/marketplace/actions/homebrew-tap
- https://github.com/garden-io/update-homebrew-action
- https://github.com/marketplace/actions/bump-homebrew-formula

Happy to discuss further and answer any questions.  I'm not an osxDev so i'm a bit in. the dark about how the app is currently built and what the current approach is for determining when a release should be cut.  But once a release has been cut, it's easy to get that release added to brew.

**Comment by zacwest** [comment]
Implemented externally, thanks!

**Comment by kquinsland** [comment]
Wonderful! Thanks for getting this done so quick! 

Can confirm things are working :

```
$ brew cask install home-assistant
Updating Homebrew...
==> Auto-updated Homebrew!
==> New Casks
home-assistant                                                                          nova
==> Downloading https://github.com/home-assistant/iOS/releases/download/mac/2020.7/1/home-assistant-mac.zip
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/55336932/4ddafc00-f85f-11ea-867e-f52d4e3ea7a1?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Crede
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'home-assistant'.
==> Installing Cask home-assistant
🍺  home-assistant was successfully installed!
```
