### ISSUE TITLE
App does not remember the window size

### ISSUE THREAD

**Issue by domoritz** [home-assistant/iOS#1040]
**Device model, version and app version**

Software Version: macOS 11
App version: 2020.7 (1)

**Describe the bug**

The window does not remember the window size across closing/opening the app. 

**To Reproduce**

* Resize window
* Close app
* Open app again

**Expected behavior**

The window should remember its previous size.

**Comment by zacwest** [comment]
Do you have System Preferences > General > "Close windows when quitting an app" enabled?

**Comment by domoritz** [comment]
Yes, I do.

**Comment by SeanPM5** [comment]
Had the same behavior here since a few builds, I thought it was just me. It was always opening in the top left of the screen in like a 600px window.

That "Close windows when quitting an app" option was on for me (never changed it), after unchecking it it's now remembering the window size.

Also on macOS 11 / Big Sur PB.

**Comment by zacwest** [comment]
Multi-window support means it's now persisting information about the windows when quitting, and if there are none, it doesn't have anything. I need to investigate if the Catalyst side of things will allow us to manually do so.

**Comment by carsten-h** [comment]
The option "System Preferences > General > "Close windows when quitting an app"" is not longer there and the positions are not saved!
This information is for Home Assistant Companion 2021.1 (1).

**Comment by zacwest** [comment]
<img width="780" alt="image" src="https://user-images.githubusercontent.com/74188/103182395-d22a1b80-485f-11eb-93a2-eaee76952806.png">

**Comment by carsten-h** [comment]
Oh, you are right, I totally read over "System"!

**Comment by wojciechpolak** [comment]
I unchecked the system option "Close windows when quitting an app" and now when I quit the HA desktop app v2021.1.1 (9) it remembers its custom window size & position. However, when I click the top-left red circle close button it closes the app without quitting it AND THEN when I click the app again from the dock, its previous window size & position is gone and reset back to default.

**Comment by skrenes** [comment]
I have my app setup with the "Menu Bar" option. Whenever I close the window and then tap the menu bar icon, it goes back to the default small window size centered on my first display.
<img src="https://user-images.githubusercontent.com/5075909/113428730-8cb44780-9394-11eb-8f78-9dbc4096af83.png" width="50%">

**Comment by matthew-larner** [comment]
"System Preferences > General > "Close windows when quitting an app" isn't the best way to handle this issue. It should remember the window size and position when closing the window irrespective of this setting.

**Comment by zacwest** [comment]
Perhaps, but a lot of this behavior comes from how Apple has decided Catalyst apps should work. It is possible to change this behavior by rewriting the app or substantially hackily overriding the default behavior (hence why this issue is still open) but this would be both a lot of work or an unsafe, short-term change due to the changes required.

**Comment by melyux** [comment]
Please consider fixing this, it makes using this app so aggravating. Command + Q works to keep the window size the next time, but the red X resets it every single time. Maybe you can make the app quit upon pressing the red X so a Command + Q isn't required.

**Comment by Bat-Maniac** [comment]
> Please consider fixing this, it makes using this app so aggravating. Command + Q works to keep the window size the next time, but the red X resets it every single time. Maybe you can make the app quit upon pressing the red X so a Command + Q isn't required.

You could use command +  H. That does the job for me. The app window size won't change back to default after reopening, but the service remains running.

But in general the app should remember its window size like allmost every other app does.

**Comment by skrenes** [comment]
I used to use command+h, but the trouble is periodically pops up out of nowhere, especially when I'm opening/closing windows in another application. It's very bizarre. Even if it could be set to maximize on the display it's on, that would be a huge improvement.

**Comment by sdschramm** [comment]
Is there really no fix for this after 2+ years? The lack of such a basic feature annoys me so much that I end up using HA in my browser.

**Comment by AykutCevik** [comment]
First of all thank you for the app! It is a great addition!
But I agree with all here:
>But in general the app should remember its window size like allmost every other app does.

It is really annoying to resize the window everytime. I can't disable the option "Close windows when quitting an app" since other apps like the Terminal behave totally different then. Other than that the HA app is the only app which shows me this behaviour on my system.
Is there a plannen fix for this?

**Comment by technotiger** [comment]
There seems to be an easy fix using _SceneDelegate_ and _GeometryPreferences_.

It is described in these articles: [[1]](https://www.vbutko.com/articles/how-to-preserve-user-preferred-window-size-in-mac-catalyst-apps) [[2]](https://fpposchmann.de/restore-window-size-on-maccatalyst-apps/).

**Comment by bgoncal** [comment]
> There seems to be an easy fix using _SceneDelegate_ and _GeometryPreferences_.
> 
> It is described in these articles: [[1]](https://www.vbutko.com/articles/how-to-preserve-user-preferred-window-size-in-mac-catalyst-apps) [[2]](https://fpposchmann.de/restore-window-size-on-maccatalyst-apps/)

Implemented the proposed solution:
https://github.com/home-assistant/iOS/pull/2514

**Comment by cafferata** [comment]
@bgoncal I tested (with TestFlight build) the restore mac window size https://github.com/home-assistant/iOS/pull/2514 in combination with 'the red X' and `Command + Q`. This works very well with 1 Home Assistant server. However, with two Home Assistant servers (both open), only 1 will be reopened. Is this issue in scope for this GitHub issue?

**Comment by bgoncal** [comment]
> @bgoncal I tested (with TestFlight build) the restore mac window size #2514 in combination with 'the red X' and `Command + Q`. This works very well with 1 Home Assistant server. However, with two Home Assistant servers (both open), only 1 will be reopened. Is this issue in scope for this GitHub issue?

Can you open a new issue to keep track of this?

**Comment by cafferata** [comment]
> Can you open a new issue to keep track of this?

Sure, no problem at all. ☺️
