### ISSUE TITLE
WebView window is slightly blurry

### ISSUE THREAD

**Issue by zacwest** [home-assistant/iOS#1041]
I think the fix in #996 is making the text _slightly_ blurry, since it's doing two scaling operations to counteract each other. It may be appropriate to use some private API to get the scene's NSView to be _forced_ to be 1.0 scale so we don't need to apply any modifiers.

**Comment by ntompson** [comment]
Hi Zac - I've noticed the same thing. Putting the new app side by side with HA viewed through Chrome, it is quite a noticeable difference. Noticeable on icons and Grafana charts as well.

**Comment by fi-sch** [comment]
It's still blurry for me after latest update

**Comment by johnwarne** [comment]
It's still blurry for me as well. It gets more pronounced if your Page Zoom level is other than the default 100% setting.
