### ISSUE TITLE
App doesn't remember last page

### ISSUE THREAD

**Issue by kersten-lohmeyer** [home-assistant/iOS#1052]
Everytime I launch the app it starts with the Settings -> Info page of HA. No matter if I left the app when my dashboard was active. Remember last page is checked in settings.

iOS version: 14.0
HA version: 0.115.2
App version: 2020.6.1 (2)

**Comment by zacwest** [comment]
The only situation I can think of that would prevent this from working is if the app is force-quit rather than allowing the system to kill it when it desires. The system uses the force quit as a signal that it should throw away the saved information in case it's causing a problem.

**Comment by kersten-lohmeyer** [comment]
Shouldn't this information be saved at the time I switch to another page? So you're basically saying I need to leave the app in the background for this feature to work?

**Comment by zacwest** [comment]
Sorry, I missed your response. Correct; force quitting the app is not normal behavior, and it's the signal of "something is wrong" and the system uses that to discard anything like saved states. [You do not need to force quit applications regularly](https://daringfireball.net/2017/07/you_should_not_force_quit_apps).
