### ISSUE TITLE
High processor load MacOS app

### ISSUE THREAD

**Issue by MrUserY** [home-assistant/iOS#1055]
Hi, I did a clean install of Catalina to try out the HomeAssistant MacOS app (nice!) but it is causing a hight processor load, fans spinning hard.

**Device model, version and app version**

Model Name: Macbook Pro 15" 2015
Software Version: OSX Cataline 10.15.6
App version: 2020.7

**Home Assistant Core Version**

0.115.1

**Describe the bug**
High processor load.

**To Reproduce**
Not shure. I was editing the Lovelace in Firefox browser at the same time.

**Expected behavior**
Normal processor load

**Screenshots**

<img width="941" alt="Schermafbeelding 2020-09-20 om 11 46 59" src="https://user-images.githubusercontent.com/48710822/93708617-017e0d80-fb38-11ea-8bd6-74bf7141f0c7.png">

**Additional context**

Probably guessinng what it is. Do you want a dump of the process?

**Comment by Stooovie** [comment]
HA behaves like this when Content blockers are enabled for its website. The Mac app looks like a simple web view wrapper, so I´d say it´s the same issue.

**Comment by MrUserY** [comment]
Hmm but I don’t have content blockers on Safari. Since I always use Firefox.

To be clear. After closing Firefox. The HA MacOs app is still blowing the fans.

Is there a dummy way to find out what’s exactly causing it? Probably not...


Op 20 sep. 2020 om 12:09 heeft Stooovie <notifications@github.com> het volgende geschreven:

﻿
HA behaves like this when Content blockers are enabled for its website. The Mac app looks like a simple web view wrapper, so I´d say it´s the same issue.

**Comment by zacwest** [comment]
If you launch the website in Safari on your Mac, does the same CPU usage issue occur?

**Comment by MrUserY** [comment]
No and it is not always running like this. It just happend once. I made a dump of the process before quitting the app. Is it of any use? I actually don't know if the dump contains personal information.

We'll maybe this post will lead to nothing. I just wanted to mention it's a clean install, and the app spinned the mac to high processor load, but dunnow why. Just to let you know. If I have any clue why I'll let ya know. Maybe close this issue...?

**Comment by zacwest** [comment]
A profile of it would be useful, and likely only contains the backtraces of the methods being run, so it's just what the app was doing, not what it was doing it on. Given that this is exclusively the WebKit view, I don't believe it'll end up being something the iOS app can help improve, but it might be useful to file an issue with the frontend if you can reproduce it at all.

**Comment by MrUserY** [comment]
Well and if it inludes personal info it won't be relevant anymore because I did another clean install again :-) So here it is! A dump of the proces on the moment I had a high processing load from the MacOS app. I hope it's useful.

[Momentopname van com.apple.WebKit.WebContent.txt](https://github.com/home-assistant/iOS/files/5258010/Momentopname.van.com.apple.WebKit.WebContent.txt)

**Comment by dmatora** [comment]
I'm still experiencing this (I think I always was)
Plus in the app clipboard doesn't work for most of the stuff
