### ISSUE TITLE
Window minimum width too wide

### ISSUE THREAD

**Issue by markcocker** [home-assistant/iOS#1056]
**Device model, version and app version**
Model Name: macOS Catalina 
Software Version: version 10.15.6
App version: 2020.7 (1)

**Home Assistant Core Version**
0.115.2

**Describe the bug**
I cannot resize the window to be less in heigh or width than show in the screenshot below..

**To Reproduce**
Open the Home Assistant App, try to reduce the width or heigh to less than show in the screenshot.

**Expected behavior**
I should be able to set the window height + width to be very narrow, similar to a Firefox/Chrome browser.

**Screenshots**
<img width="634" alt="Screenshot 2020-09-20 at 10 57 42" src="https://user-images.githubusercontent.com/15351000/93708756-ae548c80-fb30-11ea-8e68-6dc184c91e56.png">

**Additional context**
I typically show Home Assistant on screen all day with zoom set to 75% and a narrow window, for example using FIrefox:
<img width="445" alt="Screenshot 2020-09-20 at 11 07 00" src="https://user-images.githubusercontent.com/15351000/93708869-a1846880-fb31-11ea-8bcd-961f04415ba2.png">

**Comment by zacwest** [comment]
OS | App | Width (pts) | Height (pts)
-- | -- | -- | --
Catalina | Home Assistant | 596 | 615
  | Safari | 507 | 270
Big Sur | Home Assistant | 514 | 320
  | Safari | 575 | 283
