### ISSUE TITLE
Carplay critical notification, tap action feature

### ISSUE THREAD

**Issue by niccolobusato** [home-assistant/iOS#1057]
**Is your feature request related to a problem? Please describe.**

we are able to show notifications on carplay head unit with critical notifications but we can't interact with theme in any mode.. 
**Describe the solution you'd like**

cool be amazing to add an action and he recognize when a notification is opened on carplay head unit to trigger other actions

**Additional context**

**Comment by bagobones** [comment]
Would be cool to prompt to open the garage door via carplay every time you arrive home.

**Comment by niccolobusato** [comment]
yes i will use to ring the doorbell automatically and open the gate, turn on porch light at night when i'm back ecc

**Comment by zacwest** [comment]
Actions showing up in CarPlay, according to Apple's docs, requires the app being approved for CarPlay overall. This is unlikely to be doable since Home Assistant is not in the allowed list of CarPlay app types: Audio, Automaker, Communication, EV Charging, Navigation, Parking, Quick Food Ordering.
