### ISSUE TITLE
Apple Watch app crashes on series 3 watchOS 7

### ISSUE THREAD

**Issue by Cell-NL** [home-assistant/iOS#1058]
- The Apple Watch app closes automatically after opening. After starting the loading animation shows, then it directly closes.  
- The Home Assistant house icon is disappearing and not showing in complications anymore. 

It's still possible to trigger actions from IOS14 widget on iPhone XR. The issues above were already present on WatchOS6. 

Apple Watch Series 3 WatchOS 7
IOS App version 2020.6.1
Home Assistant 0.115.2
HassOS 4.13

**Comment by zacwest** [comment]
Can you retrieve a crash log on the iPhone from: Settings > Privacy > Analytics > Analytics Data? It should start with either "Home Assistant" or "WatchApp"

**Comment by Cell-NL** [comment]
> Can you retrieve a crash log on the iPhone from: Settings > Privacy > Analytics > Analytics Data? It should start with either "Home Assistant" or "WatchApp"

[WatchAppExtension-2020-09-19-010749.txt](https://github.com/home-assistant/iOS/files/5252235/WatchAppExtension-2020-09-19-010749.txt)

**Comment by jodiswhw** [comment]
Hi, have exactly the same issue.
Just a comment to the topic:
 _The Home Assistant house icon is disappearing and not showing in complications anymore._
It is not showing, but you can click on the empty field and the App try to start again. However it directly coloses after starting.

Apple Watch Series 3 watchOS7
IOS App version 2020.6.1 (2)
Home Assistant 0.115.2
Docker

**Comment by ekkesa** [comment]
Same issue here. Also found this thread on the [forum](https://community.home-assistant.io/t/ios14-apple-watch-app-stopped-working/228250/4)

**Comment by zacwest** [comment]
Based on the comment thread in realm/realm-cocoa#6682 I believe we can work around this crash by compiling with 'dead code stripping' disabled. This may bloat the binary size, so perhaps we can do it for the watch targets only.

**Comment by zacwest** [comment]
2020.6.2 is rolling out now, please give it a try and see if it resolves the issue.

**Comment by gitmirko** [comment]
I had the same issue and can confirm that now it is fixed. Thank you.

**Comment by Cell-NL** [comment]
> 2020.6.2 is rolling out now, please give it a try and see if it resolves the issue.

Yes! Crashing issue is resolved. 

The complication icon is still missing though. See upper right complication in screenshot. 
![67C6CB27-3189-457B-887E-1C17D92DAB95](https://user-images.githubusercontent.com/63556180/94304955-b8cbb780-ff70-11ea-8458-81a5702bd2db.png)

**Comment by TomBrien** [comment]
The upper left appears to be a gauge ring? If so you may not have normalised the value to 1 which can cause the complication to fail
