### ISSUE TITLE
Home Assistant app shows blank white screen on repeated launch

### ISSUE THREAD

**Issue by offbyone** [home-assistant/iOS#1071]
**iOS device model, version and app version**

Model Name: iPhone 11 Pro
Software Version: iOS 14.0
App version: 2020.6.1

**Home Assistant Core Version**

0.115.2

**Describe the bug**
The Home Assistant iOS app opens, and briefly flickers the "orange +" before turning into a white screen. You can see this behaviour in the attached screen capture.

**To Reproduce**
Open the app. This is true whether I force-close the app or not.

**Expected behavior**
The app should show a dashboard. 

**Screenshots**

![hass-bug](https://user-images.githubusercontent.com/181693/93848469-7b101b80-fc5e-11ea-815c-caa1243e453a.gif)

**Additional context**

I removed (disabled? It's not really clear, since it was never specifically _defined_ in config anywhere I could find) the default generated dashboard.  I don't know if that's related -- I don't use the app a lot, so I've made other changes between then and now too.

**Comment by offbyone** [comment]
FWIW I tried the last-ditch option too, and deleted the app and re-installed it. It's doing the same thing after, only with a dark screen for some reason.

**Comment by offbyone** [comment]
Things that have partially worked:

1. I went to airplane mode, and then was able to access settings from the error bar that popped up
2. In settings, I eventually tried a full reset of the app
3. The reset walked me through the complete setup dialog... and then promptly put me back into the blank screen scenario

**Comment by offbyone** [comment]
I don't know what the issue is in detail but if I wipe out my dashboard configuration completely, and then literally just re-add it... the app works now. No clue.

**Comment by michalk-k** [comment]
After waiting a bit on white screen (not shown on animation above), message "connection time out" occures

**Comment by zacwest** [comment]
The symptoms here do not sound like the app but the frontend. Can you try opening your HA instance in Safari and see what the result is? The orange gear will disappear once we successfully load and talk to the frontend, so it makes me think that there's something at issue rendering it.

Temporarily disabling (to test) any custom integrations might be a helpful for debugging as well.

**Comment by michalk-k** [comment]
yes. At time of having the problem frontend was opening properly using nabu casa url copied directly from app options.

Intresting is, in my case the app started to work half a day later while I did nothing. just did run it on evening again and it was just working. I have no idea why it didn't work at first time.

**Comment by offbyone** [comment]
@zacwest for my part, on the web frontend, yeah, my default dashboard / overview was blank. However, I could see all my other dashboards in the sidebar, and they all worked. On the app, I was never able to see a list of dashboards or a menu affordance to select them.

**Comment by zacwest** [comment]
The header is also part of the frontend, so that makes sense. Depending on what is going wrong, you can also pull from the left edge of the screen towards the right to open up the menu.

**Comment by michalk-k** [comment]
@zacwest when it was failing for me, pulling the menu was not possible.

**Comment by bkr1969** [comment]
I have had similar problems since the last update. I’ve tried deleting and reinstalling the app several times. I’m given an external URL as my local IP address which I copy into the internal URL field. I am never given the “switch” for connecting via remote that all the guides mention. No matter what is in this field I cannot connect remotely. If I try to manually enter my Nabu address I get an error that says it will be detected automatically and I cannot (do not need to) enter it. I have tried leaving the external URL field blank, leaving it as the internal address and even using the Nabu address in the internal URL field during setup (which it won’t let me do) but no matter what, I cannot connect remotely with the app. The Nabu address works fine in a browser. Does anyone have any idea how to get the app working again (as it was just 3 weeks ago)?

**Comment by zacwest** [comment]
@bkr1969 what version of the app? What URLs were you using to connect before enabling cloud? Do they still work in the browser?

**Comment by bkr1969** [comment]
I am using version 2021.1.5 on the app. Cloud has always been enabled. I have my local IP address and a Nabu Casa address for remote connection. I can connect with Nabu through a browser just fine. Remote UI is enabled in HA. Still no remote connection via the app.

**Comment by zacwest** [comment]
That sounds like the HA Core version. Can you double check the app one in App Configuration > About (at the top)?

Does the internal URL still work?

**Comment by bkr1969** [comment]
Hmmm...didn’t realize it would list the other.
2021.1.1 (9)

**Comment by bkr1969** [comment]
Internal URL works fine when at home

**Comment by zacwest** [comment]
@bkr1969 I am not sure why it is not picking up the cloud status, but toggling it off and on or restarting HA seems to make it get picked up again in the future. For the next release, I just removed the check that disallows entering nabu.casa manually, so if you don't want to fiddle with it and you know the hostname works, you can grab the [latest beta](https://home-assistant.io/ios/beta) and give that a try.

**Comment by bkr1969** [comment]
Ok...I downloaded the beta and entered the Nabu URL. I got an error the first time (attached image) but when I edited it by taking of the “/lovelace/default_view” at the end of the URL it worked perfectly. I hope this helps. Thanks for helping me get this working. 

Brian

**Comment by frenkie1234** [comment]
Same here in the Netherlands Did work fine until update 🥺. Can connect with local or external ip adres on the iPhone 7 but on a iPhone 8 it works just fine Maybe a screen program issue?

**Comment by cetooapp** [comment]
Same issue here. No problem on Android.

**Comment by flowchartsman** [comment]
New user here, running into this bug on multiple devices. Very frustrating having to either refresh or restart the app every time. Any data I can provide?

**Comment by TomBrien** [comment]
This is probably now a different issue which is tracked in #1801

**Comment by scottrhoyt** [comment]
For those of you experiencing a blank mobile app due to a front end rendering problem: https://github.com/home-assistant/iOS/issues/2259#issuecomment-1336248185

**Comment by davet2001** [comment]
> For those of you experiencing a blank mobile app due to a front end rendering problem: https://github.com/home-assistant/iOS/issues/2259#issuecomment-1336248185

Yes, I had this problem, and the fix above worked for me, but it's a really bad user experience IMO. Completely blank page with no error basically looks like it's broken, and this only ever occurs for me on the iOS app (never in the browser).

Is there any way of catching the problem of 'the page we tried to render was empty', and at least displaying an error? Even better to retry a safe URL within the HA instance?
