### ISSUE TITLE
Circular complication on the Inforgraph modular does not work

### ISSUE THREAD

**Issue by balonchiks** [home-assistant/iOS#1072]
**iOS device model, version and app version**
Model Name: iPhone Xs
Software Version: 14.0
App version: 2020.6.1(2)

**Home Assistant Core Version**
115.2

**Describe the bug**
I have set the icon of the circular complication using the "Circular Image" template and it worked fine for months now. Today however i tried switching from "Circular Image" template to "Open Gauge Range Text" and apparently it doesn't work, the watch still shows the same icon i had when the "Circular Image" template was used and it's been like 3 hours like that now. I have read other topics concerning complications and it seems that it worked for people after some time. 

i think it's worth mentioning that Preview button shows correct values for all 4 fields that have to be filled for "Open Gauge Range Text".

Is there anything that i am missing, or the functionality is a bit broken? thanks.

**To Reproduce**
Set icon for the "Circular Image" template on the circular complication, then switch from "Circular Image" template to "Open Gauge Range Text".

**Expected behavior**
Expect the complication to show the gauge with my info

**Comment by TomBrien** [comment]
I believe the gauge and ring complications require the marker value to be normalised to `1`

**Comment by balonchiks** [comment]
feel quite stupid now. it worked flawlessly, thanks Tom!
