### ISSUE TITLE
iOS splash screen doesn't respect dark mode

### ISSUE THREAD

**Issue by jhqv** [home-assistant/iOS#1074]
**iOS device model, version and app version**

Model Name: iPhone XR
Software Version: 13.6.1
App version: 2020.6.1 (2)

**Home Assistant Core Version**
0.113.3

**Describe the bug**
When phone is set to dark mode, the second of the two splash screens ("loading data") has a bright white background.

**To Reproduce**

1. Force-close the app.
2. Switch phone to dark mode.
3. Start the app.
4. The second splash screen (blue logo and "loading data" text) has a bright white background.

**Expected behavior**
Both splash screens display dark backgrounds.

**Screenshots**
![IMG_6777](https://user-images.githubusercontent.com/8491785/93936739-ea514280-fd26-11ea-8c78-7de87174b53d.jpg)
![IMG_6778](https://user-images.githubusercontent.com/8491785/93936755-ef15f680-fd26-11ea-8a16-881127022390.PNG)

**Comment by zacwest** [comment]
This is a frontend issue, and is solved by the latest Core release (0.115) - please update.
