### ISSUE TITLE
Touch/swipe delayed response on iPad & iPhone after upgrade to iOS 14

### ISSUE THREAD

**Issue by fmonday** [home-assistant/iOS#1077]
**iOS device model, version and app version**

Model Name: iPhone 11 Pro Max, iPad Pro (11 inch)
Software Version: iOS 14.0
App version: 2020.6.1

**Home Assistant Core Version**

0.115.2
**Describe the bug**
Immediately upon upgrading to iOS14, it became apparent that taps or swipes in the companion app register after about a half-second delay. This is less of an issue when turning off a light than when swiping to navigate or, for instance, swiping down to refresh (which is actually quite difficult because by the time the refresh is about to register my finger is almost off the bottom of the screen). The issue is present neither in Safari nor if using the touchpad on a Magic Keyboard attached to the iPad inductively. 
**To Reproduce**
Swipe or tap. 
**Expected behavior**
Snappy response as per usual 
**Screenshots**

**Additional context**

**Comment by fmonday** [comment]
I just realized that this lag happens on the iPhone in Safari, so maybe I filed this in the wrong place. Weirdly it doesn't happen at all on iPad (which led to my error).

**Comment by fmonday** [comment]
Still happening on 14.0.1 and 0.116. Am I the only one?? I tried logging in/out of things, deleting the app, clearing the cache etc. 

Certain cards like swipe card are really hard to use.

**Comment by TomBrien** [comment]
If you're seeing this in safari I suggest opening an issue on the frontend repository as they'll be able to help you on this one :)

**Comment by fmonday** [comment]
Ok thanks
