### ISSUE TITLE
Signing issues when building locally

### ISSUE THREAD

**Issue by torarnv** [home-assistant/iOS#108]
I'd like to work on the iOS app, build it, and test it on my iPhone, but it seems like a lot of the signing stuff in the Xcode project is hard-coded to a certain development team and certain provisioning profiles. How are contributors supposed to build the app? Should I register provisioning profiles with my own app id and app group id, etc? Or is there a way to build the app with the existing profiles/app group settings?

@blackgold9 how are you solving this?

**Comment by torarnv** [comment]
Perhaps it would be possible to define the team and provisioning profiles in an `xcconfig` file, with comments on what profiles/enablements need to be registered, so that it's easy to hot-swap for another developer for on-device development

**Comment by blackgold9** [comment]
PRs welcome :)

**Comment by torarnv** [comment]
:smile:

**Comment by robbiet480** [comment]
I've said this in #devs_ios previously, but the primary issue here is that I have an individual account which means that I can only have my certificates which is why everything is hardcoded. You can go ahead and replace the certificate settings on your local version to build and test but please try to reset the project file containing the settings to defaults when submitting PRs. Hopefully someday this app will be under the HA organization and we can have multiple team members.

**Comment by torarnv** [comment]
The app is now under the HA organization. Does that mean the app can now be built without replacing certs?

**Comment by robbiet480** [comment]
What organization? It’s always been under the HA GitHub organization & the app is still published under my Apple Developer account.

**Comment by torarnv** [comment]
Ah, my bad, I was looking at this and thought the GitHub org was the one that needed changing. I just pulled the latest master and can confirm what you're saying. I'll look into moving some of that into an xcconfig file to at least make it easier to customize. Thanks!

**Comment by robbiet480** [comment]
One thing to note if you or anyone gets to this someday: The app now features the special critical alerts entitlement which must be requested from Apple. You _should_ be able to just remove it from the entitlements file and be on your way, but it may also require removing the request for critical alerts in the code too.

**Comment by robbiet480** [comment]
Fixed via #386
