### ISSUE TITLE
Camera streams don't start on initial tap/try

### ISSUE THREAD

**Issue by Codelica** [home-assistant/iOS#1080]
**iOS device model, version and app version**

Model Name:  iPhone 11 Pro
Software Version: 14.0
App version: 2020.6.1 (2)

**Home Assistant Core Version**

0.115.2

**Describe the bug**
When tapping to start camera stream from Lovelace card like Picture Entity, Picture Glance, etc, the stream fails to start on IOS Companion on *first* try.  Results in endlessly spinning loader icon in IOS media player. However, after that first try it will work and stream fine on subsequent tries.  It's almost like some odd startup/timing issue with HA starting up the hls streamer initially.

**To Reproduce**
Add camera to Picture Entity or Glance card and try to initiate stream via IOS companion

**Expected behavior**
Should work on first try/tap.

**Screenshots**

First tap to start stream stays like this indefinitely with spinner... 

![IMG_3696](https://user-images.githubusercontent.com/386101/94031145-c8ce7600-fd7b-11ea-926b-b121c2ae3e99.PNG)

2nd tap and later....

![IMG_3697](https://user-images.githubusercontent.com/386101/94030989-a5a3c680-fd7b-11ea-9345-081fa8429194.PNG)

**Additional context**

Streams work first click in Safari, Chrome, etc.  Wasn't sure if this should fall under "frontend" or IOS, but starting here since it only happens in the mobile app.  Have tried a variety of different camera/video settings to see if it was some quick I could work around, but nothing has helped so far.

**Comment by ionutbalutoiu** [comment]
I'm affected by exactly the same issue on:

Model Name: iPhone SE 2020
Software Version: 14.0.1
App version: 2020.6.2

**Comment by thexperiments** [comment]
For me the streams don't start at all and the complete phone freezes for some time.

iPhone 12pro max
2 Cameras via ONVIF integration

**Comment by bgoncal** [comment]
Is this still an issue with latest versions of app and core? Please also check if the issue happens in Safari, if so please report the issue to frontend. Feel free to reopen if needed
