### ISSUE TITLE
macOS app becomes unresponsive

### ISSUE THREAD

**Issue by paularmstrong** [home-assistant/iOS#1087]
**Device model, version and app version**

Model Name: MacBookPro 13-inch 2020
Software Version: OS X 10.15.6
App version: 2020.7 (2)

**Home Assistant Core Version** 0.115.2

**Describe the bug** The app does not respond to any click/mouse/keyboard input. System menus work fine, but nothing in the UI will respond. Accessing the same HA installation from a web browser works fine.

**To Reproduce** Unknown, but mine is stuck in this state, even after quit and re-open.

**Expected behavior** It does not become unresponsive

**Screenshots** N/A

**Additional context**

**Comment by zacwest** [comment]
Does the cursor change to the beachball icon when this happens?

Please launch Activity Monitor, find the Home Assistant app in the list, and sample the process - this should give a better idea what's going on.

**Comment by paularmstrong** [comment]
Of course it cleared up after the app was closed for a few hours then reopened. I'll check when/if it happens again.

**Comment by paularmstrong** [comment]
Okay, it's doing it again. I was clicking around between views in the dashboard and after one showed it suddenly froze.

No beachball in the app. Activity monitor looks fine

<img width="852" alt="Screen Shot 2020-09-25 at 10 01 09 AM" src="https://user-images.githubusercontent.com/33297/94295443-167ee600-ff16-11ea-810b-41e798fe67ec.png">
<img width="852" alt="Screen Shot 2020-09-25 at 10 01 10 AM" src="https://user-images.githubusercontent.com/33297/94295449-18e14000-ff16-11ea-88e2-1e73edcf1cd1.png">
<img width="862" alt="Screen Shot 2020-09-25 at 10 01 13 AM" src="https://user-images.githubusercontent.com/33297/94295451-1a126d00-ff16-11ea-9023-f750be89f773.png">

I see a lot of this in the Console

<img width="560" alt="Screen Shot 2020-09-25 at 10 02 39 AM" src="https://user-images.githubusercontent.com/33297/94295579-4928de80-ff16-11ea-9d25-1514d5ffbe12.png">

**Comment by zacwest** [comment]
Huh -- I wonder what's going on there. It sounds like it's blocking the main thread waiting for a callback from something, perhaps. Next time this happens, can you also grab a Sample from Activity Monitor? Double-click Home Assistant in the list and click Sample. That _may_ show what's going on.

**Comment by paularmstrong** [comment]
Happaned again. Found a sample 
[Sample of Home Assistant.txt](https://github.com/home-assistant/iOS/files/5292668/Sample.of.Home.Assistant.txt)

**Comment by arjunsamir** [comment]
Hey @zacwest @paularmstrong I'm not sure if this is the same issue that was reported, but I wanted to avoid opening a new issue in case it was. I can't interact with the ui either. For me it looks like there is some kind of overlay with a faint loading bar in the center that doesn't allow me interact with the app. The app itself updates in the background. When I control the app from other devices I can see the toggles update. Force quitting the app doesn't resolve the issue. I'm currently running lates stable release: [2022.10.1 (424)](https://github.com/home-assistant/iOS/releases/tag/release%2F2022.10.1%2F2022.424)
<img width="1658" alt="Screenshot 2022-12-11 at 3 40 14 PM" src="https://user-images.githubusercontent.com/47369740/206935882-230fb74a-7283-432d-868a-366086a0907b.png">

**Comment by bgoncal** [comment]
Do you still experience the same on the latest core and companion app version?  
(Feel free to reopen if needed)
