### ISSUE TITLE
New widgets open the app.

### ISSUE THREAD

**Issue by Darkwolf1515** [home-assistant/iOS#1091]
**iOS device model, version and app version**

Model Name: iphone 8
Software Version: ios 14.0.1 
App version: 0.115.2

**Describe the bug**
The new widgets open the app, the old ones do not.
**To Reproduce**
Create a home assistant ios14 widget, click on it, watch as it opens the app.

**Expected behavior**
It to not open the app, kinda defeats the point of a quick widget if it just takes me to the app anyways.

**Comment by TomBrien** [comment]
This is a _feature_ of iOS 14 and is beyond our control at the moment unfortunately. I'm closing this as there is nothing that can be done to address this, even though I agree it's a pain
