### ISSUE TITLE
I really like this companion for macOS and I even create a video tutorial about it

### ISSUE THREAD

**Issue by peyanski** [home-assistant/iOS#1093]
Hi there,
this is my video guide/tutorial - https://youtu.be/VBWYaQ64Q18

If you think that the video is helpful you can put it somewhere in the GitHug page.
Or I if it's easier for you I can do that and create a Pull request

Either way keep up the good work.
Cheers,
Kiril

**Comment by zacwest** [comment]
Thanks for making the video! An appropriate place to share this will be on the [forums](https://community.home-assistant.io), on [Reddit](https://www.reddit.com/r/homeassistant/) or in [Discord](https://www.home-assistant.io/help/).
