### ISSUE TITLE
Export as YAML action and notification categories created on iOS app

### ISSUE THREAD

**Issue by AnilDaoud** [home-assistant/iOS#1099]
It would be great to be able to export actions created in the iOS app to configuration.yaml

This way all users of HA would see actions appear in their iOS device. 
It would also serve as a backup: in case user moves to a new device, he/she doesn't have to recreate actions.

I am aware we can directly create Actions in the configuration.yaml file, but there is no user friendly way to pick icons/colors this way.

**Comment by michalk-k** [comment]
It would be even better if the application could push categories to HA, making them usable for all devices connected to the HA.

But exporting yaml as the first step will be great help too.
