### ISSUE TITLE
Hundreds of simultaneous connections to HA when BlueIris camera is in Lovelace view

### ISSUE THREAD

**Issue by iankaufmann** [home-assistant/iOS#1100]
**Device model, version and app version**
Model Name: MacBook Pro (Retina, 13-inch, Early 2015)
Software Version: 10.15.7
App version: 2020.7 (2)

**Home Assistant Core Version**
0.115.3

**Describe the bug**
The companion app is opening hundreds of simultaneous connections when there is a BlueIris camera displayed on a Lovelace view and the app is open (even if minimized).

Switching to a different view that doesn't include a camera feed makes it stop.

**To Reproduce**
Create a dashboard view that includes a camera feed and watch the requests to your HA instance.  I have mine behind HAProxy running on PFSense and can see the requests on my PFSense dashboard.

**Expected behavior**
Only one or a small hand full of connections made to HA.

**Screenshots**
<img width="443" alt="Screen Shot 2020-09-26 at 9 28 35 AM" src="https://user-images.githubusercontent.com/1100001/94343330-f6662a00-ffdc-11ea-9da4-3d23d0dc786e.png">

**Additional context**
As seen in the screenshot, a single laptop (192.168.1.36) has opened 156 simultaneous connections to HA (my desktop, 192.168.1.32, is only opening two).

The connections drop immediately when I quit the companion app, and then if I re-open it and leave it on a dashboard view with no camera feeds, it doesn't happen.

This does not happen in a web browser.  It opens one connection for each camera, but the connections die off after the tab is not in the foreground for a few seconds.

**Comment by zacwest** [comment]
Judging by the connected times in that table, it looks like a new connection is being made every 5 minutes. I believe this is the default disconnect time for the webview, so it's possible there's an issue there, or it's a coincidence. Can you try disabling (under your profile/username in the sidebar) "Automatically close connection" and see if that makes a difference here?

My hunch is that the app, while running, is behaving more like an active tab than an inactive tab unless the app itself is hidden (⌘H). It's possible we can take advantage of macOS's … the name escapes me … to realize we're not visible and treat the view as hidden, assuming it doesn't already do that.

**Comment by iankaufmann** [comment]
Thanks for looking into it!  

"Automatically close connection" was turned on for both machines, so I have switched it to "off" on both and will monitor the situation for a few hours.

**Comment by iankaufmann** [comment]
Unfortunately it doesn't seem to have made an impact.

After a little over an hour I have over 100 connections again.

It also has the unfortunate side effect of completely thrashing my BlueIris machine, which kills my FPS down to almost nothing.  It was driving me crazy until I put it together that it started right after I started using the HA app.

I just quit the app on both machines, re-opened it, browsed to a view that has no cameras on it, then hit (⌘H).  All of the connections dropped off and the network is stable again.

**Comment by bgoncal** [comment]
Do you still experience the same on the latest core and companion app version?  
(Feel free to reopen if needed)
