### ISSUE TITLE
Battery State Not Updating

### ISSUE THREAD

**Issue by c0nt4x** [home-assistant/iOS#1111]
## The problem

The battery charging state does not dynamically update. When checking entity in Developer Tools the state does not change automatically. I have to change entity selection then go back to the original device entity for the charging state to update. This state also cannot be used in any automation as it doesn’t update dynamically. 

## Environment

- Home Assistant Core release with the issue: 0.115.3
- Last working Home Assistant Core release (if known): 
- Operating environment (OS/Container/Supervised/Core): iOS 13 and 14
- Integration causing this issue: 
- Link to integration documentation on our website: 

## Problem-relevant `configuration.yaml`

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by c0nt4x** [comment]
Ok thanks. I’m only assuming it’s the mobile app. I don’t know enough about HA yet to know where the battery state comes from, I’m sorry.

**Comment by zacwest** [comment]
There are likely delays where the battery state won't update its entity, because the app isn't running, but please correct me if I'm wrong, that's not what this issue is about, right @c0nt4x?

@frenck My read of the issue description above is that the entity itself is live-updating, but the Developer Tools page requires a refresh to show the new value.

**Comment by c0nt4x** [comment]
For example in a Lovelace card showing the battery state the state changes correctly but in developer tools it doesn’t change/refresh.

And in Lovelace it only seems to change if I first open the app on the device and have it in the foreground and device unlocked. That would mean to get the battery state you first have to launch the app, leave the device unlocked then put it on the charger instead of it just working in the background. Occupancy state changes without having to launch the app first so shouldn’t battery state also? Or is that a different issue altogether?

**Comment by pangwa** [comment]
+1, it looks like sensors not updating while ios companion app being in background.

**Comment by bgoncal** [comment]
The app updates it's sensors in background following background modes that Apple allow developers to use (so not realtime), the option to improve that is to enable "Local notifications" which will increase battery comsumption but keep a connection with the websocket open and then update sensors often.

Do you still experience the same on the latest core and companion app version?  
(Feel free to reopen if needed)
