### ISSUE TITLE
iOS 14 Today Widget group (or entity) state 

### ISSUE THREAD

**Issue by simieski** [home-assistant/iOS#1116]
**Is your feature request related to a problem? Please describe.**
Currently actions on today widget are not as useful on iOS 14 because Home Assistant companion app has to open to fire the action and the new Today Widgets are designed/restricted by Apple to be more information based rather than actions.

**Describe the solution you'd like**
I would like to use a similar feature to 'actions' to display the state of a particular entity or 'group' of entities on a iOS 14 Today Widget (specifically the smaller square widget). 

For example, if I have a *group* defined in config yaml *light.all_lights*, when I leave the house I would like to quickly be able to see, by looking at my today widget on my iPhone home screen if all lights were in the state *off*

I would like to be able to set the icon, text and colours for all possible states. Eg. bulb, Lights on, and yellow for state ON. and lightbulb-off, Lights off and grey for OFF.

**Additional context**

**Comment by zacwest** [comment]
#920
