### ISSUE TITLE
AppleScript Support

### ISSUE THREAD

**Issue by gabe565** [home-assistant/iOS#1117]
**Is your feature request related to a problem? Please describe.**

I can't currently find a way to interact with the companion from other applications.

**Describe the solution you'd like**

There are already intents defined for iOS's Siri shortcuts, it could make for some pretty powerful local scripting if they could be called from an AppleScript.

**Additional context**

I use [BetterTouchTool](https://folivora.ai/) to customize my Touch Bar, and one option is to run AppleScripts to interact with other applications. I could use the `RenderTemplate` intent to show HA template output in my Touch Bar. I could also add buttons to my Touch Bar which trigger a `CallService` intent to perform actions in my HA install.

There are already some implementations of HA on Touch Bars out there (notably [basnijholt/home-assistant-macbook-touch-bar](https://github.com/basnijholt/home-assistant-macbook-touch-bar)), but these usually use HTTP requests.

I don't know much about the internals of AppleScripts so I don't know what the security would look like here, but it could maybe be an opt-in feature in preferences somewhere?

**Comment by mar005** [comment]
I would also want to drop my name into the hat. I use Keyboard Maestro, which does a lot of automation on the Mac itself. KM allows you to run automations based on various different triggers including Scripts such as those in the screenshot below:

![image](https://user-images.githubusercontent.com/24581058/94576263-c1efa980-023a-11eb-9fc4-7d04ad471866.png)

AND KM allows you to run scripts as actions too. I know my proposal is different than the OP but figured this is how it could all fit together.

If we had the ability for local scripts to work as HA Automation Triggers AND/OR HA Automation Actions to run local scripts then those close the gap for apps like BetterTouchTool (BTT) and [Keyboard Maestro](https://www.keyboardmaestro.com/main/) that do so much more.
