### ISSUE TITLE
Using color picker on macOS Companion App causes looping and front-end to lock up

### ISSUE THREAD

**Issue by OverZealous** [home-assistant/iOS#1119]
**Device model, version and app version**

Model Name: **Mac Pro (Late 2013)**
Software Version: **macOS Catalina 10.15.6**
App version: **Home Assistant Companion 2020.7 (3)** — but was present in previous version, too

**Home Assistant Core Version**
Home Assistant **0.115.3**

**Describe the bug**
If I try to change the UI colors in the Mac version of the app, the color selector pops up and gets stuck in a loop. I have to quit and restart the companion app to use HA in the Mac app again.

**To Reproduce**
Click on a color selector shown for the default theme on the profile page.

**Expected behavior**
I should be able to select a color.

**Screenshots**
Screen recording of event (attached inside the zip): **[ha-companion-color.mp4.zip](https://github.com/home-assistant/iOS/files/5295777/ha-companion-color.mp4.zip)**

**Additional context**

I tested it under Safari, and this doesn't happen. In fact, Safari uses a completely different color picker (one that's more compact, but also lets me open up the full system color selector). I wonder if it's a bug with the iOS->macOS conversion process, since the picker looks like an iOS color picker?

That being said, I think I was able to pick the colors once when this was first announced. But I don't remember 100%.

**Comment by zacwest** [comment]
It's unclear to me when this started working, but this no longer reproduces on Big Sur 11.1 (20C69). It's almost certainly a Catalyst issue, so I'm not sure there's much more we can do for backwards fixes.

**Comment by OverZealous** [comment]
Ah shoot, I completely forgot I filed this! I believe I found the cause, it was due to the page being zoomed in. I just double-checked it, and I agree, it appears to have been fixed with `11.1`, even if I zoom in the app.
