### ISSUE TITLE
Window position is not saved when ending the Home Assistant companion App!

### ISSUE THREAD

**Issue by carsten-h** [home-assistant/iOS#1122]
**Device model, version and app version**

Model Name: Mac Pro 2013
Software Version: 10.15.7
App version: 2020.7 (3)

**Home Assistant Core Version**

HassOS 4.13 on a Pi4B 4GB
Supervisor 245
Home Assistant 0.115.4

**Describe the bug**
If you end the Home Assistant Companion App on the Mac and start it again, the position and size of the window is always the default, not the last position used.

**To Reproduce**
Start the Companion App, place the window anywhere on the screen, end the App and start it again.

**Expected behavior**
The window positions should be saved.

**Screenshots**

**Additional context**

**Comment by zacwest** [comment]
#1040
