### ISSUE TITLE
iOS Push Notification Rate Limits - Two “Errors”

### ISSUE THREAD

**Issue by ZuluWhiskey** [home-assistant/iOS#1124]
**iOS device model, version and app version**

Model Name: iPhone 8 Plus
Software Version: 14.0
App version: 2020.6.2(1)

**Home Assistant Core Version**

Core Version: 0.115.0

**Describe the bug**
If you go to App Configuration > Notifications > Scroll down to "Rate Limits" you can see that 'Errors' appears twice in the list at position 1 & 3.

**To Reproduce**
Navigate to the aforementioned place in the application to see the error.

**Expected behavior**
There not to be two 'Errors', unfortunately I don't know what the correct layout / format is.

**Screenshots**

![image](https://user-images.githubusercontent.com/35011199/94604956-4fa9b400-0290-11eb-8825-95248d1dc67a.jpeg)

**Additional context**

**Comment by TomBrien** [comment]
That's British English (only one that's shows GMT not UTC). Probably a string/translation issue

**Comment by TomBrien** [comment]
Just had a quick look. Doesn't look like a translation issue. Only string I can see translated as "Errors" is `settings_details.notifications.rate_limits.errors`

**Comment by ZuluWhiskey** [comment]
> Just had a quick look. Doesn't look like a translation issue. Only string I can see translated as "Errors" is `settings_details.notifications.rate_limits.errors`. Looking at my app I'm not sure what the top one is supposed to be. Looks like a dupe of Delivered?

Ah nice one, sounds like a (hopefully) easy fix!

**Comment by zacwest** [comment]
Fixed in #1123.
