### ISSUE TITLE
MacOS App Background/Menubar Options (Hide icon from dock)

### ISSUE THREAD

**Issue by MikeFez** [home-assistant/iOS#1126]
The MacOS application is a wonderful addition to Home Assistant, and has now found a permanent spot on my login items list.

That being said, I find the real value of the application to be the ability to read sensor data from my Mac, as well as the ability to work with notifications. Due to this, I don't intend to use the GUI of the application (especially as I prefer accessing it via browser), and so it remains minimized in my dock.

It would be wonderful if there would be the option to hide the application from the dock, having it available as an icon in the menu bar instead. Upon clicking the menu bar, it could show/hide the GUI, allowing easy access for users who would prefer this run as more of a background service.

**Comment by zacwest** [comment]
#949
