### ISSUE TITLE
Jinja Template not working in 'gauge' nor 'ring' watch complications

### ISSUE THREAD

**Issue by mountainsandcode** [home-assistant/iOS#1127]
**iOS device model, version and app version**

Model Name: Apple Watch Series 6
Software Version: WatchOS 7, iOS 14
App version: Latest from App Store

**Home Assistant Core Version**

0.115.5

**Describe the bug**
I’ve been trying to get the Graphic Corner complication (Template: Gauge Text) to work, which is working great, except for when I add a Jinja template to indicate the gauge progress. Using a local template `{{ 0.5 }}` or remote template `{{ states(“sensor.x”) }}` means the complication doesn’t update. Using `0.5` instead, the complication works without any issues. This problem only affects the Gauge field (which sets the gauge progress), templates are working fine for the other, text-based fields.

**To Reproduce**

- Create Graphic Corner, Gauge Text complication
- Use `0` for leading, any text or emoji for outer, `7` (or any number) for trailing, and `0.5` for the gauge. The complication shows without any issue
- Add any template to the gauge and simultaneously change another field (I’d suggest the outer text) to keep track of changes
- Complication will no longer update

**Expected behavior**
Templates to work in setting gauge to update the gauge progress

**Screenshots**

**Additional context**

**I’d guess it to be an issue converting the template output to a numeric value between 0 and 1 which is used for the gauge progress indicator**. This would explain why templates are working fine for all the other fields (even using identical templates), because they display strings.

**Comment by zacwest** [comment]
This indeed does not work - the gauge text is not parsed for templates.
