### ISSUE TITLE
Lokalize Greek Language Support Request

### ISSUE THREAD

**Issue by dsimop** [home-assistant/iOS#1129]
English Name: Greek
Native Name: Ελληνικά

**Comment by dsimop** [comment]
@zacwest this issue seems to be still unresolved. The Greek Language Integration is still missing from the respective Lokalize Project.

**Comment by TomBrien** [comment]
Hi @dsimop I can see Greek in the project. Can you confirm your username on Lokalize and I'll make sure you have access to it

**Comment by dsimop** [comment]
Hello @TomBrien. I am talking about the "Home Assistant Companion for iOS" Project, not the "Polymer frontend" one ;)
