### ISSUE TITLE
Support erasing tag memory

### ISSUE THREAD

**Issue by raman325** [home-assistant/iOS#1134]
**Is your feature request related to a problem? Please describe.**
The tag integration is fun to play with, but when I was done experimenting and wanted to wipe the tag, I wasn't able to find a way to do it through the app. I was able to do this using a 3rd party app but it would be great to have native support in HomeAssistant.

**Describe the solution you'd like**
Just a thought, but when a user goes to delete the tag, maybe add a dialog that allows them to choose to wipe the tag itself  while deleting the entry - if the user selects to do so, use the same UI as the one for writing a tag.

**Additional context**
Cross-posted to home-assistant/android#1001

**Comment by zacwest** [comment]
I'm curious what your goal is for erasing the tag. Is it to reuse it for another purpose that doesn't involve writing to it?

**Comment by raman325** [comment]
Admittedly it may be a minor use case, but it was to put it back in the bag so I didn't have to figure out which one had already been written to
