### ISSUE TITLE
Platform mobile_app does not generate unique IDs Error

### ISSUE THREAD

**Issue by c0nt4x** [home-assistant/iOS#1137]
Hi

In the HA log I am seeing an error referring to the two devices (iphones) that I have the companion app installed on. The error states "Platform mobile_app does not generate unique IDs" for both devices.

I have attached a screenshot of the log entry.

Can you please advise. Thanks.
![error](https://user-images.githubusercontent.com/70321584/94905578-04142780-0495-11eb-926f-0dec9f52c93a.png)

**Comment by zacwest** [comment]
This likely means you have more than one integration for the same devices. I suggest you look at your Configuration > Integrations and delete the mobile_apps for those 2 devices (assuming there's more than 1) and restart the apps on the phone. They'll recreate the integration, and this error should go away.

**Comment by c0nt4x** [comment]
Thanks Zak, that sorted it.

**Comment by zacwest** [comment]
Thanks for following up!
