### ISSUE TITLE
Complication Icons to large

### ISSUE THREAD

**Issue by skycryer** [home-assistant/iOS#1162]
iOS device model, version and app version

Model Name: Apple Watch Series 6
Software Version: Apple Watch OS 7.0.1
App version: 2020.6.2 (1)

Model Name: iPhone 11 pro
Software Version: iOS 14.1
App version: 2020.6.2 (1)

Home Assistant Core Version
0.115.6

**Describe the bug**
Icons used in complications are to large.

**To Reproduce**
Just add a complication with an icon, every icon is to large.

**Expected behavior**
Icons need to be outputted smaller so they fit into the complication

**Screenshots**
![IMG_5442](https://user-images.githubusercontent.com/3725699/95187727-c59ba700-07cb-11eb-8414-e0e31d29d885.PNG)
![IMG_5443](https://user-images.githubusercontent.com/3725699/95187737-c92f2e00-07cb-11eb-948e-e13efdf40ee2.PNG)

**Additional context**
Both samples using the ab_testing icon. But problem is with every icon what I have seen so far

**Comment by TomBrien** [comment]
This is duplicate on #276 closing in favour of the original.

**Comment by skycryer** [comment]
@TomBrien duplicate ok, but why is #276 then also closed but not solved?

**Comment by TomBrien** [comment]
#276 was reopened two weeks ago
