### ISSUE TITLE
Complication Gauge with gradients

### ISSUE THREAD

**Issue by skycryer** [home-assistant/iOS#1163]
**Is your feature request related to a problem? Please describe.**
Add gradient to gauge bars. In Graphic Corner Gauge and Graphic Circular there are options with gradient bars on Apple Watch Face site 

<img width="94" alt="CornerGaugeText_2x" src="https://user-images.githubusercontent.com/3725699/95188482-c2ed8180-07cc-11eb-80f3-1d051ccdb71e.png">
<img width="68" alt="CircularOpenGaugeRangeText_2x" src="https://user-images.githubusercontent.com/3725699/95188487-c3861800-07cc-11eb-92b9-85ab239b1628.png">
<img width="68" alt="CircularOpenGaugeSimpleText_2x" src="https://user-images.githubusercontent.com/3725699/95188488-c3861800-07cc-11eb-9912-d33540afee56.png">
<img width="68" alt="CircularOpenGaugeImage_2x" src="https://user-images.githubusercontent.com/3725699/95188489-c41eae80-07cc-11eb-9a57-8e631838dcb2.png">

https://developer.apple.com/design/human-interface-guidelines/watchos/overview/complications/

Atm the complication configure from Home Assistant only show the bar in one color.

**Describe the solution you'd like**
Add a gradient to the bars so if to different colors are configured there is a gradient visible.

**Additional context**
I know there are gauge with more then 2 colors like Graphic Circular Open gauge text 
<img width="68" alt="CircularOpenGaugeSimpleText_2x" src="https://user-images.githubusercontent.com/3725699/95188425-acdfc100-07cc-11eb-8b9e-488a76661524.png">
but that could be something for later. I think for the beginning having a 2 color gradient would be a great start.

**Comment by mountainsandcode** [comment]
@skycryer Are you managing to set the progress of the gauge using templates? I can’t get this to work, see #1127

**Comment by skycryer** [comment]
Hm, looks like only static values work. Just added a template value that is 0.26 in home assistant but not updating in the watch complication so I think it has a problem with the data. Will wait a bit if it maybe update later like large rectangular did with template data.

**Comment by zacwest** [comment]
Gauge provider supports N number of [colors and positions](https://developer.apple.com/documentation/clockkit/clkgaugeprovider). Likely a good UI for this is a multi-point `UISlider`-like thing that allows adding additional thumbs/colors to the track.

**Comment by GuySie** [comment]
If it is possible, having support for the gradient colors and positions in a template-able form would be amazing. I have some complication ideas where I'd like to change the colors across the gauge/ring bar depending on sensor readings in HA.
