### ISSUE TITLE
Graphic Bezel complication not working

### ISSUE THREAD

**Issue by skycryer** [home-assistant/iOS#1166]
**iOS device model, version and app version**
Model Name: Apple Watch Series 6
Software Version: Apple Watch OS 7.0.1
App version: 2020.6.2 (1)

Model Name: iPhone 11 pro
Software Version: iOS 14.1
App version: 2020.6.2 (1)

**Home Assistant Core Version**
0.115.6

**Describe the bug**
Graphic Bezel not showing any data, also icon not configurable or show extra data on that place.

**To Reproduce**
Add Graphic Bezel complication to Infograph, only ?? visible as text.

**Expected behavior**
Show Text configured as Bezel

**Screenshots**
![IMG_5457 2](https://user-images.githubusercontent.com/3725699/95219851-2344e900-07f6-11eb-92f1-9701ea658c53.PNG)
![IMG_5456 2](https://user-images.githubusercontent.com/3725699/95219861-25a74300-07f6-11eb-8c65-dcded6c9b210.PNG)

**Comment by zacwest** [comment]
This is actually not implemented, it seems:

https://github.com/home-assistant/iOS/blob/4d9a5306372afa9fd105ae82f3e2fe036d88015f/Sources/Shared/API/Models/WatchComplication.swift#L582-L588

**Comment by zacwest** [comment]
Thanks for this and the other tickets; having detailed reproduction helps resolve issues, and the Watch is a huge pain to debug (it takes _minutes_ to test a change, if you're lucky and it is actually working at all) so these are particularly painful to experiment with.

**Comment by skycryer** [comment]
@zacwest glad I can help a bit. No knowledge with Swift but with testing. So if you have anything that need to be tested just tell me. If there is a beta for iOS I can try it out.

**Comment by zacwest** [comment]
You can join the [TestFlight beta](https://www.home-assistant.io/ios/beta). A new build with the Watch changes will likely happen this weekend.

**Comment by skycryer** [comment]
The link only opens the home assistant app. I installed TestFlight but how to join the beta?

**Comment by zacwest** [comment]
I think Universal Links is being annoying there (I thought I fixed this). If you launch it on desktop it should redirect to a TestFlight link that you can use.

**Comment by skycryer** [comment]
Looks like the beta link on the TestFlight page is not available anymore? Or is there just no active beta atm?

**Comment by zacwest** [comment]
It should work. If you copy the beta link (the one that opens the app by default should also work) and paste it into Safari on iOS you should see a "Start Testing" button.

**Comment by skycryer** [comment]
![IMG_5460](https://user-images.githubusercontent.com/3725699/95371768-f3234600-08da-11eb-83c9-96cfdd1bc831.PNG)

Trying it as described and I can open the TestFlight app but the link on that page is not available.

**Comment by TomBrien** [comment]
In your current app if you go to App Configuration>About there should be a join beta link there that will hopefully work.

**Comment by skycryer** [comment]
That worked, I have the beta now installed. Waiting now for updates on the watch to test. 🙃

**Comment by zacwest** [comment]
You may need to restart for it to pick up the TestFlight app being installed in Safari. It errors a lot sooner if the TestFlight link itself isn't valid anymore.
