### ISSUE TITLE
Not able to navigate from intro screen

### ISSUE THREAD

**Issue by tejuamirthi** [home-assistant/iOS#1174]
Hey all,

I'm relatively new to the whole application. I just wanted to try this out on a simulator. Somehow it seems like I'm not able to do that correctly. I need help from you guys! I'd like to contribute later on but would like to get to know about the application more. Please help how to proceed further. 

**iOS device model, version and app version**
I built the project on Xcode 12.0.1. Got the initial errors mentioned in the description for setting up the application. But I don't understand how to go past this screen I have attached below.

I feel like I need to setup server or something like that. Again someone please help!

Model Name: iPhone 8
Software Version: 12.2
App version: 2020.7

**Screenshots**
<img width="443" alt="Screenshot 2020-10-09 at 11 07 03 PM" src="https://user-images.githubusercontent.com/29634986/95614458-28b76300-0a84-11eb-981b-a4b29976c768.png">

**Comment by TomBrien** [comment]
You will need a working Home Assistant server to connect the app to. It has no function without Home Assistant

**Comment by tejuamirthi** [comment]
Oh, is it something like, I could host this Home Assistant server?

**Comment by TomBrien** [comment]
Yeah, you should have a look at the guide here: https://www.home-assistant.io/getting-started/

**Comment by tejuamirthi** [comment]
Firstly thank you so much for taking out your time and for the above document.
But after seeing that I'm worried if I need physical hardware material or anything that could connect and I need to host the software on a different computer? Sorry if I'm being silly, I'm really new to this. Thanks in advance

**Comment by zacwest** [comment]
That is correct, you need to run the Home Assistant server for the app to do anything; it's purely a controller for a larger system. You can check out the steps Tom linked above to see some local-install options to get it running on a Mac or in Docker.
