### ISSUE TITLE
"Native types" template generation breaks our render template uses

### ISSUE THREAD

**Issue by zacwest** [home-assistant/iOS#1177]
**Home Assistant Core Version**
0.117

**Describe the bug**
home-assistant/core#41227 introduces a change to template generation behavior which allows for non-string types to be returned by template generation. This means that something like `{{ range(1, 10) | random }}` will now return a value like `3` instead of `"3"` as the rendered value.

Throughout the template rendering handling (in Watch and Shortcuts notably) we expect this to be a String and `as? String` fails to coerce these Int/Float/Dict/Array/Bool/etc. types to a String.

**To Reproduce**
Attempt to render a template via the `render_template` webhook on `mobile_app`

**Additional context**
Three possible changes:

1. Add a flag to the API to always deliver a string, make the new behavior opt-out so we can prevent regressing existing clients
2. Update our parsing to always intentionally stringify any value, to preserve existing behavior.
3. Audit our internal Watch value generation to get what we need (always String for text, always Float for ring/gauge (now that they work)) and inform people about the breaking change in URL scheme & Shortcuts generation.

I'm not sure how cleanly Shortcuts.app will handle these type changes, since we promise String as the result value and there's actually no "can be any type" option in the list; we must give it a concrete type.

**Comment by frenck** [comment]
As mitigation, for now, we can also adjust the `mobile_app` integration to return a string value to remain compatible. That would be a 10 second job.

**Comment by zacwest** [comment]
I think getting the real types is good. If we want to make older clients work with it, we could add a parameter to allow the native type to come through. Otherwise I think I'll have a release out for 0.117.
