### ISSUE TITLE
WatchOS complications: Highlight actively used types

### ISSUE THREAD

**Issue by mountainsandcode** [home-assistant/iOS#1179]
**Is your feature request related to a problem? Please describe.**

Thanks Zac for all the recent bug fixes and extensions on the WatchOS app, really looking forward to testing and using them!

I noticed one thing that comes out as a change from #1176 - “Stops restricting complication rendering to only the active complication”. 

My assumption is that all complication types that are configured are being refreshed? Or is it only those that are added to a watch face somewhere. In case it is indeed the former, we may be carrying around some unnecessary dead weight because users may have previously configured a complication they are no longer using.

**Describe the solution you'd like**
Highlight in the list with the 12 complications which ones are being configured. Additionally, if one is configured, adding a simple button (e.g., trash bin) to remove the configuration for that complication.

**Additional context**
In case I’m mistaking and we only calculate those complications that are on some watch face (whether it’s currently being shown or not), please feel free to close this one :)

**Comment by zacwest** [comment]
Right now we only know which complications are being actively displayed. We won't do any display work for those that aren't, but we will include them in the 'render template' call. Unless your templates are extraordinarily complex, the additional cost should be pretty minimal. 

I believe a good plan forward is #839 which will turn the list from "select which family you want to edit" to "view your complications" -- e.g. it will be an explicit + button to add a new complication that you must name, and you can pick on the Watch which choice you want from that list.

**Comment by mountainsandcode** [comment]
Thanks, @zacwest, for the speedy reply. That will indeed cover it, and is a more elegant solution!
