### ISSUE TITLE
Error: Platform application is disabled

### ISSUE THREAD

**Issue by biiiink** [home-assistant/iOS#1182]
**iOS device model, version and app version**

Model Name: iPhone Xs Max
Software Version: 14.0.1
App version: 0.116.2

**Home Assistant Core Version**

0.116.2
**Describe the bug**

Whenever a notify automation runs, i see this error in the logs:
`Logger: homeassistant.components.ios.notify
Source: components/ios/notify.py:104
Integration: Home Assistant iOS (documentation, issues)
First occurred: 2:14:38 PM (1 occurrences)
Last logged: 2:14:38 PM

Platform application is disabled`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by TomBrien** [comment]
It looks like you might be using `notify.ios_DEVICE_NAME` rather than `notify.nobile_app_DEVICE_NAME`

**Comment by biiiink** [comment]
Bah.  Oops.  My apologies!

**Comment by TomBrien** [comment]
No worries. Glad it's working now :)
