### ISSUE TITLE
Ethernet connection sensor

### ISSUE THREAD

**Issue by LucasJanin** [home-assistant/iOS#1184]
**Is your feature request related to a problem? Please describe.**

The current sensors don't permit to know if the Mac connected over ethernet cable.
This information can permit HA to know if the laptop is used in the office or not.
For example, turn on the light office if mac is active and connected on ethernet.

**Describe the solution you'd like**

The sensor will be on if is ethernet connected and off isn't connected.
IP can be store too for a better understanding of that VLAN the mac is connected.

**Describe alternatives you've considered**

I'm currently using unifi control sensors but unfortunately, this adds delay for the changing state of the sensor.

https://github.com/LucasJanin/Home/tree/main/HomeAssistant/macOccupencyTemplate

Thanks

**Comment by phischmi** [comment]
+1 from me 👍

**Comment by LucasJanin** [comment]
Fantastic! Thanks @zacwest for adding this future to the application!

**Comment by maxandersen** [comment]
This is awesome. I was looking around for binaries I could test install but didn't see any In GitHub actions. 

Are they available somewhere or must one build them manually locally ?

**Comment by zacwest** [comment]
They must be built locally at the moment. Signing requires a manual step and waiting for Apple to process the results. I will likely do a beta this weekend that includes everything up until then.

**Comment by LucasJanin** [comment]
> I will likely do a beta this weekend that includes everything up until then.

Nice! I can't wait to test the beta :-)
