### ISSUE TITLE
Zone Bounce Following Zone Transistion

### ISSUE THREAD

**Issue by garyak** [home-assistant/iOS#1189]
**iOS device model, version and app version**

Model Name: iPhone SE
Software Version: 14.0.1
App version: 2020.6.2
**Home Assistant Core Version**

 HA Core 116.2
**Describe the bug**
Following a transition from Away to Home, the iOS App device_tracker will bounce several times before it settles on the current zone. 
**To Reproduce**
Return to Home zone after being Away.
**Expected behavior**
Device_tracker should not switch from Home to Away repeatedly every five seconds after arriving Home.
**Screenshots**

![bounce](https://user-images.githubusercontent.com/47036329/95853721-199a1480-0d13-11eb-9a32-f3a7010663c3.jpg)

**Additional context**

A manual update when Away results in the Zone returning to Home triggering my arrival automation. The bouncing occurs when the device enters the Home zone triggered by an iBeacon, if that's important).

**Comment by zacwest** [comment]
The easiest way to identify what's happening will be the logs on the device as it decides to send up location changes. If iBeacon is playing a part here, my guess would be in the sending option events. Is it attached to the home zone or a different one?

From App Configuration > Event Log or the export button for the in depth ones, can you report the detailed information for each of the location updates it is sending?

**Comment by garyak** [comment]
Log was exported immediately following the events. The device name is gryphon. Arrival at home is is initially triggered by iBeacon Region Entered. I got as close as I could. 
[gryphonlog.txt](https://github.com/home-assistant/iOS/files/5405566/gryphonlog.txt)

**Comment by zacwest** [comment]
Looking at your logs, I believe what you're experiencing is that a location update is occurring (from beacon or otherwise) which causes the app to recalculate which regions to monitor (you have 31 circular regions from your 14 zones, due to size, so it truncates to 20). The act of doing so then causes location updates outside of the beacon codepath.

This scenario should hopefully be resolved by #1136 in 2020.7 (not yet out). You can check it out [in beta](https://www.home-assistant.io/ios/beta) or wait for it to be in the released build to try it out.

**Comment by garyak** [comment]
2020.7 appears to have addressed this issue.

**Comment by TomBrien** [comment]
I saw this yesterday with 2020.7 but it is much less frequent now. This was the first time I'd seen in it in a few weeks vs maybe every other day before

**Comment by garyak** [comment]
OK. I'll keep checking the logbook and post new events.

**Comment by zacwest** [comment]
> I saw this yesterday with 2020.7 but it is much less frequent now.

Can you pull the logs when this happened? It may be another issue, or the same one. Only way to tell.

**Comment by TomBrien** [comment]
Just happened, sending you some logs now

**Comment by zacwest** [comment]
Unless anyone feels otherwise, I do believe this is largely resolved. Please make a new ticket if you experience this again.
