### ISSUE TITLE
Updated zone definition names are being cached with the old name and a new name

### ISSUE THREAD

**Issue by nateww** [home-assistant/iOS#1190]
**iOS device model, version and app version**

Model Name: iPhone 8
Software Version: 0.116.2
App version: 2020.6.2 (1)

**Home Assistant Core Version**

0.116.2

**Describe the bug**
I updated two of my zone definitions to increase the size of the radius, and now I have two definitions. The original now has a LAT/LON of 0.000,0.00 Radius: 0, and a second (correct) definition with the correct LAT/LON and radius.

This ONLY seems to occur on the iOS app, Home Assistant only shows the correct zones.

**To Reproduce**
Create a zone using the UI to get the LAT/LON, remove the zone from the UI after writing down it's data, and then add a new zone in the configuration.yaml file with the data

**Expected behavior**
The old zone should go away (as it does in HA-core).

**Additional context**
How can I remove all the existing zones and force the iOS app to re-synchronize them would be acceptable. I attempted to delete the app and re-download it, but the zones appear to be cached on my device.

**Comment by zacwest** [comment]
If you export your log files from the app (App Configuration > Export) it should have some information about what it received for zone information and how it synced them locally. That will be helpful in trying to debug what is going on. You may also need to call `zone.reload` and launch the app to get the changes to be seen.

**Comment by nateww** [comment]
How do I call zone.reload ONLY on the iOS app?  (The zones are correct in HA-core in that their is only one zone.)

Also, when I deleted/reinstalled the app, I apparently lost all the logs, so the only logs that exist contain data for the duplicate zones, and don't show anything about what data caused the updated zones.

**Comment by zacwest** [comment]
`zone.reload` would cause the server-side information to update, and the app uses the API to load zones that way. If the app synced down multiple zones on a fresh install, that also points to the API response including it still. The logs from this case are still relevant/useful.

**Comment by nateww** [comment]
The earliest logs on the app show

Initially monitoring zone.foozone@000
```
{"region": "CLCircularRegion(identifer:'zone.foozone@000', center:<+0.00089932, _0.00000000> radio:100.00m)" }
```

**Comment by nateww** [comment]
I called the `zone.reload` service from Developer Tools -> Service, but it didn't do anything to the list of Zones on the iOS app, and there are no new logs after the service was run in HA on the app either.

**Comment by zacwest** [comment]
Region monitoring is related, but not the same as, zones. Some zones require multiple monitored regions to correctly handle.

You should look for anything containing "zone" in the logs, what I expect is something like `get_zones` listing the response that includes them, and `ModelManager` talking about how it is persisting the information.

**Comment by nateww** [comment]
Slightly redacted
```
2020-10-13 12:40:40.626 [Info] [main] [WebhookManager.swift:206] sendEphemeral(request:) > got successful response for get_zones: (
        {
        attributes =         {
            "friendly_name" = FooZone;
            icon = "mdi:school";
            restored = 1;
            "supported_features" = 0;
        };
        context =         {
            id = 3e63e3b20ce611eba0f8ede1d2c2a0c3;
            "parent_id" = "<null>";
            "user_id" = "<null>";
        };
        "entity_id" = "zone.foozone";
        "last_changed" = "2020-10-12T23:54:19.367752+00:00";
        "last_updated" = "2020-10-12T23:54:19.367752+00:00";
        state = unavailable;
    },
        {
        attributes =         {
            editable = 0;
            "friendly_name" = FooZone;
            icon = "mdi:school";
            latitude = "46.0000000";
            longitude = "-112.0000000";
            passive = 0;
            radius = 210;
        };
        context =         {
            id = 3571889d0ce611eba1a74d6cd6e025aa;
            "parent_id" = "<null>";
            "user_id" = "<null>";
        };
        "entity_id" = "zone.foozone_2";
        "last_changed" = "2020-10-12T23:54:04.357710+00:00";
        "last_updated" = "2020-10-12T23:54:04.357710+00:00";
        state = zoning;
    },
```

**Comment by nateww** [comment]
Note, 'Configuration -> Zones' only shows 4 zones on HA-core.

**Comment by zacwest** [comment]
I'm not sure where it may be loading from, but it doesn't appear this is a bug in the iOS app -- it's just loading whatever zones it's told. If you're not seeing it in any of the config, restarting the server may flush it from the states list which is what the app is loading from.

**Comment by nateww** [comment]
Logs from ModelMaker from when I reinstalled the app.
```
2020-10-10 11:30:28.869 [Verbose] [com.apple.root.utility-qos] [ModelManager.swift:160] store(type:sourceModels:) > updating RLMZone from(6) eligible(6) deleted(0) ignored(0) new(0)
2020-10-10 11:30:28.875 [Info] [main] [ZoneManager.swift:151] sync(zones:) > monitoring 10 ((beacon: 0, circular: 10, zone: 6)), started 0, ended 0
2020-10-10 11:30:29.109 [Verbose] [com.apple.root.utility-qos] [ModelManager.swift:160] store(type:sourceModels:) > updating NotificationCategory from(0) eligible(0) deleted(0) ignored(0) new(0)
2020-10-10 11:30:29.110 [Verbose] [com.apple.root.utility-qos] [ModelManager.swift:160] store(type:sourceModels:) > updating Action from(0) eligible(0) deleted(0) ignored(0) new(0)
2020-10-10 11:30:29.528 [Verbose] [com.apple.root.utility-qos] [ModelManager.swift:160] store(type:sourceModels:) > updating RLMScene from(0) eligible(0) deleted(0) ignored(0) new(0)
```
Note, I have 4 Real zones defined, not 6 (2 of the zones showing up are the dupes), if I'm reading the logs correctly.

I tried building the app on my Mac (for other reasons) to try and get more information, but (1) I don't have a developer account, and (2) it's failing with missing icons trying to build the watchOS image.  And, (3) I don't know Swift, but I've been a professional developer for > 30 years, so I thought I could muddle through. 👍 

[ ps. Thanks for the quick response. ]

**Comment by nateww** [comment]
The primary HA app has been restarted dozens of time since the zone update, so I have no idea where it's getting the data from, as there is nothing ANYWHERE in the HA app (or MQTT, or the DB) where the zones are defined.

Is there an easy way for me to make a REST call against the HA app to fetch the zones, to verify that HA-core is indeed returning 6 zones?

**Comment by zacwest** [comment]
The Xcode build environment is relatively unstable right now -- Swift Package Manager is necessary for Catalyst but it's full of bugs, the latest Xcode builds are missing the images necessary for CoreNFC, etc. The [README](https://github.com/home-assistant/iOS/blob/master/README.md) has some of the workarounds necessary. You shouldn't need a paid developer account to run in the simulator, though.

The Webhook requires a shared key to send encrypted traffic, so you won't be able to replicate it super easily from the information you have. However, it loads info in a similar way that the REST API does for the [`/api/states/`](https://developers.home-assistant.io/docs/api/rest#get-apistates) endpoint. That should include all of the zones.

**Comment by nateww** [comment]
Making the following request and filtering-in the zones, I verify that there are multiple zones being returned from HA-core, including the duplicates, so I would concur that the iOS app is behaving properly.

```
curl -s -X GET -H "Authorization: Bearer ABCDEFG " -H "Content-Type: application/json" http://ha.local8123/api/states | jq | grep zone\.```
```
Returns (redacted):
```
    "entity_id": "zone.foozone",
    "entity_id": "zone.foozone_2",
...
```

Now I need to figure out where the

**Comment by nateww** [comment]
As @zacwest indicated already, this is not a bug in the iOS app, but it's just returned the bogus data from HA-core.

**Comment by nateww** [comment]
FYI, I had to play games on the UI in Configuration -> Entities and manually delete the `original` zone name, and then after restarting HA (and waiting a bit), the new definitions were renamed to the proper name with the correct definition.

All's well that ends well (thanks again @zacwest !).
