### ISSUE TITLE
NFC Tags can not be scanned iOS 14

### ISSUE THREAD

**Issue by thibmaek** [home-assistant/iOS#1194]
## The problem
Scanning NFC tags with iOS 14 results in `CPSErrorDomain error 2.` message. HA can read/write the tag in the app, but scanning it afterwards does not work.

## Environment

- Home Assistant Core release with the issue: 106.2
- Last working Home Assistant Core release (if known): 
- Operating environment (OS/Container/Supervised/Core): iOS 14, latest version of app
- Integration causing this issue: Tags
- Link to integration documentation on our website: 

## Traceback/Error logs

```txt
CPSErrorDomain error 2.
```

## Additional information
 Using these NFC tags: https://www.aliexpress.com/item/32968995666.html?spm=a2g0s.9042311.0.0.752d4c4d5np2be

**Comment by thibmaek** [comment]
> From the looks of the Apple forums, it seems it's a common problem with iOS 14 and the iPhone 11

Aha, do you have any links?

**Comment by sebaxf** [comment]
I had the same problem after upgrading the device to iOS 14, if we uninstall the app and reinstall the app everything works well, any ideas. so avoid the re-installation?

**Comment by thibmaek** [comment]
Works perfectly for me now with latest stable HA app and iOS. Closing

**Comment by paulandroshchuk** [comment]
@thibmaek hey there,

I know it's been ~5 years so far but I wonder if you had to do something in order to get it fixed? Have you had the same issue since then?

We're currently experiencing the same issue and it just sucks.

**Comment by thibmaek** [comment]
@paulandroshchuk nope never had it again. But I also have an iPhone 16 and iOS 26 by now so no real comparison possible to the original issue.

**Comment by paulandroshchuk** [comment]
That makes sense, thanks for answering, @thibmaek !

Do you remember how long did it last? Do you happen to use lots of advanced app clip experiences back then/now?

We just started experiencing it and want to get it fixed so bad 😬.
