### ISSUE TITLE
Region enter/exit notifications use ID rather than Name

### ISSUE THREAD

**Issue by TomBrien** [home-assistant/iOS#1212]
**iOS device model, version and app version**

Model Name: iPhone Xs
Software Version: 14.2b3 (18B5072f)
App version: 2020.7 (8)

**Home Assistant Core Version**

0.116.4

**Describe the bug**
I recently enabled region enter/exit notifications to debug something else and noticed that the notification returns the zone's entity ID rather than the name. 

The notification seems to be defined by [`sendLocalNotification`](https://github.com/home-assistant/iOS/blob/master/Sources/Shared/API/HAAPI.swift#L586-L604) although I can't find anywhere that calls that function... This is using the `Name` key which according to [the model](https://github.com/home-assistant/iOS/blob/master/Sources/Shared/API/Models/RealmZone.swift#L204-L210) should either return the `FriendlyName` or essentially strip it out of the entity ID. I've had a look in the backup of my Realm and all the `FriendlyName`s are `null` but the fallback doesn't seem to be working.

**To Reproduce**
1. Enable region enter/exit notifications
2. Go for a walk

**Expected behavior**
Notification to contain a human-friendly name with nice capitalisation. 

**Screenshots**

![IMG_1586](https://user-images.githubusercontent.com/12411302/96443367-6a72a700-1204-11eb-8f97-60eeeccd5a21.PNG)

**Additional context**

**Comment by zacwest** [comment]
`sendLocalNotification` is indeed dead code now. This is now executed via `WebhookResponseLocation`'s `UNNotificationRequest`.

**Comment by TomBrien** [comment]
Cheers. I'll look at changing that when I get a chance :). Ta Zac

**Comment by TomBrien** [comment]
Fixed via #1224 (yeah I forgot to tag it in the PR)
