### ISSUE TITLE
Gauge complication outer text doesn't scale to fit

### ISSUE THREAD

**Issue by TomBrien** [home-assistant/iOS#1213]
**iOS device model, version and app version**

Model Name: Series 4 44 mm
Software Version: 7.1b3
App version: 2020.7(8)

**Home Assistant Core Version**

0.116.4

**Describe the bug**
When creating a Gauge Text complication in the Corner position, the text specified for the outer value is doesn't scale to fit the space and clips easily. Some exceptionally crude measuring shows that in the below example the HA complication text (top right) is about the same size as the UV index but the world clock is smaller.

**To Reproduce**
1. Create a gauge text complication with the outer text longer than about 7 _average_ width characters

**Expected behavior**
Font scaled to fit down to some minimum font size

**Screenshots**

![IMG_1588](https://user-images.githubusercontent.com/12411302/96503455-2f479680-124b-11eb-94cb-42a3e329cef5.PNG)
![IMG_1588_markup](https://user-images.githubusercontent.com/12411302/96503458-3078c380-124b-11eb-9bbf-bcdda08d31d9.png)

**Additional context**

**Comment by TomBrien** [comment]
So as that complication got wider as the value changed it did truncate more properly (below) scaling text would be nicer IMHO 
![image](https://user-images.githubusercontent.com/12411302/96511911-a420cd80-1257-11eb-9430-6474b0fd837f.png)

**Comment by zacwest** [comment]
I don't think we can/do know this information. When we configure this all we do is tell the system what text/gauge we want, and it does the layout/positioning.

**Comment by TomBrien** [comment]
Closing as "beyond our control"
