### ISSUE TITLE
Gauge complication outer text forced to upper case

### ISSUE THREAD

**Issue by TomBrien** [home-assistant/iOS#1214]
**iOS device model, version and app version**

Model Name: Series 4 44 mm
Software Version: 7.1b3
App version: 2020.7(8)

**Home Assistant Core Version**

0.116.4

**Describe the bug**
When creating a gauge complication the text is forced to upper case regardless of how it is declared. This changes the meaning in some cases.

**To Reproduce**
1. Create a complication with simple text like `Mb`.
2. When viewed on watch face. both characters are upper case
**Expected behavior**

**Screenshots**

![IMG_1589 (2)](https://user-images.githubusercontent.com/12411302/96504241-59e61f00-124c-11eb-8e59-7dfd918ebc6d.PNG)
![IMG_1588](https://user-images.githubusercontent.com/12411302/96504263-5f436980-124c-11eb-9f48-3faa09e29df3.PNG)

**Additional context**

Seems fine in some other complications. E.g. modular large is fine.

**Comment by zacwest** [comment]
I believe this text behavior is being set by the system. We tell it what text to provide, and it decides to always uppercase.

**Comment by TomBrien** [comment]
Closing as "beyond our control"
