### ISSUE TITLE
Device creates multiple sensors 

### ISSUE THREAD

**Issue by poldim** [home-assistant/iOS#1216]
**Device model, version and app version**

Model Name & macOS Version: 
![image](https://user-images.githubusercontent.com/16869713/96619070-918bb000-12ba-11eb-88d7-186b310b9243.png)

App Version: 
![image](https://user-images.githubusercontent.com/16869713/96622181-7622a400-12be-11eb-928d-3b47d339c90f.png)

Safari Version:
![image](https://user-images.githubusercontent.com/16869713/96619146-a8320700-12ba-11eb-9b4b-9c32fa98cd95.png)

**Home Assistant Core Version**

Home Assistant 0.116.4

**Describe the bug**
Multiple sensors are created.  Potentially this is caused by MacOS changing the computer name.

**To Reproduce**
Install MacOS client.  Change computer name.  Maybe reboot mac or restart HA and new sensors are created.

**Expected behavior**

**Screenshots**

![Developer Tools - Home Assistant 2020-10-20 10-21-12](https://user-images.githubusercontent.com/16869713/96622030-44114200-12be-11eb-8ccc-a91154057de9.jpg)

![Developer Tools - Home Assistant 2020-10-20 10-30-08](https://user-images.githubusercontent.com/16869713/96623009-88e9a880-12bf-11eb-8b1a-41519ea5e642.jpg)

**Additional context**

This used to be a problem on the iOS client but was recently resolved.

**Comment by zacwest** [comment]
The battery sensors I'd expect if you've upgraded through a few betas -- the unique ID backing them has changed a few times now, sorry about that.

Do you have a rough idea when the duplicates were created? It's possible this is solved by #1101 if it happened earlier than 2020.7 (3).

**Comment by zacwest** [comment]
Actually that is probably not it, because it would change the name but not create duplicates.

In Preferences > Sensors, do you see all 3 of the audio+audio+microphone sensors that are reporting there for the monitor?

**Comment by zacwest** [comment]
#1320 should resolve this in 2021.1 (5) or newer.
