### ISSUE TITLE
Don't open the app when interacting with iOS 14 widgets

### ISSUE THREAD

**Issue by rifelpet** [home-assistant/iOS#1227]
**Is your feature request related to a problem? Please describe.**
I have a homescreen widget setup in iOS 14 with buttons that trigger home assistant automations. Before iOS 14 I had the older style widget. I noticed that when tapping a button on the iOS 14 widget, it opens the home assistant app whereas before iOS 14 tapping a button would stay on the widget screen.

I much prefer if the iOS 14 widget buttons do not open the app: Often times the only thing I want to do with home assistant is trigger an automation by tapping the button. Having it open the app means I waste time swiping up to the app switcher to get back to what I was doing. If I'm swiping over to the widget screen directly from the lock screen that causes iOS to either unlock and open the app, or open the passcode prompt, both of which are distracting me from doing what I want to accomplish (open another app or just relock my phone).

Sometimes I want to trigger two automations. With the old widget I could tap both buttons. With the new widget I have to either wait for the app to open after tapping the first button, then tap the equivalent action in the app's dashboard, or swipe up and left back to the widget screen to get back to tapping the second button. 

**Describe the solution you'd like**
It would be great if the iOS 14 widget buttons didn't open the app, or allowed that to be configurable somehow.

**Additional context**

Thanks for the great app! I'm really loving the home assistant experience so far.

**Comment by TomBrien** [comment]
Sadly this is a feature of iOS 14 that interacting with a (non-Apple) widget opens the associated app. Currently it appears beyond our control. I agree it's super annoying!

**Comment by TomBrien** [comment]
Closing this as "beyond our control" but rest assured if Apple make it possible for use to _fix_ this it will get pushed out quickly

**Comment by rifelpet** [comment]
Understood, thanks for the prompt response!

**Comment by zacwest** [comment]
For iOS 14 I also added the "Perform Action" shortcut, as well as making the Shortcuts app aware of all of your Actions, so putting together a Shortcuts.app Widget (which has special permissions to not require launching the app) full of HA Actions should be relatively straightforward.
