### ISSUE TITLE
App doesn’t know about 5G

### ISSUE THREAD

**Issue by TomBrien** [home-assistant/iOS#1232]
**iOS device model, version and app version**

Model Name: iPhone 12 Pro
Software Version: iOS 14.2b4
App version: 2020.7(8)

**Home Assistant Core Version**

N/A

**Describe the bug**
When connected to 5G cellular technology reports "unknown technology"

**Screenshots**

![image](https://user-images.githubusercontent.com/12411302/97049696-0ccbbb00-1574-11eb-8e70-5aded2b9f6dd.jpeg)
**Additional context**

**Comment by TomBrien** [comment]
Posting this as a reminder to me. I'm guessing this is a quick fix. I'll try and knock it out tomorrow

**Comment by robbiet480** [comment]
5G isn't available as a constant yet https://developer.apple.com/documentation/coretelephony/cttelephonynetworkinfo/radio_access_technology_constants

(and your file didn't finish uploading)

**Comment by TomBrien** [comment]
Well that's just silly isn't it

**Comment by TomBrien** [comment]
I'm wondering if assuming Unknown = 5G is fair

**Comment by zacwest** [comment]
since the underlying data type is a string, knowing that value may be enough plus-or-minus the different 5g implementations.

**Comment by TomBrien** [comment]
This is what I was going going to try. Just log the string and see. Just spent 20 minutes reading the 5G standard names. It's not a clear cut as LTE.

**Comment by zacwest** [comment]
I believe there are defines for 5G: `CTRadioAccessTechnologyNR` and `CTRadioAccessTechnologyNRNSA`

**Comment by jsiemek** [comment]
CTRadioAccessTechnologyNRNSA-CTRadioAccessTechnologyNR=NSA 😉
