### ISSUE TITLE
request_location_update  push notification rate limits with iCloud3 

### ISSUE THREAD

**Issue by gcobb321** [home-assistant/iOS#1239]
Zac, 
I’m sure you have heard about the change Apple made to verifying iCloud accounts around October 8th. The verification went from a 2-month period to 2-weeks and sometimes doesn’t work at all. Additionally, they made a change so you can not create a new non-2fa account to bypass all the notifications. 

I’m making changes to iCloud3 to better support the iOS app so it provides the same tracking abilities as iCloud location requests in terms of requesting location updates on a variable interval based on the distance from home, the age of the location data, the accuracy of the gps location, etc. 

To do this, iCloud3 will do ‘request_location_update’ mobile_app notifications on a regular basis to determine the phone’s location. Are these requests subject to the rate limits like a normal push notification is? If so, can this request be excluded from the rate limit count?

Thanks and I appreciate the work you and the rest of the people working on the iOS app are doing. 

Contact me offline at geekstergary@gmail.com if you prefer. 

Gary Cobb

**Comment by zacwest** [comment]
`request_location_update` isn't subject to rate limits: https://github.com/home-assistant/mobile-apps-fcm-push/blob/4d61739e4931655671436960c49e3524b9af5d69/functions/legacy.js#L51-L57
