### ISSUE TITLE
Use/Specify Cloudhook to send back actionable notifications

### ISSUE THREAD

**Issue by vajonam** [home-assistant/iOS#1245]
As it stand today, it appears that the external URL is needed to send back response from an actionable notification.  When a user has Nabu Casa integration enabled for Alexa/Google assistants , but remote UI turned off (security reasons), then then means the user cannot send actions when I am far away from the home assistance instance (not at home or vpn disabled). 

The request is the following

- The mobile app registers a cloud hook to send back location/battery information from the iOS app, similarly it can register a different hook for notifications. 

or 

- Provide a webhook URL as part of push notification, so that when it is specified the cloud/webhook is called when an action is pressed.

example push request 
```
{
	"data": {
		"title": "{{payload.foo}}",
		"message": "{{payloab.bar}} - {{payload.alarm}}",
		"data": {
			"push": {
				"category": "zm",
                               "cloudhook":"http://usecloud.com/hook"   # OPTIONAL 
			},
			"action_data": {
				"entity_id": "input_boolean.send_notification_front"
			},
                        "cloudhook:" { 
                                  "_":"http://cloudhook.com/foo"    # Send all actions here, with event object in POST
                                 "ACTION_ONE":"http://cloudhook.com/hook",   # Specific actions to specific hooks
                                 "ACTION_TWO":"http://cloudhook.com/hook",    # Specific actions to specific hooks
                        }
		}

	}
}
```

Possibly we can just register one cloud hook and then send the ACTION_NAME as part of the payload.  The cloud hook can then trigger existing HA events to maintain backward comapt. 

Also this will enable us to use this to integrate to other services that support webhooks.

**Comment by robbiet480** [comment]
The app already registers a Cloudhook and will use it automatically to send data back home, whether sensor or otherwise.

**Comment by vajonam** [comment]
@robbiet480  had a conversation with @zacwest [here]( https://github.com/home-assistant/iOS/pull/709#issuecomment-716890195). It appears that cloudhook is used only when "remote UI" switch is enabled. guess a part of this FR is to decouple that.
