### ISSUE TITLE
Can not connect with Cloud (only int/ext url)

### ISSUE THREAD

**Issue by mvanrijnen** [home-assistant/iOS#1246]
iPhone X
IOS: 14.01
HA Comp.App: 0.116.4
HA Core:  2020.10.0

Can not get the cloud function in the app working. No switch "use cloud" comes visible.
tried all the tips and tricks.

**Comment by TomBrien** [comment]
Please can you confirm the app version you are using, the version you've listed (2020.10) doesn't exist. Do you have "Remote Control" enabled within Home Assistant (Configuration>Home Assistant Cloud)
![image](https://user-images.githubusercontent.com/12411302/97477589-b67dc400-1947-11eb-86fb-fb06a2fb0b6f.png)

Below are the instructions for checking the app version, these should have been in the issue template.
> Please include your device 'Model Name' and 'Software Version' as listed in iOS Settings>General>About. Please also give the app version listed beneath "Home Assistant Companion" in the App Configuration>About menu within the app, please include the number in bracket

**Comment by mvanrijnen** [comment]
> Please can you confirm the app version you are using, the version you've listed (2020.10) doesn't exist. Do you have "Remote Control" enabled within Home Assistant (Configuration>Home Assistant Cloud)
> ![image](https://user-images.githubusercontent.com/12411302/97477589-b67dc400-1947-11eb-86fb-fb06a2fb0b6f.png)
> 
> Below are the instructions for checking the app version, these should have been in the issue template.
> 
> > Please include your device 'Model Name' and 'Software Version' as listed in iOS Settings>General>About. Please also give the app version listed beneath "Home Assistant Companion" in the App Configuration>About menu within the app, please include the number in bracket
it states 0.116.4

HA Core: 2020.10.0 (this is the HA supervisor version)

**Comment by mvanrijnen** [comment]
It works now.
Remote Control was switched on.
I switched off, close app on IOS,  witched remote control on (in HA), and rrestart app on IOS. 
Cloud button now visible

**Comment by TomBrien** [comment]
Glad it working. Thanks for letting us know
