### ISSUE TITLE
App crashes when trying to remove action of unsaved notification category

### ISSUE THREAD

**Issue by kukulich** [home-assistant/iOS#1256]
**iOS device model, version and app version**

Model Name: iPhone Xs
Software Version: 14.1
App version: 2020.7 (11)

**Home Assistant Core Version**

0.117.1

**Describe the bug**

App crashes when trying to remove action of unsaved notification category

**To Reproduce**

1. Create notification category
2. Create one action - name and indentificator are enough
3. Try to remove the action

**Expected behavior**

No crash :)

**Screenshots**

**Additional context**

**Comment by TomBrien** [comment]
Reproduced and submitted logs
