### ISSUE TITLE
Automatic Session Authorisation for Viewing Grafana Panels in Lovelace Webpage Cards.

### ISSUE THREAD

**Issue by Teleportist** [home-assistant/iOS#1259]
**Problem**
I have a number of panels created in Grafana, which are set up to be visible as webpage cards in Lovelace.

This all works well when viewing through a browser on my windows PC. However, these are not immediately visible using the companion app on my iPhone 10 without first having to open Grafana from the sidebar, to enable authorisation for the session.

**Requested Solution**
Functionality aligned with typical web browsers.
i.e. the companion app to be able to set up the authorisation automatically, without the extra step of the user needing to open Grafana from the sidebar first.

Thank you.

**Comment by TomBrien** [comment]
This sounds like something similar to a report on discord. Can you let us know in if the panels work when viewing your home assistant via safari on your iPhone.

**Comment by Teleportist** [comment]
Pasting the same address in to Safari returns the same "401: Unauthorised" error previously seen in the HA App before opening Grafana.

So this could be more of an iOS limitation than one with the companion app maybe?

**Comment by zacwest** [comment]
If this is happening in iOS 14, can you try enabling the Cross-Site Tracking setting in the system Settings app > Home Assistant?

**Comment by Teleportist** [comment]
Enabling Cross-site Tracking has no effect unfortunately.

**Comment by TomBrien** [comment]
This sounds like it might be related to something that came up [on discord the other day](https://discordapp.com/channels/330944238910963714/551871772484698112/771486407192870913), there was a fix applied by the Grafana team here: grafana/grafana#28695

**Comment by Teleportist** [comment]
Thanks Tom.

So I see a fix is intended for 7.3.2., so fingers crossed.

**Comment by kzaoaai** [comment]
I’m using HA container with Grafana as a separate docker container. The Grafana dashboards I set up work fine on Safari and Chrome, just not in the iOS app.

**Comment by tomlut** [comment]
> there was a fix applied by the Grafana team here: [grafana/grafana#28695](https://github.com/grafana/grafana/issues/28695)

No That is a separate issue when viewing single graphs in grafana itself. 

This issue is about seeting up authorisation between grafana and home assistant.
