### ISSUE TITLE
Small graphical glitch when starting the app or reloading a view

### ISSUE THREAD

**Issue by kersten-lohmeyer** [home-assistant/iOS#1260]
See screenshot.

Model Name: iPhone 12 (pretty sure it was the same on iPhone 11)
Software Version: 14.1
App version: 2020.7 (11)
HA Version: 0.117.2

Small graphical glitch when starting the app or reloading a view

![IMG_0016](https://user-images.githubusercontent.com/61520094/98018596-06093780-1e01-11eb-9cfa-fde20470e260.jpeg)

**Comment by deluxestyle** [comment]
I do have the same issue

**Comment by TomBrien** [comment]
Do you see the same on safari in iOS?

**Comment by kersten-lohmeyer** [comment]
> Do you see the same on safari in iOS?

Yes

**Comment by deluxestyle** [comment]
we should maybe open a defect in home assistant frontend

**Comment by deluxestyle** [comment]
I opened a defect: https://github.com/home-assistant/frontend/issues/7602

**Comment by TomBrien** [comment]
As this reproduces in Safari it is a front end issue (probably to do with the new compact header). Not much we can do here so I will close
