### ISSUE TITLE
Translation Error:  Intl.PluralRules is not available in this environment

### ISSUE THREAD

**Issue by rbron01** [home-assistant/iOS#1263]
Model Name: iPhone 6 Plus 
Software Version: iOS 12.4.8
App version: 2020.7 (11)

**Home Assistant Core Version**
0.117.2

**Describe the bug**
In Lovelace Entites Card when choosing secondary_info last-changed you get the error on the secondary_info Line.  Under iOS 14 on my iPad it doesn't come up. This is since the last change.

**To Reproduce**

**Expected behavior**
Date since last refresh.

**Screkenshots**
First one: iOS 12 with error
Second one: iOS 14 correct wo error

![05943DC6-2218-4A77-8BA8-57F3D9DE36BD](https://user-images.githubusercontent.com/61490695/98183573-b9108880-1f08-11eb-8e1b-44abefcb903f.png)
![676595F3-D8EE-4941-9937-2C02CD5A4DD3](https://user-images.githubusercontent.com/61490695/98183415-5dde9600-1f08-11eb-9091-cb070d45c4b3.png)

**Additional context**

**Comment by TomBrien** [comment]
Do you see the same error in safari on your iPad?

**Comment by rbron01** [comment]
iPad no problem in iPadOS 14
But on iPhone with iOS 12 yes same issue.

**Comment by TomBrien** [comment]
As you see this in Safari too, this sounds like an issue with the frontend but before creating an issue worth checking that going to App Configuration and at the bottom try resetting the frontend cache

**Comment by rbron01** [comment]
Tried the reset of the cache wo any luck.
Still the same issue.

**Comment by rbron01** [comment]
Fyi. This is the full error message:
Translation Error: Intl.PluralRules is not available in this environment. Try polyfilling it using "@formatjs/intl-pluralrules"

**Comment by zacwest** [comment]
This appears to be an error in the frontend and not in the iOS app.

**Comment by TomBrien** [comment]
Actually this is the same as home-assistant/frontend#7551 appears to be an issue with Safari that shipped in iOS 12. A fix was merged in home-assistant/frontend#7575
