### ISSUE TITLE
iPhone / iPad does not reconnect when Home Assistant is restarted

### ISSUE THREAD

**Issue by nenadmilano** [home-assistant/iOS#1265]
**iOS device model, version and app version**
Model Name: iPad Air 2 / iPhone 6
Software Version: iOS 14.2 / iOS 13.6.1
App version: 2020.7(11)

**Home Assistant Core Version**
0.117.2

**Describe the bug**
If Home Assistant is restarted, my iPads and iPhones don‘t reconnect automatically and need a manual refresh (pull-down). The Setting „Automatically close connection“ is OFF but it seems that the reconnect is still not happening properly. Was working in 0.116 flawlessly but now i have to manually refresh all Wall mounted iPads and iPhones manually.

**To Reproduce**
Reboot Home Assistant

**Expected behavior**
Apps should automatically reconnect and display the Lovelace Dashboard

**Screenshots**
-

**Additional context**
-

**Comment by tane64** [comment]
Same problem here with the iPad.  
Also iPad will often disconnect after few hours while HA is still running. 

Some kind of auto refresh is welkom.

**Comment by JoelMSawyer** [comment]
Also experiencing this on a fairly old iPad Mini 2, running ios 12.

**Comment by zacwest** [comment]
home-assistant/frontend#7732
