### ISSUE TITLE
add time_zone aware attribute 'last_seen'

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/iOS#1266]
**Is your feature request related to a problem? Please describe.**

trying to replace as much custom components/integrations with core as possible, I am stuck here, using the Composite integration which allows me to use an attribute last_seen and calculate the timezone difference between home and the tracker:
```
      marijn_tz_offset:
        friendly_name: Marijn time zone offset
        unit_of_measurement: hr
        value_template: >
          {% set state = states.device_tracker.me %}
          {% if state.attributes is not none and
                state.attributes.time_zone is not none and
                state.attributes.time_zone != 'unknown' %}
            {% set n = now() %}
            {{(n.astimezone(state.attributes.last_seen.tzinfo).utcoffset() -
               n.utcoffset()).total_seconds()/3600}}
          {% else %}
            undetermined
          {% endif %}
```

**Describe the solution you'd like**

the above solution, but using an additional attribute to the current set of attributes for the device_tracker.

**Additional context**
https://community.home-assistant.io/t/how-to-get-to-or-template-last-seen-on-person-or-companion-app-sensors/242988

and

https://github.com/pnbruckner/ha-composite-tracker#time-zone-examples

further info:

though the sensor  geocoded_location has the Time Zone attribute:

<img width="1112" alt="Schermafbeelding 2020-11-08 om 13 27 45" src="https://user-images.githubusercontent.com/33354141/98464904-4df3da00-21c6-11eb-8905-be6b64e9dd57.png">

we cant use the utc_offset filter on it like in the offset template above like:
```
{{(n.astimezone(state_attr('sensor.calltheboss_geocoded_location','Time Zone')).utcoffset() -
               n.utcoffset()).total_seconds()/3600}}
```

because of the type error:

<img width="1369" alt="Schermafbeelding 2020-11-08 om 13 31 38" src="https://user-images.githubusercontent.com/33354141/98465012-bfcc2380-21c6-11eb-869d-b55208e4c0a6.png">

so an time_zone aware attribute last_seen would be very much appreciated.
thanks for considering

**Comment by zacwest** [comment]
Is there a particular reason that you can't use the device_tracker's last_updated/last_changed?

**Comment by Mariusthvdb** [comment]
well, I thought I had described that reason above? 

In need of a timezone aware attribute, to be able to calculate the time difference between a traveling tracker and the home instance. Last_changed wouldn't be useful since the tracker wouldn't need to have changed at all, and yes I did look at last_updated, but that isn't timezone aware is it?

did have a go at this:
```
          {% set state = states.device_tracker.calltheboss %}
          {{(state.last_updated.astimezone().utcoffset() -
            now().utcoffset()).total_seconds()/3600}}
```

but I am not very confident it does what I seek it to do, and I can't test it because I am at Home ;-)

**Comment by zacwest** [comment]
I guess I'm not understanding what this would do to augment the device tracker. Are you looking for a new entity from the device for its current time zone?

**Comment by Mariusthvdb** [comment]
> Are you looking for a new entity from the device for its current time zone?

Not a new entity per se, an attribute 'last_seen' for the existing device_tracker would do the job. I did have a look at the last_seen of the life360 integration but that too doesn't seem to be timezone aware
