### ISSUE TITLE
Active sensor should be 'off' when application terminates due to shut down, logout, etc.

### ISSUE THREAD

**Issue by PierreScerri** [home-assistant/iOS#1270]
**Is your feature request related to a problem? Please describe.**

When MacOS shuts down, the state of the iMac in HA remains On. This makes some automations based on this sensor ineffective.  e.g. an automation to turn off a light when the iMac is not active would not work when the iMac is shutdown.

**Describe the solution you'd like**

The app would detect a shutdown command and update the sensors accordingly.

**Additional context**

**Comment by arehsan** [comment]
It is the same behavior when logging out. I think it would be nice to change the active-state when quitting the app, not just at shutdown.
