### ISSUE TITLE
App crashes on startup

### ISSUE THREAD

**Issue by davidclemens** [home-assistant/iOS#1272]
**iOS device model, version and app version**
Model Name: iPhone Xs
Software Version: 14.0.1
App version: 2020.7 (I don't know the build number since I can't launch the app)

**Home Assistant Core Version**

0.117.5

**Describe the bug**
When launching the app (by tapping the app icon or running actions from widgets or reopening from the app switcher) it shows the opening animation and then immediately crashes (see [screen recording](https://www.dropbox.com/s/l688866vexonkgn/HA%20Companion%20Crash.mov?dl=0)).

**To Reproduce**
This will probably be hard to reproduce. I have no pointers.

**Expected behavior**
A nominal app launch.

**Screenshots**
![Console Output](https://user-images.githubusercontent.com/43437141/98734044-b814a680-23a1-11eb-86c7-9091bdf07584.png)

**Additional context**
With the help of the great Discord server I did some debugging via the macOS Console app:
Home Assistant seems to be started correctly by the 'Springboard' and later the 'runningboardd' processes. HA is then killed by the 'mediaserverd' process "because client is not allowed to play in the background AND does not continue AirPlaying video when device locks" (see screenshot)

On my dashboards I don't have any media (audio or video) to be played. Only a GIF and images. So it seems strange that the HA Companion app should try to play media.

Edit: I just noticed that push notifications are still coming through. If tapped, the app tries to launch but crashes as described above.

I recently updated HA Core from 0.115 to 0.117.5. This will hardly be the problem since everything worked fine for at least half a day.

HA works fine via the browsers. The HA iOS Companion apps on 2 different devices work fine (iPhone 5s with HA Companion 2020.7 (11) on iOS 12.4.8 and iPad mini 2 with HA Companion 2020.7 (11) on iOS 12.4.8).

Thanks for your help in advance!

**Comment by TomBrien** [comment]
I think David has summed up everything perfectly but for what it's worth [link to Discord chat](https://discord.com/channels/330944238910963714/551871772484698112/775705450447765554)

**Comment by zacwest** [comment]
I'm not sure the core media line there is what's killing the app; that's likely stopping an audio playback session and not the app. What would be helpful is to see the crash log from the device.

Crash Logs can be found in the system Settings app > Privacy > Analytics > Analytics Data. Look for something like `Home Assistant` in the file name.

**Comment by davidclemens** [comment]
I sent the crash logs your way.

Well the issue title would be very misleading then. Will have to change that.

Thanks for looking into this.

**Comment by zacwest** [comment]
Symbolicated crash log:

```
Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libsystem_kernel.dylib        	0x00000001c88b798c __pthread_kill + 8
1   libsystem_pthread.dylib       	0x00000001e3edfc74 pthread_kill + 272
2   libsystem_c.dylib             	0x00000001a5a88bb4 abort + 104
3   libc++abi.dylib               	0x00000001b0affe24 __cxxabiv1::__aligned_malloc_with_fallback+ 65060 (unsigned long) + 0
4   libc++abi.dylib               	0x00000001b0af141c demangling_terminate_handler+ 5148 () + 284
5   libobjc.A.dylib               	0x00000001b0a00720 _objc_terminate+ 42784 () + 148
6   libc++abi.dylib               	0x00000001b0aff2a8 std::__terminate(void (*)+ 62120 ()) + 20
7   libc++abi.dylib               	0x00000001b0aff234 std::terminate+ 62004 () + 44
8   Shared                        	0x000000010105fd68 realm::ObjectSchema::ObjectSchema(realm::Group const&, realm::StringData, realm::TableKey) + 2506088 (_$s10PromiseKit0A0Cy6Shared21WebhookUpdateLocationCGACyxGAA8ThenableAAWl:110)
9   Shared                        	0x0000000101066798 realm::ObjectStore::schema_from_group(realm::Group const&) + 2533272 (_$sSo13NSURLResponseCMa:755)
10  Shared                        	0x000000010107af80 realm::Realm::read_schema_from_group_if_needed() + 2617216 ($ss17_NativeDictionaryV8capacityAByxq_GSi_tcfCSS_6Shared17ServiceDefinitionCTg5:205)
11  Shared                        	0x000000010107ad98 realm::Realm::Realm(realm::Realm::Config, realm::util::Optional<realm::VersionID>, std::__1::shared_ptr<realm::_impl::RealmCoordinator>, realm::Realm::MakeSharedTag) + 2616728 ($ss17_NativeDictionaryV8capacityAByxq_GSi_tcfCSS_6Shared17ServiceDefinitionCTg5:69)
12  Shared                        	0x000000010103b12c protocol witness for Collection.index(_:offsetBy:limitedBy:) in conformance String + 2355500 (_$sSo13UIWindowLevelaSQSCSQ2eeoiySbx_xtFZTW:389)
13  Shared                        	0x0000000101039da8 realm::_impl::RealmCoordinator::do_get_realm(realm::Realm::Config, std::__1::shared_ptr<realm::Realm>&, realm::util::Optional<realm::VersionID>, realm::util::CheckedUniqueLock&) + 2350504 ($sSp14moveInitialize4from5countySpyxG_SitFs9CodingKey_p_Tg5:301)
14  Shared                        	0x0000000101039b54 realm::_impl::RealmCoordinator::get_realm(realm::Realm::Config, realm::util::Optional<realm::VersionID>) + 2349908 ($sSp14moveInitialize4from5countySpyxG_SitFs9CodingKey_p_Tg5:264)
15  Shared                        	0x000000010107b6f8 realm::Realm::get_shared_realm(realm::Realm::Config) + 2619128 ($ss17_NativeDictionaryV8capacityAByxq_GSi_tcfCSS_6Shared17ServiceDefinitionCTg5:144)
16  Shared                        	0x0000000101109768 reflection metadata field descriptor L10n.Watch.Labels.ComplicationTemplate.ExtraLargeStackText + 3200872 (_$s6Shared4L10nO8WhatsNewO10TwoDotZeroO5ItemsO31InAppNotificationCategoryEditorOMF:504)
17  Shared                        	0x00000001012f2494 Realm.init(configuration:queue:) + 5203092 (_$s6Shared18AuthRequestMessageC10CodingKeys33_7033756FEE3130C01B9317022FC66F58LLOSQAAMc:92)
18  Shared                        	0x0000000100e82d8c closure #1 in variable initialization expression of static Realm.live + 552332 (Realm+Initialization.swift:153)
19  Home Assistant                	0x00000001003cca38 specialized AppDelegate.setupModels() + 674360 (AppDelegate.swift:705)
20  Home Assistant                	0x00000001003c2090 AppDelegate.application(_:willFinishLaunchingWithOptions:) + 630928 (AppDelegate.swift:92)
21  Home Assistant                	0x00000001003c24c8 @objc AppDelegate.application(_:willFinishLaunchingWithOptions:) + 632008 (<compiler-generated>:0)
22  UIKitCore                     	0x000000019f29c9d8 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 216
23  UIKitCore                     	0x000000019f29eac4 -[UIApplication _callInitializationDelegatesWithActions:forCanvas:payload:fromOriginatingProcess:] + 5136
24  UIKitCore                     	0x000000019f2a4478 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1244
25  UIKitCore                     	0x000000019e935db0 -[_UISceneLifecycleMultiplexer completeApplicationLaunchWithFBSScene:transitionContext:] + 216
26  UIKitCore                     	0x000000019f2a02f0 -[UIApplication _compellApplicationLaunchToCompleteUnconditionally] + 68
27  UIKitCore                     	0x000000019f2a0710 -[UIApplication _run] + 1036
28  UIKitCore                     	0x000000019f2a5e10 UIApplicationMain + 168
29  Home Assistant                	0x00000001003320a4 main + 41124 (ConnectInstanceViewController.swift:50)
30  libdyld.dylib                 	0x000000019c5c3e60 start + 4
```

I'm not sure what is going on here, but Realm is our database layer and it's crashing. You may need to delete and reinstall the app to get it working again.

**Comment by davidclemens** [comment]
Interesting. Was your symbolicated log from the Home Assistant crash logs or the HA widget logs?

I did reinstall the app and this solved the issue for now.
And great work on your side eliminating another onboarding process! Magic! Everything was there as I left it.

Thank you!

**Comment by Grimidor** [comment]
I have the same issue. For me it's connected to the the location services. If go to _settings -> Home Assistant_ and disables the use of location data (_Never_ or _Ask Next time_) it stars working and I can use the app. If I enable the use of location data (_Always_ or _When using the app_) it stops working again.
BUT! It works in the _Always_ and _When using the app_ mode IF I disabled _Exact position_ option.

Do you have the same symptoms?

**Comment by zacwest** [comment]
@Grimidor Your issue sounds different than this ticket's. You are likely feeling the results of #1267 which will be fixed in the next release; you can be sure this is what you're feeling by checking how many zones you have. If you've got a bunch, and many of them are within the same area around you, it's likely that issue.

**Comment by Grimidor** [comment]
@zacwest Might be. I have 3 zones around me with just a few 100 meters between them. I will just wait until the next update and see if it goes away. :-). Thanks for steering me in the right direction.

**Comment by bgoncal** [comment]
Is this still an issue with latest versions of app and core? Feel free to reopen if needed
