### ISSUE TITLE
Home Assistant mobile App on iOS does NOT allow to access HA in a local area network.

### ISSUE THREAD

**Issue by skumka** [home-assistant/iOS#1273]
##  Home Assistant mobile App on iOS does NOT allow to access HA in a local area network.

I cannot access HA from my iPhone when on home Wifi using HA Mobile App.
I am receiving the message stating that the server is not certified. Even accepting the risk and choosing "Use Anyway" HA is not starting.

The local server address is filled well.
SSIDs' names of local Wifi is properly added.

Everything works well if not in the local network.

HA versions: 0.115.x, 0.116.x

**Comment by TomBrien** [comment]
Can you let us know what address is shown in App Configuration>Connection for your internal and external URLs. Please blank out personal details

**Comment by skumka** [comment]
Hi.
I have the address https://192.168.1.8:8123 

For external: https://skumka.duckdns.org:1919.  (and I have a port forwarding set on my router to 192.168.1.8 and port 8123)

**Comment by TomBrien** [comment]
`https://` is not valid for internal (unless you have a certificate specifically for internal use). Changing that to `http://192.168.1.8:8123` should fix your problem. Did you manually add that address or did the app pull your `internal_url` automatically?

**Comment by skumka** [comment]
yes, I filled it in manually since after installing App it did not connect to my HA.
Interesting thing is that https worked for about 2 weeks, and after I think 115.2 it stopped...

**Comment by TomBrien** [comment]
It may have changed in an iOS update maybe? iOS can be very strict about certificates and it's quite possible they doubled down on it. Let me know if changing to `http://` resolves the issue.

**Comment by skumka** [comment]
I have just checked. I am logged into my home network. SSID of wifi is the one in app.
Using http only I cannot run HA in the app

**Comment by skumka** [comment]
The message is strange since I am connected to sla1 wifi....
<img width="552" alt="image" src="https://user-images.githubusercontent.com/71942616/99109169-affa7800-25e8-11eb-957c-fb8c26607900.png">

**Comment by skumka** [comment]
this is my screen when opening the app in local network
<img width="552" alt="image" src="https://user-images.githubusercontent.com/71942616/99109345-f94ac780-25e8-11eb-9646-6604370f69e4.png">

**Comment by skumka** [comment]
I discovered what the issue is.
When I remove SSID names and use http it works.
Issue is that SSID names does NOT work.
I have checked 3 times if the names are properly filled in. They were.
Said that it looks that condition checking those names is not working in HA

**Comment by zacwest** [comment]
The error you are receiving when saving the internal URL there is telling you it is unable to connect. The SSIDs are used to try and decide when to use the internal URL; since it is unable to connect it will be unable to connect.

What happens when you open your local URL in the browser, without using https?

**Comment by skumka** [comment]
As you can see on my screenshots above I am connected to wifi. Signal is max. I am connected to one of the network which is specified by SSID.
It is enough to remove those SSID names and all works.

**Comment by TomBrien** [comment]
Sorry meant to post back this morning but day got away from me. I did some testing and when I add an internal address (`http://ip:8123`) I get the say error as you if I ignore it and tap use anyway, I get the red 'connection lost' banner but when I return to the dashboard all works. Connection settings show I am using my internal address. 

Summary: setting the internal address is working for me but there are some misleading warnings.

**Comment by TomBrien** [comment]
If you add the SSID and use `http://homeassistant.local:8123` does it work? That address might not work on your network mind so worth checking in a browser

**Comment by skumka** [comment]
I did the following test:
I am connected to my local network.
I filled in http address (https://192.168.1.8:8123) and SSID name (sla1) - HA Mobile App does NOT work - blan screen
i just removed SSID name - HA Mobile App  works

My conclusion is that somehow filling name of SSID casues issue

**Comment by TomBrien** [comment]
I just checked using `https://` and adding the SSID and it works here all be it with the erroneous saving error and a red banner about the certificate being invalid. As Zac suggested above can you try opening <http://182.168.1.8:8123> in a browser on your phone? Does that work?

**Comment by grivescorbett** [comment]
Hey all I'm having the same issue. Using http://192.168.1.200:8123 as internal URL, external access not setup. Can't access via safari on my phone though so I don't think this is necessarily an HA issue, but I can't figure out why not.

**Comment by JDStudiosAuto** [comment]
I can't log in using local IP in a browser on a computer either

**Comment by grivescorbett** [comment]
Oh this was super weird, ended up fixing itself when I set my server to
DHCP as opposed to static IP. Honestly no idea why that worked.
