### ISSUE TITLE
Home Assistant macOS App quits unexpectedly.

### ISSUE THREAD

**Issue by Gio76** [home-assistant/iOS#1274]
**Device model, version and app version**

Model Name: iMac (Retina 4K, 21.5-inch, 2017)
macOS Version: macOS Big Sur version 11.01 (issue started occurring already on macOS Catalina)
App Version: 2020.7 (10) Mac & iOS
Safari Version: Version 14.0.1 (16610.2.11.51.8)

**Home Assistant**

arch | x86_64
-- | --
chassis | vm
dev | false
docker | true
docker_version | 19.03.12
hassio | true
host_os | HassOS 4.16
installation_type | Home Assistant OS
os_name | Linux
os_version | 5.4.75
python_version | 3.8.6
supervisor | 2020.11.0
timezone | Asia/Bangkok
version | 0.117.6
virtualenv | false

**Describe the bug**
When I try launching the HA Companion App for macOS, I keep getting the error message 'Home Assistant quit unexpectedly' (see below screenshot).

**To Reproduce**
This will probably be hard to reproduce. I have no pointers.

**Expected behavior**
A nominal app launch.

**Screenshots**

![image](https://user-images.githubusercontent.com/26906928/99138452-2b990b00-2663-11eb-8153-08247e1fb0bc.png)

**Additional context**

This issue started occurring already in macOS Catalina, after updating HA to 0.117.0. I have tried a million times to uninstall the HA Companion app and then re-installing it (making sure to copy it to the Application Folder) but that has not solved the issue. I am able to access HA from any browser, that works perfectly. My iOS app also works perfectly. I do not have any errors showing in the logs.

**Crash Report**
See below Zipped file for the latest crash report:
[Home Assistant_2020-11-14-102118_Gios-iMac.crash.zip](https://github.com/home-assistant/iOS/files/5540128/Home.Assistant_2020-11-14-102118_Gios-iMac.crash.zip)

**Comment by zacwest** [comment]
If you trash the `~/Library/Group Containers/group.io.robbie.homeassistant/dataStore` folder it will stop crashing; the database is having some kind of issue, unfortunately.

**Comment by Gio76** [comment]
@zacwest that worked!!!. Thank you SO MUCH for the prompt reply and for solving my issue, really appreciated!
