### ISSUE TITLE
iOS HA Complication not showing in list

### ISSUE THREAD

**Issue by matthew-larner** [home-assistant/iOS#1281]
Model Name: 
Software Version: iOS 14.1 / Watch OS 7.1
HA App version: 0.117.6

**Home Assistant Core Version**
Home Assistant 0.117.6

**Describe the bug**
The HA complication isn't showing on the apple watch. The complication I'm referring to is the one that shows all the actions you have setup. I've tried uninstalling/resetting/reinstalling the app on the connected iPhone.

**Comment by TomBrien** [comment]
Do you mean the App Icon complication? Any complication you create will open the action list when tapped. However, the icon currently isn't available as per #525

**Comment by matthew-larner** [comment]
> Do you mean the App Icon complication? Any complication you create will open the action list when tapped. However, the icon currently isn't available as per #525

I'm referring to the complication that when tapped open the actions menu like this: https://community-assets.home-assistant.io/original/3X/4/a/4a305ac7d4c683601b9e65c03cda3a40d9aad560.png

I can't see that complication in the list at all anymore. It used to be there with the HA app icon.
