### ISSUE TITLE
Check if ethernet connecton is present

### ISSUE THREAD

**Issue by phischmi** [home-assistant/iOS#1282]
Hi all,
i'd like to trigger an automation when my MacBook is connected to the internet via ethernet.
Background is that my desk lamp also acts as a night light and switches off, when no motoin is detected for 3 minutes. When sitting at my desk i'd like to keep the light on even if I'm not moving on my chair :)
Best way to detect if I'm sitting at the desk is to check wheter the MacBook is connected via ethernet or not.
Would that be possible?

**Comment by LucasJanin** [comment]
Previously requested
https://github.com/home-assistant/iOS/issues/1184
