### ISSUE TITLE
Companion app stuck on "Connection lost.  Reconnecting..." after HA upgrades

### ISSUE THREAD

**Issue by iankaufmann** [home-assistant/iOS#1283]
**Device model, version and app version**
Model Name: MacBook Pro (Retina, 13-inch, Early 2015) & (16-inch, 2019)
Software Version: 10.15.7
App version: 2020.7 (10)

**Home Assistant Core Version**
0.118.0

**Describe the bug**
Ever time I upgrade Home Assistant Core, the companion app on both machines that I have it running on will be stuck on "Connection lost.  Reconnecting...", and won't post sensor updates until you quit the app and re-open it.

**To Reproduce**
Keep the app open while upgrading HA.

**Expected behavior**
For the companion app to reconnect once HA Core is back online

** Additional context**
I don't think this has always happened... but it has for all upgrades since around .0116 and forward.  It actually took me a while to correlate it to HA upgrades.  I thought it was happening randomly, but then I realized after going on vacation for a couple weeks and not running any HA updates during that time, that both machines went the entire time without it happening, but then started happening once we got back (and I started keeping up with updates once again).

**Comment by zacwest** [comment]
Can you confirm if this sounds like home-assistant/frontend#7732?

**Comment by iankaufmann** [comment]
After playing around with it today I think it does sound like that.  It seems to have trouble reconnecting even if I disable wifi for a while and then reconnect.  Sorry for the duplicate issue.

**Comment by jazzmonger** [comment]
I had same issue stuck on "Connection lost. Reconnecting..." today on MACOS app (Catalina 10.15.7) after the 202.12.1 upgrade.  Also the app is VERY sluggish compared to Safari via browser.  clicking on a cam takes 4-5 seconds for image to appear vs instant on Safari.
