### ISSUE TITLE
Home Assistant Companion for MAC, Node-Red Function Node Scrolling Issue

### ISSUE THREAD

**Issue by Mossi777** [home-assistant/iOS#1290]
Model Name: iMac (Retina 5K, 27-inch, 2019)
macOS Version: macOS Big Sur version 11.-.1 (20B29)
App Version: Home Assistant Companion 2020.7 (9) & (10)
Safari Version: Version 14.0.1 (16610.2.11.51.8)

**Home Assistant Core Version**

System Health

Home Assistant Core Integration

version: 0.118.2
installation_type: Home Assistant OS
dev: false
hassio: true
docker: true
virtualenv: false
python_version: 3.8.6
os_name: Linux
os_version: 4.19.127-v8
arch: aarch64
timezone: Europe/London

Home Assistant Cloud

logged_in: false
can_reach_cert_server: ok
can_reach_cloud_auth: ok
can_reach_cloud: ok

Home Assistant Supervisor

host_os: HassOS 4.17
update_channel: stable
supervisor_version: 2020.11.0
docker_version: 19.03.12
disk_total: 57.8 GB
disk_used: 7.1 GB
healthy: true
supported: true
board: rpi4-64
supervisor_api: ok
version_api: ok
installed_addons: Samba share (9.3.0), Node-RED (7.2.10), File editor (5.2.0), Mosquitto broker (5.1), Terminal & SSH (8.9.1), Duck DNS (1.12.4), TasmoAdmin (0.13.1), motionEye (0.10.2)

Lovelace

dashboards: 1
mode: storage
views: 5
resources: 1

**Describe the bug**
When scrolling within the Function node in Node-Red, the screen does not scroll using the mouse.  Scrolls ok using the arrow keys.  This does not happen when accessing Home Assistant via Safari.

**To Reproduce**
The issue is repeatable as above.

**Expected behavior**
Should be able to scroll within the Function node

**Screenshots**
See attached video showing issue when mouse scrolled.

**Additional context**
None

[Screen Recording 2020-11-23.mov.zip](https://github.com/home-assistant/iOS/files/5583261/Screen.Recording.2020-11-23.mov.zip)

**Comment by nic0dk** [comment]
same goes for using vs code addon

**Comment by SildeHoop** [comment]
and for esphome addon

**Comment by zacwest** [comment]
#1059
