### ISSUE TITLE
Use scripts as widgets 

### ISSUE THREAD

**Issue by Darkwolf1515** [home-assistant/iOS#1291]
I have a script I cannot convert into a scene, and that would be perfect for a widget, sadly, they don’t support scripts, can we please add them as an option?

**Comment by zacwest** [comment]
You can create an automation which triggers a script call via an action. Since scripts often have input parameters, it is not feasible to create automatic actions from them.

**Comment by Darkwolf1515** [comment]
Right, did that, now how do I make that an ios widget?

**Comment by Darkwolf1515** [comment]
Got it working by

-Making a blank ios action
-creating an automation to trigger the script every time the button is pressed

This feels overly complex to just run a script with an iphone widget

**Comment by iamarealperson1** [comment]
> Got it working by
> 
> -Making a blank ios action -creating an automation to trigger the script every time the button is pressed
> 
> This feels overly complex to just run a script with an iphone widget

Can you explain "making a blank ios action"?

I am trying to achieve the same thing as you. I have a script that works but need a way to call it from a widget button on my phone.
