### ISSUE TITLE
Connect to different URLs based on SSID

### ISSUE THREAD

**Issue by jonassam1** [home-assistant/iOS#1292]
I have two sites with Home Assistant. I would really love if the app would have different internal URLs based on the SSID my phone is connected to. So, if I my phone is connected to the SSID of site#1 it would use one URL, if it is connected to the SSID of site#2 it would use a different one. Of course, the external URL would always be the same.

As it is now, the iOS companion app is always connected to one of my sites, and I have to access the other using the web browser which is kind of annoying.

Best regards,
Jonas

**Comment by zacwest** [comment]
This feels like a request more appropriate for #161.
