### ISSUE TITLE
Automatically detect the remote url if Nabu Casa url entered for external url

### ISSUE THREAD

**Issue by balloob** [home-assistant/iOS#1296]
**Is your feature request related to a problem? Please describe.**

Entering the cloud url as external url gives an error that the app will automatically detect the Remote UI:

<img width="339" alt="image" src="https://user-images.githubusercontent.com/1444314/101408159-4e25e900-38dc-11eb-971d-51af092edf18.png">

**Describe the solution you'd like**

Instead of showing the error, fetch the `get_config` webhook to update the info. 

How often do we fetch this info btw (the automatic detect part)? I searched for `GetConfig` in the repo and could only find it being called during onboarding.

**Additional context**

**Comment by TomBrien** [comment]
Agree that this makes more sense. Just checked in my production instance and the Remote UI connection is checked (and set it enabled) on any app opening (including soft open from background)

**Comment by zacwest** [comment]
We update the registration which should be delivering us the cloudhook/etc. but there may be an issue where the integration doesn't get updated with it after cloud is enabled, or remote UI is toggled, maybe?

**Comment by balloob** [comment]
[`update_registration` code](https://github.com/home-assistant/core/blob/dev/homeassistant/components/mobile_app/webhook.py#L330)

[`get_config` code](https://github.com/home-assistant/core/blob/dev/homeassistant/components/mobile_app/webhook.py#L544)

As you can see in `get_config`, it includes `remote_ui_url` and `cloudhook_url`. Noticing now that it is not creating a cloudhook url if it doesn't exist there. That's something I should fix. Cloudhooks are only created when creating the registration ([source](https://github.com/home-assistant/core/blob/dev/homeassistant/components/mobile_app/http_api.py#L68-L71)).

I can update the webhook so that we create the cloudhook when we request the config. Or maybe even when we update the registration we include all the config too?

**Comment by zacwest** [comment]
`get_config` is called pretty regularly (via [`Connect(reason:)`](https://github.com/home-assistant/iOS/blob/2920ffc98dc30ca65cd60bd170de185cc664bdbc/Sources/App/LifecycleManager.swift#L123)). it should be picking up the cloudhook url and remote UI URLs via that response. so adding the "create if not already created" to there sounds super reasonable and should start working without any app-side changes.

**Comment by zacwest** [comment]
hmm, worth noting though that we show the 'use cloud?' settings when a remote UI URL is present, but it doesn't seem like that's triggering in this error case. i wonder if there's an issue with `get_config` parsing when cloud is turned on after the fact.

**Comment by zacwest** [comment]
I tested the following:

1. Started with an install without cloud
1. Connected the app, setting up whatever IP address to connect to it
1. Set up cloud and enabled remote UI
1. Launched the app

After launching the app, "connect via cloud" became available in the Connection settings and I could enable it to use the remote UI URL.

**Comment by michaeldavie** [comment]
@zacwest I went through a similar sequence as you describe and I don't see the "connect via cloud" option in the app. Is there any way to enable this?

**Comment by michaeldavie** [comment]
Solved! The missing bit seems to have been the `discovery` and/or `ios` components in the server's YAML config. With those added the app was able to discover the server and configure it correctly.

**Comment by zacwest** [comment]
I'm guessing restarting the server when adding those is what resolved it for you, and not their presence or absence.

**Comment by michaeldavie** [comment]
Updated
