### ISSUE TITLE
Blurry Fonts on macOS Companion

### ISSUE THREAD

**Issue by henrikbjorn** [home-assistant/iOS#1305]
**Device model, version and app version**

Model Name: MacBook Pro 16"
macOS Version: 11.1 beta
App Version: 2020.07
Safari Version: 

**Home Assistant Core Version**

2020.12

**Describe the bug**

Fonts look blurry on the macOS companion

**To Reproduce**

Install macOS companion

**Expected behavior**

Not to have blurry fonts

**Screenshots**

![Skærmbillede 2020-12-19 kl  10 28 31](https://user-images.githubusercontent.com/19725/102686047-42dc9280-41e5-11eb-902e-5c3981a935ce.png)

**Additional context**

**Comment by svh1985** [comment]
I'm experiencing the same issue on my external 27 inch LG 4k screen.

**Comment by matthieu-fesselier** [comment]
Same for me on my external screen

**Comment by zacwest** [comment]
Looks like this can be solved on Big Sur by adopting the Mac appearance style. The app's pretty close to functional when doing so, there's a few things that _must_ be addressed:

- UIStepper and UIRefreshControl are unavailable
- Some rows and things in settings do not look good (their rows are so short that icons are overpoweringly big)
- The UI feels a lot less easy to use with a small checkbox in a tiny row. Settings may need some translation to more Mac-appropriate UI to be usable.

It does look unblurry though:

![image](https://user-images.githubusercontent.com/74188/105778857-10c7fa00-5f22-11eb-9c33-7c5b2a941b8d.png)
![image](https://user-images.githubusercontent.com/74188/105778881-1cb3bc00-5f22-11eb-88c0-9eed4f5964ee.png)

This approach, of course, does not resolve the issues on Catalina.

**Comment by nickdos** [comment]
> Looks like this can be solved on Big Sur by adopting the Mac appearance style...

I've had a quick look on my machine running Big Sur but I can't find this setting... how do I do this?

**Comment by zacwest** [comment]
That is not a setting, it is something the app would need to be updated to support.

**Comment by TheJulianJES** [comment]
Is it possible to already do this ourselves? (Or is it possible to add a checkbox that only implements a basic version of this? I don't really care if the settings UI isn't "scaled" properly, as it seems to finally make the app usable)
But it might be too much of a hassle to do atm.

**Comment by zacwest** [comment]
Not yet. This requires code changes.
