### ISSUE TITLE
HA app doesn't remember window size

### ISSUE THREAD

**Issue by Stooovie** [home-assistant/iOS#1310]
**Device model, version and app version**

Model Name: iMacPro1,1
macOS Version: 11.1
App Version: 2021.1
Safari Version: 14.0.2

**Home Assistant Core Version**
2012.7

**Describe the bug**

App doesn't remember window size, it always resets upon relaunch

**To Reproduce**

Resize app window
Quit app
Reopen app

**Expected behavior**

App remembers window size

**Screenshots**

**Additional context**
I do see the suggestion to disable "Close windows when quitting apps" in System Preferences-General, but that is not an acceptable solution as it changes the system behavior in a major way.

**Comment by zacwest** [comment]
That setting directly controls this behavior as it's a system-level feature for Catalyst apps.

**Comment by zacwest** [comment]
#1040
