### ISSUE TITLE
untangle battery_level and battery_state sensors

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/iOS#1311]
**Is your feature request related to a problem? Please describe.**

as it stands, the battery_state and battery_level sensors duplicate most of each others info. In itself that isn't really an issue, but, it makes it more complex to create functional templates based on their attributes. Eg they are both of `device_class: battery`, so a simple template like

```
    {% for state in states | selectattr('attributes.device_class', '==', 'battery') %}
      {{state.name }}: {{state.state}}
    {% endfor %}
```
and deriverates of this (listing, counting, selecting below threshold) need to exclude the battery_state sensors out of this selection.
Other examples could be given but this illustrates it clearly.

**Describe the solution you'd like**

Imho, it would be a good start to only use the `device_class: battery` on the battery_level sensors.
Second, I would suggest to un-duplicate the attributes.

Most simply said: take out all battery_level attributes from the battery_state sensors.
On the battery_level sensor: take out `battery_state` attribute

The icon for the battery_state could thus reflect only what the sensors state _is_: Charging, Not charging or Full (which have appropriate mdi icons), and with this adaptation make the battery_percentage icon used only on the battery_level sensor.

**Additional context**
<img width="971" alt="Schermafbeelding 2020-12-23 om 12 20 21" src="https://user-images.githubusercontent.com/33354141/102991303-42ac0200-4519-11eb-8cc6-425066ebd539.png">

**Comment by Mariusthvdb** [comment]
shoud we re-open this or create a new one? After updating to 2021.2.10, the battery_level and battery_state sensors still are duplicates of each other....

unless there's some instruction I have missed for deleting the former maybe?

also, on the iOS app for Mac these sensors get the prefix `_internal`, which seem superflous as a battery is always that? Internal....?

**Comment by zacwest** [comment]
I mostly ignored the macOS sensors there, because I'm not sure how I want to handle them; they're appropriate-ish for either, but maybe a lot of them should also be pulled out into their own sensors. As a consumer of this, what do you think? This also applies to the 'low power mode' attribute on the battery state sensor. The `internal` prefix is because macOS supports multiple batteries, and that is the internal battery on your device.

**Comment by zacwest** [comment]
I also do not know if the device_class will reset without deleting and re-creating the integration/sensor, but it should no longer be on the battery state sensor.

**Comment by Mariusthvdb** [comment]
something's odd. I've deleted  Mac OS app in the integrations page, and re-added it, but as you can see both sensors are almost identical.

what I'd think would be to have none of the attributes twice.... of course that would lead to a discussion which attribute to use where. For now I would not suggest pull any of the out just yet, as this integration already holds many sensors (which probably are never used as such).

Since the name is either _state and _level, I'd suggest anything to relate to the state of the battery (so that would include most attributes here) to the _state sensor, and have only the level, unit percentage and device_class set to the battery_level sensor.

Internal: I see, didnt know that, so yes that makes sense then ;-)
