### ISSUE TITLE
Push ID is lost until application restart when using 'Reset' in App Configuration

### ISSUE THREAD

**Issue by Unsigus** [home-assistant/iOS#1312]
**iOS device model, version and app version**

Model Name: iPhone 12 
Software Version: 14.3
App version: 2021.1 (1)

**Home Assistant Core Version**
2020.12.1

**Describe the bug**
Notification Push-ID not set after configuring new Home Assistant installation

**To Reproduce**
1. Have the app configured for a Home Assistant installation (for my situation: a RPI). Notifications are up and running here.
2. Have another Home Assistant installation in you network (for my test: an Odroid N2). I did not copied a snapshot.
3. In the app: Go to App configuration > Hit 'Reset'
4. Configure the just resetted app (I did not quit the app)
5. Go to App configuration > Notifications. Here you see that there is no Push ID. 

**Expected behavior**
The push ID has to be set after moving to a new installation.

**Screenshots**
![IMG_1626](https://user-images.githubusercontent.com/20977992/103101441-ec71b880-4617-11eb-992c-1fc5166d7825.PNG)

**Additional context**
After hitting 'Reset ('herstel')' below the Push ID, an ID is filled in and notifications are working as expected. So it is not that big of an issue.

**Comment by zacwest** [comment]
You can avoid this issue for now by logging out (from your profile in the frontend) instead of resetting.

**Comment by Unsigus** [comment]
Yeah, I did that. It is not a problem and easily avoidable but still, it is a (tiny) bug.
