### ISSUE TITLE
Detect which screen is connected

### ISSUE THREAD

**Issue by geertsmichael** [home-assistant/iOS#1314]
**Describe the solution you'd like**
I would like to know which monitor is connected to my MacBook. I have different screens in my office downstairs or upstairs. The 3rd location I use my MacBook, is without a screen connected.
I can detect my MacBook is at home or not, but it's hard to determine where exactly I am.

If there could be a sensor with all the screen names that are connected, I can derive in which room I exactly am.
In combination if the existing sensor that indicates that the MacBook is active, it can be used a presence sensor to determine if light needs to be on or off.

**Comment by zacwest** [comment]
#1247
