### ISSUE TITLE
Placement of cursor in File editor is not correct when using zoom! This is also visible in Webapp/Website and iOS App!

### ISSUE THREAD

**Issue by carsten-h** [home-assistant/iOS#1315]
Device model, version and app version

Model Name: Mac Pro 2013
Software Version: 10.15.7
App version: 2020.7 (3)

Home Assistant Core Version

HassOS 4.13 on a Pi4B 4GB
Supervisor 245
Home Assistant 0.115.4

Describe the bug
If I am setting the scaling in the App to something below 100%, the Cursor in the File editor is not longer placed on the correct characters.
To see what I mean, I double clicked on "dachboden" and this is the result:
![falsch](https://user-images.githubusercontent.com/44360828/103182438-7b4a3380-48ab-11eb-9445-e173b9ca2330.png)

To Reproduce
Switch to another zoom like 85% and then go to the file editor.

Expected behavior
The cursor should be placed correct.

Screenshots

This is seen with 100%:
![richtig](https://user-images.githubusercontent.com/44360828/103182440-83a26e80-48ab-11eb-845e-b38ff3e6a18e.png)

This bug is also visible in the webapp/website for Home Assistant and also in the iOS App! This is very annoying, because the website is much to big in 100% It uses too much space!

Additional context

**Comment by zacwest** [comment]
#1120 If this is happening outside of the app, though, that sounds like an issue for the frontend repo.
