### ISSUE TITLE
App will not connect to the internal URL unless precision location is enabled

### ISSUE THREAD

**Issue by adub08** [home-assistant/iOS#1318]
Model Name: iPhone 6
Software Version: 14.2
App version: 2020.7 (11)

**Home Assistant Core Version**
2020.12.2

**Describe the bug**
App will not connect to the internal URL unless precision location is enabled (not just Location: Always). 

**To Reproduce**
Turn Off Precision Location under Location in the Iphone's Settings --> Home Assistant --> Location Menu.
App will then not detect the SSID and will not use the Internal URL.
**Expected behavior**
A note should be made in the 'app explanation' in the Location Menu, to tell users to manually enable precision location. 
A note should also be made in the documentation in getting started and other relevant sections.

**Comment by zacwest** [comment]
Sorry you got bit by this. Tracking this in #776 for remaining iOS 14 precise location things.
