### ISSUE TITLE
Sensors for accessory (Apple Watch, AirPods, etc.) battery level

### ISSUE THREAD

**Issue by fi-sch** [home-assistant/iOS#1332]
**Is your feature request related to a problem? Please describe.**
I would like to be able to read Apple Watch battery state (percentage, charging). Any other connected accessories, like AirPods, are also welcome.
I tend to charge my devices up to 70-80%, and don't go below 30% to preserve battery lifespan. This still gives me a whole day of uptime, but also saves the battery. Anyways, AW or AirPods charge quite quickly, so I need to keep an eye on it to not go above 80% when charging during the daytime, or at the morning after a night with sleep tracking.
Having battery details in Home Assistance would give me ability to send notifications when device is charged (or a reminder when battery get's below 30%). I would also be able to automate charging and cut off the charger when device is charged to desired 70-80% :)

**Describe the solution you'd like**
Additional sensor for Apple Watch battery state (or any other connected accessory, like AirPods).

**Comment by fi-sch** [comment]
Seems to be a duplicate of #1331. I didn't notice that FR before posting, sorry <facepalm>.
However I'm not sure because what I meant are only Apple accessories which are displayed in iOS widget. Please close this one if #1331 coincides with this request.
Thanks!

**Comment by zacwest** [comment]
This may be possible for the Watch since we are an app that runs there, but other devices that e.g. show up in the Battery widget are not accessible via API.

**Comment by fi-sch** [comment]
That's good to hear as sensor for Apple Watch is what I'd really love to have :)
