### ISSUE TITLE
Using Ambient Light Sensor Mac

### ISSUE THREAD

**Issue by mnium** [home-assistant/iOS#1333]
After searching around, it seams, that it is now possible with Mac OS Big Sur (Mac Catalyst 14.0+) to get information of the ambient light sensor in a easy way without any hacks like before.

https://developer.apple.com/documentation/sensorkit/srsensor/3377673-ambientlightsensor

**Describe the solution you'd like**
The ambient light sensor of the mac delivers a light level value [Lux]. A HA Automation turns on (or off) desk lights, when it is too dark(bright). Similar to motion sensor like Philips Hue ones.

**Comment by zacwest** [comment]
#917 is for the SensorKit part of this, but SensorKit looks like it's going to be similar to HealthKit -- something that's likely off-limits for most things :( It looks like Firefox/Mozilla found a [private-ish API](https://bugzilla.mozilla.org/show_bug.cgi?id=793728#attach_664102) route to get the data, but Apple's locked it down in newer Macs. I'm not sure why they're so tightlipped about this info.

**Comment by mnium** [comment]
My guess it's because of this: https://blog.lukaszolejnik.com/stealing-sensitive-browser-data-with-the-w3c-ambient-light-sensor-api/

My hope was/is that now with an "official" way it might not interfere with the Mac App store policy.

**Comment by grischard** [comment]
I think [Lunar](https://github.com/alin23/Lunar) gets around this by reading the main display brightness, which is then set automatically using the sensor. In other words, the display brightness is used as a proxy.

There's also an [AmbientDisplay.framework](https://github.com/alin23/Lunar/tree/master/EDIDReader/AmbientDisplay.framework) being mentioned in the code, but that's way out of my depth.

**Comment by zacwest** [comment]
Looks like @Insidegui found a way to grab the state reliably: https://github.com/insidegui/DarkModeBuddy
