### ISSUE TITLE
History doesnt show anything but in the mouse hover

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/iOS#1334]
**Device model, version and app version**

Model Name:   MacBook Pro 16
macOS Version:  Big sur 11.1
App Version: 2021.1 (5)
Safari Version: 14.0.2

**Home Assistant Core Version**

2012.2

**Describe the bug**

App History page shows nothing, except when hovering

**To Reproduce**

**Expected behavior**

Show all
**Screenshots**

App:

<img width="941" alt="Schermafbeelding 2021-01-02 om 23 25 53" src="https://user-images.githubusercontent.com/33354141/103467689-e4b9be80-4d51-11eb-89d6-2be0f78bc07e.png">

App Hovering:

<img width="1080" alt="Schermafbeelding 2021-01-02 om 23 26 36" src="https://user-images.githubusercontent.com/33354141/103467707-fdc26f80-4d51-11eb-8f84-6801e323a50b.png">

Safari:
<img width="1093" alt="Schermafbeelding 2021-01-02 om 23 29 03" src="https://user-images.githubusercontent.com/33354141/103467742-5bef5280-4d52-11eb-85d6-07586f9c4a25.png">

**Additional context**

**Comment by zacwest** [comment]
home-assistant/frontend#3340 (Mac webview behaves like under iOS characteristics) -- it's possible this will be fixed for the Mac app in the future by moving to the "mac-style" app in Big Sur.
