### ISSUE TITLE
Be able to require user's confirmation of an Action prior to triggering it

### ISSUE THREAD

**Issue by fi-sch** [home-assistant/iOS#1345]
**Is your feature request related to a problem? Please describe.**
There's no problem in terms of functionality. It just may happen that some action is triggered by an accidental tap.

**Describe the solution you'd like**
Be able to set up a "confirmation: true" parameter for a single action. Action defined with this parameter would need an additional tap in the iOS widget or watchOS app.
It could behave similarly to what's already in Lovelace UI: https://www.home-assistant.io/lovelace/actions/#options-for-confirmation 
A simple Yes/No confirmation, or more complicated one with user's own defined message.

**Additional context**
I had quite stressful beginning of this year. Thing happened in the morning after a long long New Year's party at my friend's chalet. I'm not sure when and how, but I accidentally tapped the action shortcut (probably it was on my Apple Watch). Action was to open my garage door...
It also happened that the action was triggered with a slight delay – because of a poor cellular coverage – and it also prevented me from undoing the action (closing the door)... You can only imagine how stressed I was for a couple of minutes.

**Comment by stbeep1** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> There's no problem in terms of functionality. It just may happen that some action is triggered by an accidental tap.
> 
> 
> 
> **Describe the solution you'd like**
> 
> Be able to set up a "confirmation: true" parameter for a single action. Action defined with this parameter would need an additional tap in the iOS widget or watchOS app.
> 
> It could behave to what's already in Lovelace UI: https://www.home-assistant.io/lovelace/actions/#options-for-confirmation 
> 
> A simple Yes/No confirmation, or more complicated one with user's own defined message.
> 
> 
> 
> **Additional context**
> 
> I had quite stressful beginning of this year. Thing happened in the morning after a long long New Year's party at my friend's chalet. I'm not sure when and how, but I accidentally tapped the action shortcut (probably it was on my Apple Watch). Action was to open my garage door...
> 
> It also happened that the action was triggered with a slight delay – because of a poor cellular coverage – and it also prevented me from undoing the action (closing the door)... You can only imagine how stressed I was for a couple of minutes.

I want this too, do you have any update on that? Thanks

**Comment by carmelo42** [comment]
This would be great, I'm accidently opening my garage door from my watch :(
