### ISSUE TITLE
NFC unable to Callback URL

### ISSUE THREAD

**Issue by AdvaitT17** [home-assistant/iOS#1346]
## The problem

Unable to run NFC triggered events or automation in debug Home Assistant iOS build. On reading the tag, it just gives a notification popup to 'home-assistant.io/ios/tag/...' which leads to the home assistant NFC documentation page and does not fire any event.

## Environment

Version - 2020.12.0
Installation Type -  Home Assistant Supervised
Development - false
Supervisor - true
Docker - true
Virtual Environment - false
Python Version - 3.8.6
Operating System Version - 5.4.51-v7+
CPU Architecture - armv7l

**Comment by zacwest** [comment]
The kind of NFC tags on iOS that the Home Assistant app writes and reads use [universal links](https://developer.apple.com/documentation/corenfc/adding_support_for_background_tag_reading), which require augmenting the [apple-app-site-association file](https://developer.apple.com/documentation/safariservices/supporting_associated_domains) with app information. Since this requires team provisioning, we cannot make it available in debug builds for the Home Assistant app.

If you'd like to emulate this locally, you'll need to update the entitlements file to include additional domains, update the association file on your domain, and update the tag-writing code in the app to use your custom domain. Tag reading -- as long as it is launched via universal links -- is domain-agnostic.

**Comment by AdvaitT17** [comment]
I've updated the associated domain located in App-Catalyst.entitlement
It gives a popup with the custom domain but doesn't open app.

**Comment by zacwest** [comment]
The Catalyst app is the macOS build. You can still test this by e.g. launching the URL via Messages.app or something, but for NFC you want to edit the iOS app (`App-ios.entitlement`).

**Comment by AdvaitT17** [comment]
@zacwest Yep did that as well! Therefore I am just getting the custom URL I set to my personal website which when clicked directs me to 404.

**Comment by zacwest** [comment]
Can you share the details of your `apple-app-site-association`. For example, you can see [the home-assistant.io one](https://www.home-assistant.io/.well-known/apple-app-site-association). How do they compare?

**Comment by AdvaitT17** [comment]
Do I have to host that on my web server?

**Comment by zacwest** [comment]
Yes. Both sides need to say that they support each other for it to work.

**Comment by AdvaitT17** [comment]
Oh, okay! Will host that and let you know if that works. Thanks :)

**Comment by AdvaitT17** [comment]
Hi there!

I hosted this code over my website but still, it isn't opening the app.

{
  "applinks": {
    "apps": [],
    "details": [
      {
        "appID": "2J8UKYKX2Z.io.advait17.HomeAssistant.dev",
        "paths": [
          "/ios/*",
          "NOT /ios/beta",
          "NOT /ios/beta/*",
          "/tag/*"
        ]
      },
      {
        "appID": "2J8UKYKX2Z.io.advait17.HomeAssistant.beta",
        "paths": [
          "/ios/*",
          "NOT /ios/beta",
          "NOT /ios/beta/*",
          "/tag/*"
        ]
      },
      {
        "appID": "2J8UKYKX2Z.io.advait17.HomeAssistant",
        "paths": [
          "/ios/*",
          "NOT /ios/beta",
          "NOT /ios/beta/*",
          "/tag/*"
        ]
      },
      {
        "appID": "2J8UKYKX2Z.io.advait17.HomeAssistant.dev",
        "paths": [
          "/ios/*",
          "NOT /ios/beta",
          "NOT /ios/beta/*",
          "/tag/*"
        ]
      },
      {
        "appID": "2J8UKYKX2Z.io.advait17.HomeAssistant.beta",
        "paths": [
          "/ios/*",
          "NOT /ios/beta",
          "NOT /ios/beta/*",
          "/tag/*"
        ]
      },
      {
        "appID": "2J8UKYKX2Z.io.advait17.HomeAssistant",
        "paths": [
          "/ios/*",
          "NOT /ios/beta",
          "NOT /ios/beta/*",
          "/tag/*"
        ]
      }
    ]
  }
}

**Comment by AdvaitT17** [comment]
Is there anything to be done for mydomain.com/tag/

**Comment by AdvaitT17** [comment]
It's working now! Thanks @zacwest

**Comment by AdvaitT17** [comment]
@zacwest The NFC Callback isn't working on iPhone SE 2nd Generation with Passive NFC Reading. I've tested it over iPhone X, XS, and 12 Pro and all are working except SE 2. It just opens the URL in the browser.

**Comment by zacwest** [comment]
Universal Links is a technology that is largely in Apple's hands. You may find that you need to allow access to their servers (Universal Link metadata is proxied in iOS 14), restart the device, wait for it to manually re-read the apple-app-site-association file, etc.

**Comment by zacwest** [comment]
Also read the contents of www.home-assistant.io/tag for more how-to.
