### ISSUE TITLE
report current active applications and/or at least current focus application

### ISSUE THREAD

**Issue by maxandersen** [home-assistant/iOS#1347]
**Is your feature request related to a problem? Please describe.**

I would like to detect wether I'm currently active on a conference call to change lights and other settings - here knowing what application I'm actively using and which are running would be very useful.

**Describe the solution you'd like**

First, would be getting current focus application name (i.e. Safari, Zoom, Bluejeans, etc.) BUT also get the current title - to i.e. detect Chrome being on "Google Meet"

Secondary, would be to detect that i.e. Zoom is running in background while I'm on Chrome, Terminal of VSCode which would indicate I'm sharing the screen but still on zoom call.

**Additional context**

current camera and microphone sensors are not good enough for my usecase since I use virtual camera/mic which is not detected; but also that I'm running ecamm live or OBS more or less always and thus camera and microphone is always detected as on.

**Comment by zacwest** [comment]
#977
