### ISSUE TITLE
Unable to send attachments or live feed over iOS notifications

### ISSUE THREAD

**Issue by AdvaitT17** [home-assistant/iOS#1350]
**iOS device model, version and app version**

Model Name: 
Software Version: iOS 14.4 Beta
App version: Home Assistant iOS 2021.4 Debug

**Home Assistant Core Version**
2021.0 Home Assistant Supervised Running Docker

**Describe the bug**

I am unable to send attachments over iOS devices. The trick works with android but not iOS.
Error: Send a camera snapshot when motion is detected: Error executing script. Unexpected error for device at pos 3: Unable to resolve webhook ID from the device ID

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by zacwest** [comment]
The error you are quoting sounds like it is happening in your HA instance and not in the app. Can you share a screenshot and examples of what you are executing?

**Comment by AdvaitT17** [comment]
I am trying to test actionable notifications on the debug iOS version of HA. I am also using [FCM](https://github.com/home-assistant/mobile-apps-fcm-push) hosted on my server to run node functions. It runs well on Android with both normal and actionable notifications although on iOS I was only able to run plain text notifications that too had to reset push id every 20-30min after inactivity.

**Comment by AdvaitT17** [comment]
@zacwest ?

**Comment by AdvaitT17** [comment]
What is this used for? https://github.com/home-assistant/core/blob/810561e313e6de57d5fbe443247126d4704a8914/homeassistant/components/ios/notify.py#L20

**Comment by zacwest** [comment]
The FCM function sends the events to Apple, yes. However I still need to see what you're trying to do to have any idea what is erroring though.

**Comment by AdvaitT17** [comment]
It's working fine with plain notifications after changing the gateway. Although I'm unable to send actionable notifications like attachments or actions in the notification on iOS device.

**Comment by zacwest** [comment]
Can you share an example of what you are doing and isn't working?

**Comment by AdvaitT17** [comment]
I'm trying to send a notification ![image](https://user-images.githubusercontent.com/15717657/103924502-1eb50700-513c-11eb-95cb-c12c7cda8831.jpeg) something like this but I'm just getting a plain text version of the same.

**Comment by zacwest** [comment]
I'm having trouble understanding what you've tried to do and what didn't work about it. Can you share an example service call, yaml configuration or screenshots of your notification categories, and what errors you received?

**Comment by AdvaitT17** [comment]
I am not getting any error in logs for that...just I am not getting the desired attachment. It just delivers plain text and title.

**Comment by AdvaitT17** [comment]
And this is what I get when I try to fire notifications with attachments.

Error saving events: (sqlite3.DatabaseError) database disk image is malformed [SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id, context_parent_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)] [parameters: ('call_service', '{"domain": "persistent_notification", "service": "dismiss", "service_data": {"notification_id": "config_entry_discovery"}}', 'LOCAL', '2021-01-08 05:15:14.013952', '2021-01-08 05:15:14.013952', 'ba9181dde32fbfea143572c060a03a7b', None, None)] (Background on this error at: http://sqlalche.me/e/13/4xp6)

**Comment by AdvaitT17** [comment]
Is there any special entitlement to be created on developers portal?

**Comment by zacwest** [comment]
Please see the [documentation](https://companion.home-assistant.io/docs/notifications/notification-attachments) around doing attachments. That error is related to persistent notifications which are a different feature of HA. The iOS app is notified via the mobile_app integration.

**Comment by AdvaitT17** [comment]
Yeah, but why wouldn't the attachment appear when the code includes the requirement to? And when I tested, I even found out that only the Title & Text fields work even when I add an option for things like subtitle, attachments and everything that has been listed [here](https://companion.home-assistant.io/docs/notifications/notifications-basic/)

**Comment by zacwest** [comment]
Can you share an example of what you are sending which is not working?

**Comment by AdvaitT17** [comment]
Only the first example works of this [list](https://companion.home-assistant.io/docs/notifications/notifications-basic/). Rest all just end sending the Title & Text(message) field of the notification. I don't get to use links, subtitle, sounds, attachments, etc.
'

**Comment by AdvaitT17** [comment]
It's clearly stated everything I want to use in this [file](https://github.com/home-assistant/mobile-apps-fcm-push/blob/master/functions/ios.js) and I hosted it as it is with just changing the package name.

**Comment by zacwest** [comment]
I'm sorry but I really am having trouble understanding:

1. What you are doing
2. What isn't working about what you are doing

If you've got the FCM function running and you're successfully sending notifications, you must be invoking them somehow. Can you show me an example of one that works and one that doesn't?

**Comment by AdvaitT17** [comment]
Okay. For eg. when I try sending a notification containing subtitle.

title: "Smart Home Alerts"
message: "Something happened at home!"
  data:
    subtitle: "Subtitle goes here"

This is what I get on our official released HA and what I get on debugged HA running fcm function on my server.

![image](https://user-images.githubusercontent.com/15717657/103993681-fd93fb00-51bb-11eb-87ec-dfaea3003ee4.png)

![image](https://user-images.githubusercontent.com/15717657/103993689-fff65500-51bb-11eb-9153-55ed71946fca.png)

**Comment by AdvaitT17** [comment]
Same thing with attachments...

![image](https://user-images.githubusercontent.com/15717657/103994420-fe795c80-51bc-11eb-85e1-872252a372c0.jpeg)
![image](https://user-images.githubusercontent.com/15717657/103994426-020ce380-51bd-11eb-8ef8-08c34a0b03bf.png)

**Comment by AdvaitT17** [comment]
I guess it related to APNS entitlement?

**Comment by AdvaitT17** [comment]
@zacwest The issue is with the Firebase configuration code in the app I suppose as I tried sending a notification with an image as an attachment through Firebase Cloud Messaging but still got Title & Text but no image...

**Comment by AdvaitT17** [comment]
I got an error while compiling code in xcode. Can the issue be related to this?

firebaseanalytics.framework is not included in your target. please add the firebaseanalytics dependency to your project to ensure messaging works as intended."

**Comment by zacwest** [comment]
> Okay. For eg. when I try sending a notification containing subtitle.

Although you did not wrap it in code blocks, I can see the original indentation when quoting and you are not indenting the 'data' field correctly here.

```yaml
title: "Smart Home Alerts"
message: "Something happened at home!"
  data: # too deep
    subtitle: "Subtitle goes here"
```

> @zacwest The issue is with the Firebase configuration code in the app I suppose as I tried sending a notification with an image as an attachment through Firebase Cloud Messaging but still got Title & Text but no image...

This is not a feature the app supports. We do not want to be beholden to Firebase (and have intentions to leave it) and as such we do not include its attachment flow.

> I got an error while compiling code in xcode. Can the issue be related to this?

This is not an error, this is a warning. It is not harmful.

-----

At this point I do not believe this is a useful ticket - if you're attempting to do things separately in a debug build and in your own FCM flow from the normally app, and you cannot troubleshoot the issues yourself, I cannot dedicate time to problem solving; I'm sorry. You may find a better avenue in the [Community forums](https://community.home-assistant.io/c/mobile-apps/ios/41).

**Comment by AdvaitT17** [comment]
@zacwest I was testing that over dev service tool, therefore I didn't put in quotes. And as I said, it's working fine with just title and body even when I specifically ask for actionable one. And when the same thing I use in the official app, it works.

**Comment by AdvaitT17** [comment]
Can you just tell me all the changes to be made in xcode to make fcm work properly. I just changed 2 URLs and Google plist files.

**Comment by zacwest** [comment]
That is all that I believe is necessary. If you're receiving _any_ notifications, than Firebase is set up properly. The app does not use firebase for anything client-side other than getting the push identifier that can work.

**Comment by AdvaitT17** [comment]
URLs sendPushNotification & checkRateLimits right?

**Comment by AdvaitT17** [comment]
I tried HA Official & Debug version on almost 3 different instances where I found whenever using debug version, once notification registry happens

I get spammed by this in my logbook

Logger: homeassistant.components.recorder
Source: components/recorder/__init__.py:526
Integration: Recorder (documentation, issues)
First occurred: 10:30:02 PM (53 occurrences)
Last logged: 10:46:21 PM

Error executing query: (sqlite3.DatabaseError) database disk image is malformed [SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id, context_parent_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)] [parameters: ('state_changed', '{}', 'LOCAL', '2021-01-08 17:13:45.546725', '2021-01-08 17:13:45.546725', '9f7b3a2ce1148b825de10d9eb510a319', None, None)] (Background on this error at: http://sqlalche.me/e/13/4xp6)

And whenever I try sending notifications...

Logger: homeassistant.components.recorder
Source: components/recorder/__init__.py:509
Integration: Recorder (documentation, issues)
First occurred: 10:30:02 PM (49 occurrences)
Last logged: 10:46:21 PM

Error saving events: (sqlite3.DatabaseError) database disk image is malformed [SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id, context_parent_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)] [parameters: ('state_changed', '{}', 'LOCAL', '2021-01-08 17:13:45.546725', '2021-01-08 17:13:45.546725', '9f7b3a2ce1148b825de10d9eb510a319', None, None)] (Background on this error at: http://sqlalche.me/e/13/4xp6)

sqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) database disk image is malformed
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id, context_parent_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('call_service', '{"domain": "system_log", "service": "write", "service_data": {"logger": "frontend.js.latest.202012120", "message": "http://homeassistant.local:1702/local/community/custom-header/custom-header.js:1:11701 TypeError: null is not an object (evaluating \'f[t].cloneNode\')"}}', 'LOCAL', '2021-01-08 17:04:35.947654', '2021-01-08 17:04:35.947654', '19c8580b7cd51a901565c82a71c82250', '2eafaa2df3c242da8376dc84d3e18041', None)]
(Background on this error at: http://sqlalche.me/e/13/4xp6)

**Comment by AdvaitT17** [comment]
@zacwest I figured it out! The URL I was using was the legacy one and therefore it was just supporting title and body fields and not iOS features. Thank you so much for the help :)
