### ISSUE TITLE
Virtual camera and microhones do not show up in sensors

### ISSUE THREAD

**Issue by maxandersen** [home-assistant/iOS#1354]
as discussed in https://community.home-assistant.io/t/mac-sensors-for-network-ip-and-cameras/264152/4 it would be great if the active camera and microphone would support virtual cameras like ecamm live and OBS including virtual microphones like krisp.ai.

**Comment by maxandersen** [comment]
sorry - i opened it using the wrong template, should have had mac label not ios but can't change it now.

**Comment by zacwest** [comment]
Right now, I'm able to see virtual microphones like Krisp.ai, which uses an underlying microphone; both appear active to me.
<img width="728" alt="image" src="https://user-images.githubusercontent.com/74188/104104758-e8bc7380-525e-11eb-91d8-d48a8465d112.png">
Snap Camera also produced similar results, where it was using another underlying camera which was picked up. Can you give me any more details about how to reproduce this issue?

**Comment by jturnbull** [comment]
I think this is the same issue that I have: I use [Reincubate Camo](https://reincubate.com/support/camo/camo-overview/) on the Mac, which creates a virtual camera from an external iPhone.

This virtual camera, like OBSstudio, isn't detected by the Home Assistant app. The [Camo documentation](https://reincubate.com/support/camo/camo-faq/#allow-camo) says that: "In order for a video conferencing app to support Camo, its developers need to add the `com.apple.security.cs.disable-library-validation` entitlement to their product."

Is this a change that can be made to the Home Assistant Mac app? Thanks

**Comment by lidanh** [comment]
Hey, any update on this? I use Sony ImagingEdge webcam app, but can't see it in Home Assistant. Looks like it's related to this issue

**Comment by ClayBenson94** [comment]
Same here, but with https://mmhmm.app/

**Comment by zacwest** [comment]
As of macOS 12.3, third party apps can use a new feature in the OS to show up as virtual devices in sandboxed apps without an entitlement change. Apps will need to update themselves to use this new OS feature, and you'll need to use macOS 12.3 or newer.
