### ISSUE TITLE
Window position and size - lost after quit

### ISSUE THREAD

**Issue by wochen** [home-assistant/iOS#1356]
**Device model, version and app version**
Model Name: MacBook Pro 16,1
macOS Version: 10.15.7
App Version: 2021.1 (6)
Safari Version: 14.0.1

**Home Assistant Core Version**
HassOS 3.13

**Describe the bug**
The application is always opening in the same position of the screen and in the same size. Even if the size is changed by user, the app doesn't save it properly.

**To Reproduce**
1. Open the app (it should appear in the middle of the screen, default window size)
2. Close the app
3. Re-open the app

**Expected behavior**
When opening the app, it should remember last size and position (for example when the application fits the screen size (not full-screen mode, but maximized)

**Comment by TomBrien** [comment]
Sounds like a duplicate of #1040. Could you check the steps mentioned in there and if your problem is the same, let's close this in favour of that post. Please let us know

**Comment by wochen** [comment]
Dear @TomBrien,
many thanks for sending this and apologize I didn't notice the same thread.

It's all sorted now.
Closing.

Best.
