### ISSUE TITLE
Consider VPN in the decision between internal and external URLs

### ISSUE THREAD

**Issue by mountainsandcode** [home-assistant/iOS#1357]
**Is your feature request related to a problem? Please describe.**

Currently, the iOS app decides on using the internal or external URLs based on the WiFi SSID. This covers all situations except two constellations relating to VPN. 

A) Connected to “internal” SSID and being connected to another VPN (e.g., work, Uni, etc.)
* The app tries to connect using the internal URL, but can’t reach it because DNS is typically set by the VPN

B) Not connected to “internal” SSID but connected to home VPN 
* The app connects to the external URL although the internal URL would actually be available

**Describe the solution you'd like**

I’m aware of the fact that we could have complicated constellations with several VPNs, etc., but I would propose having a relatively simple configuration option for “When connected to VPN, use...” with the options auto (current behavior), always internal, always external

**Additional context**
This appears to be possible [Ref](https://medium.com/@alessandrofrancucci/checking-vpn-connection-on-ios-swift-9748d733e49d)

**Comment by zacwest** [comment]
The technique to achieve it there isn't great, but it's possible to inspect all network interfaces and see if there's one that's named like a VPN interface, so this is theoretically possible. I'm not sure how much we can depend on it continuing to function, nor the performance characteristics around it.

**Comment by mrclschstr** [comment]
This issue is not limited to iOS. It would be a nice addition to the Android app as well.
