### ISSUE TITLE
Create new zones using current location

### ISSUE THREAD

**Issue by ericjmonson** [home-assistant/iOS#1368]
The IOS app lets you create new zones by clicking "Configuration -> Zones -> +ADD ZONE". However, the location for the zone seems to be random. It would be helpful if it defaulted to start with your current location ... or to have a button to use the current location. That would help make setting up zones much easier.

**Comment by zacwest** [comment]
I think this suggestion would be more appropriate in the [home-assistant/frontend](https://github.com/home-assistant/frontend) repo, as this would be a change entirely in the web view.
