### ISSUE TITLE
Implementing User Authentication with Sign in with Apple

### ISSUE THREAD

**Issue by AdvaitT17** [home-assistant/iOS#1395]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
It'd be awesome if we could store instance data (Only Login Credentials) on Apple's Servers integrated with NabuCasa. So the next time just tap login with Apple ID to logon to our instance without configuring everything manually.

**Additional context**

**Comment by zacwest** [comment]
#771, with Sign in with Apple.
