### ISSUE TITLE
Home Companion can report "Leave Home" but NOT "Arrive Home"

### ISSUE THREAD

**Issue by kelvinng1** [home-assistant/iOS#1399]
**iOS device model, version and app version**

Model Name: iPhone 7
Software Version: 14.3
App version: 2021.1.1 (9)

**Home Assistant Core Version**

2021.1.4
**Describe the bug**
I try to use Home Assistant Companion to track if I arrived / left home for further automation.

Left home (Home Exited) function work as expected, but arrive home (Home Entered) never change the device's state in Home Assistant.

I checked the log (see below), but Home Exited and Home Entered did have event sent out, but the Home Entered event never trigger a change to the device's state in Home Assistant. Also, I do receive both "Enter Home" and "Exit Home" notifications from the Mobile App as I have turned on both  "Enter Zone Notifications" and "Exit Zone Notifications" in the Mobile App

**To Reproduce**
1. Leave the Home Zone until the mobile app notification "Location Change Home exited" show up
2. Check the iphone device location using device_tracker.iphone in home assistant
3. Re-enter the Home Zone until the mobile app notification "Location Change Home entered" show up
4. mobile app notification "Location Change Home exited" show up

**Expected behavior**
In step 2 above, the state of the device_tracker shall be "away"
In step 4 above, the state of the device_tracker shall be "home"

**Screenshots**

**Additional context**

From Home Assistant companion event logs:

Home exited:
{
  "speed" : 1.1599999666213989,
  "gps" : [
    22.48xx,
    114.04xx
  ],
  "battery" : 74,
  "course" : 240.46875,
  "gps_accuracy" : 10,
  "vertical_accuracy" : 12
}

Location Change - exit Home
{
  "event" : "ZoneManagerEvent(region(CLCircularRegion (identifier:'zone.home@000', center:<+22.48xx,+114.04xx>, radius:100.00m), outside), zone.home)",
  "start_ssid" : "none"
}

Home Entered
{
  "gps_accuracy" : 12.410070148282287,
  "gps" : [
    22.48xx,
    114.04xx
  ],
  "vertical_accuracy" : 10,
  "altitude" : 5.6401915550231934,
  "battery" : 71
}

Location update - enter home
{
  "start_ssid" : "none",
  "event" : "ZoneManagerEvent(region(CLCircularRegion (identifier:'zone.home@000', center:<+22.48xx+114.049xx>, radius:100.00m), inside), zone.home)"
}

**Comment by TomBrien** [comment]
This seems weird. When you are away from home, can you app connect to your Home Assistant instance?

**Comment by bgoncal** [comment]
Is this still an issue with latest versions of app and core? Feel free to reopen if needed
