### ISSUE TITLE
GAnalytics App Count Not Showing Up

### ISSUE THREAD

**Issue by DebbyRi71** [home-assistant/iOS#1406]
**iOS device model, version and app version**
iPhone 11 Pro, iOS 14.4, 2021.2 (10)

**Home Assistant Core Version**

2021.1.5
**Describe the bug**
Updating GoogleService.info.plist files to firebase project generated files didn't respond to Firebase Analytics. Realtime Active Users appear to be 0. Also, why does Podfile doesn't contain pod 'Firebase/Analytics'?

**Comment by zacwest** [comment]
We do not want to include Firebase analytics in the project. Our longer-term goal is to remove all of the Firebase dependencies.

**Comment by DebbyRi71** [comment]
So do you mean the options in the privacy tab do not work or are not supported since the newer versions?

**Comment by zacwest** [comment]
Firebase Analytics is no longer part of the project, and the privacy setting for analytics largely only controls some information sent up to Sentry. It's functional but doesn't really do much right now. Firebase Crashlytics is no longer used. The only thing Firebase remaining in use is the Messaging (Firebase Cloud Messaging, FCM) which has a toggle which does control it.

**Comment by DebbyRi71** [comment]
Could you please mention the version since you discontinued it. I was interested in implementing it into an app I am working on in a conditional toggle manner.

**Comment by zacwest** [comment]
The switchover happened in #854.

**Comment by DebbyRi71** [comment]
Thanks!
