### ISSUE TITLE
Ability to trigger particular actions from a complication

### ISSUE THREAD

**Issue by bcmitri** [home-assistant/iOS#1414]
**Is your feature request related to a problem? Please describe.**
Currently, I have a number of complications on my Apple Watch and clicking any of them launches the same list of actions.  Given that my complications represent different domains / devices, it would be nice to tailor the list of actions for each accordingly. 
For example:
- My indoor temperature complication gives me actions related to controlling temperature
- My complication that tells me how many lights are on gives me actions related to controlling lights

**Describe the solution you'd like**
As part of the options for defining a complication, I am able to select from a list of available actions.  Choosing multiple actions will present only those actions when the complication is clicked.  Choosing none will result in no prompt.  And choosing only a single action will launch that action immediately when the complication is clicked.

**Additional context**

**Comment by zacwest** [comment]
Probably best paired with #1345 (as an option) since accidentally tapping a complication seems _very_ likely.

**Comment by bcmitri** [comment]
Makes sense. But I suspect that’s only needed in the case of a single action.

**Comment by zacwest** [comment]
Might also be a good idea to auto automatic complications for all Actions.
