### ISSUE TITLE
Allow templates for complications colours

### ISSUE THREAD

**Issue by TomBrien** [home-assistant/iOS#1415]
**Is your feature request related to a problem? Please describe.**

Currently we define text and gauge colours when creating a complication and the colours are static from that point on. It would be a nice improvement to allow templates for the colours.

**Describe the solution you'd like**

Keep the current colour picker to allow a static HTML (or other spec) colour to be picked. Store this as a string but allow user to enter text in the field. Then when the complication is updated, if string begins `#`, `hsl(` etc. use colour, if it begins `{{` render template. I guess we would use template sensors on HA side to generate colour as HTML, HSL or whatever. 

**Additional context**

Also ties into the newish colour picker in HA, bonus points if we can get gradients like watchOS weather and AQ gauges

**Comment by bcmitri** [comment]
It looks like the gradient request is already covered in #1163.
