### ISSUE TITLE
Folders and States and More!!

### ISSUE THREAD

**Issue by ThykeAdams** [home-assistant/iOS#1422]
**Is your feature request related to a problem? Please describe.**

It would be great for the watch app to be able to have folders and State Icons. from what I have seen most people use the watch app actions to control individual entities or scenes. It would be great to be able to see if an entity is turned on or off. Folders would be a great addition as well because it would allow people to group rooms together and such (Maybe even allow a automation to open folders depending on where you are if you have presence sensors). Another great feature would be to allow a computer or other device to edit actions and such. Its really annoying to type the action ID  I feel that these features would a different device and it would be awesome to be able to setup a watch action on a separate device form a phone. All of these would be a great addition to the companion app. 

**Describe the solution you'd like**

See above

**Additional context**

**Comment by zacwest** [comment]
#512 (grouping)
#1394 (dynamic content)

> Another great feature would be to allow a computer or other device to edit actions and such.
You can create Actions [in YAML](https://companion.home-assistant.io/docs/core/actions#creating-actions-in-home-assistant).

**Comment by joelhawksley** [comment]
@zacwest I see this is closed, but I don't believe it's been implemented. Would you be open to adding it? I'd be willing to take a crack at writing a PR ❤️

**Comment by bgoncal** [comment]
@joelhawksley a lot has happened in the meanwhile, check how watch home is now rendered and configured in iPhone as well, feel free to give it a try, it should be possible without changing much. I'm happy to review the PR 💪🏻
