### ISSUE TITLE
Create a service to set the DND flag in the OS

### ISSUE THREAD

**Issue by eavanvalkenburg** [home-assistant/iOS#1426]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
A service in HA that toggles Do Not Disturb mode, that would allow scenario's like setting DnD when the you're doorbell goes off, when media is playing etc.

**Additional context**

**Comment by zacwest** [comment]
Unfortunately access to the DND status is not available from sandboxed apps.

**Comment by eavanvalkenburg** [comment]
That's unfortunate!
