### ISSUE TITLE
Apple watch is installed with homeassistant, and watch data set in homeassistant cannot be obtained,

### ISSUE THREAD

**Issue by tiancom** [home-assistant/iOS#1437]
Apple watch is installed with homeassistant, and watch data set in homeassistant cannot be obtained,

Even if the mobile phone and watch are refreshed, saved and synchronized, the data of homeassistant cannot be displayed on the watch

Home assistant version 2021-1-5

Apple watch 5 OS version: 7.3

iphone 12 pro，ios 14.4

**Comment by tiancom** [comment]
> It's difficult for me to eyeball it, but that looks like Chinese (Simplified) with a complication for `图像` which is the 'Graphic' style. This is for Infograph and Infograph Modular watch faces. You should double check that is what you are currently showing on your watch - it's hard to tell if it's Modular or Infograph Modular. If it is, restarting the watch may help, or adding text that contains a template like `{{ now() }}` to work around a bug fixed in 2021.2 which will not correctly update the watch if no complications contain templates.
> 
> Also certain watch faces require all of the text fields visible, and I don't think any for Infograph allow line 2 to be optional - you must fill it in.


As you said, I use the simplified Chinese version of my mobile phone and watch, but it doesn't seem to affect the smooth display of the information I need on my watch. In addition, I have restarted my watch and mobile phone many times without any improvement,

Also, you mentioned that the addition includes: “adding text that contains a template like {{ now() }} to work around a bug fixed in 2021.2 which will not correctly update the watch if no complications contain templates.”I don't understand. It means that the whole problem needs to be fixed in 2021-02, right



Finally, as you mentioned, I am sure that all the required information has been completed.

**Comment by zacwest** [comment]
The syncing issue without templates will be fixed in the next iOS release. You can upgrade to [the beta](https://home-assistant.io/ios/beta) right now to try it out.

In your screenshot I see some of the fields in the complication do not have values entered into them. I believe the first line is 'title' then 'line 1' then 'line 2', and it looks like 'line 1' does not have a value.

**Comment by tiancom** [comment]
> The syncing issue without templates will be fixed in the next iOS release. You can upgrade to [the beta](https://home-assistant.io/ios/beta) right now to try it out.
> 
> In your screenshot I see some of the fields in the complication do not have values entered into them. I believe the first line is 'title' then 'line 1' then 'line 2', and it looks like 'line 1' does not have a value.

![4A9D84BF-72FC-4DEC-B3C0-4002AA4FB09E](https://user-images.githubusercontent.com/38832581/106223187-e88b1480-621b-11eb-8ee8-b825e84c4d66.png)

**Comment by zacwest** [comment]
字体 1
字体 2

**Comment by tiancom** [comment]
> The syncing issue without templates will be fixed in the next iOS release. You can upgrade to [the beta](https://home-assistant.io/ios/beta) right now to try it out.
> 
> In your screenshot I see some of the fields in the complication do not have values entered into them. I believe the first line is 'title' then 'line 1' then 'line 2', and it looks like 'line 1' does not have a value.



> 字体 1
> 字体 2


没错，如果这个line2不填写，是不影响在手表上做显示，这个在home asssistant 版本110到115之间的时候我是确认过的。换句话说，我只填写了line1，那么手表上只显示line1的内容“如123”
That's right. If line2 is not filled in, it will not affect the display on the watch. I have confirmed this between 110 and 115 versions of home assistant. In other words, if I only fill in Line1, then only Line1's content "such as 123" will be displayed on my watch

**Comment by tiancom** [comment]
> 没有模板的同步问题将在下一个iOS版本中修复。您可以立即升级到[Beta](https://home-assistant.io/ios/beta)进行试用。
> 
> 在您的屏幕截图中，我看到了复杂性中的某些字段没有输入值。我相信第一行是“标题”，然后是“行1”，然后是“行2”，看起来“行1”没有值。

Please tell me how to get IOS beta version

**Comment by tiancom** [comment]
> The syncing issue without templates will be fixed in the next iOS release. You can upgrade to [the beta](https://home-assistant.io/ios/beta) right now to try it out.
> 
> In your screenshot I see some of the fields in the complication do not have values entered into them. I believe the first line is 'title' then 'line 1' then 'line 2', and it looks like 'line 1' does not have a value.

Please tell me how to get IOS beta version

**Comment by tiancom** [comment]
> The syncing issue without templates will be fixed in the next iOS release. You can upgrade to [the beta](https://home-assistant.io/ios/beta) right now to try it out.
> 
> In your screenshot I see some of the fields in the complication do not have values entered into them. I believe the first line is 'title' then 'line 1' then 'line 2', and it looks like 'line 1' does not have a value.

I have updated to beta version-2021-02 on IOS mobile phone

However, the information I need is still not displayed in the watch

![BD4CFB97-BDD6-4F32-99BF-7D03BD1F4221](https://user-images.githubusercontent.com/38832581/106437031-c8738380-64af-11eb-85c2-afa63c085f35.png)
![6F330B86-8BB5-4CD7-B555-A03C2A09FDE6](https://user-images.githubusercontent.com/38832581/106437036-cad5dd80-64af-11eb-8ae0-3976a6932756.png)
![BAAB4DBA-0CDC-48C9-B838-E0F098124913](https://user-images.githubusercontent.com/38832581/106437040-cc9fa100-64af-11eb-8889-f79172d8b2ef.png)

**Comment by tiancom** [comment]
This is the actual effect of the system when there was no bug
![Uploading B80031CD-D0F4-4191-8A5B-A8049A727B1C.jpeg…]()

**Comment by zacwest** [comment]
Can you confirm that it is no longer showing the "not configured" message now? I wold like to better understand the exact issue you're running into now. I thought from a previous message you sent that things were working again.

**Comment by tiancom** [comment]
Since I raised this question and now I have used the bate version of IOS according to your suggestion, I am very sure that "not configured" has always been displayed on the dial of my watch. The above normal screenshot is a historical version

**Comment by tiancom** [comment]
> Can you confirm that it is no longer showing the "not configured" message now? I wold like to better understand the exact issue you're running into now. I thought from a previous message you sent that things were working again.

The above screenshot is on January 3, 2020, not in the near future. I have mentioned it many times. Thank you for your support

**Comment by zacwest** [comment]
Can you try this for me: go into your app settings and delete the complication configuration and create a new one. Does that begin working?

**Comment by zacwest** [comment]
Also please understand: there is both a language and time barrier, I am not able to immediately reply. If you'd like to give a try at synchronous problem solving, you can [join the Discord channel #ios_and_mac](https://www.home-assistant.io/join-chat/).

**Comment by tiancom** [comment]
> Can you try this for me: go into your app settings and delete the complication configuration and create a new one. Does that begin working?

This is the one I just created. It still doesn't show the corresponding data on my watch
![Uploading C81CED45-198C-4CCD-A2E1-FB6FDB42DA29.png…]()
![Uploading image.jpg…]()

**Comment by tiancom** [comment]
> Can you try this for me: go into your app settings and delete the complication configuration and create a new one. Does that begin working?

This is the one I just created. It still doesn't show the corresponding data on my watch
![Uploading 30C54FBA-D407-4308-A9CA-8BEEC53DDFF0.png…]()
![Uploading EADFC854-A7CB-4E12-B4CD-4354DFD97F56.jpeg…]()

**Comment by tiancom** [comment]
> Also please understand: there is both a language and time barrier, I am not able to immediately reply. If you'd like to give a try at synchronous problem solving, you can [join the Discord channel #ios_and_mac](https://www.home-assistant.io/join-chat/).

Sorry, I can't use the channel you provided in China

**Comment by tiancom** [comment]
> Also please understand: there is both a language and time barrier, I am not able to immediately reply. If you'd like to give a try at synchronous problem solving, you can [join the Discord channel #ios_and_mac](https://www.home-assistant.io/join-chat/).

![6C242608-E8B2-46E2-AA8E-A25988EB4534](https://user-images.githubusercontent.com/38832581/106743807-cea56380-6659-11eb-85f4-35731f5968df.png)
![3DB43421-3D29-430D-954C-14C786821ADC](https://user-images.githubusercontent.com/38832581/106743834-d5cc7180-6659-11eb-8329-2a4b60cbd9a8.png)


Hello, I have accepted your invitation to join https://www.home-assistant.io/join-chat/
