### ISSUE TITLE
Disabling application activation after activating actions from widgets

### ISSUE THREAD

**Issue by inthami** [home-assistant/iOS#1438]
Hi,
Is it possible that after invoking actions from widgets on macOS, the action will activate without moving the user to the Home assistant app? The confirmation could appear briefly in the widgets. This is a bit annoying.
Thank you very much

_
PS: Sorry, I accidentally sent the previous message in the wrong place. ;)

**Comment by zacwest** [comment]
Unfortunately Apple has decided that we cannot perform things in Widgets, they _must_ launch the app to do any work.
