### ISSUE TITLE
Latest TestFlight version starts with an error only 

### ISSUE THREAD

**Issue by gjveld** [home-assistant/iOS#1445]
Home assistant works in the browser.
The app starts with an error only
(and can’t raise the bug through the functionality in the app either)

![1CEDEA81-1ACE-4A52-89AE-6839BB3D7A47](https://user-images.githubusercontent.com/19951982/106423729-4ceae580-6461-11eb-9a9b-912f99e94809.png)

**Comment by zacwest** [comment]
What happens if you press the back button?

**Comment by gjveld** [comment]
Nothing happens

I installed a previous build but get (weirdly) the same error result

**Comment by zacwest** [comment]
Sounds like the page it has set to restore to isn't working. If you force-quit the app and restart, it should reset to the main dashboard. Does that work?

**Comment by gjveld** [comment]
I tried that, but that doesn’t work.
Final resort is deleting and reinstalling the app?

**Comment by zacwest** [comment]
Just to confirm, you: (1) opened the app switcher, (2) swiped up to kill HA, (3) re-opened HA, and (4) were still stuck on the above screen?

**Comment by gjveld** [comment]
Yes to all 4

**Comment by zacwest** [comment]
Can you swipe from the left edge to expose a menu at all? It's hard to remotely debug without logs, but logs are only available in settings which it doesn't seem like you can access.

**Comment by gjveld** [comment]
I didn’t try the swipe from left (so used to the hamburger menu ;)...

But that does work and I can select the dashboard.  And the app is working normal again.
I can access the logfiles too. 
Any specific log entries you are interested in to know the cause of the error?

**Comment by zacwest** [comment]
It doesn't look like we log which URL is happening, but you can look for `restoring initial url` in the exported logs of when the problem was happening to verify the hypothesis. I don't think it will be super valuable though so feel free to not. Glad it's working now though!
