### ISSUE TITLE
Type Connection: wrong report to HA but correct in the App

### ISSUE THREAD

**Issue by LucasJanin** [home-assistant/iOS#1460]
**Device model, version and app version**

Model Name: Macbook Pro M1 + Anker USB C Hub, PowerExpand 8-in-1
macOS Version: 11.2
App Version: 2021.2 (2021.34)
Safari Version: 14.0.3

**Home Assistant Core Version**
2021.2

**Describe the bug**
After wakeup from sleep, my Macbook Pro M1 report being connected to WiFi in HA but is connected over Ethernet.
The sensor in the app is correct "Ethernet" (preference/ sensors) but the value report in HA is WiFi.
Check my screen capture.

**To Reproduce**
Mac connected over Ethernet
Go to sleep
Wakeup
Check the value of the sensor on the HA integration page and in the app  (preference/ sensors) 

**Expected behavior**
Report the value Ethernet to HA

**Screenshots**
https://imgur.com/a/h9VIjRv

**Comment by zacwest** [comment]
This is going to be one of those bugs where logs are required to resolve it. Can you grab the log file(s) from Preferences > Reveal? It will be useful to know about when time-wise this happened as well. It you can either snip the logs to then or upload the logs [here](https://www.dropbox.com/request/CtVWqILBXZ41tmFSGK2y) I can take a look and hopefully try and see what went wrong.

**Comment by LucasJanin** [comment]
Hi @zacwest 

Thanks for your reply, I uploaded the log.
I wake up my Mac  around 2021-02-05  08:40 (bottom a the log)
Let me know if you need more data

Thanks

**Comment by zacwest** [comment]
I'm unable to see what's going wrong from the logs, unfortunately. I've created a [one-off build](https://github.com/home-assistant/iOS/actions/runs/542039021) (download and install the "mac-developer-id" one) with some additional logging. Please give it a try and save off the logs for this attempt, hopefully it can help narrow it down.

**Comment by LucasJanin** [comment]
I just sent you a new lof with the "mac-developer-id" app. 
The event happened at the end of the log.

**Comment by zacwest** [comment]
I think I see what's going on.

| Actual Value | Last Sent Value | Current Send Value | Result |
| --- | --- | --- | --- |
| Ethernet | Ethernet | Ethernet | Updated |
| Wi-Fi | Ethernet | Wi-Fi | Failed to Update |
| Ethernet | Ethernet | Ethernet | Not Sent, No Change |

The request to change the sensor status from "Ethernet" to "Wi-Fi" errors (`Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost."`) so we consider this to be 'unsuccessful' in updating the state.

I think I can fix this, thanks for running the special build!

**Comment by LucasJanin** [comment]
Fantastic!!! Thanks for tracking this strange bug!
Look forward to testing the new beta.
