### ISSUE TITLE
Add default notification categories to make it easier to do common tasks

### ISSUE THREAD

**Issue by zacwest** [home-assistant/iOS#1465]
**Is your feature request related to a problem? Please describe.**
Users have to set up categories for things that likely can fit into some built-in categories really well.

**Describe the solution you'd like**
Categories I'm thinking of, but I'd love to hear feedback.

| Category | Actions |
| -------- | ------- |
| `BUILTIN_ABORT` | `Abort` |
| `BUILTIN_CALL` | `Call` |
| `BUILTIN_CANCEL` | `Cancel` |
| `BUILTIN_CLOSE` | `Close` |
| `BUILTIN_CONFIRM` | `Confirm` |
| `BUILTIN_MORE_INFO` | `More Info` |
| `BUILTIN_MUTE` | `Mute` |
| `BUILTIN_NO` | `No` |
| `BUILTIN_OFF` | `Off` |
| `BUILTIN_OK` | `OK` |
| `BUILTIN_ON_OFF` | `On`, `Off` |
| `BUILTIN_ON` | `On` |
| `BUILTIN_OPEN_CLOSE` | `Open`, `Close` |
| `BUILTIN_OPEN` | `Open` |
| `BUILTIN_PERFORM` | `Perform` |
| `BUILTIN_REDO` | `Redo` |
| `BUILTIN_SAVE` | `Save` |
| `BUILTIN_UNDO` | `Undo` |
| `BUILTIN_YES_NO` | `Yes`, `No` |
| `BUILTIN_YES` | `Yes` |

Variants I am considering:
- Destructive (red text)
- Camera (allows providing a camera entity ID for the lock screen content)

So perhaps, as an example, I would create `BUILTIN_CAMERA_CONFIRM` for a camera version of confirm.

**Additional context**
It will not be possible to customize these at all to maintain their consistent behavior.

**Comment by olbjan** [comment]
Open/Close

**Comment by zacwest** [comment]
Canceling for #1588.
