### ISSUE TITLE
HA app splash screen should show black instead of blue when dark mode is on.

### ISSUE THREAD

**Issue by di-ccmd** [home-assistant/iOS#1469]
**The HA app splash screen shows blue when I open the app, it should be black when the app is set to dark mode**

It's annoying that blue is too bright, it's too bright when everything is dark on my iPhone.  
Please set the splash screen to completely dark(black screen), that will pretty good, especially for dark mode users!  Here is the splash screen that I am talking about: https://imgur.com/a/VgilRfk

**### Important: This feature request is not the same as #1074. I have double confirm it .**

**Comment by di-ccmd** [comment]
**Additional information:**
Model Name: Apple iPhone 11
Software Version: 14.3 (download from App Store)
App version: 2021.1.5

**Comment by stbeep1** [comment]
Totally agree with that.
