### ISSUE TITLE
Menu bar bugs when setting app to only show in menu bar

### ISSUE THREAD

**Issue by parrel** [home-assistant/iOS#1485]
**Device model, version and app version**

Model Name: MacBook Pro (13-inch, 2020, four Thunderbolt 3-ports)
macOS Version: 11.2.1 (20D74)
App Version: 2021.2.2 
Safari Version: 14.0.3 (16610.4.3.1.4)

**Home Assistant Core Version**

2021.2.3

**Describe the bug**
When bringing the Home Assistant app to the front, the menu bar does not show 'Home Assistant' in the top left in the menu bar. Also, when you full screen the app, and move your mouse to the top of the screen to show the menu bar, it won't appear.

**To Reproduce**
In settings, enable the app to be displayed in the menu bar only. Then bring the app to the front, or make the app full screen.

**Expected behavior**
Menu bar should show like it does when you have the app set to show in 'Dock' only.

**Screenshots**

As you can see, the window is active but it shows finder in the menu bar.
<img width="491" alt="image" src="https://user-images.githubusercontent.com/22742147/107889385-7a7c6800-6f12-11eb-9c21-436c18e54f79.png">

**Additional context**

None

**Comment by BradyRosino** [comment]
I could be wrong, but this may be an Apple limitation of apps without a dock icon. I just experimented with a few apps on my Big Sur mac and all other apps that do not have a dock icon exhibit this same behavior. If I enable their dock icon, the menu bar items show up immediately.

**Comment by zacwest** [comment]
This is the default behavior of apps that are running without being present in the Dock. I think the desires here will be satisfied by #1407, which would make it so that "Dock & Menu Bar Item" display will hide the dock icon when 'quitting' the app.
