### ISSUE TITLE
Autofill menu occasionally disappears and clears text box

### ISSUE THREAD

**Issue by davedhoff** [home-assistant/iOS#1490]
**iOS device model, version and app version**. 
Model Name: iPhone 11 Pro Max
Software Version: 14.4
App version: 2021.2.2 (2021.55)

**Home Assistant Core Version**. 
Home Assistant core-2021.2.1

**Describe the bug**. 
When typing the name of an entity or device, selecting the desired object from the automatic drop-down will do one of three things:
* Exit the keyboard autofill the name (as expected)
* Exit the keyboard, leaving the drop-down on screen (and not autofilling the name)
    * Selecting the item from the list _does_ work after the keyboard has exited
* Exit the keyboard and empty the text box, leaving the user to start typing over again.

Whichever of these three cases happen, it will continue to happen each time until you've moved on to a new text box.

**To Reproduce**. 
1. Create a new Scene (for example, this bug exists in many areas)
2. Add a device by name (Usually the first works fine)
3. Add another device by typing part of the name, then tap the item from the drop down list.

**Expected behavior**
Tapping an item on the autofill list should always fill the name in to the text box and exit the keyboard.

**Additional context**
I'm interested in contributing to the home assistant project, but have two questions:
1. Is this a decent first issue?
2. Is this something that (even though the issue isn't present in safari) would be fixed on the frontend, rather than on the app?

**Comment by zacwest** [comment]
Even though it doesn't happen in Safari, it's _likely_ an issue in the frontend. The app doesn't do much to the webview, but Safari's keyboard handling is definitely different than webviews' handling. I'm unsure if it would be a good first issue. If you're looking for good iOS starter tasks, check out the [Hacktoberfest](https://github.com/home-assistant/iOS/labels/Hacktoberfest) label which still contains a few smaller things of varying difficulty.

**Comment by davedhoff** [comment]
Good to know, I'll close the issue here under the assumption that it is really a frontend issue, and take a look there. I'll also look through the hacktoberfest label, thank you for the guidance!
