### ISSUE TITLE
Content width too wide

### ISSUE THREAD

**Issue by esbenr** [home-assistant/iOS#1493]
When creating a Lovelace dashboard, the columns are too wide. 
They exceed the screen on iPhone X. 
(im not using panel mode)

https://user-images.githubusercontent.com/560120/109223744-49762000-77bb-11eb-9ff6-58cbfbdb4544.MP4

**Comment by ajdezigns** [comment]
I'm having this same issue

**Comment by esbenr** [comment]
Yeah. It’s The entire web part of The app.

**Comment by zacwest** [comment]
The app follows whatever sizing the frontend is delivering. Is it possible this custom display has width issues in its css? It's difficult to tell what might be the cause. Do you experience this in Safari? What version of HA are you running? What custom components or frontend pieces are you running?

**Comment by esbenr** [comment]
> The app follows whatever sizing the frontend is delivering. Is it possible this custom display has width issues in its css? It's difficult to tell what might be the cause. Do you experience this in Safari? What version of HA are you running? What custom components or frontend pieces are you running?

This is The HA companion app for iOS. The problem appears in the latest beta. 
i probably should have added that.

**Comment by ajdezigns** [comment]
My Home Assistant renders correctly when I use a web browser on my phone it is showing to wide when using home Home Assistant app I'm on Ver 2021.3 (2021.65) my Home Assistant it's self is 2021.2.3  I'm not running any custom frontend components.

**Comment by davidmartinek-dev** [comment]
I can confirm having this issue on iPhone 11Pro and iPhone 12Pro max. I am running the latest iOS app and Home Assistant 2021.4.0b3. I have also tried running it on iPhone X, PC and the issue is not present.

**Comment by zacwest** [comment]
Does this occur in Safari? Are you also using custom UI components?

**Comment by davidmartinek-dev** [comment]
It occurs in Home Assistant iOS app. I do not use any custom UI components.

**Comment by zacwest** [comment]
Does this _also_ occur in Safari?

**Comment by davidmartinek-dev** [comment]
No, it occurs only in iOS app. Both Safari and Chrome is ok. I have also created a simple dashboard with only a non custom switch element, but still no change.

**Comment by zacwest** [comment]
Can you share the lovelace dashboard config for the simple dashboard that doesn't work? I'm not able to reproduce the issue so I can't tell what is going wrong.

**Comment by ajdezigns** [comment]
I think I have located our issue in the settings of the app it's self. Although I've never modified this setting on my own when i set it back to 100% it corrected the issue.

![image0](https://user-images.githubusercontent.com/4680112/116005734-4c806780-a5d6-11eb-9886-32c108390cab.png)

**Comment by zacwest** [comment]
Interesting, it seems like <100% settings have stopped working recently. I believe from a frontend change, as even e.g. iOS 13 doesn't work anymore. Thanks for figuring that out.

**Comment by zacwest** [comment]
Nope, not frontend - this is a bug from the 'pinch to zoom' setting. For now either enable 'pinch to zoom' or set zoom to >= 100% and it'll work again.
