### ISSUE TITLE
App does not respect system "Hide" on login option

### ISSUE THREAD

**Issue by amaisano** [home-assistant/iOS#1495]
**Device model, version and app version**

Model Name: Macbook Pro 13"
macOS Version: 10.15.7
App Version: 2021.2.2
Safari Version: 14.0.3

**Home Assistant Core Version**

2021.2.3

**Describe the bug**
Main window does not respect system's "hide on startup" flag.

In earlier versions of the Mac app, you could hide the app on startup via Mac OS's native Users > Login Items > Applications > "Hide" checkbox. This version of the HA App does not respect these settings, and the HA app window is always shown when the laptop restarts, or when the app re-launches.

ALSO: HA app is not listed in the Login Items list after enabling "Launch App on Login" -- I had to add it to the list manually.

**To Reproduce**
- In HA app, settings set to:
  - Launch App on Login: TRUE
  - Show App In... Menu Bar
- In System Settings > Users > Login Items
  - Ensure HA app is in list
  - Checkbox for "Hide"
- Restart machine
- Observe that HA app window appears when HA starts up

**Expected behavior**
- HA app window is hidden (follows system Hide flag)

**Screenshots**

**Additional context**

- Perhaps of note: due to work restrictions, I had to install the app in ~/Users/amaisano/Applications. The app is installed from the App store however. Previous versions (before the option to set as Menu Bar display), respected the system Hide option, and the app was installed in this same location.

**Comment by bgoncal** [comment]
Can't reproduce, please let me know if this is still an issue for you.
