### ISSUE TITLE
Add option to hide application window on startup

### ISSUE THREAD

**Issue by amaisano** [home-assistant/iOS#1496]
**Is your feature request related to a problem? Please describe.**
https://github.com/home-assistant/iOS/issues/1495

**Describe the solution you'd like**
In addition to the General "Launch App on Login" and "Show App In..." options, we should have a checkbox for "Hide on startup," so that every time the computer restarts or the app relaunches, we don't have to manually close the window. This is more or less like the concept of running the HA app as a background task, but probably an easier lift.

**Additional context**
When the app is set to only show in the Menu Bar, I think it loses some of the system features of being able to show/hide the application (usually options found by right-clicking the dock icon). It's also interesting that left-clicking the Menu Bar icon for the HA app toggles the main window (show/hide behavior).

**Comment by PierreScerri** [comment]
I agree with this suggestion.  I do not use the app window as it is too slow to update.  I use the app for the sensors.
