### ISSUE TITLE
Binary sensor active state stays "ON" after power off machine

### ISSUE THREAD

**Issue by marcinbauer85** [home-assistant/iOS#1501]
**Device model, version and app version**
Model Name: MBA 2016 14"
macOS Version: 11.2
App Version: 2021.2.2 (2021.55)
Safari Version: Same as OS

**Home Assistant Core Version**
core-2021.3.0

**Describe the bug**
The binary_sensor.<device>_active state stays as "on" in HA even after power off machine.

**To Reproduce**
Integrate the macOS app with the local HA instance.

**Expected behavior**
binary_sensor.<device>_active state should change to "off" when machine is off (app is closed).

**Comment by zacwest** [comment]
Please try the [latest beta](https://github.com/home-assistant/iOS/releases) and see if that resolves this issue. There's been a few different fixes in 2021.3 so far for this. If this does not work, it would be very useful to see logs from when this is happening. You can reveal the log folder via the action in Preferences, truncate them to as much as you'd like to reveal, and share what time the issue happened at. You can then attach the logs here or send them to me [via Dropbox](https://www.dropbox.com/request/CtVWqILBXZ41tmFSGK2y).

**Comment by marcinbauer85** [comment]
I can confirm that this is now working with the latest release 77!
👍

**Comment by ericmatte** [comment]
Hi, I'm still having this issue.

Just tested with the latest beta and version from the App Store.

**Device model, version and app version**
Model Name: MBP 2021 16" (M1 Pro)
macOS Version: 12.2.1
App Version: 2022.3 (358)

**Home Assistant Core Version**
2022.3.3

**Comment by thombook** [comment]
still (again) the case, Binary sensor active state stays "ON" after power off machine. Mac Mini M4, macOS 15.2, App Version 2024.12.2(2024.1058), HA Core 2025.1.4
