### ISSUE TITLE
[Crash] 2021.3 (71) version of Mac Application crashes on launch (Mac OSx 11.3)

### ISSUE THREAD

**Issue by MwC-Trexx** [home-assistant/iOS#1502]
**Device model, version and app version**

Model Name:  MacBook Pro (Retina, 15-inch, Late 2013)
macOS Version: 11.3 Beta
App Version:  2021.3 (71)
Safari Version: Version 14.1 (16611.1.18.1.2)

**Home Assistant Core Version**

2021.3.0

**Describe the bug**
Application immediately crashes at launch

**To Reproduce**
Open the app

**Expected behavior**
App launches.

**Screenshots**

**Additional context**

`Process:               Home Assistant [3238]
Path:                  /Applications/Home Assistant.app/Contents/MacOS/Home Assistant
Identifier:            io.robbie.HomeAssistant
Version:               2021.3 (2021.71)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Home Assistant [3238]
User ID:               501

Date/Time:             2021-03-04 12:52:32.032 -0600
OS Version:            macOS 11.3 (20E5196f)
Report Version:        12
Anonymous UUID:        43466829-ACB5-A081-9D29-CEC5B171BC31

Sleep/Wake UUID:       102D4171-F4F2-486E-B6B5-4BF7C2BE77BB

Time Awake Since Boot: 22000 seconds
Time Since Wake:       12000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_PROTECTION_FAILURE at 0x00007ffee1ce7ff8
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [3238]

VM Regions Near 0x7ffee1ce7ff8:
    MALLOC_LARGE             7f80b350e000-7f80b352b000 [  116K] rw-/rwx SM=PRV  
--> STACK GUARD              7ffede4e8000-7ffee1ce8000 [ 56.0M] ---/rwx SM=NUL  stack guard for thread 0
    Stack                    7ffee1ce8000-7ffee24e8000 [ 8192K] rw-/rwx SM=SHM  thread 0

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_malloc.dylib        	0x00007fff20280e64 nanov2_allocate_from_block + 8
1   libsystem_malloc.dylib        	0x00007fff20280650 nanov2_allocate + 130
2   libsystem_malloc.dylib        	0x00007fff2028269d nanov2_calloc + 123
3   libsystem_malloc.dylib        	0x00007fff2029b0ae _malloc_zone_calloc + 59
4   com.apple.CoreFoundation      	0x00007fff204d51a2 _CFRuntimeCreateInstance + 294
5   com.apple.CoreFoundation      	0x00007fff204d48ac __CFStringCreateImmutableFunnel3 + 1900
6   com.apple.CoreFoundation      	0x00007fff204e0b56 CFStringCreateWithBytes + 27
7   libswiftFoundation.dylib      	0x00007fff304b6091 @objc NSObject.createTaggedString(bytes:count:) + 33
8   libswiftCore.dylib            	0x00007fff2c8808b7 String._bridgeToObjectiveCImpl() + 167
9   io.robbie.HomeAssistant       	0x000000010d7ffe5f 0x10d718000 + 949855
`

**Comment by zacwest** [comment]
#1499
