### ISSUE TITLE
Add Indonesian (id) locale to Lokalise

### ISSUE THREAD

**Issue by lunmay** [home-assistant/iOS#1507]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Since Core and Frontend is mostly done for Indonesian, please add Indonesian (id) locale to Home Assistant Companion for iOS project in Lokalise.
Thanks

**Additional context**

**Comment by robbiet480** [comment]
Added and I’ve enabled your account to contribute to Indonesian
