### ISSUE TITLE
App crash at startup on MacOS 11.3 Beta (20E5196f)

### ISSUE THREAD

**Issue by oester** [home-assistant/iOS#1508]
**Device model, version and app version**

Model Name: MacBook Pro (15-inch, 2016)
macOS Version: 11.3 Beta (20E5196f)
App Version: 2021.3
Safari Version: Version 14.1 (16611.1.18.1.2)

**Home Assistant Core Version**
 core-2021.3.0

**Describe the bug**

Mac App crashes at startup. Has been working previous on other beta versions.

Process:               Home Assistant [38170]
Path:                  /Applications/Home Assistant.app/Contents/MacOS/Home Assistant
Identifier:            io.robbie.HomeAssistant
Version:               2021.3 (2021.71)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Home Assistant [38170]
User ID:               501

Date/Time:             2021-03-05 10:28:29.649 -0600
OS Version:            macOS 11.3 (20E5196f)
Report Version:        12
Bridge OS Version:     3.0 (14Y908)
Anonymous UUID:        DBC56975-C345-28FF-9954-32D4A7AD586B

Time Awake Since Boot: 240000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_PROTECTION_FAILURE at 0x00007ffee03dbff8
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [38170]

VM Regions Near 0x7ffee03dbff8:
    MALLOC_TINY              7ff049c00000-7ff049d00000 [ 1024K] rw-/rwx SM=PRV  
--> STACK GUARD              7ffedcbdc000-7ffee03dc000 [ 56.0M] ---/rwx SM=NUL  stack guard for thread 0
    Stack                    7ffee03dc000-7ffee0bdc000 [ 8192K] rw-/rwx SM=SHM  thread 0

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_malloc.dylib        	0x00007fff2042b61a nanov2_allocate + 76
1   libsystem_malloc.dylib        	0x00007fff2042d69d nanov2_calloc + 123
2   libsystem_malloc.dylib        	0x00007fff204460ae _malloc_zone_calloc + 59
3   com.apple.CoreFoundation      	0x00007fff206801a2 _CFRuntimeCreateInstance + 294
4   com.apple.CoreFoundation      	0x00007fff2067f8ac __CFStringCreateImmutableFunnel3 + 1900
5   com.apple.CoreFoundation      	0x00007fff2068bb56 CFStringCreateWithBytes + 27
6   libswiftFoundation.dylib      	0x00007fff30661091 @objc NSObject.createTaggedString(bytes:count:) + 33
7   libswiftCore.dylib            	0x00007fff2ca2b8b7 String._bridgeToObjectiveCImpl() + 167
8   io.robbie.HomeAssistant       	0x000000010f10be5f 0x10f024000 + 949855
9   io.robbie.HomeAssistant       	0x000000010f10bf27 0x10f024000 + 950055
10  io.robbie.HomeAssistant       	0x000000010f10c00f 0x10f024000 + 950287
11  io.robbie.HomeAssistant       	0x000000010f10bf99 0x10f024000 + 950169
12  io.robbie.HomeAssistant       	0x000000010f10c00f 0x10f024000 + 950287
13  io.robbie.HomeAssistant       	0x000000010f10bf99 0x10f024000 + 950169
14  io.robbie.HomeAssistant       	0x000000010f10c00f 0x10f024000 + 950287
15  io.robbie.HomeAssistant       	0x000000010f10bf99 0x10f024000 + 950169
16  io.robbie.HomeAssistant       	0x000000010f10c00f 0x10f024000 + 950287
17  io.robbie.HomeAssistant       	0x000000010f10bf99 0x10f024000 + 950169
18  io.robbie.HomeAssistant       	0x000000010f10c00f 0x10f024000 + 950287
19  io.robbie.HomeAssistant       	0x000000010f10bf99 0x10f024000 + 950169
20  io.robbie.HomeAssistant       	0x000000010f10c00f 0x10f024000 + 950287

**To Reproduce**
Launch App

**Expected behavior**
App Starts normally.

**Screenshots**

**Additional context**

**Comment by zacwest** [comment]
#1499 -- this should also be fixed in the latest Mac beta
