### ISSUE TITLE
How to remove the left and right space areas please help me out.

### ISSUE THREAD

**Issue by horacecar** [home-assistant/iOS#1516]
**iOS device model, version and app version**

Model Name: 
Software Version: 
App version: 
latest ios version 2021.2.2 (2021.55)
**Home Assistant Core Version**

Home Assistant 2021.3.1
**Describe the bug**
How to remove the left and right space areas please help me out.  using iphone 12 pro max , ios:14.3

and also the upper left corner menu button is missing and cannot click it.
**To Reproduce**

**Expected behavior**

**Screenshots**
![0307174512](https://user-images.githubusercontent.com/44496483/110235784-e596e880-7f6c-11eb-9450-7bd1a60e564b.jpg)

**Additional context**

**Comment by TomBrien** [comment]
Do you see the saMe issue in safari?

**Comment by horacecar** [comment]
> Do you see the saMe issue in safari?

Yes. Same.

**Comment by horacecar** [comment]
> Do you see the saMe issue in safari?
yes , same, this screenshot below is from safari , the first one is from ios ha app.
![307181915](https://user-images.githubusercontent.com/44496483/110236611-a6b76180-7f71-11eb-8a8e-93955a65e7be.jpg)

**Comment by TomBrien** [comment]
As you see this in Safari too this is not an issue with the app. To me it looks like an issue with the image size or aspect ratio of the background image, you may want to try a different image and see what happens. Otherwise, please [open an issue on the frontend repo](https://github.com/home-assistant/frontend/issues/new/choose).

**Comment by horacecar** [comment]
> As you see this in Safari too this is not an issue with the app. To me it looks like an issue with the image size or aspect ratio of the background image, you may want to try a different image and see what happens. Otherwise, please [open an issue on the frontend repo](https://github.com/home-assistant/frontend/issues/new/choose).

I already shot a different image still same.

**Comment by horacecar** [comment]
And also the upper left menu button is missing.
