### ISSUE TITLE
New version resets language settings

### ISSUE THREAD

**Issue by michalk-k** [home-assistant/iOS#1533]
Model Name: iPhone X
Software Version: iOS 14.1
App version: 2021.3 (2021.77)
But it's appearing in all releases since fall 2020 when revamped app has been released

**Home Assistant Core Version**
HA Core 2021.1.5
**Describe the bug**
Everytime new version of the application is released, its installation resets application language to operating system language.
In my instance, OS is set to Czech, but I want app to run English language.

It's even more annoying, since language setting cannot be found in application configuration. It must be found in app settings available in system config.

**To Reproduce**
1. Change language to one different than OS language
2. Install new version of app

**Expected behavior**
New version keeps previously selected language 

**Screenshots**

**Additional context**

**Comment by zacwest** [comment]
This sounds more like an iOS bug than the app -- I don't think there's anything we do that would cause this. Do any other apps behave this way?

**Comment by zacwest** [comment]
You should also try upgrading your OS - 14.4.1 is the latest public release.

**Comment by michalk-k** [comment]
> This sounds more like an iOS bug than the app -- I don't think there's anything we do that would cause this. Do any other apps behave this way?

no. never experienced it with other apps.

goong to update os, but then I would wait for next HA app update. May I expect that the app language will survive uninstal and reinstal?

**Comment by bgoncal** [comment]
Is this still an issue in 2024? Let me know and I will reopen it
