### ISSUE TITLE
Deleting app including data and settings

### ISSUE THREAD

**Issue by ThomDietrich** [home-assistant/iOS#1539]
**iOS device model, version and app version**

Model Name: iPhone 12
Software Version: latest
App version: latest

**Home Assistant Core Version**

core-2021.3.2

**Describe the bug**

The app can not be fully reset. I am not an expert with iPhones but deleting the app through the wobbly (x) or through the app store does not delete previous settings, e.g. server URL and login credentials. It is my understanding that an app should do that!? Also followed the instructions here https://support.apple.com/en-us/HT205347

Please be aware that I do not own an iPhone and am reporting this issue in my brothers stead.

**Comment by Mariusthvdb** [comment]
can confirm this to be happening as reported in another issue, where I needed to re-install the app afresh.
in the app, you can click menu/app configuration, scroll down and click Herstel (in Dutch, probably Reset, or recover, in English)

this will clear all config settings.

**Comment by ThomDietrich** [comment]
Thanks @Mariusthvdb, this seems to work. It's a good workaround but imho not enough. I do not know if there are guidelines by apple but normally my expectation would be that an uninstall (1) leaves the phone in a clean state and (2) allows for a fresh start at a later point. 
The article linked above mentions a configuration profile, maybe that would be a solution to tick all boxes?

**Comment by robbiet480** [comment]
We don't install a configuration profile, that isn't possible from apps anyway.

The app is functioning as designed. We must store all the data in a folder outside of the app that survives app being deleted to allow the data to be shared amongst all our targets (the app, the notification extensions, the widget, etc). iOS should clean up this folder after some unknown amount of time (I think 30 days) after going unused.
