### ISSUE TITLE
Unable to back to main “menu” after entering portainer dashbors

### ISSUE THREAD

**Issue by Assidefok** [home-assistant/iOS#1541]
**iOS device model, version and app version**

Model Name: Iphone Xr
Software Version: ios 14.4
App version: 2021.3

**Home Assistant Core Version**
Last aviable

**Describe the bug**
After entering portainer web interface I’m unable to go back to main menu
**To Reproduce**

**Expected behavior**
After pressing the main back button of the top left it should retourb to normal dashboard
**Screenshots**

**Additional context**

**Comment by TomBrien** [comment]
Does swiping from the left bring up the side menu bar?

**Comment by Assidefok** [comment]
Neither did. Had to reinstall app

El dj, 25 març 2021 a les 10:13 Tom Brien ***@***.***> va
escriure:

**Comment by bgoncal** [comment]
Frontend is aware of the issue, there is nothing we can do on the App side, please open an issue to frontend to keep track of progress.
