### ISSUE TITLE
app doesn't snap to correct size on orientation change

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/iOS#1545]
**iOS device model, version and app version**

Model Name: iPhone 11 Pro
Software Version: 14.4.1
App version: 2021.3 (2021.77))

**Home Assistant Core Version**

2021.3.4
**Describe the bug**

changing orientation of the device doesn't adjust screen to snap into place, it seems to zoom in and stay that way, even after changing back again. Below screenshots are the actual screens, no zooms handmade. As you can see they are fully zoomed in, and no menu items are displayed anymore.

**To Reproduce**
start portrait:

![20210320_113143000_iOS](https://user-images.githubusercontent.com/33354141/111868157-9a230800-8978-11eb-9656-adcb1eb7421d.png)

move iPhone to landscape:

![20210320_113148000_iOS](https://user-images.githubusercontent.com/33354141/111868174-b0c95f00-8978-11eb-864a-7d1c7a2118a9.png)

and back to portrait:

![20210320_113153000_iOS](https://user-images.githubusercontent.com/33354141/111868183-bb83f400-8978-11eb-8194-09c41a04ae7c.png)

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by zacwest** [comment]
I believe this was a bug related to zooming which was resolved. Please comment/reopen if this is still occurring since those fixes.

**Comment by Stooovie** [comment]
Unfixed as of 2024.6

**Comment by bgoncal** [comment]
> Unfixed as of 2024.6. [This is my video](https://youtu.be/jql-yhj9ecQ?si=1Sl2T_USxO8_bkoD) from 15. July 2024, everything is fully updated.

You mentioned in the frontend repo issue that this also happens in iOS Safari right? If thats the case let's keep the discussion in frontend, otherwise let me know

**Comment by Stooovie** [comment]
Yes. It's happening in everything - plain Safari, PWA and the Companion app.

**Comment by bgoncal** [comment]
Ok, then I'll keep this issue closed here since it's no app specific, discussion continues on frontend.

My initial advice would be to disable your custom components to identify if any of them is causing the issue, since we didn't receive other reports like that the problem probably is in your instance somehow
