### ISSUE TITLE
add system variables (templates) for Menu bar text

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/iOS#1550]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Before when using Custom Header we had these system [built-in variables](https://maykar.github.io/custom-header/#templates/builtin) available for Jinja templates:

```
        User: {{user}}, User_id: {{userID}}, Admin: {{isAdmin}},
        Owner: {{isOwner}}, Device_id: {{deviceID}}, View: {{viewTitle}},
        Path: {{viewPath}}, Index: {{viewIndex}}, Url: {{url}},
        User agent: {{userAgent}}
```

would be really nice to have these, now you've enabled Menu bar text in the App

**Additional context**
Custom Header now being archived, official availability for these system templates has gone too. Please consider bringing them back?

**Comment by TomBrien** [comment]
The header displayed in the app is set by the frontend and is not controlled by the app in anyway. This seems very similar to home-assistant/frontend#7569. Closing here as it is beyond the scope of the app.

**Comment by Mariusthvdb** [comment]
guess I didnt make myself clear enough? the app now allows for jinja templates in the header, and this was explicitly mentioned in the release note of the app.
see: https://github.com/home-assistant/iOS/pull/1529

I was merely asking if several system variables were made available in the app for those templates, and this has nothing to do with my other feature request you linked to.

**Comment by TomBrien** [comment]
Ahh I may have misunderstood. The PR you linked to is for the Mac app and corresponds to adding values to the top menu bar in macOS (see below) not the header in Home Assistant. Is it here you would like to be able to use system variables?


![](https://user-images.githubusercontent.com/74188/110993728-851cf800-832c-11eb-885d-1787a2e5443b.png)

**Comment by Mariusthvdb** [comment]
yes please! sorry for the confusion. As you can see the time is of not much use, but the other system variables would be interesting to see in a glance.

**Comment by Mariusthvdb** [comment]
made it with help of another add-on, browser-mod:

<img width="183" alt="Schermafbeelding 2021-03-26 om 09 01 44" src="https://user-images.githubusercontent.com/33354141/112600956-1e123f80-8e12-11eb-9c57-5680659b9f1c.png">


```
{{state_attr('sensor.hvbmbpro16_app','path').split('/')[2]|capitalize|replace('_',' ')}}
```

which is a hassle ;-) would become of these things could be made built-in, and, even better, be displayed on Hover tooltip.

**Comment by zacwest** [comment]
The app could include things that _it_ knows, but anything that's chaining off `hass` like user state is going to be something that needs to be added core-side. Could you give an example of what you're looking to include in the menu bar? Is it the current webview state, for example?

**Comment by Mariusthvdb** [comment]
yes, like I suggested above, it would be very nice to be able to show eg user, dashboard, or view in the menu bar. Ive been able to template a few of those, but would hope the hass object could be made available, like it is in JS templates for the frontend on some cards, eg button card? Or use the browser-mode attributes, if and when installed?

see this for button card:

zzz
  - type: custom:button-card
    name: Variables
    show_name: true
    show_label: true
    name: |
      [[[ return 'UserID: ' + hass.user.id + "<br>" +
                 'Username: ' + hass.user.name + "<br>" +
                 'Owner: ' + hass.user.is_owner + "<br>" +
                 'Admin: ' + hass.user.is_admin + "<br>" +
                 'DeviceID: ' + localStorage['lovelace-player-device-id']; ]]]
    label: |
      [[[ return 'Version: ' + hass.config.version + "<br>" +
                 'Href: ' + window.location.href + "<br>" +
                 'Path: ' + window.location.pathname + "<br>" +
                 'UserAgent: ' + navigator.userAgent + "<br>" +
                 'Entity id: ' + window.browser_mod.entity_id; ]]]
```

any of these could be great options to show in the menu bar, depending on  needs of course. Ive filed a FR for browser-mod to make those available to Jinja backend templating, but thats not yet seen response, not sure if Thomas if willing to look at that.

Anyways, was hoping the app could reveal these too, without all the more complicated templating.

btw, after the app has slept for a while, the menu bar shows 
<img width="77" alt="Schermafbeelding 2021-03-27 om 16 41 36" src="https://user-images.githubusercontent.com/33354141/112735297-45b8f300-8f4b-11eb-894b-266a046819c1.png">

which is Error in Dutch ;-) and it wont come back alive the actually using the app again.
