### ISSUE TITLE
Actions buttons on Watch and iOS should be swipeable to prevent accidental touches.

### ISSUE THREAD

**Issue by brayStorm** [home-assistant/iOS#1569]
**Is your feature request related to a problem? Please describe.**

Actions on Apple Watch and iPhone are very prone to accidental presses. 

**Describe the solution you'd like**

Can they be changed, or have the option in App Configuration, to make them swipe-to-confirm? Similar to old swipe to unlock iPhone?

**Additional context**

**Comment by bcmitri** [comment]
Seems like a similar request to #1345.

**Comment by zacwest** [comment]
I agree, feels like a duplicate of this one, thanks!
