### ISSUE TITLE
Home Assistant app blurry on macOS

### ISSUE THREAD

**Issue by phrz** [home-assistant/iOS#1572]
**Device model, version and app version**

Model Name: Mac Mini (M1, 2020)
macOS Version: macOS Big Sur 11.2.1
App Version: 2021.4 (2021.113)
Safari Version: 14.0.3

**Home Assistant Core Version**
core-2021.3.4
--

**Describe the bug**
On macOS, the Home Assistant app is blurry, as it seems to render everything at a pixel density different from other apps. When I compare the app side-by-side with Safari, text, icons, and images are more blurry. The issue is present on @1x displays and @2x displays (e.g. MacBook Air).

**To Reproduce**
Open the Home Assistant app in macOS and place it side-by-side with Home Assistant in Safari. Note the comparative sharpness of text.

**Expected behavior**
Text should render similarly in the Home Assistant app when compared to text throughout the system, as well as icons and images. The application should not appear more blurry than the rest of the system.

**Screenshots**
![Screen Shot 2021-04-05 at 09 17 30](https://user-images.githubusercontent.com/2007088/113584809-f6309200-95f0-11eb-8171-a0ab4903c8e1.png)
Safari on the left and Home Assistant on the right.

**Additional context**
n/a

**Comment by zacwest** [comment]
Fixed in #1600.

**Comment by henrikbjorn** [comment]
![Skærmbillede 2021-05-05 kl  20 51 18](https://user-images.githubusercontent.com/19725/117193938-c63d0000-ade3-11eb-8ef2-e99e315a471b.png)

Left is the MacOS app and right is a Chrome Webapp (Basically just chrome without the address bar)

It seems that there is still something off with the text in the MacOS app.

@zacwest

**Comment by phrz** [comment]
@henrikbjorn the issue I submitted was an app-wide resolution problem (note the blurry icons) and this, as far as I can see, was resolved. Your example appears to be a minor difference in rendering and anti-aliasing. Can you compare this app with Safari? Chrome is a different browser engine, likely with different text rendering.

**Comment by henrikbjorn** [comment]
The text rendering is the same across different browsers. Only the MacOS App is doing something wierd.
