### ISSUE TITLE
Casing issue in actionable notifications for iOS - the category identifier need to be uppercased when calling the service, regardless og the lowercasing in the category definition

### ISSUE THREAD

**Issue by esbenr** [home-assistant/iOS#1576]
**The problem**

Creating a category in configuration.yaml using lower case as per the documentation:
```
- name: Camera driveway motion
  identifier: "camera_driveway_motion"
  actions:...
```

Then calling the service notify.mobile_app_device with payload:
```
{
  "title": "title",
  "message": "message",
  "data": {
    "push": {
        "category": "CAMERA_DRIVEWAY_MOTION"
    }
}
```

The identifier has to be upper case even though the documentations says it has to be lower case when you define it.
It appears that there probably is a .toUpper(...) in the string comparison somewhere. That is terribly secret and impossible to know for the end user.
if the documentations specifies lower case, then it should also be lower case when calling the service. If not case insensitive...

**What is version of Home Assistant Core has the issue?**

2021.1.5

**What was the last working version of Home Assistant Core?**

_No response_

**What type of installation are you running?**

Home Assistant Supervised

**Integration causing the issue**

iOS companion app?

**Link to integration documentation on our website**

https://companion.home-assistant.io/docs/notifications/actionable-notifications/

**Example YAML snippet**

``` category definition
- name: Camera driveway motion
  identifier: "camera_driveway_motion"
  actions:
    - identifier: "snooze_10m"
      title: "Snooze 10 min."
      activationMode: "background"
      authenticationRequired: false
      destructive: false
      behavior: "default"
    - identifier: "snooze_30m"
      title: "Snooze 30 min."
      activationMode: "background"
      authenticationRequired: false
      destructive: false
      behavior: "default"
    - identifier: "snooze_2h"
      title: "Snooze 2 timer"
      activationMode: "background"
      authenticationRequired: false
      destructive: false
      behavior: "default"
```

**Anything in the logs that might be useful for us?**

``` call service payload
{
  "title": "title",
  "message": "message",
  "data": {
    "push": {
        "category": "CAMERA_DRIVEWAY_MOTION"
    },
    "attachment": {
      "url": "https://sdxgp7xws9pvzg8f7j1bv2cz2nlw0kgr.ui.nabu.casa/local/snapshots/driveway/2021-02-23_22-06-31.jpg",
      "content-type": "jpeg",
      "hide-thumbnail": false
    }
  }
}

```

The identifier has to be upper case even though the documentations says it has to be lower case when you define it.
It appears that there probably is a .toUpper(...) in the string comparison somewhere. That is terribly secret and impossible to know for the end user.
if the documentations specifies lower case, then it should also be lower case when calling the service. If not case insensitive...

**Comment by zacwest** [comment]
This sounds more like a request to update the documentation, which I agree with; feel free to submit a pull request to clarify any point of confusion there, if you'd like it updated quickly.

I don't believe the app will be able to stop converting the identifiers from the configuration.yaml to uppercase, since it would be a breaking change for all existing users without a great reason for doing so.

For convenience, both the fully-uppercased and fully-lowercased versions are registered with the system so both lowercase are accepted for the category identifiers; however, we cannot accept any mix of casing as we register the category identifiers with the system and never directly deal with them ourselves, and registering every permutation of casing would be excessive.

**Comment by zacwest** [comment]
OK, recent updates:

- Categories are now forced to be uppercase on the Firebase side of things, so there's no potential for using the wrong case.
- The focus of 2021.5 and forward is around doing dynamic notification actions without using categories, which I think eliminates this area of confusion as well.
