### ISSUE TITLE
Links open in non set browser

### ISSUE THREAD

**Issue by eavanvalkenburg** [home-assistant/iOS#1577]
**iOS device model, version and app version**

Model Name: xr
Software Version: 14.4.2
App version: 2021.4.1 (2021.115)

**Home Assistant Core Version**

2021.4.2
**Describe the bug**
When I click on a link in the HA app, rather than using the system set Brower (edge in my case) it opens Chrome and in a in-private tab!
**To Reproduce**
Set a different browser (I think) and click a link in the app, first noticed it when clicking the release notes link in supervisor but also noticed it when I clicked a ?-button in the app settings.
**Expected behavior**

**Screenshots**

**Additional context**

**Comment by zacwest** [comment]
What do you have set for the value in App Configuration > General > Open links in…?

**Comment by eavanvalkenburg** [comment]
I feel stupid now, didn't know that setting existed even though I probably changed it at some point!
