### ISSUE TITLE
QR/Barcode Scanner integration

### ISSUE THREAD

**Issue by hquick81** [home-assistant/iOS#1584]
Hi all,

i would love to see a barcode / qr code reader integration inside the HA app. This would open a lot of new possibilities for integrations.
For example: 
- Scan a barcode on an item in you kitchen to add it to your shopping cart
- Scan QR codes to trigger automations ( for older ios devices with no NFC support )
- Play a certain playlist/song on spotify

It should be reachable very fast, for example as a button on a widget.

**Comment by robbiet480** [comment]
Most of these can be accomplished by making a QR code with the [URL Handler](https://companion.home-assistant.io/docs/integrations/url-handler).

**Comment by zacwest** [comment]
Additionally, you can use the QR code support built into the [tag integration](https://companion.home-assistant.io/docs/integrations/universal-links). Any valid `home-assistant.io/tag/xyz` url will open in the app, using whatever QR code scanner (camera, control center) that you like. I do not think adding a camera into the iOS app will be easy to use nor better than these choices.
