### ISSUE TITLE
Restore old style actions widget

### ISSUE THREAD

**Issue by aetha** [home-assistant/iOS#1595]
**Is your feature request related to a problem? Please describe.**
In the new beta of the iOS app, the old actions widget has been replaced altogether by the new iOS 14 style widget. I much prefer the old widget because it's more compact, and dynamically adjusts size according to the number of action buttons configured.

**Describe the solution you'd like**
Please restore the old widget, making both styles available.

**Additional context**
n/a

**Comment by aetha** [comment]
Oh it came back again! No idea why that happened, but I'll close this (non) issue.

**Comment by TomBrien** [comment]
The old action widget uses the pre iOS 14 today view. As Apple move to more home screen widgets. It's entirely possible that the old widget will be removed beyond our control
