### ISSUE TITLE
Allow configuring update triggers (enter/exit) per zone

### ISSUE THREAD

**Issue by jjpeet** [home-assistant/iOS#160]
I'm noticing that now iBeacons seem to work in the new app, I'm needing the app to send location when I enter an iBeacon zone, but do nothing when I exit an iBeacon zone.

The use case is an automation that opens my Garage. Because often the phone doesn't report I'm in my home zone for a while after getting home, therefore the garage doesn't open. I have put an iBeacon at the front of the house, and now it reliably sends location (often the iBeacon does it rather than GPS).

But when I'm walking around in my house, I go out of the iBeacon zone, and because I'm inside the house, an inaccurate gps location is sent (often 1000m), putting me away from home.

So, if I could configure the app to only send location update on entry, and not exit of iBeacon zone I think that would pretty much make it perfect!

JP

**Comment by TomBrien** [comment]
I believe this is the current case that entry of iBeacon is used but exit not. I'm going to close this but let me know if that's wrong and I've misunderstood.
