### ISSUE TITLE
Notification : no snapshot

### ISSUE THREAD

**Issue by lowrisk75** [home-assistant/iOS#1602]
Config Raspberry Pi 4 / Home Assistant OS, Nginx Proxy Manager, CloudFlare Firewall, CloudFlare for Team, Cloudflare Gateway.

This stopped working for a while.
I initially though this was linked to my nginx install but the snapshot work just fine, I can load the snapshot locally or manually but is not attached to my iOS notification.
My AppleWatch mention a notification but nothing on my iPhone.

node-red : 

```
{
   "title": "Car outside",
   "message": "There is a car outside",
   "data": {
       "subtitle": "Side motion detector",
       "push": {
           "sound": "Alarm_Nightstand_Haptic.caf"
        },
       "attachment": {
           "content-type": "jpg",
           "url": "https//:mysub.domain.com/local/front_snapshot.jpg"
        }
    }
}
```

also I manage to sent a external jpg image no issue but when I sent my 4K snapshot, nothing!
-- livefeed don't seems to work neither.

not sure if related :
Im wondering is that anything to do with Cloudflare Access, also is this an expected behaviour from safari to cache the image? on two different computers, I have a another picture showing up when I load the URL on safari (a few days old, different from the actual image in the www folder.) if I open Firefox instead, I have to log in to CloudFare Access, then I get the correct image.

_Originally posted by @lowrisk75 in https://github.com/home-assistant/iOS/issues/362#issuecomment-826366544_

**Comment by zacwest** [comment]
```
           "url": "https:mysub.domain.com/local/front_snapshot.jpg"
```

Is this correct? It looks like you're missing `//` here, e.g. `https://mysub…`.

**Comment by lowrisk75** [comment]
> ```
>            "url": "https:mysub.domain.com/local/front_snapshot.jpg"
> ```
> 
> 
> Is this correct? It looks like you're missing `//` here, e.g. `https://mysub…`.
> 
> 
> Additionally, attachment errors will add an attachment image to the notification if they are failed. Does this not occur?


Sorry, I mistyped as I edited the URL but the URL is correct on node red
 "url": "https://mydomain.com/local/front_snapshot.jpg"
   
PS I also tried to specify the port :443 but same issue (the URL would load on my web browser though)

**Comment by zacwest** [comment]
1. Do you receive an error attachment for this notification?
2. Does the URL load specifically in Safari on your device?

Please export log files in App Configuration and [share them to me](https://www.dropbox.com/request/CtVWqILBXZ41tmFSGK2y) -- I'll delete them after taking a look. You can also look yourself for anything containing `attachment`.

**Comment by lowrisk75** [comment]
> 1. Do you receive an error attachment for this notification?
> 2. Does the URL load specifically in Safari on your device?
> 
> Please export log files in App Configuration and [share them to me](https://www.dropbox.com/request/CtVWqILBXZ41tmFSGK2y) -- I'll delete them after taking a look. You can also look yourself for anything containing `attachment`.

I have no error at all from the notification, just no attachment 
(except the Apple Watch which display "1 image attached" but nothing with it"
https://ibb.co/92hGr4w
The URL can load fine, just sometime is weirdly cached (I'm getting a older image) -- I updated my primary post with more detail on that

--log uploaded

**Comment by zacwest** [comment]
I believe the notification center on Watch requires you tap the image to see it. On iOS, it'll show up in notification center if you simultaneously have the watch running and it won't alert on both. I suggest checking there on iOS to see what the attachment image is; when the download fails, it adds an error image.

If Cloudflare Access requires that you sign into something before the URL will work, it definitely will not work for attachments and there's no workaround other than somehow encoding authentication in the URL; I don't know enough about it to know if this is possible.

If you're looking for a non-public location to store images that require authentication, the media directory (via e.g. `/media/local/image.jpg` stored in `/media/image.jpg` -- depending on your installation method) requires it for viewing. You can send the relative URL (just `/media/local/image.jpg`) for the `url` key and it will figure it out and attach it.

**Comment by lowrisk75** [comment]
When I tap on the notification + image message on my watch, I have a new "window" with the message notification but nothing else.

I think the issue is probably linked with Cloudflare Access alright, I will look at Cloudflare Access option later and maybe temporarily disable it to check whatever that fix the notification attachment or not.

Closing for now, and thank you for your time
