### ISSUE TITLE
Companion App creates multiple instances in Mobile App integration

### ISSUE THREAD

**Issue by Wolk9** [home-assistant/iOS#1606]
**Device model, version and app version**

Model Name: iMac Retina 5K, 27", Late 2015
macOS Version: 11.2.3 (20D91)
App Version: 2021.4.1 (2021.155)
Safari Version: 

**Home Assistant Core Version**
core-2021.4.6

**Describe the bug**
Companion App creates multiple instances in Mobile App Integration like:

<name>
<name>_2
<name>_3
<name>_4

Therefor I can't refer properly to the 'working' version of the needed sensor.

**To Reproduce**
Don't know how, as I don't know why it does it.

**Expected behavior**
I expect the companion app to see that it is repeating itself. 

**Screenshots**
![Schermafbeelding 2021-04-29 om 17 21 12](https://user-images.githubusercontent.com/66083478/116575824-4dcfce00-a90f-11eb-8c43-f132d5b2f67f.png)
<img width="1187" alt="Schermafbeelding 2021-04-29 om 17 21 41" src="https://user-images.githubusercontent.com/66083478/116575902-5f18da80-a90f-11eb-8e0f-24676d7a94a5.png">

**Additional context**

**Comment by zacwest** [comment]
Please look for "Integration is missing; registering" in the event log (in Preferences, under Debugging if you're on 2021.5). Click into it -- what's the result there?

**Comment by Wolk9** [comment]
Do you mean in the companion app? I run version 2021.115, the latest in imho.

**Comment by Wolk9** [comment]
> Please look for "Integration is missing; registering" in the event log (in Preferences, under Debugging if you're on 2021.5). Click into it -- what's the result there?

I do not know where I can find this Debugging part in Preferences. Is that on the HACS or on the Companion App? 

Please guide me.

**Comment by zacwest** [comment]
Home Assistant > Preferences… either under Event Log directly or under Debugging if you're on 2021.5.

**Comment by Wolk9** [comment]
found it! 

It says:

{
  "error" : "unmappableValue"
}

**Comment by Wolk9** [comment]
And?

**Comment by Wolk9** [comment]
> Home Assistant > Preferences… either under Event Log directly or under Debugging if you're on 2021.5.

Hi @zacwest, Can you elaborate on this? I'm kinda stuck here... :-)

**Comment by arjenfvellinga** [comment]
Could it be you have more user accounts on you mac and installed the companion app on each account?

**Comment by Wolk9** [comment]
> Could it be you have more user accounts on you mac and installed the companion app on each account?

Nope. This is not the case as it runs on my iMac with only one userAccount on it: mine.

**Comment by gomanuel3124** [comment]
[](https://books.apple.com/tw/book/homepod-%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8A/id1485307823?l=en)

**Comment by Wolk9** [comment]
Has there been any attention to this bug? Or are there people with a possible troubleshoot path? I'm a bit puzzled here....

**Comment by zacwest** [comment]
Can you describe your HA setup? Do you have a reverse proxy in front of the server, use cloud, etc.

**Comment by bgoncal** [comment]
Is this still an issue with latest versions of app and core? Feel free to reopen if needed
