### ISSUE TITLE
Notifications on apple watch do not show the whole notifcation 

### ISSUE THREAD

**Issue by Final-Hawk** [home-assistant/iOS#1612]
**iOS device model, version and app version**

Model Name: 
    iPhone 7, Apple Watch series 3.

Software Version: 
   Both on latest OS (14.5)

App version: 
   beta app version 2021.5 (2021.134)

**Home Assistant Core Version**
core-2021.4.6

**Describe the bug**
When sending an actionable notification to an apple watch the text is limited to 1 line. After that it says "..."
**To Reproduce**
Create an actionable notifficaiton, example:
```service: notify.mobile_app_zzz
data:
  message: This is a very good test
  title: Testing
  data:
    actions:
      - action: ALARM
        title: Alarm
```
When the notification is sent to the watch it displays as "this is a very goo..." 
**Expected behavior**
To show the whole notification

**Screenshots**
![image](https://user-images.githubusercontent.com/63589370/116798308-8d760000-ab31-11eb-9e6e-206203d95bcf.png)

**Additional context**
Another user on reddit commented they have the same issue, i believe its @Shponzo since he also mentioned me in an issue about the actions not working.
Post here https://www.reddit.com/r/homeassistant/comments/n09h6l/actionable_notifications_doesnt_work_with_apple/

**Comment by zacwest** [comment]
Thanks. Actions not firing events on watch is being tracked in #1604.

**Comment by Final-Hawk** [comment]
That was quick, Great job!
