### ISSUE TITLE
UI shows red bars and missing components

### ISSUE THREAD

**Issue by IgnacioHR** [home-assistant/iOS#1626]
The problem appears only in the OSX companion app. NOT in safari.

**Device model, version and app version**

Model Name: MacBook Pro (15 inches, 2019)
macOS Version: Big Sur 11.3
App Version: 2021.4.1 (221.115)
Safari Version: Versión 14.1 (16611.1.21.161.3)

**Home Assistant Core Version**
Home Assistant Companion
2021.4.1 (221.115)

**Describe the bug**
When moving from one view to another, vertical red bars shows up and lovelace panels are not visible. When the mouse moves, the panels might appear again.

**To Reproduce**
Open Home Assistant Companion app and use it. I updated the OS-X version a few days ago.

**Expected behavior**
No issues and smooth transition between pages

**Screenshots**
Short video stored and attached

https://user-images.githubusercontent.com/16385090/117348270-4cbc1500-aeaa-11eb-8c81-05898acfda91.mov

**Additional context**

**Comment by bgoncal** [comment]
Is this still an issue in 2024? Let me know and I will reopen it
