### ISSUE TITLE
MacOS Companion app and sensor.frontmost_app

### ISSUE THREAD

**Issue by SdeGeata** [home-assistant/iOS#1628]
Hello all!

   So I have been making goos use of the Macbook sensors that are now available to Home Assistant via the companion app. The "sensor.frontmost_app" is a good start, though it would be handy if one could detect if a specific URL active in an app like Safari - Netflix for example.

   Hope that can be implemented in a future update.

**Comment by zacwest** [comment]
#1777 feels like it would address this.
