### ISSUE TITLE
Ios app doesn't handle internal HTTPS connection with ip address due to certificate

### ISSUE THREAD

**Issue by ddeconin-gh** [home-assistant/iOS#1634]
**iOS device model, version and app version**

Model Name: 
Software Version: 2021.4.1
App version: 2021.115

**Home Assistant Core Version**

 2021.5.1

**Describe the bug**
my ha instance has an internal URL of
https://192.168.1.97:8123
and external URL of
https://myexternalha.duckdns.org:8123
When I try to enter the internal URL I get error 'The Certificate for this server is invalid'. 
I can not use the external URL, since my router doesn't loopback the URL.
I tried using an internal DNS (dnsmasq add-on) but my iphone (corporate) does DNS over HTTPS so it doesn't resolve the HTTPS call locally either.
**To Reproduce**
set up a HA instance with duckdns and enable a certificate on it.
try to configure the internal URL as the IP address of the HA host
**Expected behavior**
app shows a warning that there is an issue with the certificate of the internal URL, but still allows the access.
(when I use the chrome app on my iphone, then this is the behavior I get).
**Screenshots**
![IMG_1628](https://user-images.githubusercontent.com/81985184/117680065-1d125300-b1b1-11eb-8ced-845b71a0cc7f.PNG)

**Additional context**

**Comment by zacwest** [comment]
Allowing the app to use insecure SSL connections (where the hostname and certificate do not match, like above) are logistically difficult and downright impossible in some places -- especially on the watch, where we need to use a background URLSession which doesn't play nicely with this. Please look at the [networking documentation](https://companion.home-assistant.io/docs/troubleshooting/networking) for alternate solutions.

**Comment by Mariusthvdb** [comment]
please allow me to have a followup question here, since after adding an internal address in the app (which works fine on my desktop ea) I see this:

![20210717_083935000_iOS](https://user-images.githubusercontent.com/33354141/126032023-0e2bac75-f94c-409a-915a-18a3bce78ece.png)

reading the link you provided above on this subject:
https://companion.home-assistant.io/docs/troubleshooting/networking/#setting-up-the-ios-app

does this in fact say we should NOT enter an internal url if duckdns is configured?

(I sometimes have to use the local address, because of an Ip ban, or Internet being down, thus prefer having local access at all times.....)

**Comment by zacwest** [comment]
You want to do the split horizon DNS choice with your external URL, that will make it work both internal and external.

**Comment by Mariusthvdb** [comment]
thanks, I will try... after installing Adguard though the https://companion.home-assistant.io/docs/troubleshooting/networking/#split-brain-dns talks about 
> DNS settings, then scroll down to the bottom where you have a box titled: DNS rewrites Here you click Add DNS rewrite

while in the newly installed add-on, that box isnt available. We can set allowed clients:

<img width="935" alt="Schermafbeelding 2021-07-17 om 23 29 18" src="https://user-images.githubusercontent.com/33354141/126049757-edbd02a7-c6c6-4008-a7c3-a43e1ebf6c35.png">

would that be an updated setting of the same?

**Comment by ddeconin-gh** [comment]
I use NGinx in combination with duckdns.
If configured correctly, you can use duckdns https connection for external and let NGinx translate it to internal http so that you can use http connection with IP address on internal network.

**Comment by ddeconin-gh** [comment]
This is how to do it:
https://kleypot.com/home-assistant-nginx-unencrypted-local-traffic/

**Comment by Mariusthvdb** [comment]
Thanks, almost there. 1 issue/question:

I have 3 instances all using the same domain on duckdns but using another port forward in my router

So, I guess I can not simply use duckdns in the Nginx setting?

If this is beyond the scope of this issue we might take it elsewhere. It is however related to how we need to configure the app for more than 1 instance...
