### ISSUE TITLE
[FR] Call detection iPhone

### ISSUE THREAD

**Issue by E020** [home-assistant/iOS#1645]
**Is your feature request related to a problem? Please describe.**
-

**Describe the solution you'd like**
I would like to be able to mute (or lower the volume) on my media-player if I receive a call on my iPhone (with HA app installed). I do have an iPhone sensor in HA, but call detection is not (yet) possible.

**Additional context**
-

**Comment by TomBrien** [comment]
This is a duplicate of #498. Sadly Apple do not make it possible for us to read the call status.

**Comment by E020** [comment]
Thanks Tom for clarifying. Sorry for the duplicated entry.

**Comment by TomBrien** [comment]
No worries at all. It's a real shame this isn't possible at the moment.
