### ISSUE TITLE
Use sound already in the iOS devices or add Generic alert sound

### ISSUE THREAD

**Issue by hmakmur** [home-assistant/iOS#1647]
**Is your feature request related to a problem? Please describe.**
The current list of [Pre-installed notification sounds ](https://companion.home-assistant.io/docs/notifications/notification-sounds)will never be complete because everyone has different need. The preinstalled sound is too specific. I know  we can add whatever sound we like but most people will not do it.

**Describe the solution you'd like**
Every iOS/Android phones have lots of built in alert sound already. Can we use and play this sound in homeassistant app? If there is no way to use built-in alert sound, we can add some _Generic_ sounds  in the preinstalled sound?

**Additional context**

**Comment by SeanPM5** [comment]
This is already supported in the iOS app.

If you go to App Configuration -> Notifications -> Sounds there is a tab at the top called "System" and then a button for "Import system sounds" which can import all the system sound effects. (There won't be any sfx listed there by default until you import them first).

![image](https://i.imgur.com/Nr0xjHO.jpg)
![image](https://i.imgur.com/IqNaHuD.jpg)
![image](https://i.imgur.com/PByax3x.png)
