### ISSUE TITLE
Support TLS 1.3 protocol

### ISSUE THREAD

**Issue by avee87** [home-assistant/iOS#1648]
I'm using Cloudflare to access my HA and app stops connecting when I enable TLS 1.3 enforcement. Apparently, I'm not the only one seeing this: https://community.home-assistant.io/t/unable-to-connect-to-home-assistant-from-ios-through-proxy-even-after-trying-all-troubleshooting-from-similar-posts/211061

As far as I know, modern versions of iOS do have TLS 1.3 support. Would it be possible to enable it for the HA app?

**Comment by zacwest** [comment]
As far as I can tell, TLS 1.3 should work out of the box, but it adds [some certificate requirements](https://stackoverflow.com/questions/58011737/ios-13-tls-issue). Can you share the hostname you are trying to connect to, or a dump of the certificate information?

**Comment by avee87** [comment]
In fact, it does seem to connect and even go through the login flow. However, when it tries to load the actual UI it throws "Cannot connect to HA" error.

> TLS server certificates must have a validity period of 825 days or fewer

This may actually be relevant as I use 10-year Cloudflare certificates... Will try with 2-year ones

**Comment by avee87** [comment]
I just tested and looks like it's not just iOS app. Same happens is Safari so must be something about my setup.
