### ISSUE TITLE
Support iOS 15

### ISSUE THREAD

**Issue by nickroberts** [home-assistant/iOS#1655]
**iOS device model, version and app version**
Model Name: iPhone 11 Pro Max
Software Version: 15.0
App version: 2021.6 (2021.158)

**Home Assistant Core Version**
2021.6.3

**Describe the bug**
When using the iOS 15.0 Developer Beta, the HA app does not connect to the HA server. The "Connection Lost, reconnecting" keeps flashing, as does the settings icon in the bottom right corner.

Eventually it all stops, and just the "Reload UI" button is shown, but tapping on it does nothing. Once this happens, you can swipe open the menu. It looks like some of the items might work, but I'm not really sure.

This is also apparent in iOS Safari, as well, so it is not just related to the app.

I have also installed the beta version, from Test Flight, but it looks like it is the exact same version (2021.158).

**To Reproduce**
* Install the iOS 15.0 developer beta
* Open the HA app

**Expected behavior**
It should show the dashboard.

I know it was just released as a developer beta, but I wanted to make sure this is tracked.

**Comment by nickroberts** [comment]
Just finished installing the latest version of macOS Monterey, and the desktop version of Safari does the same thing. It looks like something to do with the web socket connection. I will try to add more info.

**Comment by TomBrien** [comment]
Probably worth flagging this over on home-assistant/frontend

**Comment by zacwest** [comment]
Going to prefer the frontend ticket above since this is outside the app's control.
