### ISSUE TITLE
[iOS 15] Add support for new delegate WKUIDelegate decideMediaCapturePermissionFor 

### ISSUE THREAD

**Issue by nanosonde** [home-assistant/iOS#1671]
**Feature request / problem description**
Every call to `getUserMedia()` from within a WKWebView instance will lead to a new permission popup requiring the user to allow/deny access to the camera and/or microphone.  This is quite annoying from a user perspective.

Example use-case: I use an audio/video capable [Home Assistant card](https://github.com/tommyjlong/doorvivint-card) to have an audio/video connection to my doorbell within HA lovelace UI.

**Describe the solution you'd like**
Implement the new delegate `WKUIDelegate decideMediaCapturePermissionFor` to handle` getUserMedia()` media capture permission requests so that the user does not get a permission prompt for camera/microphone with **every call** to `getUserMedia()` when loading or reloading a webpage from within an existing instance of WKWebView.

**Additional context**
1. Original bug report for iOS 14.3: https://bugs.webkit.org/show_bug.cgi?id=220416
2. Another related forum topic: https://developer.apple.com/forums/thread/669011
3. Presentation of the new delegate on WWDC 2021 at timestamp 14:40: https://developer.apple.com/videos/play/wwdc2021/10032/ 
4. A clarification about the new delegate in the Apple forum: https://developer.apple.com/forums/thread/682293
5. ` getUserMedia()`: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia
6. Somehow related issue: https://github.com/home-assistant/iOS/issues/1319

**Comment by zacwest** [comment]
Looks like this is declared as being supported back to iOS 14.5, but requires Xcode 13 to use it.

**Comment by zacwest** [comment]
These delegate methods are all over the place - some are `async` and some pass in a block for a decision handler. Probably best to wait until later in the Xcode 13 beta period before playing with it.

**Comment by idoodler** [comment]
I tried to implement it. Now the prompts are gone, but I don't get the orange recording indicator of iOS and I don't hear anything:/

**Comment by nanosonde** [comment]
> 
> 
> I tried to implement it. Now the prompts are gone, but I don't get the orange recording indicator of iOS and I don't hear anything:/

What exactly have you tested where you do not hear anything?

**Comment by zacwest** [comment]
It looks like the only API they added for this in the iOS 15 release is:

```objective-c
- (void)webView:(WKWebView *)webView
requestMediaCapturePermissionForOrigin:(WKSecurityOrigin *)origin
initiatedByFrame:(WKFrameInfo *)frame
type:(WKMediaCaptureType)type
decisionHandler:(void (^)(WKPermissionDecision decision))decisionHandler;
```

which is documented as:
>  If not implemented, the result is the same as calling the decisionHandler with WKPermissionDecisionPrompt.

This may behave as you'd like without any app-level changes.

**Comment by zacwest** [comment]
Oh I see, you'd like the app to always say yes so it doesn't always prompt. That also seems doable, assuming it is prompting correctly.
