### ISSUE TITLE
Problem Building HomeAssistant with Lottie on M1 Mac

### ISSUE THREAD

**Issue by Wildchild9** [home-assistant/iOS#1681]
I have cloned this repo and am trying to get it up and running for a debug build on the simulator currently. I am using an M1 Mac mini and I am on macOS 11.4. Also, my Xcode version is 12.5. Here are the steps I took to build the open the project before I tried to build it.

```bash
git clone https://github.com/home-assistant/iOS.git
cd iOS
```
After this, I deleted the `Gemfile.lock` file as I was getting the error "google-api-client-0.38.0 requires ruby version ~> 2.4, which is incompatible with the current version, ruby 3.0.1p64" when running the next step of the setup process (`bundle install`). Then I proceeded with the following commands:

```bash
bundle install
bundle exec pod install --repo-update
open HomeAssistant.xcworkspace
```

Once Xcode opened, I selected the `App-Debug` scheme and chose the iPhone 12 simulator, then I tried to run the application. This build unfortunately fails with the Swift compiler error "Could not find module 'Lottie' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator" and I have not been able to remedy this. 

Any help to get this up and working would be appreciated. Thanks

**Comment by zacwest** [comment]
You may be the first person to attempt to build on an Apple Silicon machine, so I'm guessing that's the issue here. It looks like Lottie's trying to build using x86_64 instead of arm64, but I'm not sure why that would be. Just to double check - you haven't launched Xcode in any kind of Rosetta mode, right?

Are there any underlying errors elsewhere in the build step? Can you copy/paste the full build command and output from the build progress in the Navigator > Report Navigator > Build.

**Comment by Wildchild9** [comment]
That is correct @zacwest, I didn't launch it in any kind of Rosetta mode. And I just exported and attached the failed build report. Let me know if there is any other information that would be helpful.
[Build App-Debug_2021-06-21T12-11-56.txt](https://github.com/home-assistant/iOS/files/6688423/Build.App-Debug_2021-06-21T12-11-56.txt)

**Comment by zacwest** [comment]
Your log there definitely looks like it's trying to compile for x86_64, but almost certainly debug is building only the active arch. You can test this theory by commenting out `ONLY_ACTIVE_ARCH = YES` in `HomeAssistant.debug.xcconfig`. However, I'm not sure why it's doing the wrong architecture here.

One other thing you can try is build with entirely-source pods -- run `XCODE_BETA=true bundle exec pod install` -- the deps it changes aren't actually Xcode 13 specific, but all of them are not precompiled.

**Comment by Wildchild9** [comment]
I tried both of those things and unfortunately neither of them worked. Commenting out `ONLY_ACTIVE_ARCH = YES` in `HomeAssistant.debug.xcconfig` introduced a whole new suite of errors. 
[Build App-Debug_2021-07-23T12-37-28.txt](https://github.com/home-assistant/iOS/files/6870108/Build.App-Debug_2021-07-23T12-37-28.txt)

Trying to run `XCODE_BETA=true bundle exec pod install` during the setup phase instead of `bundle exec pod install --repo-update` also did not work and just ended up emitting the same error about Lottie.

Trying to run `XCODE_BETA=true bundle exec pod install` during the setup phase instead of `bundle exec pod install --repo-update` also did not work and just ended up emitting the same error about Lottie.

**Comment by zacwest** [comment]
Probably the easiest way to get this working is to run the rosetta version of the simulator. I'm not sure why things aren't working as-is, but it may help to add `ARCHS[sdk=iphonesimulator*] = x86_64` to the xcconfig and in the Podfile where it sets per-pod build config settings.

**Comment by zacwest** [comment]
Hmm, I've had some trouble with that one too. For the moment you can comment it out in the Podfile (it's used to grab .json files, not code, so it will still run), I need to switch that to a subrepo or a script which pulls in those shared test cases.

**Comment by zacwest** [comment]
`aps-environment` is the APNS environment key. This should be set up by default in provisioning profiles from the automatic provisioning. If you're trying to build to a device, code signing is required; have you set up an account with developer.apple.com? Did you override the team information in the `.xcconfig` file as the README states?

**Comment by orcema** [comment]
I followed the advised route and put "DEVELOPMENT_TEAM" and the "BUNDLE_ID_PREFIX"  in a new config file "HomeAssistant.overrides.xcconfig"

<img width="610" alt="Screenshot 2021-10-16 at 06 42 13" src="https://user-images.githubusercontent.com/12600222/137574104-85311cd0-6ab4-483a-afbf-1a81ae8c55d4.png">

This time I didn't change anything in the "HomeAssistant.xcconfig"

<img width="894" alt="Screenshot 2021-10-16 at 06 41 53" src="https://user-images.githubusercontent.com/12600222/137574121-4c073bdc-2cef-4c43-a284-9d4bda6514d0.png">

ran the installation with success, switched sheme to app-debug

<img width="595" alt="Screenshot 2021-10-16 at 06 49 11" src="https://user-images.githubusercontent.com/12600222/137574153-c425861a-96bc-4ab0-8aa0-e4d637ddd2bf.png">

then i ran the build and ended up with the same result as previously editing directly the "HomeAssistant.xcconfig", e.g.

<img width="259" alt="Screenshot 2021-10-16 at 06 32 29" src="https://user-images.githubusercontent.com/12600222/137574191-742d1e6a-371a-4a88-a471-39727afbf1ac.png">

<img width="593" alt="Screenshot 2021-10-16 at 06 34 00" src="https://user-images.githubusercontent.com/12600222/137574200-ad9e7017-337f-464d-8c50-8caf7c7d7024.png">

I have to switch the provisioning profile in the build settings from "Local Developer" to "automatic". This works for targets "App" and "Extension-PushProvider" but not for "Watchapp".

<img width="552" alt="Screenshot 2021-10-16 at 06 57 12" src="https://user-images.githubusercontent.com/12600222/137574330-fe87553b-b042-47fc-bb8b-de24861569d6.png">

**Comment by orcema** [comment]
> i switched over to branch automatic provisioning but ended up with the same error as above when i removed the target Watchapp
> 
> <img alt="Screenshot 2021-10-16 at 07 54 46" width="1001" src="https://user-images.githubusercontent.com/12600222/137575641-c1e6e8f7-f706-4f57-be45-292115bd3f12.png">
> 
> and here the error logs: [Build App-Debug_2021-10-16T07-52-39.txt](https://github.com/home-assistant/iOS/files/7357041/Build.App-Debug_2021-10-16T07-52-39.txt)

This is the build result with the branch "automatic-provisioning" without deleting the target "WatchApp"

**Comment by zacwest** [comment]
Can you try cleaning in Xcode in Product > Clean Build Folder? This seems like it may be a stale build profile in the new build system. You may need to kill the Pods directory entirely from the earlier target deletion if it's confused.

**Comment by orcema** [comment]
I already did a "Clean Build Folder" and ran again the working installation procedure for the M1 Mac
https://github.com/home-assistant/iOS/issues/1681#issuecomment-944487536
but nothing changes, always the same issue...
😢

**Comment by zacwest** [comment]
It's erroring on the `[CP] Embed Pods Frameworks` script, saying its input file set (`InputFileList-36460EB356C0C600F45AD622-Pods-iOS-App-frameworks-Debug-input-files-4f6d0d76000313cd5d01fc2a2198a9b7-resolved.xcfilelist`) contains an element which chains back to it.

It looks like it's the `Unembed Lokalise for Catalyst` script in the build phase for the App target. If you remove this, does it work?

**Comment by orcema** [comment]
@zacwest I have a last issue concerning the push notifications. 
Despite having configured the Notification with a certificate

<img width="668" alt="Screenshot 2021-10-16 at 10 40 34" src="https://user-images.githubusercontent.com/12600222/137580839-1623fd94-3051-4d9e-9bb0-97ce0ef603ee.png">

i still get the build warnings "push provider is disabled".

<img width="521" alt="Screenshot 2021-10-16 at 10 36 52" src="https://user-images.githubusercontent.com/12600222/137580878-29b24f8b-9ddb-4b1f-83ee-1143e74a2ecc.png">

related log warnings:
[Build App-Debug_2021-10-16T10-32-47.txt](https://github.com/home-assistant/iOS/files/7357237/Build.App-Debug_2021-10-16T10-32-47.txt)

what do i have to do to enable push notifiations ?

**Comment by zacwest** [comment]
I've got an M1 now (hooray!) and everything seems peachy at this point.

**Comment by orcema** [comment]
> I've got an M1 now (hooray!) and everything seems peachy at this point.

did you have to reorder the build phase position too ?

**Comment by zacwest** [comment]
No
