### ISSUE TITLE
Locations keep going all over the place

### ISSUE THREAD

**Issue by FeikoJoosten** [home-assistant/iOS#1693]
**iOS device model, version and app version**

Model Name: iPhone X, iPhone 8
Software Version: iOS 14.7 beta, iOS 14.6
App version: 2021.6

**Home Assistant Core Version**

core-2021.6.6

**Describe the bug**
Since the latest update my location history for both phones are continuously switching between my home and entering a nearby zone. On version 2021.5 this worked flawlessly. (Precise location is enabled, as no settings have been changed between 2021.5 and 2021.6.

**To Reproduce**
Open the location history of a device tracker, notice it keeps going between zones, even though I'm not moving the phone at all.

**Expected behavior**
The gps should accurately point where it is.

**Screenshots**

![image](https://user-images.githubusercontent.com/10920052/123956296-d10eae00-d9aa-11eb-9f99-27623533d51c.png)
Notice the phone is continuously switching between zones.

![image](https://user-images.githubusercontent.com/10920052/123956505-0adfb480-d9ab-11eb-9e48-b1d85470fa1f.png)
Biggest zone is my home with a radius of 150m.

Smaller zone is "Jaap en Marrie" with a radius of 10m.

**Additional context**

Attached log files of the iPhone X: [2021-06-30T135558+0200_logs.zip](https://github.com/home-assistant/iOS/files/6740635/2021-06-30T135558%2B0200_logs.zip)
Last 4 location reports screenshots: [Location reports.zip](https://github.com/home-assistant/iOS/files/6740648/Location.reports.zip)

**Comment by zacwest** [comment]
If you want to help confirm it is the app update and not iOS 14.6, you can join the [TestFlight beta](https://home-assistant.io/ios/beta) and install 2021.5 which has about 38 days remaining before it expires. If this ceases happening, it should be easier to pin down.

**Comment by FeikoJoosten** [comment]
@zacwest I've been running 2021.5 for almost 3 hours now and it's reporting perfectly fine atm. On 2021.6 my phone would've reported roughly 10 times that I'd left home by now.

**Comment by zacwest** [comment]
The next release of 2021.7 will have some debug logging that will help, but I think I have an idea what may be causing it.

**Comment by FeikoJoosten** [comment]
Do you want me to try out the 2021.7 release? And provide the new logs?

**Comment by zacwest** [comment]
Not necessary yet until the next 2021.7 beta, which has more logging. You can upgrade if you'd like but it shouldn't fix anything or provide new insights yet.

**Comment by FeikoJoosten** [comment]
Alright, then I'll stay on .7 for now. Let me know if there's something I can do to help out.

**Comment by FeikoJoosten** [comment]
This had indeed been fixed. Thank you for the quick fix!
