### ISSUE TITLE
iOS app device tracker entity not recognizing geocoded location change

### ISSUE THREAD

**Issue by liquidbear99** [home-assistant/iOS#1705]
Model Name:  iPhone 12 Pro Max
Software Version: 14.6
App version: 2021.202

**Home Assistant Core Version**
<2021.7.1>

**The geolocation of my iPhone is not updating to the correct zone. The iPhone geocoded location entity does update correctly and often. However, the device tracker entity that tells what zone the iPhone is in is not updating with the geocoded location. For example, when I am outside of the "home" zone my geocoded location updates, but the device tracker entity still shows as home. Basically it thinks that everywhere is home. My wife's iPhone is not having this problem and I tried uninstalling and reinstalling the app on my iPhone.**

**Unknown**

**The device tracker entity should change when I leave "home".**

**Screenshots**

**Additional context**

**Comment by zacwest** [comment]
Does your person in HA have more than one device tracker? If so, try removing the others. If not, make sure you don't have more than one integration in the HA configuration's integration for mobile_app.

**Comment by liquidbear99** [comment]
the person only has one device tracker and I did have more than one integration configured in the HA mobile app configuration. After I deleted both from the HA instance, then deleted the app from my phone, then re-added the integration and app I only had one integration in the HA configuration's integration for mobile_app but the problem is persisting.

**Comment by liquidbear99** [comment]
That fixed it! I had two integrations configured for some reason! Thanks!
