### ISSUE TITLE
Virtual microphone not recognized as primary sound input device

### ISSUE THREAD

**Issue by simonszu** [home-assistant/iOS#1707]
**Device model, version and app version**

Model Name:  Mac Mini 2018
macOS Version: Big Sur 11.4
App Version: 2021.207
Safari Version: 14.1.1

**Home Assistant Core Version**
2021.7.0

**Describe the bug**
I am routing my physical microphone input via an app which provides a VST interface so that i can add a noise gate to the mic input. The app creates a virtual audio interface which is set as my main audio input interface in the system settings. Because of the architecture of the VST plugin the physical audio interface is always active, but the virtual one isn't. The app is assuming the physical audio interface as my primary one (although it isnt set as such in the system settings) and therefore is not able to distinguish between "microphone active" and "microphone not active" in its sensors. 

**To Reproduce**
Create a virtual audio interface with the physical interface as a source interface, e.g. with Rogue Amoeba's loopback. Set the virtual audio interface as your primary input in the system settings. The app will still select the hardware interface as the primary interface, showing it as always active (since loopback is constantly accessing it). 

**Expected behavior**
The virtual interface is properly selected in the app, and marked as active or inactive, depending on its state. 

**Screenshots**
![Screenshot 2021-07-13 at 11 36 14](https://user-images.githubusercontent.com/700707/125429286-8f4557de-670e-4db2-8f38-aba55c28b52b.png)

**Additional context**
Another solution would be a feature where you can select any hardware (cam, mic) in the app which should be monitored as primary, and let the sensor state switch on.

**Comment by zacwest** [comment]
The last few times I've seen this reported, I haven't been able to find an app which reproduces the issue. I believe it's related to some of the sandboxing the app opts into, but I'm not sure what causes some virtual devices to work and others not to.

Can you share what app you're using? If I can reproduce it, I can maybe figure out needs to be done (if we can do it without unsandboxing).

**Comment by simonszu** [comment]
Sure. I am using a combination of Loopback from Rogue Amoeba and OBS Studio. In Loopback i have created a first chain for stereo-izing the mic, since apparently it is only sending data on the left channel when captured raw, so the first device just sends the one input channel to both output channel. 
![Screenshot 2021-07-16 at 08 01 07](https://user-images.githubusercontent.com/700707/125899738-6b34988d-6e69-487c-9760-320d5bf03d62.png)
This output device is then added to OBS, where the RNNoise filter is applied. This filter is basically a neural network for removing background sound and the slight reverb each room has. 
The audio channel in OBS is now set with monitoring enabled 
![Screenshot 2021-07-16 at 08 03 47](https://user-images.githubusercontent.com/700707/125899981-40a683b9-14a0-4484-8862-3e00ecfa874b.png)

This makes OBS a valid input source in Loopback again, since it is an application which emits audio. So the second lane in loopback is just a virtual audio cable, like the famous Windows toolset, which maps OBS to a virtual sound card
![Screenshot 2021-07-16 at 08 05 17](https://user-images.githubusercontent.com/700707/125900106-7346afc0-1b1a-479a-aabd-1adff8f33c9c.png)

And the virtual audio device created by the second Loopback chain is then selected as the default audio input device in the system setting. I know it's a bit complicated, and i dont really like the architecture, to be honest, but i haven't found a more elegant (and free) solution yet. 

So i have to say: If you have a different idea of how i could apply the rnnoise filter (which is available as a VST plugin) to the mic input chain without creating a virtual sound card, and therefore working with the Home Assistant app as it is right now, i would see that as a reason to close this bug, at least for me.

**Comment by zacwest** [comment]
Thanks for the information. I also noticed while going through issues that the ticket #1354 has another example. I should be able to use both and the information there to look into this, but closing this one as a duplicate.
