### ISSUE TITLE
Landscape mode causes History to not display on iPad

### ISSUE THREAD

**Issue by hagak** [home-assistant/iOS#173]
Landscape mode causes History to not display on iPad it does appear fine in portrait mode on the iPad.  I have also noticed on the iPhone Xs that portrait mode or landscape mode history does not display.

**Comment by hagak** [comment]
I see this was labeled 1.5.x.  However this issue still exists in the 2.0 version.  Also note the History no longer displays in Portrait mode on the ipad.

**Comment by zacwest** [comment]
It's possible this may have been fixed along with Safe Area changes in 2020.1, please give it a try. I'm unable to reproduce an issue inn History on the iPad:

![IMG_6639](https://user-images.githubusercontent.com/74188/85215224-5f793a00-b32a-11ea-8bb0-158e67a350f3.png)
