### ISSUE TITLE
No notifications received if local push is disabled when connected trough Internal URL and SSID is set

### ISSUE THREAD

**Issue by mbo18** [home-assistant/iOS#1799]
**iOS device model, version and app version**

Model Name: iPhone Xs
Software Version: 14.6
App version: 2021.7 (2021.202)

**Home Assistant Core Version**

2021.7.3

**Describe the bug**
When connected to my Home SSID I do not receive notifications from HA when "Local push" notifications are disabled for the Internal URL

**To Reproduce**
Go to IOS companion app settings, 
clic on Home at the top, 
clic on the Internal URL, 
add SSID and disable "Local Push"

Go to HA, Developper tools, Service, and send a notification to the mobile phone when it's connected to the configured SSID (so using the Internal URL)

If I enable "Local push", notifications are correctly received.

**Expected behavior**
Notifications must be send trough the cloud if connected to the configured SSID and to HA using the Internal URL with "local push" notification disabled

**Screenshots**

**Additional context**

Firebase Cloud Messaging is enabled, no logs in HA

**Comment by sam-ward** [comment]
I have just hit what I believe is the same issue, but with a slightly different scenario.  In the HA Companion app settings, the Local push toggle was on, but I was not receiving notifications when connected to the wifi (but I could when on cellular).  When I toggled local push off, I started receiving notifications. And then when I toggled it on I still received notifications.

So it seems like after an app upgrade, despite the Local Push setting being on, its not registering properly till its toggled off and on again. Or maybe the app upgrade occurred on cellular so the initial run didn't have access to the local server to register properly (I am just theorizing here as I don't know when the app was upgraded and how/when it was first run after the upgrade).

Model Name: iPhone 8
Software Version: 14.6
App version: 2021.7 (2021.202)
Home Assistant 2021.7.3.

**Comment by mbo18** [comment]
Following your post, I tried again and toggled local push on and off several time, I quit and relaunch the app and it’s working now! Really strange

**Comment by e1miran** [comment]
Definitely a bug here. I wasn’t receiving local push notifications either until I did a series of combinations of enabling/disabling of local push and restarting the app a few times. Hopefully it sticks now.

**Comment by zacwest** [comment]
Local push is effectively a tiny app inside the iOS app that keeps a connection open to the HA server. As long as the connection is open, the HA server will send notifications through that mechanism and skip going to the cloud. What this means in practice is that, unless it's connected, it shouldn't interfere with notifications at all.

So there's a few possible things happening:
1. If notifications work either way (and it's just not coming in via local) you probably need to restart your phone. Apple's upgrade system in the App Store/TestFlight does not appear to reliably start the Local Push process after upgrades. I've filed this with them as FB9202862.
2. If notifications only work when not on the local network, and Local Push is running, this may be something we can figure out over logs. See below.
3. If notifications only work when not on the local network, and Local Push is _disabled_ but was recently enabled, there may be an issue with how the app disconnects from the server (or how the server notices a disconnect). This one is a little harder to test - but restarting the HA server should eliminate anything in this category, so if that is successful it may be an indication that this is happening.
4. If notifications only work when not on the local network, and Local Push has been disabled for some duration of time past an HA server restart, I'm not sure what's going on here. If this is the issue you're seeing, we may need to crank up some of the debug logging on the mobile_app side.

You can grab the push process's logs via App Configuration > Debugging, exporting the logs should produce a .zip which includes `HomeAssistant-Extensions-PushProvider.txt` which is the local push logs. The question here is: is it running, and what is it doing, when notifications are suppose to come in but do not?

You can increase the mobile_app logging in core by adding the following to your `configuration.yaml`:

```yaml
logger:
  logs:
    homeassistant.components.mobile_app: debug
```

**Comment by mbo18** [comment]
Find attached my logs.

I should have received a notification at 9h30 this morning. I did not received it so I played with the local push toggle.

[HomeAssistant-Extensions-PushProvider_2021-07-18_180148.txt](https://github.com/home-assistant/iOS/files/6836747/HomeAssistant-Extensions-PushProvider_2021-07-18_180148.txt)

**Comment by zacwest** [comment]
> Find attached my logs.
> 
> I should have received a notification at 9h30 this morning. I did not received it so I played with the local push toggle.
> 
> [HomeAssistant-Extensions-PushProvider_2021-07-18_180148.txt](https://github.com/home-assistant/iOS/files/6836747/HomeAssistant-Extensions-PushProvider_2021-07-18_180148.txt)

From the logs, it looks like the event was received by the app, but it couldn't figure out how to parse it, it seems. Can you share the details of the notification you tried to send? e.g. what the service call looks like.

**Comment by zacwest** [comment]
Oh no, I do see some kind of bug is happening in your case - it's subscribing to local push twice, and I think the second one (that is winning) is getting lost. Will need to spend some more time investigating how it could happen.

**Comment by mbo18** [comment]
> From the logs, it looks like the event was received by the app, but it couldn't figure out how to parse it, it seems. Can you share the details of the notification you tried to send? e.g. what the service call looks like.

```yaml
- service: notify.md
  data:
    title: "Alerte Index UV={{ states('sensor.albi_uv') }}"
    message: "Mettez de la crème solaire aujourd'hui !"
    data:
       url: "/lovelace/weather"
       group: "weather-notification"
``

**Comment by mbo18** [comment]
> Oh no, I do see some kind of bug is happening in your case - it's subscribing to local push twice, and I think the second one (that is winning) is getting lost. Will need to spend some more time investigating how it could happen.

What is strange is that I have disabled local push since the beginning. So it was disabled when the notification was sent (and not received)

**Comment by zacwest** [comment]
> > Oh no, I do see some kind of bug is happening in your case - it's subscribing to local push twice, and I think the second one (that is winning) is getting lost. Will need to spend some more time investigating how it could happen.
> 
> What is strange is that I have disabled local push since the beginning. So it was disabled when the notification was sent (and not received)

Could you send me the previous set of logs? I can see the mistake happening in the ones you attached, but I think it started in the previous days' logs.

I'm not sure why the Local Push extension was running if you had it disabled, though, but it was definitely running when you ran into this issue.

**Comment by mbo18** [comment]
> Could you send me the previous set of logs? I can see the mistake happening in the ones you attached, but I think it started in the previous day/rotation of logs.

[HomeAssistant-Extensions-PushProvider_2021-07-17_175014.txt](https://github.com/home-assistant/iOS/files/6836942/HomeAssistant-Extensions-PushProvider_2021-07-17_175014.txt)

**Comment by zacwest** [comment]
> > Could you send me the previous set of logs? I can see the mistake happening in the ones you attached, but I think it started in the previous day/rotation of logs.
> 
> [HomeAssistant-Extensions-PushProvider_2021-07-17_175014.txt](https://github.com/home-assistant/iOS/files/6836942/HomeAssistant-Extensions-PushProvider_2021-07-17_175014.txt)

Amazingly enough, the process that started at the beginning of this logs (on 2021-07-10) actually continues in-memory from `2021-07-11 11:34:13.737` (when it last ran) to `2021-07-17 17:50:14.338` (when it continued again) -- and whatever issue was happening was preserved from the 7/10 window.

If it's not too much trouble, can you send all of the logs for the PushProvider you can see? You can also upload 'em to me [via Dropbox](https://www.dropbox.com/request/CtVWqILBXZ41tmFSGK2y) if you wanna just drop a zip file.

**Comment by mbo18** [comment]
I've sent you the zip file from "Export log files". Hope this help :)

**Comment by zacwest** [comment]
I just pushed a new [TestFlight beta](https://home-assistant.io/ios/beta) which may fix this and also has more verbose logging around the potential problem areas. Please give it a try and let me know if you experience problems afterwards.

**Comment by mbo18** [comment]
Thank you. Just installed it, I will update this issue if I have this issue again

**Comment by badewanne1234** [comment]
I'm having a similar issue but the other way around.

**iOS device model, version and app version**

Model Name: iPhone 11
Software Version: 14.7.1
App version: 2021.8.3

**Home Assistant Core Version**

2021.8.3 (this also happened on 2021.7.x, I just upgraded to see if the issue persists)

**Describe the bug**

When connected to my Home SSID, I do recieve push notifications from HA in both cases: local push enabled and local push disabled.
However, I dont get any notifications as soon as I'm not connected to my WiFi / Home SSID. Prior to the introduction of Local Push functionality, external/cloud push notifications did work very well.
(FYI: Controlling HA from external / with no Wifi, works fine through DuckDNS)

**To Reproduce**
1) Disconnect from the Wifi
2) Go to HA, Developper tools, Service, and send a notification to the mobile phone when it's NOT connected the Wifi

**Expected behavior**
Notifications must be send trough the cloud when Local push is disabled. However, I'm not getting any notifications when not connected to WiFi / when external.
When I'm connected to WiFi and local push is disabled or enabled, I get push notificatiosn in both cases.

Happy to share logs if needed.

**Comment by zacwest** [comment]
> App version: 2021.8.3

This is more likely your core version. Please look in App Configuration > About, if you are on 2021.7 you should try manually upgrading to 2021.8 (the App Store is set to auto-upgrade folks slowly).

**Comment by badewanne1234** [comment]
> 
> 
> > App version: 2021.8.3
> 
> This is more likely your core version. Please look in App Configuration > About, if you are on 2021.7 you should try manually upgrading to 2021.8 (the App Store is set to auto-upgrade folks slowly).

Oh bugger, right, just corrected my post above - I was already on the newest version since I was following this issue hoping it would fix my issue too :)

**Comment by zacwest** [comment]
Do you have any errors in your HA logs when a notification is sent non-local?

**Comment by badewanne1234** [comment]
No errors or warnings in the logs. What I observed is also that in about 80% of the cases, I dont get the non-local push notifications, but in about 20% of the cases, I actually get it. This is pretty weird..

**Comment by badewanne1234** [comment]
Is there anything I can do from my side such as activate logs/debugging in either HA or companion App?

**Comment by zacwest** [comment]
You can turn up the mobile_log level to see every request it sends to Firebase:

```yaml
logger:
  logs:
    homeassistant.components.mobile_app: debug
```

**Comment by badewanne1234** [comment]
My HA crashed entirely, not sure if it was related to when I enabled the logger. ATM, I will wait with enabling the logger again. I started to figure out a pattern now though:

- When I'm booked into my Wifi: I receive notifications (local push)
- When I leave the house, I dont get push notifications for (kind of exactly) 1 hour
- When I left the house for 1 hour, I will get again push notifications (previous push notifications are not received)
- When I'm back home and booked into my Wifi, I instantly get local push notifications again.

Is there a timer somewhere in the app or HA to distinguish between local and external push notifications?

Thanks

**Comment by zacwest** [comment]
Ah, that is a good investigation, thanks for figuring this out. My hunch is the WebSocket connection is looking 'open' still from the server-side, so it's not switching over to remote notifications. This should be easy to mitigate by requiring the app to confirm all received local push notifications.

**Comment by badewanne1234** [comment]
Assuming this is something that needs to be re-coded, I cannot configure this, right?

**Comment by zacwest** [comment]
Correct.

**Comment by zacwest** [comment]
I believe this is resolved now. Please open a new ticket if you come across notification delivery issues.
