### ISSUE TITLE
iOS app crashes when Home Assistant OS still runs landing page

### ISSUE THREAD

**Issue by balloob** [home-assistant/iOS#1804]
**iOS device model, version and app version**

Model Name: 
Software Version: 
App version: 

**Home Assistant Core Version**

landing-page

**Describe the bug**

So @pvizeli ran into this issue when helping his brother. The app crashed. I have no stack trace.

When Home Assistant OS first boots up, it starts up a landing page container. This is a small container that shows a "Preparing Home Assistant, this can take up to 20 minutes" page. This page is already broadcasting mDNS such that Android and iOS can already find it. The page automatically refreshes when Home Assistant is up and guides them via onboarding.

The source code for this lives here https://github.com/home-assistant/landingpage

There is also a dev container to make it easier to test with iOS. I can't find it right now, @pvizeli can you comment with the command to run landing page?

I wonder if there is something that iOS fails to parse from the mDNS discovery. It lives https://github.com/home-assistant/landingpage/blob/main/mdns.go#L15-L25

**To Reproduce**

**Expected behavior**

It should show the landing page.

**Screenshots**

**Additional context**

**Comment by pvizeli** [comment]
You can't run that on an OSX, work only with Linux (real host network)

**Comment by zacwest** [comment]
Which app version? I _thought_ I worked around the potential parse issues in Apple's mDNS parsing with the crasher last year in #615 but there may be another. 

If you can reproduce it at all, grabbing crash logs from the device should be enough to at least see what is happening. In the system Settings app, under Privacy > Analytics > Analytics Data, there should be Home Assistant files. I may also be able to see these in Xcode if the device is opted into sharing with developers.

**Comment by zacwest** [comment]
I also have a linux box already running a bunch of docker containers so I can run something there if you can tell me what it is.

**Comment by pvizeli** [comment]
You can use these commands (need modification for your system) https://www.home-assistant.io/installation/generic-x86-64#platform-installation with the image `ghcr.io/home-assistant/qemux86-64-homeassistant:landingpage`

**Comment by pvizeli** [comment]
```
docker run --rm \
  --name homeassistant-landingpage \
  --privileged \
  --network=host \
  ghcr.io/home-assistant/qemux86-64-homeassistant:landingpage
```

that command should work on all system with amd64 I guess

**Comment by zacwest** [comment]
Running with that command, I can't reproduce the crash at all. Can you share what iOS version and app version the crash was occurring on?

**Comment by zacwest** [comment]
Feel free to reopen if you can attach a crash log but I'm unable to reproduce this.
