### ISSUE TITLE
Siri integration for adding items to shopping lists

### ISSUE THREAD

**Issue by liquidbear99** [home-assistant/iOS#1807]
Would be pretty neat to tell Siri to add things to my home assistant lists.

**Comment by zacwest** [comment]
#1741

You can achieve this right now using a Siri Shortcut that prompts for text and issues a service call with the text.

**Comment by liquidbear99** [comment]
Awesome! Thank you so much! Unfortunately, I'm having trouble creating the Siri Shortcut. Is there any possibility you could give a bit more instructions on how to make the Siri shortcut? I can add the service call but am having trouble extracting text from what I say. Ex. "tell home assistant to add eggs to shopping list" I would like it to grab "eggs" and add that to the list.

**Comment by zacwest** [comment]
I suggest posting on [the forums](https://community.home-assistant.io/c/mobile-apps/ios/41) for help putting together Shortcuts.
