### ISSUE TITLE
Use URL with basic auth enabled as external URL in iOS app

### ISSUE THREAD

**Issue by vistalba** [home-assistant/iOS#1812]
### The problem

To add an additional layer of security I want to use my RProxy in front of HA for remote access.

I've created two URLs for this case:

ha.internal.domain.com -> https://ha.internal.domain.com:8123 (this is configured as internal URL in iOS app and works fine!)
ha.dmz.domain.com -> https://ha.dmz.domain.com 

For the domain `ha.dmz.domain.com` I've enabled basic auth. When I use `https://user:password@ha.dmz.domain.com` in Safari/Chrome on my iPhone I can reach Homeassistant WebUI.

(Of corse I had to add `trusted_proxies` on configuration.yaml to get this work!)

When I use this URL  (`https://user:password@ha.dmz.domain.com`) as external URL in iOS app it doesn't work :(
I also tried to use the URL `ha.dmz.domain.com` without user:password but this doesn't work too.

Is there any idea how I can do this?

### What is version of Home Assistant Core has the issue?

core-2021.7.4

### What was the last working version of Home Assistant Core?

-

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

iOS

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/ios/

### Example YAML snippet

```yaml
-
```

### Anything in the logs that might be useful for us?

```txt
No -> As it works from Browser it looks like a Problem with the iOS App.
```

**Comment by vistalba** [comment]
Did some more troubleshooting. I'm not an expert on that but for me it looks like there is a problem as some requests has header:

`authorization: Basic aGe....` while others have `authorization: Bearer ey3...`. 

When using Chrome on Windows I can load start page `/lovelace` without issues. But I can't load any history for example. 

May this "stacked" auth methods does not work at all?

**Comment by zacwest** [comment]
Unfortunately it is not. The HTTP spec says you can include multiple in the header but nothing supports it in my testing. See #193.
