### ISSUE TITLE
Images can't close when opening from mobile ios app notifications

### ISSUE THREAD

**Issue by tdebans** [home-assistant/iOS#1827]
**iOS device model, version and app version**
Model Name: iPhone 11 Pro
Software Version: 14.7.1
App version: 2021.8

**Home Assistant Core Version**
2021.8.4

**Describe the bug**
Not sure if this is recent.
When receiving a notification with action buttons
The url in te action is a jpg image hosted in HA.
The image will open in the HA ios app. not in safari or chrome
Then the image can not close. there is no close button.
Even when closing the app the image starts again.
 to go back to te frontpage, close app, restart app, settings -> remember last page -> off. close app, restart app.

**To Reproduce**
for example:
https://community.home-assistant.io/t/frigate-mobile-app-notifications/311091
notifications with image links from this blueprint.

**Expected behavior**
-option to close the image. like when opening a mp4 video link.
-or a back button

**Screenshots**

**Additional context**

**Comment by zacwest** [comment]
This is not new, but it is also unintended use of the url parameter to open non-frontend pages, since frontend pages have navigation UI. Will need to decide how to handle this.

**Comment by jschwalbe** [comment]
I was stuck in this for awhile, and actually came to open the same issue. If someone finds himself unable to navigate away from said image (even after force quitting HA app), you can send a notification such as this:

```
service: notify.mobile_app_iphone
data:
  data:
    url: https://HA-SERVER:8123/lovelace
  message: msg
```
Tap that, and lovelace will load back up.

**Comment by Nesvet** [comment]
Thanks, @UltraSub 

The issue is still actual 🙄

**Comment by zacwest** [comment]
Please try out the latest [TestFlight beta](https://www.home-assistant.io/ios/beta) which should resolve this issue.

**Comment by RosTeHeA** [comment]
Latest TestFlight build didn’t fix it for me—even after updating, I open the app, and still have the old static screenshot of my front door. I will try fully resetting the HA app, re-trigger a notification, and see if the issue persists.

**Comment by RosTeHeA** [comment]
Looks like the update did fix it. (But it requires resetting the HA app if you’re stuck on an image like I was).

**Comment by bgoncal** [comment]
Is this still an issue in 2024? Let me know and I will reopen it
