### ISSUE TITLE
Unable to reorder / remove items from the side bar.

### ISSUE THREAD

**Issue by jamespreedy** [home-assistant/iOS#1830]
I'm running app version 2021.8 and HASS 2021.8.8.
I'm unable to reorder / remove items from the side bar.

I'm able to see the side bar within the iOS app, and I'm able to press and hold on the top banner.
The haptic feedback triggers and a small blue circle appears briefly to acknowledge the action.

However, the sidebar never goes into "edit mode" - I never see the option to delete or re-order items in the sidebar.
I've reset the app, deleted / reinstalled, and reset the frontend cache - no change.

Please let me know if there's any additional information I can provide to help.
Thanks in advance.

**Comment by TomBrien** [comment]
I can't reproduce here. I can tap and hold "Home Assistant" and upon  releasing the sidebar is in edit mode. What iOS version are you running?

**Comment by jamespreedy** [comment]
I'm running iOS 14.7.1 on an iPhone 12 Pro.
Are there any logs I could get for you to help?

**Comment by TomBrien** [comment]
I'm not sure which logs would be most appropriate. Are you running any custom themes and do you see the same thing in Safari on iOS. Also, do you have any accessibility features enabled in iOS?

**Comment by jamespreedy** [comment]
No custom themes and Safari on iOS is fine. No accessibility features enabled.
I believe it's now fixed. When in my user profile section on the iOS app, I noticed the "Change the order and hide items from the sidebar option" which I didn't know existed. Tapping Edit immediately allowed me to reorder and make changes. Since then the press and hold has started to work just fine.

Thanks for your help!
