### ISSUE TITLE
Internal URL not working in iOS 15

### ISSUE THREAD

**Issue by Tomerello** [home-assistant/iOS#1853]
**iOS device model, version and app version**

Model Name: iPhone 12 Pro
Software Version: iOS 15
App version: 2021.10 (2021.230)

**Home Assistant Core Version**
2021.9.7

**Describe the bug**
The app can no longer detect which SSID i'm connected to so the internal URL is never used.
Also when i press the plus sign to add a new SSID the currect SSID is not detected. Started in iOS15 

**To Reproduce**
iOS 15 and try to use the function to use the internal URL when connected to specific SSID.

**Expected behavior**
The Internal URL should be used when connected to my home SSID

**Comment by zacwest** [comment]
What is the value for Location permission in the system Settings app > Home Assistant?

**Comment by Tomerello** [comment]
The location permission is always allow for the app.

**Comment by zacwest** [comment]
In Location permission, do you have it set to enable "precise location"?

**Comment by Tomerello** [comment]
Yes I have

**Comment by marcgarciamarti** [comment]
Same situation over here. Please @Tomerello could you update this issue if you ever manage to fix the problem?

**Comment by PRGeno** [comment]
Same issues here, but with IOS 14.8

**Comment by Tomerello** [comment]
Internal URL works in the latest version of HA and IOS
