### ISSUE TITLE
GPS coordinates still being sent to the Device Tracker with all Location update sources disabled

### ISSUE THREAD

**Issue by jnimmo** [home-assistant/iOS#1866]
**iOS device model, version and app version**

Model Name: iPhone 12
Software Version: 14.8
App version: 2021.8 (2021.216)

**Home Assistant Core Version**
2021.9.7

**Describe the bug**
GPS coordinates are still being sent to Home Assistant device tracker even with all location update sources disabled.

I have full accuracy location enabled so that the application is able to determine when to use the internal/external URLs, however I expect with all all of the location update sources disabled, device GPS coordinates should not be sent.

The Device Tracker state attributes include:
`
source_type: gps
battery_level: 70
latitude: <removed>
longitude: <removed>
gps_accuracy: 65
altitude: <removed>
friendly_name: James' iPhone
`

While it is possible to disable this at the Device Tracker level; for privacy the control should be in the hands of the device owner rather than installation owner.

**To Reproduce**
Location > Location Permission: Always
Location > Location Accuracy: Full
Location > Background Refresh: Enabled
Location > Zone enter exit: Off
Location > Background fetch: Off
Location > Significant location change: Off
Location > Push notification request: Off

Sensors > Periodic Update: Off
Sensors > Motion Permission: Enabled
Sensors > (All other sensors) Off

Review the Device Tracker entity in developer tools, GPS coordinates will be current.

**Expected behavior**
GPS co-ordinates should not be sent to device_tracker when all location update sources are disabled.

**Screenshots**

**Additional context**

**Comment by zacwest** [comment]
In Location > Location History, can you share the source (the subtext in the list) of the location updates which are happening here?

It might be worthwhile to have an app-wide "use location" toggle that just turns off location updates regardless of source.

**Comment by jnimmo** [comment]
Good thinking. Update source is Manual, on further investigation it looks like it might be when refreshing the page in Home Assistant (dragging down from the top of the screen to refresh)

**Comment by zacwest** [comment]
Yup, that's exactly what it is doing. "Manual" doesn't have a setting guarding it, so it's still getting through.

**Comment by jnimmo** [comment]
iOS app now has a 'None' setting for Location Data, I haven't tested it yet but presume it works so I'll close this issue!
