### ISSUE TITLE
Notifications don't work when switching networks, problems with transition between local and public network

### ISSUE THREAD

**Issue by fi-sch** [home-assistant/iOS#1868]
**iOS device model, version and app version**
Model Name:  iPhone 12 mini
Software Version: iOS 15.0
App Version: 2021.8

This issue seems to be present for macOS as well. Therefore I am not sure if that is strictly caused Home Assistant Companion app.

**Home Assistant Core Version**
HA Version: core-2021.8.8

**Describe the bug**
I have this automation that was working for me for a long long time. Since some time (I can't remember exactly since when...) I started to have problems with notifications it should send. I just stopped getting those.
At first, I assumed that it may be related to the local push changes, however after trying to debug it last weekend I can't see any relation. I also seem to get all other notifications (from other automations), just this particular one is playing tricks on me.

Said automation is working properly, all of it's steps are executing properly, except notify service action. If I run this service via Developer Tools (copy&paste), it works as it should. It just seem to not work when executed from this particular automation.

**Expected behavior**
I should get notification each time the automation is triggered.

**Screenshots**
Here is example automation run. I have selected problematic action for your reference.
<img width="856" alt="Zrzut ekranu 2021-09-29 o 15 51 18" src="https://user-images.githubusercontent.com/59969726/135282238-a1d92f60-82d5-46f4-8698-62c3385c0219.png">

One remark. Since trying o debug this automation I have used 'notify.mobile_app_myname' service. For debugging purpose I changed it to notification group 'notify.filip'. Both seem to not work for me in this automation.

There are no errors related to this issue in HA logs. I have spent many time on debugging this with no success. I also did try to reset Push ID multiple times.

**Comment by TomBrien** [comment]
Can you check if the notification is listed in Notification Center?

**Comment by fi-sch** [comment]
No, it is not. I have checked it many times. I literally spend hours on this issue.

**Comment by zacwest** [comment]
This sounds like it may be related to disconnecting from the server. In 2021.10 (iOS & core), local push notifications will be rerouted to APNS-based notifications if the app doesn't actively confirm it has received the notification, which should eliminate this transition period where the WebSocket for Local Push doesn't look disconnected from core's perspective, but is from the app's perspective.

**Comment by fi-sch** [comment]
I'm glad to hear that. So I will keep you updated once those are out.

But for now. Should disabling the Local Push feature within app's settings mitigate this issue?

**Comment by zacwest** [comment]
Yes. If Local Push is related as hypothesized, disabling it should entirely prevent the problem.

**Comment by fi-sch** [comment]
Ok, do I checked wether disabling Local Push helps. It turns out that it doesn't.

1. Turned off Local Push in app settings.
2. Waited over 12 hours – I did not have possibility to check it earlier anyways.
3. On WiFi I could get the notifications. But once I turned it off, I could not get them any more. Until I turned back on the WiFi.

So it seems to me as this issue is not related to Local Push. Am I right?

**Comment by zacwest** [comment]
Yeah that does seem to indicate it's perhaps on the Apple Push side of things. Do you activate a VPN on cellular or anything which may be preventing that connection? Do other apps' notifications work?

One thing worth doing is, if you have a Mac, plugging the phone into it and launch Console.app and "start screaming" the phone's logs. It will likely include "apn" logs which can help pinpoint.

**Comment by fi-sch** [comment]
I use VPN from time to time, and also wondered if that may be the case. So for all of the tests that I've done (described in this thread), I completely turned off the VPN on my iPhone. Therefore it shouldn't be the VPN (or any other tool's) fault.

Ok. I will check with the console on my mac later, probably around 5-6h from now. I will definitely let you know about the results.

**Comment by fi-sch** [comment]
Quick update. I just wanted to pinpoint this issue and started by simple tests (turning WiFi on and off), and it works flawlessly...
I will check a little bit later again, but this is even more confusing for me right now.
