### ISSUE TITLE
Significant background battery use (10+ hours a day) with iOS 15

### ISSUE THREAD

**Issue by deviantintegral** [home-assistant/iOS#1900]
**iOS device model, version and app version**

Model Name: iPhone 12 Mini
Software Version: iOS 15.1
App version: 2021.11 (2021.261)

**Home Assistant Core Version**

core-2021.10.6

**Describe the bug**

The Home Assistant app is showing up as a significant battery consumer. When I uninstall the app, there is a noticable improvement in battery life. For example, with it installed, I have to charge around twice a day. Without it, I can go through a whole 24 hour cycle before charging.

I also had the same issue with the last stable release, and I upgraded to the beta to see if it was fixed.

For example: see the very high "Screen Off" results here. I had the app uninstalled from Sunday and reinstalled Wednesday:

<img src="https://user-images.githubusercontent.com/255023/139452759-a2fe813e-1863-4ff2-85a3-21bb5855508f.jpeg" width="50%" height="50%" />

Scrolling down, we can see Home Assistant was awake for 65 hours over the 10 day period:

<img src="https://user-images.githubusercontent.com/255023/139452989-7995d589-354e-4c87-b1f5-6d4099cff888.jpeg" width="50%" height="50%" />

After reinstalling, we can see the HA was awake overnight when my phone was not in use at all:

<img src="https://user-images.githubusercontent.com/255023/139453130-083d03ac-def6-45c0-b58d-cee024c49ba9.jpeg" width="50%" height="50%" />

At first, I was chalking this up to a reporting bug in iOS, given that it's consistently reporting Siri as a top consumer, and that by energy HA is not at the top. However, I do think something is up given uninstalling has such a dramatic improvement.

A few more notes on usage: I work from home, so nearly all of the time my phone is on the same wifi network and shouldn't be triggering location updates.

**To Reproduce**

I don't have a great answer to this yet. I've just disabled location and motion permissions to see if that improves things.

**Expected behavior**

The app only causes a small increase in battery use for features like location reporting, if any at all.

**Comment by deviantintegral** [comment]
> If you're looking at the timing for when you're not using the device [...]

Yes, totally agreed, and I appreciate the explanation of how the breakdown reporting works. I wouldn't be investigating if I wasn't seeing an actual difference in my daily use.

It looks like this isn't an issue with local push. I had it off last night, and HA was responsible for the entirety of the overnight background use from 22:00-07:00 AM, resulting in a total drop of around 20%.

<img src="https://user-images.githubusercontent.com/255023/139563067-fa3c1620-6c76-4716-9366-585e181322f8.PNG" width="50%" height="50%" />

This afternoon, I saw ~25% drop over a 3 hour period with no screen on use. I will test again tonight with motion and location off, but my best guess right now is motion related since during this time the phone was in my pocket.

**Comment by zacwest** [comment]
Can you look in Settings > Location > Location History? Do you see a lot of events happening? Do you have overlapping zones where you're in-between the border of one of them often?

**Comment by deviantintegral** [comment]
Last night, my phone drained 75% overnight and powered off, with both motion and location turned off 😱 .

The report isn't attributing any _actual_ use to Home Assistant, but that's been the same this whole time.

<img src="https://user-images.githubusercontent.com/255023/139585937-154ccc4f-b0d3-44c5-b654-416d13a2b710.PNG" width="50%" height="50%" />

Location history shows only a few updates. I only have a single zone defined around my home, and I haven't left in the past day.

<img src="https://user-images.githubusercontent.com/255023/139585987-3d8a68f7-8d4c-443a-8852-7d5fa90615fd.PNG" width="50%" height="50%" />

The only option left I see is for Background App Refresh. I guess that's for reporting other sensor states? I did a quick search for[BGAppRefreshTask](https://developer.apple.com/documentation/backgroundtasks/bgapprefreshtask/) and didn't find anything. I'm turning  off the permission for now.

**Comment by deviantintegral** [comment]
Well, looks like the exception was the very first report where I had Home Assistant uninstalled, and I saw a change in battery use. I uninstalled for last night, and still had 75% drain overnight. Thanks for your feedback on the earlier comments.

<img src="https://user-images.githubusercontent.com/255023/139693334-4599f346-5bf3-48da-8607-13f17cba28cf.PNG" height="50%" width="50%" />
