### ISSUE TITLE
Custom YAML text box buggy

### ISSUE THREAD

**Issue by LewisSpring** [home-assistant/iOS#1904]
**iOS device model, version and app version**

Model Name: iPhone SE (2nd Gen)
Software Version: 15.0.2
App version: 2021.10 (2021.247)

**Home Assistant Core Version**

2021.11 (was an issue in earlier versions)

**Describe the bug**
When editing custom YAML text boxes, for example in automation editor, the text box is buggy. The cursor will move to other positions after typing a single character, and copy and paste selection copies the wrong part
**To Reproduce**
Try editing YAML in an automation
**Expected behavior**
The text box works like any normal text entry field, eg, editing a GitHub issue
**Screenshots**

https://user-images.githubusercontent.com/40576482/140513371-9ced1440-ba98-44d9-8e74-8591d6319980.MOV
**Additional context**

None

**Comment by bcmitri** [comment]
This sounds like the following issue, which was recently reopened:
https://github.com/codemirror/codemirror.next/issues/414

**Comment by LewisSpring** [comment]
> This sounds like the following issue, which was recently reopened:
> 
> https://github.com/codemirror/codemirror.next/issues/414

It does. I will add a comment there.
