### ISSUE TITLE
HA Apps shown black screen on iOS 12

### ISSUE THREAD

**Issue by ranrinc** [home-assistant/iOS#1909]
**iOS device model, version and app version**

Model Name: iPhone 6 Plus and iPhone 6
Software Version: 12.5.5
App version: 2021.11(2021.262)

**Home Assistant Core Version**
2021.11.1

**Describe the bug**
Click on the apps and HA will loaded and its go black screen with orange button on the right.
On safari lovelace open up without any problem

**Expected behavior**
Lovelace will be loaded

**Screenshots**
![photo1636443443](https://user-images.githubusercontent.com/15801696/140883507-9558d037-300f-4b87-b7e2-076147874746.jpeg)

**Comment by ranrinc** [comment]
> Can you confirm your settings for the server in your gear menu? Do you have iCloud Relay enabled?

where can I find the icloud relay enabled setting? I can seems to find it

**Comment by zacwest** [comment]
System settings app > iCloud > iCloud > Private Relay

**Comment by ranrinc** [comment]
I dont have that services enable <- paid version

**Comment by MHerweijer** [comment]
I have the same issue. Running an older iPad with IOS 12.5.5 I get a black screen when using the app. When I open HA in the browser on the same device it is working like normal. When I open the HA app on a newer IPad running IOS 15 the app works normal. I updated HA to version 2021.11.2 yesterday evening and at that moment the HA app on IOS 12.5.5 was working normal. The IPad has been off during the day and now the app won't show the information. I tried rebooting the IPad but the issue stays the same. Safari works but the HA app shows a black screen.

Thanks!

**Comment by zacwest** [comment]
You do not need to enable iCloud Relay.

iOS 12 being the common factor is interesting. You may want to check with https://github.com/home-assistant/frontend/ to see if there were any iOS 12 regressions in core-2021.11.

**Comment by MHerweijer** [comment]
Hi,

Without any changes, rebooting or what so ever the HA app is working again today. I looks a bit like i took a long time to build the cache.

**Comment by Vinz87** [comment]
I can confirm that the bug is present in iOS 12.4, and is not present in iOS 14.3

**Comment by zacwest** [comment]
home-assistant/frontend#10885

**Comment by stefanschaedeli** [comment]
Still experiencing this issue, all latest versions

**Comment by MidnightRacer99** [comment]
Yep same issue for me too. Its a real shame because this is the perfect use for an old Ipad. Any thoughts anyone?

**Comment by JSAnyone** [comment]
I have the same issue also on an iPhone 6. However, after reloading the page with swiping down it‘s working:

https://user-images.githubusercontent.com/74502558/149567931-7683829a-19e3-4cf7-a81b-69a48eb8d9e5.MOV

**Comment by oldschoolharry** [comment]
@JSAnyone Thanks so much!
I can confirm that pulling down to refresh instantly fixed this issue on my iPad Air running iOS 12.5.5.

**Comment by sparment** [comment]
I have the same challenge with IOS 12. I can pull down to refresh; but I have to do this every 24 hours. It did not used to behave this way.
