### ISSUE TITLE
After removing a NFC tag, then scanning the tag with another app, Home Assistant displays a notification that the tag is scanned along with the other app.

### ISSUE THREAD

**Issue by liquidbear99** [home-assistant/iOS#1910]
Model Name: iPhone 12 Pro Max
Software Version: iOS 15.1
App version: 2021.11

**Home Assistant Core Version**

What occurs: After removing a NFC tag, then scanning the tag with another app, home assistant displays a notification that the tag is scanned.**

Reproducing: Pair an NFC tag with home assistant. Delete the NFC tag from home assistant. Pair the NCF tag with another app like the "home" app. Scan the tag and a notification will pop up from the "home" and the home assistant app" **

What should happen: After removing the tag from HA, there should no longer be an HA notification that it was scanned**

**Comment by zacwest** [comment]
Removing the tag from the HA Tags configuration doesn't eliminate the tag's contents, which contains a URL that the app is registered to handle. You will need to erase the tag to stop the banner notification from appearing. There currently is no 'erase' functionality in the app, but the NFC Tools app on the App Store does this well.

**Comment by liquidbear99** [comment]
Super helpful! Doing this fixed my issue!
