### ISSUE TITLE
Unable to Bypass Location Startup Screen on Managed MacOS machine

### ISSUE THREAD

**Issue by jctull** [home-assistant/iOS#1919]
**Device model, version and app version**

Model Name: MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports)
macOS Version: 11.6.1
App Version: HAC 2021.11.1 (2021.266)
Safari Version: Version 15.1 (16612.2.9.1.30, 16612)

**Home Assistant Core Version**
2021.11.4

**Describe the bug**
This is on a JAMF managed computer without the ability to turn on location services for apps. Running this version of the app opens a location setting helper. I am unable to bypass this stage of the startup process and load the HA server. Hitting "Continue" does not do anything, and reviewing the location settings in the System Preferences is not a workaround as the location setting cannot be enable for the app.

**To Reproduce**
On an mdm managed device with location settings being blocked, open the app.

**Expected behavior**
Needs an option to bypass the location services request/startup screen.

![image](https://user-images.githubusercontent.com/1389731/142036329-12f3dd96-099f-4dd1-9c5a-45b2c3f0c59b.png)

**Comment by breinonline** [comment]
I have the same but on my iPhone:

** Device model, version and app version**
Model Name: iPhone 7 (A1778)
iOS Version: 15.1
App Version: HAC 2021.11.1 (2021.266, 2021.261)

**Home Assistant Core Version**
2021.11.4

**Describe the bug**
On my iPhone app updates are installed automatically. The HAC app was updated and I was promped something (forgotten which screen came first) on a blue setup-like screen. The second screen seems to freeze. Deleting and reinstalling the app freezes the app on the location screen (same as the post above). I tried to adapt settings under the Settings app > Home Assistant. This doesn't help. There is no location setting available while most apps do have such a setting. See screen:

![IMG_8F9BA3EF96A9-1](https://user-images.githubusercontent.com/37260889/142056513-15837eda-f914-4ad5-afe9-08a683f4472e.jpeg)

Installed TestFlight and also 2021.261 has this problem. I'm now back at 2021.247 which opens like it should (however still no location services settings in the settings app available).

**To Reproduce**
Open the app on iPhone 7 with iOS 15.1.

**Expected behaviour**
Setup should continue while clicking Continue button on setup screen.

**Comment by zacwest** [comment]
For the Mac case, can you grab logs of the app from Preferences > Debugging > Reveal? It should be the main app's (e.g. HomeAssistant.log or whichever it is named) file. You can either attach it here or send to me [via Dropbox](https://www.dropbox.com/request/CtVWqILBXZ41tmFSGK2y). I haven't tested this scenario on Mac, but it _should_ be skipping that screen entirely if you are unable to grant the permission at all, but it appears that is broken. For now you can downgrade to the pre-2021.11 release, but I'd like to resolve it, too.

For the iOS case:
- Can you tell me if you've got any restrictions on location services on your device, such as Parental Controls?
- Does it allow you to press Continue on that screen, or is the app locked up?
- If it's locked up, if you leave it running for a while (60+ seconds) does it eventually get quit by the system?
- Please look for crash logs in Settings > Privacy > Analytics > Analytics Data, for things starting with Home Assistant.

**Comment by breinonline** [comment]
iOS:

* I don't have any restrictions like Parental Controls. I don't use the new focus functionality except do not disturb which was already on iOS 14 and adding Home Assistant to that Focus doesn't make a difference. If I go to Settings > Privacy > Location Services > the HAC app is not listed.
* The app is locked up.
* The app stays on and the system doesn't quit it.
* The last log (Home Assistant-2021-11-12-173106.ips) is from 2021-11-12 and HAC 2021.247. So it looks like no log information is generated for the newer version of the HAC app.

Additional information: if I downgrade to HAC 2021.247 the app is working but the location services are not. I have turned them off a couple of months ago (I think that was still iOS 14.x) to reduce battery usage of Home Assistant. However, I seem not to be able to turn it on again. This version of the app shows me: 

![IMG_9389](https://user-images.githubusercontent.com/37260889/142139374-de824291-15f3-4131-b412-2712648bcd9d.PNG)
If I click Location Permission nothing happens. If I click Location Accuracy or Background Refresh I'm taken to Settings > Home Assistant. Also the older 2021.247 HAC app doesn't have a location option. Nor is it listed as an app in Settings > Privacy > Location Services.

**Comment by zacwest** [comment]
It seems to be in a really weird state. Disabled and yet not. The best next step is to reset all of your privacy settings for all of your apps. It is a drastic matter but I am unsure what else may work.

Settings > General > Transfer or Reset > Reset > Location & Privacy

**Comment by breinonline** [comment]
I have a lot apps to chose the location preferences again but your suggestion did work. The newest HAC app does run as it should now. Thanks.

**Comment by jctull** [comment]
> For the Mac case, can you grab logs of the app from Preferences > Debugging > Reveal? It should be the main app's (e.g. HomeAssistant.log or whichever it is named) file. You can either attach it here or send to me [via Dropbox](https://www.dropbox.com/request/CtVWqILBXZ41tmFSGK2y). I haven't tested this scenario on Mac, but it _should_ be skipping that screen entirely if you are unable to grant the permission at all, but it appears that is broken. For now you can downgrade to the pre-2021.11 release, but I'd like to resolve it, too.

Log attached, HTH. Thanks

**Comment by zacwest** [comment]
Looks like I didn't include anything useful in the logs to see what the current state was. Are you able to install a command line app that may output errors that I can use to see what the state is? https://github.com/fulldecent/corelocationcli looks like it'll do it.

**Comment by jctull** [comment]
I tried, but my remote management system appears to be blocking all location requests.

`CoreLocationCLI -follow -verbose`
`authorizationStatus: CLAuthorizationStatus`
`locationServicesEnabled: false`
`deferredLocationUpdatesAvailable: false`
`significantLocationChangeMonitoringAvailable: true`
`headingAvailable: false`
`regionMonitoringAvailable for CLRegion: true`
`Fetching location timed out. Exiting.`

**Comment by zacwest** [comment]
Thanks. I can probably make it consider location services being globally disabled as the same as restricted (what should normally happen here).  I'll update this ticket when it's in.

**Comment by zacwest** [comment]
Please give this beta a try and see if it resolves the issue for you: https://github.com/home-assistant/iOS/releases/tag/release%2F2021.12%2F2021.294

**Comment by jctull** [comment]
My apologies for not getting to this sooner. I just tried the latest pre-release, and it works fine on my system. I am closing this bug. Thank you!

**Comment by chezpaul** [comment]
The 2025.7.2 version still has this problem. Running on a Mac mini M4.

But a quit and relaunch went directly to my Lovelace dashboard.
