### ISSUE TITLE
Focus changes causing incorrect binary_sensor changes

### ISSUE THREAD

**Issue by abuchananTW** [home-assistant/iOS#1921]
**Device model, version and app version**

Model Name: MacBook Pro (16-inch, 2019)
macOS Version: 12.0.1
App Version: 2021.11.1
Safari Version: 15.1

**Home Assistant Core Version**
2021.11.3 (docker version)

**Describe the bug**
I use the camera_in_use binary_sensor to control my studio lighting. When the camera is in use, it turns the lights off, and when the camera is no longer in use it turns the lights off. I think starting with iOS 15, I started getting some odd things happening. The light would turn off in the middle of a meeting for example. Or another light that triggers on the laptop active sensor would turn on even though the laptop wasn't active, etc.

It took a bit to start to notice the pattern - it seems that when the Focus changes on one of my other devices (my iPad for example), within a few seconds that will sync to the laptop and when the Focus changes the sensors all start to report incorrect info.

Example from the logbook:
```
Key Light turned off by Turn off key light for webcam
4:30:10 PM - 16 minutes ago
Turn off key light for webcam has been triggered by state of binary_sensor.andrews_macbook_pro_2019_camera_in_use by Andrew’s MacBook Pro 2019 Camera In Use
4:30:10 PM - 16 minutes ago
Andrew’s MacBook Pro 2019 Focus turned off
4:30:10 PM - 16 minutes ago
Andrew’s MacBook Pro 2019 Active Microphone changed to Inactive
4:30:10 PM - 16 minutes ago
Andrew’s MacBook Pro 2019 Microphone In Use turned off
4:30:10 PM - 16 minutes ago
Andrew’s MacBook Pro 2019 Active Camera changed to Inactive
4:30:10 PM - 16 minutes ago
Andrew’s MacBook Pro 2019 Camera In Use turned off
4:30:10 PM - 16 minutes ago
Andrew’s iPad Focus turned off
4:30:08 PM - 16 minutes ago
```

During that time, I was in a video call and typing on the keyboard, so the machine was definitely active.

An example of when a focus change on my iPad triggered a change:
```
Mini Office Ceiling Light turned on by Turn on mini office light when occupied
8:25:56 AM - 8 hours ago
Andrew’s iPad Last Update Trigger changed to Siri
8:25:56 AM - 8 hours ago
Andrew’s iPad Focus turned off
8:25:56 AM - 8 hours ago
Turn on mini office light when occupied has been triggered by state of binary_sensor.andrews_macbook_pro_2019_active by Andrew’s MacBook Pro 2019 Active
8:25:56 AM - 8 hours ago
Andrew’s MacBook Pro 2019 Focus turned off
8:25:56 AM - 8 hours ago
Andrew’s MacBook Pro 2019 Active turned on
8:25:56 AM - 8 hours ago
```

**To Reproduce**
Have a laptop and an iOS device logged into the same apple account and a camera in use on the laptop (FaceTime looking at yourself before a call for example)
On iOS device, turn on one of the Focuses.
In my case this reliably causes the camera state in HA to report inactive and turned off for the laptop, even though the camera is still on

**Expected behavior**
Sensor values on the laptop should not change unless the camera state changes (for example)

**Comment by harryohalloran** [comment]
I just installed the update today and am having the exact same issue.  I have automations set to turn on my Elgato lights when then camera is in use and off when not and upon focus changing, I'm seeing "Camera In Use" binary sensor change even though the camera is still on.

**Comment by sebr** [comment]
+1 seeing the same issue, albeit with the `sensor.active` entity.

**Comment by tompijls** [comment]
I was recommended to disable the focus permission for now for the companion app
