### ISSUE TITLE
Siri shortcuts always prompt "Allow "<shortcut name> to access "(null)"?" on watch after ios 15 update for any shortcut calling home assistant

### ISSUE THREAD

**Issue by smos08** [home-assistant/iOS#1925]
**iOS device model, version and app version**

Watch Model Name: Apple watch 7
Watch Software Version: 8.1.1

Phone Model Name: Iphone 13 mini
Phone Software Version: 15.1.1
Phone App version: 2021.11.1 (2021.266)

**Home Assistant Core Version**
core-2021.11.0

**Describe the bug**
after the ios 15 update every time i try to initiate a shortcut that interacts with home assistant from my watch i am prompted "Allow "<shortcut name> to access "(null)"?".  it asks to "allow" or "don't allow" but selecting "allow" does not prevent the prompt next time.  

**To Reproduce**
create a shortcut that calls a script (or service) and attempt to use siri to launch the shortcut from the watch 

**Expected behavior**
the shortcut should be initiated without a prompt

**Screenshots**
watch prompt
![IMG_0263](https://user-images.githubusercontent.com/19764927/142917266-0b880558-ec02-4e35-985f-7b558a48ccbd.jpg)

 siri shortcut.  
![BC9E33FE-6591-4BBE-B240-5CFB613FE4B6_1_102_o](https://user-images.githubusercontent.com/19764927/142917486-29d16f86-8fd5-45fd-95f5-ca6caeea1ce8.jpeg)

**Additional context**
running the shortcut on the phone works fine without any prompting except for the first time.  

there are a few threads on reddit and mac forums of others having the same issues on other apps.

https://discussions.apple.com/thread/253209888?answerId=256023645022#256023645022
https://www.reddit.com/r/shortcuts/comments/q3jsoy/when_i_trigger_shortcuts_via_siri_on_my_apple/hkrr95e/

**Comment by DewaldBez** [comment]
I can confirm I'm having the same issue
![image](https://user-images.githubusercontent.com/1138085/144726480-b0c6c2a5-fc1c-4351-92a2-a8e0f954fe56.jpeg)

The only workaround I have found is to do an HTTP POST request using the native shortcuts action

**Comment by ViViDboarder** [comment]
This is an Apple issue. Happens to me with any shortcut that interacts with an app.

**Comment by smos08** [comment]
> This is an Apple issue. Happens to me with any shortcut that interacts with an app.

that was my assumption since it happened after ios15 but i am seeing others saying the issue has gone away on some apps after they were updated.

**Comment by roybot0101** [comment]
having same issue.

**Comment by smos08** [comment]
after some recent home assistant ios updates looks like i no longer get "null" as the application but i am still always prompted to allow.  at this point i have to assume it is now an apple watch shortcut deficiency and will close thi

**Comment by stx** [comment]
@smos08 It can be fixed by moving the intent handlers to run on the watch rather than through the iPhone. It's definitely an Apple Watch bug though.

**Comment by smos08** [comment]
> @smos08 It can be fixed by moving the intent handlers to run on the watch rather than through the iPhone (we've done this with our production apps to fix the same issue.) It's definitely an Apple Watch bug though.
@stx is that something i would do as a end user or needs to be done on the dev side?

**Comment by stx** [comment]
Devs have to do it by adding a WatchOS Intent Extension target in Xcode. Unless you do this the Siri/Shortcut intents are sent to the iPhone and that’s what triggers the bug. I’ve reported it to Apple but they haven’t moved on it yet.

**Comment by smos08** [comment]
thank you for the detailed explanation, i'm going to reopen then for now so this trail is more visible

**Comment by zacwest** [comment]
Some of the intents could be run on watch, but some can't. To get an idea of whether it's worth adding it to the watch: which actions are you running? These probably can work:
- Call Service
- Fire Event
- Get Camera Image
- Perform Action
- Render Template

These probably cannot:
- Send Location
- Update Sensors
- Open Page

**Comment by smos08** [comment]
right now the only thing i am using it for is to call the "script.turn_on" service and fire some events.  the actions you have listed look well enough in the realm of at least what i would use it for and at least provide a way to accomplish most things.  here is a screenshot of one of my shortcuts.

![IMG_0608](https://user-images.githubusercontent.com/19764927/155892253-5a17e691-aa51-4038-bb47-e530fc55ece4.PNG)

**Comment by krissen** [comment]
Any update on this issue?

I know it's supposed to be an Apple Watch bug, but I had the same issue with some other apps (Overcast, for instance), and later an update of said _app_ led to the issue disappearing. 

Pending a fix on watchOS side, it would really be wonderful if there is something that can be done to circumvent the issue (other than using webhooks)? I used to use HA through Shortcuts _all the time,_ until this bug emerged (iOS 15/watchos 8,  I think?). Now it's so cumbersome that I basically ignore it on the watch, only use HA-shortcuts on the phone.

**Comment by thedanbob** [comment]
> The only workaround I have found is to do an HTTP POST request using the native shortcuts action

This workaround appears to no longer work as of iOS 16.2 / watchOS 9.2. I converted a shortcut from Home Assistant actions to the REST API, but now instead of asking for permission to access Home Assistant, my watch just asks permission to access my HA server's domain name. Actually, it's worse now, since after hitting allow my watch then asked which shortcut I'd like to run. (How about the one I asked you to run? The one *you* asked *permission* to run??)

However, I may have discovered another workaround of sorts. When trying to run the original shortcut that used Home Assistant actions, one time instead of hitting allow I just pressed the crown to dismiss the dialog quickly. I was then surprised when the shortcut ran anyway. Perhaps the crown is interpreted as "allow" rather than "cancel" in this context, or perhaps it's a bug. In any case, it's a lot more convenient than hitting allow on the screen.

**Comment by krissen** [comment]
> However, I may have discovered another workaround of sorts. When trying to run the original shortcut that used Home Assistant actions, one time instead of hitting allow I just pressed the crown to dismiss the dialog quickly. I was then surprised when the shortcut ran anyway. Perhaps the crown is interpreted as "allow" rather than "cancel" in this context, or perhaps it's a bug. In any case, it's a lot more convenient than hitting allow on the screen.

Doesn't work here, using the crown like that. Nothing happens besides scrolling the permission notification.

**Comment by thedanbob** [comment]
I did some more testing last night and found a better workaround (for me). After deleting and recreating the shortcut, and uninstalling Home Assistant from the watch, running the shortcut from the watch only asks permission the first time. If I install Home Assistant to the watch it asks permission every time, and then asks which shortcut I'd like to run (which I already told it).

Obviously this won't work for anyone who uses Home Assistant complications, but I only want to run shortcuts so I don't need the watch app.

**Comment by smos08** [comment]
> 

oh that sounds promising for me too, i will give this a shot.  i would have liked to use the compilations but can sacrifice them for this.

**Comment by krissen** [comment]
> I did some more testing last night and found a better workaround (for me). After deleting and recreating the shortcut, and uninstalling Home Assistant from the watch, running the shortcut from the watch only asks permission the first time. If I install Home Assistant to the watch it asks permission every time, and then asks which shortcut I'd like to run (which I already told it).
> 
> Obviously this won't work for anyone who uses Home Assistant complications, but I only want to run shortcuts so I don't need the watch app.

Interesting! Indeed, a viable workaround. Although complications are sacrificed, it would be worth it for me, too.

Perhaps it'll also help troubleshoot it; the problem doesn't seem to lie with the iOS Companion, but *watchOS* companion.

**Comment by jwfox5150** [comment]
Commenting here to bump this issue.

> I did some more testing last night and found a better workaround (for me). After deleting and recreating the shortcut, and uninstalling Home Assistant from the watch, running the shortcut from the watch only asks permission the first time. If I install Home Assistant to the watch it asks permission every time, and then asks which shortcut I'd like to run (which I already told it).
> 
> Obviously this won't work for anyone who uses Home Assistant complications, but I only want to run shortcuts so I don't need the watch app.

This does indeed work, however, it breaks actionable notifications on the Apple Watch.

**Comment by KwisatzJim** [comment]
> I did some more testing last night and found a better workaround (for me). After deleting and recreating the shortcut, and uninstalling Home Assistant from the watch, running the shortcut from the watch only asks permission the first time. If I install Home Assistant to the watch it asks permission every time, and then asks which shortcut I'd like to run (which I already told it).
> 
> Obviously this won't work for anyone who uses Home Assistant complications, but I only want to run shortcuts so I don't need the watch app.

just tried this after discovering the issue, and this thread, and it worked for me. thanks!

**Comment by smos08** [comment]
this appears to be resolved using the latest watchos and ios, i do not get a prompt anymore.
