### ISSUE TITLE
Black screen on startup

### ISSUE THREAD

**Issue by Vinz87** [home-assistant/iOS#1930]
**iOS device model, version and app version**

Model Name: iPhone 8
Software Version: 12.4
App version: 2021.11.1 (2021.266)

**Home Assistant Core Version**

core-2021.11.5
supervisor-2021.10.8
Home Assistant OS 6.6

**Describe the bug**
When launching the app, a black screen is shown.
Scrolling down will do a refresh and show the frontend correctly.

**To Reproduce**
Launch the app

**Expected behavior**
Nominal frontend

**Screenshots**

![](https://community-assets.home-assistant.io/original/3X/5/e/5ec926c857b669a285466de6ef7fade89ca35fe8.jpeg)

**Additional context**

Other people have the same issue as reported here: https://community.home-assistant.io/t/black-screen-at-startup/356190

**Comment by zacwest** [comment]
#1909
