### ISSUE TITLE
External URL is not taken correctly and changes itself.

### ISSUE THREAD

**Issue by TheCyberfreak** [home-assistant/iOS#1932]
**iOS device model, version and app version**
Model Name: iPhone 13 Pro
Software Version: 15.1.1
App version: 2021.11.1 (2021.266)

**Home Assistant Core Version**
core-2021.11.5

**Describe the bug**
When the external URL is changed in Home Assistant in the settings, this is not registered by the app.
I had my own URL at the beginning and now wanted to use the cloud. I removed the external URL and even though I activated the "Cloud URL" setting several times in the app, it is reset after different amounts of time and the old URL is again in the settings. It is sometimes enough to close the app completely and open it again, or to deactivate the WLAN while the app is closed.

**To Reproduce**
The error occurs very often, however, I can not say exactly how to reproduce it quite accurately.

**Expected behavior**
The setting should be correctly copied from Home Assistant. If no external URL is set, the app should automatically try to connect via the cloud.

**Comment by zacwest** [comment]
Please try the latest [iOS beta](https://www.home-assistant.io/ios/beta) or 2021.12 (whichever comes out first); there's been some substantial changes to how these values are read/written and I think it may fix this. If not, in 2012.12, please send in diagnostic logs from App Configuration > Debugging when you encounter this and add 'em [to this Dropbox request](https://www.dropbox.com/request/CtVWqILBXZ41tmFSGK2y).
