### ISSUE TITLE
Unable to activate TestFlight beta for macOS

### ISSUE THREAD

**Issue by deviantintegral** [home-assistant/iOS#1944]
When I open the link for the macOS beta at https://github.com/home-assistant/iOS/releases/tag/release%2F2021.12%2F2021.278, it opens TestFlight but it only shows as available for iOS devices:

<img width="1212" alt="Screen Shot 2021-11-28 at 3 32 39 PM" src="https://user-images.githubusercontent.com/255023/143784875-020fdbcf-eebc-442c-9bca-6506a779752c.png">

In Compatibility, it says it requires an Apple Silicon chip (I'm on an Intel), but perhaps that's because it actually needs a separate link for the macOS app?

**Comment by zacwest** [comment]
Oh the Mac version wasn't approved by Apple yet, I misread the build status. It should be up soon.

**Comment by zacwest** [comment]
Should be available now
