### ISSUE TITLE
Unable to add a secondary server in the macOS app

### ISSUE THREAD

**Issue by deviantintegral** [home-assistant/iOS#1951]
**Device model, version and app version**

Model Name: MacBook Pro (16-inch, 2019)
macOS Version: macOS 12.0.1
App Version: 2021.12 (2021.284) 
Safari Version: Version 15.1 (17612.2.9.1.20)

**Home Assistant Core Version**
2021.11.5

**Describe the bug**

I'm unable to add a second server instance to the app. I'm not on site right now, so I'm adding it via the nabu casa URL. Notably, this part worked fine on iOS a few days ago.

**To Reproduce**

1. Try to add a new server.
2. Enter the nabu casa URL.
3. Press connect.
4. Nothing happens, the connect button no longer responds, and only the back button is functional.

**Expected behavior**

I can add a second server.

**Screenshots**

<img width="712" alt="Screen Shot 2021-11-30 at 9 50 24 PM" src="https://user-images.githubusercontent.com/255023/144163324-08409176-f671-4735-90f3-0c078ec91186.png">

**Additional context**

This console message seems relevant. Also, I can access the instance without issue in Safari. Also, I haven't tried a local URL, since I imagine adding two servers in the app going to the same HA instance would lead to suffering.

> default	21:52:13.193281-0500	Home Assistant	Task <54EDDF03-9675-4D2D-A95E-030ECE8EE0C5>.<94> finished with error [-999] Error Domain=NSURLErrorDomain Code=-999 UserInfo={NSErrorFailingURLStringKey=<private>, NSErrorFailingURLKey=<private>, _NSURLErrorRelatedURLSessionTaskErrorKey=<private>, _NSURLErrorFailingURLSessionTaskErrorKey=<private>, NSLocalizedDescription=<private>}

**Comment by zacwest** [comment]
Chances are this is Safari getting stuck (seems to be a recent-ish Safari regression) when it's trying to open the login screen. Restarting the Safari app will fix it.

**Comment by deviantintegral** [comment]
😮 well, now I understand why you ask for the Safari version in the template!

Restarting Safari caused the window to show up immediately. Since I wasn't sure if it was actually going to post back to the app, I closed it... and a new one opened, looping I think for each time I tried to add a server.

I wonder if it's worth adding some UI text, even temporarily, along the lines of:

> Pressing Connect will open Safari to log in to your Home Assistant Server. If nothing happens after pressing Connect, quit and reopen Safari. A new window will show up asking for your login credentials.

**Comment by zacwest** [comment]
Yup, that's roughly what I'm looking to do, it's a common enough complaint recently.

**Comment by david-romero** [comment]
Hi @zacwest, If Safari is not configured as the default browser (Example: Chrome), after restarting Safari and log-in, the app does not start. The app is not able to fetch the log-in from Safari.

Once you configure Safari as the default browser, everything is working well.
