### ISSUE TITLE
Apple Watch complications not updating unless iOS App is opened/activate on screen

### ISSUE THREAD

**Issue by Doa132** [home-assistant/iOS#1955]
**iOS device model, version and app version**
Model Name: iPhone XS
Software Version: 15.2
App version: 2021.12 (2021.284)

**Home Assistant Core Version**
core-2021.11.5

**Describe the bug**
Apple Watch complication doesn't update until Home Assistant app is on screen. This includes not updating automatically every 15 minutes and not updating when "update_complications" notification message is used. Not sure if it'll eventually update if too long passes, but there'd been no update in over 5hrs while I was at work. 
Once app is clicked on, complications usually update within a minute.

**Additional context**
Two things that I'm not sure if related. 
 Firstly, I'm also getting invalid authentication messages really often. Typically happens if I haven't opened the app really recently. Not sure how long between opens to have it trigger. I'm not closing the app fully in between, just switching to Home Screen or another app.
Message in Logs:
"Login attempt or request with invalid authentication from 192.168.50.57 (192.168.50.57). (Mozilla/5.0 (iPhone; CPU iPhone OS 15_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2021.12 (io.robbie.HomeAssistant; build:2021.278; iOS 15.2.0) Mobile/HomeAssistant, like Safari)"

Secondly, when I do open the app, I often need to drag the screen down to refresh before it'll update. 
The app has all permissions enabled, including Background App Refresh, if that makes a difference.

**Comment by zacwest** [comment]
If you launch the app, does it start updating complications in the background successfully, or does it only update the one time?

Do you have Background Refresh enabled in the Watch app's settings? It's a separate one from the iOS Settings app.

The authentication error you're seeing in the logs isn't coming from the Watch, so it should be unrelated.

**Comment by Doa132** [comment]
Background Refresh is enabled in watch setting. Updated app to 2021.12 (2021.306)
Did a few tests:
1. Kept phone screen on with HA active on screen, waited for the watch complication to refresh and then unlocked my door, which should have triggered a manual update (door lock state is on complication). Waited a couple minutes but there was no update until about a minute after I pulled down to refresh the app.
2. Locked the door (at 12:24) and tried again. This time I waited longer and made sure it went past 12:30 to see if automatic update would occur, while also keeping HA active on screen. Complication updated at 12:33. 
3. Unlocked door again at 12:34, kept HA active on screen and waited. No complication update shows until 12:41.
While waiting for complication to update I had let watch screen go dark for over a minute at a time, tried clicking on complication to see actions, swiped to watch face without HA complication on it.
4. Let phone screen turn off (without swiping away from HA app). Locked door again at 12:47. Left phone locked and checked watch every few minutes. Still no update by 13:08. Had to remove watch to charge and go shower then. Still hadn't unlocked my phone by this point. When I put the watch back on at 13:56, it had updated.
Working tonight so I'll see if it updates at all while I'm at work.

**Comment by TomBrien** [comment]
I'm seeing something similar. I have a complication (admittedly on a face I don't use much) that has {{ time.time }} on it for this exact reason. When reading this, I checked and that complication was 4 hours behind, it used to never be more than 15. Opening watch app doesn't fox it, opening phone app, refreshing and then opening the watch app seemed to update. Not sure if this is related to issues of freezing frontend. 
![image](https://user-images.githubusercontent.com/12411302/144810926-ea2ba96f-5e2e-465e-8cb7-5af0750d759c.png)

**Comment by zacwest** [comment]
Sounds like it may be a regression in 2012.12. May be server related - does this reproduce for you out of the house or at home? What I am trying to figure out is if it's trying to do internal when external or vice versa. Launching the app may update which it's using when it syncs with the watch.

**Comment by TomBrien** [comment]
This reproduces at home for me but with my dev/second instances off. When I get home I'll leave that running and see if it helps. My primary instance has the same internal/external URLs

**Comment by Doa132** [comment]
Occurs both at home and away

**Comment by zacwest** [comment]
Figured it out. Complications were only updating iOS side, which jives with your report. Will be fixed in the next beta, thanks.
