### ISSUE TITLE
Again iOS app is only showing 'Initializing'

### ISSUE THREAD

**Issue by SOAPeople-RonaldSmaal** [home-assistant/iOS#1967]
Just installed HA in Docker on Syno as described in https://www.home-assistant.io/installation/alternative. UI works fine with browser but not on iPhone. 
Any suggestions?

**Comment by zacwest** [comment]
What version of the app? What version of HA? What version of iOS? Can you share a screenshot? When you say other browsers, does it work in Safari on iOS?

**Comment by SOAPeople-RonaldSmaal** [comment]
, HA 2021.11.5 (=stable docker image homeassistant/home-assistant), iOS on iPhone7 15.1,
![2021-12-03-143108_001](https://user-images.githubusercontent.com/75834898/144637332-826b32a9-90ae-42a4-818d-4a34b0ca8aa2.jpeg), when using a browser FF/Chrome on any device it works like a charm, except Safari on desktop as well as mobile. Btw. Docker version 20.10.3-0554 on synology DSM 6.2.4-25556 Update 2. So it seems to be Safari related, checked the browser console, no errors.

**Comment by SOAPeople-RonaldSmaal** [comment]
Forgot the app version: 2021.11.1

**Comment by zacwest** [comment]
If this is failing to work on Safari on the various platforms, it sounds like an issue in the login screen and not the app. Please check for or file an issue in the frontend repo: https://github.com/home-assistant/frontend
