### ISSUE TITLE
No detection of Bluetooth audio device's use (input & output)

### ISSUE THREAD

**Issue by T-Bendrath** [home-assistant/iOS#1984]
**Device model, version and app version**
Model Name: MacBook Pro (14-inch, 2021)
macOS Version: 12.0.1
App Version: 2021.12 (2021.312)
Safari Version: 15.1

**Home Assistant Core Version**
2021.11.5

**Describe the bug**
The sensors of the MacOS companion app indicating the Active Audio Input & Output devices seem to not work for Bluetooth devices. When the Audio Input device (microphone) is currently in use, e.g. in a call, the sensors `binary_sensor.audio_input_in_use` and `sensor.active_audio_input` do not change and remain `true` and `Inactive` respectively. I tested this behavior with Apple AirPods Pro and Jabra Evolve 75 in MS Teams calls. I identified this behavior a few days ago already with App version 2021.12 (306) and thus before the introduction of the newly added Audio Output sensors (see #1978). In addition, both Audio Output sensors also do not recognize the use of the Bluetooth device. However, the Bluetooth device is shown in the attributes "All Audio Input" and "All Audio Output" of both "Active Audio Input/Output" sensors.

**To Reproduce**
Check the sensor values in Home Assistant Companion App > Preferences > Sensors.

Connect a Bluetooth audio device to the laptop that the HA companion app is running on and select this device for sound output (/ input) in Settings > Sound > Output (/ Input).

Make sure the audio device is currently in use by playing music or testing the microphone.

**Expected behavior**
When the Bluetooth Audio Input device is currently in use the following sensors change:
`binary_sensor.audio_input_in_use` is set to `true`
`sensor.active_audio_input` is set to the name of the Bluetooth Audio Input device

When the Bluetooth Audio Output device is currently in use the following sensors change:
`binary_sensor.audio_output_in_use` is set to `true`
`sensor.active_audio_output` is set to the name of the Bluetooth Audio Output device

**Screenshots**
***Audio Input***
MacOS settings that show AirPods Pro as selected input device:
![image](https://user-images.githubusercontent.com/15731290/145449425-8853a1a1-cdf4-40a1-967b-b9d9f2691a42.png)

Attribute "Active Audio Input" is not set but "AirPods Pro" is listed in "All Audio Input":
![image](https://user-images.githubusercontent.com/15731290/145448532-07d99e85-da88-420a-86e5-352c69acde21.png)

***Audio Output***
MacOS settings that show AirPods Pro as selected output device:
![image](https://user-images.githubusercontent.com/15731290/145449225-107fed79-f996-42b0-a250-401198b13801.png)

Attribute "Active Audio Output" is not set but "AirPods Pro" is listed in "All Audio Output":
![image](https://user-images.githubusercontent.com/15731290/145448404-bf98be10-0968-4391-adb8-d554b325a889.png)

**Additional context**
I checked the MacOS privacy settings but Home Assistant is not listed as an application that requests access to the microphone thus I do not expect this to be an issue due to missing permissions on the laptop. Additionally, audio devices that do not connect via Bluetooth to the laptop do not cause issues.

The technical feasibility of identifying if a Bluetooth device connects to the laptop has been discussed before in #1331. However, it was not transparent enough to me if this is also the reason the Bluetooth audio device's use cannot be detected properly.

**Comment by zacwest** [comment]
I believe Apple shipped some pretty bad regressions for bluetooth devices that is causing them to never become 'active'. See #1903 -- does this sound like your issue?

**Comment by T-Bendrath** [comment]
Thank you @zacwest for pointing me to a similar issue and already filing this with Apple. I didn't indeed see the other issue from Nov 4. My issue can be closed then as this is a duplicate of #1903.
