### ISSUE TITLE
Selecting entity or device in automations, scenes, etc. is extremely difficult.

### ISSUE THREAD

**Issue by brian1917** [home-assistant/iOS#1985]
I am using 2021.11.1 (2021.266) iOS app, but have seen this for a while.

When I try to edit an automation and select a device, it is nearly impossible on the mobile UI. For example, if I am searching for my "Christmas Tree" entity, I start typing "Christmas" and it finds the entity. When I click the found entity, nothing happens.

There is some UI bug that makes editing/building automations, scripts, scenes, etc. nearly impossible on the mobile app.

**Comment by zacwest** [comment]
This sounds like a good ticket to file in the [frontend repo](https://github.com/home-assistant/frontend/issues/new?assignees=&labels=bug&template=bug_report.yml). Please make sure you
