### ISSUE TITLE
App config not accessible after updating to 2021.12

### ISSUE THREAD

**Issue by golles** [home-assistant/iOS#1993]
**iOS device model, version and app version**

Model Name: 13 pro
Software Version: 15.1.1
App version: ? can't check this, no updates in App Store

**Home Assistant Core Version**

2021.12
**Describe the bug**
App configuration menu item is not visible on the iPhone.
I can't remember if this item was on the OSX version, I can access the settings there with `CMD + ,`
**To Reproduce**

**Expected behavior**

**Screenshots**

![IMG_9704](https://user-images.githubusercontent.com/2211503/145709969-76044602-e721-4fa2-9697-448a384b29bd.jpeg)

**Additional context**

**Comment by TomBrien** [comment]
In 2012.12 App Configuration has moved into the Configuration section and is now call Companion App. Please see the [breaking changes in the release notes](https://www.home-assistant.io/blog/2021/12/11/release-202112/#breaking-changes).

**Comment by golles** [comment]
> breaking changes in the release notes

Oh wow, that was not straightforward, I've got auto-updates on, so I don't see app release notes.
Thanks for pointing it out
