### ISSUE TITLE
Cannot Access App Configuration without Admin Privileges after 2021.12

### ISSUE THREAD

**Issue by mandrepont** [home-assistant/iOS#1997]
**iOS device model, version and app version**

Model Name: iPhone XS
Software Version: 15.1 (19B74)
App version: 2021.11.1

**Home Assistant Core Version**
core-2021.12.0

**Describe the bug**
Without admin role on a user that user is not able to edit their app configuration.
I know that App Configuration was moved into Configuration menu (#1993), though I don't believe it is expected that users without the admin role should no be able to access this configuration. 

**To Reproduce**

**Expected behavior**
I would expect users without the admin role should be able to either have the app configuration menu item back or show them just that entry in the configuration menu rather than hiding the configuration and making it impossible to access.

**Comment by zacwest** [comment]
Darn, looks like this was an oversight. Thanks for filing. Workarounds for the moment
1. Enable Airplane Mode & disable Wi-Fi and re-launch the app.
2. On iOS-2021.12, swipe up with 3 fingers and tap the settings icon.

If you do not have iOS-2021.12, it's currently a [TestFlight beta](https://www.home-assistant.io/ios/beta) at the time of writing this.
