### ISSUE TITLE
Normal user (non admin) can't access Companion App settings in 2021.12

### ISSUE THREAD

**Issue by weelad** [home-assistant/iOS#2001]
Model Name: iPhone 10XS
Software Version: 14.8.1
App version: Home Assistant Companion 2021.11.1 (2021.266) 

**Home Assistant Core Version**
2021.12

**Describe the bug**
There is a change introduced in HA Core 2021.12 where:
"If you are using our Android, iOS, or macOS Companion apps, the sidebar menu to configure those has also been moved into the configuration panel."

This is an issue when you have users that are not admins, they cannot access the settings for the Companion App. 

A non admin user of mine was not able to access the settings to enable for example Home Assistant Cloud so that they could use the app remotely or access settings to do with creating Actions or configuring their Apple Watch.

I had to promote normal users to admin to work around this.

This update to HA doesn't take into account that normal users will still need access to the Companion App settings.

I presume this will affect Android, iOS and macOS too.

Let me know if you require any more information, cheers.

**Comment by TomBrien** [comment]
Fixed by home-assistant/frontend#10890 which will be included in 2021.12.2

**Comment by weelad** [comment]
@TomBrien how are patches announced? I couldn't find anything on the HA release-notes blog.

I currently use Docker. Do I need to update my docker-compose from `ghcr.io/home-assistant/home-assistant:stable` to `ghcr.io/home-assistant/home-assistant:latest` to be able to access this when it's released?

**Comment by weelad** [comment]
Thanks 👍

**Comment by TomBrien** [comment]
@weelad the patch should be out sometime tomorrow

**Comment by weelad** [comment]
Cool, thanks for getting back to me!
