### ISSUE TITLE
Gauge not displayed properly

### ISSUE THREAD

**Issue by ohnefrust** [home-assistant/iOS#2002]
**Versions / Devices**
Model Name: Mac Mini 2018
macOS Version: 12.1
App Version: 2021.12 (2021.315)

**Description of the bug**
Gauge card is not displayed correctly (see picture below)

**Steps to reproduce the bug**
Add a gauge card. Had the same problem with all gauge cards.

**Expected behavior**
Gauge card is displayed correctly

**Other observations**
I found out that the gauge card is displayed correctly in Google Chrome. Only safari and the Home Assistant apps have problems to display the gauge card correctly.

<img width="606" alt="Bildschirmfoto 2021-12-14 um 20 20 01" src="https://user-images.githubusercontent.com/22940070/146065113-7993e636-bed0-4b8f-8350-eb5c93d64bb4.png">

**Comment by zacwest** [comment]
home-assistant/frontend#10766

**Comment by ohnefrust** [comment]
Thanks Zac! Sorry, I've overlooked that one!

**Comment by TomBrien** [comment]
Pinning for reference. See also home-assistant/frontend#10910

**Comment by TomBrien** [comment]
Note this is fixed in 2022.2 via https://github.com/home-assistant/frontend/issues/11041

**Comment by b0ulanger** [comment]
When will this be fixed?
Still have those problems al my gauges are messed up.

Running on iOS 15.3 and Home Assistant App 2021.12.1 (2021.327), also my Server shows up twice on the iOS app.
When i remove one, the next time i open the App it shows two Server connections again.

**Comment by zacwest** [comment]
There are multiple links throughout this ticket to the paired frontend issue that has the resolution info. This is fixed in the frontend version being released with core-2022.2 this week.
