### ISSUE TITLE
Gauge card not rendering correctly

### ISSUE THREAD

**Issue by wifijt** [home-assistant/iOS#2007]
Model Name: iPhone 12pro iOS 15.2
Software Version: HA 2021.12.2
App version: 2021.11.1

**Home Assistant Core Version** 
2021.12.2
**Describe the bug**
Gauge cards do not render correctly - the color fill bar is not aligned at all to the outline - it's rotated like 90 degrees
**To Reproduce**

**Expected behavior**

**Screenshots**
![](https://community-assets.home-assistant.io/original/4X/6/e/1/6e1e30e8dc00d841d73fbb97ec510b1e28e937fa.jpeg)

**Additional context**
Multiple report of this

https://community.home-assistant.io/t/gauge-card-strangely-displayed/361957

**Comment by zacwest** [comment]
https://github.com/home-assistant/frontend/issues/10910
