### ISSUE TITLE
App crash on launch iOS 12.5.5.

### ISSUE THREAD

**Issue by Camatobe** [home-assistant/iOS#2008]
**iOS device model, version and app version**

Model Name: iPad Air (iPad4)
Software Version: 12.5.5 (16H62)
App version: 2021.322 (2021.12)

**Home Assistant Core Version**
2021.12.3

**Describe the bug**
App crashes on startup – only splash-screen is shortly visible.
even reinstall does not fix the issue

**To Reproduce**
start the App on 12.5.5 on iPad Air 

**Expected behavior**
App should launch

**Screenshots**
none

**Additional context**
I added my CrashLog as PDF
[CrashLog_12.5.5..pdf](https://github.com/home-assistant/iOS/files/7739970/CrashLog_12.5.5.pdf)

**Comment by zacwest** [comment]
I just put out a new beta -- 2021.12.1 -- which I believe fixes this crash. Please report back if you find it works or doesn't work.

**Comment by Camatobe** [comment]
Fixes the crash. Thanks a lot!

**Comment by zacwest** [comment]
Thanks for confirming!

**Comment by Flipsoo** [comment]
also working for me:

iOS 12.5.5 iPad Mini 2

**Comment by alexeyovich** [comment]
Hi, 

I’m getting the same problem on my iPhone 6 (NOT 6s), with the same version of iOS. 

How can I get the fixed version of the Home Assistant app? My iPhone is not jail broken. 

Is there going to be another release in the next few days or will it be next month? 
Thanks in advance!

**Comment by Camatobe** [comment]
> How can I get the fixed version of the Home Assistant app? My iPhone is not jail broken. 


See the temporary Workaround in the comments above 😉

Will paste Zac's answer again. The Version 2021.12.1 should work too.

> Temporary workaround: install 2021.12 (2021.306) or earlier [on TestFlight](https://www.home-assistant.io/ios/beta). This is just before when the Apple-side bug started.

**Comment by alexeyovich** [comment]
Thanks; I must admit that I hadn’t heard of TestFlight before. 
I may need to free up some space on my ageing handset! 
Cheers!

**Comment by alexeyovich** [comment]
TestFlight requires iOS 13 or later, so unfortunately this is a non-starter for me. 
I really need to upgrade my phone, but won’t be doing that immediately. 
Any other way round this problem?

**Comment by zacwest** [comment]
You can likely install an older version of TestFlight but the instructions are complicated if you don't have any devices which are iOS 13+.

A version with the fix is pending review with Apple and is scheduled to be released immediately once approved. Hopefully the wait isn't too long, but it's been pending since Saturday now.

**Comment by lpt2007** [comment]
Any news about that I have same roblem on iphone 6 ios 12.5.5

**Comment by dmexs** [comment]
Experiencing this issue on iPad Mini 2 on iOS 12.5.5. Is the fix still pending? Trying to get TestFlight to install but that' has proved difficult as well.

**Comment by FS1961** [comment]
I have the issue where the startup screen "hangs" but swiping up/down repeatedly clears and then the app loads. Same IOS version. Any thoughts?

**Comment by Camatobe** [comment]
> I have the issue where the startup screen "hangs" but swiping up/down repeatedly clears and then the app loads. Same IOS version. Any thoughts?

What do you mean by startup screen? – because I think I have the similar issue.

My iPad Air (iPad4) on 12.5.5 (16H62) is woken up by motion sensor (via Kiosk Mode + Home-Kit Notification).
Irregularly the App hangs in the "startup-screen" (White background, Home-Assistant Logo in the middle).

Only by interacting and "pull to refresh" the Dashboard loads again.
Annoying for trying to get Information by a walk by.

**Comment by FS1961** [comment]
I mean it just stays here until I swipe up and down repeatedly. 
![34AB50BA-F973-4DDA-915E-32101C08C931](https://user-images.githubusercontent.com/98458806/158009310-de5b47b4-b6c4-45e4-8da8-6ea8da17f19c.jpeg)
