### ISSUE TITLE
Homeassistant App on iPadOS 12.5.5 crashing on Startup

### ISSUE THREAD

**Issue by BeeHeisenberg** [home-assistant/iOS#2011]
**iOS device model, version and app version**

Model Name: iPad Air 1 2013
Software Version: iOS 12.5.5
App version: 2021.12

**Home Assistant Core Version**
core-2021.12.3

**Describe the bug**
I have today on 19.12.21 an update of the Homeassistant app on my iPad Air 1 carried out after this update I started the app and had to find that it no longer open. The app quits immediately after trying to open it. Meanwhile I have already reset my iPad, but the error remains the same.

**To Reproduce**
on my wife's iPad is the same problem
**Expected behavior**
that the app opens
**Screenshots**
no

**Additional context**

**Comment by TomBrien** [comment]
Please see #2008. A fix has been found and the update has been submitted to Apple.

**Comment by BeeHeisenberg** [comment]
Thanks
