### ISSUE TITLE
Gauce card need misplaced in iPhone

### ISSUE THREAD

**Issue by lemppari** [home-assistant/iOS#2020]
**iOS device model, version and app version**
Model Name: iPhone 13 Pro 
Software Version: 15.2
App version: 2021.12 (2021.322)

**Home Assistant Core Version**
Home Assistant 2021.12.4

**Describe the bug**
In my lovelace there is a Gauce card showing the temperature. The needle is misplaced. See attached screenshot.
**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

![Untitled](https://user-images.githubusercontent.com/28360748/146931588-6b8df926-dc66-44f9-b4ce-e97000a800a0.png)

**Comment by TomBrien** [comment]
Please see home-assistant/frontend#10910
