### ISSUE TITLE
No Host found - Connection via Synology reverse proxy not possible after  app update to version 2021.12.1

### ISSUE THREAD

**Issue by medicus07** [home-assistant/iOS#2022]
Model Name: iPhone 12 (German Location Setting)
Software Version: 15.2
Home Assistant Core Version 2021.12.3

Today I updatet to the new app version 2021.12.1.

Since then, there is no external connection via reverse proxy possible. HA docker runs on my Synology NAS, reverse proxy is configured in the Synology software. Before the update everything works fine...

Error message:
NSURLErrorDomain -1003, host not found

My URL is like this: 
https://name.synology.me:[PORT]

Configure a new server in app makes no difference.

**Comment by ProfDrYoMan** [comment]
Running the same app version, but works for me.

**Comment by medicus07** [comment]
I checked in safari, everything was working.
Another trial in the app... everthing ok. Weird.
