### ISSUE TITLE
If "launch app on login" is set, app erroneously shows window on boot

### ISSUE THREAD

**Issue by tigersoul925** [home-assistant/iOS#2025]
**Device model, version and app version**

Model Name: MacBook Pro (15-inch, 2016)
macOS Version: 11.6.2 (20G314)
App Version: 2021.266
Safari Version: irrelevant

**Home Assistant Core Version**

core-2021.12.5
**Describe the bug**
When setting macOS companion app to "launch app on login", a window is opened at boot which is not the normal behavior for apps launching at boot. They should launch with the main window hidden or not yet opened.
**To Reproduce**
Set "launch app on login" to ON and "show app in" to "menu bar". Reboot.
**Expected behavior**
App launches at boot but does not display a window until clicking the tray icon.
**Screenshots**

**Additional context**

**Comment by bgoncal** [comment]
The mac app uses "Mac Catalyst" technology, which ports iOS Apps to Mac and this is it's normal behavior, to fix that we need to migrate to native mac app. It's on the backlog but it's a huge task which I can't promise it will be done soon.
