### ISSUE TITLE
Latest IOS app always need a refresh (drag the finger down)

### ISSUE THREAD

**Issue by rhoddan** [home-assistant/iOS#2026]
**iOS device model, version and app version**

Model Name:  Home assistant IOS App
Software Version: 2021.12.5
App version: 2021.12.1

**Home Assistant Core Version**

2021.12.5
**Describe the bug**

**To Reproduce**
Very often when I start the app it’s a blank screen. I need to refresh it manually (drag finger down) or close the app and start it again
**Expected behavior**
To show the content
**Screenshots**

**Additional context**

**Comment by TomBrien** [comment]
Please see #1801
