### ISSUE TITLE
Camera in use binary sensor always on on macOS 11

### ISSUE THREAD

**Issue by parautenbach** [home-assistant/iOS#2029]
**Device model, version and app version**

Model Name: iMac (24-inch, M1, 2021)
macOS Version: macOS Big Sur 11.6
App Version: 2021.12 (2021.322)
Safari Version: 15.0 (16612.1.29.41.4, 16612)

**Home Assistant Core Version**
2021.12.5

**Describe the bug**
The sensor `binary_sensor.xxx_camera_in_use` always shows `on` and `sensor.xxx_active_camera` always shows `FaceTime HD Camera` when I'm not actively using the camera or have no apps open that uses the camera. The reason seems to be a background daemon called `appleh13camerad` running as user `_cmiodalassistants` (a built-in macOS user). I first thought it might be due to the `ChromaCam.app` which can intercept and camera stream to apply filters. I have uninstalled this application which changed nothing. The `appleh13camerad` remains. Killing it manually briefly changes the binary sensor's state to off, before the system restarts it. I suppose this daemon is necessary in some way, but there is close to no information available via Google. Regardless, it makes this sensor less useful if it's always on. 

**To Reproduce**
Open the activity monitor to check that `appleh13camerad` is running.
Check the sensor state in HA's template editor or under the states tab.
Kill the process and note the state change.  

**Expected behavior**
If this issue is due to me still being on a macOS 11.x version, there isn't any indication that an upgrade would change this. I would expect the binary sensor not to be on unless an (active) app is actually using the camera. For example, my camera light isn't on, hence I wouldn't expect HA to report the camera to be in use. 

**Screenshots**
I don't think there's any I can give that would help. 

**Additional context**
I don't think there's more I can add at this stage.

**Comment by zacwest** [comment]
Unfortunately this is a bug in the M1 hardware only, in macOS 11.

Fortunately it is indeed fixed in macOS 12: https://github.com/home-assistant/iOS/issues/1294

**Comment by parautenbach** [comment]
Thank you, Zac!
