### ISSUE TITLE
IOS guest user can see forbiden Panel in Overview

### ISSUE THREAD

**Issue by pacoso81** [home-assistant/iOS#2030]
**iOS device model, version and app version**

Model Name: 
Software Version: don't know
App version: don't know (latest, just installed)

**Home Assistant Core Version**
2021.12.5 

**Describe the bug**
I have setup multiple tabs on Overview and they are all not visible to guest users, but the IOS guest user can see only my tab whit Panel (1 card)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by TomBrien** [comment]
Please can you confirm if this happens in safari or just the app and also if your using any custom elements to achieve this or just standard Home Assistant

**Comment by pacoso81** [comment]
i have tested now on safari and on the app and the bug is now gone on both.

**Comment by TomBrien** [comment]
Glad it's fixed
