### ISSUE TITLE
issue with iOS notification and connection

### ISSUE THREAD

**Issue by lowrisk75** [home-assistant/iOS#2036]
**iPhone 12 Pro Max, 15.3 (19D5026g) Home assistant 2021.12.1 92021.327) (same issue with prod version of iOS/Home assistant)**

App 2021.12.7
Websocket connected
Local push disabled 
external IP configured (owned domain + SSL using cloud-flare + Cloudflare for team with limited DNS filtering in the VLAN where the client is)

System Health
```
version: core-2021.12.7
installation_type: Home Assistant OS
dev: false
hassio: true
docker: true
user: root
virtualenv: false
python_version: 3.9.7
os_name: Linux
os_version: 5.10.63-v8
arch: aarch64
timezone: Europe/Dublin
GitHub API: ok
Github API Calls Remaining: 5000
Installed Version: 1.18.0
Stage: running
Available Repositories: 997
Installed Repositories: 18
logged_in: false
can_reach_cert_server: ok
can_reach_cloud_auth: ok
can_reach_cloud: ok
host_os: Home Assistant OS 7.0
update_channel: stable
supervisor_version: supervisor-2021.12.2
docker_version: 20.10.9
disk_total: 57.8 GB
disk_used: 32.9 GB
healthy: true
supported: true
board: rpi4-64
supervisor_api: ok
version_api: ok
installed_addons: Samba share (9.5.1), Nginx Proxy Manager (0.11.0), MariaDB (2.4.0), File editor (5.3.3), SSH & Web Terminal (10.0.0), Node-RED (10.2.2), Z-Wave JS to MQTT (0.32.2), Z-Wave JS (0.1.51), Studio Code Server (3.7.0), Emulated HUE (0.2.10)
can_reach_server: ok
dashboards: 1
resources: 9
views: 8
mode: storage
```

**Describe the bug**
Notification are not available, also having some random issue with login on home assistant  as mentioned [here](https://community.home-assistant.io/t/daily-log-off-and-issues-with-ios-companion-app/371681)

notification are sent from node red, work with user clients when entity is changed
random result on my this mentioned clients

notification are enabled on iOS (system wild) 

Rate limits: no data
Push ID Not registered for remote notifications
> click reset : error: the operation couldn't be completed. failed to checkin before token registration.

sign out, deleting the app, redownloading, going through iOS system notification acceptance > same issue

please note that firebaselogging-pa.googleapis.com is blocked on the VLAN, which seems to be called at the same time every time I register the client

**Comment by zacwest** [comment]
You must allow the app access to Firebase for it to register for push notifications.

**Comment by lowrisk75** [comment]
Thank you, I did allow access for firebase in the VLAN but I have the same issue
I saw some activity from domain-config-1259603563.file.myqcloud.com (which seems dodgy) and device-provisioning.googleapis.com, are they required too? I don't see other blocked query during the registration, I tried 10 time in the last few minutes.

**Comment by zacwest** [comment]
myq is almost certainly not the HA app, or is from the frontend loading content. The Google API is likely one which needs to be unblocked as well. You can press the "reset" button under App Configuration > Notifications at the bottom to test whether you've stopped blocking it.

**Comment by lowrisk75** [comment]
the issue must be elsewhere then, when I click reset, I receive the error message instantaneous, no DNS query.
when I sign out / remove the app / install / I have iphonesubmissions.apple.com which is blocked, nothing else.

I'll try to use a poxy in a sec to check whatever the app is connecting too and I'll update

**Comment by lowrisk75** [comment]
I'm connecting to CloudFlare VPN to bypass DNS filtering on the local VLAN > same issue 
somehow I can now reset from the notification settings and I have a new push ID every time, even when connected on the VLAN but the notification still won't work

**Comment by lowrisk75** [comment]
It's seems like it some kind of local restriction that I missing so I'm closing since I don't have more details
