### ISSUE TITLE
Gauge card not showing needle on IOS

### ISSUE THREAD

**Issue by kyleteal** [home-assistant/iOS#2038]
**iOS device model, version and app version**
Model Name: iPhone 11 Pro Max
Software Version: iOS 15.2
App version: 2021.12.1 (2021.327)

**Home Assistant Core Version**
Server Version: 2021.12.3

**Describe the bug**
Gauge card does not display the needle properly in the iOS app. Issue is not present on Safari for iOS or on Safari for Mac. Most of the time the gauge is not displayed at all, but I noticed when it gets very low you can see it and it appears as though it is just off screen most of the time as it displays off center when low. 

**To Reproduce**
Create a gauge card and activate the needle, set max to a high number and set the gauge reading to 50 or more percent of that. 

**Expected behavior**
To see the needle centered properly.

**Screenshots**
![Untitled-1](https://user-images.githubusercontent.com/46629285/147952011-1d088250-6ec8-488c-be41-8761515910a8.png)

**Comment by ykuijs** [comment]
I noticed similar behavior:

- The needle is missing or is not placed correctly
- The fill color or the gauges is misaligned

![20220101_120007000_iOS](https://user-images.githubusercontent.com/15103891/148076949-96c74c86-d1e3-418e-848c-be1f949891ed.png)

**Comment by maciii** [comment]
Same on my iPhone 13 Pro and IOS 15.2

**Comment by abuchananTW** [comment]
I'm seeing the same problem on the MacOS, iOS, and iPadOS apps.
Using Safari or Chrome directly on the Mac works fine.
Using Safari directly on my iPhone works fine.
Using my Android tablet works fine.

Interesting, using Chrome directly on my iPhone exhibits the same problem.

Might this be an upstream issue with Home Assistant that shows up on whatever embedded web component gets used?

**Comment by shgubar** [comment]
Same issue on iPhone 12 Pro (iOS 15.2.1)
![IMG_0771](https://user-images.githubusercontent.com/75221402/149744631-31db8664-e4da-4c75-a5d1-5499f5e763d3.jpg)

This card working fine on web.

**Comment by wpfog** [comment]
Same Issue from day one with HA 12.0. Probably, display problems are not a particularly high priority for troubleshooting
<img width="332" alt="Screen" src="https://user-images.githubusercontent.com/8577342/150818638-a90444c9-4844-4016-8b53-765db9201bcc.png">
.

**Comment by jchhenderson** [comment]
it works for me when I choose a custom theme (only the default "light" and "dark" themes have the problem).

**Comment by MindGas** [comment]
Same issue here. Used to be fine in earlier versions. Not sure since which release it broke. Installed version 2021.12.1

![20220129_152326000_iOS](https://user-images.githubusercontent.com/5328862/151673123-b930e9f6-8d68-4a88-ad15-f7f80f292886.png)

**Comment by zacwest** [comment]
https://github.com/home-assistant/frontend/issues/11041
