### ISSUE TITLE
Can't connect - Shared.WebhookError 3

### ISSUE THREAD

**Issue by GerdRuetten** [home-assistant/iOS#2043]
Model Name: MacBook Pro (16", 2021) / Chip Apple M1 Pro
macOS Version: 12.1
App Version: 2021.12 (2021.322)
Safari Version: 15.2 (17612.3.6.1.6)

**Home Assistant Core Version**
core-2021.12.9

**Describe the bug**
I have installed the HA-Companion App on iPhone and iPad and it works flawlessly.
Now, i install the App on my new macBook Pro (see above) and i always get the Error Shared.WebhookError 3.
I have restart HA, but nothing helps.
If i login with this user over Safari or Chrome on this macBook, it works just as flawlessly.

**Screenshots**
Screenshots and log-files in the appendix

<redacted>

**Comment by zacwest** [comment]
It looks like the webhook request to get the config is failing, and I'm not sure why. If you feel comfortable using the command line, can you run the following? You'll need a long-lived access token from your profile, and you can run:

```bash
curl -H "Authorization: Bearer ACCESSTOKEN" http://your-server/api/config
```

You can either paste it here, or save the result to a text file and [upload here](https://www.dropbox.com/request/CtVWqILBXZ41tmFSGK2y) as it will contain some information like GPS coordinates and external/internal URL.

**Comment by GerdRuetten** [comment]
Thank you for your support!
First step: I create a long-lived access token.
Second step: on my macBook i open the Terminal and paste your curl-Command with:

curl -H "Authorization: Bearer ***my_long-lived_access_token ***" http://192.168.178.20:8123/api/config

{"latitude": 51.00623041640426, "longitude": 6.533879265189172, "elevation": 82, "unit_system": {"length": "km", "accumulated_precipitation": "mm", "mass": "g", "pressure": "Pa", "temperature": "\u00b0C", "volume": "L", "wind_speed": "m/s"}, "location_name": "Home", "time_zone": "Europe/Berlin", "components": ["cloud", "sensor.speedtestdotnet", "google_assistant", "input_text", "trace", "sensor.mobile_app", "dwd_weather", "hassio", "media_source", "sensor.systemmonitor", "config", "sensor.time_date", "switch.shelly", "stream", "counter", "frontend", "sensor.template", "group", "my", "button.shelly", "scene.hue", "dhcp", "automation", "binary_sensor.cloud", "notify", "websocket_api", "cover.shelly", "search", "weather.dwd_weather", "tts.cloud", "notify.mobile_app", "zone", "binary_sensor.updater", "logger", "rki_covid", "device_automation", "system_health", "zeroconf", "mobile_app", "default_config", "binary_sensor.hue", "sensor", "button", "input_number", "energy", "tag", "updater", "input_boolean", "switch.hue", "sensor.hassio", "webhook", "sensor.dwd_weather", "homeassistant", "binary_sensor.hassio", "script", "person", "device_tracker.mobile_app", "binary_sensor.shelly", "map", "switch", "sensor.shelly", "homekit", "tts", "sensor.qnap", "system_log", "camera", "weather", "hacs", "template", "ssdp", "persistent_notification", "timer", "sensor.devolo_home_network", "stt", "scene.homeassistant", "http", "shelly", "sensor.hacs", "analytics", "tts.google_translate", "devolo_home_network", "auth", "network", "sun", "recorder", "rpi_power", "usb", "light.shelly", "blueprint", "speedtestdotnet", "light.hue", "input_datetime", "image", "light", "binary_sensor", "lovelace", "binary_sensor.mobile_app", "input_select", "binary_sensor.rpi_power", "sensor.hue", "ffmpeg", "hue", "onboarding", "sensor.rki_covid", "api", "logbook", "history", "scene", "sensor.energy", "device_tracker", "cover"], "config_dir": "/config", "whitelist_external_dirs": ["/media", "/config/www"], "allowlist_external_dirs": ["/media", "/config/www"], "allowlist_external_urls": [], "version": "2021.12.9", "config_source": "storage", "safe_mode": false, "state": "RUNNING", "external_url": null, "internal_url": null, "currency": "EUR"}

**Comment by zacwest** [comment]
I don't see anything wrong there that would be causing an issue, but it could be something else in the middle like a reverse proxy. Can you describe your HA setup? Do you have a reverse proxy set up like nginx/caddy, or anything special?

**Comment by GerdRuetten** [comment]
I think, i have no specials.
I install HA on an raspberry PI 3b. 
The PI is connected to my local network. 
And i use the Cloud-Intigration (trial) from Nabu Casa.

Sorry for my bad english - my german is better ;-)

**Comment by GerdRuetten** [comment]
After that, i tested the connect from the App.

What should i say ... it works.

I don't know why.

Would you close the issue?

**Comment by zacwest** [comment]
Glad it started working, wish I could pin down why it wasn't.

**Comment by vanlooverenkoen** [comment]
I updated home assistant to the latest version as described here #2195
