### ISSUE TITLE
IOS Companion App does not request access to camera

### ISSUE THREAD

**Issue by orandasoft** [home-assistant/iOS#2049]
The zwavejs2mqtt allows to scan the S2 QR code, but the HA iOS companion app does not request access to the camera nor has the ability to grant access in Settings > Home Assistant.

As a result zwave2mqtt is unable to scan the QR code.

**Comment by bgoncal** [comment]
Are you trying to access the camera from a non secure environment? (non-https)? If so, thats the issue, webviews can't use camera through http.
Closing this issue since it's quite old but let me know in case I should reopen

**Comment by heindrichpaul** [comment]
@bgoncal I am experiencing the same problem but I do use a https connection to my server. I have deleted the server from the app reinstalled it etc but the camera permission is not requested. I also have an Android so I know when you try to add a Matter device you can scan the QR and that works but on iOS the app "crashes" and reloads the default dashboard. Almost like an exception is thrown and not caught when trying to access the camera.

**Comment by bgoncal** [comment]
Matter flow uses Apple commissioning flow, not handled by the App, so no need for camera permission.
The only place I can remember where camera permission is used is the add zwave device flow.

**Comment by bgoncal** [comment]
It's possible that because zwave2mqtt is presented in sort of an "iframe", that the camera permission/request is not relayed to the main app
