### ISSUE TITLE
No Focus Update on iPhone 13 MAX

### ISSUE THREAD

**Issue by Schlauwi** [home-assistant/iOS#2057]
I have a problem since the update to Home Assistant 2021.12. on my iPhone 13 MAX. Before the update, the Focus Sensor would display correctly when I had a Focus turned on. Since the update, no Focus state is updated on my iPhone 13 MAX. The sensor always shows "off". However, on an iPhone 12 Pro, the Focus state is correctly displayed as "on". I have tried and checked everything possible - all settings are the same. Uninstalling and reinstalling the Home Assistant app did nothing either.

**Comment by davidolrik** [comment]
I also have this issue on `2022.2.9` on a iPhone 10SX Max.

**Comment by davidolrik** [comment]
Just found this in the docs that might explain the behaviour I'm seeing:

## Sensor List

| Sensor | Attributes | Description |
| --- | --- | --- |
| binary_sensor.focus | None | Whether focus is currently enabled. Requires iOS-2021.10 or later, macOS 12 update later this year. Will not work if Home Assistant is in the "Allowed Notifications" list, see [interruption level](https://companion.home-assistant.io/docs/notifications/notifications-basic#interruption-level) for more. |

I removed Home Assistant from the "Allowed Notifications", and my Focus is now updating as it should.
But now I'm not getting any notifications from Home Assistant when a focus is active.

So maybe this should be filed as a bug for not updating focus when Home Assistant is in the "Allowed Notifications" list?

**Comment by bgoncal** [comment]
This looks more like a coincidence, can you reproduce it consistently when you remove or add HA from allowed notifications?
Focus won't update right away always, background app refresh (when the focus updates is updated) happens periodically and defined by iOS, if you enable "Local push" it keeps a connection open in background between HA and the iPhone (consumes more battery) and then updates more often

**Comment by bgoncal** [comment]
I just noticed this is from 2022, it could also be a bug in iOS, can you still reproduce it?

**Comment by bgoncal** [comment]
Im closing it for now but feel free to reopen anytime if needed
