### ISSUE TITLE
Three-finger swipe between servers doesn't work on macOS

### ISSUE THREAD

**Issue by deviantintegral** [home-assistant/iOS#2059]
**Device model, version and app version**

Model Name: MacBook Pro (16-inch, 2019)
macOS Version: 12.2
App Version: 2021.345
Safari Version: 15.3

**Home Assistant Core Version**
2021.12.10

**Describe the bug**
The app says to use a three-finger swipe to switch servers, which works fine in the iOS app. However, on the macOS app nothing happens. It looks like by default that gesture is bound to switching between full-screen apps and multiple desktops, but even disabling that doesn't make it work.

**To Reproduce**

Set up multiple servers and try to switch using a trackpad with three fingers left or right.

**Comment by daytonturner** [comment]
Seems like there should be a macos specific hotkey introduced to switch servers.  Right now the only way I can figure to actually switch is to go the long way through the preferences menu.

**Comment by bohtho** [comment]
This has now been broken per february 2022 as per issue creator, probably longer. Should get a slightly higher priority to get fixed, or the swipe instructions should just get removed from the mac app.

**Comment by deviantintegral** [comment]
I noticed that on iPads it's actually possible to have multiple server windows open at the same time. Create a new window, which will show the same server twice, and then switch one of them using the gesture.

Knowing the code is shared, I think this would be even more "mac like" to support multiple windows. If they are closed, I would generally expect `CMD+#` to open different server windows again, likely with servers listed in a "Window" menu.

**Comment by jbishop129** [comment]
Stil an issue as of Dec 2022. Has anyone figured out any other way to switch between configured servers, other than Preferences -> Servers -> choose desired server -> Activate ? Super easy in iOS, iPadOS, but macOS the three-finger swipe is not an option.

**Comment by deviantintegral** [comment]
I actually discovered you can have multiple Home Assistant windows open on macOS! I'm on the beta channel in case this was something I added.

There's "New" listed under the File menu. That will give you two identical windows. Then, open preferences and switch servers. It will change the window you just opened. Then, just never close them. They'll even both open when reopening the whole app.

This is totally not discoverable, and I think it would make sense to have "Servers -> <list of servers>" as a top-level menu or under File. But, it works well enough once you figure it out.

**Comment by timr49** [comment]
The "Window" menu already is a top level menu that switches between windows created with File/New. A problem with it is that it names all of the windows on its list as "Home Assistant" so knowing which one to select requires trial and error (or a good memory).  A solution could be to use the name configured in Settings/System/General/Name instead of "Home Assistant".

**Comment by bgoncal** [comment]
Closing this issue since macOS is not planned to support 3 fingers gesture anymore, it conflicts too much with other mac gestures.
