### ISSUE TITLE
Home zone detection with overlapping zones [Privacy: zone names only] only the largest zone is sent. 

### ISSUE THREAD

**Issue by MauiR** [home-assistant/iOS#2064]
**iOS device model, version and app version**

Model Name: iPhone 12 mini
Software Version: iOS 15.3
App version: 2022.2

**Home Assistant Core Version**

core-2022.2.1

**Describe the bug**
If you select the new privacy feature Location Sent [Zone name only] in the settings of the iOS APP.
The largest zone in which you are located is sent to Home Assistant. If you have the home zone in a larger zone, it is not recognized that you are at home. 
If you choose the setting [Exact]
The home zone is always prioritized, even if a smaller zone is placed in the home zone.

Regardless of the home zone, [Zone name only] always prioritizes the largest zone, while [Exact] always prioritizes the smallest. I think this should be consistent. 

**To Reproduce**
- Draw a larger zone around your home zone
- Set your GPS location at home.

Select the setting [Zone name only] in the iOS app:
The larger zone will be detected.

Select the [Exact] setting in the iOS app:
The home zone will be detected.

- Create any 2 zones that overlap.
- Place your GPS in both zones

Select the setting [Zone name only] in the iOS app:
The larger zone will be detected.

Select the setting [Exact] in the iOS APP:
The smaller zone will be detected.

**Expected behavior**
It would be expected that the home zone is always detected or that the behavior is consistent. Always the largest or always the smallest zone. 

**Screenshots**

**Additional context**

**Comment by zacwest** [comment]
Looks like the difference in logic between core and the app is core is comparing zone centers for closeness, and the app is comparing perimeters for closeness. Should be an easy fix.
