### ISSUE TITLE
Opening Logbook produces ":0:0 Script error"

### ISSUE THREAD

**Issue by darootler** [home-assistant/iOS#2067]
**iOS device model, version and app version**

Model Name: iPhone 11
Software Version: 15.3
App version: 2021.12.1 (2021.327)

**Home Assistant Core Version**

core-2022.2.2

**Describe the bug**
The error "[frontend.js.latest.202202030] :0:0 Script error." is logged everytime i hit Logbook on the companion app. This error is not logged if i hit Logbook on a PC running Chrome browser

**To Reproduce**
Open Home Assistant companion app, click on Logbook

**Expected behavior**
No errors are logged or produced

**Screenshots**

**Additional context**

2022-02-05 08:42:34 ERROR (MainThread) [frontend.js.latest.202202030] :0:0 Script error.

Let me know if i can provide further information

Regards
Richard

**Comment by zacwest** [comment]
This error appears to be:

> ResizeObserver loop completed with undelivered notifications.

https://github.com/home-assistant/frontend/issues/11079
