### ISSUE TITLE
App expresses emotional connections

### ISSUE THREAD

**Issue by mppkll** [home-assistant/iOS#2070]
![AECDDECF-69BA-4230-8005-4871BCE5F4FE](https://user-images.githubusercontent.com/98370621/152896816-90d5bc05-e561-45f9-a267-3ce860ead925.png)

Sorry, I’m happily married.

Not sure if this is a easter egg or someone left some debugging code in the release.  This happens when you touch close to the “Done” button but not quite on it.

**Comment by zacwest** [comment]
Yes, this is an easter egg, though it would be a good idea to add a 'copy' action to this alert for copying the version numbers.
