### ISSUE TITLE
Scrolling doesn't work with iOS betá 15.4

### ISSUE THREAD

**Issue by treb33** [home-assistant/iOS#2082]
**iOS device model, version and app version**

Model Name: Apple iPhone 12 Pro
Software Version: 15.4 (19E5219e)
App version: 2022.345

**Home Assistant Core Version**
2022.2.6

**Describe the bug**
Scrolling in Automations & Scenes doesn't work after update to iOS 15.4 betá. Its only in Automations, scripts or scenes

**To Reproduce**
Update to iOS 15.4 betá and try to scroll in Automations, scripts or scenes

**Expected behavior**
That scrol works..

**Screenshots**

**Additional context**

**Comment by treb33** [comment]
Also not in the helpers section

**Comment by zacwest** [comment]
https://github.com/home-assistant/frontend/issues/11495
