### ISSUE TITLE
Markdown card server navigation not working

### ISSUE THREAD

**Issue by TyzzyT** [home-assistant/iOS#2097]
**iOS device model, version and app version**
Model Name: iPhone SE
Software Version: 15.3.1
App version: 2022.2 (2022.345)

**Home Assistant Core Version**
2022.2.9

**Describe the bug**
When using the Lovelace card markdown and trying to use the URL homeassistant://navigate in it, it's not doing anything.

**To Reproduce**
Create a Lovelace card with the following parameters:
```
type: markdown
content: >-
  This [URL title](homeassistant://navigate) isn't working
```

**Expected behavior**
iOS app to open the server nagivation panel to select a different server. Ideally I'd like to go to the other server directly, but a pop-up would also be nice.

**Comment by bgoncal** [comment]
I just tested and it does not look something App related, I created the same markdown on my side and after inspecting the HTML the link was not there, manually adding the link made it work, so I would say you should report this to Core to check why this link is not working.
