### ISSUE TITLE
scrollbar thumb wrong color with dark theme 

### ISSUE THREAD

**Issue by peledzius** [home-assistant/iOS#2104]
**iOS device model, version and app version**

Model Name:  iPhone 6s
Software Version: 15.3.1
App version: 2022.358

**Home Assistant Core Version**

2022.3.7

**Describe the bug**

Scrollbar thumb is in wrong color with default dark theme. It's almost invisible in Lovelace with black background.

**To Reproduce**

Try scrolling in Configuration page, or where all content can't fit. 

**Expected behavior**

Looking fine in Safari:

https://user-images.githubusercontent.com/24360494/160882094-2d9d5110-49ee-46ab-b876-1392c435465b.MOV

**Screenshots**

https://user-images.githubusercontent.com/24360494/160882074-e8d2e37e-07f2-44cf-905b-6eb885486aa0.MOV

**Additional context**

**Comment by bgoncal** [comment]
That is the default iOS behavior
Let me know if you feel like I should reopen
