### ISSUE TITLE
Client Certificate support

### ISSUE THREAD

**Issue by JamesWP** [home-assistant/iOS#2111]
At home I run many applications on my home server and provide remote access with nginx acting as a reverse proxy.

When doing this i like using X509 Client Certificates to add an extra layer of security, in addition to whatever the application supports.

When using HA behind a reverse proxy like this, the IOS application is unable to function. I'm not sure how Client certs work 100% within an application like HA, but safari for example supports the use of client certs and i can access HA via that.

**Comment by zacwest** [comment]
https://github.com/home-assistant/iOS/discussions/1788
