### ISSUE TITLE
App ignores time zone and displays everthing in UTC

### ISSUE THREAD

**Issue by drcryogen** [home-assistant/iOS#2116]
**iOS device model, version and app version**

Model Name: iphone 8
Software Version: 14.1
App version: 2022.358

**Home Assistant Core Version**
2022.4.3

**Describe the bug**
All plots and time series information are not displayed using the time zone setting. Plots are displayed in what appears to be UTC regardless of the time zone set. This impacts the Energy dashboard, history plots, entity histories etc. It appears that the app is simply ignoring the time zone information sent by HA.

The web interface (via safari on iOS) displays the data properly, so this behavior appears to be isolated to the app. The data are also displayed properly when checked from MacOS using Safari and Firefox. So it appears the app is simply ignoring the timezone data that HA is sending.

**To Reproduce**
Examine any history plot and compare time signature against local time. See screenshots.

**Expected behavior**
Time zone should be honored and time series information should display in local time.

**Screenshots**
![IMG_6730](https://user-images.githubusercontent.com/22484754/164915977-a0fa30ce-af0e-4847-ba24-b007e5836e81.PNG)
![IMG_6728](https://user-images.githubusercontent.com/22484754/164915991-0b849241-2ae5-4bf1-bf6b-87ffb2b56c21.PNG)
![IMG_6729](https://user-images.githubusercontent.com/22484754/164915996-3bf9c2be-5f7c-4ec9-bcc4-ac25c520421b.PNG)
![IMG_6731](https://user-images.githubusercontent.com/22484754/164916002-fa227b5
![IMG_6733](https://user-images.githubusercontent.com/22484754/164916010-244060a3-690e-4daa-a35d-28b26e62caed.PNG)
7-d6fb-480a-ad58-51f24019b91c.PNG)

**Additional context**

**Comment by drcryogen** [comment]
Update: On additional digging it is possible to make the app display the data correctly. So this bug is more subtle than my initial report implied. Will do additional testing and post back with any updated information.

**Comment by bgoncal** [comment]
Is this still an issue with latest versions of app and core? Feel free to reopen if needed
