### ISSUE TITLE
App Not Showing Dashboard On iPad Mini 2

### ISSUE THREAD

**Issue by BarryBennett** [home-assistant/iOS#2118]
When starting the companion app on the iPad Mini 2 the app often gets stuck on the screen with the HA icon in the center and the configuration gear icon in the lower right.  You can click on the gear icon and it seems you are connected to the server but the dashboard never appears.  If you swipe down on the screen with the HA icon in the center (like you want to refresh the page) you can often get it to move onto the dashboard view after a few seconds.  In between swiping down and the dashboard appearing there is a brief time when some text appears that says something about loading data.  If you do not swipe down to refresh the screen the dashboard never appears.  The problem is not 100% consistent as sometimes the dashboard will appear right away with no need to do the refresh.  The iPad Mini 2 to is up to date with the latest iOS it supports which is 12.5.5.  Based on other user feedback this does not seem specific to the Mini 2 model but more tied to iOS version as some other older iPad models seem to have a similar problem.

**Comment by zacwest** [comment]
https://github.com/home-assistant/frontend/issues/10885
