### ISSUE TITLE
Binary sensor for microphone is turning on when playing any media

### ISSUE THREAD

**Issue by fzellner** [home-assistant/iOS#2130]
**Device model, version and app version**

Model Name: MacBook Pro M1
macOS Version:  macOS Monterey 12.3.1
App Version: 2022.3 (2022.358)
Safari Version: 15.4 (17613.1.17.1.13)

**Home Assistant Core Version**
2022.5.4

**Describe the bug**
When playing any media, the binary sensor for the microphone is turning on.

**To Reproduce**
Play any media in Youtube, Spotify or Apple Music

**Comment by derN3rd** [comment]
Have the same issue with any media on Firefox

**Device model, version and app version**

Model Name: MacBook Pro (2019)
macOS Version: macOS Big Sur 11.6.8
App Version: 2022.3 (2022.358)

**Home Assistant Core Version**
2022.8.2

**Describe the bug**
When playing any media, the binary sensor for the microphone is turning on.

**To Reproduce**
Play any media in Firefox, Youtube, Spotify etc. Also I'm using the same Media Device for Input/Output (Usb Soundcard) if thats relevant

**Comment by bgoncal** [comment]
Can't reproduce, perhaps it was fixed at some point since originally reported, let me know in case I should reopen
