### ISSUE TITLE
No Back option after clicking a hyperlink on the map

### ISSUE THREAD

**Issue by maurits-h** [home-assistant/iOS#2145]
**iOS device model, version and app version**
Model Name: iPhone 12 Pro Max
Software Version: 15.5
App version: 2022.3 (2022.358)

**Home Assistant Core Version**
Home Assistant Core 2022.6.0

**Describe the bug**
The app does not offer the possibility to go back after clicking a hyperlink on the map.

**To Reproduce**
1. Open the map
2. Click on a person
3. Click on the OpenStreetMap hyperlink in the lower right corner
4. The link is opened in the app and there's no way to go back to the map. Pulling down to refresh the screen reloads the home screen.

**Expected behavior**
The app should offer a Back option.

**Comment by bgoncal** [comment]
App has no control over content presented inside the webview (what the app presents is the same as in the browser), I believe this needs to be fixed by the frontend instead since they are the ones that provide all back buttons, please open an issue there.
