### ISSUE TITLE
Unable to save changes in the mobile app

### ISSUE THREAD

**Issue by pittbull** [home-assistant/iOS#2150]
**iOS device model, version and app version**
Model Name: Iphone 13 Pro Max
Software Version: 15.5
App version: 2022.3 (2022.358)

**Home Assistant Core Version**
HA Core: 2022.6.7

**Describe the bug**
When trying to edit various fields in the app, the changes are not saved. I have tried the following:

- Settings->People
- Select person
- Remove/add Tracking device
- Update

Changes are not saved.

- Dashboard->Edit dashboard->Edit card
- Remove/add entity

Changes are not saved.

**To Reproduce**
As described.

**Expected behavior**
Changes to be saved.

**Additional context**
When trying the same operations from a web browser the changes are saved.

**Comment by jflattery** [comment]
I'm also experiencing the same issue with the following:
iOS 15.5 on a iPhone 12 Pro Max
app version: 2022.6 (2022.375)
Home Assistant 2022.7.7
Supervisor 2022.07.0
Operating System 8.4
Frontend 20220707.1 - latest

**Comment by bgoncal** [comment]
Is this still an issue with latest versions of app and core? Feel free to reopen if needed
