### ISSUE TITLE
Drop low accuracy GPS data

### ISSUE THREAD

**Issue by imuncas** [home-assistant/iOS#2156]
Hi,
On the Android seems to be a feature to set a minimum gps_accuracy for location updates. Can the same be implemented in the IOS as well? The data seems to be known, on the home assistant the gps_accuracy is reported and looks correct.
For example, when I'm in a train there is no good GPS coverage, and the accuracy is very low. (>1000) Because of this, I'm reported to be at home already from the train station although thats still quite far from home.

**Comment by simphide** [comment]
I also have the sam problem

**Comment by bgoncal** [comment]
Since the feature does not exist in iOS please request it through Home Assistant Community, GitHub is used only to track bugs.

I'm cleaning open old issues, so I'll be closing this for now, let me know if you believe this should be reopened.
