### ISSUE TITLE
When automations run, the automation "submenu" is closed

### ISSUE THREAD

**Issue by Fulladorn** [home-assistant/iOS#2162]
**iOS device model, version and app version**

Model Name: iPhone 13
Software Version: iOS 15.5
App version: 2022.3

**Home Assistant Core Version**

2022.7.6

**Describe the bug**
When you are in the Automations screen (Settings > Automations & Scenes) and an automation is triggered, if you have a submenu open for an automation (the 3 dots), it will immediately close.

**To Reproduce**
Go to the Automations screen (Settings > Automations & Scenes) and press any of the 3 dots next to an automation. Trigger an automation while you remain on that screen on your device.

**Expected behavior**
The submenu should remain opened.

**Screenshots**

**Additional context**

This is problematic because if automations are running often (multiple per second, etc.), it makes it difficult to open and potentially edit an automation.

**Comment by bgoncal** [comment]
What the app presents is the same as the browser, this means it's a frontend issue, please report to the correspondent repository instead.
