### ISSUE TITLE
History-graph wont show graph (but does show the popup per entity)

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/iOS#2171]
**iOS device model, version and app version**

Model Name: 13Pro
Software Version: 15.6
App version:  2022.358

**Home Assistant Core Version**

<img width="433" alt="Schermafbeelding 2022-08-06 om 12 43 05" src="https://user-images.githubusercontent.com/33354141/183245574-62469873-9d89-40fe-9a6d-3b6a1b353cd2.png">

**Describe the bug**

as title, one knows the graph is there, because of the popups that do show when touching/hovering

<img width="1034" alt="Schermafbeelding 2022-08-06 om 15 15 40" src="https://user-images.githubusercontent.com/33354141/183250615-4e80bba9-03ea-4d85-9aa6-1bc95ea32509.png">

**To Reproduce**
```
    - type: entities
      title: History include all domains
      entities:

        - type: custom:auto-entities
          card:
            type: history-graph
            hours_to_show: 12
          filter:
            include:
              - domain: "*"
```

shows fine on desktop, but nothing on Mobile
**Expected behavior**

**Screenshots**

<img width="1429" alt="Schermafbeelding 2022-08-06 om 12 44 51" src="https://user-images.githubusercontent.com/33354141/183245624-406fb7f1-72a4-4725-b458-67ebc0f2716d.png">

**Additional context**

this is to replace the legacy history panel, showing all recorded entities:
```
- title: History auto
  path: history-auto
  icon: mdi:history
  panel: true
  cards:

    - type: entities
      title: History include all domains
      entities:

        - entity: input_number.history_span

        - type: custom:hui-element
          card_type: entities
          card_mod:
            style: |
              ha-card {
                box-shadow: none;
              }
              .card-content {
                max-height: 700px;
                overflow-y: scroll;
              }
          entities:
            - type: custom:config-template-card
              entities:
                - input_number.history_span
              variables:
                span: states['input_number.history_span'].state
              card:
                type: custom:auto-entities
                card:
                  type: history-graph
                  hours_to_show: ${span}
                  card_mod:
                    style: |
                      ha-card {
                        box-shadow: none;
                        margin: 8px -16px 0px -16px;
                      }
                filter:
                  include:
                    - domain: "*"

```

but as posted, the abridged version without the embedding cinfig-template-card doesn't work either.

**Comment by TomBrien** [comment]
As I understand it, you're having this across all mobile views (I.e. in browsers and the app). That means it's a frontend issue not with the app. However, as this is an issue with a custom card. You should raise it with the developer of the card.

**Comment by Mariusthvdb** [comment]
No, this is only happening in Mobile. Both iPhone and the Mac App.

Desktop Safari, Chrome, Firefox) is showing just fine.

Please reopen.

**Comment by Mariusthvdb** [comment]
This is the reason: https://discord.com/channels/330944238910963714/551871772484698112/1005506166106898442

As just explained by Zac:

ios has a maximum image texture size that it enforces and the history page exceeds it. mac in catalyst mode copies this.

**Comment by TomBrien** [comment]
Does it also happen in safari etc. on iOS

**Comment by Mariusthvdb** [comment]
didnt test yet, bu Zac's remark mad it clear as to the why.
I did add a domain selector to the config, and now that works alright. Ofc, Its no longer a 'show all', but apparently thats a no-can-do, so I wont pursue.

thx anyways.
