### ISSUE TITLE
Apple Watch complications - template is not correctly applied on automatic/background update

### ISSUE THREAD

**Issue by McTristan** [home-assistant/iOS#2179]
**iOS device model, version and app version**

Model Name: Apple Watch 6 
Software Version: 8.7
App version: 2022.3

**Home Assistant Core Version**

2022.8.4

**Describe the bug**
I've added a multiline, corner complication which shows 2 different numbers.

I'm using a template like this to format the output (it is a float number / raw value which might have many digits):

{{ states ("sensor.energy_delivered_today")| round(2)}}

It shows correctly in the preview and correctly on the watch.

However, when the HomeAssistant app updates the value every 15 minutes (or so) it shows the value without any format being applied (i.e. instead of 18.20 it shows 18.20000003434 and so on).

When I remove the | round(2) part it also shows the value in full length in the preview and on the watch when manually updating it.

I guess the template is right (as it works both in the preview and when manually updating the complication).

I can work around the issue by creating a new state based on a template for each value I would like to show there but it seems a bit overkill.

**To Reproduce**

**Expected behavior**
The template should work in every situation.

**Screenshots**

**Additional context**

**Comment by zacwest** [comment]
I'm guessing even a rounded floating point number, to Python, is still a floating point number and the result it gives to the app is a number. Try adding another character to the text, like ° at the end or something. Does that fix the rounding?

**Comment by McTristan** [comment]
Good thinking. It indeed seems to solve the problem.
