### ISSUE TITLE
Received invalid response from Home Assistant

### ISSUE THREAD

**Issue by skonagaya** [home-assistant/iOS#2195]
**iOS device model, version and app version**

Model Name: iPhone 11 Pro
Software Version: 15.6.1
App version: 2022.8

**Home Assistant Core Version**

Home Assistant 0.115.6 (Container)

**Describe the bug**
I get "Failed to Connect Shared.WebhookError 3" after logging into my Home Assistant login page thru the iOS HA app. Everything was working fine before I switched from wireless to wired internet connection. The app kicked me out of my session on my phone and I've been receiving the error ever since.

I'm able to login fine on safari/chrome using iOS/PC. Doesn't work thru the app using iPhone/iPad.

I tried removing and re-running my container. Tried pulling the latest container. Tried rebooting. Tried reinstalling the app on my iPhone. Nothing seemed to help.

_home-assistant.log_ shows:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/webhook/__init__.py", line 96, in async_handle_webhook
    response = await webhook["handler"](hass, webhook_id, request)
  File "/usr/src/homeassistant/homeassistant/components/mobile_app/webhook.py", line 185, in handle_webhook
    webhook_payload = _decrypt_payload(config_entry.data[CONF_SECRET], enc_data)
  File "/usr/src/homeassistant/homeassistant/components/mobile_app/helpers.py", line 80, in _decrypt_payload
    message = decrypt(ciphertext, key)
  File "/usr/src/homeassistant/homeassistant/components/mobile_app/helpers.py", line 45, in decrypt
    return SecretBox(key).decrypt(ciphertext, encoder=Base64Encoder)
  File "/usr/local/lib/python3.8/site-packages/nacl/secret.py", line 130, in decrypt
    plaintext = nacl.bindings.crypto_secretbox_open(ciphertext,
  File "/usr/local/lib/python3.8/site-packages/nacl/bindings/crypto_secretbox.py", line 77, in crypto_secretbox_open
    ensure(res == 0, "Decryption failed. Ciphertext failed verification",
  File "/usr/local/lib/python3.8/site-packages/nacl/exceptions.py", line 68, in ensure
    raise raising(*args)
nacl.exceptions.CryptoError: Decryption failed. Ciphertext failed verification
```
**Screenshots**

![IMG_6085](https://user-images.githubusercontent.com/1175459/187352443-4f99e2aa-ff04-4c7e-932e-845567d000cd.PNG)

**Comment by zacwest** [comment]
0.115.6 is pretty old, it's possible #2095 (which fixed an issue with the encryption) broke communicating to versions this old. I believe it should still work if you set up the app via picking a server from the list rather than from typing in the URL manually, does that work for you?

**Comment by skonagaya** [comment]
@zacwest Updating to the latest version resolved my issue. Thank you!

I was using the same refresh token for a very long time so I'm guessing the need to upgrade was dormant. When I touched the network settings it broke the iOS app session and forced me to renew the token which HA didn't allow till I upgraded.

**Comment by vanlooverenkoen** [comment]
Installed the latest home assistant version and the issue was resolved. I was still using 2021.12.x
