### ISSUE TITLE
No camera stream with iOS 16 in notifications

### ISSUE THREAD

**Issue by yan14** [home-assistant/iOS#2201]
The camera stream and still image is missing with iOS 16. 
The automation looks the same as in the documentation:
`service: notify.mobile_app_<your_device_id_here>
data:
  message: Motion Detected in the Living Room
  data:
    entity_id: camera.living_room_camera`

**Comment by TomBrien** [comment]
I can't reproduce this in iOS 16. Camera streams seem to be. Are you receiving the notification at all? If not, you may be running into the issue described [here](https://companion.home-assistant.io/docs/troubleshooting/faqs#ios-16-device-name-missing-from-notify-service-andor-entities).

**Comment by yan14** [comment]
Yes I get a notifiaction, but there is no stream and still image:
![grafik](https://user-images.githubusercontent.com/46852850/189883646-1353bf2e-a5b1-4153-b846-5ab6a953e54b.png)

My automation looks like this:
`  - service: notify.notifyfamily
    data:
      message: Hier das Bild
      title: Es hat jemand geklingelt
      data:
        entity_id: camera.einfahrt_camera`

**Comment by TomBrien** [comment]
Please can you repost the service call you're using correctly formatted as you have it in your automation (with line breaks an indents as used)

**Comment by TomBrien** [comment]
Also, it looks like you're using a notify group, is this correct? If so, can you try targeting a single device.

**Comment by yan14** [comment]
sorry for the wrong format. It should be formated properly now :)

```
service: notify.mobile_app_yannicks_iphone
data:
  message: Hier das Bild
  title: Es hat jemand geklingelt
  data:
    entity_id: camera.einfahrt_camera
```

In the case above, i used my single device as a target and not the group. The result is the same.

**Comment by yan14** [comment]
So, I changed the name in the app and now it works fine... The strange thing is, that the notification worked, but not the camera. Therefor this issue is fixed :)
