### ISSUE TITLE
IOS App Not Preserving Device Name - Creating Generic Mobile App Entries

### ISSUE THREAD

**Issue by dlindnegm** [home-assistant/iOS#2203]
Model Name: iPhone 11
Software Version:  IOS 16.0
App version: 2022.8 (2022.387)

**Home Assistant Core Version**
2022.9.4

**Describe the bug**
If I log out of the IOS Companion App and log back in it creates a new generic iPhone entry in the Mobile App Integration.  With 3 iPhones it makes it difficult to know which device is which for purposes of device_tracker and and notifications.  

**To Reproduce**
Starting with no Mobile App Integration, download & install IOS Companion App & Log in.  A new entry is created in the Integration named a generic "iPhone" instead of the actual name of the iPhone which is "Davids iPhone".  All Entities created are also named a generic "sensor.iphone_xxxx" instead of the appropriate "sensor.davids_iphone_xxx".  Proceeded to rename the entry in the Integration from "iPhone" to "Davids iPhone" and also renamed the Device from "iPhone" to "Davids iPhone".  Accepted the prompt to rename all Entities, and it successfully renamed those to "sensor.davids_iphone_xxx".   Restart HA and everything remains in the correct state, but as soon as I log out of the HA IOS App and log back in it renames the entry back to a generic "iPhone" and all Entities have also reverted back to the generic "sensor.iphone_xxxx".

**Expected behavior**
HA Device and Entities should pick up the name of the iPhone from Settings - General - About.  
Companion App should also pick up the Device Name from the iPhone Settings.
Companion App should preserve a manually entered Device Name after a logout/login.

**Additional context**
Setting the Device Name in the Companion App doesn't seem to have any effect on what the Device or Entities are named in HA.  In fact, if I change the Device Name in the Companion App from the generic "iPhone" to "Davids iPhone", it remains until I log out of the  app and then reverts back to generic "iPhone".  This seems to have started before the upgrade to IOS 16 - I believe I was at 15.6 when I first noticed it.  I'm was using DuckDNS for external access along with NGINX, as well as 2-factor authentication and Trusted Networks, but I can reproduce this with all of those disabled.

**Comment by jsiemek** [comment]
This is a known issue. Please see #2148 or the instruction [here](https://companion.home-assistant.io/docs/troubleshooting/faqs/#ios-16-device-name-missing-from-notify-service-andor-entities)

**Comment by dlindnegm** [comment]
I only have one server listed as "Home".  If I change the device name there and reload the integration before I log out of the app it only changes the name of the Device, but leaves the name of the Integration entry as the generic "iphone" and all of the entities with the generic "sensor.iphone_xxxx".  Reloading the integration also doesn't generate the prompt to rename all of the entities like it does when you rename it manually.  I can manually rename the device and it does prompt to rename all of the entities.  But this only lasts until the next time you log out/in on the IOS app - then it all reverts back to the generic entity names.  Am I missing a step here?

**Comment by dlindnegm** [comment]
It seems like with the IOS 16 changes the Device Name in the Companion App should just be removed, since it's no longer allowed access.  And HA itself would need to be updated to allow a manual rename after the device is added, but once added and renamed it should no longer revert back based on the Companion App sending it the generic 'iPhone' name after a logout/login.

**Comment by rickschrader** [comment]
> > This is a known issue. Please see #2148 or the instruction here
> 
> Those instructions are worthless cause they don't work.

After you set the device name on each device's settings, remove the Mobile App integration for that device within HA. Then, close the HA mobile app, reopen it, then refresh the integrations page in HA. This worked for me.

**Comment by bgoncal** [comment]
Is this still an issue in 2024? Let me know and I will reopen it
