### ISSUE TITLE
Mobile app: iOS 16 with default device naming "iPhone" constantly breaks mobile app integration by creating redundant instances of same server

### ISSUE THREAD

**Issue by bcutter** [home-assistant/iOS#2206]
### The problem

Since updating to iOS 16, even after renaming the device in the mobile app --> server settings from the default "iPhone" to the former/correct name, app and integration only sporadically match:

Frequently the default device name and entities are pushed to HA. Only occasionally the right name matches.
It feels like a constant battle between the mobile app and the integration switching from `iPhone` to `Custom iPhone Name`.

![grafik](https://user-images.githubusercontent.com/13799156/190864285-31e6c30f-38ea-4ef1-8ada-420fed905f1b.png)

Without having created them in the app (only renamed the default "iPhone" name of the mobile app integration) now I have the same server connection multiple times in the mobile app settings:

![grafik](https://user-images.githubusercontent.com/13799156/190864658-a83ac568-6d07-4e22-bf54-3561b2419e88.png)

1) with my custom device name
2) with the default device name `iPhone`
3) with my custom device name

### What version of Home Assistant Core has the issue?

core-2022.6.7

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Mobile App (Companion App)

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/mobile_app

### Additional information

Already tried multiple times:
- logging off from and on to the app
- renaming the device in the mobile app server settings
- renaming the integration name in HA devices & integrations settings

Basically everything noted at https://companion.home-assistant.io/docs/troubleshooting/faqs/#ios-16-device-name-missing-from-notify-service-andor-entities had no permanent success.

storage entity example:
![grafik](https://user-images.githubusercontent.com/13799156/190864080-e41b91e3-07ca-4d4f-a9ac-7193815e863b.png)

focus entity example:
![grafik](https://user-images.githubusercontent.com/13799156/190864337-ebb68740-4e66-41a1-b168-30f12550d649.png)

Logs as screenshots can not be added to the original logs section here:
![grafik](https://user-images.githubusercontent.com/13799156/190864784-2708895b-1a3f-46d7-b439-49afe1efc0b6.png)

![grafik](https://user-images.githubusercontent.com/13799156/190864791-4b11b3b3-82d8-4b51-94ac-5fa49256d33e.png)

![grafik](https://user-images.githubusercontent.com/13799156/190864797-83a6c7a9-5e55-485f-be6e-dea04e20844c.png)

**Comment by Reachushere** [comment]
> I‘ve the same issue after changing the default „iPhone“ naming. Multiple instances of the same server will be created after time. Sometimes with the changed device name, sometimes with default „iPhone“ naming.
> 
> Two days ago I uninstalled and reinstalled the app on my iPhone 12 Pro and Apple Watch without changing the default naming. The issue is gone but with the downside of the default naming.

Has there been a solution found to this?  We have two ios both on 16, and only one phone will receive a notification.  We use the Call Service test in Developer, and from both phones the notitications only go to the same phone - even after both phones are renamed.

**Comment by Reachushere** [comment]
There was a Core update about 45 mins ago and fixed the issue entirely for me.On Sep 22, 2022, at 6:26 AM, bcutter ***@***.***> wrote:﻿
Solution is "on the way", see #2148 (comment)
All other workarounds don't work, not permanently.

**Comment by Reachushere** [comment]
So I updated and suddenly our individual iPhones were there listed with the names that we had chosen in the Companion App under Server.  Until then they were not showing up.  I tested and the notifications seem to be working now.  Maybe it’s just a fluke as I was trying to figure this out at the same time the update became available, so maybe I did something to make it work and didn’t realize it.On Sep 22, 2022, at 6:40 AM, bcutter ***@***.***> wrote:﻿

There was a Core update about 45 mins ago and fixed the issue entirely for me.

I doubt it as there's nothing related to this issue in the release notes.
https://www.home-assistant.io/blog/2022/09/07/release-20229/#release-202296---september-22
Maybe wait another 24 hours and tell us if it is still completely fine (as it sometimes looks like it is for few hours when applying the workarounds).

**Comment by mww012** [comment]
I'm updating to 16.0.2 now. I'll report back if the issue auto-resolved or if I need to remove and re-add my phone into HA. Fingers crossed that this settles it.

**Comment by mww012** [comment]
No luck. I upgraded to 16.0.2 deleted my phone from HA entirely. It added back fine but within 1 hour I had 5 entries back in my mobile app. 😔

**Comment by ziptbm** [comment]
I'm seeing this as well across two different servers and two different phones, so 4 times.

As part of my troubleshooting, I've ensured the device is now properly renamed as it was before so it does not break my previous automation notifications, which are now working correctly.  However, the device page within Home Assistant no longer shows the listed automations associated with this device.

![Screenshot 2022-10-04 152904](https://user-images.githubusercontent.com/46136563/193908981-d0a38623-68e3-426f-82c3-ef3692356f62.jpg)

**Comment by maikkoe** [comment]
I had this problem too. I don’t know if it’s the HA release 2022.10.1 or the way I reconfigured the App/Integration. First I resetted the app, uninstalled it, deleted the device from the Integration over my Mac. After everything was gone I reinstalled the App and configured it correctly (custom name not iPhone). Since that it’s working nearly one day. Before it was working only for a few hours.

**Comment by snookerap** [comment]
I still have the problem despite all the updates.

**Comment by restauffer** [comment]
This has solved the problem for me. The name is being passed from iOS properly as before iOS16. Thank you.

**Comment by mww012** [comment]
Same here!  It took a full uninstall of the app and removing the integration HA. Before doing that my extra entries would come back. We're all good now though. 

Thanks again guys!

**Comment by kamwill** [comment]
It is better now, but still doesn’t work properly. Names of the phone are properly shown in the integration, but the devices name itself keeps on changing from the proper one to “iPhone” multiple times a day.

**Comment by eyeseesharp** [comment]
Still doesn't work for me, the device name seems to stick, but most of the sensors associated with my phone 'disappear' and become unavailable, only to finally become available when I focus attention on the companion app.

Deleted app and server info, no luck after reinstall on both.

**Comment by davidlarkins** [comment]
Just wanted to echo what previous user said.  update to iOS-2022.10 did NOT work for me.  Both my iphone and my wife's iphone reset from the device name to 'iPhone' and from 'iPhone' to the device name.  I have not been able to pinpoint if it's only when I'm logging in with the cloud vs. when I'm on my own network via wi-fi. 
I don't think I'm willing to try a TestFlight beta - especially on my wife's phone.  Do you think that a true fix will make it to the official app in an update soon?

Right now, I'm not able to count on ANY notification of automation that I have set up to use device tracking.  :(

**Comment by restauffer** [comment]
Early after the release I said it had solved my problems but as time as progressed, I am still having problems similar to what others are experiencing.

**Comment by kamwill** [comment]
Disabling local push in companion app did the trick for both of my iPhones. Proper names are persistent now.

**Comment by davidlarkins** [comment]
> 

In my companion app settings, local push does not seem to be something that I am able to modify.  (Perhaps I just don't know how).  It just says 'Disabled'.

**Comment by kamwill** [comment]
Click on the internal url.
![67AD4F73-A8BA-4D51-9AE3-5A918C800F35](https://user-images.githubusercontent.com/34270987/197970298-e7a8efef-224b-41c7-bc6a-2821b25c7cf1.jpeg)
Then the local push option will show on the next screen. 
![CB72DD49-D7E0-4F3C-A5E7-A51C77B33D08](https://user-images.githubusercontent.com/34270987/197970503-9ad837d5-a0e9-4a3e-bdf1-2dee68c55019.png)

**Comment by davidlarkins** [comment]
Thank you! I'll disable that and see if it stabilizes.  (Seems like that slider button should have gone into a screen that was available by clicking on the status of that item.)

**Comment by zacwest** [comment]
2022.10.1 is now out which should resolve the last of the issues for iOS.

**Comment by dlindnegm** [comment]
> 2022.10.1 is now out which should resolve the last of the issues for iOS. If you disabled Local Push you can re-enable it with this update.

Where do you confirm the version of the IOS app?  In Settings - About I see the same versions as in the Windows Desktop web page:
Home Assistant 2022.10.5
Supervisor 2022.10.0
Operating System 9.2
Frontend 20221010.0 - latest

And in the server settings on the IOS app I show:
Connected via     Internal URL
Version                10.5

**Comment by zacwest** [comment]
HA settings > Companion app > About (top left)

**Comment by davidlarkins** [comment]
Much appreciation for the resolution of this issue, and for the helpful communication to those of us who have posted.  

Thanks all!

**Comment by eyeseesharp** [comment]
What was is that fixed it for you? it's still not working for me

**Comment by davidlarkins** [comment]
update to version 2022.10 of the app + disabling local push fixed it for me.  But we're told that upgrading to 2022.10.1 will fix the issue even with local push enabled. (that update just came out today)

**Comment by dlindnegm** [comment]
Thanks Zac for resolving this for everyone!

Everything seems to be working as before with the 2022.10.1 release and local push re-enabled.

**Comment by IIAIronWolf** [comment]
Issue is still occuring for me. It seems that after iOS updates, Apple updates the name of the iPhone in Settings > General > About > Name from 'iPhone-Name' to 'iPhone-Name (600)' and the number in parentheses increases with each iOS update. There have been numerous reports of this issue in the Apple forums, like the one here: https://discussions.apple.com/thread/253846964

**Comment by bgoncal** [comment]
Is this still an issue with latest versions of app and core? Feel free to reopen if needed
