### ISSUE TITLE
Build error: Missing required module 'Clibsodium'

### ISSUE THREAD

**Issue by fhriley** [home-assistant/iOS#2214]
**Describe the bug**

I am using XCode 14.0.1 on ARM.

I followed the build instructions and chose the cocoapods method. When building App-Debug, I get a `Missing required module 'Clibsodium'` fatal build error.

**To Reproduce**

Clone the repo and follow the build instructions for cocoapods. Then try to build App-Debug.

**Expected behavior**

The build succeeds.

**Comment by zacwest** [comment]
Can you share the full build log for this failure? Which revision of master?

**Comment by fhriley** [comment]
`9996aaf6d5d802327c9e57621134bb93e6e963cb`

[408D1AE7-E454-43D1-8FD8-340E6E7D8884.xcactivitylog.zip](https://github.com/home-assistant/iOS/files/9702255/408D1AE7-E454-43D1-8FD8-340E6E7D8884.xcactivitylog.zip)

**Comment by fhriley** [comment]
A directory it is using does not exist:

```bash
ls -l /Users/friley/Library/Developer/Xcode/DerivedData/HomeAssistant-amxwsueqetxtprhdpleltocsathi/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/Clibsodium
ls: /Users/friley/Library/Developer/Xcode/DerivedData/HomeAssistant-amxwsueqetxtprhdpleltocsathi/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/Clibsodium: No such file or directory
ls -l /Users/friley/Library/Developer/Xcode/DerivedData/HomeAssistant-amxwsueqetxtprhdpleltocsathi/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates
total 0
drwxr-xr-x  3 friley  staff   96 Oct  3 19:07 FirebaseAnalytics
drwxr-xr-x  4 friley  staff  128 Oct  3 19:07 GoogleAppMeasurement
drwxr-xr-x  4 friley  staff  128 Oct  3 19:06 Realm
drwxr-xr-x  4 friley  staff  128 Oct  3 19:06 Sodium
```

**Comment by fhriley** [comment]
I switched to method 2 and now it builds successfully. It appears method 1 does not work.

**Comment by zacwest** [comment]
I believe this is an issue with newer Cocoapods which would explain why the bundler approach works. The Gemfile currently pins us to an older one.
