### ISSUE TITLE
Multiple audio output devices not detected (no bluetooth)

### ISSUE THREAD

**Issue by WoLpH** [home-assistant/iOS#2215]
**Device model, version and app version**

Model Name: MacBookPro16,1
macOS Version: 12.6
App Version: 2022.8 (2022.387)
Safari Version: 16.0 (17614.1.25.9.10, 17614)

**Home Assistant Core Version**

**Describe the bug**

When I switch the audio device from my dock (Caldigit TS3+) to the internal macbook speakers or  my JDS Element headphone dac/amp the Home Assistant app does not detect it. Restarting the Home Assistant app does not work either, it will still show the wrong device.

It does however work to switch to the speakers bulit into my monitors...

**To Reproduce**

1. Set audio device to built-in macbook speakers or JDS Element
2. Start Home Assistant (or already have it running, it makes not difference)

**Expected behavior**

1. The audio device to change

**Screenshots**

**Additional context**

Not sure if it helps, but the SwitchAudioDevice app does detect the audio devices correctly: https://github.com/deweller/switchaudio-osx

This might be somewhat related to the issues about not detecting bluetooth devices, but these are all physical devices connected either internally in the laptop or through usb in case of the DAC.

**Comment by zacwest** [comment]
Do they show up in the sensor (as an attribute) but never transition to active, or do they not show up at all?

**Comment by WoLpH** [comment]
They do show up as attributes, but they never transition to active.
![image](https://user-images.githubusercontent.com/270571/193644485-304eb905-0e4c-4e8d-8c58-ed243461ebfb.png)

I wouldn't be surprised if it's a bug within OS X, but that could mean that a different API has to be used. It has to be possible since SwitchAudioSource does detect it correctly.

**Comment by zacwest** [comment]
Does it note active status or default status? The app doesn't switch to a particular one unless the system says it's actively receiving audio output, not just set as the default output.

**Comment by WoLpH** [comment]
That's a good point. That app only shows the default status, which might be convenient to expose as well :)

That's unfortunately not the issue here though, even though it's actively outputting through the other output device it's still not showing any change.
Thinking about it... the Active Audio Output could be problematic in multiple ways. You can have multiple output devices enabled at the same time for example. I have all of my (video) call applications set to use the built-in speakers and built-in microphone whereas I use either the  regular speaker set or headphones for music/video/etc.

**Comment by WoLpH** [comment]
Oddly enough... I have rebooted my laptop and now it does appear to work correctly. I'm pretty sure there's still a bug somewhere but it will be near impossible to track down if it's not consistently repeatable so I'll close this issue unless I find something more concrete
