### ISSUE TITLE
URLs containing & are truncated when Chrome or Firefox browsers are configured

### ISSUE THREAD

**Issue by flyboy013** [home-assistant/iOS#2220]
**iOS device model, version and app version**
Model Name: iPad (6th generation)
Software Version: 15.7
App version: 2022.8 (2022.387)

Problem also occurs on iPhone.

**Home Assistant Core Version**
2022.9.7

**Describe the bug**
When opening a URL that contains two or more parameters (ie. uses ampersand for specifying second or later parameter), only the URL upto the ampersand is passed to the browser.  When safari is configured as browser to open links, it works correctly, but not for Chrome or Firefix.  This seems to be related to bug [930](https://github.com/home-assistant/iOS/issues/930) and fix [933](https://github.com/home-assistant/iOS/pull/933).

**To Reproduce**

```
type: markdown
content: |-
  [Example with & code](https://www.google.com/search?dummy=1&q=home%20assistant)
```
**Expected behavior**

The URL should open with a search for Home Assistant.  Works on Mac and iOS iPadOS when using Safari but not Chrome or Firefix.

**Screenshots**

**Additional context**

**Comment by bgoncal** [comment]
Is this still an issue in 2024? Let me know and I will reopen it
