### ISSUE TITLE
can' delete server entry in iPhone App

### ISSUE THREAD

**Issue by rifffraf** [home-assistant/iOS#2226]
Model Name: IPhone13 Pro
Software Version: 16.1
App version: 2022.10.3

Supervisor 2022.10.0
Operating System 9.2
Frontend 20221010.0 - latest

It's not possible to delete the login credentials in the App. Not by Deleting the App or using the Reset Button. The App Try always to reconnect me to a old instance. The old Sever Entry can't also not be deleted. 

After closing and opening the app, the entry simply reappears

**To Reproduce**
Maybe it has something to do with the fact that I first re-setup the Home Assistant Server and afterwords changed the app entry.

**Expected behavior**
just delete the old entry wenn pressing delete 

Anyway homeassistat is a great pease of software, thanks a lot for your work

**Comment by zacwest** [comment]
This should be fixed by #2190

**Comment by rifffraf** [comment]
i'am sorry but I understand your answer, way did you closed the ticket? The Problem exist in my version?

please reopen the ticket or tell me how to solve the problem. idk???

**Comment by jsiemek** [comment]
It's fixed in upcoming release. You have to wait.

**Comment by zacwest** [comment]
You have reported a bug. That bug is fixed in the pull request linked above. The fix will be included in the next app release, 2022.11 (or later).

**Comment by rifffraf** [comment]
Ok, I'm sorry for my misunderstanding thanks for your reply
