### ISSUE TITLE
Servers Deleted from the Companion App Server List Reappear

### ISSUE THREAD

**Issue by truseer** [home-assistant/iOS#2232]
Old server in app:
![IMG-4200](https://user-images.githubusercontent.com/22533211/196977513-0bb43868-3794-4956-a215-f93fffad40b1.PNG)
Delete server:
![IMG-4201](https://user-images.githubusercontent.com/22533211/196977526-835fd215-0980-46aa-8ee7-c356ca751a8a.PNG)
Server is gone:
![IMG-4202](https://user-images.githubusercontent.com/22533211/196977534-0099bcf7-cab3-45db-b5c5-0e362fdde204.PNG)
After several minutes and restarts of the app the old server has mysteriously returned:
![IMG-4203](https://user-images.githubusercontent.com/22533211/196977564-6fff7440-b28e-44e0-8fe9-34fbc7a1dad8.PNG)

**Comment by zacwest** [comment]
Try the latest [TestFlight beta](https://home-assistant.io/ios/beta) which has some improvements in deleting servers.

**Comment by truseer** [comment]
Beta installed, will report back once tested.

**Comment by truseer** [comment]
Beta seems to have this issue fixed.  Thanks!
