### ISSUE TITLE
Settings button disappears after Lovelace UI loads

### ISSUE THREAD

**Issue by krystof-k** [home-assistant/iOS#2240]
**iOS device model, version and app version**

Model Name: iPhone 13 mini
Software Version: iOS 16.0
App version: 2022.10

**Home Assistant Core Version**

Home Assistant 2022.10.5
Supervisor 2022.10.0
Operating System 9.2
Frontend 20221010.0 - latest

**Describe the bug**

Settings floating button disappears after Lovelace UI is loaded. If I turn on the airplane mode, it stays here.

**To Reproduce**

Launch the app.

**Expected behavior**

The button keeps visible.

**Screenshots**

https://user-images.githubusercontent.com/11633481/197545159-f89d7ba2-9553-4c9e-9669-7a04cd1067b9.MP4

https://user-images.githubusercontent.com/11633481/197545515-a7d802fd-5fc9-411d-86f6-beba4a15e197.mov

**Additional context**

—

**Comment by TomBrien** [comment]
This is the intended behaviour. After the dashboard has loaded you can enter settings via the side menu. Settings>Companion App. The floating button is only there to help fix the case where the app can't connect due to bad settings.

**Comment by krystof-k** [comment]
I see, I missed that option in the settings, a bit confusing. Thanks.
