### ISSUE TITLE
Can't create Shortcut using Shortcuts app, KAKit.HAError

### ISSUE THREAD

**Issue by sfatula** [home-assistant/iOS#2243]
Model Name: iPhone SE (2nd Gen), 
Software Version: 15.7
App version: 2022.398

**Home Assistant Core Version**
22.10.5

**Describe the bug**
Trying to create a shortcut on IOS. Get error "The operation couldn't be completed. (HAKit.HAError error 1.)

**To Reproduce**
Run Shortcuts app on IOS
Click + to create a new shortcut
Click add action
Click "Apps"
Click Home Assistant
Click "Call Service"
Click the word service to select a service, get error

**Expected behavior**
Expected to be able to pick a service.

**Screenshots**
[](https://drive.google.com/file/d/1Q83AB7hxuUW3ReNxrPcuHqX1pttuYNlj/view?usp=drivesdk)

**Additional context**
Same error occurs on iPad also. Near as I can tell, no way to workaround it.

**Comment by zacwest** [comment]
This is probably an issue parsing the list of services. Can you export logs (app settings > debugging > export) and look in `HomeAssistant.log` for `HAError`? You can also [attach the full logs here](https://www.dropbox.com/request/CtVWqILBXZ41tmFSGK2y) [note this issue number in the name] or share them [in Discord](https://www.home-assistant.io/join-chat/) in #ios_and_mac.

**Comment by sfatula** [comment]
I uploadeed the IOS debig logs to dropbox. In homeassistant.log, there is nothing there, nothing generated when this happens in shortcuts app. Hopefully the helper app logs help. Likely you can reproduce too.

**Comment by zacwest** [comment]
Looks like the error isn't logged, darn. My hunch is that it's a component with a service call missing a name and description, but we don't log the response to the 'get_services' call. Should be able to update the app blindly to handle one of those being missing. It is likely specific to which components you have loaded, so it doesn't reproduce for me, for example.

**Comment by sfatula** [comment]
I see. The reason I said that was I brought it up first on reddit, and a guy responded and got the same error as me. 

Is this data stored in MySQL? I could find it there if you tell me where. If not, the addons I have are:

AWNET to HASS
Nextcloud Backup
Terminal and SSH
ZWave JS

Lots of devices though. If you can tell me what to look for and where, I will gladly look.

**Comment by zacwest** [comment]
It's not super easy to get the result that would make it easy - if you're comfortable with the web inspector in your browser you could look at the WebSocket (WS in inspector) connection and see what the response is to "get_services".

**Comment by sfatula** [comment]
I uploaded to dropbox location a file named get_services.txt for the results of that call. Let me know if it tells you anything.

**Comment by zacwest** [comment]
Thanks, that was helpful -- it is the `awnet_local` component, which has a services.yaml of:

```yaml
update:
  name: Update Weather Information
  description: Updates the weather information from a local push
  fields: []
```

`fields` is expected to be a dictionary, not an array -- so the app is failing to parse that.

**Comment by bgoncal** [comment]
Is this still an issue in 2024? Let me know and I will reopen it

**Comment by sfatula** [comment]
It does seem to work now for the test case.

**Comment by Bogdis** [comment]
Hello, 
I hope this Is ok that I write here instead of opening a new issue for the same thing.
I have the same problem can't get the call service to work getting the hakit.haerror error 1 when I klick on service.
iPhone 16 pro max
Ios 26.1
HAOS 2025.11.1

Removed the App, reset the app, add it again, remover my phone from integrations and added it again nothing works.

**Comment by Bogdis** [comment]
No one who has this problem?

**Comment by rauchenistschlecht** [comment]
I started having this issue about 2 days ago as well. Perhaps it is related to a home assistant change in a recent update rather than configuration formatting, as we both began experiencing this recently?

I already tried debugging my yaml files by wiping them, trying to add "call service" from the iOS shortcuts app, and then restoring my yaml files. No luck that way. I am able to produce this error on 2 different iPhones.

My configuration is:
iPhone 15 Pro
iOS 18.6.2
HAOS 2025.11.1

I began experiencing this issue with HAOS 2025.11.0. The second iPhone I attempted with is an iPhone 17 on iOS 26.1.

**Comment by Bogdis** [comment]
I haven't used Shortcuts before with HAOS so I don't know when it started. I just begun to try out HA shortcuts and it didn't work :(

**Comment by rauchenistschlecht** [comment]
Ah, I see. I am fairly new as well. Just to clarify my previous comment - I did not experience this issue at all prior to HAOS 2025.11.0.

**Comment by Bogdis** [comment]
New Issue is created.
#3946

**Comment by Goewiebassman** [comment]
I found this post because I have the same issue. I'm trying to get rid off homekit because of the stabilty of HA. Hopefully there will be a solution soon.

**Comment by DepkaCZ** [comment]
Stil geting this error, has it been released to public yet ? Or still only in Beta ?
