### ISSUE TITLE
Template widget feature request 

### ISSUE THREAD

**Issue by pettably** [home-assistant/iOS#2254]
Can a template widget please be added to iOS like the widget on android please. 
This would be a lot better than using workarounds like scriptable

**Comment by raemsey** [comment]
Yes that would be awsome!

**Comment by bgoncal** [comment]
We don't track feature requests in github issues, probably thats why this was not seen before, please use https://community.home-assistant.io/ for that.
Meanwhile we now have template widget for Lock Screen already
