### ISSUE TITLE
Typing entity names auto-complete sometimes doesn’t work

### ISSUE THREAD

**Issue by llamafilm** [home-assistant/iOS#2262]
Model Name: iPhone 12 Pro
Software Version: 16.1.1
App version: 2022.10.1 (2022.424)

**Home Assistant Core Version**
2022.12.0

**Describe the bug**
Sometimes when typing an entity name to add to an automation, the autocomplete doesn’t work. This problem happens only in portrait mode. If I rotate the iPhone to landscape mode and type again then it works.

**To Reproduce**
It’s a bit random. It doesn’t happen every time. It’s not related to any particular entity. The same entity works if I add it to different automation. 

**Screenshots**
![ezgif-4-5ac4dd452d](https://user-images.githubusercontent.com/3991046/208272351-ae714103-9341-4a57-802f-03ced8f07a7e.gif)
Full video: https://user-images.githubusercontent.com/3991046/206837788-3b90527e-438c-43c1-8bbb-e3b5f60a56de.MOV

**Comment by bgoncal** [comment]
Does this issue also happens in iOS Safari? It looks like frontend related, you can open an issue for froentend instead.

I will be closing this issue due to have been reported long time ago and what I said above, but feel free to reopen if needed
