### ISSUE TITLE
Colour picker in actions configuration goes over container

### ISSUE THREAD

**Issue by zacchild** [home-assistant/iOS#2263]
Model Name: iPhone 11
Software Version: 16.1.2
App version: 2022.12.1

Home Assistant Core Version
2022.12.1

Describe the bug
When choosing a colour in the actions configurator, the scrollable element containing the colours in different categories doesn't conform to the container that it is displayed in 

To Reproduce
Create a new action -> click on the colour picker and see the UI fault.

Screenshots
See the attached image
![IMG_3232](https://user-images.githubusercontent.com/100210970/206883133-e5a7d223-10de-4597-a0dd-98b7be479129.PNG)

**Comment by bgoncal** [comment]
iOS Actions had become a legacy feature, so non-critical issues won't be addressed anymore, we now offer direct access to scripts and scenes for watch, CarPlay (coming in this release) and widgets
