### ISSUE TITLE
Negative numbers can't be entered in the iOS number picker

### ISSUE THREAD

**Issue by jolros** [home-assistant/iOS#2270]
I'm trying to set a negative temperature threshold in an automation using Home Assistant on iOS, but the picker does not allow for negative numbers, so I have to use the web.

![home-assistant-number-no-negative](https://user-images.githubusercontent.com/215467/208314897-ccda1d45-cc5d-428c-a44d-a50075e3311c.png)

Version: Home Assistant 2022.12.7
Frontend: 20221213.1

**Comment by kittentronic** [comment]
Same here, Home Assistant 2023.2.2, Frontend 20230202.0

**Comment by lesma** [comment]
Same here with the Android App. FrontEnd 20231030.2, supervisor 2023.11.6 Core 2023.11.3, App 2023.10.2-full

**Comment by bgoncal** [comment]
Do you still experience this issue? If so, please report to frontend repo which most likely will need to update the field content type.

Closing, since it's not App specific

**Comment by lesma** [comment]
@bgoncal can confirm it is still an issue. Can I ask what makes you believe it’s not an app issue? It works fine in browsers on both desktop and mobile and can on desktop can use the up down Buttons in the box (or arrow keys on a desktop) to make the number negative.

**Comment by bgoncal** [comment]
Oh so it behaves differently between iOS Safari and the iOS App?

**Comment by lesma** [comment]
I am on android myself and on that the App and Android Chrome behaviour differently. I would guess from the original poster who was on iOS that it does behaviour differently between the app and Safari.

**Comment by bgoncal** [comment]
> I am on android myself and on that the App and Android Chrome behaviour differently. I would guess from the original poster who was on iOS that it does behaviour differently between the app and Safari.

Thanks for mentioning that, I overlooked, the app should behave the same as in Safari browser, I'll have a look.

**Comment by lesma** [comment]
Interesting, looking again I was actually using Samsung Internet when it worked, in Chrome it does not work even though they both use Chromium. To me this does now feel more like a potential front end issue, with Samsung Internet also having an issue with not following validation rules. Though it does still seem odd to me that on desktop its using diffrent validation rules?

**Android App:**
![Screenshot_20240226_171125_Home Assistant](https://github.com/home-assistant/iOS/assets/4517893/b2aa6b1d-66ca-4631-9239-a4c314117e67)

**Chrome:**
![Screenshot_20240226_171943_Chrome](https://github.com/home-assistant/iOS/assets/4517893/6daa3059-c676-4166-bd2d-3c0467ae2d25)

**Samsung Internet**
![Screenshot_20240226_171142_Samsung Internet](https://github.com/home-assistant/iOS/assets/4517893/9dc7bb0b-2ec9-47d4-afb5-a3563a83a597)

**Comment by bgoncal** [comment]
Indeed it looks like it's a frontend issue. Can you open an issue there and reference this one?

**Comment by lesma** [comment]
Raised: [https://github.com/home-assistant/frontend/issues/19893](url)
