### ISSUE TITLE
MacOS companion creates iPad entity in devices, but no notification target

### ISSUE THREAD

**Issue by klement** [home-assistant/iOS#2271]
I installed companion apps on both iPhone and Mac.

I see mobile_app_klements_iphone but no corresponding entry for mac. In fact, there is no other mobile_app_* entry.

If I send a notification with notify.notify, it lands on the iPhone, but not on Mac.

What I would like to achieve is to have my Mac play a sound when a specific sensor value is reached. But I don't want to have to clear iPhone notifications.

I tried removing iPhone app and only keeping Mac one. Also removing that registration and adding it back. Notify target is simply not created for Mac.

In servers section I see that Local Push is Available (0) (after sending some test notifications via Developer Tools).

I see the Mac (as iPad) in devices with all its sensors, it's just not possible to select is as a notification target.

**Comment by bgoncal** [comment]
Is this still an issue in 2024? Let me know and I will reopen it

Tip: delete the device entry, force close the mac app and open it again, it will force the app to register everything again.
