### ISSUE TITLE
Home Assistant app on MacOS 13.2 Beta Not Opening

### ISSUE THREAD

**Issue by jmbly** [home-assistant/iOS#2276]
<img width="264" alt="Screenshot 2023-01-03 at 1 22 55 PM" src="https://user-images.githubusercontent.com/47805357/210418175-f21c4956-d03c-4443-93b9-83a0236eda1e.png">

For the last few beta builds of the app I get the attached error messages when trying to open the app. I have removed it from TestFlight and re-enrolled and still have this issue.

I am on a 2021 MBP M1 running MacOS beta 13.2(a). I have the same provisioning for my iOS devices and have no issues opening or running those variants on an iPad or iPhone - only on my Mac.

**Comment by zacwest** [comment]
Whoops, I updated the iOS build but not the macOS build. This will be resolved once Apple approves the update -- each macOS TestFlight build needs to be manually approved.

**Comment by jmbly** [comment]
Tested today and now it's working. Thanks!
