### ISSUE TITLE
No Integration/Devices Created

### ISSUE THREAD

**Issue by AshtonKem** [home-assistant/iOS#2280]
**Device model, version and app version**

Model Name: Mac Mini (2018)
macOS Version: Ventura 13.0.1
App Version: 2022.10.1 (2022.424)
Safari Version:16.1 (18614.2.9.1.12)

**Home Assistant Core Version**

2023.1.2

**Describe the bug**

I logged into the MacOS companion app, but it does not appear to create any integrations, devices, or entities. The only instances of the "Mobile App" integration are for our iOS devices, which work as expected.

The app otherwise works. I can edit settings, view my dashboards, and interact with Home Assistant as expected. The only thing that does not work is the sensors.

**To Reproduce**

Sign into local server using Companion App.

**Expected behavior**

Integration is created with 1 device, and the standard set of entities for MacOS.

**Screenshots**
![image](https://user-images.githubusercontent.com/199201/211860155-67437cad-4dd4-49ce-beb0-fb849e031d46.png)

I would expect to see "Ashton's Mac Mini" or similar in this list.

**Additional context**

I see a strange error log when signing into the app.

![image](https://user-images.githubusercontent.com/199201/211860468-315cdf01-a347-4ca1-b093-7aba3ce55a36.png)

**Comment by zacwest** [comment]
They are probably called "iPad" which is the default name macOS 13 redacts the device name to. You can adjust this in Preferences > Servers > your server and set the device name.

**Comment by AshtonKem** [comment]
It appears like you're correct. That is quite the unexpected behavior.
