### ISSUE TITLE
Save / Cancel Buttons missing Screen to edit internal URL

### ISSUE THREAD

**Issue by dylan09** [home-assistant/iOS#2300]
**Device model, version and app version**

Model Name: MacBook Air M2 2022
macOS Version: 13.2
App Version: 2032.2
Safari Version: 16.3

**Home Assistant Core Version**
HA 2023.2.1
Supervisor 2023.01.1
Operating System 9.5

**Describe the bug**
I try to change the settings for internal URL for my server. Settings -> Server. Select server. Under details click internal URL.
The dialogue that opens has the correct URL and SSID. But there is also the hardware address for my WLAN adapter. 
Changes couldn't be saved because there is no save button in the dialogue.

**To Reproduce**
See above
**Expected behavior**
To have buttons for save and cancel inside the dialogue. As they are shown on my MacBook Pro with Intel CPU.

**Screenshots**

<img width="595" alt="Bildschirm­foto 2023-02-08 um 21 09 31" src="https://user-images.githubusercontent.com/13660768/217640946-8607949e-bb47-4c9b-83b3-08498be30b0d.png">
Screenshot from MacBook Air. Save and Cancel Buttons are missing.

<img width="603" alt="Bildschirmfoto 2023-02-08 um 21 14 46" src="https://user-images.githubusercontent.com/13660768/217641355-fc02c349-4fde-47d2-8b10-3350d5a4b783.png">
This is a screenshot from my MacBook Pro.

**Additional context**

**Comment by zacwest** [comment]
Darn, looks like this is a regression in the latest app (because of upgrading Xcode).

**Comment by dylan09** [comment]
Also observed that it detects the MacBook as iPad. All sensors in HA was named `sensor.ipad_XXX`.
Have to change the name in Companion App and deleting device from integration.
After next start of app the device and entities was named correct.
