### ISSUE TITLE
Custom intents work via Assist dialog in Home Assistant but not through IOS shortcuts

### ISSUE THREAD

**Issue by dave-parsons** [home-assistant/iOS#2308]
- Built in intents work on HA and via IOS shortcuts (watch and phone)
- Custom intents work on HA
- No custom intents work via IOS shortcuts

**Comment by balloob** [comment]
There shouldn't be any difference. 

Can you explain a bit more about the versions of the app + HA you use and how you trigger the custom intents both in HA and via iOS shortcuts?

**Comment by dave-parsons** [comment]
Thank you for looking at this. 

Home Assistant 2023.2.3
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest

home assistant companion
2023.2 (2023.444)

Shortcut

Assist
Dictate text
     If © Dictated Text does not have any value
   Stop this shortcut
   Otherwise
  Dictated Text is stop
   Stop this shortcut
  End If
End If
Assist with
  Dictated Text " 1
  Get the Device Model

**Comment by dave-parsons** [comment]
Shortcut is per install doc "Assist Button"

**Comment by dave-parsons** [comment]
I trigger Homeassistant using assist dialog.   I trigger shortcut on both watch and iPhone using shortcut button.

**Comment by balloob** [comment]
Both end up at the same code:

- Mobile app webhooks go via https://github.com/home-assistant/core/blob/dev/homeassistant/components/mobile_app/webhook.py#L316
- And Assist UI goes via https://github.com/home-assistant/core/blob/dev/homeassistant/components/conversation/__init__.py#L164

For the shortcut, can you open the "Assist with" action and make sure the right server is selected?

**Comment by dave-parsons** [comment]
I've confirmed the server is the correct server in the shortcut assist with. Further, I currently have only one server.

**Comment by dave-parsons** [comment]
Upgrade to IOS 16.3.1 has no effect.  Issue remains.

**Comment by dave-parsons** [comment]
Here is a short screen capture of exactly what I'm experiencing and the shortcut I have.   Stumped by this.  Any help appreciated.

https://user-images.githubusercontent.com/37843022/219985322-6e5a1a5c-e24b-4cb0-bd0b-c07d69c55026.mp4

**Comment by synesthesiam** [comment]
@dave-parsons I've got a PR with a possible fix. iOS is likely sending a full language code, like `en-us` or `en_US`. HA is currently checking for custom sentences with that literal string, so if you have `custom_sentences/en/` they will be skipped.

**Comment by balloob** [comment]
Thanks for filing the issue @dave-parsons !

**Comment by dave-parsons** [comment]
Confirmed fixed.   Thank you!

**Comment by WHQJonathan** [comment]
> Confirmed fixed. Thank you!

Hi could you help to advise. How to fix this issue ? I have same issue too thanks

**Comment by WHQJonathan** [comment]
Hi I have issue same as dave mentioned before, but my language zh-tw. Any suggestions how to fix it?
