### ISSUE TITLE
Assist fails in iOS app with a constant loop

### ISSUE THREAD

**Issue by wgstarks** [home-assistant/iOS#2309]
**iOS device model, version and app version**

Model Name: iPhone 11
Software Version: 16.2
App version: Home Assistant 2023.2.2 Supervisor 2023.01.1 OS 9.5 Frontend latest

**Home Assistant Core Version**

**Describe the bug**
The prompt "Hey Siri Assist" results in a response "How can I assist". Any command, for example "Turn on driveway floodlight" results in a response "How can I assist". This is constant for any command.
**To Reproduce**
Use the assist shortcut.
**Expected behavior**
Control device.
**Screenshots**

Screenshots posted in the support forum with my original report [here](https://community.home-assistant.io/t/assist-not-working-with-ios-app/530166?u=wgstarks).
**Additional context**

I got an error "Home Assistant did not hear anything" once. Also got "Action could not be found" once.

**Comment by bcmitri** [comment]
I believe this is an issue with iOS 16.2.  Upgrading to iOS 16.3 corrected the issue for me.

**Comment by wgstarks** [comment]
I updated to iOS 16.3.1 and the issue has changed slightly. Now I get an initial response “How can I assist”. When I give a command I get a response of “Done”. No action is performed though. The light that I wanted to turn on is still off so Siri didn’t do anything. This is the same for voice dictation and for typing the command directly into the shortcut.

**Comment by bcmitri** [comment]
Then it would seem that your original issue is cleared up.  I suspect your current issue is with Home Assistant interpreting your request.  Do you get the same result if you type that same request directly into the Assist dialog within Home Assistant?

**Comment by wgstarks** [comment]
> Then it would seem that your original issue is cleared up. I suspect your current issue is with Home Assistant interpreting your request. Do you get the same result if you type that same request directly into the Assist dialog within Home Assistant?

Not sure where the Assist dialog is?

**Comment by jsiemek** [comment]
He means middle icon on the right side of top HA menu.

**Comment by wgstarks** [comment]
Also getting the same error in the macOS app.

**Comment by bcmitri** [comment]
So, it sounds like you're dealing with an issue that is external to the iOS app.  Unless you are dealing with custom intents, then you may be running into the following:
https://github.com/home-assistant/iOS/issues/2308

**Comment by wgstarks** [comment]
I think you’re correct. I tested 18 times on 4 different devices with the iOS, macOS and webUI interfaces. I was able to turn on one device once (but not turn it off). Seems to be an application wide problem with all my devices. I’ll close this issue and wait a few releases and test again.
