### ISSUE TITLE
MacOS: Gray screen on launch, have to force quit

### ISSUE THREAD

**Issue by n8henrie** [home-assistant/iOS#2311]
**Device model, version and app version**

Model Name: 2020 M1 MBP
macOS Version: 13.1
App Version: 2023.2.1
Safari Version: 16.2

```console
$ brew info home-assistant
==> home-assistant: 2023.2.1,2023.452
https://companion.home-assistant.io/
/opt/homebrew/Caskroom/home-assistant/2023.2,2023.444 (128B)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/home-assistant.rb
==> Name
Home Assistant
==> Description
Companion app for Home Assistant home automation software
==> Artifacts
Home Assistant.app (App)
```

**Home Assistant Core Version**

 2023.2.1

**Describe the bug**

HomeAssistant launches to a grayed-out screen (as if there is some popup somewhere that is stealing focus -- but there isn't, I've looked through all windows for something like an update or privacy notification).

Going on for weeks to months in spite of reboots.

Goes away after a (homebrew) reinstall, then returns eventually.

**To Reproduce**

Open homeassistant

**Expected behavior**

Normal interactive screen

**Screenshots**

Note the gray color.

<img width="463" alt="Screenshot 2023-02-13 at 09 42 47" src="https://user-images.githubusercontent.com/1234956/218518480-799c667f-2d88-4082-9703-234f27ee4241.png">

**Additional context**

None of the buttons on the main interface work. Menu -> Quit HomeAssistant doesn't work (must force quit). I *can* still open preferences from the menu. I don't see anything interesting in the debugging -> event log. Debugging -> reset frontend cache doesn't fix the issue.

**Comment by zacwest** [comment]
I believe this is caused by a macOS 13 bug which is fixed if you upgrade to macOS 13.2. Whenever a modal/alert appears on the window, it instead does this. You likely see a white line across the window, too.

**Comment by n8henrie** [comment]
Yup. Thanks for quick response!

Of course, after having this issue for weeks, crawling through Console logs, force removing caches, etc. I think I finally figured it out within minutes of posting an issue -- if I disable the "automatically check for updates" button, after a force quit it relaunches normally. Manually checking for an update then recreates the locked up / grayed out situation.

**Comment by n8henrie** [comment]
Is 13.2 release yet?

<img width="315" alt="Screenshot 2023-02-13 at 09 50 23" src="https://user-images.githubusercontent.com/1234956/218520290-7921036e-4d24-45d4-834d-78ac7bb74357.png">

**Comment by zacwest** [comment]
Yeah, it was released on January 23. I've found toggling on/off some of the 'auto update' settings can force Settings to see it, at least.

**Comment by n8henrie** [comment]
Seems to be working on 13.2. Thanks @zacwest!

**Comment by oscar-b** [comment]
As a workaround for anyone who hasn't updated, opening a new window with `⌘N` kinda works.
