### ISSUE TITLE
iOS 16.4 fails to attach notification content in Local Push

### ISSUE THREAD

**Issue by Miroslavgapa** [home-assistant/iOS#2316]
**iOS device model, version and app version**

Model Name: Iphone 14 Pro Max
Software Version: 16.4 a
App version: 2023.2

**Home Assistant Core Version**

2023.3.1
**Describe the bug**
Notification which include attachment  as url is not more functional on this version of iOS - even notification is not delivered. I have latest beta with security update a - marked as 16.4 a (beta 2). My wife is running notification smoothly - she is on stable iOS 16.3.
**To Reproduce**
Create automation with notification to iOS device and include url with snapshot from camera.
as 
service: notify.mobile_app
data:
  message: Bla bla
  title: Test
  data:
    attachment:
      hide-thumbnail: false
      url: http://XXX/local/camera.jpg
**Expected behavior**
Delive the attachment.
**Screenshots**

**Additional context**

**Comment by zacwest** [comment]
I've filed this with Apple, I believe that local push extension is incorrectly unable to add notifications with attachments. Temporarily you can disable Local Push in HA Settings > Companion App > [Your Server at the top] > Internal URL settings.

**Comment by Miroslavgapa** [comment]
I currently doesn’t have external access to HA only through VPN. So in case of this setup I will receive nothing even when I am at home network . Anyway thank you for your recommendation.

**Comment by The-Croz** [comment]
Issue still persists on 16.4 release as well. Notifications with attachments wouldn't even come through at all for me. Disabling Local Push fixes this for now until a fix.

**Comment by JohnnyM84** [comment]
Same problem with the 16.4 public release, for now disabled local push.

**Comment by zacwest** [comment]
Thanks for the update. I am seeing similar. I will try and figure out a workaround.
