### ISSUE TITLE
Memory Leak - all memory is wasted by the app over time.

### ISSUE THREAD

**Issue by windswept321** [home-assistant/iOS#2318]
**Device model, version and app version**

Model Name: M1 Pro, 16-inch, 2021 16GB
macOS Version: 13.2.1 (22D68)
App Version:   2023.2.1 (2023.452)
Safari Version: Version 16.3 (18614.4.6.1.6)

**Home Assistant Core Version**
Home Assistant 2023.3.1

**Describe the bug**

A memory leak occurs when the app is left running for a few days. I have run out of memory twice, with 32GB, including SSD wasted by the Home Assistant app - The OS complains and I can see the issue in the Activity Monitor.

**To Reproduce**

Leave the app running and open for a few days until memory is gone.

**Expected behavior**

No memory leak.

**Comment by windswept321** [comment]
This is still an issue. Hopefully someone will pick up on it soon. I now have to remember to close Home Assistant client as otherwise I often see 32GB memory usage on my MBP 16” with 16GB RAM. I assume this could do actual physical damage to SSDs…

**Comment by bgoncal** [comment]
Let's continue this discussion here: https://github.com/home-assistant/iOS/issues/2101
I'll close this one as duplicate
