### ISSUE TITLE
ASWebAuthenticationSession http support

### ISSUE THREAD

**Issue by robbiet480** [home-assistant/iOS#233]
Using ASWebAuthenticationSession throws this warning in console: `ASWebAuthenticationSession support for http scheme is deprecated and will be removed in a future version of iOS. Use https scheme instead.`

Just making this issue to note it.

**Comment by robbiet480** [comment]
🤞 that Apple doesn’t kill this at WWDC tomorrow in iOS 14!

**Comment by zacwest** [comment]
Not sure there's anything we can do here. If Apple breaks things, we could move to WKWebView then, maybe.
