### ISSUE TITLE
my location changed in the middle of the night (while I was sleeping)

### ISSUE THREAD

**Issue by jmwhite5** [home-assistant/iOS#2336]
**iOS device model, version and app version**

Model Name: iPhone 13 Pro
Software Version: 16.3.1
App version: 2023.4

**Home Assistant Core Version**

Home Assistant 2023.3.6
Supervisor 2023.04.0
Operating System 9.5
Frontend 20230309.1 - latest

In the middle of the night, my phone sent out a "Significant Location Change" update from the companion app.  The GPS accuracy went down to 1446 feet which happen to overlap with another zone and Home Assistant deemed I was now in that zone.

The change caused an automation to run that woke me up 😔 

**To Reproduce**

I don't know how to reproduce.  This was the first time it happened.  I haven't made any changes to my zones in months.

**Expected behavior**

I would not have expected a "Significant Location Change" event to have happened while my iPhone was sitting on its charger next to my bed.

**Screenshots**

**Additional context**

I was able to recover by clicking on "Update Location" button in the companion app.

**Comment by fjfricke** [comment]
I think this is unfortunately due to the iPhone's incorrect location tracking when inside. It thinks the location it finds is accurate.
I think we could implement an extra check that location updates get ignored as long as the device is connected to the home wifi for example as an additional option for the user.

**Comment by bgoncal** [comment]
> I think this is unfortunately due to the iPhone's incorrect location tracking when inside. It thinks the location it finds is accurate. I think we could implement an extra check that location updates get ignored as long as the device is connected to the home wifi for example as an additional option for the user.

Please submit this as a feature request on Home assistant community, for now you can add this as a condition on your automation.
