### ISSUE TITLE
Swiping from left to right doesn't open the burger menu anymore from anywhere

### ISSUE THREAD

**Issue by mihaicristianpetrescu** [home-assistant/iOS#2338]
**iOS device model, version and app version**
Model Name: iPhone 13 Pro Max
Software Version: iOS 16.4
App version: 2023.444

**Home Assistant Core Version**
2023.4.1

**Describe the bug**
Swiping from left to right doesn't open the burger menu anymore from anywhere 

**To Reproduce**
In any screen the user cannot swipe anymore to open the burger menu for navigation in the app

**Expected behavior**
The user should be able to swipe to open the menu of the app

**Comment by zacwest** [comment]
If you update your app it will begin working again.

**Comment by mihaicristianpetrescu** [comment]
@zacwest Brilliant! Thank you very much!
Unfortunately the App Store on iOS wasn't providing an update for the app in the updates list, but after a manual search and showing "Open" initially it refresh and showed an "Update" finally.
