### ISSUE TITLE
Calendar and iOS Companion App

### ISSUE THREAD

**Issue by reotto613** [home-assistant/iOS#2343]
**iOS device model, version and app version**

Model Name: Apple IPhone 13 Pro Max and IPad Air 5th Gen
Software Version: 16.4.1 & 16.4.1
App version:  2023.4 (2023.460)

**Home Assistant Core Version**

**Describe the bug**
I have my calendar with 7 calendars from google calendar.

By accessing the calendar from the side menu on the web it works fine, shows all 7 calendars, all appointments and I can navigate away when I am done.

In the companion app on my iphone and ipad, if I access the calendar from the side menu it does NOT show the calendars (usually they are listed where you can check and uncheck them), it shows 0 appointments, and I am unable to navigate away from it no matter what I try.

To make matters worse no matter what I can including closing the app it always opens back up to the calendar. The only resolution I have found is to delete the app and reload it.

**To Reproduce**
Open the App, and click on the calendar on the sidebar on the left. 

**Expected behavior**
I should be able to click on the 3 lines at the top to get back to the side menu.

**Screenshots**

**Additional context**

**Comment by nima-1102** [comment]
I have exactly the same problem:

Model Name: Apple IPhone 12
Software Version: 16.4.1
App version: 2023.4 (2023.460)

Home Assistant 2023.4.4
Supervisor 2023.04.0
OS 9.5
Front end 20230411.1 - latest

**Comment by martdj** [comment]
I have the same problem and it's not iOS only. The Android app ha the exact same problem

**Comment by reotto613** [comment]
> I have the same problem, and it's not iOS only. The Android app has the exact same problem iPhone XR iOS 16.3.1 App version: 2023.4 Home Assistant 2023.4.4 Container version.

Appears to be a frontend issue then and not core or Companion App.

Opened a new ticket here:

[https://github.com/home-assistant/frontend/issues/16219](url)
