### ISSUE TITLE
Inspecting Simulator with Safari is not possible anymore

### ISSUE THREAD

**Issue by fredck** [home-assistant/iOS#2355]
**iOS device model, version and app version**

Model Name: Simulator with iPhone 14 Pro Max
Software Version: 16.4
App version: 2023.4.6 (Simulator version taken today from the latest CI action)

**Home Assistant Core Version**
2023.4.6

**Describe the bug**

The steps described in the README file to run and inspect the Simulator build created by ci don't work with the latest iOS. The WebView is not listed in Safari's "Develop" menu.

**To Reproduce**

Just follow the steps described in the README file using the latest Xcode Simulator:
https://github.com/home-assistant/iOS#testing-just-the-frontend

**Expected behavior**

The companion app WebView should be listed in the menu.

**Screenshots**

<img width="757" alt="image" src="https://user-images.githubusercontent.com/630060/235660325-96a1d4b4-3c32-436e-be9e-5e3c104ae1a0.png">

**Additional context**

Since iOS 16.4 WebViews are not inspectable by default and enabling it must be done explicitly by code:
https://webkit.org/blog/13936/enabling-the-inspection-of-web-content-in-apps/

**Comment by bgoncal** [comment]
It has recently being enabled for iOS 16.4+ (Release coming this month but already available on testflight)
