### ISSUE TITLE
iOS Assist Action calls unexpected Conversation Agent/integration

### ISSUE THREAD

**Issue by kbromer** [home-assistant/iOS#2357]
**iOS device model, version and app version**

Model Name: iPhone 8
Software Version: iOS 16.4.1
App version: 2023.4 (2023.460)

**Home Assistant Core Version**
2023.5.0

**Describe the bug**
When the OpenAI integration is installed, the companion app "Assist" function (triggered by shortcut or manually) will only call the OpenAI Conversation Agent, regardless of what the Voice Assistant configuration is set to. 

**To Reproduce**
Create a voice assistant for the "Home Assistant" Conversation Agent.
Install OpenAI integration and configure. 
Create a voice assistant with it (not clear if this step is necessary)
Delete the OpenAI voice assistant
Install the iOS shortcut for "Assist" provided in the documentation. 
Trigger the shortcut and ask home assistant for something simple (e.g. Turn on the kitchen lights)

**Expected behavior**
As the only Voice Assistant configured, and the one marked as primary, I would expect the "Assist" call from iOS to be handled by the Voice Assistant. 
Instead the OpenAI integration responds to the request (with some version of: "As a language model, I do not have access to control physical objects in the real world. Please consider using the Home Assistant app")

**Additional context**
This seems to be isolated to the companion app Assist call - I can replicate the (incorrect?) behavior on a wall tablet also running the companion app. However, if I call the Assist directly from the UI in a web browser, the feature works as expected.  I noted the companion app docs have not yet been updated, so I'm unclear what the Assist call is actually doing, but this seems to be the root.

**Comment by bgoncal** [comment]
You can now define the pipeline you want to use (check testflight version 2024.12), release coming this month
