### ISSUE TITLE
App frozen on a spinner after signing in

### ISSUE THREAD

**Issue by c10l** [home-assistant/iOS#2370]
**iOS device model, version and app version**

Model Name: iPhone X
Software Version: 16.4.1 (a)
App version: Can't get into the app, but in the app store it shows `2023.4`.

**Home Assistant Core Version**

2023.6.2

**Describe the bug**
After I select the server or type in the URL manually, the auth webview pops up. I enter my user/pass, then totp, at which point the webview closes and I'm back at the server selection screen. This time there's a spinner next to the server, and the app just stays there.

**To Reproduce**
In my case, it happens every time. I haven't been able to sign in to the iOS app.
On the same iPhone, I can log in via Firefox. I used to be able to use it on Safari as well but [now can't](https://github.com/home-assistant/core/issues/94782).

**Expected behavior**
Probably have access granted to my Home Assistant server.

**Screenshots**

![0AB361D8-3277-4695-B2B3-A119A1D1452B](https://github.com/home-assistant/iOS/assets/399431/631c38b2-467d-4e05-a573-c835a1676c82)
![383C9CD9-47B9-43C3-A531-FB0921FBD9DB](https://github.com/home-assistant/iOS/assets/399431/00095daa-107b-4df1-aec8-72bae70a2881)
![CE4607FF-550C-4A4E-9FE6-D4BF7FEE633E](https://github.com/home-assistant/iOS/assets/399431/bf0fcc20-f965-4ef3-982f-841763ea46b6)
![F010CCF2-B5E5-4859-A037-31ADCBB57E63](https://github.com/home-assistant/iOS/assets/399431/e92b8fbf-0186-4d7e-8113-acff6c89ac0c)

**Additional context**

Under my user, I can see a `Refresh token for https://home-assistant.io/iOS` created for this login attempt.
I can also see a `device_tracker` entity created for the iPhone with `Mobile App` as the integration.
There is also a device created by the `Mobile App` integration.

**Comment by bgoncal** [comment]
Do you still experience the same on the latest core and companion app version?

**Comment by c10l** [comment]
I just tried it now and got through, both in the app and on Safari. I'll close this issue. Thanks for checking!
