### ISSUE TITLE
IOS 16.6

### ISSUE THREAD

**Issue by dthomas946** [home-assistant/iOS#2374]
**iOS device model, version and app version**

Model Name: MLEJ3LL/A - iPhone 13 Pro Max
Software Version: 16.6 (Beta)
App version: 2023.4 (2023.460)

**Home Assistant Core Version**

**Describe the bug**
App will not open on iPhone. 
TestFlight error:not compatible on iPhonr

Compatibility: Requires macOS 10.15 or later and a Mac. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by outgeeked** [comment]
Seeing the same thing.

iPhone 14 Pro
iOS 16.5.1
US

**Comment by caraar12345** [comment]
This isn’t a bug: the TestFlight iOS release has expired a day before the macOS release.

So either switch back to the App Store version or wait for a new TestFlight release.

(TestFlight releases expire after 90 days.)
