### ISSUE TITLE
How to safely shutdown Home Assistant in RPI 4 

### ISSUE THREAD

**Issue by JoeRodGitHub** [home-assistant/iOS#2381]
I’ll like to know how to safely Shutdown my Home Assistant 2023.7.3 - Supervisor 2023.07.1
Operating System 10.3 - Frontend 20230705.1 - latest in my Raspberry Pi-4 8GB - Samsung Evo 64GB SD Card 

I have read everything in the community app and this topic is so confusing and the answer’s are from 1 or 2 years ago and not relevant to the newest has iOS. 

Following all these recommendations I have damaged my HA installation three times. Need to shutdown and be able to restart after moving the system to another room. 

I’m afraid do that because no matter what recommendation(s) I have tried after reconnecting Home Assistant to power nothing works and I have to start with a new installation over and over again. 

Any help to be able to unplug-move and reconnect Home Assistant in another location without having to start a new install again will be much appreciated. 

Joe

**Comment by TomBrien** [comment]
This is not an iOS issue. To shutdown Home Assistant, go to Settings>System>Power Button (top right)>Advanced Options>Shut down system. You'll probably need to use an admin account with Advanced Mode enabled in the user profile.
