### ISSUE TITLE
iOS app keeps crashing 

### ISSUE THREAD

**Issue by djfanatix** [home-assistant/iOS#2382]
**iOS device model, version and app version**
Model Name: iPhone 13 Pro
Software Version: 16.5.1
App version: 2023.7 (2023.462)

**Home Assistant Core Version**

Home Assistant 2023.7.3
Supervisor 2023.07.1
Operating System 10.3
Frontend-versie: 20230705.1 - latest

**Describe the bug**
iOS app starts normally, but after +/- 30 seconds it becomes slow, freezes and crashes. (app shuts down)
When using HA with safari, everything works smooth and responsive.
This is happening since a few months.

Diagnostics tried:
- deleting and reinstalling app
- other accounts for same installation

I use Cloudflare for remote access.
**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by rknobbe** [comment]
Seeing the same here, both for iPad and iPhone

**Comment by JIOB** [comment]
Experiencing the same here. iPhone 14 Pro Max.

**Comment by bgoncal** [comment]
Are you still experiencing this?

**Comment by djfanatix** [comment]
I am still experiencing this.
I only use the web version now.

I thinks it is an integration or lovelace or hacs bug. It seems like it is filling the memory and then crashes

**Comment by bgoncal** [comment]
Could you share more details on what do you have in your HA instance? Does it crashes in an specific dashboard?
