### ISSUE TITLE
Support for image entity missing

### ISSUE THREAD

**Issue by eikowagenknecht** [home-assistant/iOS#2391]
App version: 2023.4 (2023.460)

**Home Assistant Core Version**
2023.8.1

**Describe the bug**
The new image entity can not be used in notifications.

HA 2023.7 introduced a new "image" entity:
- Release Notes: https://www.home-assistant.io/blog/2023/07/05/release-20237/#image-entities
- DEV Docs: https://developers.home-assistant.io/docs/core/entity/image/

> The image entity is a simplified version of the [camera](https://developers.home-assistant.io/docs/core/entity/camera) entity, and supports serving a static image or an image URL that can be fetched.

I tried the following for getting that image shown in a notification:

```
  data:
    image: image.au_vorgarten_kamera_hauseingang_event_image
```

-> URLSessionTask failed with error: URL not supported

```
  data:
    image: /api/camera_proxy/image.au_vorgarten_kamera_hauseingang_event_image
```

-> Response status code was unacceptable: 404

Neither version works.

**To Reproduce**
- Have an image entity
- Send a notification with the entity

**Expected behavior**
It would be expected to be able to use the "image" entity to show an image in a notification.

**Screenshots**
---

**Additional context**
---

**Comment by eikowagenknecht** [comment]
Seems to be just missing documentation. This works (for me):

```yaml
  data:
    image: /api/image_proxy/image.au_vorgarten_kamera_hauseingang_event_image
```

I created a PR to the docs repo.

**Comment by melyux** [comment]
This doesn't work with the Telegram notifier. I get these in the logs:

>WARNING (SyncWorker_15) [homeassistant.components.telegram_bot] '/api/image_proxy/image.xxx_xxx' are not secure to load data from!
>ERROR (SyncWorker_15) [homeassistant.components.telegram_bot] Can't send file with kwargs: {'message': 'Message goes here!', 'file': '/api/image_proxy/image.xxx_xxx', 'caption': 'Message goes here!'}
