### ISSUE TITLE
Unable to create a shortcut "Call Service with data": HAKit.HAError error 1.

### ISSUE THREAD

**Issue by smtrfnv** [home-assistant/iOS#2397]
**iOS device model, version and app version**

Model Name: iPhone 13 Pro Max
Software Version: iOS 16.6
App version: 2023.460

**Home Assistant Core Version**
2023.8.2

**Describe the bug**
When I am trying to create a Home Assistant shortcut of type "Call Service" an error occures after touching "Service" lable (not possible to choose a service).

**To Reproduce**
Run Shortcuts app
Click + to create a new shortcut
Click add action
Click "Apps"
Click Home Assistant
Click "Call Service"
Click the word service to select a service, get error

**Expected behavior**
I expect a list of services abailable

**Screenshots**

![IMG_9059](https://github.com/home-assistant/iOS/assets/18582493/615353b6-8742-4c48-8e48-0c29b146998c)

**Additional context**
The same happens on my iPad.

**Comment by zacwest** [comment]
The services list in the app is very sensitive to invalid data at the moment. Do you have any custom components via HACS? Their services.yaml may contain invalid data the app is unsure how to handle so it gives up and errors. I hope we can improve this in the future.

**Comment by smtrfnv** [comment]
Yes, there are custom integrations. Is there a way to get a clear hint about invalid data in .yaml from Home Assistant logs or anywhere else?

**Comment by smtrfnv** [comment]
Somehow it is fixed for me now.
