### ISSUE TITLE
Making WatchOS independent from iOS

### ISSUE THREAD

**Issue by DeveloLongScript** [home-assistant/iOS#2408]
When someone created the WatchOS app, someone used "iOS app with watch app". This means any watch using Family Setup cannot install Home Assistant. I'm not quite sure how to fix this though.

Thanks!

**Comment by bgoncal** [comment]
I have moved this to "feature-request". I do see the value of it but it would need to change the watch app completely since currently, it depends on the iOS app information to perform actions/get data.

**Comment by bgoncal** [comment]
I've closed it since it's not an issue and indeed a feature request, please use GitHub discussions tab for that or Home Assistant Community https://community.home-assistant.io/
