### ISSUE TITLE
Back button do not working on iPhone for Studio Code server

### ISSUE THREAD

**Issue by L0bit0** [home-assistant/iOS#2410]
Hi

I use Code editor on my phone and back button do not work anymore. So i am stuck now on Code Editor every time i enter to Home Assistant on my phone 

Additional info:

- I have an iPhone SE, IOS 16.1.1
- Home assistant versions and Add On are up-to-date (HA2023.9.2, Studio Code Server 5.10.2)
- I tried restarting Server and iPhone app
- I tried restarting the iPhone
- Every time I start Home Assistant App on the phone, i come back to Studio Code Server, so now I can not do anything with Home Assistant on my phone now.

Do you know how to fix this on the iPhone? Or at least how I can "reset"home Assistant on the iPhone to do not start directly on the Stdio Code screen?

Thanks!

**Comment by danielforster** [comment]
Same with me, a little bit frustrating

**Comment by L0bit0** [comment]
Hi
if there is not a solution to fix the back button, at lease can anyone help how to "reset" the settings to start on default dashboard once we start HA app on IOS. i am stuck on Studio Code Server, and close app, reset iPhone... did not works, so I assume anything is saved on the server with default screens for the device.

As workaround i have created a new connection, but would be great how to manage these situations...

thansk

**Comment by jsiemek** [comment]
Hi,

 

Close application

Turn airplane more on.

Reopen the app

Press OK on no Internet red screen

Press gear icon

Disable airplane mode

Go to general and disable: Remember Last Page

 

That's all.

**Comment by bgoncal** [comment]
Hi, can you please run the latest version of the app available and send me a video of this behavior happening? You can also try testflight version: https://www.home-assistant.io/ios/beta

Also, you can always swipe up with 3 fingers to access Companion App settings
