### ISSUE TITLE
App no longer working in iOS 10.3.4

### ISSUE THREAD

**Issue by jokerigno** [home-assistant/iOS#2421]
**iOS device model, version and app version**

Model Name: iPad retina MD527TY/A
Software Version: 10.3.4
App version: 2023.4

**Home Assistant Core Version**

2023.10
**Describe the bug**

I tried to downlad the iOS app in my old ipad. App Store asked me and I installed the last working version (but downloaded the last relased). That's why it's not working: i'm not able to login so no able to have the sensors of the iPad like battery status.

**To Reproduce**

Download the app, try to login.

**Expected behavior**

Download the app,  Login works and be able to see iPad sensors.

**Screenshots**

**Additional context**

**Comment by bgoncal** [comment]
Home Assistant minimum supported iOS is iOS 12 for now, so that's actually not a bug

**Comment by jokerigno** [comment]
Ok there is maybe written somewhere and I missed or do you think this should be specified?

**Comment by bgoncal** [comment]
In the App Store, you can see the minimum requirements to run the app, as well as in Xcode
<img width="290" alt="Screenshot 2023-11-01 at 10 42 20" src="https://github.com/home-assistant/iOS/assets/5808343/6ec5b7a6-bb6d-48df-9b5d-e455e3bbff7a">
<img width="1341" alt="Screenshot 2023-11-01 at 10 43 11" src="https://github.com/home-assistant/iOS/assets/5808343/4ba9a344-23b1-4577-9814-4785c66f54d4">

**Comment by jokerigno** [comment]
I wonder why it let me download the app from the store if system is not supported then...

**Comment by bgoncal** [comment]
That weird, In the App Store the latest version available of the app for that iOS version is the one you can download, so you are (should be) downloading an old version of the app

**Comment by jokerigno** [comment]
uhm it make sense. But it seems that old version of the app no longer works as well.
