### ISSUE TITLE
Add Slovak language to Lolalise/[Home Assistant Companion for iOS]

### ISSUE THREAD

**Issue by misa1515** [home-assistant/iOS#2422]
**iOS device model, version and app version**

Model Name: 
Software Version: 
App version: 

**Home Assistant Core Version**

**Describe the bug**
Missing language "Slovak" in Lolalise https://app.lokalise.com/projects/ 
[Home Assistant Companion for iOS]

**To Reproduce**

**Expected behavior**
Please add Slovak language for translation in lokalise to [Home Assistant Companion for iOS]

**Screenshots**

**Additional context**

**Comment by bgoncal** [comment]
Please don't report as a bug something that it is not.
Create a discussion here in github requesting the language add and please mention any translators available so they could also be added to Localise for that language.
