### ISSUE TITLE
App crashes when clicking input_datetime field

### ISSUE THREAD

**Issue by dennisbrouwer91** [home-assistant/iOS#2432]
Model Name: iPhone 15 Pro
Software Version: iOS 17.0.3
App version: Home-Assistant App 2023.7

Home Assistant 2023.10.3
Supervisor 2023.10.0
Operating System 11.0
Frontend 20231005.0 - latest

I have an input_datetime helper configured on my Lovelace dashboard, this worked great for a long time on iOS 16, but on iOS 17, when i click the field to fill in a new time, the Home-Assistant app crashes back to the homescreen. Is on multiple iPhones in our household.

`type: custom:lightalarm-card
time_entity: input_datetime.wekker_time
mode_entity: input_select.wekker_mode
duration_entity: input_number.lightalarm_duration
`

To be able to fill in the time.

**Screenshots**
![IMG_F1DE7F95F0B3-1](https://github.com/home-assistant/iOS/assets/17491836/df7ac9a2-a3d3-417d-a179-2e5b96f5c72f)

**Comment by bgoncal** [comment]
I'm trying to reproduce the issue but I wasn't able to, Is anything special in your setup that I may not have on mine?
https://github.com/home-assistant/iOS/assets/5808343/005f399f-a68d-4138-a536-afe26961dc06

**Comment by dennisbrouwer91** [comment]
I guess it’s recently fixed (either in HA app or iOS) because it’s now also
working on my side!
Thanks for testing.
Dennis

Verzonden vanaf mijn iPhone


Op wo 1 nov 2023 om 10:23 schreef Bruno Pantaleão Gonçalves <
***@***.***>
