### ISSUE TITLE
Can't find WatchKit

### ISSUE THREAD

**Issue by nazar-41** [home-assistant/iOS#2433]
Hello everyone. After switching development teams and updating the bundle identifier, I encountered an error that prevented the discovery of the WatchKit 2 extension. Has anyone else experienced this issue?

<img width="455" alt="Screenshot 2023-10-24 at 19 16 01" src="https://github.com/home-assistant/iOS/assets/89843408/cc2630e7-51aa-4cbb-a66c-a675002d7a3e">

**Comment by bgoncal** [comment]
Make sure you:
- have the latest Xcode
- pull the most recent changes from master
- clean build
- delete derived data
- create your HomeAssistant.overrides

 and run again.
 
 (Are you running on simulator or real device?)
