### ISSUE TITLE
Display on IOS device does not match desktop when using the Calendar integration

### ISSUE THREAD

**Issue by homeautomator2** [home-assistant/iOS#2449]
**iOS device model, version and app version**
Model Name: iPhone 15 Pro
Software Version: 17.0.3
App version: 2023.7 (2023.471)

**Home Assistant Core Version**
2023.11.1

**Describe the bug**
I am using the Calendar integration by franc6.  When viewing the calendar in HA on a desktop, it displays perfectly.  However, on mobile (IOS), perhaps 1 in 10 entries displays incorrectly. Currently i'm seeing an entry that is supposed to end on Nov 5 shows as ending on Nov 7. There was one event in Oct that had the same behavior. All the rest of the events show accurately in both places. I am on the latest version of everything and the problem persists.

**To Reproduce**
For those events affected, it is 100% incorrect all the time (on IOS).

**Expected behavior**
IOS behavior should match desktop behavior.

**Screenshots**
attached.
![IMG_0879](https://github.com/home-assistant/iOS/assets/146100089/c2f28cc2-c26f-4a6a-9e5b-0095b0eff471)
![Screenshot 2023-11-09 at 9 10 21 AM](https://github.com/home-assistant/iOS/assets/146100089/43d04db2-183b-4061-93b9-ae59638d6a97)

**Additional context**
Tell me if you need additional info?

**Comment by bgoncal** [comment]
Does the same happen if you open HA in your mobile browser? If so maybe it's better to open a bug to `core` instead

**Comment by bgoncal** [comment]
Feel free to reopen if needed
