### ISSUE TITLE
Conditonal Cards not working on Mac App

### ISSUE THREAD

**Issue by ncodee** [home-assistant/iOS#2450]
Model Name: MacBook Air 2022
macOS Version: 14.2 Beta (23C5041e)
App Version: 2023.7 (2023.471
Safari Version: 17.2 (19617.1.13.11.1)

**Home Assistant Core Version**
2023.11.2

**Describe the bug**
Conditional Cards stop working randomly on the Mac companion app and show as 'Conditions are Invalid'. However, when you force close the HA app and relaunch they reappear as normal.

**To Reproduce**
- Launch Home Assistant for Mac app
- Random occurrence

**Expected behaviour**
Load Conditional card without errors

**Screenshots**
![Screenshot 2023-11-11 at 19 30 14](https://github.com/home-assistant/iOS/assets/52791179/b09f15ad-b209-4fa1-9e9c-85fad85e4921)

**Additional context**
Issue persists with stable version of macOS Sonoma, and works perfectly fine on Safari and other browsers. The Mac companion app is buggy and needs some overdue attention.

**Comment by bgoncal** [comment]
If you open it in safari, do they work? Could you share a video on how it behaves in safari and how it behaves in the app?

**Comment by bgoncal** [comment]
Feel free to reopen this issue if needed
