### ISSUE TITLE
isOnInternalNetwork should also use local push status instead of location permission

### ISSUE THREAD

**Issue by Cyberbeni** [home-assistant/iOS#2455]
**iOS device model, version and app version**
Model Name: iPhone 11 Pro
Software Version: 17.1.1
App version: 2023.7

**Home Assistant Core Version**
2023.11.2

**Describe the bug**
I've set up Tailscale to run when I'm not connected to my home wifi.
I've set up local push connectivity in Home Assistant and disabled location permissions.
If I add the Tailscale IP of the machine as external URL, Home Assistant always tries to connect through the external URL even when I'm on my home wifi, thus not connected to Tailscale.
As can be seen here, isOnInternalNetwork is querying the SSID name, which requires GPS permission:
https://github.com/home-assistant/iOS/blob/47425ef071456b55486e55ebef05456e270a80a7/Sources/Shared/API/ConnectionInfo.swift#L242-L254
It would be better that in case of local push is turned on, we prefer using its status for checking if we are on an internal SSID:
https://github.com/home-assistant/iOS/blob/47425ef071456b55486e55ebef05456e270a80a7/Sources/App/Notifications/NotificationManagerLocalPushInterfaceExtension.swift#L21-L34

**To Reproduce**
see description

**Expected behavior**
see description

**Screenshots**

**Additional context**

**Comment by Cyberbeni** [comment]
The workaround I found is to add "myserver.tail1234.ts.net" on the pihole local dns settings to point to the local IP address and use that as the external server.

**Comment by Cyberbeni** [comment]
SCNetworkReachability might also be worth trying out: https://github.com/ashleymills/Reachability.swift/blob/a81b7367f2c46875f29577e03a60c39cdfad0c8d/Sources/Reachability.swift#L140-L148

**Comment by Cyberbeni** [comment]
I usually categorize "unnecessary permission" type of issues as bug. But since it technically works, some might categorize it as improvement.

**Comment by bgoncal** [comment]
> I usually categorize "unnecessary permission" type of issues as bug. But since it technically works, some might categorize it as improvement.

I agree with you, we should avoid unnecessary permission, but we haven't validated that your approach would work without any other issues, so we consider what we have a working/tested version and your suggestion as improvement.

Good opportunity to open a PR showing the improvement, let me know if you need help running the app on your machine

**Comment by bgoncal** [comment]
We use GitHub for tracking issues, not for providing support or tracking feature requests, for that reason I'll be closing this issue for now.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
