### ISSUE TITLE
`clear_notification` message will not update badge value over cellular (outside local push?)

### ISSUE THREAD

**Issue by jamieshaw** [home-assistant/iOS#2462]
**iOS device model, version and app version**
Model Name: iPhone 15 Pro Max
Software Version: iOS 17.1.1
App version: 2023.7 (2023.471)

**Home Assistant Core Version**
Home Assistant Core 2023.10.5
(Frontend 20231005)

**Describe the bug**
When pushing a `badge` value as part of a `clear_notification` message, if connected to Wi-Fi and using local push, the notification is dismissed and the badge value updated.
When connected to cellular, the notification is cleared but the badge value remains unchanged (regardless if 0 or above).

**To Reproduce**
```yaml
service: notify.jamie
data:
    title: 'Home Assistant'
    message: 'clear_notification'
    data:
        push:
            badge: 99
```

**Expected behavior**
Consistent behaviour either setting the value or not — preferably, `clear_notification` will allow badge updates silently in the background.
(I'm aware of `delete_alert`, which is similar, but different. It does not clear the notification unless setting the badge to 0 — clearing _all_ notifications).

**Screenshots**
https://www.dropbox.com/scl/fi/5qb47a3xjjfwfdma4cnke/home_assistant_notification_bug.MP4?rlkey=h2lcwj63invrub7jmktlt3jzs&dl=0
(Video showing push over Wi-Fi, then failing over cellular, and the successfully back on Wi-Fi)

**Additional context**
In the above video `notify.jamie` is a group notifier that links 3 `mobile_app` notifiers.

**Comment by jamieshaw** [comment]
So as of Home Assistant Companion (for iOS) 2023.12.1 (2023.508), this appears to have been resolved.  I can no longer get badges of any value to display regardless of connection type.

Unfortunately, not the desired outcome of allowing badging of `clear_notification` messages, but consistent now, nonetheless.

**Comment by jamieshaw** [comment]
So as of Home Assistant Companion (for iOS) 2023.12.1 (2023.508), this appears to have been resolved.  I can no longer get badges of any value to display regardless of connection type.

Unfortunately, not the desired outcome of allowing badging of `clear_notification` messages, but consistent now, nonetheless.

**Comment by jamieshaw** [comment]
I take it back — having some weird notification issues where dynamic actions where not populating — restarting the phone _fixed_ dynamic actions but reintroduced the same bug here the badge value is not updated over cellular for `clear_notification`.

**Comment by lesgrebe** [comment]
+1 for me - using `clear_notification` long time to clear messages which a not usable any more, for example if I come home I perform an actionable notification to unlock my door via my appe watch but if Im unlocking my door manual I clear this message because its not useful any more. `clear_notification`  now only works if Im in my home network, not over cellular as mentioned in the comment above.

iPhone 13 Pro (iOS 17.3.1)
Home Assistant Companion-App 2024.1

Hardware:
Raspberry Pi 4 8GB

Home Assistant:
Core
2024.2.1
Supervisor
2024.01.1
Operating System
11.5
Frontend
20240207.1
