### ISSUE TITLE
Blank screen after back button

### ISSUE THREAD

**Issue by nicdive** [home-assistant/iOS#2474]
Hi,

Bug report on iOS 17.1.2 with iPhone 15 pro
Companion app 2023.47
When navigating with back button, I get sometimes a blank Home dashboard or part blank on the top side of the app. If I just touch the screen everything appears.
with safari no such problem.
Regards

**Comment by bgoncal** [comment]
Can you share a short video that shows the issue?

**Comment by bgoncal** [comment]
Closing for now, feel free to reopen and add more details.
