### ISSUE TITLE
iOS app v2023.12 instantly crashing / will not open 

### ISSUE THREAD

**Issue by keckrich** [home-assistant/iOS#2493]
Model Name: iPhone 11
Software Version: iOS 14.6
App version: 2023.12

**Describe the bug**
After updating the app from 2023.7 to 2023.12 I can no longer open it. It just instantly crashes. I tried restarting my device, but that did not help. When I restored my phone to version 2023.7 it worked again.

**Comment by EyalRotem** [comment]
I have the same issue. 
iphone 11 pro on 14.8. jailbroken with taurine.

when not in a jailbroken mode - it loads as it should.

after jailbreaking - instant crash.

while i realize a jailbreak adds more variables to the mix - I see  no reason it shouldn't work. as many many other apps work whether or not jailbroken.
Also, as HA is mainly used by tinkerers - some will probably use a jailbroken device =] 


to add more info - even when trying to run the app without tweak injection (using choisy or libhooker configurator - it still crashes.

**Comment by EyalRotem** [comment]
i checked on another iphone - 6s with 14.1 and jailbroken by taurine as well - doesn't crash

**Comment by dhrto** [comment]
Same here, after update from 2023.7 to 2023.12 this morning, the app won't launch. It seems like to launches (brief screen switch) and then back to the Ipad's app screen. Ipad mini 2, iOS 12.5.7, NOT jailbroken.

Is there a way to revert to 2023.7?

**Comment by zacwest** [comment]
Please attach crash logs. You can find them in the system Settings app under Privacy > Analytics > Analytics Data > search for HomeAssistant

**Comment by EyalRotem** [comment]
I have no logs there. Also, when installing Cr4shed from Sileo, it also has no crash logs.
Anything else ? I have access to all the device files

**Comment by dhrto** [comment]
Apparently I had to enable sharing crash logs first, before any crash log is generated at all (phrasing in iOS could be better). Please see attached:

[Home Assistant-2023-12-29-190932 - Copy.txt](https://github.com/home-assistant/iOS/files/13795460/Home.Assistant-2023-12-29-190932.-.Copy.txt)

**Comment by keckrich** [comment]
Here is my crash log:


[Home_Assistant-2023-12-27-090842.txt](https://github.com/home-assistant/iOS/files/13797111/Home_Assistant-2023-12-27-090842.txt)

**Comment by grahamr** [comment]
Model Name: iPad Air 1
Software Version: iPadOS 12.5.7
App version: 2023.12

crash log attached. 
[Home Assistant-2023-12-30-134607.log](https://github.com/home-assistant/iOS/files/13798830/Home.Assistant-2023-12-30-134607.log)

**Comment by Joshbloam** [comment]
Same issue here! My dashboard is down :(

![image](https://github.com/home-assistant/iOS/assets/10256258/e078c69f-d7e3-4177-8188-0013098c6912)

Apple iPad Air
IOS 12.5.7
Companion app: 2023.12 (most recently worked with 2023.7)

Home Asisstant
Core: 2023.12.4
Supervisor: 2023.12.0
Operating System: 11.2
Frontend: 20231208.2

**Comment by Joshbloam** [comment]
Does anyone have the ios IPA file for version 2023.7?

**Comment by jpoon** [comment]
Ditto. My experience is the same as others. v2023.12 crashes on app launch. 

Crash Dump: [Home Assistant-2023-12-31-175717.log](https://github.com/home-assistant/iOS/files/13802758/Home.Assistant-2023-12-31-175717.log)

I am running this on an iPad Mini 2 with iOS12. As per v2023.12 release notes: `This is the last release for iOS 12, 13, and 14; more information is available when you open the App.` so it'd be great if this we get a bug fix to get the app in a working state before it is fully deprecated for older versions of iOS.

**Comment by jpoon** [comment]
(Preface: I am *not* an iOS developer by any means so this is me just Googling around). 

It looks like one of the major changes in the current release is upgrading from xcode 14 -> 15. xcode 15 has this in their release notes:  https://developer.apple.com/documentation/xcode-release-notes/xcode-15-release-notes#Linking

> Binaries using symbols with a weak definition *crash at runtime on iOS 14/macOS 12 or older*. This impacts primarily C++ projects due to their extensive use of weak symbols. (114813650) (FB13097713)
> 
> Workaround: Bump the minimum deployment target to iOS 15, macOS 12, watchOS 8 or tvOS 15, or add -Wl,-ld_classic to the OTHER_LDFLAGS build setting.

**Comment by kcoffau** [comment]
Another +1 for iOS 12.5.7

I appreciate its old ios and hardware but that it what we use for panels around home.  I’m not spending $1k to replace each panel because of code.

Hopefully this is just a code cleanup

**Comment by bgoncal** [comment]
I'll be investigating the issue today

**Comment by bgoncal** [comment]
> (Preface: I am _not_ an iOS developer by any means so this is me just Googling around).
> 
> I see that one of the major changes in the current release is upgrading from xcode 14 -> 15. xcode 15 has this in their release notes: https://developer.apple.com/documentation/xcode-release-notes/xcode-15-release-notes#Linking
> 
> > Binaries using symbols with a weak definition * **crash at runtime on iOS 14/macOS 12 or older** * (emphasis mine). This impacts primarily C++ projects due to their extensive use of weak symbols. (114813650) (FB13097713)
> > Workaround: Bump the minimum deployment target to iOS 15, macOS 12, watchOS 8 or tvOS 15, or add -Wl,-ld_classic to the OTHER_LDFLAGS build setting.
> 
> Based on https://developer.apple.com/forums/thread/736214 and https://developer.apple.com/forums/thread/738317 of other users reporting their xcode15-built apps crashing on ios12, they have a similar stack trace (ie. seg fault / EXC_BAD_ACCESS) to what I'm seeing on the v2023.12 crash. In addition, based on the other user reports on this GH issue, the crash is impacting iOS12 and iOS14 devices which aligns with the above xcode linking issue.

It's indeed something related to Xcode, I ran the app again on Xcode 14.3.1 and it works. Unfortunately the workaround recommended by Apple is not working, I'll keep digging.

**Comment by bgoncal** [comment]
Update: Apple's workaround also needed to be done in one of our dependencies (Realm), I'll prepare a 2023.12.1

**Comment by jpoon** [comment]
@bgoncal thanks for the quick turnaround. Glad to hear it was a (relatively) simple bug / fix.

**Comment by ildar170975** [comment]
iPhone 5S, iOS 12.5.7 - crash with 2023.12.1
iPad Air 2, iOS 15.7.9 - OK

**Comment by bgoncal** [comment]
> iPhone 5S, iOS 12.5.7 - crash with 2023.12.1
> 
> iPad Air 2, iOS 15.7.9 - OK

Can you share the logs? I have been testing on an iPhone 6 iOS 12.5.7 and it has been working fine.

You can also try to delete and reinstall the app if this I ok for you.

**Comment by kcoffau** [comment]
I'm on iPad Air 1, iOS 12.5.7, app 12.1 and I'm back online 

Thank you

**Comment by ildar170975** [comment]
@bgoncal 
> You can also try to delete and reinstall the app if this I ok for you.

Thanks for a feedback!
I could not realize how to retrieve a log if App is not started.
What helped me: uninstall the App, install - and it works again!

**Comment by keckrich** [comment]
Deleting the old version and then updating the app worked. Thanks!

**Comment by EyalRotem** [comment]
IPhone 12 Pro, iOS 14.8, jailbroken with taurine:
Working again on 2023.12.1

thanks for the fast response!

**Comment by dhrto** [comment]
iPad mini 2, iPhone OS 12.5.7. 
I can confirm 2023.12.1 my dashboard is working again. Thanks for the quick fix!

**Comment by Janver448** [comment]
The same for me.

iPad mini 2, iOS 12.5.7.
I can confirm 2023.12.1 my dashboard is working again. Thanks for the quick fix!
