### ISSUE TITLE
Buttons look weird (WatchOS)

### ISSUE THREAD

**Issue by m1ke-hub** [home-assistant/iOS#2494]
**iOS device model, version and app version**

Model Name: Apple Watch Ultra 2
Software Version: 10.2
App version: 2023.12

**Home Assistant Core Version**
2023.12.4

**Describe the bug**
The corners of the buttons within the app on the watch look kinda weird.

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot](https://github.com/home-assistant/iOS/assets/57773976/ee71cdfc-cac7-4b94-ad98-dc2c8fe1728d)

**Additional context**

**Comment by bgoncal** [comment]
Can you check the latest Beta?

**Comment by m1ke-hub** [comment]
Sorry for the late reply. Just tested and it's still the same:

![image](https://github.com/home-assistant/iOS/assets/57773976/44bd2882-0cfc-43ba-9204-e49e9ffe8bc6)

**Comment by bgoncal** [comment]
Thats weird, I can't find a way to reproduce it, if you reinstall the watch app does it stays the same? I have an Apple Watch Ultra 2 and it looks good 
![watch](https://github.com/home-assistant/iOS/assets/5808343/8ec4f99a-8cbd-4b9d-81c1-6f399ce5daab)

If you change the action content does it has any impact on the UI?

**Comment by m1ke-hub** [comment]
Thanks for your feedback and time. I reinstalled the app and all is good now! Sorry for not trying earlier - I was under the impression switching from/to beta would be kind of the same as reinstalling..
