### ISSUE TITLE
Notification opening HA app with specific landing point

### ISSUE THREAD

**Issue by tinglis1** [home-assistant/iOS#250]
One thing I would like to see is when you open a notification that you can specify where in the app you want it to land.

For instance. When I get a image sent to my phone when there is motion at my door. I can view the image in the notification but if I open the app from the notification it takes me to the main page of the HA app.
It would be nice if I could specify something like a navigation path in Lovelace, so when it opens the HA app it takes me to my security page or the stream for my camera.

**Comment by jimz011** [comment]
I too was wondering if this would be possible.

**Comment by gregschwartz** [comment]
+1 on this request!

**Comment by tinglis1** [comment]
Any update on this?
The 2.0 app is awesome and this would really make it perfect for me.
In particular the other non-technical users of the app in my household would be the real target users. 

I figure there is two main types of landing page. A Lovelace navigation path or an entity panel. 

Some example use cases I could use right now are:
- motion notification could open a camera entity or security page
- temperature notification could open the entity to show history
- temperature notification could take you too climate control page.

**Comment by TomBrien** [comment]
This is similar to what is being discussed in #643
