### ISSUE TITLE
SIM/network Details are not populated in the sensors with the latest IOS app version.

### ISSUE THREAD

**Issue by schettada** [home-assistant/iOS#2503]
SIM Details are not populated in the sensors with the latest IOS app version.

**iOS device model, version and app version**
Model Name: iPhone 15 Pro Max, iPhone 14 Pro Max
Software Version: 17.1.2
App version: 2023.12.1 (2023.508)

**Home Assistant Core Version**
Core: 2023.12.4
Supervisor: 2023.12
OS: 11.2
Frontend: 20231208.2

**Describe the bug**

With the latest IOS app, the sim details are not populated in the sensors with mobile app is configured. The last this sensor updated was on Dec 28th. 

**To Reproduce**

Check the sensor details in IOS app and in the mobile app integration .

**Expected behavior**
SIM card/network details should be listed as it was working before.

**Screenshots**
![Screenshot 2024-01-03 at 07 48 31](https://github.com/home-assistant/iOS/assets/16140432/1d598977-1fd1-4e2a-8885-4f98b8613f3b)
![IMG_1859](https://github.com/home-assistant/iOS/assets/16140432/416d695c-2e89-4ec5-b0c7-db2c0ab29f9e)
![Screenshot 2024-01-03 090427](https://github.com/home-assistant/iOS/assets/16140432/1366d3ef-25c6-427e-a0b9-4737cd527bce)

**Additional context**

**Comment by bgoncal** [comment]
Unfortunately there is nothing we can do on App side right now, apparently the API was deprecated by Apple, leaving many people frustrated with the change and no alternative for now:
https://developer.apple.com/forums/thread/714876
