### ISSUE TITLE
Actions in notifications stoped work after app update

### ISSUE THREAD

**Issue by PaveLGIL** [home-assistant/iOS#2507]
**iOS device model, version and app version**

Model Name: iPhone 15 Pro
Software Version: 17.2.1
App version: 2023.12.1 (2023.508)

**Home Assistant Core Version**

2024.1.0 (but actions in notifications stoped work after application update, on previous core version)

**Describe the bug**
Actions in notifications stoped work after update app
My configuration:
![Screenshot 2024-01-04 at 09 58 40](https://github.com/home-assistant/iOS/assets/15833990/5e961d7f-ee7d-4c6c-816a-8a01090c69cd)
But, I stoped to see actions:
![IMG_1903](https://github.com/home-assistant/iOS/assets/15833990/3d4c84a4-0b13-4760-9686-0222075a9677)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by PaveLGIL** [comment]
Sorry, I will close the issue, iPhone reboot helped.

**Comment by Joao-Sousa-71** [comment]
Have exactly the same problem and was also not possible to view the attachments. Reboot iPhone fix it. Hope this will help somebody.
