### ISSUE TITLE
User agent IOS app is blocked by Google

### ISSUE THREAD

**Issue by albertbeuker** [home-assistant/iOS#2531]
I’ve Cloudflare Zero trust in front of my HA installation. I use Google Signin to authenticate in Cloudflare. However the authentication call is blocked by Google with a 403: Disallowed_useragent.

It works fine using safari or Chrome on IOs

Can you make sure to set the user agent to a valid one or make it a config option?

**Comment by bgoncal** [comment]
Hey @albertbeuker, thanks for reaching out, at this moment the setup you have in Cloudflare + Google Signin is not something we support or are aiming to support in the near future, but I have brought your concern to the rest of the team and if anything changes I will update this issue.

**Comment by rubinghv** [comment]
Can this issue be revisited? It really doesn't want seem difficult to fix it based on recent changes in iOS: https://github.com/nextauthjs/next-auth/issues/7044#issuecomment-2351147550 (https://felixcarmona.com/solving-google-login-issues-linkedin-ios/)

**Comment by jaredbrogan** [comment]
Can we please reevaluate this? It does appear that this is a simple fix to implement and would be appreciated by several in the community.

**Comment by YarekTyshchenko** [comment]
Please reconsider this. I assume reasons for closing this is that workaround exists using the paid remote access offering...

**Comment by SirKitboard** [comment]
+1
Running into the same issue when trying use OAuth to login. Would love to see this fixed when the fix is so simple

**Comment by Varrial** [comment]
Hi, I got exact same problem, but iPad and Mac app works

**Comment by mattonthenet** [comment]
Adding a +1 to a reconsideration. Getting a OTP via email as a workaround is _fine_ but not my preferred method. 

Still a problem as of 2026.2.1 (2026.1766)

**Comment by polmonta** [comment]
+1. 
I would greatly appreciate it, considering it should be a simple fix. Thanks!
