### ISSUE TITLE
iOS12 / iPad mini: App crashes on startup

### ISSUE THREAD

**Issue by umrath** [home-assistant/iOS#2533]
**Additional context**

**Comment by bgoncal** [comment]
Which version for the App are you using?
Does it crash right away or you see something before it crashes?
Reinstalling the App solves the issue?

**Comment by umrath** [comment]
The latest stable: 2023.12
It crashes pretty much right away within a split second.

**Comment by bgoncal** [comment]
> The latest stable: 2023.12
> It crashes pretty much right away within a split second. 

There is 2023.12.1 available, have you updated?

**Comment by umrath** [comment]
Well, I updated 2 days ago, so it was probably 2023.12.1 already.

However, I have been able to fix the issue myself now by deleting the app and reinstalling it.
