### ISSUE TITLE
Device_tracker don't work correctly

### ISSUE THREAD

**Issue by alexsaas** [home-assistant/iOS#2536]
Since an update from the end of December, the device_tracker of the mobile app (iOS) no longer works as it has before. I can't verify if it was triggered by the core update 2013.12 or the App-Update 2023.12. But since then (and now iOS 17.2.1, Home Assistant and App up-to-date), the device_tracker always shows home, even if I or the iPhone are not at home.

**Comment by bgoncal** [comment]
Even if you open the app when you are not at home it doesn't update? Can you double check location permission, disable & enable

**Comment by alexsaas** [comment]
Thanks for the reply. I haven't set up remote access for Home Assistant. From the beginning and it still worked without it with 2023.12.1 and for the iOS app all accesses are enabled.

**Comment by alexsaas** [comment]
To be honest, I don't know how it worked either. But I know 100% that it worked. With exactly the setting described. Before updating Home Assistant to 2024.1, updating the mobile app and updating iOS. It's a pity that I don't noticed it during one of these events. That's how I could not have narrowed it down. Luckily, I haven't set up automation with device_tracker yet, but I plan to do so at some point. Or rather, had.

**Comment by alexsaas** [comment]
Addendum: I had explained it to myself so far that Home Assistant notices through other entities of the app integrations that the iPhone is no longer in the network or the home zone.

I just checked it again, in the settings of the app under Location History is logged, as a significant location change that the home zone was left and re-entered. Was this perhaps synchronized with device_tracker when I arrived back?

I'll try to allow access to the movement data (motion and fitness) in the app. Maybe that will help.

**Comment by alexsaas** [comment]
Okay, access to the motion and fitness sensor didn't help. It was just trial and error. 

When I think about it, it sounds logical that without remote access, the Home Assistant app can't report that iPhone is not at home. But I'm not crazy. I swear it worked before!

**Comment by bgoncal** [comment]
> Okay, access to the motion and fitness sensor didn't help. It was just trial and error. 
> 
> When I think about it, it sounds logical that without remote access, the Home Assistant app can't report that iPhone is not at home. But I'm not crazy. I swear it worked before!

@zacwest do we have a logic like " if not reachable consider the person away" ?

**Comment by alexsaas** [comment]
Thanks for continuing your research. I'm starting to doubt myself. 🫣

**Comment by zacwest** [comment]
> @zacwest do we have a logic like " if not reachable consider the person away" ?

No. The `device_tracker` is only updated from the app phoning home via the webhook. It is possible the state restored on core startup would be different, but there's not timeout from being away or anything like that.

**Comment by alexsaas** [comment]
Thank you very much for your support and time. I don't have the Home Assistant Cloud, Cloudflare, or other cloud services active in Home Assistant. Only iCloud on the Apple devices. 

If it doesn't seem to be technically possible, I must have been very wrong. I can't believe it. I guess I'll have to go to the doctor. Sorry I must have been so wrong. And thanks again to both of you for the help.
