### ISSUE TITLE
sensor.<iphone>_ssid not updating when app is closed

### ISSUE THREAD

**Issue by Mnemonic0** [home-assistant/iOS#2538]
Model Name: Iphone 14 pro
Software Version:  17.2.1
App version: 2023.12.1

**Home Assistant Core Version**
2024.1.2

**Describe the bug**
sensor.<iphone>_ssid is not updating when the app is closed.

**To Reproduce**
1- open the companion app.
2- connect to a wifi network.
3- close the companion app.
4- turn off wifi
5- check on a different device that sensor.<iphone>_ssid status is still connected

**Expected behavior**
on step 5, sensor.<iphone>_ssid should have "Not Connected" status.

**Comment by bgoncal** [comment]
Can you double check if "Local Push" is enabled?

**Comment by Mnemonic0** [comment]
It was actually disabled, and that solved the issue. Thanks for pointing me in the right direction :)
