### ISSUE TITLE
CarPlay shows only first 12 Areas, can't navigate to see more

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/iOS#2542]
**iOS device model, version and app version**
Model Name: iPhone 15 Pro
Software Version: 17.3
App version: 2024.1 (2024.535) Testflight

**Home Assistant Core Version**
2024.1.5

**Describe the bug**
Current CarPlay UI limits to 12 items per page with back/forward arrows located in top right corner to navigate pages. This works fine on the "Control" tab but since "Areas" is top-level it displays the top tab bar where those arrows normally are. If you have more than 12 areas you cannot access all of them in current CarPlay UI.

Note: I would assume the "Actions" tab would probably have this same navigation issue as well, but I have less than 12 actions and no time to test at the moment.

(Really nice job on this feature btw!)

**To Reproduce**
Have more than 12 areas and try to view them all in CarPlay

**Screenshots**
Below screenshot shows the end of "page 1" with no way of navigating to "page 2" to see more of my areas such as Office, Patio, Upstairs Hallway etc.

![IMG_9620](https://github.com/home-assistant/iOS/assets/9065557/341655a7-400b-461f-a145-66b54ebe80d4)

**Comment by bgoncal** [comment]
Thanks for the feedback

**Comment by bgoncal** [comment]
https://github.com/home-assistant/iOS/pull/2543
