### ISSUE TITLE
Crash when integrating an iframe with basic auth security

### ISSUE THREAD

**Issue by rdlvm** [home-assistant/iOS#2546]
After seeing this problem for Android, I have the same problem on iOS and to this day the problem continues to appear

https://github.com/home-assistant/android/issues/1218

Same problem in the iOS application, when I add some access as a valetudo to the iframe homeassistant (the authentication is a pop-up window and is not embedded in the web)

No solution here?

**Comment by bgoncal** [comment]
Could you share a video of how it behaves in safari? 

Currently the app doesn't support with popups neither has plans to do so

**Comment by bgoncal** [comment]
Feel free to reopen if needed
