### ISSUE TITLE
Immediate crash on MacOS 12.7.3

### ISSUE THREAD

**Issue by jsiemek** [home-assistant/iOS#2550]
**Device model, version and app version**

Model Name: MacBookAir7,2
macOS Version: 12.7.3
App Version: 2024.535
Safari Version: Version 17.3 (17617.2.4.11.9, 17617)

**Home Assistant Core Version**
2024.1.5

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Home Assistant [4763]
Path:                  /Applications/Home Assistant.app/Contents/MacOS/Home Assistant
Identifier:            io.robbie.HomeAssistant
Version:               2024.1 (2024.535)
App Item ID:           1099568401
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-01-27 20:59:41.5324 +0100
OS Version:            macOS 12.7.3 (21H1015)
Report Version:        12
Anonymous UUID:        

Sleep/Wake UUID:       32FAB03D-89B1-4E2C-BC50-BB3E7140C351

Time Awake Since Boot: 2300 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: '/System/Library/Frameworks/ThreadNetwork.framework/Versions/A/ThreadNetwork'
Referenced from: '/Applications/Home Assistant.app/Contents/MacOS/Home Assistant'
Reason: tried: '' (no such file), '/System/Library/Frameworks/ThreadNetwork.framework/Versions/A/ThreadNetwork' (no such file)
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	       0x11cd1b9a2 __abort_with_payload + 10
1   dyld                          	       0x11cd31ab2 abort_with_payload_wrapper_internal + 80
2   dyld                          	       0x11cd31ae4 abort_with_payload + 9
3   dyld                          	       0x11ccdf699 dyld4::halt(char const*) + 615
4   dyld                          	       0x11ccdb5b5 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3995
5   dyld                          	       0x11ccda4e4 start + 388

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000002000209  rbx: 0x0000000000000000  rcx: 0x00007ff7b100c4b8  rdx: 0x00007ff7b100c920
  rdi: 0x0000000000000006  rsi: 0x0000000000000001  rbp: 0x00007ff7b100c500  rsp: 0x00007ff7b100c4b8
   r8: 0x00007ff7b100c520   r9: 0x0000000000000000  r10: 0x000000000000009f  r11: 0x0000000000000246
  r12: 0x000000000000009f  r13: 0x00007ff7b100c920  r14: 0x0000000000000001  r15: 0x0000000000000006
  rip: 0x000000011cd1b9a2  rfl: 0x0000000000000246  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x02000209 
Trap Number:     133

Binary Images:
       0x11ccd5000 -        0x11cd40fff dyld (*) <cbcd7d35-e8e9-3e64-b80b-b254b042afbf> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=28.1M resident=0K(0%) swapped_out_or_unallocated=28.1M(100%)
Writable regions: Total=9540K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9540K(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
VM_ALLOCATE                         12K        3 
__DATA                            1808K       41 
__DATA_CONST                      1104K       35 
__LINKEDIT                        8512K       36 
__TEXT                            19.8M       35 
dyld private memory               1024K        1 
===========                     =======  ======= 
TOTAL                             96.0M      153 

-----------
Full Report
-----------

{"app_cohort":"2|date=1706383800000&sf=143478&tid=7b4273e23e23c26fe4144843675e984eedb8a9ba2a80de0f3f37c6ce0ef67411&ttype=e","app_name":"Home Assistant","app_version":"2024.1","timestamp":"2024-01-27 20:59:41.00 +0100","slice_uuid":"bef90aa9-01a8-3912-ba8b-9fc019a469a6","adam_id":"1099568401","build_version":"2024.535","platform":6,"bundleID":"io.robbie.HomeAssistant","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.7.3 (21H1015)","incident_id":"275440E1-DB1F-4287-822C-738054423F6A","name":"Home Assistant","is_beta":1}
{
  "uptime" : 2300,
  "procLaunch" : "2024-01-27 20:59:41.4178 +0100",
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookAir7,2",
  "procStartAbsTime" : 2330101282127,
  "coalitionID" : 2479,
  "osVersion" : {
    "train" : "macOS 12.7.3",
    "build" : "21H1015",
    "releaseType" : "User"
  },
  "captureTime" : "2024-01-27 20:59:41.5324 +0100",
  "incident" : "275440E1-DB1F-4287-822C-738054423F6A",
  "bug_type" : "309",
  "pid" : 4763,
  "procExitAbsTime" : 2330198982990,
  "cpuType" : "X86-64",
  "procName" : "Home Assistant",
  "procPath" : "\/Applications\/Home Assistant.app\/Contents\/MacOS\/Home Assistant",
  "bundleInfo" : {"CFBundleShortVersionString":"2024.1","CFBundleVersion":"2024.535","CFBundleIdentifier":"io.robbie.HomeAssistant"},
  "storeInfo" : {"storeCohortMetadata":"2|date=1706383800000&sf=143478&tid=7b4273e23e23c26fe4144843675e984eedb8a9ba2a80de0f3f37c6ce0ef67411&ttype=e","itemID":"1099568401","deviceIdentifierForVendor":"BA37188A-5E8C-5424-90D3-255DBA630CEA","thirdParty":true,"entitledBeta":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "io.robbie.HomeAssistant",
  "isBeta" : 1,
  "sleepWakeUUID" : "32FAB03D-89B1-4E2C-BC50-BB3E7140C351",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: '\/System\/Library\/Frameworks\/ThreadNetwork.framework\/Versions\/A\/ThreadNetwork'","Referenced from: '\/Applications\/Home Assistant.app\/Contents\/MacOS\/Home Assistant'","Reason: tried: '' (no such file), '\/System\/Library\/Frameworks\/ThreadNetwork.framework\/Versions\/A\/ThreadNetwork' (no such file)"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":40378,"threadState":{"r13":{"value":140701803268384},"rax":{"value":33554953},"rflags":{"value":582},"cpu":{"value":0},"r14":{"value":1},"rsi":{"value":1},"r8":{"value":140701803267360},"cr2":{"value":0},"rdx":{"value":140701803268384},"r10":{"value":159},"r9":{"value":0},"r15":{"value":6},"rbx":{"value":0},"trap":{"value":133},"err":{"value":33554953},"r11":{"value":582},"rip":{"value":4778473890,"matchesCrashFrame":1},"rbp":{"value":140701803267328},"rsp":{"value":140701803267256},"r12":{"value":159},"rcx":{"value":140701803267256},"flavor":"x86_THREAD_STATE","rdi":{"value":6}},"frames":[{"imageOffset":289186,"symbol":"__abort_with_payload","symbolLocation":10,"imageIndex":0},{"imageOffset":379570,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":80,"imageIndex":0},{"imageOffset":379620,"symbol":"abort_with_payload","symbolLocation":9,"imageIndex":0},{"imageOffset":42649,"symbol":"dyld4::halt(char const*)","symbolLocation":615,"imageIndex":0},{"imageOffset":26037,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3995,"imageIndex":0},{"imageOffset":21732,"symbol":"start","symbolLocation":388,"imageIndex":0}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4778184704,
    "size" : 442368,
    "uuid" : "cbcd7d35-e8e9-3e64-b80b-b254b042afbf",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 140703413248000,
  "size" : 19331678208,
  "uuid" : "86bc6103-e387-3a89-a90f-c8314d49a242"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=28.1M resident=0K(0%) swapped_out_or_unallocated=28.1M(100%)\nWritable regions: Total=9540K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9540K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8192K        1 \nVM_ALLOCATE                         12K        3 \n__DATA                            1808K       41 \n__DATA_CONST                      1104K       35 \n__LINKEDIT                        8512K       36 \n__TEXT                            19.8M       35 \ndyld private memory               1024K        1 \n===========                     =======  ======= \nTOTAL                             96.0M      153 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "5f72dc58705eff005a46b3a9",
      "factorPackIds" : {

      },
      "deploymentId" : 240000015
    },
    {
      "rolloutId" : "6112dda2fc54bc3389840642",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "620aec83b02b354d3afd2f50"
      },
      "deploymentId" : 240000145
    }
  ],
  "experiments" : [

  ]
}
}

**To Reproduce**
Just upgrade to 12.7.3

**Expected behavior**
Start Normally

**Additional context**
The app was working well on MacOS 12.7.2

**Comment by Spipora** [comment]
Not sure it is OS version related, I am having the same failure on macOS 12.7.2 (21G1974).

**Comment by drawgas** [comment]
Same issue. I see Home Assistant app updated itself this morning and stoped working after that

**Comment by dartheide** [comment]
Same here. macOS 12.7.2 file missing /System/Library/Frameworks/ThreadNetwork.framework/Versions/A/ThreadNetwork



-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Home Assistant [50910]
Path:                  /Applications/Home Assistant.app/Contents/MacOS/Home Assistant
Identifier:            io.robbie.HomeAssistant
Version:               2024.1 (2024.535)
App Item ID:           1099568401
App External ID:       862745403
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-02-02 23:15:21.7800 +0100
OS Version:            macOS 12.7.2 (21G1974)
Report Version:        12
Anonymous UUID:        076C64AA-C0B2-7AEC-2BA6-8172F39A9814

Sleep/Wake UUID:       0D258F53-DF5F-432D-84F0-8FF53EDFEFFB

Time Awake Since Boot: 130000 seconds
Time Since Wake:       252 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: '/System/Library/Frameworks/ThreadNetwork.framework/Versions/A/ThreadNetwork'
Referenced from: '/Applications/Home Assistant.app/Contents/MacOS/Home Assistant'
Reason: tried: '' (no such file), '/System/Library/Frameworks/ThreadNetwork.framework/Versions/A/ThreadNetwork' (no such file)
(terminated at launch; ignore backtrace)

**Comment by OnFreund** [comment]
I'm also seeing this with 12.7.3

**Comment by christianonpele** [comment]
yes. have the issue like above:

Process:               Home Assistant [1108]
Path:                  /Applications/Home Assistant.app/Contents/MacOS/Home Assistant
Identifier:            io.robbie.HomeAssistant
Version:               2024.2 (2024.544)
App Item ID:           1099568401
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               502

Date/Time:             2024-02-04 14:01:51.8576 +0700
OS Version:            macOS 12.7.3 (21H1015)
Report Version:        12
Bridge OS Version:     3.0 (14Y910)
Anonymous UUID:        


Time Awake Since Boot: 3600 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: '/System/Library/Frameworks/ThreadNetwork.framework/Versions/A/ThreadNetwork'
Referenced from: '/Applications/Home Assistant.app/Contents/MacOS/Home Assistant'
Reason: tried: '' (no such file), '/System/Library/Frameworks/ThreadNetwork.framework/Versions/A/ThreadNetwork' (no such file)
(terminated at launch; ignore backtrace)

**Comment by mirekmal** [comment]
Seems Apple instroduced Matter/Thread support in Mac OS 13 (Ventura), so perhaps all versions of Mac OS prior to Ventura will suffer from this issue?

**Comment by hughsaunders** [comment]
Could the thread library dependency be made optional so that older MacOs versions continue to be supported?

**Comment by hughsaunders** [comment]
Fow now, you can dowload 2023.7 to get the previous version of the Mac App working: https://github.com/home-assistant/iOS/releases/tag/release%2F2023.7%2F2023.471

**Comment by hughsaunders** [comment]
Looks like it is already conditional: https://github.com/home-assistant/iOS/blame/3ebd1e6c1f121e0a8e0bc094e0da6c4030d3d9f7/Sources/App/ThreadCredentialsSharing/ThreadClientService.swift#L21

But its a compile time condition, not a runtime condition. So builds & releases would have to be made that target older versions of macOs for this this to be effective.

**Comment by panoriega** [comment]
> Fow now, you can dowload 2023.7 to get the previous version of the Mac App working: https://github.com/home-assistant/iOS/releases/tag/release%2F2023.7%2F2023.471

Home Assistant 2023.12 works for me on macos 12.7.3
https://github.com/home-assistant/iOS/releases/tag/release%2F2023.12%2F2023.499

**Comment by bgoncal** [comment]
Please test the latest TestFlight build

**Comment by jsiemek** [comment]
For me, it works! Thank you!

**Comment by hughsaunders** [comment]
@bgoncal Works for me also, thanks :)

**Comment by bgoncal** [comment]
Feel free to reopen this issue if needed

**Comment by upamanyudas** [comment]
I've started to face the same problem with 2025.2 (1178) on macOS 15.3.2. Tried all the version (Mac App Store, Github & Testflight). As soon as I launch the app, it crashes and becomes unresponsive.
