### ISSUE TITLE
Launch screen iOS Does not work anymore since 2023.7

### ISSUE THREAD

**Issue by mat1th** [home-assistant/iOS#2552]
Model Name: Iphone
Software Version: 17.2
App version: 2024.1

**Home Assistant Core Version**
2024.1.5

**Describe the bug**
The[ Launch screen](https://developer.apple.com/documentation/xcode/specifying-your-apps-launch-screen/) of the app. Is full white. It does not contain the app logo anymore.

**To Reproduce**
1. Launch app from cold start
2. You see a full white screen

**Expected behaviour**
The launch screen contains the home assistant logo.

**Screenshots**
![photo_screen](https://github.com/home-assistant/iOS/assets/6486389/7d3a6e81-3212-43c3-8b81-5012e903df65)

**Additional context**
The issue appeared for the first time in version 2023.7.

**Comment by codyc1515** [comment]
Yep, seems to be the case.

**Comment by bgoncal** [comment]
Good catch, PR: https://github.com/home-assistant/iOS/pull/2559

**Comment by bgoncal** [comment]
Feel free to reopen this issue if needed

**Comment by mat1th** [comment]
Thank you for fixing it so quickly!
