### ISSUE TITLE
App is crashing upon closing the app from fullscreen

### ISSUE THREAD

**Issue by Poshy163** [home-assistant/iOS#2563]
Model Name: Macbook Air (M2)
macOS Version: 14.3 & 14.4 beta 1
App Version: 2024.535
Safari Version: 17.4 (19618.1.11.11.3)
Home Assistant Core Version: 2024.1.6

**To Reproduce**
When shutting the app from fullscreen, it "crashes" rather than shutting, providing this error:

> Termination Reason: Namespace SIGNAL, Code 5 Trace/BPT trap: 5
> Terminating Process: exc handler [7878]

**Video**
Link to google drive video demonstrating it from app being shut:
https://drive.google.com/file/d/1nQp7vHBijR-hAF3s8hl5sMyhCpwQXWXV/view?usp=sharing

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Home Assistant [7878]
Path:                  /Applications/Home Assistant.app/Contents/MacOS/Home Assistant
Identifier:            io.robbie.HomeAssistant
Version:               2024.1 (2024.535)
App Item ID:           1099568401
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-01-31 21:30:17.9092 +0000
OS Version:            macOS 14.4 (23E5180j)
Report Version:        12
Anonymous UUID:        

Sleep/Wake UUID:       C748A4E3-FEE6-40F8-A17A-BF28EC7634E1

Time Awake Since Boot: 30000 seconds
Time Since Wake:       170 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x000000019f2ca014

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [7878]

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libobjc.A.dylib               	       0x19f2ca014 object_getClass + 48
1   Foundation                    	       0x1a08844e4 _NSKeyValueObservationInfoGetObservances + 252
2   Foundation                    	       0x1a0f97f70 NSKeyValueWillChangeWithPerThreadPendingNotifications + 236
3   UIKitCore                     	       0x1d02e0bb0 -[UIWindowScene _updateEffectiveGeometryIfNeeded] + 184
4   UIKitCore                     	       0x1d02e3594 -[UISceneSizeRestrictions _setContentSize:requested:] + 116
5   UIKitMacHelper                	       0x1b91a74d4 -[UINSSceneViewController _updateSizeRestrictions] + 540
6   UIKitMacHelper                	       0x1b911a04c -[UINSSceneViewController updateViewConstraints] + 28
7   AppKit                        	       0x1a303ab48 -[NSView _updateConstraintsForSubtreeIfNeededCollectingViewsWithInvalidBaselines:] + 568
8   AppKit                        	       0x1a3046a88 __82-[NSView _updateConstraintsForSubtreeIfNeededCollectingViewsWithInvalidBaselines:]_block_invoke + 228
9   CoreAutoLayout                	       0x1a8020588 -[NSISEngine withBehaviors:performModifications:] + 88
10  AppKit                        	       0x1a303a9d8 -[NSView _updateConstraintsForSubtreeIfNeededCollectingViewsWithInvalidBaselines:] + 200
11  AppKit                        	       0x1a3a51bb8 __45-[NSView updateConstraintsForSubtreeIfNeeded]_block_invoke_2 + 52
12  CoreAutoLayout                	       0x1a8020588 -[NSISEngine withBehaviors:performModifications:] + 88
13  AppKit                        	       0x1a3cf4d48 -[NSView(NSConstraintBasedLayoutInternal) _withAutomaticEngineOptimizationDisabled:] + 48
14  AppKit                        	       0x1a303a790 __45-[NSView updateConstraintsForSubtreeIfNeeded]_block_invoke + 224
15  AppKit                        	       0x1a2ff950c NSPerformVisuallyAtomicChange + 108
16  AppKit                        	       0x1a303a6a4 -[NSView updateConstraintsForSubtreeIfNeeded] + 96
17  CoreAutoLayout                	       0x1a8020588 -[NSISEngine withBehaviors:performModifications:] + 88
18  AppKit                        	       0x1a3cf4d48 -[NSView(NSConstraintBasedLayoutInternal) _withAutomaticEngineOptimizationDisabled:] + 48
19  AppKit                        	       0x1a3cfe180 -[NSWindow(NSConstraintBasedLayoutInternal) updateConstraintsIfNeeded] + 176
20  AppKit                        	       0x1a2ffb4bc -[NSWindow _oldPlaceWindow:fromServer:] + 456
21  AppKit                        	       0x1a2ffa9c4 -[NSWindow _setFrameCommon:display:fromServer:] + 1832
22  AppKit                        	       0x1a3b1a2dc __74-[_NSExitFullScreenTransitionController setupWindowForAfterFullScreenExit]_block_invoke + 556
23  AppKit                        	       0x1a2ff950c NSPerformVisuallyAtomicChange + 108
24  AppKit                        	       0x1a3b1a0a4 -[_NSExitFullScreenTransitionController setupWindowForAfterFullScreenExit] + 96
25  AppKit                        	       0x1a3b1d2d8 __46-[_NSExitFullScreenTransitionController start]_block_invoke.47 + 52
26  AppKit                        	       0x1a3d06f14 ___NSMainRunLoopPerformBlockInModes_block_invoke + 44
27  CoreFoundation                	       0x19f779ad8 __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 28
28  CoreFoundation                	       0x19f7799ec __CFRunLoopDoBlocks + 356
29  CoreFoundation                	       0x19f778844 __CFRunLoopRun + 848
30  CoreFoundation                	       0x19f777e9c CFRunLoopRunSpecific + 608
31  HIToolbox                     	       0x1a9fc5190 RunCurrentEventLoopInMode + 292
32  HIToolbox                     	       0x1a9fc4fcc ReceiveNextEventCommon + 648
33  HIToolbox                     	       0x1a9fc4d24 _BlockUntilNextEventMatchingListInModeWithFilter + 76
34  AppKit                        	       0x1a2fb7860 _DPSNextEvent + 660
35  AppKit                        	       0x1a37a30f8 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 716
36  AppKit                        	       0x1a2faaba8 -[NSApplication run] + 476
37  AppKit                        	       0x1a2f81e4c NSApplicationMain + 880
38  AppKit                        	       0x1a31d3854 _NSApplicationMainWithInfoDictionary + 24
39  UIKitMacHelper                	       0x1b9116188 UINSApplicationMain + 972
40  UIKitCore                     	       0x1cf40376c UIApplicationMain + 148
41  Home Assistant                	       0x1000ff190 0x100008000 + 1012112
42  dyld                          	       0x19f3120e0 start + 2360

Thread 1:
0   libsystem_pthread.dylib       	       0x19f695d2c start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	       0x19f695d2c start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	       0x19f695d2c start_wqthread + 0

Thread 4:: com.apple.uikit.eventfetch-thread
0   libsystem_kernel.dylib        	       0x19f65a214 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x19f66cb44 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x19f662e54 mach_msg_overwrite + 476
3   libsystem_kernel.dylib        	       0x19f65a598 mach_msg + 24
4   CoreFoundation                	       0x19f77a0e8 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x19f7789ac __CFRunLoopRun + 1208
6   CoreFoundation                	       0x19f777e9c CFRunLoopRunSpecific + 608
7   Foundation                    	       0x1a08ac7d8 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8   Foundation                    	       0x1a09212f0 -[NSRunLoop(NSRunLoop) runUntilDate:] + 100
9   UIKitCore                     	       0x1cf404b38 -[UIEventFetcher threadMain] + 104
10  Foundation                    	       0x1a08a5cd0 __NSThread__start__ + 716
11  libsystem_pthread.dylib       	       0x19f69afa0 _pthread_start + 136
12  libsystem_pthread.dylib       	       0x19f695d40 thread_start + 8

Thread 5:
0   libsystem_pthread.dylib       	       0x19f695d2c start_wqthread + 0

Thread 6:: Realm notification listener
0   libsystem_kernel.dylib        	       0x19f660360 kevent + 8
1   Realm                         	       0x102a06f04 realm::_impl::ExternalCommitHelper::listen() + 156
2   Realm                         	       0x102a07054 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&, realm::RealmConfig const&)::$_0>>(void*) + 52
3   libsystem_pthread.dylib       	       0x19f69afa0 _pthread_start + 136
4   libsystem_pthread.dylib       	       0x19f695d40 thread_start + 8

Thread 7:: JavaScriptCore libpas scavenger
0   libsystem_kernel.dylib        	       0x19f65da0c __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x19f69b568 _pthread_cond_wait + 1228
2   JavaScriptCore                	       0x1e3b7d594 scavenger_thread_main + 1308
3   libsystem_pthread.dylib       	       0x19f69afa0 _pthread_start + 136
4   libsystem_pthread.dylib       	       0x19f695d40 thread_start + 8

Thread 8:
0   libsystem_pthread.dylib       	       0x19f695d2c start_wqthread + 0

Thread 9:
0   libsystem_pthread.dylib       	       0x19f695d2c start_wqthread + 0

Thread 10:
0   libsystem_pthread.dylib       	       0x19f695d2c start_wqthread + 0

Thread 11:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	       0x19f65a214 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x19f66cb44 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x19f662e54 mach_msg_overwrite + 476
3   libsystem_kernel.dylib        	       0x19f65a598 mach_msg + 24
4   CoreFoundation                	       0x19f77a0e8 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x19f7789ac __CFRunLoopRun + 1208
6   CoreFoundation                	       0x19f777e9c CFRunLoopRunSpecific + 608
7   AppKit                        	       0x1a30e0b5c _NSEventThread + 144
8   libsystem_pthread.dylib       	       0x19f69afa0 _pthread_start + 136
9   libsystem_pthread.dylib       	       0x19f695d40 thread_start + 8

Thread 12:: com.apple.NSURLConnectionLoader
0   libsystem_kernel.dylib        	       0x19f65a214 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x19f66cb44 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x19f662e54 mach_msg_overwrite + 476
3   libsystem_kernel.dylib        	       0x19f65a598 mach_msg + 24
4   CoreFoundation                	       0x19f77a0e8 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x19f7789ac __CFRunLoopRun + 1208
6   CoreFoundation                	       0x19f777e9c CFRunLoopRunSpecific + 608
7   CFNetwork                     	       0x1a4bef910 0x1a498f000 + 2492688
8   Foundation                    	       0x1a08a5cd0 __NSThread__start__ + 716
9   libsystem_pthread.dylib       	       0x19f69afa0 _pthread_start + 136
10  libsystem_pthread.dylib       	       0x19f695d40 thread_start + 8

Thread 13:: caulk.messenger.shared:17
0   libsystem_kernel.dylib        	       0x19f65a190 semaphore_wait_trap + 8
1   caulk                         	       0x1a9bc8624 caulk::semaphore::timed_wait(double) + 212
2   caulk                         	       0x1a9bc84d8 caulk::concurrent::details::worker_thread::run() + 36
3   caulk                         	       0x1a9bc81d8 void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*>>>(void*) + 96
4   libsystem_pthread.dylib       	       0x19f69afa0 _pthread_start + 136
5   libsystem_pthread.dylib       	       0x19f695d40 thread_start + 8

Thread 14:: caulk.messenger.shared:high
0   libsystem_kernel.dylib        	       0x19f65a190 semaphore_wait_trap + 8
1   caulk                         	       0x1a9bc8624 caulk::semaphore::timed_wait(double) + 212
2   caulk                         	       0x1a9bc84d8 caulk::concurrent::details::worker_thread::run() + 36
3   caulk                         	       0x1a9bc81d8 void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*>>>(void*) + 96
4   libsystem_pthread.dylib       	       0x19f69afa0 _pthread_start + 136
5   libsystem_pthread.dylib       	       0x19f695d40 thread_start + 8

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000600003a04870   x1: 0x0000600002175bf8   x2: 0x0000000000000000   x3: 0x000000016fdf5148
    x4: 0x0000000000000007   x5: 0x0000000000003020   x6: 0x0000600003a19b90   x7: 0x000000016fdf47d8
    x8: 0x0000b33b2d5d4870   x9: 0x4ea66c89caaa00b2  x10: 0x00000002c90ca9aa  x11: 0x000000000000003f
   x12: 0x0000000000000002  x13: 0x0000000131887610  x14: 0x01000002074d8ee9  x15: 0x00000002074d8ee8
   x16: 0x0000b33b2d5d4870  x17: 0x0000333b2d5d4870  x18: 0x0000000000000000  x19: 0x0000600003353020
   x20: 0x000000016fdf5210  x21: 0x0000000000000038  x22: 0x0000000000000007  x23: 0x000000016fdf5110
   x24: 0x0000000000000000  x25: 0x000000016fdf5188  x26: 0x0000000208f05000  x27: 0x0000600003a047e0
   x28: 0x0000000000000000   fp: 0x000000016fdf5200   lr: 0x00000001a08844e4
    sp: 0x000000016fdf5110   pc: 0x000000019f2ca014 cpsr: 0x20001000
   far: 0x0000000000000000  esr: 0xf200c472 (Breakpoint) pointer authentication trap DA

Binary Images:
       0x100408000 -        0x100413fff io.robbie.HomeAssistant.MacBridge (2024.1) <c30e139f-89fb-3552-9923-886945ad1218> /Applications/Home Assistant.app/Contents/Frameworks/Shared.framework/Versions/A/PlugIns/MacBridge.bundle/Contents/MacOS/MacBridge
       0x1013ec000 -        0x1013f7fff libobjc-trampolines.dylib (*) <097e9292-21ec-3a98-b39e-f87e804205e6> /usr/lib/libobjc-trampolines.dylib
       0x10094c000 -        0x100a47fff org.cocoapods.Alamofire (2024.1) <34967e14-5a7a-3681-a467-1e40f33664a8> /Applications/Home Assistant.app/Contents/Frameworks/Alamofire.framework/Versions/A/Alamofire
       0x1006d4000 -        0x1006e3fff org.cocoapods.CPDAcknowledgements (2024.1) <7afc4977-4717-355f-b484-5a672da53b75> /Applications/Home Assistant.app/Contents/Frameworks/CPDAcknowledgements.framework/Versions/A/CPDAcknowledgements
       0x10068c000 -        0x1006a3fff org.cocoapods.CallbackURLKit (2024.1) <94cbaf28-b964-3af2-a368-3e20af41997a> /Applications/Home Assistant.app/Contents/Frameworks/CallbackURLKit.framework/Versions/A/CallbackURLKit
       0x10076c000 -        0x100783fff org.cocoapods.ColorPickerRow (2024.1) <6cc0aef2-5d01-3206-b309-ada0498534ca> /Applications/Home Assistant.app/Contents/Frameworks/ColorPickerRow.framework/Versions/A/ColorPickerRow
       0x1007a0000 -        0x1007b7fff org.cocoapods.Communicator (2024.1) <35300ed3-7eb4-3c44-9004-2538e1d789c8> /Applications/Home Assistant.app/Contents/Frameworks/Communicator.framework/Versions/A/Communicator
       0x1007d0000 -        0x100897fff org.cocoapods.Eureka (2024.1) <e4e5e65a-ac5d-3e36-8095-1e0b8f2c7141> /Applications/Home Assistant.app/Contents/Frameworks/Eureka.framework/Versions/A/Eureka
       0x100914000 -        0x100923fff org.cocoapods.FBLPromises (2024.1) <305b972a-44d2-3d42-8866-7db2c38bdb4d> /Applications/Home Assistant.app/Contents/Frameworks/FBLPromises.framework/Versions/A/FBLPromises
       0x100aac000 -        0x100abffff org.cocoapods.FirebaseCore (2024.1) <8189ce83-4ad8-3457-ba5a-2b2d8c1f8e32> /Applications/Home Assistant.app/Contents/Frameworks/FirebaseCore.framework/Versions/A/FirebaseCore
       0x100ad8000 -        0x100af3fff org.cocoapods.FirebaseCoreInternal (2024.1) <7bb2b6d6-9e85-3885-b75d-c05d45dd0305> /Applications/Home Assistant.app/Contents/Frameworks/FirebaseCoreInternal.framework/Versions/A/FirebaseCoreInternal
       0x100b0c000 -        0x100b23fff org.cocoapods.FirebaseInstallations (2024.1) <aa171c8f-e90f-378f-b069-fdb56cbdf55a> /Applications/Home Assistant.app/Contents/Frameworks/FirebaseInstallations.framework/Versions/A/FirebaseInstallations
       0x1006f8000 -        0x10072ffff org.cocoapods.FirebaseMessaging (2024.1) <eb7c3761-7ede-3593-a97b-1b5b86544e78> /Applications/Home Assistant.app/Contents/Frameworks/FirebaseMessaging.framework/Versions/A/FirebaseMessaging
       0x100bec000 -        0x100c13fff org.cocoapods.GoogleDataTransport (2024.1) <7bbb4128-6594-3fd1-9a55-54dd8b381a21> /Applications/Home Assistant.app/Contents/Frameworks/GoogleDataTransport.framework/Versions/A/GoogleDataTransport
       0x100c40000 -        0x100c5bfff org.cocoapods.GoogleUtilities (2024.1) <192191ad-e1bc-32f6-aeef-c7ed2826a6f6> /Applications/Home Assistant.app/Contents/Frameworks/GoogleUtilities.framework/Versions/A/GoogleUtilities
       0x100b44000 -        0x100babfff org.cocoapods.HAKit (2024.1) <6e91cfc7-bf4e-3e59-b129-b7740c98383a> /Applications/Home Assistant.app/Contents/Frameworks/HAKit.framework/Versions/A/HAKit
       0x100d08000 -        0x100d2ffff org.cocoapods.KeychainAccess (2024.1) <2bc7c58d-164b-38aa-98d3-5af0dd48290d> /Applications/Home Assistant.app/Contents/Frameworks/KeychainAccess.framework/Versions/A/KeychainAccess
       0x1010dc000 -        0x101227fff org.cocoapods.Lottie (2024.1) <2ca0f051-17f2-3083-8c28-e77919c2f711> /Applications/Home Assistant.app/Contents/Frameworks/Lottie.framework/Versions/A/Lottie
       0x100cd0000 -        0x100cdffff org.cocoapods.MBProgressHUD (2024.1) <0ad818e5-f484-3b9d-9a17-f9f2c3001a4c> /Applications/Home Assistant.app/Contents/Frameworks/MBProgressHUD.framework/Versions/A/MBProgressHUD
       0x1006bc000 -        0x1006c3fff org.cocoapods.ObjcExceptionBridging (2024.1) <937a60bc-03de-390b-b4da-aafe517bc3f6> /Applications/Home Assistant.app/Contents/Frameworks/ObjcExceptionBridging.framework/Versions/A/ObjcExceptionBridging
       0x100c80000 -        0x100cabfff org.cocoapods.ObjectMapper (2024.1) <34e87725-a1c3-374e-83d3-fb3c2cd6b0d6> /Applications/Home Assistant.app/Contents/Frameworks/ObjectMapper.framework/Versions/A/ObjectMapper
       0x100e34000 -        0x100e7bfff org.cocoapods.PromiseKit (2024.1) <bd3a09b3-4b06-37ce-bb2a-4c553ec5293b> /Applications/Home Assistant.app/Contents/Frameworks/PromiseKit.framework/Versions/A/PromiseKit
       0x100d90000 -        0x100d9bfff org.cocoapods.Reachability (2024.1) <f4525b0a-dffb-33eb-a117-3b01d852452f> /Applications/Home Assistant.app/Contents/Frameworks/Reachability.framework/Versions/A/Reachability
       0x102630000 -        0x102c0ffff org.cocoapods.Realm (2024.1) <47d905c7-3452-38cd-9a6b-5b5138b49448> /Applications/Home Assistant.app/Contents/Frameworks/Realm.framework/Versions/A/Realm
       0x100ea8000 -        0x100f83fff org.cocoapods.RealmSwift (2024.1) <4e9419ae-69c9-3f2e-b72a-8f32bc5753f1> /Applications/Home Assistant.app/Contents/Frameworks/RealmSwift.framework/Versions/A/RealmSwift
       0x100db0000 -        0x100deffff org.cocoapods.Sodium (2024.1) <b6b632f4-2a91-3f32-8a27-81754bd7636e> /Applications/Home Assistant.app/Contents/Frameworks/Sodium.framework/Versions/A/Sodium
       0x1012a8000 -        0x1012d3fff org.cocoapods.Starscream (2024.1) <822ddb6e-f5a3-372d-9cb7-5489bf1965f4> /Applications/Home Assistant.app/Contents/Frameworks/Starscream.framework/Versions/A/Starscream
       0x10100c000 -        0x101047fff org.cocoapods.SwiftMessages (2024.1) <a8369c69-e9f0-3826-8fc8-affa08bd1814> /Applications/Home Assistant.app/Contents/Frameworks/SwiftMessages.framework/Versions/A/SwiftMessages
       0x100e10000 -        0x100e1bfff org.cocoapods.UIColor-Hex-Swift (2024.1) <26070278-4fb7-3d37-9a4e-33c4c59ca443> /Applications/Home Assistant.app/Contents/Frameworks/UIColor_Hex_Swift.framework/Versions/A/UIColor_Hex_Swift
       0x100d48000 -        0x100d57fff org.cocoapods.Version (2024.1) <96e218ef-19dc-3fce-bb21-f72b527e1386> /Applications/Home Assistant.app/Contents/Frameworks/Version.framework/Versions/A/Version
       0x100d6c000 -        0x100d77fff org.cocoapods.ViewRow (2024.1) <2e863c58-6b75-388c-818e-498377ab3d9e> /Applications/Home Assistant.app/Contents/Frameworks/ViewRow.framework/Versions/A/ViewRow
       0x101070000 -        0x10109bfff org.cocoapods.XCGLogger (2024.1) <29485d80-a716-3913-adee-2f63b0ce1edb> /Applications/Home Assistant.app/Contents/Frameworks/XCGLogger.framework/Versions/A/XCGLogger
       0x1013a0000 -        0x1013d3fff org.cocoapods.ZIPFoundation (2024.1) <ebfe6444-fb71-3582-918f-d7fe5349ed69> /Applications/Home Assistant.app/Contents/Frameworks/ZIPFoundation.framework/Versions/A/ZIPFoundation
       0x1010c0000 -        0x1010c7fff org.cocoapods.nanopb (2024.1) <79b77a1b-22b6-39c6-9064-61f03a653e16> /Applications/Home Assistant.app/Contents/Frameworks/nanopb.framework/Versions/A/nanopb
       0x101d68000 -        0x1020cffff io.robbie.HomeAssistant.Shared (2024.1) <520e387d-ad34-3c0a-8023-59cef3d438f5> /Applications/Home Assistant.app/Contents/Frameworks/Shared.framework/Versions/A/Shared
       0x100008000 -        0x100193fff io.robbie.HomeAssistant (2024.1) <5a00e554-f212-39bd-bbc2-6019fea4db65> /Applications/Home Assistant.app/Contents/MacOS/Home Assistant
       0x19f2bc000 -        0x19f30bd83 libobjc.A.dylib (*) <872a7ebc-024b-35f1-9501-3b0e0444066f> /usr/lib/libobjc.A.dylib
       0x1a0851000 -        0x1a14a5fff com.apple.Foundation (6.9) <3ebfe97a-07bf-35d2-ba01-d1c82385f042> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
       0x1cf400000 -        0x1d0d7dfff com.apple.UIKitCore (1.0) <3e873bac-0340-38aa-bf8c-97c180452fed> /System/iOSSupport/System/Library/PrivateFrameworks/UIKitCore.framework/Versions/A/UIKitCore
       0x1b9112000 -        0x1b9224fff com.apple.UIKitMacHelper (1.0) <652ac176-3df8-392b-8082-56a57c4370ea> /System/Library/PrivateFrameworks/UIKitMacHelper.framework/Versions/A/UIKitMacHelper
       0x1a2f7d000 -        0x1a42b0fff com.apple.AppKit (6.9) <c91af841-6ad4-38e8-96b3-6b3ed3db865c> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x1a8010000 -        0x1a8059fff com.apple.CoreAutoLayout (1.0) <4f567292-ea20-3f5a-9924-242a19eb39cc> /System/Library/PrivateFrameworks/CoreAutoLayout.framework/Versions/A/CoreAutoLayout
       0x19f6fc000 -        0x19fbd4fff com.apple.CoreFoundation (6.9) <77b96f8f-142d-3718-b8b5-b1873bb3cd7e> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
       0x1a9f95000 -        0x1aa254fff com.apple.HIToolbox (2.1.1) <bdbe400f-e63e-3ce4-93c3-92dca6905ae5> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
       0x19f30c000 -        0x19f39495b dyld (*) <754b0ee2-457c-3a5e-a67d-599700a9e1fc> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x19f694000 -        0x19f6a0fff libsystem_pthread.dylib (*) <00c2d151-841a-3548-9f2b-f3a7452d0501> /usr/lib/system/libsystem_pthread.dylib
       0x19f659000 -        0x19f693ffb libsystem_kernel.dylib (*) <7117f291-884e-3364-a204-71ba125faac2> /usr/lib/system/libsystem_kernel.dylib
       0x1e24f2000 -        0x1e3d55fff com.apple.JavaScriptCore (19618) <be75d16e-7004-38e3-9c64-1b5afe0e6837> /System/iOSSupport/System/Library/Frameworks/JavaScriptCore.framework/Versions/A/JavaScriptCore
       0x1a498f000 -        0x1a4d63fff com.apple.CFNetwork (1.0) <0fd547f0-439e-3ff7-9298-6d816e347e20> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
       0x1a9bc6000 -        0x1a9beffff com.apple.audio.caulk (1.0) <416b3626-0381-334e-887e-9fa4dd7d6d46> /System/Library/PrivateFrameworks/caulk.framework/Versions/A/caulk

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.4G resident=0K(0%) swapped_out_or_unallocated=1.4G(100%)
Writable regions: Total=5.8G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=5.8G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               128K        1 
Activity Tracing                   256K        1 
CG image                           192K       10 
CG raster data                      32K        1 
ColorSync                          592K       27 
CoreAnimation                      816K       48 
CoreGraphics                        32K        2 
CoreServices                       400K        2 
CoreUI image data                  976K        8 
Foundation                          32K        2 
Kernel Alloc Once                   32K        1 
MALLOC                             1.6G       71 
MALLOC guard page                  480K       30 
SQLite page cache                  512K        4 
STACK GUARD                       56.2M       15 
Stack                             15.4M       15 
VM_ALLOCATE                      192.1M       18 
VM_ALLOCATE (reserved)             3.9G        1         reserved VM address space (unallocated)
WebKit Malloc                    192.1M        4 
__AUTH                            3635K      550 
__AUTH_CONST                      37.9M      787 
__CTF                               824        1 
__DATA                            18.3M      819 
__DATA_CONST                      43.0M      833 
__DATA_DIRTY                      2775K      306 
__FONT_DATA                          4K        1 
__INFO_FILTER                         8        1 
__LINKEDIT                       531.4M       37 
__OBJC_RO                         71.7M        2 
__OBJC_RW                         2194K        1 
__TEXT                           858.1M      853 
dyld private memory                272K        2 
libnetwork                        1664K       24 
mapped file                      216.1M       49 
shared memory                     1488K       20 
===========                     =======  ======= 
TOTAL                              7.7G     4547 
TOTAL, minus reserved VM space     3.8G     4547

**Comment by bgoncal** [comment]
I'll make a beta release today so you can validate if the issue was fixed

**Comment by Poshy163** [comment]
Cheers!

**Comment by Poshy163** [comment]
Appears to have fixed it, thanks!
