### ISSUE TITLE
Problem with CarPlay

### ISSUE THREAD

**Issue by lambros414** [home-assistant/iOS#2564]
**iOS device model, version and app version**

Model Name:  Iphone 13
Software Version:  17.2.1
App version: 2024.1

**Home Assistant Core Version** - 2024.1.5

Hopefully this is still the right place to put this, because I can see that CarPlay support is brand new.... And I'm PSYCHED

I noticed an issue. One of the options, when on CarPlay, is to go to the various areas in the house, and bring up the components/entities/devices associated with that area. When listing in CarPlay, only the first 12 are listing. I have probably about 25-30 areas, and it is only showing the first 12 alphabetically.

The second issue is less of an issue, but possibly a feature request now that Home Assistant is part of CarPlay.
I have several actionable notifications built in home assistant that pop up on my iPhone. Many in the past have asked why these don't pop up with CarPlay, and the responses I saw was there wasn't an integration. Don't know if this is on the plans, but if possible would be great to look at.

I have actionable notifications based upon my geographic proximity that will pop up when driving close to home (opening garages etc). Right now I have to pull out my phone to act on this (while driving). would be great if a pop up happened on car-play - similar to phone messages, texts, or other alerts from other CarPlay supported apps.

In addition to the convince of garage options with proximities, there are other more important actionable notifications I am using that would really be better (and safer) if they could be incorporated as part of CarPlay. Is this on the radar?  I realize as CarPlay is new, it may be coming later, but just wanted to put it out there as a really needed feature in time.

Thanks SO MUCH for bringing this feature to Home Assistant!

**To Reproduce**.  select areas tab on top of menu and scroll

**Expected behavior**. It should scroll through all of my areas alphabetically, not just the 1st 12.

**Screenshots**
Please let me know if necessary, but a screen shot would just show my list of areas that end at the 12th area.

**Additional context**

**Comment by bgoncal** [comment]
About the areas, we merged a PR recently that adds pagination to the areas tab, so you will be able to see all your areas in the next release (or current TestFlight build).

About actionable notifications, that's currently not in the plans since this is not something officially supported by Apple and the implementation would actually need to be a workaround. But you are not the first that asks for that so, I'll keep in mind.

**Comment by bgoncal** [comment]
Feel free to reopen this issue if needed

**Comment by lambros414** [comment]
Thank you!

It's unfortunate that Apple doesn't officially support actionable notifications.  I'm glad I can add the the list of those liking it, and not the only one.

 Thanks again for this integration!  Fantastic work!

**Comment by claudesadik** [comment]
> About the areas, we merged a [PR](https://github.com/home-assistant/iOS/pull/2543) recently that adds pagination to the areas tab, so you will be able to see all your areas in the next release (or current TestFlight build).
> 
> About actionable notifications, that's currently not in the plans since this is not something officially supported by Apple and the implementation would actually need to be a workaround. But you are not the first that asks for that so, I'll keep in mind.

Ah ! I was looking for actionable notifications in CarPlay and ended up here. I would love to have this feature as well. 
What I wanted to do is have a CarPlay actionable notification like: Would you like to arm your home alarm system ? And then a YES / NO answer. I understand it’s not supported by Apple right now (which is a shame) but if there’s a workaround… Thanks so much for bringing Home Assistant to CarPlay tho !
