### ISSUE TITLE
Update to 2024.1: App won't start, ThreadNetwork Library missing  (Monterey)

### ISSUE THREAD

**Issue by gnumpi** [home-assistant/iOS#2570]
**Device model, version and app version**

Model Name: MacBook Pro (15-inch, 2016)
macOS Version: 12.7.3
App Version: 2024.1 (2024.535)
Safari Version: 17.3 (17617.2.4.11.11, 17617)

**Home Assistant Core Version**
2023.12.1  

**Describe the bug**
The app got automatically updated and won't start anymore.
The following is shown in the report:

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: '/System/Library/Frameworks/ThreadNetwork.framework/Versions/A/ThreadNetwork'
Referenced from: '/Applications/Home Assistant.app/Contents/MacOS/Home Assistant'
Reason: tried: '' (no such file), '/System/Library/Frameworks/ThreadNetwork.framework/Versions/A/ThreadNetwork' (no such file)

**Comment by aneisch** [comment]
Seeing the same

**Comment by SurreyMichael** [comment]
Me too

**Comment by bgoncal** [comment]
Fix on its way, apologies for the inconvenience

**Comment by iSteve-O** [comment]
In the mean time, if anyone is experiencing this issue and needs the app to work again, delete the 'Home Assistant.app' folder from the Applications folder and copy in the un-zipped previous version. 

Glad to have my Mac automations back & glad to hear this will be fixed. I was worried the 2015 MBP lost support (traumatized by apple).

https://github.com/home-assistant/iOS/releases/download/release%2F2023.12%2F2023.499/home-assistant-mac.zip

**Comment by benblb** [comment]
Also happening here, but a quick shoutout to the devs. In an attempt to fix, I deleted and re-downloaded the app from the Mac App Store (which obviously didn't work). Thanks to the comment @iSteve-O made a short 3 minutes before I searched for the issue here, I downloaded an older working version, and *all* of my settings restored themselves. Didn't even have to re-log in. Thanks, devs!

**Comment by bgoncal** [comment]
Can you validate the fix on the latest testflight build ? (2024.545)

**Comment by gnumpi** [comment]
Yes, I can validate that the testflight build is running on my system!
Thanks a lot for you work!

**Comment by fernando-freitas-alves** [comment]
The TestFlight 2024.2 version is working now! 🙌 
Thanks, @bgoncal! 🙇 

**Device model, version and app version**

- **Model Name**: MacBook Pro (Retina, 15-inch, Mid 2015)
- **macOS Version**: 12.7.1 (Monterey)
- **Safari Version**: 17.1 (17616.2.9.11.9, 17616)
- **App Version**: 2024.2 (2024.535) - _Installed via TestFlight (first removed all related files to the previous, 2024.1 AppStore, installed version by using CleanMyMac)_
- **Home Assistant Core Version**: 2024.2.0
