### ISSUE TITLE
iOS companion app crashes on iPhone/iPad after 5 min from launching

### ISSUE THREAD

**Issue by ronluna** [home-assistant/iOS#2571]
**iOS device model, version and app version**

Model Name: iPad 9th gen / iPhone 12 mini
Software Version: iPadOS 16.6/ iOS 17.2.1
App version: 2024.1

**Home Assistant Core Version**
2024.1.6

**Describe the bug**
The companion app crashes only on iOS devices  precisely after 5 minutes have pass from the initial launching of the app. The 5 minutes countdown continues to pass even while the app is running in the background. This does not happens on any browser nor android companion app. This started happening since version 2023.4 althought I was hoping to be resolved on upcoming versions.
**To Reproduce**
Launch the app and wait 5 minutes
**Expected behavior**
App should not crash
**Screenshots**
N/A

**Comment by codyc1515** [comment]
Would you be able to capture a screen recording of that happening? I certainly never observed this on iOS, iPadOS or macOS.

**Comment by ronluna** [comment]
I've been trying to track down the issue and I think I just have narrowed it to this:

The iOS companion app seems to run very stable while having only one server added and configured but the crashing starts after configuring multiple servers (In my case 3)... 

I will confirm this further with more testing... Now I'm wondering if anyone have run the iOS companion app with multiple servers configured without experiencing a crash ?

**Comment by bgoncal** [comment]
Feel free to reopen if needed
