### ISSUE TITLE
Tapping actions on the widget screen opens the app in the foreground

### ISSUE THREAD

**Issue by markusspa** [home-assistant/iOS#2584]
Model Name:
iPhone 14 Pro

Software Version:
iOS 17.3.1

App version:
Home Assistant Companion App 2024.1 (2024.535)

Home Assistant Core Version:
2024.2.1

Description of the bug:
When I tap an action on the widget screen, the action is executed and the Home Aisstant app opens in the foreground.

Expected behavior:
When I tap an action on the widget screen, the action should be executed without opening the app in the foreground.

**Comment by bgoncal** [comment]
That's expected, the feature was implemented when widgets were not able to perform actions in background. I'll close this issue and add "feature request label"
