### ISSUE TITLE
Device tracking does not work anymore (iOS Home Assistant Mobile App)

### ISSUE THREAD

**Issue by markusspa** [home-assistant/iOS#2599]
### The problem

The location of my device is not updating anymore. That is why I am always home although I left the home zone. I checked all preferences in iOS settings as well as the settings of the HA App (Location, Background activities, ...). VPN works well. My girlfriend has exactly the same problem.

Specs:
- iPhone 14 Pro & iPhone 12 Pro
- iOS 17.3.1
- Home Assistant Companion App 2024.1 (2024.535)

The activity protocol in the app shows a lot of errors. Perhaps it helps to solve the problem. The errors are always the same:
- Webhook failed with status code 503
- Didn't update [...] (Schared.BackgroundTaskError-Fehler 0.)

### What version of Home Assistant Core has the issue?

2024.2.1

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Mobile App

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/mobile_app/

**Comment by bgoncal** [comment]
Duplicate https://github.com/home-assistant/iOS/issues/2583
