### ISSUE TITLE
HA App will not launch in OS

### ISSUE THREAD

**Issue by EPStutes** [home-assistant/iOS#2603]
**iOS device model, version and app version**
Model Name:	iMac
  Model Identifier:	iMac17,1
  Processor Name:	Quad-Core Intel Core i5
  Processor Speed:	3.3 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	8 GB
  System Firmware Version:	526.0.0.0.0
  OS Loader Version:	540.120.3~37
  SMC Version (system):	2.34f3

Software Version: MacOS Monterrey 12.7.3 (updated 2-25-24)
App version: 2024.1

**Home Assistant Core Version**
2024.2.3

**Describe the bug**
App will not launch.  Just get the error message "Home Assistant.app quit unexpectedly."

**To Reproduce**
Launch App

**Expected behavior**
App Launches

**Screenshots**
Translated Report (Full Report Below)
-------------------------------------

Process:               Home Assistant [1177]
Path:                  /Applications/Home Assistant.app/Contents/MacOS/Home Assistant
Identifier:            io.robbie.HomeAssistant
Version:               2024.1 (2024.535)
App Item ID:           1099568401
App External ID:       862745403
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-02-25 07:11:48.8918 -0600
OS Version:            macOS 12.7.3 (21H1015)
Report Version:        12
Anonymous UUID:        83828C54-A62B-B579-A0A2-69C656373E95

Time Awake Since Boot: 1100 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: '/System/Library/Frameworks/ThreadNetwork.framework/Versions/A/ThreadNetwork'
Referenced from: '/Applications/Home Assistant.app/Contents/MacOS/Home Assistant'
Reason: tried: '' (no such file), '/System/Library/Frameworks/ThreadNetwork.framework/Versions/A/ThreadNetwork' (no such file)
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	       0x10ec3c9a2 __abort_with_payload + 10
1   dyld                          	       0x10ec52ab2 abort_with_payload_wrapper_internal + 80
2   dyld                          	       0x10ec52ae4 abort_with_payload + 9
3   dyld                          	       0x10ec00699 dyld4::halt(char const*) + 615
4   dyld                          	       0x10ebfc5b5 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3995
5   dyld                          	       0x10ebfb4e4 start + 388

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000002000209  rbx: 0x0000000000000000  rcx: 0x00007ff7baa464b8  rdx: 0x00007ff7baa46920
  rdi: 0x0000000000000006  rsi: 0x0000000000000001  rbp: 0x00007ff7baa46500  rsp: 0x00007ff7baa464b8
   r8: 0x00007ff7baa46520   r9: 0x0000000000000000  r10: 0x000000000000009f  r11: 0x0000000000000246
  r12: 0x000000000000009f  r13: 0x00007ff7baa46920  r14: 0x0000000000000001  r15: 0x0000000000000006
  rip: 0x000000010ec3c9a2  rfl: 0x0000000000000246  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x02000209 
Trap Number:     133

Binary Images:
       0x10ebf6000 -        0x10ec61fff dyld (*) <cbcd7d35-e8e9-3e64-b80b-b254b042afbf> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=28.1M resident=0K(0%) swapped_out_or_unallocated=28.1M(100%)
Writable regions: Total=9540K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9540K(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
VM_ALLOCATE                         12K        3 
__DATA                            1808K       41 
__DATA_CONST                      1104K       35 
__LINKEDIT                        8512K       36 
__TEXT                            19.8M       35 
dyld private memory               1024K        1 
===========                     =======  ======= 
TOTAL                             96.0M      153 

-----------
Full Report
-----------

{"app_name":"Home Assistant","timestamp":"2024-02-25 07:11:48.00 -0600","app_version":"2024.1","slice_uuid":"bef90aa9-01a8-3912-ba8b-9fc019a469a6","adam_id":"1099568401","build_version":"2024.535","platform":6,"bundleID":"io.robbie.HomeAssistant","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.7.3 (21H1015)","incident_id":"012FE729-D4CC-4469-A958-E3EFB6F11BBC","name":"Home Assistant"}
{
  "uptime" : 1100,
  "procLaunch" : "2024-02-25 07:11:45.6610 -0600",
  "procRole" : "Background",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "iMac17,1",
  "procStartAbsTime" : 1165930683887,
  "coalitionID" : 962,
  "osVersion" : {
    "train" : "macOS 12.7.3",
    "build" : "21H1015",
    "releaseType" : "User"
  },
  "captureTime" : "2024-02-25 07:11:48.8918 -0600",
  "incident" : "012FE729-D4CC-4469-A958-E3EFB6F11BBC",
  "bug_type" : "309",
  "pid" : 1177,
  "procExitAbsTime" : 1169161248333,
  "cpuType" : "X86-64",
  "procName" : "Home Assistant",
  "procPath" : "\/Applications\/Home Assistant.app\/Contents\/MacOS\/Home Assistant",
  "bundleInfo" : {"CFBundleShortVersionString":"2024.1","CFBundleVersion":"2024.535","CFBundleIdentifier":"io.robbie.HomeAssistant"},
  "storeInfo" : {"storeCohortMetadata":"10|date=1708864200000&sf=143441&pgtp=Search&pgid=osx&prpg=Software_1099568401&ctxt=Search&issrch=1&imptyp=card&kind=macSoftware&lngid=1","itemID":"1099568401","deviceIdentifierForVendor":"5C2BB174-DBE9-5992-A0B8-6AB9C322FB9D","thirdParty":true,"softwareVersionExternalIdentifier":"862745403"},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "io.robbie.HomeAssistant",
  "crashReporterKey" : "83828C54-A62B-B579-A0A2-69C656373E95",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: '\/System\/Library\/Frameworks\/ThreadNetwork.framework\/Versions\/A\/ThreadNetwork'","Referenced from: '\/Applications\/Home Assistant.app\/Contents\/MacOS\/Home Assistant'","Reason: tried: '' (no such file), '\/System\/Library\/Frameworks\/ThreadNetwork.framework\/Versions\/A\/ThreadNetwork' (no such file)"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":19474,"threadState":{"r13":{"value":140701964986656},"rax":{"value":33554953},"rflags":{"value":582},"cpu":{"value":0},"r14":{"value":1},"rsi":{"value":1},"r8":{"value":140701964985632},"cr2":{"value":0},"rdx":{"value":140701964986656},"r10":{"value":159},"r9":{"value":0},"r15":{"value":6},"rbx":{"value":0},"trap":{"value":133},"err":{"value":33554953},"r11":{"value":582},"rip":{"value":4542679458,"matchesCrashFrame":1},"rbp":{"value":140701964985600},"rsp":{"value":140701964985528},"r12":{"value":159},"rcx":{"value":140701964985528},"flavor":"x86_THREAD_STATE","rdi":{"value":6}},"frames":[{"imageOffset":289186,"symbol":"__abort_with_payload","symbolLocation":10,"imageIndex":0},{"imageOffset":379570,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":80,"imageIndex":0},{"imageOffset":379620,"symbol":"abort_with_payload","symbolLocation":9,"imageIndex":0},{"imageOffset":42649,"symbol":"dyld4::halt(char const*)","symbolLocation":615,"imageIndex":0},{"imageOffset":26037,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3995,"imageIndex":0},{"imageOffset":21732,"symbol":"start","symbolLocation":388,"imageIndex":0}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4542390272,
    "size" : 442368,
    "uuid" : "cbcd7d35-e8e9-3e64-b80b-b254b042afbf",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 140703511023616,
  "size" : 19331678208,
  "uuid" : "86bc6103-e387-3a89-a90f-c8314d49a242"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=28.1M resident=0K(0%) swapped_out_or_unallocated=28.1M(100%)\nWritable regions: Total=9540K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9540K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8192K        1 \nVM_ALLOCATE                         12K        3 \n__DATA                            1808K       41 \n__DATA_CONST                      1104K       35 \n__LINKEDIT                        8512K       36 \n__TEXT                            19.8M       35 \ndyld private memory               1024K        1 \n===========                     =======  ======= \nTOTAL                             96.0M      153 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "60356660bbe37970735c5624",
      "factorPackIds" : {

      },
      "deploymentId" : 240000027
    },
    {
      "rolloutId" : "6112e14f37f5d11121dcd519",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "634710168e8be655c1316aaa"
      },
      "deploymentId" : 240000231
    }
  ],
  "experiments" : [

  ]
}
}

Model: iMac17,1, BootROM 526.0.0.0.0, 4 processors, Quad-Core Intel Core i5, 3.3 GHz, 8 GB, SMC 2.34f3
Graphics: AMD Radeon R9 M395, AMD Radeon R9 M395, PCIe, 2 GB
Display: iMac, Retina 5K (5120 x 2880), Main, MirrorOff, Online
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1867 MHz, 0x802C, 0x384B54463531323634485A2D314739503220
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1867 MHz, 0x802C, 0x384B54463531323634485A2D314739503220
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x14A), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1710.4)
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Serial ATA Device: APPLE SSD SM0128G, 121.33 GB
Serial ATA Device: APPLE HDD ST2000DM001, 2 TB
USB Device: USB30Bus
USB Device: Bluetooth USB Host Controller
USB Device: FaceTime HD Camera (Built-in)
USB Device: hub_device
USB Device: USB Receiver
Thunderbolt Bus: iMac, Apple Inc., 28.1

**Additional context**

**Comment by bgoncal** [comment]
Please use the latest TestFlight build or pre-release available on GitHub, the issue has been fixed.

**Comment by EPStutes** [comment]
Thanks.  I will look for the pre-release

**Comment by EPStutes** [comment]
Cannot figure out how to download and install the pre-release.  (noobie issue I am sure)

When will the app be updated on the App Store?

**Comment by bgoncal** [comment]
This week

**Comment by EPStutes** [comment]
Great and thanks again
