### ISSUE TITLE
Dashboard refresh on IOS: Uncaught error from WebKit 605.1.15 on iOS 16.7.5 Script error.

### ISSUE THREAD

**Issue by mostdone** [home-assistant/iOS#2604]
**iOS device model, version and app version**

Model Name: IPhone8
Software Version: IOS 16.7.5
App version: 2024.1

**Home Assistant Core Version**

HA Core : "2024.2.3"
supervisor: "2024.02.0"
Home Assistant: "OS 11.5"
Frontend: "20240207.1"

**Describe the bug**

Each time I open or refresh a dashboard on IOS using the APP.
The following error appears in the Core logs:

**2024-02-25 06:42:36.747 ERROR (MainThread) [frontend.js.latest.202402071] Uncaught error from WebKit 605.1.15 on iOS 16.7.5
Script error.
null
@:0:0**

It does NOT happen on OSX with either Safari or Chrome.
My installation also has other dashboards. The error does NOT occur when the other dashoards are viewed or refreshed.

**To Reproduce**
Create Dashboard that contains 4 GRID cards each containing 4 thermostat cards. There is also one other SINGLE thermostat card.
17 thermostat entities in ALL.

**This is the Dashboard code.**

title: Home
views:
  - path: default_view
    title: Home
    cards:
      - square: true
        type: grid
        cards:
          - type: thermostat
            entity: climate.sinope_technologies_th1124zb_g2_thermostat
            name: SolariumEst
          - type: thermostat
            entity: climate.th_solariumouest
            name: SolariumOuest
        columns: 2
      - square: true
        type: grid
        cards:
          - type: thermostat
            name: Cave Nord
            entity: climate.th_cavenord
          - type: thermostat
            entity: climate.th_cavesud
            name: Cave Sud
        columns: 2
      - square: false
        type: grid
        cards:
          - type: thermostat
            entity: climate.th_chambrenord_thermostat_2
            name: Miriam
            show_current_as_primary: false
          - type: thermostat
            name: Elise
            entity: climate.th_chambreest_thermostat_2
          - type: thermostat
            entity: climate.sinope_technologies_th1124zb_thermostat
            name: Francois
          - type: thermostat
            name: Toilette
            entity: climate.th_toilettehaut_thermostat
        columns: 2
      - square: true
        type: grid
        cards:
          - type: thermostat
            name: Cuisine
            entity: climate.th_cuisine
          - type: thermostat
            entity: climate.th_entree
            name: Entrée
          - type: thermostat
            entity: climate.th_foyer
            name: Foyer
          - type: thermostat
            entity: climate.th_salledebain
            name: SalleBain
        columns: 2
      - square: true
        type: grid
        cards:
          - type: thermostat
            entity: climate.th_passage
            name: Passage
        columns: 2

**Expected behavior**
The view should show/refresh without an uncaught error from WebKit.

**Screenshots**

**Additional context**

The error does not happen when the dashboard is viewed or refreshed in Safari or Chrome on OSX.
This bug was previously opened and closed on an earlier version [#2439](https://github.com/home-assistant/iOS/issues/2439)

**Comment by mostdone** [comment]
**Further testing**
1- Completely deleted the problematic dashboard

2- Recreated dashboard from scratch with only **ONE GRID containing 2 THERMOSTAT** card. 
-The problem **OCCURS** when this dashboard is viewed in IOS.
I have grids in another dashboard (NOT containing "thermostat" entities) that do not cause the issue.

3- I deleted the grid and added just a thermostat card in the dashboard.
-The the problem **DOES NOT OCCUR**

Issue #2439 occured with 20 x **"Logbook cards"** it's not clear whether they were in GRID or not.
and here with 2 x **"Thermostat cards"** in a GRID.

The following code is the "Raw configuration view" but it was created using the UI.
The issue occurs with this dashboard config.

**Code**
views:
  - title: Home
    cards:
      - square: false
        type: grid
        cards:
          - type: thermostat
            entity: climate.th_solariumouest
            name: SolOuest
          - type: thermostat
            entity: climate.th_solest
            name: SolEst
        columns: 2

**Comment by bgoncal** [comment]
What happens if you open on iOS Safari? (Not macOS)

**Comment by mostdone** [comment]
When I open the dashboard on IOS (Not MAC OS) Safari. The issue OCCURS.

**Comment by bgoncal** [comment]
Since the issue happens inside the iOS app and ALSO in iOS Safari, please report the issue to frontend repo, it must be some WebKit edge case they have to treat on their side.

**Comment by mostdone** [comment]
Can you give me the URL of this frontend repo? 
Do I have to re-enter everything?

**Comment by bgoncal** [comment]
Here it is: https://github.com/home-assistant/frontend

Please fill the information requested when opening a new issue, you can also mention this issue there.

**Comment by bgoncal** [comment]
I closed the issue here since it's not something on the App side, feel free to reopen in case you disagree or new information comes up
