### ISSUE TITLE
No widgets available for watchOS

### ISSUE THREAD

**Issue by pzich** [home-assistant/iOS#2612]
**iOS device model, version and app version**

Model Name: iPhone 14 Pro
Software Version: 17.3.1
App version: 20240104.0

**Home Assistant Core Version**
2024.1.5

**Describe the bug**
With the release of watchOS 10, Apple has added widgets, which are able to be accessed quickly by swiping the crown. My hope is to be able to add a widget similar to the ones available on iOS, where I can either have quick actions I can trigger there directly, or at least a quick way to launch the watchOS app and do it from there.

Unfortunately, it seems that there's no way to add application launching to the widget screen unless the app has explicitly built a widget (thanks Apple 🙄), so I'm hoping that at least a "launch" option can be added so it can be selected as one of the three buttons pictured below, but it would also be amazing if a full fledged widget can be added with customizable action buttons.

**To Reproduce**
Open the widgets, long press to add a widget (or edit the three button one). Scroll through the list of available apps and see that Home Assistant is not an option.

**Expected behavior**
Home Assistant should be able to be added at least as a launch option, and ideally a set of actions as well.

**Screenshots**
Widgets screen shown
![incoming-42A4D1D9-4835-4CE2-B5C3-C97C7656A241](https://github.com/home-assistant/iOS/assets/706138/a4d9ce62-67f8-4545-ba80-b3443a4d1fe0)

Editing widgets
![incoming-B4A542FA-BAB3-4C68-8025-3FCF8DD5C8D3](https://github.com/home-assistant/iOS/assets/706138/32d0c5b4-5b6f-4724-8ad6-be543b6c0a78)

Messages launch option
![incoming-73B2F700-5D54-4681-88ED-C2AEF0582D8A](https://github.com/home-assistant/iOS/assets/706138/f569a95a-d36b-4f9c-8c81-2bb5957d0ef9)

Home Assistant not listed as an option (despite it being an installed app)
![incoming-6CA2E2E8-7814-4799-B02A-2BE3ADAD0D28](https://github.com/home-assistant/iOS/assets/706138/5d028450-819a-47e2-b6a5-100c63df3251)

**Comment by bgoncal** [comment]
This is more like a feature request, please use https://community.home-assistant.io/ for that
