### ISSUE TITLE
Triggered action overlay blocks app interaction

### ISSUE THREAD

**Issue by pzich** [home-assistant/iOS#2613]
**iOS device model, version and app version**
Model Name: iPhone 14 Pro
Software Version: 17.3.1
App version: 20240104.0

**Home Assistant Core Version**
2024.1.5

**Describe the bug**
Right now, when you trigger an action from the companion app, Home Assistant is launched, and a full screen overlay is shown for 3 seconds indicating what was triggered. Unfortunately this overlay also seems to block any other interaction with the app until it disappears. I know this is a short time to wait, but it's frustrating when I want to trigger an action and then adjust something else.

It would be great if, at the very least, tapping this overlay would make it disappear.

Additionally though, it would be amazing if:
- you could customize how long this overlay is shown, if at all
- you could choose to have this show as an non-intrusive banner at the top
- you could customize what screen is shown after the action (e.g. bring me to this tab of this dashboard, or show the color/brightness picker for this light)

**To Reproduce**
- Create a companion app action
- Add it as a widget
- Trigger the action

**Expected behavior**
At the very least, I'm able to immediately dismiss the overlay by tapping it, but ideally customize how or whether it's shown at all, etc.

**Screenshots**

https://github.com/home-assistant/iOS/assets/706138/63a16ec4-11d8-4033-a70c-ad2a7f16fcf8

**Comment by bgoncal** [comment]
Please don't report feature requests as bugs, use https://community.home-assistant.io/ to request new features.
