### ISSUE TITLE
Camera attachments don't work when going through Cloud

### ISSUE THREAD

**Issue by olbjan** [home-assistant/iOS#263]
When HA is set up with Cloud through Nabu Casa, the iOS app always tries that connection. This impacts notification attachments as e.g. Camera attachments don't work.

At this point I'm about to say:

Can we make the whole "use cloud" thing an option in the app that can be enabled or disabled? I want to support the project and thus have the subscription but I don't want to use remote control.

**Comment by roflcoopter** [comment]
Can confirm this too, camera attachment work fine when on LAN, but not through the Cloud UI

**Comment by TomBrien** [comment]
@olbjan is this still true?

**Comment by olbjan** [comment]
This is either no longer true and/or has been resolved. Closing the ticket.
