### ISSUE TITLE
App locks up for 15-20 seconds on launch

### ISSUE THREAD

**Issue by yayadrian** [home-assistant/iOS#2637]
**iOS device model, version and app version**
Model Name: iPhone 15 Pro  - MTV13ZD/A
Software Version: 17.3.1
App version: 2024.3 (2024.587)

**Home Assistant Core Version**
Core - 2024.3.0
Supervisor - 2024.02.1

**Describe the bug**
When you first launch the app there is 1 second where it works, then it locks up (unable to swipe up/down, click buttons has no action)
After 15-20 seconds the app will work a normal. 
Reverting back to 2024.580 does not show this issue. 

**To Reproduce**
Install 2024.587, open app and try scrolling. 
App locks for 15-20 seconds. 

**Expected behavior**
App should be responsive like previous version and not lock up
OR should loading message if still loading data.

**Comment by bgoncal** [comment]
Could you double check if 2024.3 (2024.590) fixes the issue?

**Comment by yayadrian** [comment]
Still occurring in 2024.3 (2024.590)
On first load you get the standard "loading data" screen. 
Leave the app and use other amounts for ~5 minutes. 
Return to HA companion app, it works for 1 second and then locks up for 15-20 seconds. 

Test with internal IP http (no ssl) and external nabu.casa cloud. Both appear to have the same issue.

**Comment by bgoncal** [comment]
If you downgrade to 580 the issue doesnt happen? Consistently? Can you try downgrading and test then upgrade and test?
(I know you already did that once, but just to be sure)

**Comment by yayadrian** [comment]
Tried several times to see if I can pin point it. 
I can consistently recreate the problem on.587, .590 
on .580 or earlier it's totally fine.

**Comment by Mariusthvdb** [comment]
seeing related: in each opening/returning to the app.... so dont have to wait 5 minutes. just, use it, use sme  else then return.

figured it to be me installing HA dev, but might also be iOS app beta...
numbers:

HA 2024.4.0.dev20240308
SU 2024.03.1.dev0802

have to wait a bit....


iOS app 2024.3 (2024.590)

**Comment by IT-Fuzzi** [comment]
I’m not able to reproduce the issue you face / reported. Just working fine for me with the internal as well as with the external server address.

iPhone 12 Pro
2024.3 (2024.590)

Core 2024.3.0
Supervisor 2024.02.1
Operating System 12.0
Frontend 20240306.0

**Comment by lux4rd0** [comment]
I've been having the same issue for a few weeks. Something is eating up a bunch of CPU when it's running, as my phone gets hot when I leave it on the HA app. I'm trying to get to the Debugging | export log files, but the app is locked up when I get there.

iPhone 15 Pro (iOS 17.4)
2024.2
Core 2024.3.0
Frontend 20240306.0

_I'm following along until I can get some logs to contribute... (no issues on my laptop - but it's definitely locked up using Safari or Chrome on mobile as well)_

**Comment by lux4rd0** [comment]
To follow up, I have the same issues with simply using a Web browser on iOS. So, I decided to try the different flavors of Web browsers, knowing most still use WebKit under the covers. Safari, Chrome, and Firefox all hang. Opera does not hang. That's all on my primary HA site with hundreds of devices.

Everything works fine on a new site with just a handful of devices. I don't get any hangups. So, it's understandable that this impacts different people with different configurations.

**Comment by bgoncal** [comment]
Since the issue also happens in Safari, then I don't think it is app specific, you may have better luck reporting to frontend repo.

**Comment by lux4rd0** [comment]
> Since the issue also happens in Safari, then I don't think it is app specific, you may have better luck reporting to frontend repo.

It's specific in that iOS has the issue and normal desktop computers do not. But I see your point...

**Comment by yayadrian** [comment]
It does appear to be an issue with instances that have a large number of
entities.
With my smaller instance, I'm unable to recreate the issue (same version
numbers)
But I don't have an issue using Safari on my large instance.
Larger Instance: 8438 entities
Small instance: 104 entities.

**Comment by lux4rd0** [comment]
**Not working:**

automation: 100
binary_sensor: 302
button: 133
calendar: 3
camera: 11
climate: 2
device_tracker: 6
event: 76
fan: 9
image: 6
input_boolean: 21
input_select: 15
input_text: 2
light: 112
media_player: 27
number: 373
person: 1
proximity: 1
remote: 1
scene: 10
script: 9
select: 183
sensor: 2127
stt: 1
sun: 1
switch: 306
text: 2
time: 4
tts: 2
update: 44
vacuum: 2
weather: 10
zone: 1

**Working fine:**

automation: 1
binary_sensor: 62
button: 26
camera: 7
device_tracker: 31
event: 9
light: 3
media_player: 9
number: 38
person: 1
select: 32
sensor: 159
stt: 1
sun: 1
switch: 107
text: 1
todo: 1
tts: 2
update: 11
weather: 1
zone: 1

**Comment by yayadrian** [comment]
Still able to reproduce with
App version: 2024.3 (2024.595) 
Home Assistant Core Version
Core - 2024.3.1

**Comment by bgoncal** [comment]
I'll be investigating this issue next week, I have an idea where this may be coming from, I'll get access to an instance with lots of entities to perform more tests.

**Comment by Mariusthvdb** [comment]
Yep, that seems to fix it !

very nice, thank you!

**Comment by yayadrian** [comment]
👍🏻 looks good. I’m not longer able to recreate the bug. 
great work. Thanks for your help.

**Comment by bgoncal** [comment]
Im glad to hear that! Thanks for reporting

**Comment by lux4rd0** [comment]
I grabbed the Beta off of TestFlight, and I'm still having the issue... :(

**Comment by bgoncal** [comment]
> I grabbed the Beta off of TestFlight, and I'm still having the issue... :(

Perhaps you are experiencing a different bug... does this behavior also happens on 2024.3 (2024.580) testflight version? Because that was the version prior to the issue we are discussing in this thread

**Comment by lux4rd0** [comment]
Yes - I just now installed 2024.580 from testflight and the slowness is also happening on that version.

**Comment by bgoncal** [comment]
> Yes - I just now installed 2024.580 from testflight and the slowness is also happening on that version.

In that case your issue is different from this one, please open a new bug report and provide the more information you can, if possible also logs.
