### ISSUE TITLE
Mobile App integrations list

### ISSUE THREAD

**Issue by towerhand** [home-assistant/iOS#265]
Since the introduction of the mobile app in the beta, every device creates a integration entry. Resulting in:
- Mobile App: phone 1
- Mobile App: phone 2
- Mobile App: phone 3

Per discussion in discord, I’m requesting to have an entry per mobile app and list devices inside that entry like it used to be with the Home Assistant for iOS integration. Resulting in:
- Mobile App: iOS
   + phone 1
   + phone 2
   + phone 3
- Mobile App: Android
   + phone 1

**Comment by SeanPM5** [comment]
The Integrations page has been significantly overhauled since this FR was opened last year, I think this is no longer relevant right?

0.110 now groups integrations by default.

**Comment by towerhand** [comment]
You are right, closed.
