### ISSUE TITLE
Remove deprecated iOS 12 things

### ISSUE THREAD

**Issue by michalsrutek** [home-assistant/iOS#2655]
There are still things in the project annotated with `@available(iOS, deprecated: 13.0)`. Namely
- `UIWindow`'s `convenience init(haForiOS12: ())`
- `StateRestorationKey`
-  `viewController(withRestorationIdentifierPath identifierComponents: [String])`
- `SceneManagerPreSceneCompatibility`

which could be removed, as the min iOS version is now 15.

**Comment by bgoncal** [comment]
Hey @michalsrutek, I see you started contributing to the project, could you help out with this one? No pressure though

**Comment by bgoncal** [comment]
Thanks @mat1th 🥳
