### ISSUE TITLE
Zone updates in Event Log have "Unknown" categorization

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/iOS#267]
So there was fixes to zone webhooks and stuff in 0.91.2. But I notice there is still one very minor issue in the Event Log. Any zone background task says "Unknown" on the right, when it used to say "Location Update" or "Zone Update" i believe.

![image](https://i.imgur.com/FxVOPrR.jpg)

**Comment by zacwest** [comment]
Fixed by #698.
