### ISSUE TITLE
Update Popup Too Long Hiding the Okay button

### ISSUE THREAD

**Issue by modernben** [home-assistant/iOS#2670]
**Device model, version and app version**
Model Name: Macbook Pro
macOS Version: 14.3.1
App Version:  2023.4 (2023.460)
Safari Version: 17.3.1
Monitor Resolution: 2560x1440

**Describe the bug**
The Update Available window is too tall and not scrollable so I can't hit the Okay button to close it.

**To Reproduce**
Running 2023.4, set monitor resolution to 2560x1440 and open the app. The Update available window pops up and the buttons aren't visible. You can also trigger with the Check for Updates... link from the menu.

**Expected behavior**
Set a max height to the window and make it scrollable

**Screenshots**
<img width="1036" alt="Screenshot 2024-03-25 at 10 02 30 AM" src="https://github.com/home-assistant/iOS/assets/67608755/1fcef5a8-0c65-459d-ae5b-7d584c4fc850">

**Additional context**
This isn't the first release this has occurred. I have to set the resolution to 3008x1692 in order to see the buttons.

**Comment by bgoncal** [comment]
Oh, good catch, I guess it was not meant to display big github release description. I have updated the description of this release, kill the app and open again, let me know if it is better now.

**Comment by modernben** [comment]
![Screenshot 2024-03-25 at 10 27 57 AM](https://github.com/home-assistant/iOS/assets/67608755/42829875-a423-45ea-aff7-c3368562aec9)

Looks much better! Thanks for the super quick turnaround.
