### ISSUE TITLE
“Swipe up bar” not transparent

### ISSUE THREAD

**Issue by dhoeben** [home-assistant/iOS#2673]
**iOS device model, version and app version**

Model Name:  iPhone 15 Pro
Software Version: iOS 17.3.1
App version: 2024.608

**Home Assistant Core Version**

Home Assistant 2024.3.3
**Describe the bug**
The iOS swipe up bar, which used to be the home button shows full white in stead of light transparant.

**Comment by bgoncal** [comment]
Can you share a screenshot and point out what you mean? The swipe up bar was always white wasn't it?

**Comment by bgoncal** [comment]
Feel free to reopen this issue if needed, I'm closing it for now because this doesn't look like a bug, just the way iOS presents the home indicator
