### ISSUE TITLE
Check if BTLE device is connected

### ISSUE THREAD

**Issue by TesLocker** [home-assistant/iOS#2676]
Mode Name: iPhone 12 Pro
Software Version: 17.4.1
App Version: 2024.2 (2024.561)

**Home Assistant Core Version**
2024.3.3

**Describe the bug**
No ability to see whether a BTLE device is connected or not. Other iOS apps seem to have this, so it isn’t likely to be an iOS limitation. For example, the iOS “Actions” app enables checking if a BTLE device is connected and integrates with the Shortcuts app.

**Screenshots**
![IMG_4148](https://github.com/home-assistant/iOS/assets/111825925/04112abe-61ca-4b6a-94a2-b8d8113d117c)
![IMG_4149](https://github.com/home-assistant/iOS/assets/111825925/1035c84f-1250-465e-abe9-0051a7e8ffd1)

**Comment by bgoncal** [comment]
Thanks for sharing, we don't track feature requests in github issues though, please use https://community.home-assistant.io to request that
