### ISSUE TITLE
Can not toggle Toggle in Location settings per Zone

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/iOS#2702]
**iOS device model, version and app version**

Model Name:  iPhone 13 Pro
Software Version: iOS 17.3.1
App version: 2024.4 (2024.624)

**Home Assistant Core Version**

2024.4.1

**Describe the bug**

as title: the toggles on each of the (UI) configured Zones can not be touched, they are 'greyed'

**To Reproduce**
Nothing special, just go to location settings and scroll down a bit

**Expected behavior**

being able to toggle the toggles

**Screenshots**

![image](https://github.com/home-assistant/iOS/assets/33354141/7512fc84-d342-483b-8067-85600a893033)

![image](https://github.com/home-assistant/iOS/assets/33354141/97d184aa-0a25-4cfe-b20f-02422c631d78)

**Additional context**

as explained in the community asking for help here: https://community.home-assistant.io/t/why-cant-the-location-settings-zone-toggle-be-toggled/714356

I was trying to do away with my customizations, hoping the toggles in the app would do the same (as their setting showed what I wanted, and the toggle are 'off' on the zones I had set `track_ios: false` to in customize:.

However, even after deleting the customizations, I still can not reach the toggles as they are 'greyed out'

this must be an issue, so reason for me to open this.

**Comment by bgoncal** [comment]
That's the intended implementation, for now you need to use `track_ios` to define that, you can't toggle through the App

**Comment by bgoncal** [comment]
Thanks for the feedback, I do agree with you.
