### ISSUE TITLE
cannot adjust numeric value due to decimal separator config

### ISSUE THREAD

**Issue by santiagozky** [home-assistant/iOS#2717]
**iOS device model, version and app version**

Model Name:  iphone 15
Software Version: 17.4.1
App version:  2024.624

**Home Assistant Core Version**
2024.4.0

**Describe the bug**
when adjusting a numeric value, the ios app will show a number-only keyboard. but since my ios locale settings have comma as a decimal separator. it is impossible to enter decimal numbers since the field validation will fail.

**To Reproduce**
have an ios device that uses comma as decimal separator. 
try to adjust the value of a number ox field (in my case, adjusting a statistics value).
the validation will fail since it expects a dot rather than a comma and it is not possible to enter a dot.

**Expected behavior**
the app should figure out that the comma is a decimal separator (or use a normal keyboard so I can input a dot)
**Screenshots**

![IMG_1438](https://github.com/home-assistant/iOS/assets/1405393/7f17a8f3-31c1-4445-a214-abcaf7c58722)

**Comment by bgoncal** [comment]
Have you checked if the same happens in iOS Safari? If so, please report the issue ti frontend repo

**Comment by santiagozky** [comment]
thanks. I tought it was an app specific thing, but no. this happens in the browser as well.

**Comment by eikowagenknecht** [comment]
I‘m having the same problem. My iPhone is set to use the , sign as a separator. But the Home Assistant app (and web site) need a . for the input. It is literally impossible to change values because of the mismatch.

I think the input field needs to accept numbers in the locale of the device.
