### ISSUE TITLE
App's user agent doesn't comply with Google's Use Secure Browsers policy

### ISSUE THREAD

**Issue by iloveicedgreentea** [home-assistant/iOS#2718]
**iOS device model, version and app version**
ios 17
iphone 15 pro
App 2024.624

**Home Assistant Core Version**
2024.4.3

**Describe the bug**
When using Cloudflare Zero Trust via the Google IDP, the app tries to open a webview with an unapproved user agent. This breaks the login flow and google does not allow you to authenticate

The fix is to not use a webview and to make this use the phone's browser

I hope this can be implemented because this is a really important security feature. This method allows you to have a public endpoint for HA without exposing any ports and proxying via a strong identity check.

**To Reproduce**
Set up a cloudflare tunnel
Set up Google workspace authentication
Set up an application which supports google auth via zero trust
Log in with the external url

**Expected behavior**
HA companion presents a valid user agent, like chrome
I am able to log in

**Screenshots**
![IMG_98431BBC2C40-1](https://github.com/home-assistant/iOS/assets/31193909/d7803a3c-45f9-487f-8591-6dc0a3c27449)

**Additional context**
https://support.google.com/accounts/answer/12917337?hl=en#403disallowed

**Comment by bgoncal** [comment]
Duplicate https://github.com/home-assistant/iOS/issues/2531
