### ISSUE TITLE
Webview refreshes every time app is switched to

### ISSUE THREAD

**Issue by iloveicedgreentea** [home-assistant/iOS#2719]
**iOS device model, version and app version**
ios 17
iphone 15 pro
App 2024.624

**Home Assistant Core Version**
2024.4.3

**Describe the bug**
I am using OTP auth via cloudflare which emails me a pin. I have to put in my email which brings me to the second part of the screen. When I check my email, and then go back to the HA app, it refreshes the webview which breaks the flow. This is very unusual behavior from a webview.

This actually breaks EVERY kind of two factor flow - tokens, MFA, whatever. I can't even switch to my MFA app. 

I suspect the error would be happening somewhere around here https://github.com/home-assistant/iOS/blob/1a733042321e324ce88439548dd4d0dba837b31a/Sources/App/WebView/WebViewController.swift#L600

**To Reproduce**
Open a webview in HA app
Switch to an app
Switch back to the app

_I think its specifically when the keyboard goes down though_

I noticed the webview will refresh when the keyboard is retracted even when I stay in the same app. Maybe there is some code which checks if the keyboard tray was exited?

For example:
Open a webview
enter in some info to validate it refreshed and have the keyboard open
Get a notification (or even swipe down to the notification tray and long press an existing notification)
Long press it and then exit the notification (remains in the same app)
Keyboard disappears and the webview refreshes 

**Expected behavior**
Webview remains where it was and does not refresh

**Screenshots**

**Additional context**

**Comment by zacwest** [comment]
The app is not designed to support a use case where it is being redirected to a non-HA URL. This is likely one of many bugs in that area, see #1719

**Comment by bgoncal** [comment]
Since this is not supported by the App I will be closing this issue, please open a feature request over https://community.home-assistant.io

**Comment by iloveicedgreentea** [comment]
>Since this is not supported by the App I will be closing this issue,

why? The point of this issue is to add the support

**Comment by bgoncal** [comment]
Because we don’t track requests here we track issues from features we currently support.
