### ISSUE TITLE
Timeout in app and in browser interface

### ISSUE THREAD

**Issue by imbaczek** [home-assistant/iOS#2743]
**iOS device model, version and app version**

Model Name: iPhone 15
Software Version: 17.4.1
App version: 2024.624

**Home Assistant Core Version**

2024.04.4

**Describe the bug**
App stopped loading. Goes to 'retrying' after 10s. Guess I've got too much stuff. Tried clearing cache, etc.

**To Reproduce**
Clear cache. Load app.

Same behavior when trying to load the UI with a web browser.

Computer browser works just fine, if a bit slow to load everything - some icons pop in after a while.

**Expected behavior**

Loads even if I have to wait for 30 s.

**Screenshots**

**Additional context**

Added a bunch of stuff to HA recently (installed ~5 new shellies, added 15-ish new zigbee devices) and rebooted my phone today.

**Comment by bgoncal** [comment]
Have you tried on iOS Safari? how does it behave?

**Comment by imbaczek** [comment]
Tried now again... It's fixed itself 🤯

Could be helpful to get some more diagnostics on which call exactly timed out; e.g. I'm not sure which hostname it tried to use (internal or external) and maybe add a configurable timeout to the app...? Otherwise I'll come back here if it breaks again
