### ISSUE TITLE
Fixed background does not work

### ISSUE THREAD

**Issue by Nezz** [home-assistant/iOS#2746]
**iOS device model, version and app version**

Model Name:  iPhone 15 Pro
Software Version: iOS 17.4.1
App version: 2024.624

**Home Assistant Core Version**
2024.4.4, 2024.5.0-b1

**Describe the bug**
When I set the background of a dashboard (lovelace & energy) to a fixed background, it still scrolls like a non-fixed background

**To Reproduce**
Use a theme like this:
```
background-image: "center / cover no-repeat fixed url('/hacsfiles/themes/something.jpg')"
```
The background image will be stretched across the whole dashboard vertically. It will scroll with the contents.

**Expected behavior**
The background image should not move when scrolling.

**Screenshots**

**Additional context**
Reported in https://github.com/basnijholt/lovelace-ios-themes/issues/59 but only seems to affect the iOS app. It works correctly on the web and in the Android app.

**Comment by bgoncal** [comment]
How does it behave in iOS Safari?

**Comment by Nezz** [comment]
It doesn't work correct in Safari either. That's quite the surprise.

**Comment by Nezz** [comment]
This seems to cover it pretty well: https://caniuse.com/background-attachment
