### ISSUE TITLE
Status bar color follows wrong color variable

### ISSUE THREAD

**Issue by Nezz** [home-assistant/iOS#2752]
**iOS device model, version and app version**

Model Name:  iPhone 15 Pro
Software Version: iOS 17.4.1
App version: 2024.624

**Home Assistant Core Version**
2024.4.4, 2024.5.0-b4

**Describe the bug**
The color of the status bar follows the `--app-header-background-color` variable. This is inconsistent with the browser where it follows `--app-theme-color`. It'd be nice to use that variable if it's set.

**To Reproduce**
Create a theme which sets `app-theme-color`:
```
app-theme-color: "#88827B" # Average header color, used on the top of the browser
```

**Expected behavior**
`--app-theme-color` should be used if it's set. The header color could still be used as a fallback.

**Screenshots**

**Additional context**
The frontend sets the theme color here:
https://github.com/home-assistant/frontend/blob/7120ad99b9bdd3d6dc648deb6ae5285d986f8744/src/state/themes-mixin.ts#L134

In the default theme the value of  `--app-header-background-color` and `--app-theme-color` is the same.

**Comment by bgoncal** [comment]
I had to revert the PR, the app theme color doesn't always match the navigation bar, which makes it look weird in some situations like dark mode using the default themes

**Comment by Nezz** [comment]
@bgoncal I think that should be fixed by this:
https://github.com/home-assistant/frontend/pull/20671

**Comment by bgoncal** [comment]
> Looks like the fix doesn't work. I'll try to get it patched up.

Let's wait a bit until this ir tested in the frontend and we are sure it will behave as expected, but I will keep this on the radar, feel free to drop a message in a week or two

**Comment by Nezz** [comment]
Sounds good. I opened the fix:
https://github.com/home-assistant/frontend/pull/20758

**Comment by bgoncal** [comment]
Closing this issue since both frontend and mobile PR's were merged, let me know in case its not behaving as expected

**Comment by Nezz** [comment]
Thank you. I grabbed the latest build from TestFlight. It's now the right color in light mode, but in dark mode the color does not change to the dark one.
