### ISSUE TITLE
Companion app extremely slow on Iphone 

### ISSUE THREAD

**Issue by Solarflor** [home-assistant/iOS#2760]
**iOS device model, version and app version**

Model Name: Iphone 15
Software Version: 17.4.1
App version: 2024.4 (2024.624)

**Home Assistant Core Version**
2024.5.1

**Describe the bug**
My wife have Iphone 13 and I have iPhone 15. Both phone’s companion app works extremely slow. It takes 15-20 seconds to register button clicks on dashboards or just moving through it .
Tried clearing front end cache. Tried reset. Tried reinstall. Same result
**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

The problem started with previous version of HA version but now it is impossible to use it.
Also other users are complaining the same problem.

**Comment by bgoncal** [comment]
How's does it behaves on iOS Safari?

**Comment by Solarflor** [comment]
You mean Safari on Iphone? same issue.

**Comment by bgoncal** [comment]
> You mean Safari on Iphone? same issue.

Yes, in this case the issue is not related to the App, it's probably front end or core, please considering opening an issue in those repos.

Perhaps it's the same as this? https://github.com/home-assistant/frontend/issues/20697
