### ISSUE TITLE
macOS app - Assist dialog can't be closed via keyboard shortcut

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/iOS#2764]
**Device model, version and app version**

Model Name: M1 MBP
macOS Version: Sonoma 14.4.1 (23E224)
App Version: 2024.4.1 (2024.671)
Safari Version: Version 17.4.1 (19618.1.15.11.14)

**Home Assistant Core Version**
2024.5.2

**Describe the bug**
The macOS app has a native UI for Assist which is great. The one minor drawback is there's no way to close the assist window using keyboard shortcuts. 

When accessing HA directly through the browser you can press esc key to dismiss this dialog (just like with Quick Bar dialog), but that doesn't work in macOS app. Also tried cmd-w and that doesn't work either. Would be nice to easily close via keyboard shortcuts in case of accidental misclick etc.

**To Reproduce**
Open assist dialog, try to close via kb shortcuts

**Expected behavior**
esc key to dismiss assist dialog

**Screenshots**

**Additional context**

**Comment by bgoncal** [comment]
Voilá
