### ISSUE TITLE
Automatik Displaylock Not Working When Homeassistant App is Open 

### ISSUE THREAD

**Issue by silvar05123** [home-assistant/iOS#2778]
**iOS device model, version and app version**

Model Name: iPad 
Software Version: 16.7.7
App version: 2024.4
Server: 2024.5.3

**Home Assistant Core Version**

**Describe the bug**
I have guided access enabled on iPad the automatic Display lock doesnt work When I use the App. On Safari the Auto lock works fine.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by bgoncal** [comment]
Can you elaborate on that? I am not sure I understood which behavior you are talking about, perhaps share a screen recording

**Comment by silvar05123** [comment]
Now with the New iOS Update its working fine… sorry 🤦
