### ISSUE TITLE
App loses / deletes server configuration

### ISSUE THREAD

**Issue by litronics** [home-assistant/iOS#2780]
Model Name: Iphone 12
Software Version: 17.5
App version: 2024.4(2024.624)

**Home Assistant Core Version**
2024.5.4

**Describe the bug**
The Iphone forgets the server configuration and starts without any configured server. When configuring a new server, the app works as expected.

**To Reproduce**
Configure a Server and wait for a few hours without using it.

**Expected behavior**
Server is stored and remembered all the time (as on our Iphone 15)

**Comment by bgoncal** [comment]
Can you reproduce the issue?

**Comment by litronics** [comment]
Good question. 
There is no action we can take to reproduce it directly.
It just happens when the app is not used for some time.

**Comment by bgoncal** [comment]
> Good question. There is no action we can take to reproduce it directly. It just happens when the app is not used for some time.

So it happened more than once?

**Comment by litronics** [comment]
Yes, otherwise I would have thought that we might made a mistake while configuring the server.

As said earlier - there is no specific action we can take to reproduce this.
After configuring the server the app works fine with no issues.

After not using the app for a while, the server configuration is gone and we need to reconfigure the server. I don't know the exact time required to loose the server configuration but I guess its either some background task, a wakeup procedure after reactivating the app or an IOs issue with the storage causing that issue.

Just as a side note - there is enough free space on the iphone and it shouldn't be an issue to store the configuration :)

Is there some kind of log I can turn on, which logs all what happens when the app is not actively used?

**Comment by bgoncal** [comment]
In the App settings inside "Debugging" you can find a button to export logs, when this happens again please do so (after login of course)

**Comment by litronics** [comment]
[2024-05-27_12.34.11+0200.logs.zip](https://github.com/home-assistant/iOS/files/15455270/2024-05-27_12.34.11%2B0200.logs.zip)

These are the logs from the App. There are some errors but I don't know if they are related to our issue.

**Comment by bgoncal** [comment]
So it happened again?

**Comment by litronics** [comment]
actually yes - we just didn't use the app for a few hours and had to reconfigure the server.

Here the new logs:
[2024-05-27_19.10.56+0200.logs.zip](https://github.com/home-assistant/iOS/files/15464894/2024-05-27_19.10.56%2B0200.logs.zip)

**Comment by bgoncal** [comment]
Let's try deleting the App from the devices that have the problem, rebooting and installing the latest App Store version 2024.5

**Comment by litronics** [comment]
Unfortunately the same behaviour.

Here the logs:
[2024-05-29_22.52.19+0200.logs.zip](https://github.com/home-assistant/iOS/files/15495458/2024-05-29_22.52.19%2B0200.logs.zip)

**Comment by zacwest** [comment]
You're signed in as a local only user. Accessing outside your local network is expected to fail.

**Comment by litronics** [comment]
> You're signed in as a local only user. Accessing outside your local network is expected to fail.

You may be right. But that is not the issue.
The issue is that HA starts as it hasn't been connected to ANY sever previously. After an hour not using HA it just forgets all configured connections.

**Comment by fenderle** [comment]
I have the same issue here with my phone and my wife's phone. It's super annoying and started a while ago. Not exactly sure when. Everything is at the latest version.

**Comment by mundschenk-at** [comment]
I think the issue is triggered when it can't access the configured (external) address a certain number of times.

**Comment by litronics** [comment]
> I think the issue is triggered when it can't access the configured (external) address a certain number of times. I can reproduce it at will when switching between a non-WiFi network that is allowed to access the server and a WiFi network that is not.

Interesting idea - however, we do have two iPhones, one is working the other one shows that behavior. Therefore I would guess, that accessing the address is not the issue.

**Comment by mundschenk-at** [comment]
It may not be the only trigger for the issue, but it apparently is _a_ trigger.

**Comment by litronics** [comment]
Funny thing though - after updating HA Core to a newer version it works now and both iPhones are connected without any issues.

Currently we are running version: 2024.6.2

**Comment by mundschenk-at** [comment]
@litronics That might have removed the trigger for your case, but not the general issue. I am running 2024.6.4 and I can (unfortunately) still reproduce the issue whenever I am on the wrong network.

**Comment by litronics** [comment]
@mundschenk-at That seem to be a different issue than mine. Probably it would be a good idea to open a new issue. There you can describe precisely how you are able to reproduce that issue.
In our case we just didn't use the app for some time. But in your case you seem to be connected to the wrong network - this could be a standard behavior from the app.

**Comment by mundschenk-at** [comment]
It's not the wrong network per se, just one not authorized. I don't think the app should ever delete the configuration without prompting by the user. 

Not sure when I'll have the time to create a new issue since I am on the road (which is why I noticed), but OK.

**Comment by ChristopherGerdes** [comment]
FYI, this has started happening to me as well as of about a week ago

**Comment by grownuphacker** [comment]
Just dropping in to say I'm experiencing the behaviour from about a week ago. Everything latest version on an iPhone 15.  If there's any debug logs I can send to help, just ask.  

My setup is an auto updating docker container (does not happen after updates) and multiple AP roaming wifi.  Periodically simply forgets all server data.

**Comment by grownuphacker** [comment]
Interesting detail - I'm also using a personal domain on CloudFlare and we're having multiple isolated intermittent faults on CloudFlare proxy at work (SaaS software).

**Comment by ChristopherGerdes** [comment]
This appears to still be happening.  Can we reopen it?

**Comment by bgoncal** [comment]
Continue the discussion here: https://github.com/home-assistant/iOS/issues/3141#issuecomment-2477071156
