### ISSUE TITLE
watchOS App 2025.5 not able to fire actions anymore

### ISSUE THREAD

**Issue by felixmueller** [home-assistant/iOS#2783]
**iOS device model, version and app version**
Model Name: iPhone 13 Pro / Apple Watch Series 7 41mm
Software Version: iOS 17.5.1 / watchOS 10.5
App version: 2024.5

**Home Assistant Core Version**
2024.5.4

**Describe the bug**
No actions can be fired with the Watch App anymore, Watch App is showing a spinner and cancelling after half a minute or so showing a big X for a second. The iOS App debug log is not showing any action and HA is not receiving any events. Tried it with custom iOS actions and scenes. Both can be triggered via iOS, but not watchOS. No difference between server synced or manually added actions.

**To Reproduce**
Add some scenes as actions to the companion app and try to trigger them via the Watch App

**Expected behavior**
The actions are fired instantly and confirmed by vibrating the Watch to indicate success

**Screenshots**
<img width="1292" alt="watchOS_actions_bug" src="https://github.com/home-assistant/iOS/assets/115331/1c03a15c-c5aa-4b45-8104-54752bb56066">

**Additional context**

**Comment by TomBrien** [comment]
I've seen similar things after app updates. Are actions working on the phone? Might be worth trying restarting the phone and see if that resolves it (this has worked for me before).

**Comment by felixmueller** [comment]
@TomBrien It seems to affect cases without WiFi connection. @bgoncal already did some changes trying to fix it: https://github.com/home-assistant/iOS/pull/2784/files

**Comment by TomBrien** [comment]
I've been running 2024.5 for a while and my actions work fine without WiFi.

**Comment by bgoncal** [comment]
Issue was auto closed by my PR merge, I already submited a new beta for Apple review, it's version should be 2024.5.1 in case it shows up for you

**Comment by felixmueller** [comment]
@bgoncal Thank you very much for your fix, I can confirm the actions now fire on my watch on the current TestFlight build 2024.5.1. I hope to see an official bugfix release in the App Store soon 😎
