### ISSUE TITLE
Watch actions are now blocking

### ISSUE THREAD

**Issue by TomBrien** [home-assistant/iOS#2785]
**iOS device model, version and app version**

Model Name: iPhone 14 pro / series 8
Software Version: iOS 17.5 / watchOS 10.5
App version: 

**Home Assistant Core Version**

**Describe the bug**

Watch actions used to be queue able, i.e. tapping multiple actions would fire them all in order without having to wait for each one to be confirmed. This was great if you wanted to quickly carry out a number of tasks (for example when walking into a room, turn the lights on, close the blinds and turn the TV on). Now when actions are fired the UI blocks other actions from being selected until the first has completed meaning what used to take a couple of seconds now takes tens of seconds or longer.  

**To Reproduce**

**Expected behavior**

It'd be nice to be able to "queue up" actions again, not have to wait for each to be acknowledged. 

**Screenshots**

**Additional context**

**Comment by bgoncal** [comment]
Good point, I will change it back to the old way

**Comment by TomBrien** [comment]
Thanks Bruno. I wondered if the blocking behaviour could be limited to each action's button. I.e. a spinner on the right and block that button, avoiding accidental double taps would be awesome.

**Comment by bgoncal** [comment]
> Thanks Bruno. I wondered if the blocking behaviour could be limited to each action's button. I.e. a spinner on the right and block that button, avoiding accidental double taps would be awesome.

Thats what I also had in mind 🤘🏻

**Comment by bgoncal** [comment]
@TomBrien I used the spinner replacing the action icon, but the rest is the same, chekc the PR video and let me know what you think

**Comment by TomBrien** [comment]
That looks brilliant. I'll test it when that merges and let you know. Thanks Bruno

**Comment by TomBrien** [comment]
@bgoncal Just tried the new build, seems perfect! Thanks again

**Comment by bgoncal** [comment]
Thank you!
