### ISSUE TITLE
Assist from widget and lockscreen not hearing anything

### ISSUE THREAD

**Issue by skycryer** [home-assistant/iOS#2792]
**iOS device model, version and app version**

Model Name: 
Software Version:  iOS 17.4.1
App version: 2024.05

**Home Assistant Core Version**

Home Assistant 2024.5.5

**Describe the bug**
When I open assist from lockscreen or widget it does not hear me. I need to stop and start listening several times until it maybe hears me. 

**To Reproduce**
Open assist from lockscreen or widget and try to talk to assist. 

**Expected behavior**
Should hear me after opening app from widget or shortcut

**Screenshots**

**Additional context**

Tested with iPad Pro 4. generation and iPhone 11 both with latest iOS and app version. 

Just tried reinstall app to reset maybe access problems did not help.

**Comment by skycryer** [comment]
Another strange behavior is that Bring mich nach Hause when it hears me speaking it understand something completely wrong. Saying like „turn on living room light“ show in app „yes“ as my sentence. Assist does not understand that that is clear. MöchteBut why does it understand something completely different.

**Comment by bgoncal** [comment]
I merged a PR last week to fix this issue where Assist were not able to understand what is being said, if you time could you check testflight version 2024.5.1?

**Comment by skycryer** [comment]
Sure I can

**Comment by skycryer** [comment]
So it can be marked as fixed with 2024.5.1 I would say

**Comment by bgoncal** [comment]
Sweet, thanks for checking!
