### ISSUE TITLE
Login Attempt of Request with Invalid Authentication from...

### ISSUE THREAD

**Issue by MrBogger** [home-assistant/iOS#2793]
When trying to log in to HA locally on iOS app (2024.5), it connects but then comes up with a "The server has rejected your credentials" error. I have also raised (https://github.com/home-assistant/core/issues/118173#issue-2317705070) as a Core issue. Safari and Firefox iOS browsers ok, MacOS browsers ok, Windows Browsers ok, MacOS App 2024.4 ok.

Model Name: iPhone 13 Pro, iPhone SE
Software Version: 17.4.1
App version: 2024.5.5
HA Supervised: Core - 2024.5.5 (One on HyperV and one on RaspPi3B)
[Perkins Home Versions.txt](https://github.com/home-assistant/iOS/files/15447562/Perkins.Home.Versions.txt)

**Describe the bug**
Unable to login using iOS app locally.

**To Reproduce**
Logging in through iOS app with any user.

**Expected behavior**
Successful login and operation.

**Screenshots**

![IMG_6748](https://github.com/home-assistant/iOS/assets/32661657/fb3ff544-0d1b-45e2-91c9-4ec808f73244)
![IMG_6747](https://github.com/home-assistant/iOS/assets/32661657/045c0ecb-d671-408d-9f7c-47bd9b6508d4)

**Additional context**

![Screen Shot 2024-05-26 at 19 35 32](https://github.com/home-assistant/iOS/assets/32661657/69fb7e2c-faad-4cd3-9031-6f3ff24e338c)
<img width="1292" alt="Screen Shot 2024-05-26 at 19 42 11" src="https://github.com/home-assistant/iOS/assets/32661657/92f5e7e6-8728-477e-b7fd-0131fd3aad7b">

I have tried different users, different passwords, rolling back Core versions but still not working. Seems to have coincided with the latest App release on Apple Store.

 Application logs:
[Home Assistant.txt](https://github.com/home-assistant/iOS/files/15447565/Home.Assistant.txt)
[HomeAssistant-Extensions-PushProvider.txt](https://github.com/home-assistant/iOS/files/15447566/HomeAssistant-Extensions-PushProvider.txt)
[HomeAssistant-Extensions-Intents.txt](https://github.com/home-assistant/iOS/files/15447567/HomeAssistant-Extensions-Intents.txt)
[HomeAssistant-Extensions-Widgets.txt](https://github.com/home-assistant/iOS/files/15447568/HomeAssistant-Extensions-Widgets.txt)

**Comment by bgoncal** [comment]
Was it working on a previous app version? Have you tried to reinstall the App?

**Comment by MrBogger** [comment]
Hey matey, I have deleted the app, restarted my phone and reinstalled the app to no avail. I tried on my other iPhone SE which has never had a HA app on it and it's the same fault. The previous app version was working yes.

**Comment by MrBogger** [comment]
Hey,

Tested with 2024.5.1 (2024.684) and it works / logs on as per normal.

[HA iOS 2024.5.1 Log.txt](https://github.com/home-assistant/iOS/files/15453530/HA.iOS.2024.5.1.Log.txt)

**Comment by bgoncal** [comment]
That even weirderer, 2024.5.1 has just a fix for Assist feature, nothing related to login, but good to know that it works for you

**Comment by MrBogger** [comment]
I've just tried again with my iPhone SE with the App Store Version, and not working. The log files are from an attempt to log in last night and again now. I'm using the same user to login with on both phones.

[Home Assistant.txt](https://github.com/home-assistant/iOS/files/15453667/Home.Assistant.txt)

**Comment by bgoncal** [comment]
So 2024.5.1 fixes it for you?

**Comment by bgoncal** [comment]
I'll close this but let me know and I can reopen if needed
