### ISSUE TITLE
Actions not working on Apple watch when connected via External URL

### ISSUE THREAD

**Issue by no-compromise** [home-assistant/iOS#2799]
**iOS device model, version and app version**

Model Name: iPhone 15 Pro, Watch Series 6
Software Version: iPhone: 17.5.1, Watch: 10.5
App version: 2024.5 (2024.678)

**Home Assistant Core Version**

2024.5.5
**Describe the bug**
When my iOS Companion app is connected via external URL, the actions that I have set in app dont work on Apple watch. They are listed in HA shortcut on watches, but on click after a few seconds the cross appears and action is not performed. When I fire action within app on phone (long press HA icon and select action) then the action is performed correctly. This bug does not appear when Im connected via internal URL.
**To Reproduce**

**Expected behavior**
Actions should work on Apple watch when connected via external URL

**Screenshots**

**Additional context**

**Comment by bgoncal** [comment]
Duplicated: https://github.com/home-assistant/iOS/issues/2783

Fix coming most probably this week to App Store
