### ISSUE TITLE
Issue with layout and color on iOS

### ISSUE THREAD

**Issue by MelleD** [home-assistant/iOS#2800]
I am currently using the following custom component: https://github.com/MelleD/lovelace-expander-card
The color changes and the responsive design work on the Safari and Chrome browsers on the iPhone and Mac.

Some examples on iPhone safari browser

Example one: Header is white and arrow is white
![bild1](https://github.com/home-assistant/iOS/assets/6340898/7ea8ca7e-744d-4894-b808-a09da9d27bce)

Color red and green:

![IMG_2545](https://github.com/home-assistant/iOS/assets/6340898/32e6febb-ea4a-4b3b-b4c2-8a99879dfb2d)

Open the expander, layout is working and shrinking to the screen size

![IMG_2546](https://github.com/home-assistant/iOS/assets/6340898/a0d51529-b565-431b-bcfb-2134b146971c)

As soon as I open the same thing in the app, the colors no longer work (always blue) and the layouts become larger and not adjusted.

Example 1 header and arrow are blue instead of white

![IMG_2547](https://github.com/home-assistant/iOS/assets/6340898/3aceb546-b47c-44fb-bcf8-7b34c7d01a24)

Example 2: Coloring red and green also not working
![IMG_2548](https://github.com/home-assistant/iOS/assets/6340898/8daa55ff-3984-46b5-a5b6-b90eb383b645)

Example 3: And the biggest issue the layout is broken and not shrinking

![IMG_2549](https://github.com/home-assistant/iOS/assets/6340898/05951338-5232-4d97-b52a-aff4c7c17b45)

I have no idea if something needs to be changed in the component or if it's a problem in the app. I would have expected if everything worked on the browser (Mac and iPhone) there would be a problem in the app.

Can I somehow debug and isolate the problem in the app?

**iOS device model, version and app version**

Model Name: iPhone 14
Software Version: 17.5.1
App version: 2024.5.1
Core: 2024.5.5

EDIT: The App on macOS and Android is working. Issue is only on the iOS App

**Comment by NikolayKaradzhov** [comment]
Hello @MelleD , 

I also have similar problem with colors on iOS only with lovelace custom cards, both companion app and in safari browser.

![441458818_1507901643442582_3331665465720487535_n](https://github.com/home-assistant/iOS/assets/35952928/fe3c1a01-cfbd-4ba0-adb6-e8e8813dfaa5)
![windows - ha](https://github.com/home-assistant/iOS/assets/35952928/679332e1-e925-44c9-9662-a02f8620f153)

**Comment by MelleD** [comment]
Hey @NikolayKaradzhov

If it is also in the Safari browser, it could also be an error in the custom card (maybe).
In my case, all options work. Any browser including Safari (Desktop and mobile), Android app, macOS app.

Except the iOS app doesn't work. The colors are particularly a problem, because with a white default theme the arrow are also white and completely unusable.

**Comment by NikolayKaradzhov** [comment]
Hi again @MelleD ,

From another forum, people have guided me to play around with the themes in settings for the companion app, I have selected minimalist-mobile theme, and it worked.

**Comment by MelleD** [comment]
Thanks for the tip @NikolayKaradzhov .
I would hate to change the default (dark and white) theme :(.
Since it only appears in the iOS app, I think it could be a bug.

**Comment by MelleD** [comment]
I also changed the theme now it's working also in the App
