### ISSUE TITLE
Assist: Intent not passing`conversation_id` since 2024.5

### ISSUE THREAD

**Issue by goniz** [home-assistant/iOS#2801]
**iOS device model, version and app version**

Model Name: iPhone 13 Pro
Software Version: 17.5.1
App version: 2024.5.1

**Home Assistant Core Version**

2024.5.5

**Describe the bug**
When using the new Assist intent, it does not retain the conversation id between api calls.

**To Reproduce**
Ask the (LLM based) assistant some question that has follow up and it won't understand what you want 😅

**Expected behavior**
The conversation_id should be passed to subsequent conversation/process api calls to give the agent the previous messages as context.

**Screenshots**

![image](https://github.com/home-assistant/iOS/assets/976803/6b3ea28f-8669-4dd4-97a6-0259e1352579)

**Additional context**

https://github.com/home-assistant/iOS/blob/master/Sources/Shared/Intents/AssistIntentHandler.swift#L70

**Comment by bgoncal** [comment]
Good catch, PR open to fix that

**Comment by goniz** [comment]
> Btw, out of curiosity, which approach you used to have OpenAI able to control your devices?

I'm using https://github.com/jekalmin/extended_openai_conversation through OpenAI or Openrouter.ai
