### ISSUE TITLE
 iOS notification via web socket support on VPN connection.

### ISSUE THREAD

**Issue by wakawakaaa** [home-assistant/iOS#2802]
**iOS device model, version and app version**

Model Name: iPhone 15
Software Version: 17.5.1
App version: 2024.5.1

**Home Assistant Core Version**

core-2024.5.5 
Home Assistant Supervised, Home assistant as virtual machine

**Describe the bug**

Currently Web Socket Notification only supported via Wifi connection to specific network, but it should also include VPN support. So, when iOS connected via VPN, it should also tries to connect to internal URL of Home assistant.

And also have a option to completely turn off apple servers for notification.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by bgoncal** [comment]
We don't track feature requests in GitHub, please use Home Assistant Community for that.
