### ISSUE TITLE
App deletes server configuration when connected through an unauthorized network

### ISSUE THREAD

**Issue by mundschenk-at** [home-assistant/iOS#2824]
**iOS device model, version and app version**

Model Name: iPhone 12 mini, iPad Pro 11" 3rd Gen
Software Version: 17.5.1
App version:  2024.5.1

**Home Assistant Core Version**
2024.6.4

**Describe the bug**
The app deletes the network configuration when connected to an external network that is not authorized to connect to the HA instance. This is a follow-up to the previously reported issue #2780.

**To Reproduce**
1. Set up external access with a limitation to what devices are allowed to the HA server. In my specific case, that is handled through CloudFlare ZeroTrust, but that's ab implementation detail. 
2. Make two networks connections to switch between (e.g. LTE and WiFi, or plain WiFi and a VPN), with one network allowed to connect to the server and the other not. Both networks should resolve the DNS name to a valid IP though.
3. Set up the HA server while connected to the authorized network. Log in with your user.
4. Exit the app.
5. Switch to the non-authorized network.
6. Open the app. Your server configuration will now be deleted. Even when you switch back to the authorized network, the configuration is still gone.

**Expected behavior**
The app displays an error message that it can't connect to the server instance, but does not delete the configuration.

**Additional context**
I believe the problem surfaces because the app receives a HTTP response to its API calls, but of course not the expected one, so thinks the URL is incorrect. IMHO that is not a valid reason to delete the user's configuration though.

**Comment by bgoncal** [comment]
The way that the app was designed was: if there is a reachable URL and the user is not authorized, you will be redirected to the onboarding flow to authenticate, anything more specific than that is not expected to work and would be considered a feature request.
Let me know in case I missunderstood

**Comment by mundschenk-at** [comment]
The HTTP status code is 403, correct. However, I don't see why this should be a reason to

1. start a new "onboarding" flow from scratch without user confirmation (since obviously the user was already onboarded)
2. discard existing server and user names even if such an onboarding flow would actually be desired - you can easily keep the data with the existing dialogues

Furthermore, I have now discovered this whole mess creates multiple entries for the same device under the Mobile App integration (that apparently cannot even be deleted).

I am sorry, but that does not meet the "missing feature" definition for me by a wide stretch.

**Comment by bgoncal** [comment]
The "onboarding" flow is just for convenience of reusing the same login screens, if you reauthenticate nothing will be lost, if you don't, it means the server should be removed indeed considering you can't authenticate to it.

Perhaps the setup you have is not something we support yet, please allow access externally to users that have external URL set or remove the external URL for now.

About not being able to remove the mobile app integration entry, which error do you see when you try to remove?

**Comment by mundschenk-at** [comment]
Regarding external access: It is limited by country to reduce the attack surface, but I am currently abroad - this causes an issue when I am logged into a WiFi network instead of cellular because obviously the WiFi IP is in the wrong country. Not having access when I am on WiFi is fine, having to reauthenticate everytime I (by habit or because of a notification) switch to HA is not.

Regarding the spurious integration entries: There is no error when I click "delete", they are just not deleted but marked as "unloaded" instead.

**Comment by bgoncal** [comment]
I understand what you want to achieve, but the app doesn't support this setup, or you have external access always or you don't, for now this is the cases we cover, that's why I mentioned a feature request.

About removing the integration, I'm investigating it now.

**Comment by LittleNo** [comment]
Same issue here, but a little simpler: I use HA cloud for remote access, with TOTP 2FA enabled for all of my users. I don't need to use the WebUI remotely (only use the iOS App remotely), therefore I disabled remote access for my users. With an first attempt, leaving the home Wifi, the App re-connects thru HA cloud. But after a while of not using the app on a foreign network, the app stays blank (I guess it's trying to re-connect somehow) and after a restart I have the same situation as all others here: the server was deleted from the App

Please don't tell me that's not the use case your app was made for. I'm just trying to make a secure access to my Home Assistant from outside. That's nothing that should be handled low priority by your project.

**Comment by bgoncal** [comment]
@LittleNo If you disable remote access in HA cloud, App won't be able to access your HA when you are not at home. What the app displays is the "WebUI".

**Comment by LittleNo** [comment]
If you're right, I will accept that and stop using it, because its simply unsecure then (in that case the Cloud Service is nothing more than a reverse proxy, which can't deliver the required security level nowadays).

But: When I move from my home Wifi to LTE or a foreign wifi, the App works just fine. It shows its connected thru HA-Cloud. So your comment is just not true.

**Comment by bgoncal** [comment]
Checked and confirmed, if HA cloud remote access is disabled, your remote URL access (which the App uses to display the UI) is not available, the only thing the continues available is the sensor reporting through the coud webhook we create.

Can you send a screen recording showing the app working on local wifi and remotely (of course with remote access disabled)?
Please make sure you also show how your internal/external URL are configured

**Comment by LittleNo** [comment]
No, this one: 
![image](https://github.com/user-attachments/assets/2b0144a6-151a-4f1e-bca2-342050a8971e)

The Main Remote Access Toggle Switch is set to on. Without that the HA-Cloud can't work.

Here's the screen record:
https://github.com/user-attachments/assets/4bcb043d-0b65-4f59-84f3-71548ae2bd57

**Comment by bgoncal** [comment]
Ok, now it makes more sense. Next time it happens please export logs under companion app settings >> debugging and submit here: https://docs.google.com/forms/d/1lx0hKiN8D-YDTmMKybVeiBlrj4S4s1hczLrgNXTZsW8/edit

**Comment by LittleNo** [comment]
I've sent you the log

The issue can easily reproduced: Switch from Wifi to LTE, close the HA App completely, browse for 2 minutes thru other Apps, open HA App again > issue is there.

This time I saw this error message (it did not appear the other times): 
![IMG_8963](https://github.com/user-attachments/assets/fb0f04b7-764b-4d15-8eeb-97a59662c0ea)

**Comment by bgoncal** [comment]
@LittleNo If you perform the same routine accessing your external Url from iOS Safari directly, does it always work?

**Comment by LittleNo** [comment]
yes, the login can be performed:
![image](https://github.com/user-attachments/assets/6bdc5ca3-6b63-42b6-9a66-837bae3dd19d)


but then, of course, the access is denied:
![image](https://github.com/user-attachments/assets/bb937ccd-f1bb-44b6-8286-a12fd024bc14)

**Comment by bgoncal** [comment]
But are you trying to use a local-only user remotely? That will not work, your user needs to be able to login remotely using your remote URL

**Comment by LittleNo** [comment]
I thought that was what you wanted to test/see

I don't want any users to be able to login on the WebUI from a browser because I don't need it and therefore it's an avoidable security risk. I want the App to be allowed to continue working from outside thru HA cloud after it was initially connected internally. I don't know how HA cloud exactly works, but usually this scenario is handled by an App-Token. That allows the Apps to work remote, but others cannot login from outside.

**Comment by bgoncal** [comment]
I just double checked with cloud team and the behavior that you experience is what is expected on our side, App accessing HA remotely goes into the rule of "local-only user" the same way as browser. If you want remote access in the App as well then you need to allow users to not be local-only.

**Comment by LittleNo** [comment]
ok, thanks for clarification. In that case, the cloud is just a reverse proxy and does not offer any additional security.

In the end it's way too insecure and I will not use it.
