### ISSUE TITLE
Dashboard gets changed when on Cellular / Remote UI URL

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/iOS#2843]
**iOS device model, version and app version**

Model Name: iPhone 15 Pro
Software Version: iOS 18 dev beta 3 (unrelated to beta, happened on iOS 17 too)
App version: 2024.7 (2024.711) -- TestFlight

**Home Assistant Core Version**

2024.7.1

**Describe the bug**
I have a custom dashboard "Testbed" that I have set as the default on my phone (via profile page setting). Whenever my connection type changes over from Wi-Fi (Internal URL) to Cellular (Remote UI URL) it changes the dashboard too from my custom "Testbed" dashboard to the default auto-generated "Overview" dashboard. 

This isn't ideal, because I have several thousand entities including some "heavy" ones like live camera streams that take a while to load over cellular, and even on the latest iPhone 15 Pro it lags when trying to open the sidebar while all that is loading. So switching back to the correct dashboard is a bit of a pain.

Below is screen recording demonstrating.. You can see the dashboard it starts off with, and the auto-generated overview dashboard it changes as soon as the connection switches to cellular. 

https://github.com/home-assistant/iOS/assets/9065557/da3901d2-4a55-4733-9007-ace2a3945509

**To Reproduce**
1. On your profile page in HA, set your default dashboard
2. Navigate to the dashboard you set as default
3. Turn off Wi-Fi via the control center, so that you are on cellular
4. After reloading it on the remote UI URL, it brings you back to the auto-generated "overview" dashboard with all states

**Expected behavior**
Should not change dashboard

**Screenshots**

These are my connection settings, standard setup using Nabu Casa / Home Assistant Cloud.

![Screenshot 2024-07-10 at 1 51 11 PM](https://github.com/home-assistant/iOS/assets/9065557/26904171-9e83-4a7c-80c6-68f9d5551b62)

**Additional context**

**Comment by bgoncal** [comment]
If I am not mistaken this preferred dashboard settings is saved via cookies, so when you switch URL's you have a different set of cookies, can you try setting the default dashboard twice? Once using the external URL and another time the internal

**Comment by SeanPM5** [comment]
You're right, that seems to have fixed it. Thanks.

I'll close this issue but I still consider this somewhat of a bug / undesirable behavior. Being on Wi-Fi vs Cellular shouldn't be considered as two seperate devices with different settings.  

You can be using HA on your iPhone and then walk into your backyard outside of Wi-Fi range and suddenly you've got a different theme, completely different sidebar, different dashboard, etc. I understand the technical reasoning, but it's not ideal.

**Comment by bgoncal** [comment]
I totally agree with you, I'll share the feedback with the frontenders too so we can find a better approach.
