### ISSUE TITLE
Memory leak consuming 40GB RAM

### ISSUE THREAD

**Issue by lsuanet** [home-assistant/iOS#2846]
**Device model, version and app version**
Model Name: MacBook Pro M1 Pro
macOS Version: 14.5
App Version: 2024.6 (2024.696)
Safari Version: 17.5

**Home Assistant Core Version**
20246

**Describe the bug**
Home Assistant app consuming ~40GB of RAM.

**To Reproduce**
Not sure

**Expected behavior**
Consume less RAM

**Screenshots**

<img width="558" alt="Screenshot 2024-07-11 at 17 02 24" src="https://github.com/home-assistant/iOS/assets/11297330/0c3ffe6e-6b66-47c4-b05c-6b3d53481f4b">

**Additional context**

**Comment by bgoncal** [comment]
Duplicate, please use this issue to provide updates: https://github.com/home-assistant/iOS/issues/2101
