### ISSUE TITLE
Back swipe navigation opens menu

### ISSUE THREAD

**Issue by tomfrenzel** [home-assistant/iOS#2851]
**iOS device model, version and app version**

Model Name: iPhone 14 Pro
Software Version: iOS 17.5.1
App version: 2024.696

**Home Assistant Core Version**
2024.7.2

**Describe the bug**
When swiping from the left screen edge towards the right, the navigation menu opens instead of returning to the previous page.

**To Reproduce**
Go into settings and open the any menu entry. Now swipe from the left screen edge towards the right.

**Expected behavior**
Instead of opening the navigation menu, the previously opened page should be displayed.

**Additional context**
This only seems to be an issue with the iOS App since the expected behavior works in Safari on iOS and also within the Android Companion App

**Comment by bgoncal** [comment]
Hi @tomfrenzel, this behavior is as designed, you can still go to the previous page by swiping with 2 fingers but the swipe from left to right is reserved for opening the side menu.

If you believe this should be different please open a feature request on Home Assistant Community, in GitHub we only track bugs.

**Comment by tomfrenzel** [comment]
Alright, but shouldn't i use the Feature Request page in this GitHub repo?

**Comment by bgoncal** [comment]
> Alright, but shouldn't i use the Feature Request page in this GitHub repo?

No, please use https://community.home-assistant.io/
