### ISSUE TITLE
Choices in drop down lists "not remembered" - Lists always start on top again

### ISSUE THREAD

**Issue by orgebar** [home-assistant/iOS#2857]
**iOS device model, version and app version**

Model Name: iPhone 12 Pro
Software Version: 17.5
App version: 20240710.0

**Home Assistant Core Version**

2024.7.2

**Describe the bug**

In general Choices or search words in drop down, search or suggestion lists are "not remembered" - If you enter the Lists again they always start on top again. E.g. If you made a choice from any drop down list within the app and like to switch to a different option which was below or above your choice you have to type in the seach word again or delete parts of your search or scroll for ages in long lists. 

Its very time consuming and user unfriendly, especially, if you want to use the UI e.g. for setting up long(er) automations, use services or even search for anything within the app.

**To Reproduce**

E.g. go to services, choose an option, then try to choose the option, which was above your choice in the drop down.

**Expected behavior**

When entering a dropdown, the lists should start at the last choice and not jump back to the first Option in the list.

**Screenshots**

![image](https://github.com/user-attachments/assets/27d2a752-5b6e-4f99-bf14-129170aba222)

**Additional context**

**Comment by bgoncal** [comment]
Can you check on iOS Safari if the same happens?

**Comment by bgoncal** [comment]
I tested on my side and the behavior also happens in iOS Safari, in this case please open an issue in the frontend repo. I'll be closing this one since it is not App-specific
