### ISSUE TITLE
Cannot get the Gauge widget to work on lock screen of iphone

### ISSUE THREAD

**Issue by d2too** [home-assistant/iOS#2887]
**iOS device model, version and app version**

Model Name: iphone 14 Pro
Software Version: was ios17 but have now also tried ios 18 dev beta
App version: 2024.7

**Home Assistant Core Version**
2024.7.4

**Describe the bug**
Trying to add a gauge widget to my lock screen with the following script but it just shows a gauge with question marks. The script works fine in dev tools, template and returns a number;
Script: 
{% set original = states('sensor.ioniq_5_ev_battery_level') | float %}
{% set minimum = 0 %}
{% set maximum = 100 %}
{% set adjusted = min(maximum, max(minimum, original)) %}
{{ (adjusted - minimum) / (maximum - minimum) }}

**To Reproduce**

**Expected behavior**
Display a gauge with my ev charge %

**Screenshots**

![image](https://github.com/user-attachments/assets/61c118bf-5148-4209-8ccb-0fb709cb66cd)

**Additional context**

**Comment by bgoncal** [comment]
```
{% set original = states('sensor.ioniq_5_ev_battery_level') | float %}
{% set minimum = 0 %}
{% set maximum = 100 %}
{% set adjusted = min(maximum, max(minimum, original)) %}
{{ (adjusted - minimum) / (maximum - minimum) }}
```

The variables that you are creating generates 4 empty lines in developer tools template, perhaps create a helper template (Settings > Devices & services > Helpers > Create helper > Template > Template a sensor )

And then use 
```
{{ states['sensor.your_new_sensor'].state }}
```

**Comment by d2too** [comment]
Thanks,
I just created a helper and have the script as per screenshot but still no go
[image0.png]
I'm out & about so may be short as Sent from my iPhone.

On 5 Aug 2024, at 10:46, Bruno Pantaleão Gonçalves ***@***.***> wrote:

﻿

{% set original = states('sensor.ioniq_5_ev_battery_level') | float %}
{% set minimum = 0 %}
{% set maximum = 100 %}
{% set adjusted = min(maximum, max(minimum, original)) %}
{{ (adjusted - minimum) / (maximum - minimum) }}


The variables that you are creating generates 4 empty lines in developer tools template, perhaps create a helper template (Settings > Devices & services > Helpers > Create helper > Template > Template a sensor )

And then use

{{ states['sensor.your_new_sensor'].state }}

**Comment by bgoncal** [comment]
What's the output of this helper? It needs to be between 0 and 1

For example mine I do this:

{{ states['sensor.tronity_e208_level'].state | float / 100 }}

**Comment by d2too** [comment]
> What's the output of this helper? It needs to be between 0 and 1
> 
> For example mine I do this:
> 
> {{ states['sensor.tronity_e208_level'].state | float / 100 }}

returns the battery level of my ev:  61%

**Comment by bgoncal** [comment]
It needs to return 0.61, check my example above

**Comment by d2too** [comment]
> It needs to return 0.61, check my example above

Just created the same as yours with my helper and still just get a gauge with ? either end.

**Comment by bgoncal** [comment]
Please send me a screenshot how it looks now (the widget config)

**Comment by d2too** [comment]
> Please send me a screenshot how it looks now (the widget config)

![image](https://github.com/user-attachments/assets/6c22eec6-b55f-46e6-a195-bcf86c15ce66)

![image](https://github.com/user-attachments/assets/129069a4-b1ed-4e4f-851c-7b290d84845c)

**Comment by bgoncal** [comment]
Does your helper returns  `61%` or `61`? If it includes `%` please make sure it doesn't, paste this in developer tools template and let me know the output.

Also, fulfill the other widget configuration fields just so we know if they are working of not for your

**Comment by d2too** [comment]
In developer tools if I use {{ states['sensor.ioniq_5_ev_battery'].state | float/100 }}  it returns an error of 
ValueError: Template error: float got invalid input 'unknown' when rendering template '{{ states['sensor.ioniq_5_ev_battery'].state | float/100 }}' but no default was specified

**Comment by d2too** [comment]
Hi, when i run the script through dev / Template it returns 0.61. 
If I put a 0 in Min label and 100 in Max nothing changes on the icon.

**Comment by bgoncal** [comment]
Please share your logs with me (Companion App settings > debugging > export logs)

**Comment by d2too** [comment]
Logs attached, thankyou.
[2024-08-05_13.14.34+0100.logs.zip](https://github.com/user-attachments/files/16495535/2024-08-05_13.14.34%2B0100.logs.zip)

**Comment by bgoncal** [comment]
```
App Transport Security policy requires the use of a secure connection." UserInfo={NSLocalizedDescription=The resource could not be loaded because the App Transport Security policy requires the use of a secure connection., NSErrorFailingURLStringKey=http://d2too2.asuscomm.com:8123/auth/token
```

What's your HA setup? Local IP for internal URL and `http://d2too2.asuscomm.com:8123/auth/token` for external?

**Comment by bgoncal** [comment]
```
App Transport Security policy requires the use of a secure connection." UserInfo={NSLocalizedDescription=The resource could not be loaded because the App Transport Security policy requires the use of a secure connection., NSErrorFailingURLStringKey=<http://YOUR-DOMAIN.com:8123>
```

What's your HA setup? Local IP for internal URL and `<http://YOUR-DOMAIN.com:8123>` for external?

**Comment by d2too** [comment]
Hi, yes local ip  for internal and a dynamic DNS pointing to has for external with port :8123

**Comment by bgoncal** [comment]
Ok, so first an advice, don't use remote access without HTTPS, secondly, will you be home soon so we can test if locally it works?

**Comment by d2too** [comment]
Hi, if I try my address with Https it doesnt like it. I wont be home unfortunately for another 5 hours

**Comment by bgoncal** [comment]
You need to configure "Let's encrypt" or something else to generate an SSL certificate for you.

When you get home, give it a try.

**Comment by d2too** [comment]
will do thankyou

**Comment by d2too** [comment]
Being I don't have a static Ip will this work? Also when I get home and I'm locally connected with the address can I test he gauge etc without changing to https first?

**Comment by bgoncal** [comment]
Yes

**Comment by d2too** [comment]
> Yes

Thankyou., for your help . Ill update you once home.

**Comment by d2too** [comment]
> Yes

When I get home onto my local network what do I need to do/check as upto now the gauge hasnt worked when I'm home.

**Comment by bgoncal** [comment]
Open the app, check if it is using your internal URL, remove your widget, add it again.
Then forward the logs to my email in case it doesnt work:
bruno.pantaleao@nabucasa.com

**Comment by bgoncal** [comment]
About the widget disappearing that you reported via email, this is iOS 18 bug, I had it myself, rebooting usually fixes it.

I'll check your logs tomorrow.

**Comment by d2too** [comment]
Ok, Thankyou

I'm out & about so may be short as Sent from my iPhone.

On 5 Aug 2024, at 19:05, Bruno Pantaleão Gonçalves ***@***.***> wrote:

﻿

About the widget disappearing that you reported via email, this is iOS 18 bug, I had it myself, rebooting usually fixes it.

I'll check your logs tomorrow.

**Comment by bgoncal** [comment]
```
2024-08-05 18:48:03.173 [Info] [com.apple.NSURLSession-delegate] [Environment.swift:71] init() > WebSocket: Received: result failure HARequestIdentifier(rawValue: 59): external(HAKit.HAError.ExternalError(code: "400", message: "{\"message\":\"Error rendering template: ValueError: Template error: float got invalid input \'unknown\' when rendering template \'{{ states[\'sensor.ioniq_5_ev_battery\'].state | float / 100 }}|?|100|0\' but no default was specified\"}"))
```

**Comment by bgoncal** [comment]
Apparently `states['sensor.ioniq_5_ev_battery'].state` is returning unknown so it can't be converted to float, double check it in developer tools

**Comment by d2too** [comment]
> {{ states['sensor.tronity_e208_level'].state | float / 100 }}
Hi,
I have Sent you an email. Had to reboot HA as sometimes the Kia/Hyundai add in doesnt always grab the info. now working and works in dev tools but not on phone. Sent the logs to your email

**Comment by bgoncal** [comment]
your logs display the same error message, please send me a screenshot from your dev tools and remove the widget and add it again.

**Comment by bgoncal** [comment]
Oh your logs are still the old one's, can you try exporting again? Latest erro was 13:06 CET

**Comment by d2too** [comment]
Just sent email with latest log and here is a screen shot of dev tools 
![image](https://github.com/user-attachments/assets/4f51f983-07f9-4564-9b54-12a1adf3336f)

**Comment by bgoncal** [comment]
Still nothing new in the logs, did you remove and added back the widget? Let's talk in discord if you have time, (I am bgoncal2 there)

**Comment by bgoncal** [comment]
Issue resolved, apparently something related to timin of when the car integration was reporting "unknown" and widget timeline is reloaded. I'll close the issue for now and reopen if needed.
