### ISSUE TITLE
Performance problems

### ISSUE THREAD

**Issue by skycryer** [home-assistant/iOS#2912]
**iOS device model, version and app version**

Model Name: iPhone 11, iPad 12 pro 4. generation
Software Version: iOS 17.5.1
App version: 2024.730

**Home Assistant Core Version**

2024.8

**Describe the bug**
I use ha on several devices, some with companion app some in browser. My devices are all not the newest but also on my work machine an MacBook Pro Max m2 I see problems. But my focus is on my iPad and iPhone. Often I sit there, think about something to improve on my dashboard or add a new automation like today. I wanted to edit a complex automation that controls several window positions. I wanted to add a window here but had to give up. It was so slow opening the choose parts or even edit the new trigger that it was not usable. 

Not sure how I could better describe it. I run ha on an intel nuc i5, also not with that much power. But I think it is more a client thing. 
like when I use browser_mod there is a difference visible in safari or chrome, not usable on safari but on chrome it is good, but that is not related. 

I can browse my dashboard mostly fine, as long as I do not try to edit it on iPhone or iPad. 

Same appears when I open ha on safari direct, so if the app is just using the website and browser engine sure it has same issues. But then it should be worked on general performance for the Frontend. Or is my setup so different and my dashboard and automations just to complex, I can not believe that. 

**To Reproduce**

**Expected behavior**
It should be fast on browser and app, in using dashboard also Edit the dashboard or writing automations or debugging on mobile devices. 

**Screenshots**

**Additional context**

If I can add logs or screen recordings showing the problem I am happy to help.

**Comment by bgoncal** [comment]
Just checking but if the slowness happens in iOS Safari as well as in iOS HA app, please open an issue to frontend repo.

**Comment by PrathikGopal** [comment]
Fully slow to render any card on ios 16.7.8

**Comment by bgoncal** [comment]
Closing the issue since it is not App specific, please open an issue to frontend repo.
