### ISSUE TITLE
Companion app extremely slow, laggy and instable on Iphone, while browser based use works great (Safari, Chrome etc)

### ISSUE THREAD

**Issue by uTZFu** [home-assistant/iOS#2917]
**iOS device model, version and app version**
iPhone 12 Max Pro IOS (17.6.1)
iPhone SE II IOS(17.6.1) 

Latest Companion Version 

**Home Assistant Core Version**
Core (2024.8.1)
Supervisor (2024.08.0)
OS (13.0)
Frontend (20230809.0)

**Describe the bug**
The companion app is not at all useable for us since it is very slow. The problem exists since a while and i switched to using the browser instead. Since the family is now getting more involved I would love to get the app usable for them. 

- Touch inputs seem to "hang"
- Touch inputs are often not recognised at all
- The app is laggy and extremely slow as if it would be calulating or waiting for something.
- Scrolling up and down is laggy and unresponsive. 
- This happens on any page and dashboard within the app
- The problem seems to get bigger over time and often leads to a app stalling at the end
- On the iphone SE stalling occures very fast compared to the iphone 12 pro max
- On any iphone accessing HA via the browser (Chrome & Safari tested) works flawless and impressively fast as from any other computer.

**Actions taken**
- I have updated all application to the latest available Home Assistant companion App, all Integrations are up to date and IOS versions too.
- I have cleared the cache of my browser.
- I removed the app and reinstalled it (reboot inbetween etc)
- I changed internal and external URIs and access via VPN from outside
- I removed the known devices yaml
- I followed issue #2822 and https://github.com/home-assistant/frontend/issues/20728 (Checking DB and Utilisation, Updated lovelace modes and changed standard dashboards - all without sucess - the app is still standing while the browser is running :-) 
- Also played with all different variations of privacy settings in the companion app without any luck 

**Expected behavior**
Same as via the browser  - fast and reliable.

**Additional context**
Not sure what else i could try to resolve those issues and be able to use the companion app again - any hints?
And sorry in case this is not the correct location for this issue

**Comment by bgoncal** [comment]
Please always specify App version when opening a github issue, I assume latest you mean `2024.7`?
Did you try to reset frontent cache going to `Companion App settings >> debugging >> reset frontend cache`?

Please export your logs (`Companion App settings >> debugging >> export logs`) and send it to: https://forms.gle/hvTfeMWoADXCZgkj9

**Comment by uTZFu** [comment]
Hi Bruno - thanks for your support. Yes - Latest version was 2024.7. I tried resetting cache, resetting full app, removing and adding servers, removing app (with restart inbetween). Even tried the beta version via Testflight (2024.8 (2024.771) all without success so far. Also checked the logs - will send em tonight!

**Comment by bgoncal** [comment]
Thanks, also a screen record comparing iOS Safari with iOS App if possible

**Comment by uTZFu** [comment]
Hey Bruno, got the screen capture and the logs, but cant get access to https://forms.gle/hvTfeMWoADXCZgkj9 (Erforderliche Berechtigung fehlt, Dieses Formular dürfen nur Nutzer ansehen, die zur Organisation des Eigentümers gehören). Any hint? Thanks in advance!

**Comment by bgoncal** [comment]
That's weird, I'm far from my computer right now but send me an email instead then Bruno.pantaleao@nabucasa.com

**Comment by bgoncal** [comment]
Received ✅

It indeed looks extremelly slow, do you know how many entities do you have?
Also please send me how your server configuration looks like (internal and external URL, screenshot is enough).

Finally, could you try creating a non-admin user, let this user only have access to a blank dashboard and remove access to the other dashboards, then:
- Remove Server from App
- Reboot device
- (Optionally) Download current beta from testflight
- Add server again using this test user to sign in

**Comment by uTZFu** [comment]
**Entities:** Too many - roughly 40k entities. But basically this should be due to the BLE Tracking if i understand it correctly. Just a fraction of those are really used and i understood this is due to the nn consistent MAC Addresses of those devices. Also deleted the known devices.yaml to reduce the comparision against this list since it grew to almost 4 Mb in Size over time. If the number of entities is a potential root cause for the speed of the companion app, why is this then not visibile via the browser? Just asking to better understand :-)

**Server Config:** Minimal - only reachable via internal URL (IP based) no external access setup, no cloud utilisation, no usage of the HomeAssistant.local naming. Standardport 8123, not encripted. Also played around with other setups but they all did not make any difference at all. Works flawless on the browser as you could see.

**Non Admin Test:** Tried this before, too (also with a blank dashboard, new users, minimal setup) - could not really test for the slowness this way thou. Also had no effect on the usability after i selected the former user with maximum rights afterwards

**Beta from Testflight:**Tested this seperately but will test it again with a new, minimum user on an empty dashboard tonight.

**Comment by bgoncal** [comment]
I believe the problem then is the 40k entities, we have a subscription to state change in the app that listen to state changes all the time and keep things in sync, 40k entities updating could be messing up.
Would it be ok to share guest access to your HA instance with me? you can block everything if you want, I just need to check if the state sync is the problem. (You mentioned no external access, can you temporarely enable it? Perhaps HA Cloud trial?)

[Bruno.pantaleao@nabucasa.com](mailto:Bruno.pantaleao@nabucasa.com)

**Comment by uTZFu** [comment]
Then let me test something tonight upfront (Tried to incapsulate HA quite strong and made it challenging to access from outside :-) )

- 1. I will try to remove the BLE Device Tracking from my configuration yaml, in case there is no effect, 
- 2. I will remove any other devices Tracking like e.g. my iBeacon Tracker, in case there is no effect,
- 3. I will start cleaning up the Entities list and reduce it significantly. 

In case all the above will not work, i will set up the HA Cloud trial - thanks for your help so far!!!

**Comment by uTZFu** [comment]
Hey Bruno, 

I can confirm, the issues was within the the entities. I remioved the BLE Device Tracking from the configuration YAML and could see an imidiate effect. After various restarts HA also cleared the entities list and i am back down to roughly 1.3k - everything now works in the companion app as fast as in the browser again! 

Thanks for your support and resolving this!

**Comment by madz12345** [comment]
I have the same problem. Iphone 14 with the latest version of IOS and applications.
