### ISSUE TITLE
I cannot invoke Assist from the companion app on watchOS 8

### ISSUE THREAD

**Issue by duckida** [home-assistant/iOS#2925]
**iOS device model, version and app version**

Model Name: Apple Watch S3
Software Version: 8.7.1
App version: 2024.7 (730)

**Home Assistant Core Version**

2024.8.1
**Describe the bug**
I don’t see assist icon in the corner of the app on my Apple Watch
**To Reproduce**
Open the app on an Apple Watch Series 3 or watchOS 8
**Expected behavior**
The Assist button shows in the corner of the app.
**Screenshots**

**Additional context**

**Comment by bgoncal** [comment]
Assist for Apple Watch is in beta, currently not compatible with your watch model neither OS (watchOS 9+)

**Comment by duckida** [comment]
Can you keep the app supported for watchOS 8 but restrict Assist to w9 so than I can still control basic actions from my watch?

**Comment by bgoncal** [comment]
watchOS 8 is supported, no plan to get rid of it right now.

**Comment by duckida** [comment]
FYI, I setup my pipeline and it even works perfectly on wOS 8 from the complication!

**Comment by bgoncal** [comment]
> FYI, I setup my pipeline and it even works perfectly on wOS 8 from the complication!

Thanks for reporting! I'm preparing an entry point in the app as well for watchOS 8, it will be just a little bit different than watchOS 10 due to OS constraints, keep an eye on release notes
