### ISSUE TITLE
HA Companion App for iPAD no longer renders a couple of custom cards in HA 2024.8, but Safari does and iPhone does

### ISSUE THREAD

**Issue by tommyjlong** [home-assistant/iOS#2927]
**iOS device model, version and app version**

Model Name: iPAD Air3 or Pro
Software Version: iPadOS 17.5.1
App version: 2024.730

**Home Assistant Core Version**
HA Core 2024.8.2

**Describe the bug**
Starting in HA 2024.8, a couple of custom Lovelace cards no longer render but only when using HA Companion App for iPad.  I downgraded to HA2024.7.4 and things work fine.  Upgraded back to 2024.8 and no longer works.
Using Safari on the same iPad works fine.  
Using HA Companion App ver 2024.730 for iPhone using iOS Version 17.5.1 works fine.
HA Companion App for Android works fine.
Windows Desktop browser Chrome works fine too

As an FYI, the two custom cards are weather-radar-card, platinum-weather-card.

**To Reproduce**

**Expected behavior**

**Screenshots**
Working Screenshot (HA Core 2024.7.4)
![image](https://github.com/user-attachments/assets/dc01a191-4ba5-4194-b897-542522282f00)
Bottom left is the weather-radar-card, the other two at the bottom center and bottom right are two instances of the platinum-weather-cards, one configured, the other not configured.

Non-working Screenshot (HA Core 2024.8.2)
![image](https://github.com/user-attachments/assets/c9186203-f5d1-4b57-abb5-18b84a837b08)

Bottom left is the weather-radar-card,  the other two at the bottom center and bottom right are two instances of the platinum-weather-cards, one configured, the other not configured.
**Additional context**

**Comment by bgoncal** [comment]
Duplicate https://github.com/home-assistant/iOS/issues/2908
