### ISSUE TITLE
High Battery Usage in Background

### ISSUE THREAD

**Issue by robd003** [home-assistant/iOS#2930]
Model Name: iPhone 13 Pro
Software Version: 17.6.1
App version: 2024.7

**Home Assistant Core Version**
2024.8.2

**Describe the bug**
iPhone battery usage plummets due to Home Assistant companion app running for 50+ minutes in the background of every hour.

**To Reproduce**
Install Home Assistant companion app, login to your instance.

I've even tried disabling location access and background refresh. No matter what the iOS app will run like crazy in the background and deplete your phones battery.

**Expected behavior**
The app should not be running ALL OF THE TIME in the background. If anything it should wake up maybe once an hour. (This should be optional and should have a "sleep until user activity" radio switch in Settings)

Similar issues: https://github.com/home-assistant/iOS/issues/2429 https://github.com/home-assistant/iOS/issues/2023

**Comment by bgoncal** [comment]
Duplicate https://github.com/home-assistant/iOS/issues/2429
