### ISSUE TITLE
No more haptic feedback in iOS widgets since update to version 2024.8

### ISSUE THREAD

**Issue by Ruud-St** [home-assistant/iOS#2936]
Model Name: iPhone 12 Pro
Software Version: iOS 17.6.1
App version: 2024.8 (783)

**Home Assistant Core Version**
2024.8.2

**Describe the bug**
Since the latest Home Assistant iOS app update to version 2024.8 (783), the haptic feedback stopped working.
Not sure if you now need to enable it somewhere. I have been searching for days, but I can't find an option for that anywhere.

**To Reproduce**
Just adding Scenes to the Action widgets. I've tried them all (2, 4 and 10)
Same goes for the Open Page widgets.

**Expected behavior**
When pressing a scene or open a page I would like to have the Haptic Feedback.

**Comment by bgoncal** [comment]
Thanks or reporting, I'll fix this week.

**Comment by bgoncal** [comment]
Fixed and available in App Store

**Comment by Ruud-St** [comment]
Thanks! That works as a charm again! :D 

The only thing not working yet is the Haptic feedback for the **Open Page** widgets.

**Comment by Ruud-St** [comment]
True, i wasn't sure anymore if it was there before, that’s why i also mentioned that one 😄 
Thanks for the quick fix!
