### ISSUE TITLE
iOS Lock Screen Widgets

### ISSUE THREAD

**Issue by andy-81** [home-assistant/iOS#2937]
**iOS device model, version and app version**

Model Name: iPhone 14 Pro
Software Version: 17.6.1
App version: 2024.8 (2024.783)

**Home Assistant Core Version**
2024.8.3

**Describe the bug**
I am no longer getting any data showing in my lock screen widgets. I used to have my car’s battery level, range and time to charged showing on my Lock Screen but since updating this has stopped working. 

**To Reproduce**
I have tried pulling in other sensor data into the display without success so it doesn’t appear to be linked to the sensors I am pulling as I am unable to get anything to pull through. 
I have tried to delete the app and reinstall the companion app however this doesn’t appear to have resolved the issue. 

**Expected behavior**
Sensor data should show on the Lock Screen, in the screenshot below the sensor data should show on the left under the date and time beside my other two widgets which are being driven from other apps (HomeKit and VW)

**Screenshots**
![IMG_3285](https://github.com/user-attachments/assets/c385c5cd-e77e-44e4-b04b-08c682bc0265)

**Additional context**
The sensor data was showing and below is the code I was using to drive the data, if I use the sensor data in the template tap the data is pulled through in the app and web page (developer tools section)

Range: {{ states('sensor.blue_steel_range') }}

{% if is_state("switch.blue_steel_charger", "on") -%}
  TTC: {{ state_attr('sensor.blue_steel_charging_rate', 'time_left') }}
{%- else -%}
  Battery: {{ states('sensor.blue_steel_battery') }}%
{%- endif %}

 Not sure if it is anything to do with the app update or the core software update as both updated on my phone around the same time. Hoping maybe someone else is having the same issue to help understand where the issue is coming from but couldn’t see anyone else with the issue on here.

**Comment by andy-81** [comment]
I have also tested on my iPad which has the same issue when I try to add the widgets to the Lock Screen.  

![IMG_1832](https://github.com/user-attachments/assets/6154f577-ee12-41af-8503-a8e4df41203a)
![IMG_1833](https://github.com/user-attachments/assets/e7e4f8a1-2696-4c1f-815c-5e0b928c03ad)
![IMG_1834](https://github.com/user-attachments/assets/9a9240b1-158a-4b16-a81d-297b491cb097)

if that helps at all.

**Comment by bgoncal** [comment]
Please submit your logs: https://docs.google.com/forms/d/1lx0hKiN8D-YDTmMKybVeiBlrj4S4s1hczLrgNXTZsW8/edit

**Comment by bgoncal** [comment]
Please submit your logs: https://forms.gle/LiUvogFgTMLi1f4F9

**Comment by andy-81** [comment]
> Please submit your logs: https://forms.gle/LiUvogFgTMLi1f4F9

Is there any specific logs you want. I can see a home assistant pushover log, is it just that or do you want the analytics logs?

**Comment by bgoncal** [comment]
Companion App settings >> debugging >> export logs

**Comment by andy-81** [comment]
> > Please submit your logs: https://forms.gle/LiUvogFgTMLi1f4F9
> 
> Is there any specific logs you want. I can see a home assistant pushover log, is it just that or do you want the analytics logs?

Never mind I realised you probably meant the logs in the companion app. I have uploaded them now and shared the folder. If you need any other logs let me know and I will add to the folder. 

Equally, if you want me to do any tests and then upload the logs happy to do that too. 

I did try rebooting the phone and deleting and reinstalling the app but neither worked successfully.

**Comment by andy-81** [comment]
> I see in your logs when the widget tried to reload it used your remote URL from home assistant cloud and the result was `"The internet connection appears to be offline."`, So it used the placeholder to render the widget.
> 
> Are you on your local network now? Can you try going to Companion app settings >> widgets >> reload widgets and wait a few minutes then submit logs again?

I am now so will try again. 

If it helps I was able to access the dashboards and app when I pulled the logs (with refreshing the data).

Will upload the latest log to the same folder if you're ok with that, if not let me know and I will complete the form again.

**Comment by andy-81** [comment]
All uploaded now. It is showing in HA that I am on the internal address. 

The external address in the app from memory is a nabu one.

**Comment by bgoncal** [comment]
Ok, perhaps this is related to something i fixed this morning https://github.com/home-assistant/iOS/pull/2942 (not available yet though), you are using the widget without any action set for when you tap right ?

**Comment by andy-81** [comment]
Correct, I'm planning to add actions but right now I have none set. 

If I set an action is that likely to fix it in the short term? Or will that break it more? lol

**Comment by bgoncal** [comment]
It will possibly fix it short term, but it may take a few minutes to show up after you set

**Comment by andy-81** [comment]
I'll give it a go now and confirm so you can validate if it is linked.

**Comment by andy-81** [comment]
It does appear to be linked,

I set an action on it and within a minute it had the details back on. So it looks like you are correct. 😄

**Comment by bgoncal** [comment]
Fixed and available in App Store
