### ISSUE TITLE
Interuttore per tapparella Tuya risulta invertito  

### ISSUE THREAD

**Issue by MorenoComi8** [home-assistant/iOS#2955]
Buongiorno per quanto riguarda il vostro portale riguardo app. Tuya l'interuttore  per le tapparelle risulta invertito. Per cui risulta tapparella chiusa ed invece è aperta ed anche la percentuale non corretta, e viceversa. 

  
![immagine1](https://github.com/user-attachments/assets/4a00e7eb-a942-49b9-886a-c7d087a1a6f2)
![Immagine 2](https://github.com/user-attachments/assets/6cc2889d-9274-4188-a9fe-386794fdab53)

Cordiali Saluti
Comiotto Moreno

**Comment by bgoncal** [comment]
Hey, please ask this question in "core", this is unrelated to the mobile app.
