### ISSUE TITLE
In-app Notification Editor doesn't appear to save category/action names

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/iOS#296]
Noticed something just now when playing with the in-app notification editor.

1. Make a notification category with actions
2. Save it
3. Click on the newly created category name
4. The category Name/Identifier at the top will appear blank, and the Action buttons at the bottom will appear to have been deleted / not saved. Instead of seeing the actions you created you'll just see the "Add" button as if you never added an action at all..

See here for video demonstrating issue (skip to the final 10-15 seconds or so (1:24 mark is where i save it): https://streamable.com/1559e 

**However...**  olbjan tested this as well and reproduced the issue on his device, but discovered that it _does actually save_ if you visit the main settings window. I have confirmed this as well.

**Comment by olbjan** [comment]
What would be best would be that returning from creating a new category reloads the notification settings screen.

**Comment by zacwest** [comment]
Fixed by #603
