### ISSUE TITLE
Did not receive auth message within 10 seconds

### ISSUE THREAD

**Issue by herebcs** [home-assistant/iOS#2969]
**iOS device model, version and app version**
Model Name: iPhone 13 Pro Max
Software Version:  iOS 17.6.1
App version: 2024.8.1

**Home Assistant Core Version**
2024.8.3

**Describe the bug**
Although it improved a lot since the last version was released, it still occasionally happens that the app cannot connect for several seconds (typically more than 10) when bringing it to the foreground or launching it via a CarPlay action despite of perfect network conditions.

The relevant log entry:
2024-09-02 14:33:19.771 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection] [547139546288] from 94.44.119.73 (Home Assistant/2024.8.1 (io.robbie.HomeAssistant; build:2024.791; iOS 17.6.1)): Disconnected: Did not receive auth message within 10 seconds

I’m connecting through SSL/nginx via an external URL. Most of the time the setup works perfectly.

**To Reproduce**
Launch the app by pressing a button on CarPlay or simply from the phone after several hours of inactivity.

**Expected behavior**
The app should connect in a reasonable time (few secs).

**Comment by herebcs** [comment]
After switching to a cloudflared tunnel, the issue is gone.

**Comment by yafengwy** [comment]
> After switching to a cloudflared tunnel, the issue is gone.

Hi i have the exact same error and my HA kept disconnecting on my busiest dashboard (works fine on other page like settings, developer tools etc.). Do you mean Nabu Casa is the reason causing this issue and switching to a different cloud service will fix the issue?
