### ISSUE TITLE
iPhone 14 getting hot when using HA iOS App.

### ISSUE THREAD

**Issue by Fatalmose** [home-assistant/iOS#2990]
**iOS device model, version and app version**

Model Name: iPhone 14 Apple
Software Version: iOS  17.6.1
App version: 13.1

**Home Assistant Core Version**
< 2024.9.1 -->

**Describe the bug**

When programming into HA dashboards using the iOS application , my iPhone is getting real slow and the battery is heating up.

**To Reproduce**

I close down the HA application and wait for a while.
The temperature of my iPhone becomes normal again.
 I restart the HA iOS application , go into my dashboards and start working and after a few seconds my iPhone becomes slow again , with battery heating up.
I close down the HA App , again and everything becomes normal again after a few minutes.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by bgoncal** [comment]
How does it behave in iOS Safari?

**Comment by Fatalmose** [comment]
Thx for the reply.
Not quite sure I understand your question…
I only use the HA application on my iPhone.
What do you mean by iOS Safari in this context.

**Comment by bgoncal** [comment]
I mean opening your home assistant through iOS Safari browser and using it, if it also gets warm then the issue is on frontend, not app specific.

**Comment by Fatalmose** [comment]
Ok…
I’l check this out…
Will keep you informed.

**Comment by Fatalmose** [comment]
Just tried using http://homeassistant.local:8123
But that doesn’t work.
Do you know another way…?
Thx.

Regards.

JS.

**Comment by Fatalmose** [comment]
Ok…
Got it…
Will keep you updated…
Thx for the reply…

**Comment by Fatalmose** [comment]
Hello.

Using iOS Safari…

As slow as on the HA Application.
iPhone warming up.
Not as much as using the iOS HA Application but…warming up…
You where right…
It’s not the HA iOS Application having a problem.
What is your opinion concerning this…?

Regards.

JS

**Comment by bgoncal** [comment]
Please report the issue in frontend repo to get help:
https://github.com/home-assistant/frontend/issues/new/choose
