### ISSUE TITLE
Thread configuration: floating button hides static buttons

### ISSUE THREAD

**Issue by pethans** [home-assistant/iOS#2994]
**iOS device model, version and app version**
Model Name: iPhone 13 mini
Software Version: 17.6.1
App version: 2024.8.1 (2024.791)

**Home Assistant Core Version**
2024.8.3

**Describe the bug**
Thread network configuration settings has a float-over button "Send Credentials to Home Assistant" that covers and makes static UI elements inaccessible. For example, button "Send credentials to phone" can be invisible unless band-scrolling (tap-and-drag), but it still cannot be clicked without releasing the scroll-drag. The hidden button is only accessible if the phone is rotated to landscape. 

Incidentally, a UX issue with this button is that, where there are two or more Thread networks, the button is ambiguous about which credentials are being sent to HA. Are all credentials on the phone being sent? Even the ones HA already sent to the phone? Or just credentials for the Apple network? Do I (or should I) have a choice?

A secondary bug, or UI issue, with the same button is that it always appears, even when HA has already received the credentials. It wouldn't be an issue if the button disappeared once the credentials were sent, but it never disappears. 

**To Reproduce**
In Devices and Services, tap Thread, then tap CONFIGURE and scroll to bottom. 

**Expected behavior**
Buttons should not be covered and inaccessible by floating UI elements. 

I feel the expected behavior would be eliminate the floating button and have a blue-text link-button immediately below the Apple network to "Send credentials to Home Assistant", similar to the blue-text link-buttons below the OpenThread network. This would remove the ambiguity of which credentials are being sent, as well as eliminate the float-over button covering UI elements.

**Screenshots**

In the first (portrait) screenshot, the text/button "Send credentials to phone" are hidden by the blue floating button. In the second (landscape) screenshot, the buttons are visible.

![portrait](https://github.com/user-attachments/assets/0b265834-0adf-4b4a-8a80-0585c207f10b)
![landscape](https://github.com/user-attachments/assets/e7b57836-2b81-4b6a-a017-423611d52791)

**Additional context**
<!--Add any other context about the problem here.—>

**Comment by bgoncal** [comment]
Thanks for the feedback, about the button display issue, please report to frontend repo since the app has no control of that.

About the rest, thanks for the suggestion, I'll follow up on that but this screen will change at some point anyways.

**Comment by pethans** [comment]
> Thanks for the feedback, about the button display issue, please report to frontend repo since the app has no control of that.

Only reported here because the referenced floating button is specific to the iOS app, it does not appear in the web interface.  

Thanks for looking into it, hopefully nobody else is confused trying to find the hidden buttons.
