### ISSUE TITLE
iPhone Watch (Apple Watch) Battery Status Issue

### ISSUE THREAD

**Issue by AngeloAna** [home-assistant/iOS#3000]
I originally reported this issue in HA Core. Here are the details: [https://github.com/home-assistant/core/issues/125999#issuecomment-2351707723]

The watch battery percentage is no longer updating in HA. It looks like there is an IOS app or watch app issue. Please see the above referenced report for details. I can reenter the information here if required.

**Comment by bgoncal** [comment]
Looking at your screenshot you just have updated the iOS app version to 2024.9, correct? 

Open the watch app and iOS app at the same and check if the battery sensor updates.

Also check if other iPhone sensors update or not.

Some considerations:
- Battery is not realtime updated
- If you have a home assistant complication in your watch face, the battery will update more often
- Only 1 paired watch is supported to report battery level

**Comment by AngeloAna** [comment]
It looks like the watch battery percentage is now updating after I updated the IOS phone app to 2024.9. It took a while. The only remaining issue is the watch app. I am still seeing the following:
![image](https://github.com/user-attachments/assets/69011f1d-43ab-4767-b001-f3032c363686)

**Comment by bgoncal** [comment]
That's correct, we will release a blog post on Monday, there is now a configuration screen for Apple Watch inside the iOS App, companion app settings >> Apple Watch configuration.

Go check it out and choose what you want to display on your watch

**Comment by AngeloAna** [comment]
I was able to add 2 scripts and they display on the watch now. Thank you for the quick response.
