### ISSUE TITLE
Scenes from control center not being activated

### ISSUE THREAD

**Issue by andersdreyer** [home-assistant/iOS#3005]
**iOS device model, version and app version**

Model Name: iPhone 15 pro
Software Version: iOS 18
App version: 2024.9.2

**Home Assistant Core Version**

Core 2024.9.2
Supervisor 2024.09.1
Operating System 13.1

**Describe the bug**
Added 2 HA scenes to control center. Activating the buttons does not work. The log shows "Called service: scene.turn_on" with this payload:
{
  "entity_id" : "2cd6808431db49878c66a22327e78243-scene.godnat"
}

I have a scene named "godnat".

**To Reproduce**
Add scene to control center. Tap new scene button. 

**Expected behavior**
Scene is activated

**Screenshots**

**Additional context**

**Comment by bgoncal** [comment]
Thanks for your report, I already identified the issue, fix coming.
