### ISSUE TITLE
iOS 18 Action Widget not compatible with tinted icons

### ISSUE THREAD

**Issue by TomBrien** [home-assistant/iOS#3006]
**iOS device model, version and app version**

Model Name: iPhone 14 Pro
Software Version: iOS 18
App version: 2024.848

**Home Assistant Core Version**

**Describe the bug**
With iOS 18 set to use tinted icons, the actions widget shows as a block colour. Suspect this is true for other sideways but not tested

**To Reproduce**
Set icon tint 

**Expected behavior**

**Screenshots**

Dark icons:
![image](https://github.com/user-attachments/assets/3972f370-a395-4295-a712-55972572e1b0)

Tinted icons
![image](https://github.com/user-attachments/assets/68a3b3a0-27a3-4d1a-b76b-15936af4489f)
**Additional context**

**Comment by bgoncal** [comment]
Good catch, fix coming

**Comment by bgoncal** [comment]
I just noticed "open page" widget still has a very white background while tinted, I'll fix that next week

**Comment by northcity** [comment]
请问一下怎么修复呢？我在iOS18下也遇到了Widget在Tint下显示空白的问题？
