### ISSUE TITLE
Scene name is not shown due to colour on watch

### ISSUE THREAD

**Issue by m1dst** [home-assistant/iOS#3016]
**iOS device model, version and app version**

Model Name: M00D3B/A (watch)
Software Version: 10.6.1 & 11.0
App version: 2024.9

**Home Assistant Core Version**
2024.9.2

**Describe the bug**
When showing scenes on the watch, they only show the icon.  The text colour is white and the background is white.  If you allow the watch to sleep, the background goes grey and you can then see the text.   I see no way to customise the colour of the background or the text.  Only the icon colour can be changed.

**To Reproduce**
Add scenes to your watch.

**Expected behavior**
I expect to be able to see the text at all times.  The colour of the text should be inverted when the foreground is white.

**Screenshots**
![incoming-719CD700-21BC-4397-BBE2-C6E9AE22980F](https://github.com/user-attachments/assets/3658cd9e-6af9-4969-a920-a5f39edaa5af)
![incoming-94038D24-F769-4B15-8A49-8F84EA68FE91](https://github.com/user-attachments/assets/3b612946-6c67-421d-bc6c-cc4d22b41cff)

**Additional context**

**Comment by bgoncal** [comment]
Fix coming on 2024.9.2 related to be able to set the text color, but no logic will be added to check for the background color and update the text color, colors are static, it's up to the user to decide to customize or use the default colors (which always show correctly)

**Comment by m1dst** [comment]
When you suggest that default colours will always work correctly, do you
mean after the fix, or should default be working now?  I am unaware I have
changed the colours of scenes as I can’t find anywhere to change the
background colour.

**Comment by bgoncal** [comment]
Default colors should work right away, they are:
- Dark gray background
- White text
- Blue icon

Can you send me a screen recording of your configuration? Show me each item configuration screen.

**Comment by bgoncal** [comment]
Example
https://github.com/user-attachments/assets/46e8ca86-6ee1-4689-bff5-701587ede3f5

**Comment by m1dst** [comment]
Thanks Bruno - I deleted the scenes and recreated them.  I can now see the text.  I can also now change the "use custom colors", switch, which I think was disabled previously.   Perhaps I had an old schema or something.  Not sure, but glad it is working now.
