### ISSUE TITLE
Ipad dashboard not showing

### ISSUE THREAD

**Issue by Dickslinger** [home-assistant/iOS#3022]
On my ipad A1822  with the latest ios (17.5 ) and HA (2024.9.0) will not load the standard dashboard anymore. The older (2024.8.4) is working fine.On my laptop and cellphone it works fine. Both are fully updated. 
![inbound1894039031826634463](https://github.com/user-attachments/assets/0eda9614-7435-485f-9d69-0e2091497a4e)

**Comment by bgoncal** [comment]
Please reopen your issue providing all information requested in the issue form.

Also there is an update for Core and iOS App available.
