### ISSUE TITLE
Ipad dashboard not showing

### ISSUE THREAD

**Issue by Dickslinger** [home-assistant/iOS#3023]
Issue also exist in safari

**iOS device model, version and app version**

Model Name: Ipad  ( A1822 )
Software Version:  ( 17.5 )
App version:  Core  ( 2024.9.2 )
Supervisor  ( 2024.09.1 )
Operating System ( 13.1 )

**Describe the bug**
On my ipad A1822 with the latest ios (17.5 ) and HA (2024.9.2) will not load the standard dashboard anymore. The older (2024.8.4) is working fine. On my laptop and cellphone it works fine. Both are fully updated.

**Screenshots**
![WhatsApp Image 2024-09-18 at 10 25 28](https://github.com/user-attachments/assets/3067c330-516f-44ad-8d91-dfe75ec1780d)

**Comment by bgoncal** [comment]
If you pull down to refresh or kill the app and reopen, do you see any sign of part of it working? 

If you swipe from left to right to open the sidebar, does it works?

**Comment by bgoncal** [comment]
If you swipe with 3 fingers up, then tap the setting gear, then tapping on your server name, can you send me a screenshot?

**Comment by Dickslinger** [comment]
> If you swipe with 3 fingers up, then tap the setting gear, then tapping on your server name, can you send me a screenshot?



> If you swipe with 3 fingers up, then tap the setting gear, then tapping on your server name, can you send me a screenshot?

![20240918_142533](https://github.com/user-attachments/assets/aa9f674c-7f4b-4336-8839-6ce6b1c32bb4)

**Comment by Dickslinger** [comment]
This is 2024.8.3 with this it works but starting with 2024.9.0 nothing works only black screen.

This email message is
intended only for the addressee(s) and contains information that may be
confidential to and/or copyrighted by M.Wijmans Jr. If you are not the intended recipient, please notify the sender by reply email and immediately delete this email.
Use, disclosure or reproduction of this email by anyone other than the intended recipient(s) is strictly prohibited. Any
views expressed in the email are those of the individual sender unless
the sender expressly states them to be the views of someone else. No representation is made that this email or any attachments are free of viruses. Virus scanning is recommended and is the responsibility of the recipient.
Dit
e-mailbericht is alleen bedoeld voor de geadresseerde (n) en bevat
informatie die mogelijk vertrouwelijk is en / of auteursrechtelijk
beschermd is door M.Wijmans Jr.
Als u niet de beoogde
ontvanger bent, stelt u de afzender hiervan op de hoogte via een
antwoord-e-mail en verwijdert u deze e-mail onmiddellijk.
Gebruik,
openbaarmaking of reproductie van deze e-mail door iemand anders dan de
beoogde ontvanger (s) is ten strengste verboden.
Alle
standpunten in de e-mail zijn die van de individuele afzender, tenzij
de afzender uitdrukkelijk aangeeft dat het de mening van iemand anders
is.
Er wordt niet beweerd dat deze e-mail of bijlagen vrij zijn van virussen.
Virusscanning wordt aanbevolen en is de verantwoordelijkheid van de ontvanger.

Verzonden met Proton Mail Android

-------- Oorspronkelijk bericht --------
Op 18-09-2024 14:38, schreef Bruno Pantaleão Gonçalves :

**Comment by bgoncal** [comment]
Ok, but I need the screenshot from the 2024.9.0 app version (btw there is a 2024.9.1 now available) showing the same thing, can you swipe up with 3 fingers and follow the procedure I shared before?

**Comment by Dickslinger** [comment]
Oke I wil installeren it I send you a screenshot later

This email message is
intended only for the addressee(s) and contains information that may be
confidential to and/or copyrighted by M.Wijmans Jr. If you are not the intended recipient, please notify the sender by reply email and immediately delete this email.
Use, disclosure or reproduction of this email by anyone other than the intended recipient(s) is strictly prohibited. Any
views expressed in the email are those of the individual sender unless
the sender expressly states them to be the views of someone else. No representation is made that this email or any attachments are free of viruses. Virus scanning is recommended and is the responsibility of the recipient.
Dit
e-mailbericht is alleen bedoeld voor de geadresseerde (n) en bevat
informatie die mogelijk vertrouwelijk is en / of auteursrechtelijk
beschermd is door M.Wijmans Jr.
Als u niet de beoogde
ontvanger bent, stelt u de afzender hiervan op de hoogte via een
antwoord-e-mail en verwijdert u deze e-mail onmiddellijk.
Gebruik,
openbaarmaking of reproductie van deze e-mail door iemand anders dan de
beoogde ontvanger (s) is ten strengste verboden.
Alle
standpunten in de e-mail zijn die van de individuele afzender, tenzij
de afzender uitdrukkelijk aangeeft dat het de mening van iemand anders
is.
Er wordt niet beweerd dat deze e-mail of bijlagen vrij zijn van virussen.
Virusscanning wordt aanbevolen en is de verantwoordelijkheid van de ontvanger.

Verzonden met Proton Mail Android

-------- Oorspronkelijk bericht --------
Op 18-09-2024 14:49, schreef Bruno Pantaleão Gonçalves :

**Comment by Dickslinger** [comment]
> Ok, but I need the screenshot from the 2024.9.0 app version (btw there is a 2024.9.1 now available) showing the same thing, can you swipe up with 3 fingers and follow the procedure I shared before?

thnx but 2024.9.0 Not Working on Ipad , 2024.9.1 Not Working on Ipad , 2024.9.2 Working on Ipad :>)

**Comment by bgoncal** [comment]
The 2024.9.2 is the testflight App version (beta), is this what you mean? Please don't mix up with Core version.

Does it work now or did I missunderstand?

**Comment by Dickslinger** [comment]
Yess it works with the 2024.9.2

This email message is
intended only for the addressee(s) and contains information that may be
confidential to and/or copyrighted by M.Wijmans Jr. If you are not the intended recipient, please notify the sender by reply email and immediately delete this email.
Use, disclosure or reproduction of this email by anyone other than the intended recipient(s) is strictly prohibited. Any
views expressed in the email are those of the individual sender unless
the sender expressly states them to be the views of someone else. No representation is made that this email or any attachments are free of viruses. Virus scanning is recommended and is the responsibility of the recipient.
Dit
e-mailbericht is alleen bedoeld voor de geadresseerde (n) en bevat
informatie die mogelijk vertrouwelijk is en / of auteursrechtelijk
beschermd is door M.Wijmans Jr.
Als u niet de beoogde
ontvanger bent, stelt u de afzender hiervan op de hoogte via een
antwoord-e-mail en verwijdert u deze e-mail onmiddellijk.
Gebruik,
openbaarmaking of reproductie van deze e-mail door iemand anders dan de
beoogde ontvanger (s) is ten strengste verboden.
Alle
standpunten in de e-mail zijn die van de individuele afzender, tenzij
de afzender uitdrukkelijk aangeeft dat het de mening van iemand anders
is.
Er wordt niet beweerd dat deze e-mail of bijlagen vrij zijn van virussen.
Virusscanning wordt aanbevolen en is de verantwoordelijkheid van de ontvanger.

Verzonden met Proton Mail Android

-------- Oorspronkelijk bericht --------
Op 18-09-2024 15:42, schreef Bruno Pantaleão Gonçalves :

**Comment by Dickslinger** [comment]
> The 2024.9.2 is the testflight App version (beta), is this what you mean? Please don't mix up with Core version.
> 
> Does it work now or did I missunderstand?

Yess it works
![20240918_154454](https://github.com/user-attachments/assets/e6efb28e-1396-4078-a1b1-a32f6dd79be1)
