### ISSUE TITLE
Scene actions have wrong icons in new Apple Watch Configuration

### ISSUE THREAD

**Issue by ErikvO** [home-assistant/iOS#3031]
**iOS device model, version and app version**
Model Name: iPhone 14 Pro Max
Software Version: 18.0
App version: 2024.9.1 (2024)

**Home Assistant Core Version**
2024.9.2

**Describe the bug**
The scene actions on the Apple Watch get the default "palette" icon, instead of the icon that is configured in Home Assistant. It cannot be changed in the Apple Watch configuration section.

**To Reproduce**
- In Home Assistant, have at least 1 scene configured with a non-default icon.
- In the iOS Home Assistant app, open "Settings".
- Tap "Companion app".
- Tap "Configuration" under "APPLE WATCH".
- In the "Items" section, tap "Add item".
- Tap the "Scenes" tab.
- Tap the scene with the non-default icon.
- See that the Icon name is set to "palette" instead of the configured icon.
- Also note that the icon cannot be changed.
- Tap Add
- Tap Save
- On the Apple Watch open the list of Scenes
- Tap the refresh button (top left)
- See that the scene is now show but with the wrong icon

**Expected behavior**
The scene should have the same icon as configured in Home Assistant.
It would be a bonus if it could be overridden in the Watch settings.

**Screenshots**
![image](https://github.com/user-attachments/assets/9e7ebcab-2703-42ae-a877-413b9477f924)

![image](https://github.com/user-attachments/assets/ed636702-84a0-4402-a0a5-1af783fb8c18)

![image](https://github.com/user-attachments/assets/0918d98f-7403-4f6e-9cd7-810f7693f9bf)

**Comment by deanchin** [comment]
I’m experiencing the same issue

**Comment by bgoncal** [comment]
Fix coming in app v2024.9.2

**Comment by ntompson** [comment]
I'm at v2024.9.4, but I am seeing an issue like this. In the Apple Watch configuration page on the iPhone companion app, icons set against the scene render correctly, but on my watch, everything shows up with a script icon. I've tried restarting HA on both phone and watch, and pressed the refresh button on the watch.

![IMG_6591](https://github.com/user-attachments/assets/2460f8ac-b18a-4f06-9a8f-bf8a5ccba4b7)

![incoming-17A9C597-AE97-4C12-9769-2E6F1D9CAACC](https://github.com/user-attachments/assets/c54307d4-7730-4c8b-b1ff-5a99bd5b41b8)

**Comment by jledoux** [comment]
> I'm at v2024.9.4, but I am seeing an issue like this. In the Apple Watch configuration page on the iPhone companion app, icons set against the scene render correctly, but on my watch, everything shows up with a script icon. I've tried restarting HA on both phone and watch, and pressed the refresh button on the watch.

I had the same issue with Scenes not having the proper icon (all being script).  I'm able to fix it when I add the Scene via "Actions", but then I can't configure the Action (to disable the "Require confirmation" which is important to me; I don't like the extra key presses).

To reproduce the issue, start with a fresh configuration:

First, go into HA mobile App -> Settings -> Companion App.  Select actions, and make sure all the scene actions are turned off (do this by toggling, select all, until all are unselected).
Then go into back to  Companion App settings, select "Configuration" (in Apple Watch section) and press Reset Configuration (and Ok the reset).

Then go to Add Item, select a scene (I'm going "Lock Front Door" with an icon mdi:lock).  Press add. 
<img src="https://github.com/user-attachments/assets/d2ccd8db-bb3b-4bf9-ab63-b06178394cd5" width="200">

Within companion app it looks correct, so press save:
<img src="https://github.com/user-attachments/assets/d4154d4d-0307-4ea3-9754-ab69ee74f64a" width="200">

On the apple watch, reset the configuration by pressing the reload button in upper right and it now has the script icon:

<img src="https://github.com/user-attachments/assets/d5f9fba5-7e04-455e-9547-239476a0f5f5" width="100">

To fix the icon, you can go to Actions, toggle on the "Scene Actions" you want enabled, and then when you back to Apple Watch "Configuration" page and reset the Configuration, you'll see the scene action there (with the correct icon) and when you sync it over to the watch the correct icon will be there.  

However, this method doesn't let you edit the item before adding it, so you can't disable say the Confirmation icon.

**Comment by ntompson** [comment]
Hey, thanks for the suggestion. When I navigate to actions there's a big red box saying that iOS actions are going away and I should use the scripts or scenes tab instead. It doesn't actually let me add anything in the iOS actions tab.

**Comment by jledoux** [comment]
I think you misunderstood me.  To get the icons working, go to Settings inside mobile app and select Companion App:
<img src="https://github.com/user-attachments/assets/1306cf92-9e73-4cee-ace9-73b934ba2992" width="200">
Then select "Actions" on the next page to enable/disable Scene Actions.
<img src="https://github.com/user-attachments/assets/5d939307-481d-4ac5-a0ac-fb41166897ab" width="200">

Then when you go back to Settings -> Companion App -> Configuration -> Reset Configuration and then (Save), and then reload on apple watch, the icons should be working on the Scene Actions you had enabled previously.

(You seemingly did Settings -> Companion App -> (Under Apple Watch) Configuration -> Add Item and select iOS Actions to get to page about "We will stop supporting iOS Actions").

**Comment by ntompson** [comment]
You're quite right - I did misunderstand. Before I hit the reset button - will I lose my complications config? I've invested quite a bit of time in getting those right - I'd hate to have to start from scratch again.

**Comment by ronaldheft** [comment]
Also seeing the script icons for my manually configured scenes, with the correct icon displayed in the app preview.

**Comment by bgoncal** [comment]
It's fixed on the testflight version, It will still take a while until it is release to App Store, so feel free to test there and provide feedback.

**Comment by bgoncal** [comment]
@red-avtovo it is in the App Store for a while already, please open a new issue and share your setup so I can help you

**Comment by ErikvO** [comment]
I did not realize it was released either as it never started working for me. For me the issue is still as explained in https://github.com/home-assistant/iOS/issues/3031#issuecomment-2401582957
(Scene icons still all look like a script icon)
