### ISSUE TITLE
Apple Watch Battery Percentage and Status Not Updating in Background

### ISSUE THREAD

**Issue by markimarc** [home-assistant/iOS#3033]
**iOS device model, version and app version**

Phone:
Model Name: iPhone 13 Pro Max
Software Version: 18.0
App version: 2024.9.1 (2024)

Watch:
Model Name: Apple Watch Series 5
Software Version: 10.6.1
App version: 2024.9.1

**Home Assistant Core Version**
2024.9.1

**Describe the bug**
The battery percentage and status of my Apple Watch are not updating in the background while the Home Assistant companion app is running. Both the iPhone and Apple Watch apps are visible in the app drawers, indicating they are active in the background. However, while my iPhone’s information is updating as expected, the Apple Watch’s battery status remains unchanged, even after days. When I manually open the Apple Watch app, the data updates correctly.
It doesn't matter if I'm connected via Internal or External URL.

**To Reproduce**
- Ensure the Home Assistant companion app is running in the background on both the iPhone and Apple Watch.
- Wait for any battery percentage change or put the watch on a charger.
- Observe that the battery percentage or charging status on the watch is not updated in Home Assistant until manually opened.

**Expected behavior**
The Apple Watch’s battery percentage and status should be updated in the background, just like the iPhone companion app.

**Screenshots**
![IMG_3284](https://github.com/user-attachments/assets/8193ca08-f9ae-4930-b8ed-d67aab7a484d)
![IMG_3279](https://github.com/user-attachments/assets/b87a39b5-7e75-4eff-beed-29d511f5dde1)

**Additional context**
The problem was also present in the latest iOS 17.

**Comment by bgoncal** [comment]
To start debugging this, can you add one home assistant complication to your watch face? When you have a complication there the frequency it reports the sensor should be higher

**Comment by fay000fay** [comment]
> To start debugging this, can you add one home assistant complication to your watch face? When you have a complication there the frequency it reports the sensor should be higher

this method solved my problem.

**Comment by bgoncal** [comment]
For now this is a limitation form this functionality, I will add this to the docs
