### ISSUE TITLE
Apple Watch Actions stuck with white text on white background

### ISSUE THREAD

**Issue by makerwolf1** [home-assistant/iOS#3035]
Model Name:  both Apple Watch Series 6 and 10 connected via iPhone 13 Pro Max. 
Software Version: 2024.9.1
App version: 2024.9.1

**Home Assistant Core Version**
2024.9.1

**Describe the bug**
Since it seems 2024.9.1 my actions are only loaded with white text on a white background. The actions are server side configured via yaml and contain colors (white background and black text).  It seems those configurations are ignored, and it also happenes with scenes that are added via the companion app. 

**To Reproduce**

**Expected behavior**

**Screenshots**
![incoming-707933D3-DC19-461E-AA66-2D7AABDD4E3F](https://github.com/user-attachments/assets/6eb1876d-277c-4927-99e7-7cc643904140)

**Comment by bgoncal** [comment]
Fix for text color will come in 2024.9.2, for now the workaround is to use another color for your background

**Comment by maciii** [comment]
> Fix for text color will come in 2024.9.2, for now the workaround is to use another color for your background

I have same issue (same server side config) - still white text also on 2024.9.2 - backgroud color is OK.

**Comment by bgoncal** [comment]
@maciii are you running the beta? It’s the iOS beta v2024.9.2

**Comment by boom235** [comment]
> Fix for text color will come in 2024.9.2, for now the workaround is to use another color for your background

I do not really see how I as a user can change that background color. But maybe I will just wait for 2024.9.2.

**Comment by bgoncal** [comment]
@boom235 2024.9.2 is now available on App Store

**Comment by boom235** [comment]
> @boom235 2024.9.2 is now available on App Store

AND it works! BIG THX for this quick fix!

**Comment by makerwolf1** [comment]
Thank you Bruno for the fast response and the quick fix! Issue is solved and closed 🤗
