### ISSUE TITLE
App logs you off when you receive a push notification and cannot connect to HA instance.

### ISSUE THREAD

**Issue by leacho73** [home-assistant/iOS#3036]
**iOS device model, version and app version**

Model Name: iPhone 15 Pro Max (but same behavior on 13&14)
Software Version: 18
App version: 2024.9.1

**Home Assistant Core Version**
2024.9.2
**Describe the bug**
I have a public address for my HA instance, which is secured by Cloudflare, because of this I use an always on VPN on my phone, which allows me to access home assistant as if I was at home - this works fine, until there is a drop in the VPN and I receive a push notification with an image attached, which then generates a 404 error. When the VPN reconnects, I open the Home Assistant app, and its lost all the server information, and I have to set up as default again - this causes Home Assistant to add another phone under the companion app integration, thus breaking all my tracking beacons, as my entities have a _1,_2 or _x appended to the phone entity.
**To Reproduce**
Connect to home assistant, log in to app, and control home assistant natively. You then need to create a scenario where you are blocked from accessing home assistant, such as using Cloudflare zero trust. When you are 'blocked' from accessing your instance, send a push notification with an image attached, you will see the 404 error. Remove the 'block' and open the app again, and it will ask you to set up from scratch again.
**Expected behavior**
When unable to connect to my Home Assistant instance it should not loose the login credentials or session data and should automatically reconnect when the connection is re-established.
**Screenshots**

N/A
**Additional context**
I use Cloudflare zero trust, so I'm not sure if that is messing with the traffic to the app - but either way, I thought I would raise the bug as I don't think the app should just randomly loose your session data/logon data when it cannot connect to home assistant.

**Comment by bgoncal** [comment]
Thanks for reporting, the app compatible setup is to have an internal and one external URL, neither of them can return unauthorized response, otherwise the app will log you out.

**Comment by leacho73** [comment]
Thanks @bgoncal - is there any way around this? Appreciate the security aspect here - just wondering if a setting can be added to turn it off. As I don't particularly want to expose my HA instance to the internet if I can help it.

**Comment by bgoncal** [comment]
Currently there is no configuration like that unfortunately
