### ISSUE TITLE
Weather icons aren’t being displayed on iOS 

### ISSUE THREAD

**Issue by auggy** [home-assistant/iOS#3038]
**iOS device model, version and app version**

Model Name:  15 pro max and 16 pro max 
Software Version:  iOS 18
App version:  2024.9.1 (2024)

**Home Assistant Core Version**
  2024.9.2

**Describe the bug**

weather icons do not appear in weather cards. Tried multiple themes, providers 

**To Reproduce**

Add a weather card 

**Expected behavior**

weather card with weather icons

**Screenshots**

![IMG_0070](https://github.com/user-attachments/assets/f85943d7-5f90-4de8-a963-94089a1624e3)

**Additional context**

they do  display in safari and iPadOS. 

Hopefully I submitted enough info.

**Comment by bgoncal** [comment]
Try resetting frontend cache.
Companion app settings >> debugging >> reset frontend cache
