### ISSUE TITLE
Icon and Background color keep changing back to black

### ISSUE THREAD

**Issue by Tuatop** [home-assistant/iOS#3048]
**iOS device model, version and app version**

Model Name: iPhone 15 Pro
Software Version: iOS 18
App version: 2024.9.2

**Home Assistant Core Version**
2024.9.1

**Describe the bug**
Even update the app to version 2024.9.2, when change Script icon or background color, it always switch back to black instantly. I also found the "Require confirmation" option cannot toggle. It is always keeping on and cannot toggle to off

**To Reproduce**
just change the Script icon or background color to any color and you will see

**Expected behavior**
The icon and background color should respect the color change

**Screenshots**
[View Video](https://drive.google.com/file/d/1mIIcaeN5MCJ_m1ZV8qaMeTaiH8yCa2Po/preview)

**Comment by bgoncal** [comment]
Im on it 👍🏻
