### ISSUE TITLE
When swiping to leave HA app, light slider reacts 

### ISSUE THREAD

**Issue by chrstmnn** [home-assistant/iOS#3058]
**iOS device model, version and app version**
iPhone 13 
iOS 18.0 (22A3354)
2024.9.2 (2024.881)

**Home Assistant Core Version**
2024.9.3

**Describe the bug**
When swiping from bottom to top to leave the HA app, sometimes the light slider card reacts to this and light is turned on. 
The gesture to leave or close the app should not be recorded by the app or lead to any action in the dashboard.   

**To Reproduce**
Place light slider so that it is located in the bottom of the display. Close / leave app. 

**Expected behavior**
App is closed / left without any actions executed. 

**Screenshots**
Issue is only for the recorded card in attachment. 
![IMG_0004](https://github.com/user-attachments/assets/32892118-91bb-4bb5-bf12-5750d92090b6)

 

**Additional context**

**Comment by bgoncal** [comment]
Thanks for your report, this is a possible issue for frontend, app does not control the webpage content, report it to:
https://github.com/home-assistant/frontend/issues/new/choose
