### ISSUE TITLE
Apple Watch Actions not available - iOS App shows GRDB.RecordError error 0

### ISSUE THREAD

**Issue by katb-1** [home-assistant/iOS#3064]
**iOS device model, version and app version**

Model Name:  iPhone 15 Pro
Software Version: iOS 18.0 (22A3354)
App version: 2024.9.3 (2024.894)

Apple Watch Series 10
WatchOS 11.0 (22R349)

**Home Assistant Core Version**
2024.9.3

**Describe the bug**
Pressing the HA icon/widget on my Apple Watch shows a blank screen other than the time in the top right corner. 
Going to Apple Watch --> Configuration in the iOS App shows an error box, which reappears every time I enter that section:

> Failed to save new Watch config, error: The operation couldn't be completed. (GRDB.RecordError error 0.)

I tried uninstalling the app from the watch, rebooting and reinstalling. Error still occurs on iOS app. In the Watch, instead of seeing the actions there's the following message:

> No watch configuration available, open the iOS App and create your configuration under companion app settings.

Pressing reload leads to endlessly spinning wheel with option to Cancel and use cache.

**Screenshots**

![Screenshot 2024-09-28 at 10 14 48](https://github.com/user-attachments/assets/aca02cf7-1f18-4552-80b1-013bc220c197)

![incoming-91DD07F1-1107-4A35-BD74-CB7DDB0ED111](https://github.com/user-attachments/assets/a925b03a-58cd-46b7-b317-cc5c579c59fd)

**Additional context**

Has only occurred with latest companion app version.
 I've rebooted both iPhone and Watch.

**Comment by rhyswaywood** [comment]
I had this too. Going to Settings / Companion App / Apple Watch Configuration / Reset Configuration fixed this error for me. 
However, now all my iOS Actions defined via YAML are requiring confirmation before they will run on the watch.

**Comment by fiservedpi** [comment]
> I had this too. Going to Settings / Companion App / Apple Watch Configuration / Reset Configuration fixed this error for me. 
> However, now all my iOS Actions defined via YAML are requiring confirmation before they will run on the watch. 

Any idea how to permanently grant permission? So don't have to keep hitting yes, like before

**Comment by bgoncal** [comment]
@fiservedpi migrate to use scripts, iOS Actions do not have a way to configure the "require confirmation" option right now.

**Comment by bgoncal** [comment]
Regarding the original issue, if this happens again to anyone could you please export your logs and send to me before resetting the watch configuration? 

You can submit it here:

https://docs.google.com/forms/d/e/1FAIpQLSeAaoHgZvWbR-xj7RtRureX1uq0OH0BfBe1ZIEkH_juhkMpjQ/viewform
