### ISSUE TITLE
"Enter Adress Manually" doesn't work

### ISSUE THREAD

**Issue by Moritz-Schmidt** [home-assistant/iOS#3076]
**iOS device model, version and app version**

Model Name: iPad Air (5th Generation) & iPhone 12 Pro
Software Version: 18.0 (iPad) & 17.6 (iPhone)
App version: 2024.9.3

**Home Assistant Core Version**
2024.10.0 (this should be irrelevant for the Issue)

**Describe the bug**
While setting up the companion app you have to press the "Continue" button multiple times, this is inconvenient but not the main problem.

On the "Scanning for Servers" page nothing happens when pressing the "Enter Address Manually" button.

**To Reproduce**
Open freshly installed Companion App, click on "continue", click on "Enter Adress Manually"

**Expected behavior**
Being able to enter the Adress manually.

**Comment by karlbeecken** [comment]
Can reproduce, have the same issue

**Comment by aleks-mariusz** [comment]
ditto, just installed on ipad and stuck at 'Scanning for servers' and can't hit that button to manually enter address

**Comment by bgoncal** [comment]
I'm on it

**Comment by bgoncal** [comment]
Can one of you share a screen recording? On my iPhone it is working fine, I'll check iPad in a few hours

**Comment by Penait1** [comment]
I can reproduce it on my simulator. It throws the error
`[Error] [main] [OnboardingNavigationViewController.swift:129] show(_:sender:) > unknown sender Optional(<HomeAssistant.OnboardingScanningViewController: 0x108f12610>) wanted us to present: <HomeAssistant.OnboardingManualURLViewController: 0x129808a00>`

I'm not sure why this condition exists near line 129 
`else if sender as? UIViewController == topViewController`

Adding an explicit else caluse for the OnboardingManualURLViewController fixes the issue but I'm not sure thats best practise

**Comment by bgoncal** [comment]
My PR above should handle that, I'll let you know it is available for test

**Comment by rgrae81** [comment]
iPhone 12 mini iOS 17.6 and 17.7 same Problem.
iPhone 14 Pro iOS 17.6 is working fine.

**Comment by bgoncal** [comment]
I just submitted beta with the fix for it to Apple Review, it will come as 2024.9.4

**Comment by aleks-mariusz** [comment]
thanks for the lightning quick turnaround folks! curious how long the take it takes to show up in the app store for us mere mortals these days is?

**Comment by CedricHaidacher** [comment]
I have just installed the update via the App Store, I have now been able to connect my server manually. Thank you very much for the quick patch! :)

**Comment by atobaum** [comment]
I have updated the app and the issue is resolved. Thank you for the quick patch also.

**Comment by aleks-mariusz** [comment]
> thanks for the lightning quick turnaround folks! curious how long the take it takes to show up in the app store for us mere mortals these days is?

answering my own question, now see the update on ipad (i don't have early beta access or anything, i'm just a regular user) - tho i did have to search for the app to see the 'update' button (the list of updatable apps didn't include home-assistant _yet_ ?).  anyway like others, thank you for the lightning quick turnaround time (report-to-fix in under 24 hours.. gotta love this community).
