### ISSUE TITLE
“Cancel and use cache” message hangs after selecting any action

### ISSUE THREAD

**Issue by loopy321** [home-assistant/iOS#3094]
**iOS device model, version and app version**

Model Name: Apple Watch A1977
Software Version: 9.6.3
App version: 2024.9.4

**Home Assistant Core Version**

2024.9.3
**Describe the bug**
I select an action and confirm yes or no and see the following for minutes.  Clicking cancel or cancel and use cache does nothing :
![image](https://github.com/user-attachments/assets/09c9adea-2b5e-4344-8226-e3140e82c9ee)

**To Reproduce**

**Expected behavior**
Simply execute action as before “confirmation” was introduced.
**Screenshots**

**Additional context**

**Comment by bgoncal** [comment]
Please export your logs and send to me: https://forms.gle/Md4xg9inxPoVN5qC9

**Comment by defisit** [comment]
I have upload logs.

Core 2024.10.4
WatchOS 9.6.3

To cancel the Cancel and Update cache screen I have to press the Crown.

**Comment by bgoncal** [comment]
Thanks, some things you can try:
- Download the latest testflight beta;
- Force close the watch app (With the app open on your watch, press and hold power button, then after you see the option to turn off the watch, press and hold the Digital Crown);
- Try to refresh the watch UI with the iOS app also open;

If the above does not fix the issue, please try to resett he watch configuration (there is a button to reset at the bottom of the watch configuration screen)

**Comment by defisit** [comment]
What is fixed for this specific issue in the Testflight beta? Did you notice anything in the provided logs? Thanks

**Comment by bgoncal** [comment]
Nothing relavant in your logs unfortunately, if you don't want to run the testflight app you will need to wait the official release.
The testflight app has some work done related to actions in the watch configuration, which as your logs show, you have several.
Can you also show me a video of how your watch behaves? specially ater force closing as I described in my previous comment.

**Comment by bgoncal** [comment]
Something you can also try is to reinstall your watch app, it happened before that an Apple Watch was stuck with older version of the App

**Comment by defisit** [comment]
For TestFlight, I require an code from the developer? Can you provide that to me?

Some other updates:

1. I have forced closed the App using your procedure but nothing improved after that.
2. reinstalled the app on Watch, no improvements.

Will make a video of my watch as per your requirement, will report back.

**Comment by bgoncal** [comment]
https://testflight.apple.com/join/1AlPbnLZ

**Comment by loopy321** [comment]
Upgrading phones apparently fixed the issue.  Thanks.

**Comment by defisit** [comment]
> https://testflight.apple.com/join/1AlPbnLZ

Installed TestFlight and latest build of the app and the issue is resolved. Thanks.

Also, the confirmation dialog when a Watch action is triggered seems to be removed in this build. I couldn't find a global toggle for that. Was the confirmation dialog purposely removed?

**Comment by bgoncal** [comment]
Correct, legacy iOS Actions don't have the "require confirmation" option at the moment, they were requiring confirmation before but that was a bug, to use confirmation migrate to scripts or scenes for now.
