### ISSUE TITLE
Assist Action Start_Listening Not Working

### ISSUE THREAD

**Issue by jhemak** [home-assistant/iOS#3100]
Model Name: iPhone 12
Software Version: 18.0.1
App version: 2024.9.4 (2024.905)

**Home Assistant Core Version**
2024.10.3

**Describe the bug**
As mentioned at https://github.com/home-assistant/core/issues/120630

When I configure a `tap_action` to initiate Assist, it does not start listening despite having `start_listening: true` defined. I have to tap the microphone in the Assist dialog for listening to begin.  I do not experience this issue when accessing HA via browser on the same device; the problem seems specific to the iOS companion app.

**To Reproduce**
See above

**Expected behavior**
The microphone should start listening automatically.

**Comment by bgoncal** [comment]
Good catch, I'll fix that

**Comment by jhemak** [comment]
Hi @bgoncal - should this be fixed now or is it still pending a release?

**Comment by bgoncal** [comment]
Still pending a release, most probably in the last week of the month, feel free to jump into TestFlight version if you want early access

**Comment by jhemak** [comment]
Hello @bgoncal - I am in no rush but do want to test this once it's been released.  Is there a clue in Github that will tell me when that's happened?  Thanks again for all you do!

**Comment by bgoncal** [comment]
It's currently available on TestFlight and I'm planning a release between this and the next week.
In GitHub you can check for releases, it will be 2024.12
