### ISSUE TITLE
Companion App Notification Text Length Limits?

### ISSUE THREAD

**Issue by loopy321** [home-assistant/iOS#3103]
**iOS device model, version and app version**

iPhone X, ios16, app 2024.9.4

**Home Assistant Core Version**

**Describe the bug**

I am sending a notify.mobile_app_XX notification with my daily agenda to my phone, but it is truncated after a certain number of characters.  

**To Reproduce**

**Expected behavior**

Full message: sent.

**Screenshots**

**Additional context**

**Comment by bgoncal** [comment]
Can you share an example? The latest information I have from Apple is that it limits on 178 characters

**Comment by loopy321** [comment]
Not sure if this helps, but I am running an automation to send my Daily Agenda to my phone using one of the blueprints:
https://gist.github.com/Progaros/63db96fa4d77a662cfbb5b199d0613c1
https://gist.github.com/allenporter/e70d9eb090c7dbdd593cf526e07b4abe
![Screenshot 2024-10-29 191639](https://github.com/user-attachments/assets/6bc646ab-2bc1-401f-b53d-65a949e6967e)

While the following message is received and is truncated (~270 characters):


![IMG_1535](https://github.com/user-attachments/assets/f6b7ad49-f689-495d-9cd5-b82c47a1ec5e)

**Comment by bgoncal** [comment]
That exceeds the limit unfortunately
