### ISSUE TITLE
Companion App Watch Configuration Problem after Core Update

### ISSUE THREAD

**Issue by livetoautomate** [home-assistant/iOS#3109]
**iOS device model, version and app version**

Model Name: iPhone 14 Pro
Software Version: 18.0.1
App version: 2024.9.4
Apple Watch Ultra 2; Software Version 11.0.1

**Home Assistant Core Version**
2024.10.4

**Describe the bug**
Background: I recently upgraded to an Apple Watch Ultra 2.  When I upgraded, I decided to adopt "scripts" for my Watch Configurations; I retired the use of Actions.  This was about a month ago.  All was good for a while, until I upgraded HA Core (not sure of the upgrade rev at the time).  After upgrading, none of my Watch "Configurations" would work. They were there but when you tapped them, they gave an X instead of a Check Mark (Check Mark means its working). Additionally, after refreshing the configurations in the Apple Watch app, the script names changed from Friendly Name to script.XXX name. This aligned as well to what they showed in the iOS companion app watch configuration, too. 

Fast forward to last night, I upgraded to 2024.10.4 and again my watch configurations stopped working.  Having seen this before, I knew I needed to remove them and re-add them.  The act of readding them isn't the end of the world but as noted under expected behavior, I expect them to persist an update. So, effectively, it seems that upgrading core breaks Watch Configurations each time you upgrade.  You must remove and re-add them.  You don't have to delete the script, just remove the item from configuration and Tap Add Item and reselect the script(s).

Mitigation:  Delete the items in Companion App/Watch/Configuration section and re-add them.  Once you re-add them they seem to work fine until the next Core update. 

**To Reproduce**
Upgrade Core to any new version

**Expected behavior**
Upgrade Core and not have to delete and re-add the "script" items in the Watch Configuration section of the companion app.

**Screenshots**
![Before Core Update](https://github.com/user-attachments/assets/e6d6d771-e45f-491a-a62c-5f9eaeb692bf)
![After Core Update](https://github.com/user-attachments/assets/77958764-9d40-49e4-947f-d8891897cffe)

**Additional context**
NOTE:  The items in the screenshots are out of order.  The point I'm trying to make is that the core update breaks something.  The order is irrelevant since you must re-add them after the core update to restore functionality.

**Comment by bgoncal** [comment]
My initial guess is that for some reason your server ID is changing when you update core, if the server ID changes the configuration items don't know what to display because they are looking for the old ID, weirdly that never happened to me, can you please export and send your logs? https://forms.gle/Uoqz127Phx4mMTpS6

**Comment by livetoautomate** [comment]
@bgoncal - Uploaded.  Link expires in 2 days.

**Comment by bgoncal** [comment]
@livetoautomate I need the app logs, go to: `Companion App Settings >> Debugging >> Export logs`

**Comment by livetoautomate** [comment]
@bgoncal - Uploaded

**Comment by bgoncal** [comment]
Some questions to help me debug:
- I am reviewing your app database (from your logs), do you have the watch configuration working fine now? Just so I know if what I am looking at is the "wrong" configuration or a configuration that is currently working.
- Are you now with more than 1 Apple Watch paired to your iPhone? If the answer is yes, how does the HA app behave on the other watch?
- Any chances you have removed and readded the server in the app?
- Do you have multiple servers configured in the App?
- If you reboot your HA instance, does the same issue happens?

**Comment by livetoautomate** [comment]
In order of your bullets...
1. The watch configuration is working properly "now".  "Now" is basically as of the time I submitted this bug since I manually removed and re-added the configuration items. Theoretically, I would think anything between 11/28 and 11/29 would be a broken configuration.
2. I only have one Apple Watch (Ultra 2).  I had a Series 8 before I traded up for an Ultra 2.  At the time of the switch, I also converted from using Actions to Configurations. I didn't like that I couldn't remove the "Are you sure?" with Actions. Working in IT, I know making multiple changes at the same time makes debugging more difficult.  If it would help, I can re-instate one or two of the Actions to see how it persists those through a Core update.  I can tell you that with the Series 8 and using Actions, I never had this problem.  It's difficult to know if its a new watch or the transition to configurations that surfaced the issue.
3. Yes, actually.  I was having 403 errors in the Companion App using the Internal URL.  The internal URL was working fine on another device, so I removed and re-added the server. The issue ended up being a DNS problem on my iPhone.  After resolving the DNS issue, the Internal URL was working fine.
4. I only have one server.
5. I confirmed my Configuration Item is working before and after a HA instance reboot (not just a Core restart).

**Comment by bgoncal** [comment]
Ok thanks for these info. Because of your answer on item `3`, I think this could be the major issue, let me give you an overview of what happens behind the scene:

iOS Actions are "items" that it's "ID" does not rely on the server, while the scripts/scenes and other entities are connected to an specific server and their ID's are "serverId-entityId", because if we only used the entityId it could conflict with user that have multiple servers and same entities in those.

When you delete a server in the App and then add it back, it will generate a new ID, since the app doesnt know if you are adding the same one you deleted or a different one, so because of that your watch configuration tries to get the information for those items that you set to display on your watch but the ID does not match anymore.

Can you keep this working configuration until the next time you update core and report back if it breaks again? Would be cool to get the logs at the same moment it breaks as well

**Comment by livetoautomate** [comment]
No Problem.  I don't believe I removed the server the first time it broke but cant be 100%.

Next Core update I will be sure not to modify the server (in companion app) and then complete the update.  I will report back.  

That then begs the question, Why does the companion app generate a new server ID.  The server ID would theoretically always be the same, unless you reinstall HA or if you do a restore.  I guess thats not how it works but it seems logical that it would work that way.

**Comment by bgoncal** [comment]
Indeed, from what I can see in the codebase, the ID is not something that comes from HA server itself, it's generate at the moment it gets added. This could be improved of course

**Comment by bgoncal** [comment]
Apparently you were kicked out because you receive "not authorized" error message, did you submit your logs? https://forms.gle/Uoqz127Phx4mMTpS6

**Comment by livetoautomate** [comment]
Uploaded

**Comment by bgoncal** [comment]
I'll check if I can find why you got logged out but in parallel Im also building a migration tool for these cases.
