### ISSUE TITLE
HomePod not playing through Home Assistant

### ISSUE THREAD

**Issue by Bodi78** [home-assistant/iOS#3116]
**iOS device model, version and app version**

Model Name: iPad 7th Gen
Software Version: 18.1
App version: 13.2

**Home Assistant Core Version**
 2024.10.4

**Describe the bug**
I am trying to integrate my HomePods into an automation to automatically start playing when I leave the home as I have a pet that has separation anxiety due to health issues and I want to have music playing so that she stays calm and doesn’t over exert herself and potentially cause herself more health issues

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by bgoncal** [comment]
Thanks for reporting the issue, and as I also have a cat I know the feeling ❤️

But unfortunately you have reported the issue in the wrong repository, this repository supports the Apple platform apps (iOS, macOS, watchOS), for bugs related to the HomePod integration you need to report to CORE.

**Comment by Bodi78** [comment]
Which section should this be in

Many Thanks

Mark Boyd

**Comment by bgoncal** [comment]
https://github.com/home-assistant/core

**Comment by Bodi78** [comment]
I think I have reported it correctly this time

Many Thanks

Mark Boyd
