### ISSUE TITLE
Sensor Widget does not respect precision

### ISSUE THREAD

**Issue by DCSBL** [home-assistant/iOS#3122]
**iOS device model, version and app version**

Model Name: iPhone 16 Pro
Software Version: 18.1
App version: Versie: Tesflight 2024.10 (2024.913)

**Home Assistant Core Version**

**Describe the bug**
New iOS Sensor widget does not respect value precision setting.

**To Reproduce**
Select a non-default precision in sensor settings, select this sensor in the widget

**Expected behavior**
Precision is reflected everywhere, why not in the widget?

**Screenshots**

![IMG_0563](https://github.com/user-attachments/assets/851cd44b-74ab-4b53-9c7f-c04ced32c615)
![IMG_0562](https://github.com/user-attachments/assets/d956b7ee-3042-40d7-b4f3-7a82b8ef2b3a)

**Additional context**

Not sure if this a bug or just a missing feature.

**Comment by Penait1** [comment]
Hi, this is missing based on my naive optimistic assumption that the HomeAssistant API would return the value correctly based on precision.

I'll look into it how to apply the precision settings anytime soon since that would be great for readability

**Comment by skynet01** [comment]
Thank you, i am glad i am not the only one that's annoyed by this

**Comment by bgoncal** [comment]
@Penait1 do you still have time to implement this? I think it can be cached in the app database so we don't have to request everytime for the precision of a sensor

**Comment by bgoncal** [comment]
Caching precision to be used in sensors:
https://github.com/home-assistant/iOS/pull/3268
