### ISSUE TITLE
Intermittent "Error while loading page" on every page

### ISSUE THREAD

**Issue by maxshcherbina** [home-assistant/iOS#3142]
**iOS device model, version and app version**

Model Name: iPhone 14 Pro Max
Software Version: 18.1
App version: 2024.905

**Home Assistant Core Version**

2024.11.1

**Describe the bug**
Opening the app, I am immediately greeted by an error screen "Error while loading page lovelace". When I open the settings, i cannot access them due to another error "Error while loading page settings", there are only a limited amount of things I can access, like history and logbook seem to work, but nothing else. Force closing the app and re-opening doesnt fix it. Problem on the TestFlight version too.

This seems to only occur on the Companion app. Safari works fine.

Half way through the day, the bug stopped, and I was able to access everything normally. But then the next day i get the same errors.

Just tried to switch my clock to early in the morning in case it was something based on time, but to no avail.

My partner's phone - also an iPhone 14 Pro (not Max) the companion app works fine.

**To Reproduce**
Open the app, immediate error.

**Expected behavior**
No errors loading the dashboard/settings.

**Screenshots**

Will add when it happens again.

**Additional context**

I can provide logs if this would be caught by them.

**Comment by jeffmeyers11** [comment]
Seeing the same behavior on my iPad Pro 11 but not on my iPhone 13 Pro.

**Comment by bgoncal** [comment]
From what I noticed this came with core update 2024.11 but I havent experienced the issue since 2024.11.1, have you updated already?

**Comment by jeffmeyers11** [comment]
> From what I noticed this came with core update 2024.11 but I havent experienced the issue since 2024.11.1, have you updated already?

I’m seeing this on Core 2021.11.1

**Comment by bgoncal** [comment]
Companion app settings >> debugging >> Reset frontend cache

Let me know if it happens again after doing that

**Comment by bgoncal** [comment]
Pull down to refresh (but I imagine you already tried), if this doesn't work, swipe up with 3 fingers, then tap the gear icon that will show up

**Comment by jeffmeyers11** [comment]
> Pull down to refresh (but I imagine you already tried), if this doesn't work, swipe up with 3 fingers, then tap the gear icon that will show up

I was unaware of swiping up with three fingers.  Good tip.    

I cleared the front end cache and this has resolved the issue for me.  Thank you for the prompt help!

**Comment by maxshcherbina** [comment]
I'll keep an eye on this, but hopefully, the bug will not return after clearing the cache!

**Comment by bgoncal** [comment]
Let me know in case it needs to be reopened, but as we could see, it is something related to frontend, so probably opening the issue in frontend repo can bring more valuable feedback about it.
