### ISSUE TITLE
2024.951 drains my phone and is sluggish

### ISSUE THREAD

**Issue by erkr** [home-assistant/iOS#3165]
**iOS device model, version and app version**

Model Name: iPhone 14
Software Version: 17.7.1
App version: 2024.11 (2024.951)

**Home Assistant Core Version**

2024.11.2

**Describe the bug**
Phone runs hot, battery drains and controlling the companion app is sluggish

**To Reproduce**
I reverted to 2024.10 (2024.927) and everything runs normal again

**Expected behavior**

**Screenshots**

![image](https://github.com/user-attachments/assets/0b80d36c-7390-4472-9e51-26916e85c073)
**Additional context**

None

**Comment by bgoncal** [comment]
Are you using the internal or external IP?
If internal, have you defined your local SSID (network name) inside the internal URL screen config? 

There is a change in the app that it will only use internal IP if the network name if defined.

**Comment by erkr** [comment]
@bgoncal 
Not sure I understand. I use local ip only AFIK:
![image](https://github.com/user-attachments/assets/fe684efb-ebf7-4bfb-afba-4af62b9b2cd1)

**Comment by bgoncal** [comment]
I mean in app settings.
If you want to use the same URL externally just set it as external URL as well.

This change is to prevent people exposing their token in public wifi without encryption since most users use http at home.

 ![image](https://github.com/user-attachments/assets/cf24361f-0576-410c-ab77-8980dcd41eff)

**Comment by erkr** [comment]
Thanks for explaining. Will give it a try tomorrow👌

**Comment by erkr** [comment]
I checked, network was configured correct. Same url for external and SSID's for internal where set.
That seems not the cause. 
Latest version stutters while scrolling dashboards and drains my phone

**Comment by bgoncal** [comment]
Thanks for the update, I'll debug during this week (I received other similar reports)

**Comment by bgoncal** [comment]
Can you try out the new beta?

**Comment by erkr** [comment]
I will do that. (Didn’t understand the database throttling)

**Comment by erkr** [comment]
Thanks I will report back in a few hours on the battery drain part 👌

**Comment by erkr** [comment]
@bgoncal 
It looks like both the sluggish UI and the battery drain are solved 👌
I chose the issue. Thanks for your time 🤗
