### ISSUE TITLE
Homeassistant server disappears for no reason

### ISSUE THREAD

**Issue by KazemaRyukuro** [home-assistant/iOS#3189]
**iOS device model, version and app version**

Model Name: IPhone 13 Pro
Software Version: IOS 18.1.1
App version: 2024.9.4 (2024.905)

**Home Assistant Core Version**

2024.11.3

**Describe the bug**

I have had the problem for some time that a Home Assistant server disappears completely from the companion app IOS after a short time. I always have to add and register it again afterwards.

The situation is that I have my own Home Assistant. This one is connected normally and does not disappear. However, my mother's second server keeps disappearing if I don't use the app for a long time.

I have already deleted the companion app several times, deleted backups and restarted my phone, but none of this has helped.

**To Reproduce**

1. add a server
2. close the app and do not use it for a while
3. server has disappeared

**Comment by bgoncal** [comment]
Try the latest beta. But the root cause must be the app getting "403" aka unauthorized, how is remote access setup in your moms server?

**Comment by bgoncal** [comment]
Duplicate: https://github.com/home-assistant/iOS/issues/3141
