### ISSUE TITLE
Unable to log in via companion app

### ISSUE THREAD

**Issue by Smk3416** [home-assistant/iOS#3194]
**iOS device model, version and app version**

Model Name:  IPhone 13
Software Version: 18.1.1
App version: 2024.9.4

**Home Assistant Core Version**
2024.11.3

**Describe the bug** Upgraded IOS version earlier today from 17 to 18.1.1. Now companion app fails to log in, just keeps saying will retry in 60 seconds. Can log in via PC on google chrome no issue. 

**To Reproduce** try upgradig ios to 18 and try to log in

**Expected behavior** refuses to log in, just keepy saying retry

**Screenshots**

**Additional context**

**Comment by bgoncal** [comment]
Please submit your logs https://forms.gle/Uoqz127Phx4mMTpS6

**Comment by Smk3416** [comment]
Which specific logs and how do I find them?
Sent from my iPhone

On 26 Nov 2024, at 18:26, Bruno Pantaleão Gonçalves ***@***.***> wrote:

﻿

Please submit your logs https://forms.gle/Uoqz127Phx4mMTpS6

**Comment by Smk3416** [comment]
After checking my logs for IOS in the last day or so, found this


Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/http.py:525
integration: Home Assistant WebSocket API (documentation<https://www.home-assistant.io/integrations/websocket_api>, issues<https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22>)
First occurred: 04:45:44 (1 occurrences)
Last logged: 04:45:44
[281473093668144] from 192.168.1.201 (Home Assistant/2024.9.4 (io.robbie.HomeAssistant; build:2024.905; iOS 18.1.1)): Disconnected: Did not receive auth message within 10 seconds

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by bgoncal** [comment]
Companion app settings >> debugging >> export logs

**Comment by Smk3416** [comment]
Found it but can’t email as file too big
Sent from my iPhone

On 27 Nov 2024, at 09:04, Bruno Pantaleão Gonçalves ***@***.***> wrote:

﻿

Companion app settings >> debugging >> export logs

**Comment by Smk3416** [comment]
Sent from my iPhone

On 27 Nov 2024, at 09:04, Bruno Pantaleão Gonçalves ***@***.***> wrote:

﻿

Companion app settings >> debugging >> export logs

**Comment by Smk3416** [comment]
Any progress?

**Comment by bgoncal** [comment]
Were you able to submit your logs? https://forms.gle/Uoqz127Phx4mMTpS6

**Comment by Smk3416** [comment]
Yes. I sent directly and a Google drive link
Sent from my iPhone

On 9 Dec 2024, at 07:59, Bruno Pantaleão Gonçalves ***@***.***> wrote:

﻿

Were you able to submit your logs? https://forms.gle/Uoqz127Phx4mMTpS6

**Comment by bgoncal** [comment]
Open Companion App Settings, double check if your internal/external URL is correct, then go to debugging >> "Reset frontend cache".

If that doesn't work, please remove your server and add it again

**Comment by Smk3416** [comment]
Tried that, even did a complete reset of the app. Now it does the same thing but won’t even allow me to open the settings for more than a second or two before it closes the page. Still won’t connect to HA
Sent from my iPhone

On 9 Dec 2024, at 09:28, Bruno Pantaleão Gonçalves ***@***.***> wrote:

﻿

Open Companion App Settings, double check if your internal/external URL is correct, then go to debugging >> "Reset frontend cache".

If that doesn't work, please remove your server and add it again

**Comment by bgoncal** [comment]
Delete the server once more, after you add it back, after the issue happens, export the logs and upload again please. If you are not able to, please try the TestFlight version.
https://forms.gle/Uoqz127Phx4mMTpS6

**Comment by Smk3416** [comment]
Tried, no joy with any of it. Uploaded link to files
Sent from my iPhone

On 9 Dec 2024, at 18:56, Bruno Pantaleão Gonçalves ***@***.***> wrote:

﻿

Delete the server once more, after you add it back, after the issue happens, export the logs and upload again please. If you are not able to, please try the TestFlight version.
https://forms.gle/Uoqz127Phx4mMTpS6

**Comment by Smk3416** [comment]
Sent you a link to the Dropbox where I have uploaded the logs
Sent from my iPhone

On 9 Dec 2024, at 18:56, Bruno Pantaleão Gonçalves ***@***.***> wrote:

﻿

Delete the server once more, after you add it back, after the issue happens, export the logs and upload again please. If you are not able to, please try the TestFlight version.
https://forms.gle/Uoqz127Phx4mMTpS6

**Comment by bgoncal** [comment]
Can you reach me on discord? Let's try to reconfigure together (username: bgoncal2).
Your logs do show that credentials were accepted though

**Comment by Smk3416** [comment]
I’ll try,  just sent you a friend request
Sent from my iPhone

On 12 Dec 2024, at 14:09, Bruno Pantaleão Gonçalves ***@***.***> wrote:

﻿

Can you reach me on discord? Let's try to reconfigure together (username: bgoncal2).
Your logs do show that credentials were accepted though

**Comment by bgoncal** [comment]
After talking in discord we observed that this issue also happens in iOS Safari iOS 18 but not iOS Safari iOS 17, since it's not app exclusive this needs to be handled by frontend or core.
I'll be closing the issue in the iOS repo but feel free to tag me in the frontend/core issue.
