### ISSUE TITLE
Sensor widget displays wrong sensor and wrong localization when connected externally

### ISSUE THREAD

**Issue by rct** [home-assistant/iOS#3213]
**iOS device model, version and app version**

Model Name: iPad Pro (10.5 inch) (iPad7,4)
Software Version: 17.7.1
App version: 2024.978

**Home Assistant Core Version**
2024.11.2

**Describe the bug**

Sensor widget on home screen configured to display two sensors working fine when internally connected, but displaying another sensor when connected externally (nabu casa)

**Expected behavior**

The sensor widget should be displaying the configured temperature and humidity sensor localized to Fahrenheit for the US.

**Screenshots**

Incorrect sensor display while connected externally
![incorrect_sensor_display](https://github.com/user-attachments/assets/9a6b1403-d823-4d34-ba3c-5218ca94b276)

Sensor config while connected externally shows the right entity names:
![sensor_config](https://github.com/user-attachments/assets/30b33828-b689-47c2-946c-21a885bd4d7b)

**Additional context**

**Comment by Penait1** [comment]
Mm, those wrong sensors you see are the placeholder ones when no values can be fetched.

Do you have multiple homes configured or did you delete the internal HA and added the external Nabu Casa one? Did you try to re-add the widget?

**Comment by rct** [comment]
* I do have 3 servers configured.  This server has both an internal URL and Nabu Casa cloud sub for external.  
* I did not delete or change home assistant ios app config/urls, etc. 
* The only thing I did was roam from my internal network wifi, to external network cellular.  
* I can reproduce this behavior by turning off wifi on my device so that it is forced to connect externally
* The main app page does get reconnected though it seems to go through some retries.

**Comment by Penait1** [comment]
I see, thank you for the additional information. I was unaware of the external/internal config options so that will help me trying to reproduce the issue

**Comment by bgoncal** [comment]
@Penait1 perhaps we shouldn't show the placeholders in this case, this a message saying it couldn't be loaded.
Besides that the real issue here is the remote connection from @rct

**Comment by rct** [comment]
Those placeholders were very confusing to me since they seemed plausibly close to my real sensors. If you are going to have any kind of placeholder, please make it really obvious.

**Comment by rct** [comment]
closing this given that it is mostly about the placeholder.  Will open a separate issue as needed about the connectivity issue
