### ISSUE TITLE
When opening any climate entity (automatic and manually created) there is no UI present for control

### ISSUE THREAD

**Issue by mihaicristianpetrescu** [home-assistant/iOS#3230]
**iOS device model, version and app version**

Model Name: iPhone 16 Pro Max
Software Version: iOS 18.1.1
App version: 2024.9.5 (2024.986)

**Home Assistant Core Version**
2024.11.3

**Describe the bug**
When opening up a climate entity, no matter if it's generated by an add-on (ex: Ecobee) or if it's a manually created one, there's no UI rendered for it, it's just a blank screen. In Chrome browser it does show up just fine.

**To Reproduce**
Open any climate entity.

**Expected behavior**
UI controls should show up

**Screenshots**
![IMG_B4D3E134D1F4-1](https://github.com/user-attachments/assets/0c242f0c-7e20-4c4f-9259-4f09e5da7a64)

**Additional context**
Not 100% sure, but the issue might have started with the latest release of the HA app on iOS. I haven't opened the a climate entity control in a couple of days.

**Comment by bgoncal** [comment]
Can you check how it behaves on iOS Safari? Also if you force close the app and open again does it works? And finally Companion app settings >> debugging >> reset frontend cache.

Let me know the results

**Comment by mihaicristianpetrescu** [comment]
Force close and open app again didn't do anything since I already tested that before reporting, and also did a phone reboot.
What fixed it is the reset frontend cache. Not ideal, but worked. Thank you!
