### ISSUE TITLE
Fast pressing "+"/"-" buttons on thermostat view zooms/unzooms on iOS

### ISSUE THREAD

**Issue by ssg** [home-assistant/iOS#3240]
**iOS device model, version and app version**
- iPhone 14 Pro, iOS 18.1.1
- Frontend Version: 20241106.2

**Home Assistant Core Version**
2024.11.3

**Describe the bug**
It's common to press on "+" or "-" buttons on a Thermostat view to rapidly change temperature target. However, multiple successive clicks are recognized as "zoom in" action and the app inadvertently zooms in and out instead of performing the action. That's quite annoying.

**To Reproduce**
Click "+" on Thermostat view successively on iOS.

**Expected behavior**
It should perform temperature change instead of zooming in. I don't expect "double click" to do anything close to zooming in on an app.

**Comment by bgoncal** [comment]
Can you check if it also happens in iOS Safari?

**Comment by bgoncal** [comment]
In this case please report in the "frontend" repo, since it's not something the app can fix.

Context: the app only displays a webview with home assistant web UI on it.

**Comment by ssg** [comment]
@bgoncal The thing is, I don’t expect Safari to handle this case, but I expect an app to. No native app has a “double click to zoom” feature on its UI. This is a problem with the app, that’s why I filed it here. Anyway, I can try frontend top, but I don’t think this issue was out of place.

**Comment by bgoncal** [comment]
I understand what you mean, but these kind of issues we address first on frontend then afterwards on mobile if needed, in this way we don't need to implement a workaround twice, in iOS and Android, feel free to ask me to reopen in case frontend say they can't fix it.

**Comment by bgoncal** [comment]
Also if this is what you mean, I was not able to reproduce the issue.

https://github.com/user-attachments/assets/fe8234c4-d9c3-43dc-abaa-44b07a528132

**Comment by bgoncal** [comment]
Are you sure you don't have this option enabled by mistake? 
![image](https://github.com/user-attachments/assets/406a8b1a-44b7-4dda-9c66-62a40e5feae7)

**Comment by ssg** [comment]
@bgoncal I understand it. Where is that setting if I may ask? I’m also attaching a video how it happens on my phone. 

https://github.com/user-attachments/assets/967075f8-2dbf-40f9-9c28-3856169301be

**Comment by bgoncal** [comment]
Companion app settings >> General

**Comment by ssg** [comment]
@bgoncal Disabling “pinch to zoom” fixed my issue, but I don’t remember enabling it. Could it be the default by any chance?

**Comment by bgoncal** [comment]
It's not the default as far as I know, I can check tomorrow during working hours
