### ISSUE TITLE
Can't connect via internal url in newest version

### ISSUE THREAD

**Issue by Cyberbeni** [home-assistant/iOS#3259]
After the newest update, my iPad decided to not connect to HA. I only had internal url setup, after copy pasting the url to external url, it successfully connects.

All permissions besides Local Network, Push and Background App Refresh are off.

**iOS device model, version and app version**

Model Name: 
Software Version: 
App version: 

**Home Assistant Core Version**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Cyberbeni** [comment]
I don't understand why it was so important to break half the people's setup, seemingly without any notice. There was no notice about the breaking change at the top of the iOS release notes, there was no alert in HA that my current setup will stop working at a specified date/version.

If people can't connect to my internal network then they can't do anything with the token.

> the App will not fallback to the internal URL in case the external URL is not available

The external URL wasn't even set, my setup is only accessible internally.

Why not just create an SSL cert on the server (and automatically create and distribute new ones overlapping with the current cert's validity) and use that to connect via https when the user adds HA with an http address? And if the device doesn't have the most up to date SSL cert that the server uses, then ask for user confirmation that we are on the home network. Could also use the Local Push connectivity managed by iOS to detect which server we are connected to via an internal address (being able to set up the SSID on the server would also be nice instead of having to add it to every device manually)

**Comment by Lancelot-Enguerrand** [comment]
Hello,

This choice, and more specifically its implementation, is causing me some issues.
I speak from the perspective of someone who only uses Home Assistant through internal access.
I have users with no technical background, and their iOS app is the only point of access to their connected devices.

### No warning
This update was pushed with a <ins>breaking change</ins> **without any warning**, neither in the app nor in the patch notes.
Upon launching the app, we are just faced with a blank page.

1. A somewhat resourceful user will eventually figure it out by tinkering and copying the internal URL into the external URL but will <ins>not being certain it's the correct solution</ins>.
2. <ins>A regular user will simply be stuck</ins>. _(This is what brought me here and, honestly, it frustrates me a little.)_

### Enabling precise location
I understand that this request for full location access just to see the Wi-Fi name is an implementation constraint imposed by Apple, but :

1. How is a user supposed to understand this?
2. Additionally, what are the guarantee of an restricted and appropriate use of this data?
3. I also have some concerns about the battery usage this implies.

### Security
Maybe I am being too skeptical about this, but if I don't expose my Home Assistant, someone intercepting my token on another network would probably not do anything with it.
I wouldn't say this protection is unnecessary, but again, it’s the sudden implementation that feels clumsy.

The fact that this update was delivered with a breaking change without any warning is really problematic in my opinion.
I suppose this could be improved by rewording some aspects and communicating about this change in an appropriate way.
As it stands, I remain uncomformatable about enabling location and doubtful about the best course of action.

**Comment by bgoncal** [comment]
@Cyberbeni When the app doesn't find a URL it can use, a message is displayed with instructions, was it not shown for you?

**Comment by bgoncal** [comment]
@Lancelot-Enguerrand thanks for the feedback, I agree the communication could be better and I'll take that into consideration in a patch release.

About security, even though your server is not exposed to the internet, the token is a private sensitive information, imagine that today you device to expose your instance to the web? Someone could already have intercepted your token, that's just one scenario.

**Comment by bgoncal** [comment]
@Cyberbeni About the SSL certificate, this is a solution also in consideration but it will require a way bigger cross platform implementation, don't expect it soon, but it's in our radar.

**Comment by bgoncal** [comment]
Just double checking, you did see a warning like this right? 

![image](https://github.com/user-attachments/assets/dabc55e4-0c64-4537-9e61-17333337be8d)

**Comment by bgoncal** [comment]
I just paused the 7-day phased release to improve the communication

**Comment by Cyberbeni** [comment]
> @Cyberbeni When the app doesn't find a URL it can use, a message is displayed with instructions, was it not shown for you?

To be honest, I read the error title and looked at the action offered (open settings), but I don't think I know many people who would do more than that when something that is supposed to be a one time setup breaks, especially if someone else helped them set it up.

**Comment by bgoncal** [comment]
@Cyberbeni fair enough, tomorrow I'll have more information to share regarding this.

Meanwhile would be very nice to have you in our beta loops, so we can get feedback in advance of releases, is this something you want? https://testflight.apple.com/join/1AlPbnLZ 

Also an invite for you @Lancelot-Enguerrand

**Comment by Cyberbeni** [comment]
Sure, I joined the beta.

**Comment by bgoncal** [comment]
While a better migration/communication is being developed, I will revert to always fallback to internal URL and release it as 2024.12.1
https://github.com/home-assistant/iOS/pull/3265

**Comment by bgoncal** [comment]
@Cyberbeni can you help me check build 2024.1041?

**Comment by Cyberbeni** [comment]
2024.1041 works fine when only the internal url is set.

**Comment by bgoncal** [comment]
2024.12.1 release in App Store.

Soon in TestFlight there will be a new screen communication the change and offering options to the user, keep an eye on it and feel free to tag me.

**Comment by tache** [comment]
Along with this change why do we have to do these settings ?

![image](https://github.com/user-attachments/assets/3d5f6c9d-3248-4289-a975-61046c23836b)

**Comment by bgoncal** [comment]
@tache whats exactly your doubt? 

The App can only determine if you can access your local URL (internal URL) if the app knows your are in your local network, for that we need to check your SSID configured and ti have access to that we need the permission explained in your screenshot.

The app CURRENTLY fallbacks to internal URL when no external URL is available, but this should change soon, we are not working on the proper communication + migration screen, we will also include an option to "ignore everything and always fallback to internal URL"

**Comment by tache** [comment]
Thanks for the reply. So this would be the first app that I have ever seen that would require that you specifiy a local wifi SSID to connect locally, that would then require you to provide IOS permission to allow always-on and precise location. The app should only rely on trying to access the local URL via DNS name reolution. If it does not resolve then it should fail to connect.

**Comment by tache** [comment]
I guess I should had posted this under #3255

**Comment by bgoncal** [comment]
I saw your other reply first, so I replied on that thread, linking it here https://github.com/home-assistant/iOS/issues/3255#issuecomment-2544055250

And let's keep the conversation here

**Comment by bgoncal** [comment]
Reposting here to be easier to continue reading:

@tache what if you are on a public network and someone hosted a fake home assistant to hijack your token?

You can imagine that people usually have internal URL such as:
192.168.0.xxx:8123

So my example above could easily happen. Resolution would succeed. But it is not your HA server.

SSID is not perfect but it is the solution in place app-wide right now, and again, we will provide an option to ignore that and just fallback to internal URL if you need/want.

**Comment by tache** [comment]
@bgoncal thanks for the latest version - working fine.

**Comment by Ren656** [comment]
Goodafternoon, i’m facing a simular problem. I’m using Home Assistant Core in Docker on a RaspberryPi 4b. It was running fine but suddenly the companion App of HA yielded ‘NSURLErrorDomain -1009’ on my iPad2. Connection through a webbrowser, either Safari or Firefox, is working fine on the same iPad and also a connection through the HA app on iPhone SE2 is working. I really have no idea, in Settings i have given the HA app ‘always’ access to ‘precise’ location. Thanks for any suggestion to repair this (Core 2024.12.5).

**Comment by tache** [comment]
Some hints that might help.
 - Make sure you are on latest iOS app.
 - in iOS app, under Settings>Network I have local network turned set to automatic: on.
 - Also in the app, hostname is just the simple local host name. It not the FQDN. 
 - in the iOS settings for the app, I have local network turned on.
 - I am not using any external capability.

**Comment by Ren656** [comment]
Possibly I found the hickup: re-installing the HA app creates a fresh, new start. Including a screen asking for permission to access my local network. Above communication suggests this permission is needed, that’s correct?
However, the only network indicated is not valid for my home situation and i see no option to change this. Any suggestion?

**Comment by tache** [comment]
Are you about to see the yellow circle with gear icon? If so, click that and then you can go to the top item "Home Assistant" to set the internal url

**Comment by tache** [comment]
Also I can duplicate the behavior you are experiencing when I turn on my VPN, so I can't see my network and therefore my home assistant.

**Comment by Ren656** [comment]
Some time ago I turned my VPN off as I experienced the above problem. After turning off VPN the HA app worked fine. But stopped again a few days ago. This yellow circle with gear icon (in above text I referred to it as ‘star like’) is not visible. Re-installing the HA app the second screen (after the Welcome) displays a map with one router name, but that’s the one of my second house in France. Now I am in NL and there is no way to change location and/or router name. 

Either way, i do have access through a web browser. It is just annoying. And, being a noob, I don’t understand the explanation of @bgoncal, especially because the web based application (HA) doesn’t work but there is no problem accessing the HA server through my brower. 

I just started reading about securing HA and know that i still have a way to go to secure my set up.

**Comment by pacmac** [comment]
same issue today, everything is on the latest version, internal and external urls are set in HA:

https://github.com/home-assistant/iOS/issues/3608#issuecomment-3544642659

**Comment by cornebistouille** [comment]
i had that problem in 2024, then i try to add externat adress it worked, but now it wont work again... isnt it related to MFA : i see no way to enter my authenticator code when trying to connect ...

<img width="768" height="583" alt="Image" src="https://github.com/user-attachments/assets/8ce5a3ab-0608-474b-97c5-a714a8898a36" />
