### ISSUE TITLE
assist.watch.mic_button.title has trailing space that Lokalise refuses

### ISSUE THREAD

**Issue by NoRi2909** [home-assistant/iOS#3286]
**iOS device model, version and app version**

Model Name:  n/a
Software Version: n/a
App version: n/a

**Home Assistant Core Version**

**Describe the bug**

assist.watch.mic_button.title has trailing space that Lokalise refuses in translations.

**To Reproduce**

See screenshot below from Lokalise.

**Expected behavior**

Should not be part of the string but added in code to avoid the issue.

**Screenshots**

![image](https://github.com/user-attachments/assets/f111bee7-38ec-4562-991b-07aee0dd30cc)

**Additional context**

**Comment by bgoncal** [comment]
I'll update that
