### ISSUE TITLE
Restart for update

### ISSUE THREAD

**Issue by MacBook1976** [home-assistant/iOS#3288]
**iOS device model, version and app version**

Model Name: raspberry pi 5
Software Version: 14.2
App version: 12.2

**Home Assistant Core Version**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
 Uh oh! Looks like we are unable to establish a connection.
Could not connect to the server.

**Additional context**

**Comment by MacBook1976** [comment]
What happened? How fix

**Comment by bgoncal** [comment]
Closing this issue since the lack of information, please open a new issue and provide more context of what happened, when it happened, any changes in your setup recently and you can also export companion app logs and upload here https://forms.gle/Uoqz127Phx4mMTpS6
