### ISSUE TITLE
Location region incorrectly states "outside"

### ISSUE THREAD

**Issue by sgruby** [home-assistant/iOS#330]
It appears that a new location issue may have been recently introduced. In the event log, I'm seeing:

`2019-05-05 13:28:40.172 [Info] [main] [ClientEventStore.swift:23] ClientEventStore > ClientEvent {
	date = 2019-05-05 20:28:40 +0000;
	text = Already Monitoring: Zone - ID: zone.home, state: outside;
	typeString = unknown;
	jsonData = <(null) — 0 total bytes>;
}
`

When I launch the app. The problem is that `state: outside` is not correct; I'm at home and looking at the device_tracker entity in HA shows the state as home.

Location was working fine last night, but it appears that the app doesn't know where I am, but HA does!

**Comment by TomBrien** [comment]
If I understand correctly, the issue here is solely related to incorrect information in that log entry. Those log entries were spamming the logs and have been removed from 2020.3 so I will close this. Let me know if I've got this wrong
