### ISSUE TITLE
Scanning for Home Assistant detects external URL

### ISSUE THREAD

**Issue by thermseekr** [home-assistant/iOS#340]
iPhone 7 plus, latest iOS.

I use duckdns + let's encrypt, and nginx as SSL proxy. When opening the app for the first time it scans the network and finds home assistant, but identifies the URL as https://******.duckdns.org.

I'm behind an Watchguard Firebox of the older XTM series, and I cannot do NAT loopback being on a dynamic IP, so this address is invalid and the app fails to connect.

If I enter the local address manually I can connect. But then in the connection settings details, I have "connected via external URL".

Shouldn't the app identify Home Assistant by its local URL? Apparently the app is not recognizing the SSID I'm connected to, although it is in the list of SSIDs in the same Connection Settings.

As a side note, if when connecting I leave the manual address field blank (with the suggested address in light gray) the app shuts down when hitting enter.

**Comment by TomBrien** [comment]
I think #722 will address this by allowing the app to import both values form Home Assistant

**Comment by zacwest** [comment]
Fixed in #1878.
