### ISSUE TITLE
Logic for filling in external/internal during onboarding

### ISSUE THREAD

**Issue by olbjan** [home-assistant/iOS#350]
Currently the app cannot detect the network environment for the HA setup. Entering manual connection info is still required under certain circumstances. The goal of this issue is to explain logic trees how the app can fill in the correct addresses for most common setups, including:

1. HA on hass.io with just defaults and Nabu Casa Cloud enabled, no NAT
2. HA with custom public DNS (e.g. DuckDNS), Hairpin NAT
3. HA with custom public DNS and nginx Reverse Proxy
4. HA with split brain DNS records
5. HA with no custom DNS and only via internal connection/VPN

Detection requires a helper service on the public internet that will be called to confirm the external availability of the HA instance (called Firebase Check).

I have created workflows in draw.io to illustrate the possible routes onboarding will take:

![HA iOS Onboarding-Automatic detection](https://user-images.githubusercontent.com/43749346/57379660-a5675300-71a7-11e9-8e83-4bb395d08586.png)

![HA iOS Onboarding-Manual Setup](https://user-images.githubusercontent.com/43749346/57379659-a5675300-71a7-11e9-9cf5-610a744d075a.png)

![HA iOS Onboarding-Firebase Check](https://user-images.githubusercontent.com/43749346/57379658-a4cebc80-71a7-11e9-937f-e8220f9bc494.png)

The source file can be downloaded here:
[HA iOS Onboarding.zip](https://github.com/home-assistant/home-assistant-iOS/files/3157542/HA.iOS.Onboarding.zip)

**Comment by olbjan** [comment]
/api/discovery got replaced by a 404 with 0.94b0

**Comment by robbiet480** [comment]
It's `/api/discovery_info`, not `/api/discovery`
