### ISSUE TITLE
Ability to selectively disable sensors in settings

### ISSUE THREAD

**Issue by pricard32** [home-assistant/iOS#358]
I would like to see a sensor tab in the setting page to let the user the ability to select or not wich sensor he want to expose to HA

**Comment by stbeep1** [comment]
Hi, does this way already exist? Because I did not find it @zacwest 
or has anything changed? @robbiet480 @SeanPM5

**Comment by zacwest** [comment]
It is not appropriate to mention everybody you can think of to try and elicit a response, please do not do that again.

The setting screen exists but the sensors cannot be selectively disabled yet.

**Comment by stbeep1** [comment]
> It is not appropriate to mention everybody you can think of to try and elicit a response, please do not do that again.
> 
> 
> 
> The setting screen exists but the sensors cannot be selectively disabled yet.

I apologize for that! But this is just unacceptable, collecting any data or sending any data should be opt-in only. Even if it’s sending data to my own HA server. And there is no way to opt-out on iOS, but you can opt-out on Android. Don't get me wrong, I love HA, and I am constantly supporting Home Assistant dev in different ways. I just want to know how can I opt-out of those iOS Sensors? Thanks for that.

**Comment by zacwest** [comment]
I understand. It is currently not possible to disable some sensors in the app, specifically those not governed by a system-level privacy setting. You can disable the entity on the HA side to disregard the sensors themselves, but the app will still be sending them up.

**Comment by stbeep1** [comment]
> I understand. It is currently not possible to disable some sensors in the app, specifically those not governed by a system-level privacy setting. You can disable the entity on the HA side to disregard the sensors themselves, but the app will still be sending them up.

I want to fully disable sending any sensors data to HA, not just disregard them! Is that possible?
