### ISSUE TITLE
Request_location_update Notification Issue

### ISSUE THREAD

**Issue by PopNFreshIsMe** [home-assistant/iOS#370]
I’ve been trying to use request_location_update in my notification to trigger a location update on demand but I’m having trouble getting it to work in both version 1.5 and the 2.0 beta.

In version 1.5, I’ve only had luck getting it to work when the app is actively open on the phone. While in version 2.0 (build 58), it works with the app closed as long as it’s running in the background. If the app is force closed, it stops responding to the request_location_update notifications.

I’m not sure if this is a limitation of iOS itself or a bug in the app that could be fixed. Other notifications continue to work fine even with the app force closed so maybe the request_location_update command can’t be passed to the app unless it’s actively running in the background. I do have Background App Refresh enabled for both versions. 

While it would be great if this worked in both versions, the main purpose of this post was to get it fixed in the 2.0 beta. Any insight on this would be appreciated and great work on the app!

**Comment by Uksa007** [comment]
I can confirm I get the same results with V1.5.1 of the app as PopNFreshlsMe gets with V2.0

e.g.  It works with the app closed as long as it’s running in the background. If the app is force closed, it stops responding to the request_location_update notifications. Normal message type Notifications still work(pop up) when the app is forced closed.

Any progress being made to resolve this, would be great if this worked when the app was force closed.

**Comment by zacwest** [comment]
Force-quitting the app will prevent any future push notifications from launching the app in the background, so this is expected behavior. It's worth noting that 'running in the background' is not the default state for apps not in the foreground. iOS aggressively suspends apps that are not being used; force-quitting a suspended app only makes it take longer to launch the next time you open it.
