### ISSUE TITLE
Connection Preferences for "Internal URL" override when not on local network

### ISSUE THREAD

**Issue by jcollas** [home-assistant/iOS#371]
When using Home Assistant Companion beta 2.0.0 (58)

If I set an internal URL, 

1. It's very difficult to reset back to empty
2. Whatever wireless network I'm on is automatically added to the SSIDS list, so when I'm away from home, the internal URL takes precedence and I can't connect to HA when on Wifi.

**Comment by robbiet480** [comment]
Focusing just on the SSID bit for a moment, the default value when you go through onboarding is the current SSID you are connected to. You should be able to delete that SSID and add a new one in settings after onboarding. Hitting the add button does default to the current SSID (if one exists) but you can just delete the contents.

**Comment by jcollas** [comment]
Here’s the specific use case:

1. at home, connected to home wireless network.  Set the internal url to the HA url.  SSID shows the home network.
2. go to work.  I see the work SSID added, and now I can’t connect to the internal URL (it only works from home).
3. Try to delete internal URL or work SSID, both show back up again.
…
x. Somehow, the internal URL or SSID stays removed, and I can connect via NabuCasa.

**Comment by josh-m-sharpe** [comment]
New to HA here, but I've noticed a similar issue.   This all happens while my device is connected to my home wifi:

1) Open Connection settings
2) See that External URL is filled in with internal IP Address (this seems odd)
3) Click on Internal URL and set the IP:Port & SSID
4) Go back to External URL and remove it.
5) Back out of the config/settings pages to the overview/dashboard
6) Kill App (double-click home and swipe up)
7) Re-open app, navigate to Connection page

At this point we're back to square one.  The External URL is filled in, but the Internal URL is blank - the opposite of what I'd expect to see.

**Comment by zacwest** [comment]
I believe most issues with URL editing have been resolved with recent settings changes.
