### ISSUE TITLE
Onboarding breaks when opening login url

### ISSUE THREAD

**Issue by joiglifberg** [home-assistant/iOS#374]
The login window opens a non-existent url, somethingbroke.fake even though a correct external url was entered in the previous step. 
![AB1F3506-7B23-41D6-A0A2-C4C7D197A2AF](https://user-images.githubusercontent.com/640695/57829227-920f4580-77ae-11e9-8ed7-bdf82d3aa446.png)
![C1053786-52ED-4BA2-B091-593CC4050838](https://user-images.githubusercontent.com/640695/57829228-92a7dc00-77ae-11e9-833f-02e5f46a31c5.png)
![578E02A4-1D19-40CB-B129-60B144349C53](https://user-images.githubusercontent.com/640695/57829229-92a7dc00-77ae-11e9-88c4-7273a7e80a21.png)

**Comment by robbiet480** [comment]
You set up manually I assume?

**Comment by circuuz** [comment]
Yes, I set up manually.

**Comment by robbiet480** [comment]
@circuuz Was there a reason you couldn't do automatic setup?

**Comment by circuuz** [comment]
@robbiet480 Yes. The automatic search doesn't find my Home Assistant instance on my network.
I'm not sure how the search works but somehow I guess it's because I run Home Assistant on a Synology NAS.

**Comment by nnmalex** [comment]
I’ve got the same issue on latest build.

**Comment by AndrewBucklin** [comment]
I've got the same issue on build 61 while on cellular LTE when manually entering my external HASS URL (which is behind Traefik reverse proxy, which handles SSL termination).

**Comment by robbiet480** [comment]
@AndrewBucklin Mind iMessaging me your URL so I can see what's going on? I don't need any authentication info, just the URL. Interested in your situation specifically because i've gotten reports from others about possibly being too strict on SSL... My iMessage is me@robbiet.us. Thanks!

**Comment by 6a61636b** [comment]
I have the same issue with the latest build (62).
Let me know how I can help

**Comment by loonysup** [comment]
I’m having the same issue with build 62 on ios13

**Comment by jmheist** [comment]
same with issue latest build as of today

**Comment by anthonyjestin** [comment]
Same issue here, but I want my external to be my Nabu Casa.  It finds my local no problem but then wants to take me to somethingbroke.fake and then wants me to enter an external URL in a pop up when I close it, but everything I have read says that I shouldn't be manually typing in a nabu casa remote url

**Comment by cansas** [comment]
I get this error when allowing auto discovery of the internal URL. iOS 12 and 13.

**Comment by estebanpapp** [comment]
I get this error as well.

**Comment by AndrewBucklin** [comment]
@robbiet480 - Sorry, just saw your post to me. I have iMessage’d you my HA URL.

**Comment by zacwest** [comment]
I believe these class of issues have been resolved.
