### ISSUE TITLE
iPad without cellular function tries to send location updates

### ISSUE THREAD

**Issue by astrandb** [home-assistant/iOS#381]
iPad without cellular function tries to send location updates also when it has no contact with Internet. When driving with an iPhone in my pocket and the iPad on the passenger seat I noted that the iPad notified me of failure more or less every kilometer.
IMHO it should not even try to send a location update when it has no contact with Internet.

**Comment by zacwest** [comment]
The notification that this is talking about no longer occurs (it's commented out as of 8e79550).

Although it is clear that sending a network event when we think we have no connection isn't great, there's a few gotchas here:
- we could be wrong about whether we have a connection -- Apple's Reachability APIs are more heuristics than omniscient
- we can move to a system where we can queue up network requests to be executed in the future when we do have network. For this one it's important to remember to cancel any pending requests when sending new ones, but it should improve the world a lot.
