### ISSUE TITLE
Zone Enter Event failed because no SSID is available

### ISSUE THREAD

**Issue by Shirk** [home-assistant/iOS#397]
The current beta fails to update my location when entering a zone without being connected to WiFi (mobile data and access to Hass is available).

The event log shows a failed update because no SSID is available:
![Image](https://i.imgur.com/lPsC3n7.jpg)

**Comment by zacwest** [comment]
This log is misleading - it's not actually failing for that reason, it's just including it for more information.

This log is removed in 2020.3+ with the In-Development Updating setting and in 2020.4 entirely.
