### ISSUE TITLE
Many location-setting errors when using internal URL and outside home

### ISSUE THREAD

**Issue by gregschwartz** [home-assistant/iOS#400]
On Beta, using a HA URL of 192.x.x.x, it is correctly recognized as Internal:
![internal url](https://user-images.githubusercontent.com/206568/59741580-38bc8b00-9220-11e9-97e1-d8d11e1ca977.PNG)

But when I'm outside my home I get these error notifications every few miles (depending on driving or walking speed, sometimes every 5-10 minutes):
![error](https://user-images.githubusercontent.com/206568/59741582-38bc8b00-9220-11e9-8374-7deb32a4c363.PNG)

To solve it I tried turning off the location notifications:
![IMG_1428](https://user-images.githubusercontent.com/206568/59741579-38bc8b00-9220-11e9-9d03-c54d391fe118.PNG)
Same issue though.

I've also turned off "Significant location change", because I'm pretty sure that's what should be causing the HA app to try and report location. But I still get the error notifications.
![IMG_1429](https://user-images.githubusercontent.com/206568/59741578-3823f480-9220-11e9-82ee-8f6451b34626.jpg)

I think at the simplest, the expected behavior should be one of the following:
- if internal URL and not on WiFi, don't show location reporting errors (easiest fix)
- if internal URL and not on WiFi, don't report Significant Location Change (better for battery life)
- if internal URL, disable the option to report Significant Location Change and whatever other options are triggering the large number of errors

Thanks!

**Comment by SeanPM5** [comment]
The location update error notifications were turned on in order to get more feedback from beta testers. These were previously occurring before in the background and just not being reported to the user.

My understanding is that they'll either be disabled or have an opt-out toggle in one of the upcoming builds.

**Comment by gregschwartz** [comment]
Yeah... really really need to have that be disabled for **internal** URLs,
since there's never a reason to hit them outside WiFi. It's to the point
that I'm going to have to turn off notifications entirely, they're so
spammy ><

**Comment by robbiet480** [comment]
@gregschwartz The 503 notifications are an actual error though. Something is broken in your setup. Furthermore, location updates also cause sensor updates, so you should know if the updates are failing even if you don't care about location because I assume you care about sensors.

Sean is right, they have been disabled in build 62 which should be out late tonight.

**Comment by gregschwartz** [comment]
Hmmm. What's the best way to debug the error? Given that the IP is a 192,
and it's only happening when I'm no longer on WiFi, I have no idea what
server could be returning a 503 Service Unavailable error. Unless that's
actually coming from the HTTP library that the app uses?

>

**Comment by robbiet480** [comment]
The 503 comes from your server(s), not the library. Is your remote UI turned on? In the build you have the app will always connect via remote UI if we detect cloud is enabled in your setup, even if your remote UI is off.

**Comment by gregschwartz** [comment]
It was on, but I've since turned it off. Perhaps that's the source of the
problem?

**Comment by robbiet480** [comment]
Possibly. Usually having it off throws a SSL error but it can be a 5xx under certain circumstances. Try turning it on and see if the notifications go away.

**Comment by gregschwartz** [comment]
Can't, I already let my trial lapse.

I'll try deleting the iPhone app and then setting it up again. Then it
should know it's always internal only... I hope.

**Comment by robbiet480** [comment]
Make sure cloud is entirely disabled before setting up again.

**Comment by gregschwartz** [comment]
Now it's broken even further :( Even after multiple reinstalls, it shows this:
![IMG_1472](https://user-images.githubusercontent.com/206568/60380251-3368f880-99f7-11e9-8a78-bb3c0a268755.PNG)

**Comment by zacwest** [comment]
Nearly all of the connection handling has changed in the few years since this issue was created. If you are still experiencing an issue, please create a new one.
