### ISSUE TITLE
Resetting app should remove HA integration/sensors

### ISSUE THREAD

**Issue by joshtbernstein** [home-assistant/iOS#407]
When resetting 2.0.0 (62) and possibly earlier, the integration and sensors are left in HA. This is an issue as when you reconfigure the app, it duplicates the integration and sensors.

**Comment by TomBrien** [comment]
This is a known issue. For know please follow follow the instructions [here](https://companion.home-assistant.io/en/next/troubleshooting/beta-cleaning). I believe some front end work is required. This will be addressed before release

**Comment by dummptyhummpty** [comment]
@TomBrien Ah, sorry, I did a search and just wanted to make sure you were aware. As long as it's going to be addressed! Should I close this out?

**Comment by TomBrien** [comment]
Hi. #612 fixes the duplication of sensors. Now if you logout/reset the app and then set the app back up it will use the same sensors. Can we close this now?

**Comment by TomBrien** [comment]
Closing this as stale. Let me know if you think the current resolution isn't right.
