### ISSUE TITLE
Status bar doesn’t match theme if rgb() values are used instead of hex values

### ISSUE THREAD

**Issue by vandalon** [home-assistant/iOS#412]
Hi,

When changing themes, the status bar change to a white-ish color and I can't seem to change it. Any advise would be appreciated :)

![IMG_5C9EF76F34FC-1](https://user-images.githubusercontent.com/3370317/60396827-869d9100-9b46-11e9-9d88-b69bad2de3a5.jpeg)

**Comment by TomBrien** [comment]
Hi Vandalon,

You need to use `front end.set_theme` have a look at the instructions [here](https://companion.home-assistant.io/en/troubleshooting/setup#the-ios-status-bar-top-bar-with-cell-wi-fi-strength-does-not-match-my-theme). I’m going to close this for now. If that doesn’t work just post back on this issue and I’ll re open.

**Comment by vandalon** [comment]
This is what I do :)

**Comment by vandalon** [comment]
This is after execution:

![IMG_F93F360C5A51-1](https://user-images.githubusercontent.com/3370317/60398515-78a53b80-9b59-11e9-9db2-af57231e2b2e.jpeg)

**Comment by SeanPM5** [comment]
First I would recommend pulling down to refresh after setting the theme. In some very rare cases it doesn't update everything in real-time until you refresh first. You could also try force quitting the app after setting the theme to force it to update. 

The iOS app status bar is themed using the `primary-color` value of your Home Assistant theme. From the screenshot you've posted, it does not appear to be the correct color values for Midnight. Is it a customized version? Can you copy and paste the `primary-color` line from it? For example:

```
midnight:
  # Main colors
  primary-color: '#5294E2'
```

The other thing that might possibly be interfering, it appears that you're using Compact Custom Header to minimize the height of the status bar. If none of the above things work, you could try temporarily disabling Compact Custom Header to see if that was causing the issue.

**Comment by vandalon** [comment]
Hi,

I figured it out.
Indeed, i altered the midnight theme, the reason it did not work, I used rgb(x,y,z) instead of #aabbcc. The app doesn't seem to understand this, so chaning back to #something everything is working again.

Cheers, and thanks for the help!

**Comment by TomBrien** [comment]
Thanks for working that out. I think I’d call that a bug to be honest. So let’s leave this here for now. Cheers again

**Comment by TomBrien** [comment]
Just a note that this is still true in 2020.2

**Comment by zacwest** [comment]
There exist a huge number of variations that need to be parsed:

- `rgb` with integer (0-255) values
- `rgb` with percentile (0-100%) values
- `rgba` with integer (0-255) values
- `rgba` with  percentile (0-100%) values
- `hsl`
- `hsla`
- `color` with transforms of the colors which is coming up in CSS

Ideally, now that we pull the color from the style [in JavaScript](https://github.com/home-assistant/iOS/blob/c6cac21577408cfe10a4d8da014182908d1f93ed/HomeAssistant/Resources/WebSocketBridge.js), we could use some kind of built-in mechanism that's able to canonicalize the color. But…it really doesn't seem like there is one.
