### ISSUE TITLE
Loading frame is interrupted

### ISSUE THREAD

**Issue by Martinvdm** [home-assistant/iOS#416]
IOS version : 12.3.1
HA App version: 1.5.1
HA version: 0.94.4

Using Traefik proxy, but other phones are not having this error, so it seems not proxy related.

Many times there is an error on the app as shown below.
"Loading frames is interrupted"

After closing the app and reopening, all is logged in, shown, and functioning just
![IMG_3805](https://user-images.githubusercontent.com/1952661/60831421-cce39780-a1b9-11e9-957c-6c011c62220b.jpeg)
 fine.

**Comment by TomBrien** [comment]
Hi is this still an issue. If so can you see if the message has changed. I've searched both the app and frontend translations and can't find "Laden van frame is onderbroken" which makes me think this is being generated elsewhere
