### ISSUE TITLE
Error sending significant location change - In Airplane mode

### ISSUE THREAD

**Issue by xstrex** [home-assistant/iOS#420]
Recently while on a backpacking trip, I put my phone into airplane mode, to conserve battery, like always. About every 10mins I received the following message:
Error sending significant location change lo...
The operation couldn't be completed.
(kCLErrorDomain error 2.)

While this was happening, I tried disabling the notification via the app configuration -> notifications -> Significant location change notification, but this did not prevent the notifications from appearing. Eventually I had to completely disable notifications in iOS, for the remainder of my trip. 

I'm not surprised I got this error, as I was in airplane mode (duh). Would be great if the app could detect that, and stop attempting to send data, which will never get there. In addition, there's no good reason to alert me every 10mins.

Please let me know if you need logs, or any additional details.
Also, this was in Beta version (61).

Cheers

**Comment by TomBrien** [comment]
Hi appreciate this is almost exactly a year ago but do you happen to know what was disabled in your airplane mode. Was Wi-Fi or bluetooth still active? I believe GPS is never turned off by airplane mode in iOS

**Comment by zacwest** [comment]
The notification that this is talking about no longer occurs (it's commented out as of 8e79550).

**Comment by zacwest** [comment]
Merging this into #381
