### ISSUE TITLE
Editing urls internal external 

### ISSUE THREAD

**Issue by glmnet** [home-assistant/iOS#425]
I complain about the UI. 
Validation is quite aggressive. Eg. If you don’t prefix http it will just fail and reject your input. It’ll be nice if could tell why it doesn’t like. 

But for the love to the users , please please please don’t clear the input field or rollback to the value it had. It is not always a pleasure to write a url on a field box and see the message box say he didn’t like it and see it vanish on front of you. 
If somebody is writing some other url that is because the previous one did not work most likely. 

Thanks. This is a really nice app.

**Comment by robbiet480** [comment]
Is this still an issue? Let me know and I will reopen this. Thanks!
