### ISSUE TITLE
Unable to register font 'Material Design Icons' beacuse URL was nil!

### ISSUE THREAD

**Issue by jayfbeast** [home-assistant/iOS#433]
Good day,

I'm really new with Xcode and I've been trying to get the code working so I could use the Simulator in order to develop my Lovelace interface without needing to buy an iPad right now. 

I,ve done all the steps from the Readme and when executing Home Assistant in the iPad emulator, the app crashes saying "Unable to register font 'Material Design Icons' beacuse URL was nil!" . That error message came from IconDrawable.swift, line 173. 

I've manually registered the ttf file in MacOS and it still doesn't work. I've registered that one ./Tools/MaterialDesignIcons.ttf

I,ve also manually ran fontname.py in order to rename the Font Name so it would work with Iconic. (according to content of: ./Tools/BuildMaterialDesignIconsFont.sh)

Pretty sure it is a basic thing... but like I said, I'm pretty new with Xcode (but not in the programming world, though).

I'm running the last version of Xcode available publicly (10.3) and Simulator 
Any help would be greatly appreciated!

**Comment by jayfbeast** [comment]
In fact, the application crashed at line 162 of IconDrawable.swift: Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)

Output shows: Unable to register font 'Material Design Icons' beacuse URL was nil!
Iconic was compiled with optimization - stepping may behave oddly; variables may not be available.
(lldb)

**Comment by jayfbeast** [comment]
I'm running Mojave... too. Don't know if it helps.

**Comment by jayfbeast** [comment]
I found the fix myself. The file MaterialDesignIcons.ttf was NOT added to the list "Copy Bundle Resources" in the Build Phases of the HomeAssistant target. See screenshot.
![Screen Shot 2019-08-31 at 2 33 34 PM](https://user-images.githubusercontent.com/54486962/64067800-88dea300-cbfc-11e9-8fd5-13f5bc920e37.png)

**Comment by zacwest** [comment]
I believe this should work now. You may need to run `bundle exec pod update Iconic` to trigger an update.
