### ISSUE TITLE
Broken in-app documentation links

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/iOS#434]
There are currently five places with outdated or missing "help" links. Some were never hooked up in the first place, other URLs broke after the the "next" version of the docs was made the "current" version, etc. This issue is to keep track of these.

1. ~~App Configuration > About > Documentation links to the old docs (https://www.home-assistant.io/docs/ecosystem/ios/) rather than the new companion URL.~~
2. ~~App Configuration > Actions links to https://companion.home-assistant.io/next/integrations/actions when it should be https://companion.home-assistant.io/en/core/actions~~
3. App Configuration > Apple Watch links to https://companion.home-assistant.io/next/integrations/apple-watch and the page no longer exists. 
4. ~~App Configuration > Shortcuts section: when making a "Fire Event" shortcut or a "Call Service" shortcut, the help button is not linked to anything yet, tapping it does nothing.~~
5.  App Configuration > Notifications > Categories > in-app creator, the help button is not linked to anything yet, tapping it does nothing.

**Comment by TomBrien** [comment]
Point 3 was fixed via home-assistant/companion.home-assistant#249.

Fixing point 5 now
