### ISSUE TITLE
Feature Request: Custom Request Headers

### ISSUE THREAD

**Issue by keatontaylor** [home-assistant/iOS#439]
I'd like the ability in the connection page of 2.0 to be able to define custom additional headers that can be added to the webhook and other calls to HA. I understand this likely isn't possible to append these headers for the webview, but that isn't an issue in the case I have in mind.

Essentially my HA install is behind a CloudFlare proxy utilizing cloudflare access. This allows for apps to request a verification step, usually via email before allowing a request to the real site. This works fine for a web view since the captive portal is displayed and the user can input the correct info. 

However, it does not work for the webhook messages back to HA that do not include the cloudflare header and so I'd be nice to be able to add these headers manually such that things like actions, push notification actions, and location updates work as intended.

https://developers.cloudflare.com/access/setting-up-access/securing-applications/ 

Above is a link for more info on CloudFlare access.

**Comment by dejanzelic** [comment]
+1 for this. I too am in the same boat

**Comment by jtscott** [comment]
+1 would like to use cloudflare access tokens for this as well
