### ISSUE TITLE
Onboarding fails for split horizon DNS configurations

### ISSUE THREAD

**Issue by ntompson** [home-assistant/iOS#448]
I seem to have discovered an issue with the on boarding process that kills remote access for split horizon DNS configurations.

### The problem
While grappling with and before discovering #445, I completely removed the 2.0.0 beta companion app and then reinstalled it. This meant I had to walk through the on boarding process again. I did this while connected by WiFi to my LAN and all appeared well. I then left home and discovered that the app couldn't connect over cellular.

A little investigation revealed that the on boarding process configured me with:
- Internal URL = https://home.mydomain.tld
- External URL = home.mydomain.tld

It appeared to fail to connect on cellular because of lack of "https://" on the external URL (?). I attempted to manually edit the external URL, but received an error message about invalid URL format. 

Subsequently, I reset the app, triggering the on boarding process to recommence, but this time did it connected to cellular, and it populated with:
- Internal URL = (blank)
- External URL = https://home.mydomain.tld

Now cellular connectivity works, as does WiFi to my LAN. The internal URL remains blank, even while back at home on WiFi.

### The issues
So I think there are two issues:

- there is something screwy around the way the onboarding process determines the external URL when on boarding from the LAN
- the external URL text box has an issue with accepting "https://" as part of the URL

### My setup
Things to know about my setup:
- I'm not using Nabu Casa to provide remote access
- I am using an nginx based reverse proxy to provide remote access and https / certificate handling
- My certificate is provided by LetsEncrypt, which is automated by a different local server than my home assistant box
- I have a dynamic DNS setup that keeps my public A record for my `home.mydomain.tld` up to date whenever my ISP changes my IP address
- I have a local DNS server configured for split horizon such that, when on the LAN, `home.mydomain.tld` resolves to the local nginx reverse proxy so that I can use the same URL whether on the LAN or out in the wide world

**Comment by olbjan** [comment]
The onboarding process does not determine the external URL at all (kinda hard to do). I have already created a possible workflow around making this more reliable but it requires some kind of cloud service to check for external connectivity. See #350

I've tried and concur that there is an issue around adding the external URL later, this is definitely a bug.

**Comment by ntompson** [comment]
Interesting comments.

I don't know the logic or how it's done, but I can absolutely confirm that the external URL is auto-populated during the on-boarding process. Per my notes, if I onboard while connected to the LAN, the process auto-discovers my local Hass instance and populates both internal and external URL as described. That is, I end up with:

- Internal URL = https://home.mydomain.tld
- External URL = home.mydomain.tld

**Comment by olbjan** [comment]
This should be fixed(-ish) now in b68. 

On iOS 13 the app needs location access before being given the wifi ssid. Without this internal url could not be consttucted properly. The current fix now applies an autodetected ha instance only to the external url field and a setup with split urls will need to be set up manually as was the case in 1.5.1.

-Jan

**Comment by ntompson** [comment]
So I think we are part of the way there in build 68. As you say, the external URL is being correctly auto-populated during on boarding, and I can manually enter the internal URL afterwards. But during reinstallation and before I triggered the on boarding process again, there still seemed to be some odd error messages when entering an https:// URL into a blank external URL box. 

Maybe with the recent adjustments to the on boarding process it doesn't matter, but it does look like there is something not quite right with the text box validation applied to the external URL box.

**Comment by olbjan** [comment]
Here is some documentation on networking recommendations: https://companion.home-assistant.io/en/troubleshooting/networking

**Comment by TomBrien** [comment]
@olbjan do you know if this is fixed in the latest update

**Comment by olbjan** [comment]
I don't believe this has ever been an app issue @TomBrien

**Comment by TomBrien** [comment]
Ok in that case I think we can close
