### ISSUE TITLE
Beta crashes after onboarding in iOS 13

### ISSUE THREAD

**Issue by chimpy** [home-assistant/iOS#452]
Hello,

I have been using Beta 2.0 on iPhone 7 for a while now with no problems. After updating to iOS13, the Companion crashes every time I open it (I still receive notifications).

I decided to reset the Companion just in case, to no avail. The Companion almost completes onboarding, then crashes. It crashes just at the moment we might expect all the circles to tick.

Is there a solution?

**Comment by TomBrien** [comment]
Which version build are you running. This was a known issues for HA 0.100+ builds before the current build 68. Best suggestion for fixing would be to update to b68. If you are getting a HA API Manager Unavailable, in HA delete the Mobile App Integration and then delete the iOS App and reinstall.

**Comment by lancelon** [comment]
Basic question - sorry - where is the repo for the 2.0 b68 release? I can't find it, even by switching to [the beta branch](https://github.com/home-assistant/home-assistant-iOS/tree/beta) - it shows the last commit being in June - so that can't be right? Cheers!

**Comment by TomBrien** [comment]
The release version is out now. Does this problem still exist?

**Comment by TomBrien** [comment]
As there's been no action on this I'm going to close for now. If you still have a problem please post back and let us know
