### ISSUE TITLE
Notification delay when using image and/or camera in notification

### ISSUE THREAD

**Issue by vandalon** [home-assistant/iOS#453]
After some testing (with the help of @TomBrien) it seems that notification in the IOS 2.0 beta app containing images or a camera feed are delayed up to 30 seconds (maybe even more). This is especially an issue when using notification with a camera and a doorbell :)
Tom mentioned that notification containing just text are near to instant. 

My girlfriend still uses the 1.51 app and the same notification are close to instant on her phone.

**Comment by vandalon** [comment]
#362

**Comment by olbjan** [comment]
I can't reproduce this, I also use image attachment notifications with camera stream and it takes around 3 seconds for the notification to reach my phone from being triggered.

One thing to note is that 1.5.1 and 2.0 use very different backends for the push notifications. On 1.5.1 I believe a more or less custom service on top of AWS is used whilst 2.0 has moved push notifications to Google Firebase Cloud Messaging. So the app itself may not be the best place to start comparing the two.

**Comment by TomBrien** [comment]
Hi is this issue still present?

**Comment by TomBrien** [comment]
Closing as stale. If this is still an issue just let us know on this post and we can re open
