### ISSUE TITLE
Log out experience

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/iOS#458]
When you go to user profile page (your initials in the sidebar) and tap Log Out button:

- You are logged out immediately without any warning / confirmation prompt. Which to be fair is more of a frontend issue, opened an issue here for that: https://github.com/home-assistant/home-assistant-polymer/issues/4109)
- You then get a blank white screen with red error "HA API Manager is unavailable" which is not that user-friendly. Most normal people won't know what that means...
- **Biggest problem is that all connection settings in the app get wiped out. Leading to numerous issues listed below.**
- There is seemingly no way to set up Home Assistant Cloud because that's only detected during the onboarding process.
- When I manually typed in http://hassio.local:8123/ to internal URL field, it told me "Cant build API URL" (screenshot below)
- If I typed anything in external URL field, I also get an error about not being able to remove external URL because HA Cloud is not set up (screenshot below). Even though there's no way to set up Cloud as mentioned above.

When you log out of a desktop browser it just revokes the refresh token and brings you back to the login screen. Here, it practically tanks the entire app and there's no easy way to recover.

In the end I had to delete the app, go "[scorched earth](https://companion.home-assistant.io/en/troubleshooting/beta-cleaning)," and run the onboarding again. I think this is kind of a poor user experience that can hopefully be improved upon somehow. Confirmation prompts, more clear error messages, etc...

For starters one idea would be that if there's no connection details filled out, don't display the blank page with confusing "HA API Manager is unavailable" error but instead bring the user right to the App Configuration -> Connection screen.

![image](https://i.imgur.com/My6UjzG.png)
![image](https://i.imgur.com/m5QVj3o.png)
![image](https://i.imgur.com/RIGDMEh.png)

**Comment by manonstreet** [comment]
I noticed the same issue when testing CCH with different user exceptions.  When switching between logged in users by clicking Log Out, it places the app in an unrecoverable error state.  However uninstalling isn't necessary as noted by SeamPM5.  You can still go into App Configuration and hit the Reset button for the app to onboard you again.  Nonetheless, this is not an ideal way to support switching users :)

**Comment by zacwest** [comment]
This was fixed by #612

**Comment by SeanPM5** [comment]
Fantastic, thanks for all your contributions! will close the other threads too.
