### ISSUE TITLE
Custom connections forgotten

### ISSUE THREAD

**Issue by MartinTerp** [home-assistant/iOS#459]
Hi

I have my Home Assistant behind a proxy, to limit access so not everyone can connect to it.
So my url to my ha is: https://ha.domain.com (both for internal and external)

When i open my app, and input this in connection field (for both internal or external, or just external, dosnt matter)
it works fine, until i re-open the app, then it seems like it have autodiscovered my ha, and put in hostname of my server, including port, then i cant use the app until i change it back  to https://ha.domain.com

Is it possible that if you override the default, autodiscovered connections.
It dosnt change back?

**Comment by TomBrien** [comment]
First guess, make sure `base_url:` in `configuration.yaml` is set to `ha.domain.com` with no protocol or port

**Comment by MartinTerp** [comment]
base_url is set correct, https://ha.domain.com

**Comment by zacwest** [comment]
I believe issues around storing connection information changes are now resolved.
