### ISSUE TITLE
Removed mobile_app integration in HA, not reenabled through the app

### ISSUE THREAD

**Issue by eavanvalkenburg** [home-assistant/iOS#466]
Hi,

I noticed I had about 4 different Mobile App integrations because of the Beta app and reinstalling and relogging in and wanted to clean that up and get the names back to something without _2,_3,_4. And I ran into an issue then that the device tracker didn't work anymore so also decided to delete the active mobile_app integration (and rebooted HA), expecting that I could then just open the app, it would detect that is was gone and reinstall it fresh, but it didn't, tried logging out, and finally reinstalled the app to get back to the onboarding flow that does reinstall the mobile_app component, this was a really messy experience and if someone accidentally deletes their mobile app integration they would go through the same, which is not good. An easy solution would be a button in the app to wipe and re-onboard.

Thanks for the great work overall though!

**Comment by TomBrien** [comment]
This sounds like it was a pain. What I think you’re saying is needed (and I agree with) is:

- When app opens check the related integration still exists
- If it does run as normal
-  If it’s been deleted, reset all local configuration and reload on boarding

Sound about right

**Comment by eavanvalkenburg** [comment]
sounds perfect!

**Comment by zacwest** [comment]
Fixed by #612.
