### ISSUE TITLE
Action functionality

### ISSUE THREAD

**Issue by niccolobusato** [home-assistant/iOS#469]
Would it not be more convenient and useful to use the scenes instead of "actions" and possibly be able to select which ones to show?

also the import option as notification categories would be very useful.

I find the use of actions a duplicate of the scenes and very complicated

**Comment by TomBrien** [comment]
Personally actions are what I use the most. I would not want them restricted to scenes only. You could easily set up an action to activate a scene. The current implementation is much more flexible.

I would like to be able to import the actions from HA so I don’t have to recreate on each new app install.

**Comment by TomBrien** [comment]
I'm going to close this, Actions I believe are more powerful as you can trigger any automation in Home Assistant with them. I fully agree on the second point. That is covered by ##494 so I'll close this in favour of that one
