### ISSUE TITLE
iOS app 2.0, unable to modify device tracker name

### ISSUE THREAD

**Issue by elsom25** [home-assistant/iOS#479]
Running into a problem getting device tracking to work.

My iOS device has name made of only emoji's (:sparkling_heart: :sparkles:), which doesn't appear to import correctly. The name that it loads by default in integrations is simply: `device_tracker.`:

![image](https://user-images.githubusercontent.com/542544/69690658-8aecbc80-109a-11ea-8381-bee123d38309.png)

Further, if I attempt to update it to a new name, both to simplify my `configuration.yaml`, and to maybe make it work at all:

![error](https://user-images.githubusercontent.com/542544/69690586-5547d380-109a-11ea-97dc-e7324bc0a408.png)

From the logs:

```
Error handling message: Entity ID device_tracker. is an invalid entity id for dictionary value @ data['entity_id']. Got 'device_tracker.'

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 96, in async_handle
    handler(self.hass, self, schema(msg))
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: Entity ID device_tracker. is an invalid entity id for dictionary value @ data['entity_id']
```
What other information would be useful to attach to the ticker, or there any obvious next steps I've missed?

**Comment by Crpnl** [comment]
i think i have the same issue. I just got a fresh install and tried to connect with the IOS app to add it as a device tracker. 
After the first steps and getting to the step (after adding the address and granting permissions) where its sets up everything. it hangs at "Intergration Created" and i get i "Unacceptable: 400" error.

Looking into my Entity list i see it created multiple device.trackers which i cant edit or remove (as described above) I also have my device name set up only with 1 emoji.
So i think this is the issue, that it doesnt accept or recognizes emoji's as device naming.

**Comment by benlbrm** [comment]
I've also same error with specials characters in the Iphone Name ( / . )
This create device_tracker than cannot be used and deleted

**Comment by TomBrien** [comment]
Can anyone confirm if this is still the case. I am able to edit and delete device_tracker entities. We will find a way of addressing emoji only phone names. Just want to know if the main problem here is fixed

**Comment by zacwest** [comment]
In addition to Tom's PR above which addresses the generated name being blank, you can change the device name locally as of #676.
