### ISSUE TITLE
Multiple trackers / Battery Level / BSSID in entities list

### ISSUE THREAD

**Issue by amamenu** [home-assistant/iOS#482]
There are multiple trackers from one device, 

**Example:**
device_tracker.iphone
device_tracker.iphone_2
device_tracker.iphone_3

I have deleted the `.ios.conf` and restart the service & re-login the app, but also like this.

**Comment by amamenu** [comment]
And I tried to deleted them from entities list, then reboot the service, they listed in list again.  What is going on of this?

**Comment by TomBrien** [comment]
Looks like you went through onboarding 4 times. Please delete the four `mobile_app` integrations in Home Assistant Configuration>Integrations, then reinstall the app and go through onbaording again. Also you can follow the steps [here](https://companion.home-assistant.io/troubleshooting/beta-cleaning) but deleting the integrations should be fine

**Comment by TomBrien** [comment]
This is fixed in #612 :)
