### ISSUE TITLE
Fast iBeacon detection broke with v2.0?

### ISSUE THREAD

**Issue by artaxx81** [home-assistant/iOS#488]
Hi there,

because either the GPS Update nor the SSID Update is working for me I have built an iBeacon with my RPi for presence detection.

Prior version 2.0 this iBeacon worked perfectly (thank god because no other method was fast enough to turn on the light fast enough)

Since v2.0 this "sharpness" is also gone like the GPS sharpness with iOS 13.

Do I have to switch to door contacts or do you have a solution for the iBeacon "reaction problem"?

I am on Home Assistant 0.102.2.

I honestly do not have the muse to find another constructive way to detect presence due to breaks caused by Apple or the HA iOS Companion App.

I hope honestly that you can help.

Thank you very much!

Greets from Germany
Daniel

**Comment by olbjan** [comment]
Hello Daniel,

I also use iBeacons and as far as I know or have noticed there has been no change in behavior between 1.5.1 and 2.0.

You may want to check the app log if there was a problem reporting to HA when the iBeacon was seen.

**Comment by zacwest** [comment]
Please give 2020.3+ a try and see if there's still an issue with the speed of the iBeacon updates -- I am not aware of anything that would slow it down now, other than network connectivity issues at the moment of detection, which will be resolved by background network updates in #744.
