### ISSUE TITLE
Phone call sensor

### ISSUE THREAD

**Issue by maxperron** [home-assistant/iOS#498]
Hello,

I wonder if it's possible to have a sensor that is telling if the phone is receiving a call, in a call and ending a call. I think Apple doesn't allow this, but I'm not sure.

This way I could have an automation that pause my chromecast when I receive a call.

Thanks!

**Comment by TomBrien** [comment]
I thought about this a little while ago and had a look at the SDKs and I think it is possible. However, the app only sends sensor updates with location updates and thus I’m not sure this would be reliable.

**Comment by TomBrien** [comment]
We had a discussion about this. It's seems we are unlikely to get the entitlement required to get call status while in the background and even if we were to, due to the way the sensors are updated it is probable such a sensor would not be of much use as the update is probably too infrequent. For those reasons, I will close this for now.

**Comment by bjackson** [comment]
Could the `CXCallObserver` allow us to get access to changes in whether a call is taking place? If this is the case and would be reliable, I'd be interested in dipping my toes in the water and creating a PR with this functionality.

https://developer.apple.com/documentation/callkit/cxcallobserver

**Comment by zacwest** [comment]
`CXCallObserver` manages the calls of the current telephony provider. For example, if HA had VoIP support, it would give the list of calls currently incoming or outgoing from the HA VoIP. It does not provide information about other calls.

**Comment by E020** [comment]
I don't have any developers skills so my 2 cents: when in a call I can open Spotify, but I'm not able to play Spotify on my iPhone. Spotify also pauses when a call is received/made. Isn't that something that is 'communicated' to (all) audio apps on the iPhone and could be the trigger? Just wondering...
