### ISSUE TITLE
The "App Configuration" menu item sometimes disappears

### ISSUE THREAD

**Issue by bcmitri** [home-assistant/iOS#510]
Typically, main menu include a menu item for "App Configuration" and looks like this:
![image](https://user-images.githubusercontent.com/53234043/70064899-aab34180-15c0-11ea-8cce-7fd57036e3c4.png)

From time to time, however, the  "App Configuration" menu item disappears and this is what I see:
![image](https://user-images.githubusercontent.com/53234043/70065010-ca4a6a00-15c0-11ea-9cff-de4860f45853.png)

Each time the issue appears, it can be corrected by pulling to refresh.

Hardware:
iPhone 7 with iOS version 13.2.3 and app version 2019.1
Raspberry Pi 2 Model B with Home Assistant version 0.102.2

It's also worth noting that I have the Compact Custom Header (version 1.4.9) add-in installed, but I don't know if that could is related at all.

**Comment by krissen** [comment]
I've also seen this. As far as I can remember, a force refresh (pull-down) did not fix it, nor did a force restart. Resorted to force restarting yet another time, and quickly pressed the orange cog. 

Later at some point, the app configuration -button returned, and has remained since. 🤷‍♂️

**Comment by TomBrien** [comment]
@bcmitri @krissen what iOS version are you running? I suspect this is a front end issue but it might not be

**Comment by bramkragten** [comment]
Can someone please check for errors in the console/log?

**Comment by krissen** [comment]
> @bcmitri @krissen what iOS version are you running? I suspect this is a front end issue but it might not be

iPhone X @ iOS 13.2.3.


> Can someone please check for errors in the console/log?

I'll do it if it happens again. Wrote it off as a odd glitch after it had re-appeared.

**Comment by bcmitri** [comment]
> @bcmitri @krissen what iOS version are you running? I suspect this is a front end issue but it might not be

iOS version 13.2.3.  I updated the original issue description.

**Comment by bcmitri** [comment]
This was related to the Compact Custom Header plug-in.
