### ISSUE TITLE
Group support for actions on Apple Watch

### ISSUE THREAD

**Issue by phaza** [home-assistant/iOS#512]
I love the actions feature, but it quickly gets a bit crowded on the watch if you have many actions. It would be very nice if you could build a hierarchy of folders/icons where you can put actions. Just having one level would make a big difference.

Personally I would have categories like:
* Lights
* Media
* Vehicle
etc.

**Comment by TomBrien** [comment]
I think just the ability to create top level folders would be best and most flexible
