### ISSUE TITLE
Actions fail on Watch when not connected to phone

### ISSUE THREAD

**Issue by ronaldheft** [home-assistant/iOS#516]
When attempting to use an action on the Apple Watch while connected to LTE, the action will not succeed. The button’s icon just spins and spins and the app needs to be force quit. When connecting back up to the phone, actions work again.

**Comment by TomBrien** [comment]
I would suspect this is because the watch app is not standalone but instead is simply passing commands to the phone. There is a plan to make it standalone but I agree this isn’t a great case. Perhaps when them phone isn’t connected it should be greyed out or disabled in some other way.

**Comment by olbjan** [comment]
Actually the actions give a nice audio and haptic feedback when there is no connection to the phone.

**Comment by zacwest** [comment]
These should (now?) be occurring successfully when the phone is not around, as long as the Watch itself has connectivity. There was an issue with this resolved in #862 where it wouldn't take care of the LTE case correctly.
