### ISSUE TITLE
Re-request motion permission when denied on first start

### ISSUE THREAD

**Issue by ronaldheft** [home-assistant/iOS#517]
It looks like when I first setup my app, I denied access to the motion data. None of the activity sensors were created (expected).

Now, I want to enable motion data and enable the activity sensors. It looks like there is no way to do that. If I go to `Settings > Privacy > Motion` there is no option to enable Home Assistant. I also do not see any options in settings to request motion data. It looks like the only way to grant access is to uninstall and reinstall the app.

Is there any way to grant motion permission after denied? If not, can we add a button to the settings to re-request that for users who deny it when first setting up the app?

**Comment by zacwest** [comment]
Fixed by #618
