### ISSUE TITLE
On Boarding improvements

### ISSUE THREAD

**Issue by XusBadia** [home-assistant/iOS#522]
Since the 2.0 version we now have an On boarding for setting up Home Assistant. The current process is this:
<img width="1778" alt="Screenshot 2019-12-26 at 11 09 30" src="https://user-images.githubusercontent.com/1400863/71471585-3db25680-27d0-11ea-9b75-57f3dd40277d.png">
_(the arrows show where the screens and buttons lead)_

I've come up with a few changes that I think could help speeding up the process. Some of my goals were:
- Remove steps. _I could only remove one screen since the process was already very simplified_.
- "Promote" the automatic discovery and "Hide" the manual configuration. _One of the goals is to make this accessible to as many people as possible, so everything should "just work". Since that's not always the case, we still need "Manual override", but it shouldn't be the option most users see at first._ 
- Retry scanning. _Currently, there's no way to try to scan again the network for Home Assistant instances._

And this is what I came up with. I also changed the design a bit.
<img width="1675" alt="Screenshot 2019-12-26 at 11 09 42" src="https://user-images.githubusercontent.com/1400863/71471787-d77a0380-27d0-11ea-9757-4fd819210f24.png">

As you can see, it's not a radical change, but I think it could help.

What do you think?

**Comment by olbjan** [comment]
You're making the assumption that the user is local to his HA install during onboarding. That is very often not the case and as such autodetection doesn't work. Manual setup should therefore be front and center ;)

**Comment by XusBadia** [comment]
That's true, but putting Manual Configuration front and center is not the solution. I believe that showing the user a screen to add a URL is not ideal, if we aim to make this available to everyone.
Maybe a solution would be to go tothe Scanning screen *only if* the user is connected to a Wifi Network. Would that work?

**Comment by olbjan** [comment]
First of all, it *is* available to everyone. That ship has sailed...

Your idea won't work as the app only knows about wifi after it has been granted location permissions. That changed in ios13. Onboarding used to work the way you describe in ios13 until it didn't any longer...

**Comment by XusBadia** [comment]
It is available to anyone, but I feel like it is still too difficult to get in for most people. I know just one or two people who'd be willing to set up home assistant manually. If it doesn't "just work" they feel like it's too big of a barrier to enter. And that's why it's so difficult, because something as complex and powerful as HA is not easy to "simplify".
I'd like to know what other think and maybe we can all figure out the best way to do this.
