### ISSUE TITLE
Only last notification gets delivered if device is in airplane mode

### ISSUE THREAD

**Issue by Fabenissimo** [home-assistant/iOS#527]
If the phone is in airplane mode and multiple notifications are being sent to the phone, only the last notification arrives once the device gets back from airplane mode.

**Comment by zacwest** [comment]
Unfortunately this is a restriction with Apple's Push Notification Service. Apple [documents](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/APNSOverview.html) it as:

> Apple Push Notification service includes a Quality of Service (QoS) component that performs a store-and-forward function. If APNs attempts to deliver a notification and the destination device is offline, APNs stores the notification for a limited period of time and delivers it when the device becomes available again. This component stores only the most recent notification per device and per app. If a device is offline, sending a notification request targeting that device causes the previous request to be discarded. If a device remains offline for a long time, all its stored notifications in APNs are discarded.

> To allow the coalescing of similar notifications, you can include a collapse identifier within a notification request. Normally, when a device is online, each notification request that you send to APNs results in a notification delivered to the device. However, when the apns-collapse-id key is present in your HTTP/2 request header, APNs coalesces requests whose value for that key is the same. For example, a news service that sends the same headline twice could use the same collapse identifier value for both requests. APNs would then coalesce the two requests into a single notification for delivery to the device. For details on the apns-collapse-id key, see Table 8-2.

**Comment by Fabenissimo** [comment]
Hi @zacwest,

thanks for the hint. I had luck by using the thread-id as that would not replace my old notifications which is what I was after. https://companion.home-assistant.io/docs/notifications/notifications-basic/#thread-id-grouping-notifications

Thanks!
