### ISSUE TITLE
Cannot compile the project in Xcode 11.3.1

### ISSUE THREAD

**Issue by laposheureux** [home-assistant/iOS#530]
Is development still being done on an earlier version of Xcode? 11 is known to have issues with extremely long switch statements (which Iconic-watchOS has and one of the places compilation fails for me when trying to build the Debug target). Also misc nonzero exit codes from CompileSwift in Eureka and Iconic-iOS that might just be because of the switch statement.

Any suggestions?

**Comment by ApexInfosysIndia** [comment]
Same here....please help!!

**Comment by zacwest** [comment]
I believe this is resolved now -- I can compile on Xcode 11.5. Please reopen if you are still experiencing it; logs would be helpful.
