### ISSUE TITLE
picture-glance card using camera_image shows "broken" image sporadically

### ISSUE THREAD

**Issue by Codelica** [home-assistant/iOS#533]
Not sure if this is a Lovelace/UI issue or one for the iOS companion, but since I've only ever seen it in the app (not via desktop Chrome or Safari), I'll start here. :)

Basically I get a "broken" image (as follows) sporadically from various `picture-glance` Lovelace cards that use `camera_image` as their source.  It can *always* be temporarily resolved by swiping down to reload the app/ui.   It doesn't matter which camera I have configured or whether there are one or many camera picture-glance cards on the view.  Individually all of the camera snapshots seem to work fine via browser over many many tests.

![IMG_2857](https://user-images.githubusercontent.com/386101/72857432-d5458080-3c7a-11ea-8a69-4b7b200d4415.jpg)

To try and track it further, I watched my nginx proxy log on a view with just one such card and found that when it happens, no GET request to `/api/camera_proxy/camera.xxx....` is received.  When swiping down to reload, I do see the request(s) come through.  This makes me think it's potentially some matter of caching with the app or maybe a service worker issue?  

I'd be curious to see if anyone else is seeing this, or if there is anything further I can try to track things down.

Thanks!

**Comment by Kedryn** [comment]
This happens to me and others too, and even via web page in chrome. It seems that when the page is loaded first time, all camera stills are loaded in few seconds. Then, when you leave that page, gradually, while refreshing each still image, sometimes one or more gets broken, and they will not work anymore until i hit F5.

**Comment by Codelica** [comment]
FWIW, this seems to be related to:

https://github.com/home-assistant/frontend/issues/3379
https://github.com/home-assistant/core/issues/23055

**Comment by TomBrien** [comment]
Hi is this problem still persistent and is it also present in safari or other browsers on iOS?

**Comment by Kedryn** [comment]
Yes, is there from the beginning. I think it's not browser/os related.

**Comment by TomBrien** [comment]
Ok if this isn't app related I will close here for now. I think the links above might help you. If this only ever happens in the app and not in Safari on iOS, let us know and we can reopen this one.
