### ISSUE TITLE
Zone Updates

### ISSUE THREAD

**Issue by scotty1395** [home-assistant/iOS#552]
Currently zones are only updated at app launch. If new zones are created or existing zones modified the app can't use this information for accurate geofence enter/exit events.

An example is the iCloud3 integration (HACS) which dynamically creates/updates a stationary zone if the device has not moved for a period of time. Currently you need to rely on less accurate significant location change events for the zone exit rather than a geofence exit.

Ideally, the app would update zones when the zone.reload service is called or perhaps when a request_location_update notification is received.

**Comment by zacwest** [comment]
The remainder of this work requires adding support for service calls in the mobile_app integration.

**Comment by zacwest** [comment]
If the app runs at all, it will now live-update the zones whenever it can.
