### ISSUE TITLE
Allow unresolved host name instead of IP address in internal and external url setting

### ISSUE THREAD

**Issue by to-scho** [home-assistant/iOS#553]
iOS automated VPN connection only works on particular domains rather than IP addresses. One can e.g. give <string>*.fritz.box</string> inVPN settings so that iOS automatically starts VPN connection for address "raspberrypi.fritz.box:8123" when that is your raspberry running home assistant.

In home assistant companion above only works a single time because the companion app replaces raspberrypi.fritz.box by the corresponding IP address after first dns lookup. Thats fine to save future dns lookup but breaks automated VPN here. Is is possible to have that replacement optional?

**Comment by TomBrien** [comment]
I think the app is actually taking the values of you Internal and External URLs from Home Assistant's configuration. Can you check what you have there

**Comment by to-scho** [comment]
Perfect, I can confirm that companion app replaces urls by home assistant yaml configurations for Internal and External URLs. Wasn't configured at all on my side before:

homeassistant:
...
  internal_url: raspberrypi.fritz.box:8123
...

Above setting will keep "raspberrypi.fritz.box:8123" as connection setting in the app once connected
