### ISSUE TITLE
Status bar does not change color on `frontend.set_theme` since 0.106

### ISSUE THREAD

**Issue by ronaldheft** [home-assistant/iOS#557]
Since the release of `0.106` of Home Assistant, the status bar no longer changes color to match the theme when `frontend.set_theme` is called.

`0.106` locked down the set_theme call to admins, so I suspect there are some bugs related to this change (https://github.com/home-assistant/core/pull/31654).

So far, I've discovered there is a frontend error related to `frontend.set_theme` reported here (https://github.com/home-assistant/frontend/issues/5021). I'm unsure if that error is suppressing the `themes_updated` event, which I'm assuming the companion app uses to change the status bar color.

Of note as well, it looks like the `themes_updated` event was updated to "no longer contains all theme data", so I'm wondering if that event no longer has the appropriate information to update the status bar when `frontend.set_theme` is called.

**Comment by ronaldheft** [comment]
I did some more research and discovered my suspicion is correct. The `themes_updated` event no longer contains the theme data.

To fix this issue, when the `themes_updated` event is received, the API has to be called to get the list of themes (Lovelace makes this exact call if you look through the socket debugger).

I’ve manage to work around this issue locally by setting up an automation that triggers on the `themes_updated` event missing theme data, and resends a new event that includes the theme data. With that, the iOS app now updates its status bar.

**Comment by zacwest** [comment]
Wild ride, debugging this one. The callback is never invoked now because `window.hassConnection` is `undefined` when `WebSocketBridge.js` is initially executed. So, on top of not getting the data, there was an underlying issue, too.
