### ISSUE TITLE
Side menu not scrollable when swiped from the left

### ISSUE THREAD

**Issue by h4nc** [home-assistant/iOS#559]
I noticed an issue with the side bar within the iOS app

When I swipe fast from the left I can't scroll down in the menu. After that I can swipe it back and if I swipe it slowly the menu becomes scrollable again. After swiping it slow once it also works fine swiping it fast for a while. 

Another way to make it work again is to reset the Frontend Cache. 

Would be interesting if someone is able to reproduce this.

**Comment by talondnb** [comment]
I’ve noticed this too, my workaround is to select an item that’s visible and quick to load and then it becomes scrollable on the next swipe. It gets rather annoying.

**Comment by talondnb** [comment]
Literally just found another workaround and that is to ‘find’ where the actual scroll bar is and swipe up/down, when you find it, it becomes active.

**Comment by Sirezul** [comment]
Same problem here!

**Comment by genebean** [comment]
This has been causing me grief lately too.

**Comment by zacwest** [comment]
https://github.com/home-assistant/frontend/issues/8988
