### ISSUE TITLE
Support for Certificates from Local Certificate Authorities

### ISSUE THREAD

**Issue by Veldkornet** [home-assistant/iOS#562]
App: 2.0.0(69)
iOS: 13.3.1
Hass.io: 0.106.5

I have a local Root and Intermediate CA which I used to issue a certificate for Home Assistant. 

The root certificates are trusted within iOS. Browsing to the HomeAssistant website with https from iOS works without any errors. 

However, when you try to connect via the app it returns a certificate error. 
I suspect that the app is not trusting the imported CA’s.

**Comment by robbiet480** [comment]
Just want to confirm [full trust](https://support.apple.com/en-us/HT204477) is enabled?

**Comment by Veldkornet** [comment]
It is enabled yes

**Comment by zacwest** [comment]
I believe this should work. See https://companion.home-assistant.io/docs/troubleshooting/networking for more help if you stumble across this issue.
