### ISSUE TITLE
Correct URL (internal/external) not determined based on SSID

### ISSUE THREAD

**Issue by CreaaZ** [home-assistant/iOS#565]
Due to my ISP I'm currently struggling with a NAT loopback issue, which results in the fact that I am unable to reach HASS via the external URL from within my local network. 

With that situation given I realized, that even when connected to my local network (correct SSID for internal URL is specified) the app still tries to connect via external URL. Even after app and device restart, the app tries to connect via external URL (even though in correct and specified WiFi)

In the settings view, the value for "Connect via" is "external URL", which I cannot change anywhere. But my assumption is/was, that the connection to a specified SSID will overwrite this setting.

iOS Device: iPhone XS
iOS Version: 13.1.3

HASS Companion: 2.0.0 (69)

**Comment by mountainsandcode** [comment]
Have you tried using the latest version of the app? 

Additionally, AFAIK the app needs location permissions (“While using the app” will be sufficient) because otherwise iOS does not allow the app to access the SSID, making it impossible for the App to know what WiFi you are connected to.

**Comment by mountainsandcode** [comment]
@zacwest This issue can be closed

**Comment by zacwest** [comment]
Thanks! OP: feel free to update this ticket if you experience issues again.
