### ISSUE TITLE
Problem with loading new dashboard lovelace of homeassistant core 107.1

### ISSUE THREAD

**Issue by YRRK** [home-assistant/iOS#571]
**iOS device model, version and app version**

Model Name: iPad 4 WIFI+Cellular (iPad3,5)
Software Version: iOS 10.3.4 (14G61) (maximum os)
App version: 2019.1 HomeAssistant for iOS

**Home Assistant Core Version**
107.1

**Describe the bug**
Problem loading new dashboard lovelace of homeassistand core 107.1 does not start-up with the user-modified-andsetto-default interface, but only with the standard one. Which is the wrong one, and also Irratic behaviour: White bar on the left. can't get rid of it anymore (I could in 107.0 with a lot of fiddeling around) Buttons are gone.

Won't be resolved with resetting the frontend cache.

Also problematic start-up (for a while now since version 2019.1) need to retry multiple times. There is no WIFI problem! The reception is good.

**To Reproduce**
Reproduceable immediately

**Expected behavior**
Display user defined lovelace

**Screenshots**
<-- If applicable, add screenshots to help explain your problem. -->
![2](https://user-images.githubusercontent.com/48710822/77167813-02fe4880-6ab7-11ea-909b-068bdff001f4.jpg)

<img width="1280" alt="1" src="https://user-images.githubusercontent.com/48710822/77167800-fed22b00-6ab6-11ea-80b9-054c1c80c193.png">

**Additional context**
Hope you can solve this one :-)

**Comment by stepman0** [comment]
I also have issues trying to use an old iPad 4 with Lovelace.

- Often no Connection / multiple retries
- wrong Display of Sensor cards
- Custom Header Not working

Do you Need any further Info?

I would like to use the old iPad as Wall Display …

**Comment by PierreScerri** [comment]
Same problem here with old iPad (IOS 10.3)
Blank side-bar.
Often unable to connect.
Works in Chrome but cannot change default dashboard.

**Comment by YRRK** [comment]
Oke, that's a clear bug. Is the developer reading this? :-)

**Comment by YRRK** [comment]
@TomBrien ?

**Comment by TomBrien** [comment]
I'm not the developer so there isn't much I can do for you sorry

**Comment by YRRK** [comment]
The new HomeAssistant 108 fixes it. Atleast for today. Lees wait a few days...

**Comment by TomBrien** [comment]
Great news I’ll close for now. Feel free to post here if it comes back
