### ISSUE TITLE
Apple Watch Complication - circular on infographic/infographic modular not working

### ISSUE THREAD

**Issue by Doa132** [home-assistant/iOS#577]
I’ve tried changing all types of the circular complications, but all that shows up is the basic icon then it updates and shows “- -“. 
I’ve tried using plain text, various templates, various icons. But it refuses to work. The corner image on infographic works, just not circular. 

I have an Apple Watch 4, version 6.2.1  
Home Assistant is on 0.108.3
Companion app is 2.0.0

example: Bottom right. Middle rectangle is a different app.
![IMG_4337](https://user-images.githubusercontent.com/43628930/79549895-f03d5a80-80da-11ea-92af-c34158c33b1e.PNG)

**Comment by Deez73** [comment]
also get this exact problem, Apple Watch series 5. WatchOS 6.2.1

**Comment by DBa2016** [comment]
Same issue here, WatchOS 6.2.1 and 6.2.5 beta 4.

Few more details:
- tapping the "--" icon still gets you into the actions selection
- when swiping into a clock face with HA complication configured, the icon is shown for a fraction of second (maybe .25s), before it disappears
- swiping left and right (changing the clock faces back and forth) randomly gets back the icon, which then disappears after another few swipes and/or after the watch is put to sleep
- removingthe complication from the watch entirely and re-adding seems to have fixed the issue for me for now, let us see if it reappears

**Comment by TomBrien** [comment]
It can take (quite) a while for the complication to update the first time, maybe an hour plus and you need to keep the face active (although it doesn't have to be _awake_).

**Comment by kmycek** [comment]
Actually, this is working fine for me today, with v2.0 (69) and WatchOS 6.1.3 on an Apple Watch 5 - HOWEVER, any icon picked for the Circular Image Template is sized way too large, resulting in me just seeing the center of the complication image. Seen in the bottom center, on this face:

![6F634F5D-07FA-4C12-8D99-B8B9D9E0AC68](https://user-images.githubusercontent.com/5732030/81849527-7a76b400-950b-11ea-8953-fffe2589b3cb.png)

**Comment by 1DontEx1st** [comment]
Adding to this, I can't seem to figure out a way to return to the default icon. In fact, I didn't want to switch in the first place, but adding actions apparently did that.

**Comment by TomBrien** [comment]
The original issue here I believe is solved and was related to initial sync of complications. I agree we should have a way of getting the app icon back. I've created #659 for this. Going to close this as the original issue is resolved
