### ISSUE TITLE
Feature: Support for push notifications through self-hosted push server (e.g. Gotify)

### ISSUE THREAD

**Issue by maichai** [home-assistant/iOS#578]
To be able to use push notifications in the companion we are forced to use Firebase, a cloud service. Cloud services are not everyone's favorite solution. 

I personally would very much to prefer to host the push server myself.

One possible implementation is Gotify, it currently only has an Android App to receive push notifications. 

However, the feature request would be to integrate the Gotify notification reception within the Companion App and make it a choice of the user whether he wants to use the pre-defined Firebase servers or a Gotify server of their own choice.

Integration of Gotify is superior to a seperate app, because this enables control of the HASS Companion App through notifications, e.g. request_location_update.

**Comment by robbiet480** [comment]
Totally understand the want for this, but all push notifications need to go through Apple’s Push Notification Service (APNS) to properly work. It’s very hard and possibly very battery intensive to be constantly running and connected to network in the background to receive notifications. Therefore, while this isn’t out of the question it’s low priority and something that I personally am unlikely to implement, but PRs welcome probably.

**Comment by zacwest** [comment]
Here's the state of affairs for iOS 14:

- Without disclosing server-side keys or certificates, it's not possible to add a third-party provider that you run locally in substitution of the Firebase messaging used by the iOS app. This includes something like the Gotify service as mentioned in this issue. It would be possible to rewrite the FCM-handling code to not have a Firebase requirement. That is a lot of work and (no matter what) requires some kind of external servers running in the cloud and Apple must always act as a intermediary.
- iOS 14 introduces [Local Push Connectivity](https://developer.apple.com/documentation/networkextension/local_push_connectivity). If anything is a likely alternative to APNS, it's going to be this, and it'll only work on WiFi locally and against certain SSIDs. Local Push is going to require an entitlement, so we need to wait to hear back from Apple (it doesn't seem like they are receiving requests for it yet). However, this feels like the best path forward to not requiring the cloud at home.

**Comment by zacwest** [comment]
Local push is now available in the iOS app, and we cannot support non-network-connected push otherwise unless Apple opens this system up further. Any future endeavors to remove Firebase are not related to this request.
