### ISSUE TITLE
Timeout in setup prevents the app from working

### ISSUE THREAD

**Issue by unlucio** [home-assistant/iOS#580]
**iOS device model, version and app version**

Model Name: iPhone XS
Software Version: 13.3.1
App version: 2019.1

**Home Assistant Core Version**
```
homeassistant/raspberrypi3-homeassistant   0.108.8             ddbf100d446c        2 days ago          1.25GB
homeassistant/armv7-hassio-supervisor      219                 262d0e5dd234        2 days ago          284MB
homeassistant/armv7-hassio-supervisor      latest              262d0e5dd234        2 days ago          284MB
```

**Describe the bug**
I'm getting an "error - The request timed out"
while trying to set up the companion app with my local installation.

**To Reproduce**
- connect to the same wifi az the server
- open the app
- wait for the server to show up in auto-discovery
- tap on the server
- login
- The app finds my installation and lets me login just fine
- It goes thru the last setup part until a popup error appears
- At this point, the app seems dead. I waited for 5 mins and nothing changed (please check the time in the screenshot)
- Closing and reopening the app starts from the beginning
- checking the integrations shows a new entry for iOS (so there is some inconsistency)
(I did all this for 3 times in a  row and gave up, it just happens every time and keep doing the same thing expecting a new outcome is a sign of insanity)

**Expected behavior**
Besides the obvious: "I'd expect it to work and the linking process to go throughout",
I'd actually expect a little bit more of information in the error pop up (WHAT did timeout?), and perhaps a "retry button" instead of having to thru the whole process again.
Since it effectively did pair (as it shows an entry in the web interface's "integrations"), it would be nice if after closing and reopening the app would show as connected and perhaps offer to repeat whatever didn't go throughout the last time.

**Screenshots**
I gathered some [screenshots on gdrive](https://drive.google.com/open?id=176DD2FZhrnLCegAgENlNll-KIO0JZ_pk):

![Permissins check](https://lh6.googleusercontent.com/NPezmAtPv4ao-NAqQNo8yA6LK_b5DnOYaq8gxFqM2o4AllF7x1UcqLySk8ZLTqUZ2lhqD3v2Xr_0SA=w3050-h2082-rw)

![timeout error](https://lh4.googleusercontent.com/foSuM8aWMn7Anrkczu-XHeX3VFYqZGuYpZsYEA2Q0V7E4-icwbRyzzyQFHfYH_m7V6cUzdtmjQ_-fw=w3050-h996-rw)

![after 5 mins it still stuck there](https://lh6.googleusercontent.com/h5MaEdfAajMuWEZXiT9hVruKivzUKzkh8fOCO-Hegv6n0ECql-WlkK8HELctFw6bBCLsxmHCKnrIhQ=w3050-h996-rw)

![Closing and reopening take you to the beguinnig](https://lh3.googleusercontent.com/JzolnK85khAU4twx1b964T-ryZkn8sho3xhK1SXxJHWw9SFD62qRGY8q_moYFY3zIxHSiN4Ug5syGw=w3050-h996-rw)

**Additional context**
tailing the docker container's logs gives:

```
2020-04-24 18:06:45 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new device_tracker.mobile_app entity: device_tracker.mulberry_3
2020-04-24 18:06:45 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.mobile_app
2020-04-24 18:06:45 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.mobile_app
2020-04-24 18:06:45 INFO (MainThread) [homeassistant.components.device_tracker] Setting up device_tracker.mobile_app
2020-04-24 18:06:55 ERROR (MainThread) [homeassistant.components.webhook] Error processing webhook af7db23da26dbb703dace7bb526515ee1312d7691ccc612a7da876f4860446e5
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/webhook/__init__.py", line 77, in async_handle_webhook
    response = await webhook["handler"](hass, webhook_id, request)
  File "/usr/src/homeassistant/homeassistant/components/mobile_app/webhook.py", line 186, in handle_webhook
    return await WEBHOOK_COMMANDS[webhook_type](hass, config_entry, webhook_payload)
  File "/usr/src/homeassistant/homeassistant/components/mobile_app/webhook.py", line 131, in validate_and_run
    return await func(hass, config_entry, data)
  File "/usr/src/homeassistant/homeassistant/components/mobile_app/webhook.py", line 379, in webhook_register_sensor
    await hass.data[DOMAIN][DATA_STORE].async_save(savable_state(hass))
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 136, in async_save
    await self._async_handle_write_data()
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 197, in _async_handle_write_data
    self._write_data, self.path, data
concurrent.futures._base.CancelledError
2020-04-24 18:06:55 ERROR (MainThread) [homeassistant.components.webhook] Error processing webhook af7db23da26dbb703dace7bb526515ee1312d7691ccc612a7da876f4860446e5
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/webhook/__init__.py", line 77, in async_handle_webhook
    response = await webhook["handler"](hass, webhook_id, request)
  File "/usr/src/homeassistant/homeassistant/components/mobile_app/webhook.py", line 186, in handle_webhook
    return await WEBHOOK_COMMANDS[webhook_type](hass, config_entry, webhook_payload)
  File "/usr/src/homeassistant/homeassistant/components/mobile_app/webhook.py", line 131, in validate_and_run
    return await func(hass, config_entry, data)
  File "/usr/src/homeassistant/homeassistant/components/mobile_app/webhook.py", line 379, in webhook_register_sensor
    await hass.data[DOMAIN][DATA_STORE].async_save(savable_state(hass))
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 136, in async_save
    await self._async_handle_write_data()
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 197, in _async_handle_write_data
    self._write_data, self.path, data
concurrent.futures._base.CancelledError
2020-04-24 18:06:55 ERROR (MainThread) [homeassistant.components.webhook] Error processing webhook af7db23da26dbb703dace7bb526515ee1312d7691ccc612a7da876f4860446e5
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/webhook/__init__.py", line 77, in async_handle_webhook
    response = await webhook["handler"](hass, webhook_id, request)
  File "/usr/src/homeassistant/homeassistant/components/mobile_app/webhook.py", line 186, in handle_webhook
    return await WEBHOOK_COMMANDS[webhook_type](hass, config_entry, webhook_payload)
  File "/usr/src/homeassistant/homeassistant/components/mobile_app/webhook.py", line 131, in validate_and_run
    return await func(hass, config_entry, data)
  File "/usr/src/homeassistant/homeassistant/components/mobile_app/webhook.py", line 379, in webhook_register_sensor
    await hass.data[DOMAIN][DATA_STORE].async_save(savable_state(hass))
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 136, in async_save
    await self._async_handle_write_data()
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 197, in _async_handle_write_data
    self._write_data, self.path, data
concurrent.futures._base.CancelledError
2020-04-24 18:06:55 ERROR (MainThread) [homeassistant.components.webhook] Error processing webhook af7db23da26dbb703dace7bb526515ee1312d7691ccc612a7da876f4860446e5
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/webhook/__init__.py", line 77, in async_handle_webhook
    response = await webhook["handler"](hass, webhook_id, request)
  File "/usr/src/homeassistant/homeassistant/components/mobile_app/webhook.py", line 186, in handle_webhook
    return await WEBHOOK_COMMANDS[webhook_type](hass, config_entry, webhook_payload)
  File "/usr/src/homeassistant/homeassistant/components/mobile_app/webhook.py", line 131, in validate_and_run
    return await func(hass, config_entry, data)
  File "/usr/src/homeassistant/homeassistant/components/mobile_app/webhook.py", line 379, in webhook_register_sensor
    await hass.data[DOMAIN][DATA_STORE].async_save(savable_state(hass))
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 136, in async_save
    await self._async_handle_write_data()
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 197, in _async_handle_write_data
    self._write_data, self.path, data
concurrent.futures._base.CancelledError
```
I cannot troubleshoot it much further because `Error processing webhook af7db23da26dbb703dace7bb526515ee1312d7691ccc612a7da876f4860446e5` doesn't mean much to me

**Comment by TomBrien** [comment]
Might be worth checking your IPv6 configuration if applicable. See here [here](https://companion.home-assistant.io/docs/getting_started/migration/#4---common-problems)

**Comment by unlucio** [comment]
The bug its self, from my perspective, is more about the app bee stuck and not providing clear info, retry logic, and ending up in a somewhat inconsistent state in respect to the server (the ios integration shows up but the app starts from the beginning)

Thank you for pointing me to the doc page, tho.
The app did work for me a couple of weeks ago on the same network and int he same situation. I just reinstalled hass.io on the PI because I "split my Pi in 2" (divided what was running on it in 2 PIs).
Moreover: my network does not have an IPV6 config and my router is not releasing any PV6 config block during the DHCP negotiation.

**Comment by TomBrien** [comment]
Can you also check about if you have a large `known_devices.yaml` file and have `nmap` on. There was something that sounds at least slightly similar last year. You may want to follow the conversation that happened [here](https://discordapp.com/channels/330944238910963714/551871772484698112/650790068323352596) going backwards from that point. I think (although I struggle to remember clearly) the fix was to empty out (or rename I guess would work) the `known_devices.yaml` file and turn of `nmap`

**Comment by unlucio** [comment]
Unfortunately, I don't have discord (I kind of got tired of installing the Nth IM app 😅and subscribing yet another random and redundant service).
How would you define a "large" `known_devices.yaml`?
I wouldn't define a 33 entry map nor a 3k file large.

```sh
pi3 homeassistant # cat known_devices.yaml| grep name | wc -l
33
pi3 homeassistant # ll known_devices.yaml
-rw-r--r-- 1 root root 3.0K Apr 25 12:01 known_devices.yaml
```

Thos I see my installation is updating right now to "Home Assistant Core 0.108.9", so I'll give it another try once it's updated and perhaps try renaming `known_devices.yaml` as well to cover my bases.

Thanks again for the suggestions! It's great to at least have options to try and ponder.

**Comment by TomBrien** [comment]
I don't know really how long. Last time I saw something similar I didn't feel like it was really either but it seemed to be the issue. They had some log entries about `nmap` taking longer than expected to get going that's what got me on that route. Don't know if that applies to you

**Comment by unlucio** [comment]
Update: I emptying the `known_devices.yaml` and deleting even device tracking configuration.
Didn't help.

**Comment by TomBrien** [comment]
Ok, do you have any other errors in your log? You're running on a Pi is there any chance of a failing SD card?

**Comment by TomBrien** [comment]
Also, if you have `nmap:` in your `configuration.yaml` can you try commenting out that part of the configuration?

**Comment by unlucio** [comment]
I don't have it.
all I have is the following:

```
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
blink: !include blink.yaml
```

and an `influxdb:`
but I currently turned all the add_ons off just in case

**Comment by unlucio** [comment]
BTW, besides my problem, I still think the BUG is that the UI ends up in a dead-end.
Every time I try to link it a new entry for my phone is created in the `configuration->integrations` panel, so my guess is that the solution would be for the app to just carry on, retain the token, unlock and eventually retry whatever timed out.
It's a bummer to have to start over and over when indicators show that mostly it worked.

**Comment by TomBrien** [comment]
I agree that there seems to be some kind of timeout or something that means it's giving up. Can you check all the expected sensors are created [see this list](https://companion.home-assistant.io/docs/core/sensors) and the `device_tracker` entity is created?

Do you know what was populating the `known_devices.yaml` as nothing in your `configuration.yaml` there would be

**Comment by unlucio** [comment]
Ok, I found the cause of my problem:
The media where I was saving all the hassio stuff.
I had a USB stick lying around and just moved everything to that media so I didn't need to have an HD connected to the PI. Turns out it was a bad idea: too slow of a device and it was causing too much I/O wait.

I moved everything to an HD and the app was able to link fine. 😅🤦‍♂️
(well I guess "someone" is touching its disk a little too much 😂)

IMHO the app bug still stands. It needs:
- better error then "time out"
- retry logic
- not to lock the UI etc.

thanks for you suggestions and help.

cheers

**Comment by TomBrien** [comment]
Ok that's great thanks for the update. That matches up with the last time we saw this which I guess was IO errors.

Agree on the fix needed for bug though

**Comment by drk-geek** [comment]
> Ok, I found the cause of my problem:
> The media where I was saving all the hassio stuff.
> I had a USB stick lying around and just moved everything to that media so I didn't need to have an HD connected to the PI. Turns out it was a bad idea: too slow of a device and it was causing too much I/O wait.
> 
> I moved everything to an HD and the app was able to link fine. 
> (well I guess "someone" is touching its disk a little too much )
> 
> IMHO the app bug still stands. It needs:
> 
> * better error than "time out"
> * retry logic
> * not to lock the UI etc.
> 
> thanks for your suggestions and help.
> 
> cheers

Hi unlucio,
I am facing same issue and still unable to find a fix. the SD card on PI have enough space to handle companion app
what you suggest?

**Comment by TomBrien** [comment]
Worth checking for other errors in your log or any sign of SD card corruption

**Comment by unlucio** [comment]
> I am facing same issue and still unable to find a fix. the SD card on PI have enough space to handle companion app
> what you suggest?

Mine wasn't a matter of space, but of speed: the media I was saving stuff too was too slow.

Based on @TomBrien 's suggestions and what I found I'd suggest measuring and investigate everything that could make things slow thus causing the timeout.
My feeling is that I/O is the problematic area.

**Comment by drk-geek** [comment]
My android device connected successfully but still have issues with IOS device. I tried to connect but end up with same issue. I can see mobile app integration in configuration -> integration for both android and ios. 
for me it looks app issue

**Comment by unlucio** [comment]
idk about Android, but my guess is that version of the app might be more resilient.
As said I still think this is mostly a problem due to hos the UI behaves in the IOS app.

**Comment by unlucio** [comment]
New version of the app and the bug still persist; increasing the time out is just a hacky patch that doesn't solve the real problem: the app ends up been hanged and unusable and the user has no clue on what's going on.
The spinning gifs hint there's something happening, the 20min of no results ultimately tell you the app is frozen.

![IMG_3274](https://user-images.githubusercontent.com/778799/92920594-cd696500-f432-11ea-89f9-dbca862dafec.PNG)
![IMG_3273](https://user-images.githubusercontent.com/778799/92920600-d0645580-f432-11ea-936a-da89bb54ba65.PNG)

 The real solution is implementing a retry logic that doesn't leave the use hanging on that screen that will never finish, and perhaps suggest possible solutions (ie: I had to delete the known_devices in order to be able to login)

**Comment by zacwest** [comment]
Feel free to open another ticket about that -- if an error happens (and clearly one did, you got an alert) we should fail out of onboarding after the error is dismissed. However, your issue is not a timeout issue - you are receiving an error message that isn't timing out.
