### ISSUE TITLE
MaterialDesignIcons.swift is not generated

### ISSUE THREAD

**Issue by kirillzuev** [home-assistant/iOS#581]
**iOS device model, version and app version**

Model Name: N/A
Software Version: N/A
App version: N/A

**Home Assistant Core Version**

**Describe the bug**
Can't build project, MaterialDesignIcons.swift contains only boilerplate code:

    // Generated using SwiftGen — https://github.com/SwiftGen/SwiftGen

    import UIKit

    // No icons found for MaterialDesignIcons font!
    // Visit https://github.com/home-assistant/Iconic/issues for further information.

**To Reproduce**

Clone repository, follow Getting Started (https://github.com/home-assistant/iOS#getting-started) to prepare environment and get dependencies.

**Expected behavior**

MaterialDesignIcons.swift is populated with code, project can be built.

**Screenshots**
<-- If applicable, add screenshots to help explain your problem. -->

**Additional context**
Xcode 11.2.1
Cocoapods 1.9.0.beta.3
master branch

**Comment by kirillzuev** [comment]
Any chance I can compile the project and contribute? :)

**Comment by chirag115** [comment]
Which version of material icons you have downloaded? I believe the latest version has some issue. and pod install will download the latest version only. 
I have replaced the ttf file in Tools directory with the older version downloaded from https://github.com/Templarian/MaterialDesign-Webfont/blob/master/fonts/materialdesignicons-webfont.ttf and run `pod install` command again.

**Comment by zacwest** [comment]
Fixed by #602.
