### ISSUE TITLE
Apple Watch location

### ISSUE THREAD

**Issue by buzz-b** [home-assistant/iOS#583]
Hi,

With the advent of eSims within the Apple Watch (and other Brands I'm sure) it's possible to now go out without your Phone in your pocket, which kinda now negates all the hard work we've done around following your location tracking, and various automations we all have based off of these events.

Could you please add an entity.location for the Apple Watch, it has GPS just like the phone, and I assume this location is shared with the dev kit as many other apps use this as a source. With the eSim you have the same access to 4G Data, so there should be no issue posting the location back to the same HASS home unit that is setup in the HASS Apple App.

Fingers crossed therefore that this is not a huge request and you could consider it in your next sprint cycle?

Please advise if you need any assistance in testing it.

Thanks.

**Comment by j0dan** [comment]
Finally someone with the same issue! I often have to remember that automations or presense won't work if I leave without my iPhone.

**Comment by magnus919** [comment]
In general, I think there'd be a lot of value to having the Watch show up as a device like any other iOS device, and bundle with it all of the possible sensor entities.

**Comment by buzz-b** [comment]
Any further thoughts on adding this watch request?, there's a lot of usage nowadays with watch usage and cashless payments etc with COVID etc. I hardly use cash, and when you have the watch with en eSim, you hardly need the phone to be with you, except all the GPS automations (like locative) I have dont work with the watch only.   Please Please... :)
