### ISSUE TITLE
Duplicate phone device tracker

### ISSUE THREAD

**Issue by chemelli74** [home-assistant/iOS#584]
**iOS device model, version and app version**

Model Name: iPhone 7
Software Version: 13.4.1 
App version: 2.0.0 (69)

**Home Assistant Core Version**

0.109.2

**Describe the bug**

At every refresh top bar shows an error, see sreenshot

**To Reproduce**
Swipe to bottom

**Expected behavior**
No error shown

**Screenshots**
<-- If applicable, add screenshots to help explain your problem. -->

![image](https://user-images.githubusercontent.com/57354320/80849551-e148c300-8c17-11ea-800e-74abbbe25860.png)

**Additional context**

I think it can be related to denying access to one of the system data like motion sensor.

**Comment by chemelli74** [comment]
Any update ?

Simone

**Comment by TomBrien** [comment]
You need to allow location permissions for the app this is documented in the docs [here](https://companion.home-assistant.io/docs/troubleshooting/faqs/#i-recieve-a-kclerror-when-pulling-down-to-manually-refresh-the-appupdate-location). Please let us know if this fixed the issue

**Comment by chemelli74** [comment]
I don't want to use the app as a tracker, but just for the interface to lovelace.
But still mobile is registered as tracker. How can I avoid this ?

Simone

**Comment by TomBrien** [comment]
Currently, disabling the tracker will result in the behaviour you describe along with stopping the operation of the sensors. This will hopefully be fixed in a future update but for now you may prefer to just pin a safari link on your homepage

**Comment by chemelli74** [comment]
Hopefully, there will be an improvement in future.

Thx for checking this issue,

Simone
