### ISSUE TITLE
Lately the app always gives me an ssl error on startup

### ISSUE THREAD

**Issue by simonk83** [home-assistant/iOS#586]
**iOS device model, version and app version**

Model Name: iPhone XS Max
Software Version: 13.3.1
App version: 2.0.0(69)

**Home Assistant Core Version**

0.109.1

**Describe the bug**
The app always gives an ssl error and won’t connect until I manually visit the nabu casa remote url and log in. Then the app connects properly. 

**To Reproduce**
Just opening the app will cause this (if you’re affected)

**Expected behavior**
App connects as expected

**Screenshots**
<-- If applicable, add screenshots to help explain your problem. -->

**Additional context**

**Comment by robbiet480** [comment]
What SSL error? Need more details, preferably a screenshot.

**Comment by simonk83** [comment]
Hey Robbie, I’ll close this. Typically, it was happening for a while and
then when I finally got around to reporting it, it’s stopped happening :)
