### ISSUE TITLE
Issue with location accuracy after 13.4 update

### ISSUE THREAD

**Issue by mbaran5** [home-assistant/iOS#589]
**iOS device model, version and app version**

Model Name: iPhone 11 Pro
Software Version: 13.5 
App version: 2019.1

**Home Assistant Core Version**
0.110.1 w/temporary webhook.py fix for sim2 errors 

- https://github.com/brg468/core/tree/mobile_app_webhook_fix/homeassistant/components/mobile_app
- https://github.com/home-assistant/core/issues/35812#issuecomment-631737472

**Describe the bug**
I am seeing my accuracy flail all over the place. Sometimes it goes as high as 2500, then drops down to 65. I can't seem to get my accuracy under 65, although my wife's iPhone X has no problem getting down to 10. 

My update type will change to Significant Location Change even though I haven't moved because it doesn't think I'm 2 miles away any more. 

Others on the HA forum are experiencing similar issues - https://community.home-assistant.io/t/gps-accuracy-after-upgrade-to-ios-13-4/181585/5

**To Reproduce**
Install app, allow initial sensors to be created, review GPS accuracy. 

**Expected behavior**
Stable location

**Screenshots**
The blue larger circle is my iPhone 11 Pro and the smaller green circle is an X. Both are on the same WiFi and cellular carrier. 
![image](https://user-images.githubusercontent.com/583865/82625117-2fa70d00-9b99-11ea-82f5-61749bc7216d.png)

**Comment by mastermc0** [comment]
Having a similar issue where the accuracy flails wildly but is also pushing me out of zones activating my alarm etc.

Happens on my iPhone 11 Pro Max and my partners iPhone 7

Happy to provide more detail if required.

**Comment by TomBrien** [comment]
I don't see this as much on my Xs. My suspicion is that this is to do with having the app open in background or some over power-saving that has been implemented in 13.4

**Comment by mbaran5** [comment]
My wife’s X on 13.5 never seems to do it. This only seems to affect my 11 Pro

**Comment by b4dpxl** [comment]
I’ve just updated to 13.5 (skipped 13.4) and I’m having major issues with it tracking my location (or rather not). In the attached screenshot I was out for nearly 3 hours after 16:30 yesterday, and for 2 hours from ~12pm today. It only registered the update when I manually refreshed the app. I can’t rely on it for presence at the moment 🙁
![80FF000C-2B17-4D06-84DB-4AFCD9DC2D95](https://user-images.githubusercontent.com/26406101/83414205-026a2280-a415-11ea-8539-5b567d84eb94.jpeg)

**Comment by zacwest** [comment]
For those who are affected by this (specifically things like Background Fetch producing very inaccurate results), please upgrade to 2020.2 and give the "In-Development Updating" option a try in App Configuration > Location.

**Comment by KennethLavrsen** [comment]
I am seeing similar issue on my iPhone 7.

It has recently started reporting my location with a huge accuracy circle with its center far far away from where I really am. It is so far away that we are beyond the next cell phone tower. More than 1 km away. The result of the combination of the wrong location and huge accuracy circle is that my Home Assistant declare me home several times a day while I am at work each time turning off my alarm system. I have just turned on the In-Development Updating as I read through this bug report history.

This used to work very well and very reliable. It is something that changed within the last month or so.

**Comment by KennethLavrsen** [comment]
I have been using the In-Development Updating since yesterday.

No improvement.

Below is a screen shot from my HA

![image](https://user-images.githubusercontent.com/8373419/85755979-b60dbc00-b70e-11ea-8b34-d6af32e98913.png)

The large green circle with a K is my phone. That position is almost 2 km from where I really am. My actual position at that moment is where the green line from the K points to. There is no way the phone on my work desk can be connected to a cell tower that far away. I have the local cell tower less than 50 meters from me.

Both the position and accuracy are false. It may be a bug in IOS. But the HA app should not report location back to HA if the accuracy is this bad. Those positions should be ignored.

**Comment by zacwest** [comment]
@KennethLavrsen If you dig into the reason that location was sent (in-app App Configuration > Event Log), I'm betting it's enter/exit of a region/zone related, which is more #661 than this ticket. The current version of In-Development Updating only affects non-movement generating location data, but the things described in #661 are more like what you're seeing, and should be addressed soon.

**Comment by cbho** [comment]
Having this issue as well on my iPhone SE (2. gen), iOS 13.5.1, Home Assistant app 2020.2 (5) with In-Development Updating activated - and on my sons iPhone Xs (other parameters equal).

Kind of problematic when a lot of automations depend on the geolocation - and the radius of 2500 meters "block" it from happening...

Some time ago the Home Assistant app included the possibility to manually trigger a location update - this seems to have disappeared - but would be really useful for situations like this...

Perhaps this functionality should be reintroduced? Just to have it as backup if (/when?) something like this happens again ;-)

**Comment by TomBrien** [comment]
Manual updates can still be triggered by pulling doing down to refresh the the view. This sends an update at the same time.

**Comment by zacwest** [comment]
2020.3+ should have greatly improved the In-Development Updating setting, and its improvements are now enabled by default for future releases. Considering this issue (thematically) closed. Please join us in Discord or create a new GitHub issue to report future instances of poor location accuracy on 2020.3+ with the setting on, or 2020.4+.

**Comment by KennethLavrsen** [comment]
Nothing is improved. The location is still inaccurate. Just like before. And it has nothing to do with zone enter and zone leave. The location is jumping kilometers around while I am sitting here still on my chair and my phone is moving centimeters, being on, with the app open.

**Comment by jsiemek** [comment]
My suggestion. Could you please install Pokemon Go. Then observe if your
avatar is where you are, or maybe is running over neighborhood.
It will show if data from GPS is correct.
My GPS in some places are getting wild. If it’s the case, app can not fix
it.


All best,
Jaroslaw

W dniu wt., 7.07.2020 o 13:18 Kenneth Lavrsen <notifications@github.com>
napisał(a):
