### ISSUE TITLE
Catalan translation

### ISSUE THREAD

**Issue by nelio12** [home-assistant/iOS#591]
Hi,
Would be nice if you can add Catalan for to the lokalise iOS app translation project as well for the Android app.

English Name: Catalan
Native Name: Català
ISO code: ca-ES

**Comment by TomBrien** [comment]
@olbjan you able to add this?

**Comment by olbjan** [comment]
I've added Catalan and assigned permissions to contribute to @nelio12 in lokalise. Sorry it took a while, I just rebuilt my main pc and only got to this now.

**Comment by nelio12** [comment]
Great! Thank you!
