### ISSUE TITLE
Cached 404 on location update notification

### ISSUE THREAD

**Issue by danikuci1** [home-assistant/iOS#594]
the docs contain a link to https://companion.home-assistant.io/docs/notifications/location-notification which is a non-existent page.

**Comment by TomBrien** [comment]
Cheers. That’s the second time in 24 hours I’ve seen a page that does exist coming up as not found. Think we’ll have to clear a cache. Sorry about this. Should be fixed soon

**Comment by TomBrien** [comment]
@danikuci1 in the mean time [here’s a link](https://5ecc3ab8b1650d00078e3934--home-assistant-companion-docs.netlify.app/docs/notifications/location-notification) to that page in the last build preview. That will expire at some point but hopeful we will have this fixed by then

**Comment by danikuci1** [comment]
USA

**Comment by TomBrien** [comment]
Thanks. I’m going to close this as I’m happy it’s an issue with the caching. Probably someone near you (in global sense of near) tried to access that page while the site was rebuilding. Should clear soon. If it hasn’t in a couple of hours let me know and we can look deeper.
