### ISSUE TITLE
RTSP live stream for dynamic attachment in notifications

### ISSUE THREAD

**Issue by basesnow** [home-assistant/iOS#596]
**Is your feature request related to a problem? Please describe.**

Not a problem, just an enhancement

**Describe the solution you'd like**
It appears that only MJPEG cameras are supported for live stream as a dynamic attachment in a notification. Is it possible to allow RTSP cameras to live stream?

**Describe alternatives you've considered**

tried to figure out ways to convert my RTSP stream to MJPEG, but I can't seem to find a solution
**Additional context**

**Comment by robbiet480** [comment]
This isn't going to happen, at least not easily, because RTSP isn't supported at all on iOS. More likely to add HTTP Live Streaming (HLS) support.
