### ISSUE TITLE
Apns-collapse-id doesn't seem to be working. 

### ISSUE THREAD

**Issue by CCOSTAN** [home-assistant/iOS#597]
**iOS device model, version and app version**

Model Name: iPhone XS Max
Software Version:  13.5
App version: 2.0.0 (69)

**Home Assistant Core Version**
0.110.4

**Describe the bug**
The APNS-COLLAPSE-ID is not working.  If you send 2 messages using the service entry, you get 2 independent messages. 

**To Reproduce**
Use the development tools and send yourself a message twice using the apns-collapse-id and you will get to messages instead of one replacing the other.

**Additional context**
More testing and detail can be found here: 
https://github.com/CCOSTAN/Home-AssistantConfig/issues/750

**Comment by CCOSTAN** [comment]
Well, There you go @TomBrien !!  It was subtle but you solved it for me.  
![image](https://user-images.githubusercontent.com/2160436/83778834-3897e400-a659-11ea-8923-ccbb5a69bf86.png)
I was using `notify.ios_carloxsmax` instead of `notify.mobile_app_carlo_xsmax`.  That small change made all the difference.  Now I need to figure out why the other ones are there and how to get rid of them. 
Thanks!

**Comment by TomBrien** [comment]
Those old ones are from the previous version of the app (v1.5) and can be safely removed. Have a look at the [migration guide](https://companion.home-assistant.io/docs/getting_started/migration/)
