### ISSUE TITLE
iOS App not available in App Store

### ISSUE THREAD

**Issue by theskm** [home-assistant/iOS#598]
Hello,
the App is not available anymore, at least in Germany. Any Infos about that?

**Comment by robbiet480** [comment]
https://twitter.com/Robbie/status/1268822295151169537

**Comment by theskm** [comment]
Thanks for the info. Keep up the good work!

**Comment by lmjohansen** [comment]
iOS App not available in Denmark either ?

**Comment by TomBrien** [comment]
Based on Robbie’s post its not available anywhere until fixed

**Comment by markheloking** [comment]
Currently also unavailable in the netherlands

**Comment by SeanPM5** [comment]
If you have downloaded the app in the past, and deleted it to re-install or set up on a new device, and now you don't see it on the store, you can still re-download it from the "Purchased" section of the App Store. Here's how:

![image](https://i.imgur.com/Vr2r77i.png) ![image](https://i.imgur.com/A61cCYv.png)

You can also use this method to get it on another family members phone:
* From the same "Account" screen in the second photo you can scroll all the way to the bottom (under all the app updates) and "Sign Out" from your family members account.
* Sign into your account and use the same method above to download the app from your "Purchased" section.
* After app is installed on your family member(s) phone then sign out of yours and have them log back into their own account.

Going to temporarily pin this issue until it goes back on the store.

**Comment by TomBrien** [comment]
I've locked this for now as the App is currently deliberately not available in any territories. If you're an existing users, see Sean's great post above on how to re-download the app.

**Comment by zacwest** [comment]
It is available now!

**Comment by TomBrien** [comment]
Unpinning too
