### ISSUE TITLE
Event Log issues in 2020.1b

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/iOS#626]
**iOS device model, version and app version**

Model Name: iPhone 11 Pro
Software Version: 13.5.1
App version: 2020.1 (15)

**Home Assistant Core Version**

0.111.0

**Describe the bug**
When going to App Configuration -> Event Log and tapping on anything in there, the resulting page is almost always blank rather than showing anything in the payload. I don't know if it was like that before, but I think it used to show stuff... I only saw it on one item (included in screenshot below) out of many.

Additionally when iOS dark mode is active it's not fully dark; there's white background on the left and right sides and bottom. Screenshot below.

**To Reproduce**
Go to App Configuration -> Event Log and tap on something

**Expected behavior**
Show payload

**Screenshots**

This one demonstrates the issue with dark mode enabled, it's half white and half black.

![image](https://i.imgur.com/h3vrsSj.png)

This one demonstrates the blank/missing payload. Again not 100% sure it showed before, but I _think_ it did.
![image](https://i.imgur.com/h3GSq69.png)

**Additional context**

**Comment by TomBrien** [comment]
Doesn’t seem to happen on a Xs ![Uploading 84467172...]()

**Comment by SeanPM5** [comment]
Mine looks like that too on the main screen, but when you tap any of those items / drill down is where it messes up visually.

**Comment by TomBrien** [comment]
May bad yeah I have the same
