### ISSUE TITLE
Support URLs in Actionable Notifications

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/iOS#643]
**Is your feature request related to a problem? Please describe.**

Currently you can make a notification link to a URL, but you cannot do the same for the actionable notification buttons. Would be really useful if you could (and it does seem to be supported in the Android app). Here's an example of some forum threads asking about this, dating years back.

* [iOS Actionable Notification Call Phone Number](https://community.home-assistant.io/t/ios-actionable-notification-call-phone-number/24144) (2017)
* [Notification Actions on Local Device?](https://community.home-assistant.io/t/notification-actions-on-local-device/53613) (2018)
* [iOS Actionable Notifications, open URL?](https://community.home-assistant.io/t/ios-actionable-notifications-open-url/39481) (2018)
* [URL Notification Link](https://community.home-assistant.io/t/url-notification-link/32554/13) (2018)
* [Launching a URL using actionable notifications, is it possible?](https://community.home-assistant.io/t/launching-a-url-using-actionable-notifications-is-it-possible/78324) (2018, me haha) 
* [Make a call from actionable notification](https://community.home-assistant.io/t/make-a-call-from-actionable-notification/203476) (2020)

This feature would allow a lot more possibilities, some examples:

1. A button that calls someone (`tel://123-456-7890`)
2. A button that runs an iOS shortcut (`shortcuts://run-shortcut?name=Your Shortcut`). 
3. A button that opens a specific Lovelace view (such as `/lovelace/cameras/`).
4. Button(s) that [deep link to iOS settings](https://www.macstories.net/ios/a-comprehensive-guide-to-all-120-settings-urls-supported-by-ios-and-ipados-13-1/) (`prefs:root=SCREEN_TIME` to open Screen Time)

And a lot more...

Example use case via ashscott on forums:

![example](https://community-assets.home-assistant.io/optimized/3X/7/c/7c35744247a4cff618b8bdc7c93e82a96773771f_2_818x1000.jpeg)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ripvega** [comment]
This will be a great addition.
Examples 1,2 and 4 above are essentially the same. The app/HA just needs to support iOS URL scheme, I think.

**Comment by TomBrien** [comment]
Point 3 can be covered by adding to the existing [URL handler](https://companion.home-assistant.io/docs/integrations/url-handler) so that links such ass `homeassistant://lovelace/...` open the app to the appropriate view

**Comment by Krocko** [comment]
@TomBrien if I use this I got the following error:
![image](https://user-images.githubusercontent.com/29394115/84757117-05901180-afc4-11ea-95f0-b7cf2bcf59ef.jpeg)

**Comment by TomBrien** [comment]
Sorry I meant by adding the functionality to the URL Handler. Currently this isn't possible and the URL handler acts kind of like an API endpoint
