### ISSUE TITLE
Add option to set status bar text color in theme

### ISSUE THREAD

**Issue by Phontana** [home-assistant/iOS#645]
**Is your feature request related to a problem? Please describe.**
In the latest release (2020.1) the option to set the status bar color by `adding app-header-background-color` to the style is implemented. However, when a light status bar color is used in the theme, the text becomes unreadable because it is always set to `UIStatusBarStyle.lightContent`. 

**Describe the solution you'd like**
An option to override this, as described in https://github.com/home-assistant/iOS/issues/531#issuecomment-584289188 and https://github.com/home-assistant/iOS/issues/561#issuecomment-596089515, would help to improve the styling when using light status bars.

**Describe alternatives you've considered**
It might be possible to check the color of the status bar and determine whether the text color should be light or dark, but that would require a lot of work.

**Additional context**
An example of the current implementation:
![IMG_2479](https://user-images.githubusercontent.com/13638753/84600832-90fe8b00-ae7c-11ea-891d-05a24a2e33f6.jpeg)

**Comment by olekenneth** [comment]
But if the theme changes with the app in background, it will not refresh the header bar unless manual refresh.

 ![image](https://user-images.githubusercontent.com/544388/85327535-6a210400-b4cf-11ea-8ca7-529e645d3de3.png)

**Comment by TomBrien** [comment]
Status bar color changes instantly for me no need to manually refresh

**Comment by TomBrien** [comment]
![image](https://user-images.githubusercontent.com/12411302/85329876-422fa180-b4cb-11ea-9d74-75a4335b6578.gif)

**Comment by olekenneth** [comment]
>... with the app in background, it will not refresh the header bar unless manual refresh.

**Background** is the keyword here

**Comment by TomBrien** [comment]
This is a different case. There is some new refreshing I believe in the next update which will refresh the view when the app is opened. That should address this

**Comment by TomBrien** [comment]
@olekenneth just wanted to let you know I tested this on the current dev version and the following works fine (which I think is roughly what you were doing).
1. Load app and set theme to "Backend Selected"
2. Go to phone home screen
3. On another device use service to change theme
4. Open app again
At this point the app does change to match the new theme

**Comment by olekenneth** [comment]
@TomBrien Correct. Looking forward to seeing it myself.
