### ISSUE TITLE
New userAgent does not differentiate between iPad and iPhone

### ISSUE THREAD

**Issue by Villhellm** [home-assistant/iOS#651]
The newest update overwrites the userAgent completely, removing any relevant browser information for the device being used. This breaks any sort of filtering based on the type of device being used ie iPhone or iPad, Mobile, etc

This goes against what the userAgent is supposed/expected to contain https://developer.chrome.com/multidevice/user-agent

**iOS device model, version and app version**

Model Name: iPhone 8
Software Version: 13.3.1
App version: 2020.1 (17)

**Home Assistant Core Version**

0.111.1

**Describe the bug**
The new userAgent completely removes any information about the current browser. 

**To Reproduce**

**Expected behavior**
The userAgent contains all the information that actually pertains to the browser being used.

**Screenshots**

**Additional context**
This would have been fixed with PR #632 , but that was closed without a real explanation as to why

**Comment by robbiet480** [comment]
Unsure what this PR is asking for. I had said the other day I have no problem adding iPad/iPhone/iPod Touch and even more detail like iOS version to the UA, but I think you're now asking to entirely revert the UA change?

**Comment by Villhellm** [comment]
I'm not suggesting reverting, I'm suggesting leaving the userAgent as it was and appending the new information, as per PR #632. This would solve both problems of device filtering and advanced reverse proxy configs for the app. 

All that was required to fix issue #554 is simply adding "Home Assistant" somewhere to the UA. It seems unnecessary and a step backwards to completely overhaul the information that was already present.

**Comment by Villhellm** [comment]
also I know that you said you had no problem with adding the device information, but so far I had seen no forward movement. I opened this issue to track progress as well as suggesting alternate fixes
