### ISSUE TITLE
Theme should be customizable based on iOS system dark/light mode

### ISSUE THREAD

**Issue by zacwest** [home-assistant/iOS#656]
**Is your feature request related to a problem? Please describe.**
I can change themes between Light and Dark mode using a backend timer-firing of `frontend.set_theme` but this isn't as elegant as watching for the _actual_ appearance type and  changing  it on the fly.

**Describe the solution you'd like**
A setting to select which theme should be displayed in dark mode and in light mode, allowing up to 1 to be not selected.

**Describe alternatives you've considered**
This could likely be done on the frontend (and thus work everywhere) based on media queries for dark mode, or by invoking a manual theme-change frontend-side in the app.

**Comment by robbiet480** [comment]
This probably should be added to the frontend repo first. Once implemented there, it can be added to the app(s).

**Comment by SeanPM5** [comment]
Coming in 0.114 🎉🎉 https://github.com/home-assistant/frontend/pull/6430

Mostly, anyway... currently does not allow you to specify a custom theme to use for dark mode, but has an "auto" option that switches between the default light and dark modes based on system appearance.

**Comment by zacwest** [comment]
I think that satisfies my desires -- it should be up to the frontend to do it, this idea was more of a hack. Great news!

**Comment by Shoomaan** [comment]
Need a work around for my Wallmounted iPad Air with iOS 12. There is no system setting for Dark Mode. A service to override this preference would be helpful. Just changing the theme is not enough, because then e.g. the map view remains in light mode
