### ISSUE TITLE
Add app icon as complication image

### ISSUE THREAD

**Issue by TomBrien** [home-assistant/iOS#659]
**Is your feature request related to a problem? Please describe.**

Currently the set of images for circular complications (and others?) does not include the app icon (which IMHO is the nicest). There is a version of the icon but it is heavily simplified and comes out over sized. If you do not set the circular complication in App Configuration, the app icon is used. However, as soon as you experiment with changing the image it is impossible to revert to the app icon with out resetting the app.

**Describe the solution you'd like**

Add the Home Assistant icon to the set of icons

**Describe alternatives you've considered**

**Additional context**

**Comment by zacwest** [comment]
@TomBrien I'm thinking you closed this one by accident?

**Comment by TomBrien** [comment]
I wish... it’s a dupe of my own issue 🤐

**Comment by TomBrien** [comment]
Dupe of #525
