### ISSUE TITLE
Lack of spacing between sensor and unit of measurement

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/iOS#660]
**iOS device model, version and app version**

Model Name: iPhone 11 Pro
Software Version: 13.5.1
App version: 2020.2 (3) / TestFlight

**Home Assistant Core Version**

0.111.3

**Describe the bug**
In the new Sensors section under App Configuration, there is no space between the sensor value and the unit of measurement. It looks OK on some things, but weird on some others, mainly activity sensors. Screenshot below.

(I understand this is brand new and still being worked on, so might've already been fixed in dev. Awesome addition btw!)

**To Reproduce**
Configuration -> Sensors, look at activity sensors mostly

**Expected behavior**
Space between value and unit of measurement (`11steps` = `11 steps`)

**Screenshots**

![image](https://i.imgur.com/7UO43F3.jpg)

**Additional context**

**Comment by TomBrien** [comment]
Also true in `SensorDetailViewController`
