### ISSUE TITLE
Incorrect Sensors icons

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/iOS#663]
**iOS device model, version and app version**

Model Name: iPhone 11 Pro
Software Version: 13.5.1
App version: 2020.2 (5) / TestFlight

**Home Assistant Core Version**

0.111.3

**Describe the bug**
In the new Sensors configuration panel, it is showing wrong/placeholder icons in the list.

Distance should be `mdi:hiking`
Floors Ascended should be `mdi:slope-uphill`
Floors Descended should be `mdi:slope-downhill`
BSSID should be `mdi:wifi-star`

When you tap through to them, the correct icon names are shown on the sub-screen.

However in the list itself, these are all showing `mdi:access-point`

**To Reproduce**

**Expected behavior**

**Screenshots**

See red box (Steps is fine but didn't want to create another rectangle haha).

![sensors](https://i.imgur.com/AQwFPEu.jpg)

**Additional context**

**Comment by TomBrien** [comment]
Seems that it’s all the sensors with multi word names so I think something is up with the substitutions for ServerSideName or whatever the variable is called. Away from computer but will post the lines in morning.

**Comment by zacwest** [comment]
The sensor icons which aren't working appear to be missing from the MaterialDesignIcons that we're loading. From this list includes:

- `hiking`
- `slope-uphill`
- `slope-downhill`
