### ISSUE TITLE
Mutal TLS authentication option

### ISSUE THREAD

**Issue by bazooka423** [home-assistant/iOS#670]
To protect the HA application layer from attackers mutual TLS implemented in the application can limit access to the server like an in-app alternative to VPN.
Exposing HA on the Internet is not always desirable for security reasons. Yet for the application to operate outside of the local network some sort of connectivity is needed.
VPN has to be either enabled manually or requires always-on VPN that's more resource intensive 
Server side TLS does not limit access to the application layer only ensures it's confidentiality and integrity. 

Capability to add client certificate and use that for authenticating to the server could limit access to application. This is available with browsers (+ e.g.: reverse proxy, etc.), but the application does not currently support configuring client certificates.

**Comment by zacwest** [comment]
#27

**Comment by sp8c3** [comment]
Could you please explain why feature request #27 is closed as completed? The feature is not implemented at all
