### ISSUE TITLE
Reported Latitude incorrect

### ISSUE THREAD

**Issue by squirtbrnr** [home-assistant/iOS#684]
**iOS device model, version and app version**

Model Name: iPhone X
Software Version: iOS 13.5.1
App version: 2020.2

**Home Assistant Core Version**

0.111.0
**Describe the bug**
When I am at my home my phone will go "Away" without me moving.  When I check the GPS coordinates, it shows latitude is 0 and longitude has not changed.
**To Reproduce**
Wait a period of time and watch GPS data and geocoded location information.
**Expected behavior**
Background fetch should have the correct GPS coordinates.
**Screenshots**

<img width="337" alt="Screen Shot 2020-06-20 at 6 27 30 PM" src="https://user-images.githubusercontent.com/35356217/85213430-d8c15e80-b323-11ea-82ae-eb347dbec506.png">
<img width="367" alt="Screen Shot 2020-06-20 at 6 15 48 PM" src="https://user-images.githubusercontent.com/35356217/85213433-e1b23000-b323-11ea-927b-6271ff1ef6e3.png">
The white parts of the history bar are when this GPS issue is occurring.

**Additional context**
The last update trigger occurred 20 minutes prior to this loss of GPS data and was a background fetch.  Find my iPhone through iCloud webpage properly reports my location on the map.  If I pull down to refresh the HA app and trigger a manual update the GPS data is correct, but will go back to 0 for latitude randomly after a period of time.  Also, as soon as I open the Find My app on my phone the GPS coordinates immediately update in the HA Companion app even though I haven't opened the app yet.

'device_tracker' state during issue
```
source_type: gps
battery_level: 72
latitude: 0
longitude: -88.15713500231504
gps_accuracy: 165
altitude: 258
vertical_accuracy: 10
```

'sensor.geocoded_location' state during issue
```
Thoroughfare: N/A
Ocean: North Pacific Ocean
ISO Country Code: N/A
Postal Code: N/A
Administrative Area: N/A
Areas Of Interest: N/A
Country: N/A
Locality: N/A
Location:
  - 0
  - -88.15713500231504
Inland Water: N/A
Name: North Pacific Ocean
Sub Thoroughfare: N/A
Sub Administrative Area: N/A
Sub Locality: N/A
Time Zone: GMT-0600
friendly_name: iPhone Geocoded Location
icon: 'mdi:map'
```

'device_tracker' state after opening Find My app
```
source_type: gps
battery_level: 71
latitude: 43.XXXXX
longitude: -88.15714763408313
gps_accuracy: 65
altitude: 257.8797607421875
vertical_accuracy: 10
```

'sensor.geocoded_location' after opening Find My app
```
Thoroughfare: N/A
Ocean: N/A
ISO Country Code: US
Postal Code: '<zip>'
Administrative Area: WI
Areas Of Interest: N/A
Country: United States
Locality: <city>
Location:
  - 43.XXXXX
  - -88.15718887118811
Inland Water: N/A
Name: '<name>'
Sub Thoroughfare: N/A
Sub Administrative Area: <area>
Sub Locality: N/A
Time Zone: America/Chicago
friendly_name: iPhone Geocoded Location
icon: 'mdi:map'
```

**Comment by squirtbrnr** [comment]
Additional info:
my wife has an iPhone 7 that does not have this GPS issue or if she does have the issue, it's very infrequent and rarely happens with her phone just sitting.  But her app also won't stay running in the background even though background refresh is turned on.  But that's a separate issue.

I do not experience this gps location issue at other places such as my work or a friend's house.

**Comment by zacwest** [comment]
It sounds from your description like this is occurring only during Background Fetch. If this is the case, can you turn on the "In-Development Updating" in the app's Settings > Location. Please report back if that's improved the situation at all for you.

**Comment by squirtbrnr** [comment]
I have turned it on and will monitor things.  I can't say for sure this only happens with background refresh, but it would seem that way.

**Comment by squirtbrnr** [comment]
I enabled the In-Development Updating and still experienced the latitude reported as 0.  It happened less frequent yesterday and today, but it still happened for about 10 minutes today and twice for a few minutes yesterday.
![IMG_0551](https://user-images.githubusercontent.com/35356217/85353443-dac72100-b4cd-11ea-8d48-3e047068b556.PNG)
![IMG_0550](https://user-images.githubusercontent.com/35356217/85353446-dbf84e00-b4cd-11ea-9b66-5bacea6ececa.PNG)

**Comment by squirtbrnr** [comment]
for troubleshooting, I have reset network settings on the phone, cleared my frequent locations under general > privacy > location services, and verified my "home" location in both HA and Find My app.  One note though, Apple, Google, OpenMaps, etc don't have a lot of info on my address.  It's a valid address per the post office, but not searchable nor is it geocoded.  Waze knows about it though.  Is there an app or something that allows me to log the GPS coordinates my phone thinks it's at?  Could this be a phone issue getting a GPS lock that I'm seeing affecting HA?

**Comment by zacwest** [comment]
The device tracker location is separate from that geocoded information, so it's unlikely the geocoder failing would be the cause of your location being wrong. It's also not going to change the location by resetting the latitude to 0 at all.

Can you grab the logs (App Configuration > Event Log > look for "Current location delivery…" ones and tap on them. Does the latitude/longitude there look correct, or off? Can you also give me an idea how far off `0` latitude is from the correct location?

**Comment by squirtbrnr** [comment]
The issue occurred at 6:54:57pm Central Time Zone and lasted approximately 10 minutes until I manually refreshed the app at 7:04:26pm.  21 seconds prior to the 0 latitude the app did receive valid coordinates.  The latitude should be 43 and change.

![IMG_0552](https://user-images.githubusercontent.com/35356217/85356674-24673a00-b4d5-11ea-90fb-83aa46f02c5e.PNG)
![IMG_0554](https://user-images.githubusercontent.com/35356217/85356680-28935780-b4d5-11ea-84c1-4ac3fb263900.PNG)
The event payloads of these events are:
```
{
  "gps_accuracy" : 165,
  "battery" : 70,
  "altitude" : 258,
  "gps" : [
    43.XXXXXX,
    -88.157150109094431
  ],
  "vertical_accuracy" : 10
}
```

(21 seconds later)

```
{
  "vertical_accuracy" : 10,
  "gps_accuracy" : 165,
  "gps" : [
    0,
    -88.157135002315044
  ],
  "altitude" : 258,
  "battery" : 70
}
```

(10 minutes later)

```
{
  "gps_accuracy" : 65,
  "battery" : 69,
  "altitude" : 257.26580810546875,
  "gps" : [
    43.XXXXXX,
    -88.157276466739418
  ],
  "vertical_accuracy" : 10
}
```

**Comment by zacwest** [comment]
This is perplexing and I do not have any immediate idea on fixes. The latitude is _so_ wrong that it looks like something is setting it to 0 in a bad code path, but I'm unable to find anything in the app that indicates how it could be happening. That it fixes itself by launching other apps makes me think it is the GPS reporting back from the system with wrong values until polled again, but the new one shot code actively polls, so I am not sure.

**Comment by squirtbrnr** [comment]
That's why I was wondering if there was a way to log the GPS coordinates my phone is getting to see if this was a HA or phone issue.  But resetting network settings should have reset the GPS.  

There was something in an iOS update a while ago that I thought tried to not necessarily randomize, but maybe skew GPS coordinates such that apps tracking you had a more difficult time, but I may have read that update point wrong.

On topic though, I have not had this issue occur in the past 24 hours.  That doesn't mean it won't occur again, but all of the times my device tracker went Away, there were valid coordinates that were good in the event log payload.

**Comment by zacwest** [comment]
The GPS coordinates you saw in the event logs are the ones received from the system -- no modification is done by the app to massage the data other than asking for locations. That's why it is so perplexing how _wrong_ it is.

**Comment by TomBrien** [comment]
I see that 65 m accuracy a lot. It doesn’t have anything to do with WiFi does it? There’s no strange way that iOS is locating SSID to location is there? Or is there a cell tower nearby that has an incorrect entry for its location

**Comment by squirtbrnr** [comment]
If it was an issue with a tower with incorrect coordinates, I should see this happening on my wife's iPhone 7, but I can't say I've ever seen this issue on her phone (looking back at historical data at least).  The 65m accuracy is pretty typical I think.  I've maybe seen 50m, but it's rare.  The issue has only occurred when I am at home on WiFi.  I did have the SSID option set in the app with my home SSID, but I only use an external URL (set accordingly in the app) so maybe there's something to do with that config (external URL, no internal URL, and SSID set).  This is not a NAT loopback/hairpin NAT issue as I can access my external URL from inside.  I did remove the SSID from the app config (probably a day or two ago) but I can't say for sure if doing that has resolved the issue.

**Comment by zacwest** [comment]
Long shot, but please give the [latest beta](https://community.home-assistant.io/t/public-beta-testing-is-now-open/70450) a try. Except for iBeacon-based events, this only ever reports locations after routing through activating the GPS, so I'm curious if it helps this issue. It's also got a bit more logging, so we'll be able to get a better picture what is happening as well.

**Comment by squirtbrnr** [comment]
Ok so a bit of a twist I think... Today I finally got a geocoded location with my correct address rather than just a general city and zip code.  This may just be purely coincidental.  But! for the past few days, I have not had any incorrect gps coordinates nor has my phone just gone "away" for no reason while stationary.  It has been a few days since the last time the issue happened.  The only thing I changed other than enabling the in-development device tracking which we kind of proved above didn't change much, was I removed my SSID from the app configuration as I noted above since I'm only using an external URL.  I will continue to monitor the situation and install the latest beta in a bit.

**Comment by squirtbrnr** [comment]
It's been over 3 days and this issue has not occurred again.  The only thing I changed was removing the SSID entry within the app configuration after enabling In-Development Updating.  Unfortunately I did not have a chance to download the latest Beta in TestFlight before the new release today.  I have installed the latest release though.  I'm going to leave this issue open, but probably close it if I don't see any more issues for a few days.  I have not gotten the 0 latitude for a while now.

**Comment by zacwest** [comment]
Could you tell me what the response looks like for… (You may need to grab an access token from your profile.)

```bash
curl -X GET -H "Authorization: Bearer <long-lived access token>" \
  -H "Content-Type: application/json" \
  "http://your-host-for-ha:8123/api/config"
```

I don't need the exact response (feel free to truncate the digits), but I'm curious if you could tell me what the `latitude` and `longitude` values look like (string wrappings and all). One guess might be that it is something that's evaluating to `0` when we try and read it.

**Comment by squirtbrnr** [comment]
I think I did it right.  Had to use my external URL and created a temporary long lived token.  I grabbed probably the last 25% of the output.

`, "config_dir": "/config", "config_source": "yaml", "elevation": 256, "external_url": "https://my.domain:8123", "internal_url": "https://my.domain:8123", "latitude": 43.XXXXXXX, "location_name": "Home", "longitude": -88.XXXXXXX, "safe_mode": false, "state": "RUNNING", "time_zone": "America/Chicago", "unit_system": {"length": "mi", "mass": "lb", "pressure": "psi", "temperature": "\u00b0F", "volume": "gal"}, "version": "0.111.0", "whitelist_external_dirs": ["/config/www", "/config/tts"]}`

**Comment by robbiet480** [comment]
@squirtbrnr Just want to confirm that you replaced the decimal place digits on latitude/longitude with an equal number of X's right. (I just edited your comment to fix the JSON formatting for easier readability and replaced them with 0's so its valid JSON.)

**Comment by squirtbrnr** [comment]
Correct, there were 7 decimal places that I replaced with 7 X’s.

**Comment by squirtbrnr** [comment]
It just happened again. Latitude reported as 0. Here’s the event log payload:

`{
  "battery" : 63,
  "altitude" : 258,
  "gps_accuracy" : 165,
  "vertical_accuracy" : 10,
  "gps" : [
    0,
    -88.157501213252544
  ]
} `

I was at home, on WiFi, sitting in my living room and all of my automations for my alarm panel arming fired.

**Comment by squirtbrnr** [comment]
Ok now it’s happening very frequently. It was fine up until I got home from work around 530pm. It has happened 3 times now in the past 30 minutes. This time I immediately went into the compass app on the iPhone and it showed the correct coordinates. Pulling down to refresh within the HA Companion app did not change anything. It took at least 3 minutes and multiple force closing the app, relaunching, and forcing a location update for it to finally see the correct coordinates.
