### ISSUE TITLE
Demote "Already Monitoring: Zone - ID:" log entries

### ISSUE THREAD

**Issue by TomBrien** [home-assistant/iOS#689]
**Is your feature request related to a problem? Please describe.**

Currently every location update adds one log entry per zone stating that the zone is already being monitored and we are either inside or outside of it. This seems to fill the log up un-necessarily hiding more critical entries. See below.

**Describe the solution you'd like**
Lower the log level to a level not shown in the UI by default

Actually looking at source it seems the `ClientEventStore` doesn't have log levels. In which case I guess the solution is either to add logs levels (bonus points to a UI option to select the displayed level) or just remove https://github.com/home-assistant/iOS/blob/master/HomeAssistant/Classes/RegionManager.swift#L181-183

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/12411302/85221997-4adf8500-b3b0-11ea-9126-ca452b9594f0.png)

**Comment by zacwest** [comment]
Fixed by #698.
