### ISSUE TITLE
Docs Error: Significant Location Change vs Significant Location Update text change, TestFlight

### ISSUE THREAD

**Issue by gcobb321** [home-assistant/iOS#693]
1. While troubleshooting iCloud3 and trying to determine why some Location changes were not being detected correctly, I found the text for the Significant Location Update was changed to Significant Location Change. Just wanted to let you know the docs still say ‘Update’. 
2. I have lost the ability to download new versions of the iOS App as part of the TestFlight program, which I have had in the past. I think it was when v2 was first released. As the iCloud3 developer, it would help me keep up with the changes before they are released. Is there any way I could get an invite again ? If you need to do a PM, send it to geekstergary@gmail.com   Thanks.

**Comment by TomBrien** [comment]
Cheers for pointing out point 1. Will do that now.

On point 2, please use the link: https://testflight.apple.com/join/vcK23nBg for the current. Will close this for now. Thanks

**Comment by gcobb321** [comment]
Tom,
The TestFlight link no longer works for 2020.5. Is there new one available. Mine expired on 2020.4 and was helpful in adding support for the small zone regions.

Thanks

You an e-mail me directly at geekstergary@gmail.com.

**Comment by TomBrien** [comment]
Hi @gcobb321, there's no active TestFlight at the moment. We had to remove all the testers and builds as part of the [migration to a new developer account](https://www.home-assistant.io/blog/2020/07/28/ios-app-migration/). I think there is a new TestFlight build in the pipeline but it will (temporarily) be without critical notifications.

**Comment by gcobb321** [comment]
Tom, Any update to the TestFlight availability. I see Zac and Robbie issuing updates and want to make sure iCloud3 has no issues that I need address. I’m holding up the next release of until the next release of the iOS app is available. Unless you think it won’t break anything. Thanks

**Comment by zacwest** [comment]
The TestFlight is open: https://www.home-assistant.io/ios/beta/

**Comment by gcobb321** [comment]
My problem is I’m stuck on 2020.4.1(1) and the iOS app does not show up in TestFlight. It was removed when 2020.5 came out. From a previous note (above), It happened a couple of weeks ago when the Robbie’s developer account was moved to Nuba Casa. 

I’ve been following the 2020.5 build updates and wondered if the TestFlight invitations had gone out. The join beta on the iOS app opens a window saying “This beta isn’t accepting any new testers right now.”

**Comment by SeanPM5** [comment]
In order to complete the transition from Robbie's account to the Nabu Casa team account it was necessary to delete all beta testers for some reason. So there's a brand new TestFlight now which _everyone_ has to enroll in again. 

The link Zac posted just above should redirect to the proper new TestFlight. That will get you 2020.5 (6).

**Comment by gcobb321** [comment]
All set. I had to delete the app and then follow the link above to install 2020.5. When the iOS app was already installed, the link would just open the app.
