### ISSUE TITLE
Make alert for „Fired event“ optional 

### ISSUE THREAD

**Issue by mountainsandcode** [home-assistant/iOS#696]
**Is your feature request related to a problem? Please describe.**
Robbie, Zac and everyone else - thanks for all of your hard work on the App.

Using [URL Handlers](https://companion.home-assistant.io/docs/integrations/url-handler) is a great way to interact with Home Assistant and the iOS app - I’m using it together with NFC tags to trigger automations in the home. 

Currently, whenever these handlers are used to trigger events or run a service, there is an alert which needs to be dismissed manually.

![B78ACEED-5D49-4736-A589-95492EF56190](https://user-images.githubusercontent.com/26942220/85529811-ba9e7b80-b60d-11ea-9590-3ea01d36b249.jpeg)

**Describe the solution you'd like**
To me, this dialog is not strictly required, would be nice if we can either

- Make it optional (adding a toggle in the App Settings “Confirm successful event/ service launch using URL Handler”)
- Using a non-invasive, self-dismissing message (e.g., using https://github.com/SwiftKickMobile/SwiftMessages) at the top of the screen which automatically disappears after a few seconds

In any case, it’s not a high priority, but would be cool to be included sometime down the road :)

**Describe alternatives you've considered**
See above

**Additional context**

**Comment by zacwest** [comment]
One suggestion that I have somewhat unrelated to this specific request is to consider using Shortcuts automations for your NFC tag. You can use the app's built-in Fire Event shortcut action to be triggered from an NFC tag, and that will not require launching the app at all.

**Comment by mountainsandcode** [comment]
Thanks Zac - in this case I’m implementing something like https://github.com/maddox/magic-cards, so there are a few too many NFC’s to set up an automation for each item :)

**Comment by zacwest** [comment]
I see. In that case, there's I think 2 good options for you:

1. Use the NFC URLs that HomeAssistant can register for and use that as the contents of the NFC tag. See this [help article](https://companion.home-assistant.io/docs/integrations/universal-links).
2. Use `x-callback-url`, e.g. `homeassistant://x-callback-url/fire_event?eventName=your_event_name&dataKey=dataValue&anotherKey=anotherValue`; you can also specify other parameters, see [the docs](http://x-callback-url.com). These do not alert as they're intended to be used in scripting.

**Comment by mountainsandcode** [comment]
Fixed in #863, thanks @zacwest!
