### ISSUE TITLE
No Siri Shortcuts option in App Configuration

### ISSUE THREAD

**Issue by Vinz87** [home-assistant/iOS#704]
**iOS device model, version and app version**

Model Name: iPhone 8
Software Version: 12.4
App version: 2020.2 (5)

**Home Assistant Core Version**

v0.110.1

**Describe the bug**

I try to follow [this](https://companion.home-assistant.io/docs/integrations/siri-shortcuts/) procedure to set Siri shortcuts, but there is no "Siri Shotcuts" in App Configuration.

**To Reproduce**

**Expected behavior**

**Screenshots**

![IMG_2352](https://user-images.githubusercontent.com/6201178/85922010-a0200880-b880-11ea-8332-3c85038e4a04.PNG)
**Additional context**

**Comment by zacwest** [comment]
I believe that page is out of date; you'll need to upgrade to iOS 13 to take advantage of Siri Shortcuts.

**Comment by Vinz87** [comment]
documentation has been updated
