### ISSUE TITLE
Hide Apple Watch in Settings on iPad and iPod touch

### ISSUE THREAD

**Issue by robbiet480** [home-assistant/iOS#716]

**Comment by TomBrien** [comment]
Even better potentially on any device with an Apple Watch paired? https://developer.apple.com/forums/thread/6021

**Comment by robbiet480** [comment]
Not sure about that since I think we can't determine if one is paired until they open or install our app.

**Comment by robbiet480** [comment]
As a first step its easy enough to just hide the item if we aren't on iPhone.

**Comment by bgoncal** [comment]
Thats done in 2024.9
