### ISSUE TITLE
URL Internal / External not storing user input 

### ISSUE THREAD

**Issue by glmnet** [home-assistant/iOS#717]
**iOS device model, version and app version**

Model Name: iPhone 11
Software Version: 13.5
App version: 2020.3 (4)

**Home Assistant Core Version**

0.111.1

**Describe the bug**

URL Internal / URL External, values are not stored sometimes, may be related to the app for some reason not being able to reach the server or for unknown reason, the app seems to fall back to an older value thus deleting what you enter manually, this just confuses and gets you frustrated

My external url is properly hair pined, I'm behind two nats, but all port forwarding are setup properly.

Also, I should add that onboarding is not great for me, it is not detecting my home assistant installation, I'm not sure why. I'm using many ESPHome nodes which use mDNS discovery and I have no problem with those.

**To Reproduce**

**Expected behavior**
Store the manually entered value, even if it's wrong, it will be awesome to get a popup with an error (unresolved host, unexpected response, timeout, whatever)

**Screenshots**

**Additional context**
I reported this earlier, but got closed. https://github.com/home-assistant/iOS/issues/425

Here is another report 

https://github.com/home-assistant/iOS/issues/539

May be related: https://github.com/home-assistant/iOS/issues/459

**Comment by TomBrien** [comment]
I believe #722 will handle this

**Comment by rccoleman** [comment]
The "Connect via Cloud" also keeps getting turned off for me.  It used to stay on in previous builds, but at least 2020.4 (2) is toggling it off fairly frequently.
