### ISSUE TITLE
App requires HA version 0.104+ because of device_id

### ISSUE THREAD

**Issue by zacwest** [home-assistant/iOS#721]
App version: master/2020.3 (5)

**Home Assistant Core Version** 0.102.2

**Describe the bug**
Unable to complete onboarding due to 400 status code error.

**To Reproduce**
Attempt to onboard onto 0.102.x

**Expected behavior**
Successfully onboards

**Screenshots**
![Simulator Screen Shot - iPhone 11 Pro - 2020-06-30 at 12 20 00](https://user-images.githubusercontent.com/74188/86168561-3e081300-bacd-11ea-93b1-d9ddd4635d6b.png)

> Data does not match schema: extra keys not allowed @ data['device_id']

**Additional context**
Should check the version before sending the `device_id` param.

**Comment by TomBrien** [comment]
I mentioned this the other day. I think 0.104 January? So is a reasonable minimum version, is in line with Android then,
