### ISSUE TITLE
Use internal/external URL fields

### ISSUE THREAD

**Issue by robbiet480** [home-assistant/iOS#722]
Now that core gives a internal_url and external_url instead of just base_url we should use that to inform instead of just guessing.

**Comment by glmnet** [comment]
This is a good idea, entering these urls should be removed and force user to setup hass properly. 

Keep in mind these options are “hidden” behind the “advanced configuration” thing, so users might need to be instructed in the app on how to setup these.

**Comment by TomBrien** [comment]
Great point, Robbie do we think we can get these popped out of advanced mode only in the frontend? They feel like an important thing to have accessible

**Comment by rccoleman** [comment]
If specifying an SSID continues to be the trigger to use the "internal URL", perhaps also grab the SSID used for onboarding and automatically use it.  I'll also put in a plug for my FR about making Connect via Cloud automatically enabled when there's an active Cloud subscription: https://github.com/home-assistant/iOS/issues/745
