### ISSUE TITLE
Impossible to open menu from some addons like File Editor and MotionEye

### ISSUE THREAD

**Issue by zacwest** [home-assistant/iOS#730]
App version: 2020.3+

**Home Assistant Core Version** 0.112

**Describe the bug**
When in an addon like File Editor which hides the menu on iPhone, it isn't possible to exit the menu. Prior to 2020.3, it was possible by pulling-to-refresh which hard-reset you to the initial dashboard.

**To Reproduce**
Open File Editor.

**Expected behavior**
One can leave the File Editor or any other addon which hides the menu somehow.

**Screenshots**
<img width="387" alt="image" src="https://user-images.githubusercontent.com/74188/86294927-5ac64880-bbaa-11ea-975a-92f0067be725.png">

**Comment by TomBrien** [comment]
If that's the configurator add on, I can get the menu by swiping from left.

**Comment by zacwest** [comment]
This is me fielding a user report and reproducing it in the browser, but they indicated it wasn't possible to swipe open the menu. Above is the File Editor.

**Comment by TomBrien** [comment]
Sorry yeah that's the add on I meant. Strange that I can open menu with the same add on. Do you know the device/iOS they were using? I can open in chrome on iOS to but it's tricky to not trigger the page navigation.

**Comment by bbostock** [comment]
I have the same problem. Once I'm in the File Editor or MotionEye, it's not possible to get back to the main menu. 
I am running on iPhone XS Max iOS 13.5.1 (Latest).
Previously I could just refresh by swiping down, but this now just refreshes into wherever you were.

**Comment by TomBrien** [comment]
@bbostock Can you check that swiping from the very left most edge of the screen towards the centre doesn't work. For me it does on a Xs running iOS 13.6. Do you have any custom components that alter the user interface installed?

**Comment by bbostock** [comment]
Ah, Ok, yes if swipe from very left it brings back the menu. I wasn't swiping quite far enough to the left. many thanks.

**Comment by john-k-mcdowell** [comment]
I was the one who originally reported this as a bug and yes, I have now confirmed that if I swipe from the very left edge, I can get the menu to show for both "File Editor/Configurator" and MotionEye, so the issue should be resolved.  Thanks

**Comment by TomBrien** [comment]
Brilliant. Well I think we can close this now, but I think I am going to add a note on the docs to explain this. It isn't a nice situation where the burger icon isn't visible as it means the way to exit isn't obvious. As the UI is the same for Safari I think it's one for the frontend team to consider.

Happy to hear it's all working.
