### ISSUE TITLE
Companion App not working on iOS 14.0 beta

### ISSUE THREAD

**Issue by bgalport** [home-assistant/iOS#734]
Model Name: iPhone 11 Pro
Software Version: 14.0 Beta
App version: 2020.3 & 2020.4

**Home Assistant Core Version**
0.112.1

**Describe the bug**
The companion app not longer connects to Hassio using iOS 140 beta. Uninstalled and re-installed the app and it times out trying to authenticate. Same problem with the Home Assistant Beta 2020.4

**To Reproduce**
Install the app, configure the Home Assistant address and click Connect - See "Unknown error: The request timed out"

**Expected behavior**
Connects to Home assistant

**Screenshots**
![image](https://user-images.githubusercontent.com/3055198/86490302-d2d56f80-bd5e-11ea-8c77-8466f808dc60.png)

**Additional
 context**

**Comment by SeanPM5** [comment]
Is there anything in your Home Assistant log file (Configuration -> Logs) related to `mobile_app` integration?

**Comment by TomBrien** [comment]
I just managed to onboard on iOS 14. Only thing I noticed was that it didn't discover my instance but I think that is expected at the moment

**Comment by bgalport** [comment]
Nothing in the Home Assistant log file for mobile_app

**Comment by bgalport** [comment]
> I just managed to onboard on iOS 14. Only thing I noticed was that it didn't discover my instance but I think that is expected at the moment. How long passes between pressing connect and the timeout error?

That's interesting. The app was installed and working under iOS 13 before I upgraded. It stopped communicating after I upgraded which is when I tried unistalling and re-installing.

**Comment by TomBrien** [comment]
Timeout errors have usually been down to other errors on Home Assistant/ Do you see any components reporting that they are taking a long time to start up when you restart? Are you running on off an SD card?

**Comment by bgalport** [comment]
> Timeout errors have usually been down to other errors on Home Assistant/ Do you see any components reporting that they are taking a long time to start up when you restart? Are you running on off an SD card?

Not seeing problems with components taking a long time. Am running on a Pi 3 with a high speed sd card, so it's not exactly quick to load anyway. btw the client on my iPad under iOS 13 is still working fine.

**Comment by SeanPM5** [comment]
Hmm, in your screenshot it says you're on 4G and not Wi-Fi. 

So if you're attempting to connect to an internal / local URL while not actually on the network, this might be the reason why it's timing out and failing? Not sure if this is the issue, but something to try.

**Comment by bgalport** [comment]
> Hmm, in your screenshot it says you're on 4G and not Wi-Fi.
> 
> So if you're attempting to connect to an internal / local URL while not actually on the network, this might be the reason why it's timing out and failing? Not sure if this is the issue, but something to try.

OMG How embarrassing - Well spotted! Don't know why wifi had turned off. Now working. Sorry to all for the panic.

**Comment by bgalport** [comment]
False alarm - I had Wifi turned off - Idiot!

**Comment by TomBrien** [comment]
That error message should be improved though

**Comment by SeanPM5** [comment]
Lol no worries @bgalport, we didn't notice this at first either. There's been plenty of times I've disabled and forgot to enable WiFi :) 

I've just opened a feature request (https://github.com/home-assistant/iOS/issues/735) to catch and improve this scenario, so even though this wasn't an issue with iOS 14, it's good you brought this to our attention.
