### ISSUE TITLE
Storage sensor showing wrong data

### ISSUE THREAD

**Issue by olbjan** [home-assistant/iOS#736]
**iOS device model, version and app version**

Model Name: iPhone XS
Software Version: 13.5.1
App version: 2020.3(5)

**Home Assistant Core Version**

0.112.1
**Describe the bug**

iOS storage sensor defaults to available storage when available (opportunistic) would be the sensor value people most likely expect.

**To Reproduce**
Look at the detailed sensor values for the storage sensor. It's less than what the device settings shows for storage utilization and free storage.

**Expected behavior**
Sensor value should match what ios settings app shows.

**Screenshots**

**Additional context**

**Comment by zacwest** [comment]
I can't even tell which value the system is using. Settings.app tells me 115.8 used (so 255.93-115.8=140.13) but the values I can see are 121.27 (total), 139.87 (important), 138.58 (opportunistic).

**Comment by olbjan** [comment]
I think opportunistic or important are pretty much the real value. I believe opportunistic is the storage an app could conceivably use without impacting important functionality whilst using every byte of the "important" space number will have a negative impact where the OS will basically tell you to get rid of stuff.

**Comment by SeanPM5** [comment]
Just for another data point here's what I'm seeing.

iOS Settings app = 61.25 GB available and 256 GB capacity. 
HA Storage Sensor = 61.23 GB (Available), 61.23 GB (Important), 59.94 GB (Opportunistic), and 255.89 GB (Total)
