### ISSUE TITLE
Critial notifications don't override DND/Mute

### ISSUE THREAD

**Issue by DavidtheMaster64** [home-assistant/iOS#737]
I tried a send a critical notification to my ios app today. The phone is muted and it just vibrates like a normal notification. In the iOS setting there is also no switch for critical notifications. 
I tried to reinstall the app but no success. 
Here is the example I used:
`notify.mobile_app_iphone_von_david`
```title: "Wake up!"
message: "The house is on fire and the cat's stuck in the dryer!"
data:
  push:
    sound:
      name: default
      critical: 1
      volume: 1.0
```

**Comment by robbiet480** [comment]
This is a problem with the latest version on the App Store where Critical Alerts weren't enabled when we built it. We are in the midst of fixing it right now and hopefully the fixed version will be on the store late tonight or by Monday at the latest. Apologies for this!

**Comment by DavidtheMaster64** [comment]
Thank for the very quick reply.
Keep up the good work!

**Comment by zacwest** [comment]
The fix is out!
