### ISSUE TITLE
App header color not refreshed if theme changed in background

### ISSUE THREAD

**Issue by olekenneth** [home-assistant/iOS#739]
I flagged this in another issue: https://github.com/home-assistant/iOS/issues/645#issuecomment-647728368

Even with the newest version of the app (2020.3) and newest version of HA (112.0) this problem persists.

**To Reproduce**
- Load app and set theme to "Backend Selected"
- Go to phone home screen 
- On another device use service to change theme
- Wait for websocket disconnect? I'm changing color between day and night. So I'm not sure how long you need to wait 
- Open app again

**iOS device model, version and app version**

Model Name: iPhone XS
Software Version: iOS 13.5.1
App version: 2020.3 (5)

**Home Assistant Core Version**
112.0

**Describe the bug**
The app header color does not update when theme changes while app is in background.
I change the Backend-selected theme twice a day. Light on in the morning, until bedtime I change to a dark one. Every morning I wake up to the light theme and black app header. 

**Expected behavior**
For the app to use the correct color for the app header.

**Screenshots**
![image](https://user-images.githubusercontent.com/544388/86509459-6737e480-bde8-11ea-8851-7d272c012166.png)

**Additional context**
No

**Comment by TomBrien** [comment]
Do you see the reverse when the header fails to change to black from white?

**Comment by olekenneth** [comment]
Yes

![image](https://user-images.githubusercontent.com/544388/86510614-956df200-bdf1-11ea-9b3f-2c932a475bc3.png)

**Comment by olekenneth** [comment]
This is not really an issue anymore with the new persistent stored themes and dark mode support. I guess we can close this one?
