### ISSUE TITLE
Zoning using WiFI SSIDs

### ISSUE THREAD

**Issue by TASSDevon** [home-assistant/iOS#740]
In Android apps for HA such as Ariela, you can set up what the home SSID is, Ariela then uses this SSID to mark yourself as home if you are connected to it, or as away if you are not connected to it. This is an option to use when you don't want to have the app poll the GPS and burn more battery than required.

As I am mainly interested in whether I am home or not, and not so much where I am in the world all the time, this would most likely save quite a bit of battery on my iPhone, is this assumption correct?

Since the app already uses SSID to know when to connect to the internal URL, I am hoping it wouldn't be too much of a jump to use it to set the tracker to zone Home when connected and perhaps 'Unknown' when not connected to the home ssid.

I am wondering if this is anything that is interesting enough to be picked up in the future.

**Comment by zacwest** [comment]
You likely won't see a change in battery life using a non-location-tracking zoning approach, but you will see issues with detection. This is two-fold:

1. The app won't launch often enough, and you will rarely have an accurate location. You need something to kickstart the app, and Location Services is by far the most reliable mechanism. Note that you could also set up an iBeacon to trigger entry events which only uses BTLE. My guess is that Android's background abilities are a little more free here -- the app simply can't be told when this happens instantly.
2. Battery usage of the app is fairly low here. The app isn't tracking your location constantly, it's only updating: when entering/exiting a region, when your device changes cell towers, and for things like background fetch. The system handles waking up the app in these less-often scenarios, so the app doesn't run unless it's being told something is worth updating for happened. Apple provides a small amount of metrics here, and the app uses ~0.25% battery per day in the background at the 50th percentile and 0.60% at the 99th.

You can attack an `ssid_filter` (array of strings) on the zone to prevent 'leave' events on the zone when it is connected to a particular SSID, but I'd recommend sticking with basic location detection and seeing what real-world accuracy/usage looks like for you.
