### ISSUE TITLE
Make "Connect via Cloud" default when Nabu Casa is detected

### ISSUE THREAD

**Issue by rccoleman** [home-assistant/iOS#745]
**Is your feature request related to a problem? Please describe.**

The app detects whether the Home Assistant installation has a Nabu Casa cloud subscription active during onboarding, but the "Connect via Cloud" option in the Connection settings defaults to "off".  This causes the app to fail to connect from outside the home network even though the Nabu Casa connection is likely available, and requiring the user to manually turn it on.  For new users installing the app and subscribing to Nabu Casa, having "Connect via Cloud" default to "on" would automatically allow connections from outside the home network and provide a smoother experience.

Users who prefer to set up and use their own external connection, even when paying for a Nabu Casa subscription, can still do so by disabling the "Connect via Cloud" option.  I'm only suggesting that the default be the typical, new-user case and not one that requires additional work for new users or manual setup of an external connection.

**Additional context**

**Comment by SeanPM5** [comment]
As a Nabu Casa user, I agree with this personally. Here is a picture from onboarding which says "Nabu Casa Cloud Detected" with a green checkmark:

![image](https://i.imgur.com/apLW9WF.png)

Based on this screen, you'd expect that everything was configured and working. Yet that isn't actually the case until you drill down into App Configuration -> Connection and toggle on Connect via Cloud. 

IMO it makes no sense to detect the users external Nabu Casa URL and show that green checkmark, and then just silently ignore all that stuff. Then when they're away from home and the app isn't working, they have no clue why. Some might look around the app settings and discover this toggle, while others will just assume it's a problem with Nabu Casa or whatever.

Either way it's a frustrating user experience, and this problem could be entirely avoided by simply having the toggle be on by default.
