### ISSUE TITLE
Support OAuth Redirect authentication prior to HomeAssistant Login

### ISSUE THREAD

**Issue by shmookles** [home-assistant/iOS#750]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Is there a way to make the app work with OAuth redirect? My setup has HomeAssistant behind a Traefik revewrse-proxy, but if it doesnt recognize your device, prior to sending you to the login screen it asks you to login with your google account, which is the )auth redirect. Currently the iOS app doesnt work with this, but it would not be that hard to allow it to breakout to a mobile browser window, login through google and then continue the normal authentication method
**Describe alternatives you've considered**

**Additional context**

**Comment by stonith** [comment]
This also doesn't work on on the Android app. Looks like it was prohibited a few years ago https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html

**Comment by oscar-b** [comment]
Came here to suggest the same thing, after the recent focus on security issues I thought it might be a good idea to activate an extra layer of auth (https://github.com/thomseddon/traefik-forward-auth with Traefik) on all of my public facing services. The HA iOS app is one of them that doesn't like it very much:


```
Error 403: disallowed_useragent
Google can’t sign you in safely inside this app. You can use Google sign-in by visiting this app’s website in a browser like Safari or Chrome.
```

And the message refers to the article above that @stonith posted.

**Comment by stonith** [comment]
I ended up using GitHub as an authentication source instead of google which works without requiring this change.

**Comment by thelittlemike** [comment]
I have recently installed the Home Assistant app to try to tinker with my HA installation while on the go (actually was testing triggers for when I'm away using my phone as the tracker). Ran into this same exact issue. I take it this is still a problem. Any solution?

**Comment by stonith** [comment]
I ended up moving to GitHub for auth which doesn't have this restriction and allows for the auth flow in app. iirc I had to create an organization and put myself in it to limit access just to me though.

**Comment by thelittlemike** [comment]
> 
> 
> I ended up moving to GitHub for auth which doesn't have this restriction and allows for the auth flow in app. iirc I had to create an organization and put myself in it to limit access just to me though.

How did you set up the middleware for that? I was using Authelia initially but lately I've been finding it a bit too heavy. Something like Github auth would work just fine for me in this case.

**Comment by stonith** [comment]
> How did you set up the middleware for that? I was using Authelia initially but lately I've been finding it a bit too heavy. Something like Github auth would work just fine for me in this case.

https://github.com/oauth2-proxy/oauth2-proxy

**Comment by thelittlemike** [comment]
> 
> 
> > How did you set up the middleware for that? I was using Authelia initially but lately I've been finding it a bit too heavy. Something like Github auth would work just fine for me in this case.
> 
> https://github.com/oauth2-proxy/oauth2-proxy

Oh you're doing it through a different proxy. I'm in the same situation as @shmookles using Traefik as my reverse proxy. I've seen some other docker containers I can run to do forward auth (maintaining Google Auth) or to use other OAuth methods. I thought you found a way to do it with a middleware in Traefik.

**Comment by thelittlemike** [comment]
I stand corrected. It's been so long I forgot it wasn't supported directly in Traefik. I'm actually using the thomseddon oauth docker container. I think it will actually support other forms like Github, so I think I may try that. Thanks @stonith .

**Comment by zacwest** [comment]
https://github.com/home-assistant/iOS/discussions/1719

**Comment by mdhwoods** [comment]
Anything ever done on the ios app user agent? seems to still be an issue.  i have homeasssitant behind traefik with google oauth.   Getting error 403 disallowed_useragent. Fine logging in from browser. i really don't want to change to a different oauth setup.

TIA
