### ISSUE TITLE
Stuck at configuring sensors

### ISSUE THREAD

**Issue by TomBrien** [home-assistant/iOS#759]
**iOS device model, version and app version**

Model Name: iPhone XS / iPhone 11 Pro Max Simulator
Software Version: iOS 14beta1 / 13.4
App version: Dev @ [`42788e1`](https://github.com/home-assistant/iOS/commit/42788e16131de74562eaeba380b69c74efd9c0c4) current `master` at time of writing.

**Home Assistant Core Version**

0.112.3

**Describe the bug**

On iOS 14 with the current master branch, the app hangs at onboarding during the checklist. All tasks complete except the final "Sensors Configured" stage where, the animation loops endlessly. The only related log I can see on the HA side is:

```text
Logger: homeassistant.components.mobile_app.webhook
Source: components/mobile_app/webhook.py:163
Integration: Mobile App (documentation, issues)
First occurred: 9:40:06 (7 occurrences)
Last logged: 14:17:01

Refusing to accept unencrypted webhook from Tom’s iPhone
```

I can't see why the app is trying to send an unencrypted message on the webhook. This is a clean install and I deleted any related old integrations for the dev build. After closing the app with onboarding stuck, I get four notifications shown below. I don't see this on the simulator (which HA doesn't know)

**To Reproduce**
Install app at commit referenced above

**Expected behavior**
Onboarding to complete

**Screenshots**

![IMG_1146](https://user-images.githubusercontent.com/12411302/86788366-fef23880-c05d-11ea-916f-fbea8d8b8aaa.PNG)

**Additional context**
iOS 14 install to device done with XCode 12.0beta, sim install with 11.5

**Comment by zacwest** [comment]
ah I may have broken the encryption enabling exchange. Will take a look.

**Comment by zacwest** [comment]
I do not know why the unencrypted log happened (I can't reproduce this part) but good news: it's not a problem in any of the webhook-sending code, which was definitely my worry. It's around how we handle recreating the background url session, which really doesn't like having multiple existing.

**Comment by TomBrien** [comment]
That's good. Yep as I say I only got that error on my device not on a sim. Just chucked it up in case.
