### ISSUE TITLE
Latitude: 0 with Home Assistant Companion @iOS

### ISSUE THREAD

**Issue by KC-inDomus** [home-assistant/iOS#763]
## The problem
Suddleny, with not reason at all, while not moving, HA assumes 0 as Latitude. Longitude is ok. The tracker is from Home Assistant Companion (latest release, but happened with the previous too) on iPhone. It's about the fourth time in a couple of months.

See the screenshot: https://ibb.co/Xb53PSx

## Environment
Home Assistant Core on Venv

- Home Assistant Core release with the issue: 112
- Last working Home Assistant Core release (if known): 100.x (not sure)

**Comment by robbiet480** [comment]
Closing in favor of #684
