### ISSUE TITLE
Add Wind Down Shortcuts

### ISSUE THREAD

**Issue by TomBrien** [home-assistant/iOS#770]
**Describe the solution you'd like**
With iOS 14's Wind Down mode we can add shortcuts to the lock screen. These are designed to make it easy to run end-of-day tasks and help users finish their day off. These shortcuts are configured in Health not Shortcuts and are separate to using start or end of Wind Down as Shortcut Automation triggers. 

A small issue I can see is that these do not (I think) have user-configurable payloads in the same way that the Shortcut-configured Shortcuts do. I don't think this is a big issue as we can just send a `mobile_app.wind_down` event to Home Assistant, although this would limit to one shortcut, I guess their is a better solution. User actions can also be donated to the system to make them available as shortcuts so we might be able to make our current Actions available this way?

**Additional context**
[Example code](https://developer.apple.com/documentation/sirikit/adding_shortcuts_for_wind_down)
[WWDC Session](https://developer.apple.com/videos/play/wwdc2020/10083/)

**Comment by zacwest** [comment]
Playing around with it, I am able to add any shortcut to Wind Down by opening the shortcut, tapping (•••), and enabling "Show in Sleep Mode." Then it appears in the Health app as a option to select for Wind Down.

**Comment by TomBrien** [comment]
Yep that works. Maybe I missed it maybe it wasn't in beta 1. I probably missed it...
