### ISSUE TITLE
Top of screen is often hidden under the status bar when switching between screens

### ISSUE THREAD

**Issue by rccoleman** [home-assistant/iOS#773]
**iOS device model, version and app version**

Model Name: iPhone XS Max
Software Version: 13.5.1
App version: 2020.4 (2)

**Home Assistant Core Version**

0.112.4
**Describe the bug**

The top of the screen is often initially hidden/rendered under the status bar at the top of the screen when switching between screens in the app. This is especially true if navigating to a screen with a tab bar at the bottom and switching to another screen.  Dragging the tab bar down moves the whole screen down, exposing the hidden part at the top. 

I know this was reported in Discord, but I don’t see an issue here.

**To Reproduce**
See above. 
**Expected behavior**
The top of the screen should always be visible when navigating to a screen. 
**Screenshots**

![6352A117-165A-43D0-8782-68893655DBBC](https://user-images.githubusercontent.com/860888/87121685-2a307f80-c238-11ea-9f76-d53504a54764.png)
![F46B833D-F47C-4368-99DC-47F428DF56A4](https://user-images.githubusercontent.com/860888/87121705-387e9b80-c238-11ea-95ae-fddfed4a902f.png)

**Additional context**

**Comment by zacwest** [comment]
The scroll position in these screenshots (it looks like the page is scrolled 'upwards' - dragging down on the tab bar likely corrects this) makes me believe #606 is the "cause" but the root issue is that home-assistant/frontend#6148 needs to resolve the safe area on the bottom being present.

**Comment by rccoleman** [comment]
Yes, you’re correct. I’ll go ahead and close this based the others. Thanks!
