### ISSUE TITLE
Watch actions don’t fire until app opened on phone

### ISSUE THREAD

**Issue by TomBrien** [home-assistant/iOS#777]
**iOS device model, version and app version**

Model Name: Xs & Apple Watch 4
Software Version: iOS 14 beta 2 and WatchOS 7 beta 1
App version: 2020.4 (3)

**Home Assistant Core Version**

0.112.4

**Describe the bug**

When selecting an action on Apple Watch, the action is not fired until you open the app on the paired phone

**To Reproduce**
Open Watch app and select an action

**Expected behavior**
Action to fire immediately

**Screenshots**

**Additional context**
I have seen this before going back a bit but it’s been solid for a long time until recently. I think this was also seen in 2020.4 (2). Actions fired from the today screen work fine as do app icon shortcut actions.

**Comment by zacwest** [comment]
Does this seem new in 2020.4? The background webhook things may have broken this.

**Comment by zacwest** [comment]
Oh yeah, I need to rejigger how the background things are [configured in extensions](https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html):

> Because only one process can use a background session at a time, you need to create a different background session for the containing app and each of its app extensions. (Each background session should have a unique identifier.) It’s recommended that your containing app only use a background session that was created by one of its extensions when the app is launched in the background to handle events for that extension. If you need to perform other network-related tasks in your containing app, create different URL sessions for them.

Shouldn't be too bad, just need a little bit of logic to use separate identifiers and to create some on the fly in the main app.

**Comment by TomBrien** [comment]
Yep it does seem new in 2020.4 (3) I think. I don't have actions on my dev build because it's a pain to keep setting up and I'm lazy...

Sounds good. I'll keep an eye out for a PR and give it a spin if needed.

**Comment by TomBrien** [comment]
Still seeing this in 2020.4 (4). It seems to come and go. I do notice that when I reopen the app I get the orange settings cog and the reconnecting text at the bottom of the scree for a split second normally. However, if I: fire action from watch, open app to _bump_ it (and see cog/reconnecting), close app and fire another action. That second action still doesn't fire until I reopen the app and then I don't see the cog...

As I say this comes and goes through the day. It was fine when 2020.4 (4) released and first thing this morning, then went bad, started working again and has gone bad again now.
