### ISSUE TITLE
use of unresolved identifier 'SDStatusBarManager' and failure to launch

### ISSUE THREAD

**Issue by aakarshsasi** [home-assistant/iOS#779]
**iPhone 8,iOS 13.5,**

Model Name: iPhone 8 (simulator)
Software Version: iOS 13.5, Xcode 11.5
App version: 2020.4 (4)

**Home Assistant Core Version**

**Describe the bug**
When I try to compile and run the project I'm always getting the error use of unresolved identifier 'SDStatusBarManager'
So if I comment out SDStatusBarManager.sharedInstance()?.enableOverrides() the build is successful but the app won't launch.
```
The request to open "io.robbie.HomeAssistant" failed.
Domain: FBSOpenApplicationServiceErrorDomain
Code: 1
Failure Reason: The request was denied by service delegate (SBMainWorkspace) for reason: Unspecified ("null").
User Info: {
    BSErrorCodeDescription = RequestDenied;
    FBSOpenApplicationRequestID = 0x668d;
}
--
The operation couldn’t be completed. (null)
Domain: FBSOpenApplicationErrorDomain
Code: 1
Failure Reason: (null)
User Info: {
    BSErrorCodeDescription = Unspecified;
}
```
--

**To Reproduce**
I don't know if I am doing something wrong because I did all the steps mentioned in the instructions
```
bundle install
pod install --repo-update
bundle exec pod install
```
**Expected behavior**
App launching smoothly

**Comment by zacwest** [comment]
This use of the status bar manager is only baked into the Debug Configuration, so you must use the Debug scheme to execute the app when the app thinks it is in Debug mode.
