### ISSUE TITLE
Siri Responses to Shortcut Actions are too verbose

### ISSUE THREAD

**Issue by xilluzionx** [home-assistant/iOS#783]
When using Siri Shortcuts to run services and automations, she responds with a very raw recollection of the actions in the shortcut.  

Hey Siri, Open Sesame!
Okay, successfully called cover.open_cover.

Would be great if there were a way to provide an override response such as, "Welcome home, opening the garage." instead.

**Comment by niemyjski** [comment]
I'd rather have any deep link or shortcut to not open the app, show an alert box or any message (maybe the message returned should be defined in the query string or shortcut payload.

**Comment by andystewart999** [comment]
I'd much rather have the ability to control what Home Assistant returns, which is presumably what Siri is just repeating.  For example, if I run the Shortcut 'Solar generation' to have a 'Have Siri say this' property along the lines of 'Your solar panels are generating' + solar_generation.state + ' watts'.

Is that already a thing?  I've been looking for ages.
