### ISSUE TITLE
Event Log "Payload" UI

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/iOS#790]
**Is your feature request related to a problem? Please describe.**
Had this idea for Event Log, there are two minor additions that I think would make troubleshooting a lot easier.

**Describe the solution you'd like**

1. When you drill down into the payload, there is no "title" (for lack of a better description) among the payload. You just get some JSON, but it doesn't say what event you're looking at or what time the event occurred. Seems like it'd be a good idea to put that info here as well?

2. When an event has GPS coordinates (location update), it might help to show a map view with a marker of those coordinates. This will help the user to much more easily troubleshoot things and determine where something may have went wrong.

Below is a very rough "mockup" / idea of what I mean.

![image](https://i.imgur.com/VZYfWEY.jpg)

**Describe alternatives you've considered**

**Additional context**

**Comment by zacwest** [comment]
It would probably be good to also show the monitored regions that exist at the time the location was captured. Would help remote debugging, too.
