### ISSUE TITLE
Large database storage size caused by fast periodic sensors

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/iOS#797]
**iOS device model, version and app version**

Model Name: iPhone 11 Pro
Software Version: iOS 14 Dev B2
App version: 2020.4 (7)

**Home Assistant Core Version**

0.113.0b1

**Describe the bug**

Was just checking iOS storage and Home Assistant Companion is now one of the largest apps on my phone. I think this is because I have periodic sensors set to 20 seconds and have the app open quite a bit, along with lots of zones (23). 

I suspect the large database size is mostly from logging everything that's happening in Event Log. Info on 23 zones being reported every 20 seconds etc.. 

![image](https://i.imgur.com/aYmHpUh.jpg)

**To Reproduce**

**Expected behavior**
Some other apps I use like Apollo for Reddit as an example, has a "Clear Cache" button in the app. Home Assistant Companion already has one but it's just for resetting the frontend cache, not the app cache. Maybe "Reset App Cache" is worth adding?

Or maybe it should just set a hard limit on how much logs are kept?

I guess there's the Clear log button in Event Log too which may or may not solve this. I never really press that in case info is needed from me for beta testing purposes.

**Screenshots**

**Additional context**

**Comment by zacwest** [comment]
The database you just sent me is 20mb so I'm betting something else is creeping up in disk space. Could you use iExplorer to take a look at what's in the app's documents? It might be something we're not keeping track of.

**Comment by SeanPM5** [comment]
I have to help paint for a couple hours so won't be home much of the day, but will look into that app tonight or tomorrow.  Will be interesting to see what it ends up being. 

I should have pointed out I have a 256GB iPhone so there's more usable space for cache. But even then 700+mb seems pretty excessive for this type of app as there's no images/videos or anything being cached afaik. I have other media-centric apps like Netflix that take less storage.
