### ISSUE TITLE
Use friendly name instead of entity ID for Zone notifications

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/iOS#802]
**Is your feature request related to a problem? Please describe.**

The other day when testing some location stuff, I turned on "Enter Zone Notifications" and "Exit Zone Notifications" under App Configuration -> Notifications. These show the entity ID of the zone, rather than the friendly name. Entity ID isn't as readable at a quick glance for two reasons:

1. One word, often long, any spaces or apostrophes are replaced with ugly underscores
2. The important information like enter/exit is listed at the very end rather than the beginning

![image](https://i.imgur.com/RNc4cGg.jpg)

**Describe the solution you'd like**
I propose that it use the friendly name instead. Using above screenshot as an example, it would instead say:

Entered Walmart Riverdale
Exited Walmart Riverdale

or this wording is perhaps more common:

Arrived at Megan's
Left Megan's

**Describe alternatives you've considered**

**Additional context**

**Comment by SeanPM5** [comment]
Fixed by Tom in https://github.com/home-assistant/iOS/pull/1224

**Comment by TomBrien** [comment]
Sorry Sean, totally missed this issue. Sorry for dupeing. I agree on the wording too. That's all in the translations so can tweak easily now.

**Comment by SeanPM5** [comment]
All good, had forgotten I created this issue myself until your PR jogged my memory :)   
Nice work 👍
