### ISSUE TITLE
App Icon Quick Actions missing

### ISSUE THREAD

**Issue by TomBrien** [home-assistant/iOS#814]
**iOS device model, version and app version**

Model Name: Xs
Software Version: iOS 14b2 
App version: 2020.4(7)

**Home Assistant Core Version**

N/A

**Describe the bug**

In iOS 14 the quick actions (the stylised action buttons accessed through "tap-and-holding"ing the App Icon are missing the Short cut list of actions is there but not the buttons.

**To Reproduce**

1) Set up actions
2) Tap and hold app icon, results in:
    * iOS 13 and earlier: shortcut list and action buttons in a view similar to the Today View widget
    * iOS 14: Shortcut list only

**Expected behavior**

To see both the action buttons and the shortcuts

**Screenshots**

**Additional context**
Maybe we don't actually need both I think both the widget view of buttons and the shortcut list only showed the first 4 actions (3 for the shortcuts on beta builds). This does seem like unneeded duplication. Would be better to get more actions in this interface.

**Comment by zacwest** [comment]
I don't think iOS 14 is showing the widgets when opening the context menu for apps any more. For example, Calendar doesn't show a widget above it anymore either.

**Comment by TomBrien** [comment]
I think we just let it go and remove references to it from docs?

**Comment by zacwest** [comment]
Yeah, that sounds about right. This is Apple removing something, not us choosing to.
