### ISSUE TITLE
Didn't Update: location update from the past every time app opened (same timestamp)

### ISSUE THREAD

**Issue by TomBrien** [home-assistant/iOS#816]
**iOS device model, version and app version**

Model Name: Xs
Software Version: iOS 14b2
App version: 2020.4(8)

**Home Assistant Core Version**

0.112.4

**Describe the bug**

Every time I open the app either from background or after force quitting, a "Didn't Update: location update from the past", if I look at the payload the time given in the `event` key is always the same, 20/07/2020 17:41:26 BST.

**To Reproduce**
1. Open app
    * After this go to the event log and view the error

**Expected behavior**
Location to update and no log entry generated

**Screenshots**

![image](https://user-images.githubusercontent.com/12411302/87988188-d8a9af80-cad7-11ea-9b71-ed834bc3ad6b.png)

![image](https://user-images.githubusercontent.com/12411302/87988011-7e105380-cad7-11ea-8941-cea94c29818f.png)

**Additional context**

**Comment by TomBrien** [comment]
Looking through logs shows this started in 2020.4 build 8

**Comment by zacwest** [comment]
This is somewhat expected, it depends on what the system provides when we start doing significant location change monitoring. I made it discard the older location updates specifically to avoid being told to update when there's no need to do so (which also matches what the app was doing before).

**Comment by TomBrien** [comment]
So the time it's giving is when I last got home so that's why it's not updating? Might be worth demoting this to a level hidden from the app log, it's a bit spammy.

**Comment by zacwest** [comment]
Yeah, that particular one isn't super useful. I made a conscious effort to make every possible failure case result in a log so that it's easier to debug later, but this particular one and a couple like it are more advisory.

**Comment by bgoncal** [comment]
Is this still an issue with latest versions of app and core? Feel free to reopen if needed

**Comment by johnshardman** [comment]
I am seeing this ("Didn't update: location update from the past" since 31 March 2024, which happens to be when British Summer Time started. Not sure if the clock change is related, or whether the event log only shows information back to 31st March (today is 11th April).
