### ISSUE TITLE
Is it possible to add the iPhone uptime as an attribute?

### ISSUE THREAD

**Issue by gieljnssns** [home-assistant/iOS#818]
**Is your feature request related to a problem? Please describe.**

x
**Describe the solution you'd like**
I would like to see the uptime as an attribute
**Describe alternatives you've considered**

x
**Additional context**
Because I think it's not bad to restart your iPhone once in x. And my wife always forgets that, so I can send a notification.

**Comment by robbiet480** [comment]
[It appears possible](https://stackoverflow.com/questions/36203662/getting-system-uptime-in-ios-swift)

**Comment by zacwest** [comment]
It feels a bit like overkill to create a new sensor for this, but I could see it being useful as a battery state attribute. What do you think?

**Comment by gieljnssns** [comment]
I'm ok with that!
