### ISSUE TITLE
Auto-Import Push Categories

### ISSUE THREAD

**Issue by CCOSTAN** [home-assistant/iOS#825]
Is there a technical reason that Push Categories aren't imported automatically in the HA IOS Companion?  

I'm running into Challenges with Family members getting the latest Push Categories as I build out new ones.  Seems like something you would always want to happen.  I can't really think of a scenario that you would connect an HA instance and NOT want the Push Categories. 

Thanks
CARLO

**Comment by zacwest** [comment]
Good timing on this request, I've been cleaning up how we load and persist things this week.

**Comment by CCOSTAN** [comment]
Thanks Zac!  This is awesome!  Can't wait to test/implement it.   Time for me to start building out more and more IOS actionable notifications.  :) 

Thanks Again!
