### ISSUE TITLE
device tracker is set to passive zone

### ISSUE THREAD

**Issue by b3nj1** [home-assistant/iOS#828]
Model Name: iPhone 11 Pro
Software Version: 13.5.1
App version: 2020.4 (FYI: This version appears in the App Store, but not here 'Please also give the app version listed beneath "Home Assistant Companion" in the App Configuration>About menu within the app)

**Home Assistant Core Version: 0.113.0 (also happened in 0.112.5)

**Describe the bug**

I’m seeing new behavior with the current App Store version of the app, 2020.4. I have “passive” zones which have coordinates+radius inside my Home zone. These zones are beacon zones. My understanding of “passive” is that they should not set the state of device trackers, however with the latest app, my iOS device_tracker location is being set to these passive zones. As a result, my “person” device thinks I am not “Home”, but instead thinks I’m in the beacon zone.

I don't know if the same happens with "passive" zones that are not beacon zones. I can create a test zone if that helps.

**To Reproduce**
Setup a zone which is passive and has a beacon.
Enter zone.
Device tracker shows as in this passive zone.

**Expected behavior**
In the previous version, when entering a passive+beacon zone which was within a "regular zone" the device tracker was set to the "regular zone" instead of the passive/beacon zone. This seemed consistent with the home assistant documentation regarding passive zones.

**Additional context**
I tried to trace through the code to see when this behavior was introduced, but quite a bit has changed. I do see that in the newer code a new "isPassive" variable has been added but it's not clear where or if it influences how status is updated.

Thanks for any help!!

**Comment by zacwest** [comment]
Before 2020.4, can you describe what would happen for these beacon entry events? Would it just update your GPS location to the zone's?

**Comment by zacwest** [comment]
For historic sake, this is the commit that flipped the switch from the old region/zone monitoring to the new: #753

**Comment by b3nj1** [comment]
@zacwest , I believe what you say is correct. I looked at the logs for the app, and when it shows an update it is with the beacon’s coordinates. 

Thanks

**Comment by CAB426** [comment]
I am seeing the same behavior.  What I understand should happen would be when a zone is `passive: true` the enter/exit zone event is fired, however the `device_tracker` is not updated to reflect the passive zone.  

Use case would be beacons in rooms at `home`.  Your `device_tracker` would be `home`, but the enter/exit events of the beacon would fire an event.  This would allow you to automate tasks, while not changing your location.

**Comment by b3nj1** [comment]
That would be my expectation too - including the *exit* behavior. Is there a reason that the beacons currently only update on enter?

In addition, it would be nice if the device tracker event included an attribute identifying the beacon.

My current workaround is to have duplicate device_tracker entities. When events come in, I convert beacon locations to be "home".

**Comment by CAB426** [comment]
Just an idea, but for passive zones, this could be handled with a custom `event_type` being sent.  Something simple like `zone_enter`/`zone.enter` and `zone_leave`/`zone.leave` with the data including the zone entity_id.

```
{
    "event_type": "zone_enter",
    "data": {
        "entity_id": "zone.front_door"
    }
}
```
```
{
    "event_type": "zone_leave",
    "data": {
        "entity_id": "zone.front_door"
    }
}
```

These events would be easy to pick up in automations and Node-Red.

Automations Example:
```
trigger:
    platform: event
    event_type: zone_enter
  condition:
    condition: template
    value_template: >
      {{ trigger.event.data.entity_id == 'zone.front_door' }}
```

Taking it a step further and tying it into [subzones](https://community.home-assistant.io/t/ibeacons-unusable-when-having-a-home-zone-add-subzones-solved-with-workaround/203819) would be a nice feature. That would require the addition of subzones to core, but it would be nice to have rooms or areas defined with beacons around your zones.

**Comment by CAB426** [comment]
Put in a new feature request for these updates: #924

**Comment by CAB426** [comment]
@b3nj1 Not sure if you saw this [926](https://github.com/home-assistant/iOS/pull/926) PR.

Next update will include an event for zone_enter and zone_exit for passive zones while not setting the device_tracker to that zone.  I think this issue can be closed with these changes.

**Comment by zacwest** [comment]
Indeed, I believe this is resolved. Please give the [TestFlight build](https://www.home-assistant.io/ios/beta) to validate if you're interested.
