### ISSUE TITLE
App freezes during onboarding if you switch to another app to retrieve 2FA code.

### ISSUE THREAD

**Issue by stimpy2318** [home-assistant/iOS#832]
**iOS device model, version and app version**

Model Name: iPhone Xs Max
Software Version: 13.6
App version: 2020.4 (unable to retrieve value from in brackets since I can't complete onboarding but latest as of 2020/07/25)

**Home Assistant Core Version**
0.113.1

**Describe the bug**
When trying to correct issues with app notifications no longer working, I removed ios and mobile app integrations from Home Assistant Core and deleted and reinstalled the iOS app. Now when attempting to complete on-boarding in the iOS app it will hang and not allow any input once I reach the 2FA code screen after entering my username and password and after switching to my 2FA app (Google Authenticator) on the same device to retrieve the code. Prior to switching to 2FA app I can enter values in the 2FA field but since I don't know what the value is until I switch I cannot enter it and it changes too rapidly to look it up before starting the onboarding process.

**To Reproduce**
Start with a fresh onboarding with 2FA enabled on your user account in Home Assistant. Once you get to the 2FA screen in the onboarding process switch to another app on your phone (I don't think it matters what app you switch to but I was swiping to get to Google Authenticator) once you have your 2FA code from the other app switch back to Home Assistant app and you will be unable to enter any values into the 2FA field, the keyboard will not show up the cursor will not display when you tap in the field, you cannot paste into the field, the cancel button is non-functional on the login screen as well. Also this effect happens if you switch to another app when on the Login screen prior to the 2FA screen. Note: You may need to stay on the switched to app for a few seconds to reproduce, in one test when I switched and came back very rapidly I was still able to enter data.

**Expected behavior**
App switching won't disable input into password or 2FA fields or cause the app to seemingly freeze up.

**Additional Context**
The app is attempting to authenticate via the Nabu Casa URL for my home assistant install when this occurs. I am now attempting to disable 2FA temporarily to see if I can get around this problem.

**Comment by stimpy2318** [comment]
Temporarily disabling 2FA on my user in HA, then performing the onboarding at least got me through that. Not certain if 2FA will be a problem in the future though on the App haven't tested logging out and then in again yet.

**Comment by zacwest** [comment]
I'm having trouble reproducing this, and the screen which has you enter this information is largely the same as what happens in Safari  -- would you mind trying this flow in the browser and see if it has a similar issue?

**Comment by stimpy2318** [comment]
I will try to make some time in a few hours to remove the integration again and going through the 2FA authentication part via Safari on my phone and update you with the results.

**Comment by B-Hartley** [comment]
I’ve got this problem. But it is much more widespread. My app is locking up / crashing on any and all screens. Particularly if you switch out of app and back in. 
So I’m
Not sure this is related to 2Fa. I think it is a wider issue.

**Comment by TomBrien** [comment]
@B-Hartley what device do you have and what app version and Home Assistant version are you running?

**Comment by B-Hartley** [comment]
Apologies, I have an iPhone 11 Pro, my wife has a Max with the same issue.
Both on iOS 13.6

Home assistant is:

```
arch | x86_64
chassis | embedded
dev | false
docker | true
docker_version | 19.03.8
hassio | true
host_os | HassOS 4.11
installation_type | Home Assistant OS
os_name | Linux
os_version | 5.4.50
python_version | 3.8.3
supervisor | 229
timezone | Europe/London
version | 0.113.2
virtualenv | false


```

It's started in last 2 days.
App unreponsive.
Occasionally comes to life briefly.
Have uninstalled, rebooted, reinstalled - no change.

**Comment by TomBrien** [comment]
Are you running app version 2020.4.1? You can check in the "about" section in App Configuration

@zacwest flagging this to you.

**Comment by B-Hartley** [comment]
Yes, 2020.4.1 (1) - but I'm not sure it is App related, I can recreate the issue using the website access in iOS web app (saved to the homescreen) mode.
I've just restarted home assistant and the app is functional again.  But I suspect that in a short time it won't be.

**Comment by TomBrien** [comment]
What's the experience like if you use Safari to access Home Assistant on your iPhone?

**Comment by B-Hartley** [comment]
Safari works perfectly. 
But if I save as a bookmark to the home screen it then fails.

**Comment by IIAIronWolf** [comment]
I also had this issue. With the iOS team change, I had to log back in to the HA iOS App and could not paste my password. Likewise, could not retrieve my 2FA code, because when you leave the iOS app, HA reloads when you come back, causing you to have to start the login from the beginning again.

**Comment by zacwest** [comment]
You are likely reporting a different issue - on iOS 14 betas, the app will crash when backgrounding the app. There's a temporary workaround in the [TestFlight builds](https://www.home-assistant.io/ios/beta) which can mitigate this, but it isn't a full solution.

**Comment by IIAIronWolf** [comment]
@zacwest Understood. I am on the iOS 14 developer beta, so I cannot test if this happens on iOS 13, but maybe that is the only reason it reloads each time I leave the app and come back.

**Comment by d0ugal** [comment]
I am also hitting the same issue as @IIAIronWolf on the iOS 14 beta.

**Comment by zacwest** [comment]
Haven't seen this since the iOS 14 betas, presumably this was something Apple fixed.
