### ISSUE TITLE
Additional Shortcuts actions (Activate Scene, Trigger Automation, Run Script)

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/iOS#840]
**Is your feature request related to a problem? Please describe.**
Currently to do simple things in Shortcuts like activate a scene, you need to either use JSON (not user friendly) or place the Dictionary action inside your shortcut (easier but less obvious). And after using the "Call Service" action and selecting `scene.turn_on` service there's still no way to actually _see_ all your available scenes; you'd need to either remember the entity ID or go looking through the HA app for it. Not totally user-friendly IMO.

**Describe the solution you'd like**
I just remembered an older idea I had in https://github.com/home-assistant/iOS/issues/314. I closed that issue last year during the 2.0 beta when Shortcuts creation was moved outside of the Home Assistant iOS app and done completely in the iOS 13 Shortcuts app. But after giving this another thought, I think a tweaked version of that idea could still work and be extremely useful.

Basically with this idea, there'd be an "Activate Scene" action and then you simply tap the variable to see all your scenes and pick from the list. The existing "Call Service" action already retrieves all the services from your Home Assistant instance, this would be doing the same thing except just showing scenes. The user flow would be very similar to the "Control Home" action of the default Home app:

![image](https://i.imgur.com/XiL5Um0.jpg)
![image](https://i.imgur.com/1rv8met.jpg)

There'd be two other actions "Trigger automation" and "Run script" that would work the same way. I think that would handle probably like 90% of use cases in a super easy and user-friendly way. The "Call Service" action would still exist for the lesser-used or more advanced stuff not handled by those three actions.

**Comment by TomBrien** [comment]
Any thing like you can see in #838?

**Comment by SeanPM5** [comment]
Those are excellent additions, and along the same lines of making this stuff easier. 

But the difference (from what I can tell) is those you create within the HA app, this FR would let you do everything completely within the Shortcuts app itself.

**Comment by davet2001** [comment]
I see that scenes are now supported in this way. Works great.

Is it possible to extend this to allow automations and scripts to be triggered?

My use case is that I want to trigger them by an rfid tag without having to confirm.

**Comment by zacwest** [comment]
You can execute any service call, including triggering automations or scripts, using the 'call service' Shortcut. This ticket is about making them more accessible by adding helper shortcuts.

**Comment by davet2001** [comment]
Yes, exactly. I would like to select from some options on the screen. 

I tried manually typing the json and couldn't get it to work. Probably I typed something wrong.

**Comment by zacwest** [comment]
You can also avoid writing JSON manually by using the "Dictionary" action to craft the input to the service call.

**Comment by davet2001** [comment]
Sounds great but that's still pretty complicated.  It's not obvious what to type. I assume it's following the pattern [here](https://www.home-assistant.io/docs/scripts/service-calls/). 

Seeing the script and automation friendly names in the shortcuts app would be way more helpful.

**Comment by SeanPM5** [comment]
Here's an example on how you can trigger an automation or turn on a script via Shortcuts:

![examples](https://i.imgur.com/iWzbH89.jpg)

You can copy and paste the JSON from the above examples here, and then just customize it to fit your entity ID:

`{"entity_id":"automation.morning_routine"}`

And here's an example of the Dictionary method that Zac mentioned: 

![dictionary](https://i.imgur.com/AtxAQfW.jpg)

You can use whichever method you prefer. After you create one, you can just duplicate that Shortcut which makes future ones easier.

So this is possible already, but not too user-friendly or accessible at the moment. Typing JSON on the iOS keyboard is a drag, and looking up the entity ID is also kind of a pain. Hence this feature request exploring ways to make it less complicated :)
