### ISSUE TITLE
Input_Numbers UI

### ISSUE THREAD

**Issue by kyleteal** [home-assistant/iOS#870]
Input numbers in the companion app on ios are quite hard to change. It would be nice to have some kind of up/down arrow that can be clicked to changed. Love the app, thanks for all you guys do!

**Comment by TomBrien** [comment]
This feels like a front end issue. The app doesn't handle much in terms of the appearance of Home Assistant. Can you check if you have the same problem when view your Home Assistant in Safari on iOS

**Comment by kyleteal** [comment]
That makes since, thanks. On the web there are arrows when you hover but they are quite small.

**Comment by TomBrien** [comment]
If it's an issue that is affecting usability on your phone, and it sounds like it is. I suggest you [raise an issue on the Frontend repo](https://github.com/home-assistant/frontend/issues/new/choose). As this isn't caused by the app, can I now close this issue?

**Comment by kyleteal** [comment]
will do thanks
