### ISSUE TITLE
Prevent iPad from falling asleep with settings

### ISSUE THREAD

**Issue by olekenneth** [home-assistant/iOS#871]
**Describe the solution you'd like**
I have a iPad tablet on the wall with a charger I can control. So I would like to have the screen not turn off during the day (charger on) and turn off at night (charger off). And then I have to manually wake it up again next morning.

**Describe alternatives you've considered**
It's straight forward to implement:
`UIApplication.shared.isIdleTimerDisabled = true`

But using this library you already have to options/settings I want. Always/whenCharging/disabled  
https://github.com/ochococo/Insomnia

The settings could always be exposed as a switch to frontend - for other automations. 
**Additional context**

**Comment by zacwest** [comment]
This will require implementing support for switches and/or service calls in mobile_app core.

**Comment by olekenneth** [comment]
Not necessarily. The last sentence I wrote. Is really just a nice to have feature. Not need to have. 

I really just would want the option in the app to keep the screen on while connected to power.

**Comment by zacwest** [comment]
What I'd like to avoid is writing an automation engine in the app, e.g. "when the battery turns to state off, re-enable the auto timer". Feeding this information and control into Home Assistant is much more consistent and easier to add more features to.

**Comment by olekenneth** [comment]
Sure. But like I'm saying in the original post; adding Insomnia (library) this will happen automatically.
