### ISSUE TITLE
Weather card icons not visible

### ISSUE THREAD

**Issue by PierreScerri** [home-assistant/iOS#872]
**iOS device model, version and app version**

Model Name: iPhoneX
Software Version: 13.6
App version: 2020.4.1(1)

**Home Assistant Core Version**

0.113.3

**Describe the bug**
On first access to the tab that contains https://github.com/bramkragten/weather-card, the icons are not there. 
To get the icons i have to refresh the page or go to another tab and come back.
Card works fine on Chrome and Safari.

**To Reproduce**
Open Companion App and select tab containing the Weather-card

**Expected behavior**
Animated icons should be visible

**Screenshots**

![IMG_7200](https://user-images.githubusercontent.com/34303331/89505288-aaabb700-d7c9-11ea-8c87-353ff96bc308.jpg)

**Additional context**

**Comment by TomBrien** [comment]
I have what I think is the same card in my main Home Assistant instance and it's seems to work with the app including the image animation. What file format are you using and where are the images stored. The fact it works in safari in iOS and not the app is strange as essentially the app is just wrapped around a Safari view. Can you try resetting the front end cache in the App Configuration. Only difference is I have the card on my main view. 

![image](https://user-images.githubusercontent.com/12411302/89580976-1fb0d800-d82e-11ea-83e4-1b5e08ff3cb0.jpeg)

**Comment by PierreScerri** [comment]
As I said before, the icons are not there when it is accessed at first.  Refreshing or going to another tab and back makes the icons visible.

**Comment by PierreScerri** [comment]
I have installed the card through HACS.  I can find the card in config/www/community but I don't know where the icons are.
I have tried moving the card around within tabs and across tabs.  It may depend on its position, but I cant quite figure out how.

**Comment by bgoncal** [comment]
Do you still experience the same on the latest core and companion app version?

**Comment by bgoncal** [comment]
Feel free to reopen this issue if needed
