### ISSUE TITLE
Connected Via always reports External URL

### ISSUE THREAD

**Issue by littlemtravis** [home-assistant/iOS#876]
**iOS device model, version and app version**

Model Name: iPhone 8
Software Version: 13.5.1
App version: 2020.4.1 (1)

**Home Assistant Core Version**

0.113.3

**Describe the bug**
When viewing the connection details the app always reports that it is connected via External URL.  I have included the SSIS of my router, but it still does not change to the Internal URL.  I am using NGINX, and have the External URL configured to my duckdns domain.  When I switch off the WiFi I am able to get connected to HA, but when I am on my WiFi I cannot get the app to connect.

**To Reproduce**
Open HomaAssistant iOS app, view the connection details.
Connected via always reports External URL.

**Expected behavior**
When connected to my WiFi, HomeAssistant iOS app should connect to via Internal URL.

**Screenshots**

![IMG_9464](https://user-images.githubusercontent.com/8172865/89640493-53632080-d875-11ea-8688-101dd15d5e66.PNG)![IMG_9465](https://user-images.githubusercontent.com/8172865/89640495-53fbb700-d875-11ea-8217-fc8a1e0860cb.PNG)

**Additional context**

**Comment by zacwest** [comment]
You do not have an internal URL set in the screeshot above. The placeholder there is descriptive and not explaining what the default value is, which admittedly is very confusing.

**Comment by zacwest** [comment]
Just updated the string to be `e.g. http://…` to be more clear.

**Comment by littlemtravis** [comment]
That was it.  Thanks
