### ISSUE TITLE
Material Design Icons version outdated

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/iOS#877]
**iOS device model, version and app version**

Model Name: iPhone 11 Pro
Software Version: iOS 14 Dev B4
App version: 2020.5 (3) TestFlight

**Home Assistant Core Version**

**Describe the bug**
Mentioned this on Discord last night but just creating an issue for safe measure so it doesn't get forgotten. Home Assistant uses Material Design Icons v5.4.55 now (see https://github.com/home-assistant/frontend/pull/6485), but the ones inside the iOS app are older (v4).

So if the user has updated their icons to the new names (as the 0.113 Logs instruct them to do), this causes them to disappear from the app and show a default `mdi:ping` icon or whatever. 

**To Reproduce**

**Expected behavior**
Icons should use the same version as included with HA, so there isn't this inconsistency.

**Screenshots**

![image](https://i.imgur.com/Hcqe6Ch.jpg)

**Additional context**

**Comment by bcmitri** [comment]
This works for me. See below. 
![966FD1A3-A94A-41EB-8C41-80FB36C22E54](https://user-images.githubusercontent.com/53234043/89712424-3149cb00-d967-11ea-96f7-1b38321537d0.jpeg)
![4748E1B1-0FD1-49B8-B0BD-7E3F2E11C449](https://user-images.githubusercontent.com/53234043/89712426-33138e80-d967-11ea-8a0b-d02371e105f3.jpeg)

**Comment by TomBrien** [comment]
The icon's you are seeing there are provided by home assistant. The app has to provide its own set for use in actions and complications along with within the App Configuration menu
