### ISSUE TITLE
do not disturb sensor

### ISSUE THREAD

**Issue by basesnow** [home-assistant/iOS#878]
**Is your feature request related to a problem? Please describe.**
Currently the companion app cannot determine if your device is in DND mode.

**Describe the solution you'd like**
A binary sensor to track DND per device.

**Describe alternatives you've considered**
Can't think of any.

**Additional context**
This would be really useful for using as a condition to turn notifications into critical notifications based on the devices DND state. I like critical notifications since they break through DND. However, I prefer standard notifications when I have DND off.

**Comment by TomBrien** [comment]
This would be awesome however due to the way sensors update from the app it may not be the most reliable

**Comment by mountainsandcode** [comment]
Great idea! 

You can use device automations in the Shortcuts App to reliably trigger fully in the background when DND is enabled/disabled - this could be used in conjunction with a new HA App Shortcut to update the sensors (or does this already happen when the Send Location shortcut is triggered?)

**Comment by zacwest** [comment]
This is implemented for iOS 15 / macOS 12, which offers Focus status as a sensor, as long as Apple doesn't lock it down before release. #1664
