### ISSUE TITLE
crash on iOS 12.4.8 App 20.20.5

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/iOS#898]
**iOS device model, version and app version**

Model Name: iPhone 5s
Software Version: 12.4.8
App version: 

**Home Assistant Core Version**

113.4
**Describe the bug**
After updating to 20.20.5 (7) the app immediately crashes on opening. repeatedly

**To Reproduce**

**Expected behavior**
dont crash ;-)

**Screenshots**

**Additional context**

Wouldn't have updated if the phone model would no longer be supported, but since the update itself went well, and no warnings were logged, one wouldn't expect this to happen.

**Comment by SeanPM5** [comment]
Your phone model is still supported, this was just a bug that wasn't caught ahead of time, as it only affects iOS 12 users on devices without NFC.

A fix was already submitted (2020.5.1) and should be out soon.

**Comment by Mariusthvdb** [comment]
Yes! It's here, installed and all well.
Thanks
