### ISSUE TITLE
Lovelace reloading when re-opening app after short timeout

### ISSUE THREAD

**Issue by mountainsandcode** [home-assistant/iOS#899]
**iOS device model, version and app version**
Model Name: iPad Pro
Software Version: iPadOS 14 latest beta
App version: 2020.5.2

**Home Assistant Core Version**
Seeing this with 0.113.3 and 0.114

**Describe the bug**
When navigating away from the Home-Assistant app for a short-time (threshold seems to be something like 10 seconds), upon reopening the app it fully reloads the Lovelace interface, forcing a white loading screen. By contrast, when keeping the dashboard open in Safari, it remains in place when navigating to other tabs or even closing Safari for longer periods of time - thereby not interrupting the interface directly upon reopening the app

I can’t replicate on an iPhone XR running 13.6.2, so it may be related to how iPadOS/iOS 14 does backgrounding?

**To Reproduce**
Open HA
Minimize HA (i.e. navigate to Home Screen or other app)
Wait 10-15 seconds
Reopen HA

**Expected behavior**
Lovelace dashboards to be still visible and refresh in place, without white reloading screen

**Screenshots**
![1496D8A5-BFF2-4AE7-B3BA-F46E1B5EC256](https://user-images.githubusercontent.com/26942220/90076663-9e12eb80-dd00-11ea-96c1-e71e63ff3e89.png)

**Comment by zacwest** [comment]
It's not that it's reloading, it's that unfortunately the app is crashing. You can follow along here: #822
