### ISSUE TITLE
More elaborate colour picker for theme colours

### ISSUE THREAD

**Issue by bcmitri** [home-assistant/iOS#906]
**Is your feature request related to a problem? Please describe.**
Currently, the colour picker for theme colours offers limited choices and lacks the ability to specify RGB values (see below).

![image](https://user-images.githubusercontent.com/53234043/90284041-acb7ea80-de47-11ea-8f57-940e3b5dd7d2.png)

**Describe the solution you'd like**
Ideally, it would be more like the desktop version of the colour picker (see below).

![image](https://user-images.githubusercontent.com/53234043/90284102-c6593200-de47-11ea-9960-a663da23506a.png)

**Additional context**
The use case here is that I'm trying to use a custom theme for my "dark mode" and I want to match the primary colour of my default theme to it, so that I may make that my "light mode" theme.  This is ensures that the iOS status bar will always be the right colour, without refreshing.  And, while this is easy on a desktop browser (since I can specify a particular RGB value), I can only get "kinda close" on my iPhone, due to the limited colour choices.

**Comment by zacwest** [comment]
Could you provide a little bit more info about the status bar bit too? It should update to the correct color in 2020.5 when Dark Mode is toggled on or off.

**Comment by bcmitri** [comment]
Sorry for not being clear...

As I understand it, the dark mode feature still only gives you two different variations of the "default" theme.  As such, I'm still using automation to switch between a custom theme and the default theme (albeit, with new colours chosen).  While toggling dark mode on and off updates the status bar just fine, switching themes via frontend.set_theme will still only update it after a refresh.

**Comment by OverZealous** [comment]
I would like this too—if nothing else, it would be nice to be able to manually enter the color value even if the color picker continues to use the limited palette.
