### ISSUE TITLE
Pull in SensorKit information as sensors

### ISSUE THREAD

**Issue by zacwest** [home-assistant/iOS#917]
[SensorKit](https://developer.apple.com/documentation/sensorkit) lets us look up a bunch of information:

- accelerometer
- ambientLightSensor
- deviceUsageReport
- keyboardMetrics
- messagesUsageReport
- onWristState
- pedometerData
- phoneUsageReport
- rotationRate
- visits

**Comment by zacwest** [comment]
The framework's basically undocumented, and the most basic test -- requesting authorization -- crashes. The headers hint that an entitlement may be required, but none is available to access it.

**Comment by CCOSTAN** [comment]
This seems neat. 
`phoneUsageReport`

**Comment by zacwest** [comment]
It doesn't appear that this will ever be accessible. Apple has finally published some [guidelines on getting access](https://www.researchandcare.org/resources/accessing-sensorkit-data/) and it's extremely not aligned with our needs.
