### ISSUE TITLE
iOS 14 Widget: Logbook

### ISSUE THREAD

**Issue by zacwest** [home-assistant/iOS#918]
Show the past few entries in the Logbook, deeplink to the entity in question.

**Comment by ibru** [comment]
Hello @zacwest . I'd like to take a look into this.

I guess in this task I need to:
-  create a iOS 14 widget which will show simple list (Is there any UI designs for it?)
- the list must be driven data from my HA device. How do I get them? Should I use some API request?

**Comment by zacwest** [comment]
The design should probably be modeled after what the frontend version of the logbook looks like. The API is documented on [developers.home-assistant.io](https://developers.home-assistant.io/docs/api/rest).

**Comment by zacwest** [comment]
Rough strokes of what's needed for this:
- Create a new widget in the widget extension. You can use a StaticConfiguration for this one -- it doesn't need Intent-based configuration, so you can skip editing the intentdefinition file.
- Add API calls to the HomeAssistantAPI class which can call the Logbook API referenced above. Use ObjectMapper to create a model representation of the response and it should parse manually.
- In your timeline provider for the widget, invoke the API and stuff the data into the widget.
- Create the widget UI in SwiftUI for the logbook widget.

**Comment by ibru** [comment]
Thanks. This should be sufficient information for now.

Since this will be kind of separated part of the app I could use some design pattern such as MVVM even though it is not used in main app. Do you prefer me to use some of this?
Also I'd use Combine since it works well with SwiftUI. Do you agree?

**Comment by zacwest** [comment]
I believe you can create a VM for the Logbook widget based on the log details to compute what is visible, that should
be okay. Feel free to post model interfaces and we can talk through their features.

Please stick to PromiseKit for any async delivery of details. We may end up skipping combine and going right to coroutines.

**Comment by ibru** [comment]
Created pull request to get Logbook data from API #1481
