### ISSUE TITLE
iOS 14 Widget: Shopping List

### ISSUE THREAD

**Issue by zacwest** [home-assistant/iOS#919]
Show the first few Shopping List entries, deeplink to the Shopping List page whenever any part of the widget is tapped.

For APIs available for this, see #909

**Comment by jbehrens94** [comment]
Hi @zacwest, can you assign this to me, please?

**Comment by SeanPM5** [comment]
Just assigned you @jbehrens94, thanks for looking into this. If you have any questions you can hop in #devs_mobile_apps chat in the [Home Assistant Discord server](https://discord.gg/c5DvZ4e) and someone might be able to help.

**Comment by jbehrens94** [comment]
Awesome, I'll probably spend some time on this feature tonight :)
