### ISSUE TITLE
Create/update a custom sensor via Shortcut

### ISSUE THREAD

**Issue by zacwest** [home-assistant/iOS#922]
There's a few things we can't do in the public API world, such as a sensor for alarm, bluetooth connectivity status, do not disturb status.

However, it is possible to make a Shortcut for this information. If we create a Shortcut intent which updates a custom sensor, we can share Shortcut Gallery items with the user that can be a one-tap setup to get this information into HA, from within the app.

**Comment by TomW1605** [comment]
has any progress been made on this?
