### ISSUE TITLE
2020.5.2 app login issues (iOS 14.0)

### ISSUE THREAD

**Issue by devopsleigh** [home-assistant/iOS#927]
The app update forced me to reconnect, however:

1. The password manager (Bitwarden in my case) pop up doesn’t appear. This is the case with Safari naively as well.
2. I cannot paste into the password field. This works just fine natively in Safari.
3. Every time I switch apps to get passwords (or OTP, if I could get that far), the HA app resets and I have to start all over again.
4. I tried force closing and reinstalling the app, but the result was the same.

At this point my only option is to enter my password with the aid of another screen, and I don’t know how I’d get my OTP entered since I’d have to switch apps on my phone.

**Comment by TomBrien** [comment]
Hi, Points 2 and 3 are duplicates of #823 and #832 respectively. On Point 1, I suggest you [open an issue on the frontend repo](https://github.com/home-assistant/frontend/issues/new?labels=bug&template=BUG_REPORT.md) as you see the same behaviour in Safari. As these are duplicates I am going to close this issue. However, as your are running the iOS 14 beta you should be aware of #925, this is in part what you are seeing in point 3 as well I believe.
