### ISSUE TITLE
Connect via Cloud keeps on disabling itself 

### ISSUE THREAD

**Issue by CarbonCollins** [home-assistant/iOS#932]
**iOS device model, version and app version**

Model Name: iPhone 11
Software Version: 13.6
App version: 2020.5.2 (1)

**Home Assistant Core Version**
0.114.2

**Describe the bug**
Currently when I leave my home and attempt to access my HA instance through the app i get a connection failed message due to the connection URLS being changed and the `Connect via Cloud` option being disabled. This has happened multiple times now after I have set up the app to use my internal URL in the `Internal URL` field under connection settings and have enabled `Connect via Cloud`. Once the bug occurs the address i entered into the `Internal URL` is now in the `External URL` field and `Connect via Cloud` is disabled. I am unsure of how much time has passed since initially updating the settings to when the bug occurs but its normally when I am at work wanting to do something at home. Though as a side effect my presence detection is flaky as the app is unable to update my GPS position in my HA instance so it always thinks i am home!

**To Reproduce**
HA setup in python environment with TLS/HTTPS and with Nabu Casa cloud account connected and enabled.
A local DNS with internal FQDN (all instances and services in my internal network have FQDN and TLS/HTTPS for all connections)

Enter the FQDN for the ha instance in the `Internal URL` field e.g. `https://ha.example.com:8123`
Specify the home SSID for when to use the `Internal URL`
Leave `External URl` blank.
Enable `Connect via Cloud`

**Expected behavior**
`Connect via Cloud` is not disabled, `Internal URL` is not switched to being the `External URL` and I am still able to connect to my HA instance when outside of my internal network

**Additional Information**
This has been happening across multiple previous versions of by the app and ha core. I tend to update the app as soon as a new update is released and HA at least once a week (assuming there is an update). I've been noticing the issue for a couple of months at least but because I seldom access my HA instance from outside my home I don't notice how long its been disconnected. Though the people I live with occasionally ask why HA says I am home when I am not which also alerts me to the issue...

This does also seem to affect some other people in the house who are using the iOS app on different iPhones.
One is using an iPhone SE running iOS 13.5.1 with app version of 2020.5.2 (1)
Another is using an iPhone 8 running iOS 13.4.0 with app version 2020.5.2 (1)

**Comment by cratermaddie** [comment]
Also having this issue on both my iPhone Xs and my bf's iPhone 7. Very frustrating....

**Comment by mountainsandcode** [comment]
@cratermaddie @CarbonCollins, did the release of 2020.6 fix your problems?

**Comment by CarbonCollins** [comment]
@mountainsandcode, i’m running 2020.6.2 (1) at the moment and have not noticed this issue occurring yet. I haven't had it occur for a little while now 👍

**Comment by SeanPM5** [comment]
Thanks for reporting back. I haven't seen this reoccur on my setup either since the 2020.6 release, so closing as fixed.

If it happens again just drop a comment here (and I'll reopen) or create a new issue.
