### ISSUE TITLE
Mac devices are reported as "x86_64" in device registration

### ISSUE THREAD

**Issue by zacwest** [home-assistant/iOS#939]
<img width="339" alt="image" src="https://user-images.githubusercontent.com/74188/91110602-2b283f80-e633-11ea-9ba4-031cb0129035.png">

**Comment by cadavre** [comment]
Why is it a bug? It's Apple devices current architecture. Haven't moved to ARM yet. :p

**Comment by zacwest** [comment]
The appropriate name here would be a.g. MacBookPro8,2 or whatnot.
