### ISSUE TITLE
JS unexpected exception thrown when trying to open HA macOS app from menu bar

### ISSUE THREAD

**Issue by cadavre** [home-assistant/iOS#942]
**iOS device model, version and app version**

Model Name: iMac Retina 5K 2017
Software Version: macOS 10.15.6
App version: alpha

**Home Assistant Core Version**
0.114.0

**Describe the bug**

When I open the app it doesn't load Lovelace. When I close it and try to open it from top menubar, it gives me:

**A JavaScript error occurred in the main process**

```
Uncaught Exception:
TypeError: Cannot read property 'isVisible' of null
    at Tray.<anonymous> (/Users/cadavre/Development/HASS/HomeAssistantElectron/dist/mac/Home Assistant.app/Contents/Resources/app/index.js:122:27)
    at emitThree (events.js:136:13)
    at Tray.emit (events.js:217:7)
```

**To Reproduce**
Don't know.

**Expected behavior**
Open the app with lovelace and don't throw error.

**Additional context**
I was able to open the app at the first time, authorize, access Lovelace – all was fine. Second window open was ok but loaded lovelace with another theme. Third time, 3h later, it doesn't load.

**Comment by zacwest** [comment]
Can you confirm which app you're running? This very much appears to be an Electron app of some sort, but the Mac app from this repo is not Electron-based.

**Comment by robbiet480** [comment]
Closing this as its generated from another app (https://github.com/matthinc/HomeAssistantElectron)
