### ISSUE TITLE
Sensor for whether the camera is on or not

### ISSUE THREAD

**Issue by zacwest** [home-assistant/iOS#944]
Can be useful for e.g. changing a light or other switch when on a call.

**Comment by robbiet480** [comment]
Merged but more to do. Should get live updates going.

Next version of this should monitor for camera state changes and update sensors. Example implementations:

* [stackoverflow.com/questions/42681127/coremediaio-incorrectly-updated-properties-kcmiodevicepropertydeviceisrunningso?rq=1](https://stackoverflow.com/questions/42681127/coremediaio-incorrectly-updated-properties-kcmiodevicepropertydeviceisrunningso?rq=1)
* [wouterdebie/onair@`52f2ea0`/Sources/onair/Camera.swift](https://github.com/wouterdebie/onair/blob/52f2ea0b72793e1eee0f64478bc7c3a87c094a02/Sources/onair/Camera.swift)
* [jakobwesthoff/on-air-notifier@`de4a579`/on-air-notifier/CameraWatcher.swift](https://github.com/jakobwesthoff/on-air-notifier/blob/de4a5794c561be510b1a0537f229f03fbb6e6635/on-air-notifier/CameraWatcher.swift)
* [lvsti/Cameo@`79d0037`/CameoSDK/Property.swift](https://github.com/lvsti/Cameo/blob/79d0037e839807b08e590cd7f8027e1a163aa456/CameoSDK/Property.swift)

[Cameo](https://github.com/lvsti/Cameo) shows the following data about cameras is provided by the system. If anything else looks interesting I can expose it as attributes:

<img width="1643" alt="image" src="https://user-images.githubusercontent.com/18516/91372478-97887780-e7c8-11ea-918b-8cc5a5498bd8.png">
