### ISSUE TITLE
Sensor for whether Do Not Disturb (Focus on iOS 15/macOS 12) is on or not

### ISSUE THREAD

**Issue by zacwest** [home-assistant/iOS#945]
- [x] Sensor reporting, permission in settings
- [x] Onboarding updates to request permission during connecting
- [ ] Prompt when upgrading to iOS 15

**Comment by robbiet480** [comment]
As per https://github.com/sindresorhus/do-not-disturb we can only get DND status if we aren't in sandbox.

**Comment by zacwest** [comment]
I have been unable to find any mechanism to get this information while sandboxed.

**Comment by fi-sch** [comment]
Could it be possible to get DND (or Sleep Mode) status from Apple Watch?

**Comment by zacwest** [comment]
I do not believe that is publicly knowable on either the watch or the paired phone.

**Comment by zacwest** [comment]
There is now Public API for this in iOS 15: [`INFocusStatusCenter`](https://developer.apple.com/documentation/sirikit/infocusstatuscenter).
