### ISSUE TITLE
MacOS app – ability to move app to the Menu Bar

### ISSUE THREAD

**Issue by fi-sch** [home-assistant/iOS#949]
**Is your feature request related to a problem? Please describe.**
Updating sensor does not work when app is turned off. On the other hand app does space in the Dock (additional icon) when you don't use it. You need to remember to launch it manually as well, and also remember to not close the window but minimize it instead – otherwise app would be terminated. [That last one is already solved.]

Actions are not quickly accessible too – I need to open app window and only then I can click 'Actions' on Menu Bar and select one. That's at least 3 clicks and a lot of eye and mouse movement.
 
**Describe the solution you'd like**
1. I'd like to be able to move this app to Menu Bar and keep it there (maybe some setting – Dock / Menu Bar / both). Actions could be easily triggered from there also – just two clicks, even if they would be nested in some submenu.
2. An option to make app autostart (on system boot / user login) would be highly appreciated.
3. Closing app window shouldn't close the app. [That's already solved]

**Describe alternatives you've considered**
If moving an app from the Dock entirely is not possible with Catalyst app, it maybe can exist both in the Dock and as a Menu Bar icon – for easy access to actions.
Also, maybe there's a possibility to update sensors even if app is not running.

**Comment by ntompson** [comment]
I note that this and #1126 are closed - is that to say that this is done? I find that sensors stop updating when I close the app.

**Comment by zacwest** [comment]
This ticket is not closed. Pulling the app into the menu bar (and _not_ remaining in the Dock) in a way that will allow the app on the Mac App Store is a pretty substantial project. Putting something in the menu bar that's in addition to the Dock is somewhat easier.

**Comment by ntompson** [comment]
Sorry Zac - I saw the closed badge on the reference to #1126 without noticing the open badge on this one at the top of the page. Understand it's not a simple job. Love your work.

**Comment by vpicone** [comment]
This would be amazing!! I think it might be easier to learn swift and try contributing this feature than to get my partner to remember to launch the app every time their computer restarts.

**Comment by zacwest** [comment]
Idea: command and entity feature shows up in a searchable thing in native UI there.

**Comment by fi-sch** [comment]
> Idea: command and entity feature shows up in a searchable thing in native UI there.

Good idea. Maybe it would be even possible to integrate with Spotlight?

**Comment by zacwest** [comment]
So I don't forget:

1. Add a setting to control [`NSApp.setActivationPolicy(_:)`](https://developer.apple.com/documentation/appkit/nsapplication/1428621-setactivationpolicy#)
2. Add an NSStatusItem using … magic … in the Mac Bridge
3. Figure out how to make the status item in the Bridge open Catalyst windows
4. Create a helper app to launch the main app, make it the "open on login" helper app
