### ISSUE TITLE
Create a sensor with a list of currently attached Bluetooth devices in order to make location updates more timely

### ISSUE THREAD

**Issue by jschwalbe** [home-assistant/iOS#956]
**Is your feature request related to a problem? Please describe.**
I'd like to improve the timeliness of GPS updates without using so much battery by watching the list of connected bluetooth devices (esp my car!).

**Describe the solution you'd like**
I don't know if this is possible with public API, but here's a scenario I am seeing:
1. I leave work, hop in my car and automatically the iPhone links up with my car via bluetooth
2. the iOS app takes note of this and updates the sensor in HA
3. either via automation or setting in the app, this triggers a location update

**Comment by zacwest** [comment]
Unfortunately the available Bluetooth APIs on iOS don't allow us access to this information, especially if we want to operate in the background. I suggest checking out the Shortcuts.app's automations which you can use as triggers for HA Shortcuts.

**Comment by danielgospodinow** [comment]
@bgoncal, do you think this is still the case? Could it be possible to now access iOS APIs for Bluetooth information?

**Comment by bgoncal** [comment]
@danielgospodinow There is still no API directly for that, it's possible to use bluetooth APIs to achieve this objective, but this may use a lot of battery and also won't be available in background.

**Comment by danielgospodinow** [comment]
Thanks for the update, @bgoncal! Makes sense.

**Comment by timokluser-dev** [comment]
hey there
as a few years have passed - is there an update on this one?

**Comment by bgoncal** [comment]
I haven't look into it anymore, I don't have availability right now, but if someone want to investigate (even if its using AI) and propose a small sample project that validates the idea, this then can be considered.
