### ISSUE TITLE
Enable/Disable sensors in app

### ISSUE THREAD

**Issue by olbjan** [home-assistant/iOS#957]
**Is your feature request related to a problem? Please describe.**

In some cases it is undesirable to have any sensors from apps, eg. an pffice install. There is no point to collect sensor data of endpoints not relevant to the functioning of the HA install and it may be a privacy issue for users.

**Describe the solution you'd like**
In the sensors list add a checkbox to enable/disable sensors, ideally removing/adding entities to HA when toggled.

From a privacy first perspective make any and all sensors an opt-in during onboarding.

**Describe alternatives you've considered**

**Additional context**

**Comment by zacwest** [comment]
#358
