### ISSUE TITLE
Preferences doesn't list app version

### ISSUE THREAD

**Issue by TomBrien** [home-assistant/iOS#970]
**Device model, version and app version**

Model Name: MacBook Pro (retina, 13-inch, Early 2015)
Software Version: 11.0b5
App version: Well there in lies the problem 😉

**Home Assistant Core Version**

N/A but 0.114.4 

**Describe the bug**
The preferences (aka app configuration) does not have the 'About' section which should contain the app version

**To Reproduce**
Open the app preferences 

**Expected behavior**
To be able to access the app version

**Screenshots**

**Additional context**

**Comment by TomBrien** [comment]
Just left home and realised it's going to be in help now isn't it

**Comment by zacwest** [comment]
Application menu > About will get you the iOS-side App Configuration > About UI.
