### ISSUE TITLE
macOS App - Don't create battery sensors for devices with no batteries.

### ISSUE THREAD

**Issue by joshtbernstein** [home-assistant/iOS#992]
**Device model, version and app version**

Model Name: Mac mini (2018)
Software Version: 10.15.6
App version: 2020.6 (13) (♥️ you too)

**Home Assistant Core Version**

0.114.4

**Describe the bug**
The following sensors are created on a device that does not have a battery:
sensor.joshs_mac_mini_battery_level
sensor.joshs_mac_mini_battery_state

**To Reproduce**
Install macOS app on a Mac mini (and I'm assuming an iMac or Mac Pro).

**Expected behavior**
Those two sensors would not be created since there is no battery in the device.

**Screenshots**

![Screen Shot 2020-09-07 at 6 24 34 PM](https://user-images.githubusercontent.com/13294526/92423851-6b111b80-f137-11ea-9f0a-191f565f7b35.png)

**Additional context**

I understand that this borders on being a feature request and understand if that's what it ends up being.

**Comment by joshtbernstein** [comment]
@zacwest How is this supposed to look in the UI? I'm happy to test/provide feedback. I removed the old sensors, loaded the new app and it looks the same.

![Screen Shot 2020-09-12 at 8 07 13 PM](https://user-images.githubusercontent.com/13294526/93009270-962ead00-f533-11ea-9687-a5511e589896.png)

**Comment by zacwest** [comment]
Can you show me what the sensors look like in the Application > Preferences… > Sensors list? What attributes are on the sensors there?

**Comment by joshtbernstein** [comment]
Strange, they don't show up there. I'm happy to remove the integration and try again?

**Comment by zacwest** [comment]
If they don't show up there, my guess is those are still the sensors left over from the previous app _or_ they loaded temporarily at some point. Disabling them again should make them stop showing up, but if they do the logs would be useful to check out in Application > Preferences > Show Logs in Finder.

**Comment by joshtbernstein** [comment]
I removed it and added it again and they didn't come back, so I think this is good. Thanks!
